### ISSUE TITLE
 divide-by-zero error in eta.c by calc_rate() and calc_iops()

### ISSUE THREAD

**Issue by zixuanhe** [axboe/fio#100]
When both --eta=always and --output-format=json are enabled, it seems
get_jobs_eta() in show_thread_status_json() may be invoked shortly
after get_jobs_eta() from print_thread_status(), such that disp_time
in calc_thread_status() may be less than 1ms, and thus rounded to 0.

Since get_jobs_eta() is forced for json output, calc_rate() and
calc_iops() may crash due to divide-by-zero error.

**Comment by axboe** [comment]
Thanks, should be fixed in current -git.
