### ISSUE TITLE
Runtime not respected in the case of slow or hung device

### ISSUE THREAD

**Issue by mofahead** [axboe/fio#1004]
Platform: Linux 4.15, 5.3, 5.6
Fio version: 3.19

First let me thank you for the fantastic work you've done on this project.

I'm using fio to test removable media that occasionally responds slowly or even hangs, and fio will hang as well even if a short runtime is set. See the long ETA in the simple example below:

```
$ fio --direct=1 --filename=/dev/sdb --runtime=10 --name=R-seq-1M --rw=read --bs=1m --numjobs=1
R-seq-1M: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=psync, iodepth=1
fio-3.19
Starting 1 process
Jobs: 1 (f=1): [R(1)][0.0%][eta 03d:11h:30m:28s]
```
It seems like ideally fio would exit when the runtime was reached. But reading issue #550, I'm wondering if fio itself can't do much in this case? If so, is there an ioengine on the Linux platform that would be less prone to this sort of hang, or is there a recommended workaround?

**Comment by axboe** [comment]
You'd have to check ```ps aux``` and see what the state of the fio process(es) is. If it's in D state, then there's nothing fio can do to exit, it's blocked in the kernel.

**Comment by mofahead** [comment]
Unfortunately that seems to be the case. 

```
$ ps aux | grep fio
root     20785  0.0  0.0  72708  4280 pts/0    S+   18:37   0:00 sudo fio --direct=1 --filename=/dev/sdb --runtime=10 --name=R-seq-1M --rw=read --bs=1m --numjobs=1
root     20786  0.3  6.9 1389832 1129336 pts/0 Sl+  18:37   0:04 fio --direct=1 --filename=/dev/sdb --runtime=10 --name=R-seq-1M --rw=read --bs=1m --numjobs=1
root     20792  0.0  0.0 1325332 3172 ?        Ds   18:37   0:00 fio --direct=1 --filename=/dev/sdb --runtime=10 --name=R-seq-1M --rw=read --bs=1m --numjobs=1
```
I imagine the best bet would be to have an observer process try to kill the fio process if it hung for too long, although it seems that the blocked kernel process can't always be killed. I've found that physically disconnecting the drive will cause fio to return almost immediately, although I'd obviously prefer to avoid that if possible.

**Comment by axboe** [comment]
You can't kill a process in D state, the very definition if it is uninterruptible sleep. That means that signals are blocked for that process. There's nothing fio can do here.

**Comment by mofahead** [comment]
Okay, that makes sense, thanks for clarifying.
