### ISSUE TITLE
fio 3.20 failed to build on OSX 10.15

### ISSUE THREAD

**Issue by chenrui333** [axboe/fio#1006]
relates to https://github.com/Homebrew/homebrew-core/pull/55163

```
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fio] Error 1
```

**Comment by sitsofe** [comment]
Sounds like a bug in XCode - https://github.com/curl/curl/issues/5210 ...

**Comment by sitsofe** [comment]
For some history, the disabling of weak symbols was introduced with ccf2d89d39b21bc8c7b497b40be5b82eadb80863 . I'm not quite sure how Apple hope for people to use `-Wl,-no_weak_imports` if they are using it for internal symbols seemingly generated by the system headers. Also see the discussion on https://github.com/mono/mono/issues/19393 ...

**Comment by Thomasdezeeuw** [comment]
For anyone who also hits this issue, my work around was to remove the `no_weak_imports` option here: https://github.com/axboe/fio/blob/8bfe330eb42739d503d35d0b7d96f98c5c544204/configure#L370-L373

As macOS 10.15.7 and Xcode 12.0.1 still have this problem it might be worth it to add work-around for macOS for this.

**Comment by sitsofe** [comment]
@Thomasdezeeuw you raise a fair point. If Apple decide to keep this behaviour in the XCode used for Big Sur then we too should change. We can go back to the comment in ccf2d89d39b21bc8c7b497b40be5b82eadb80863 and try `-Werror=partial-availability`...

**Comment by chenrui333** [comment]
Is there any patch that I can try with for fio 3.25 build?

**Comment by sitsofe** [comment]
@chenrui333 Hi! Just above your latest comment:

> **sitsofe** added a commit to sitsofe/fio that referenced this issue 3 days ago
> configure: fix compilation on recent macOS Xcode versions … b6a1e63

So you could try the patch linked there. Failing that you could trythe suggestion in https://github.com/axboe/fio/issues/1006#issuecomment-714502389 ...

**Comment by sitsofe** [comment]
(FWIW also see the pull request over in https://github.com/axboe/fio/pull/1154 )
