### ISSUE TITLE
cross compile on Android fail

### ISSUE THREAD

**Issue by OceanOhen** [axboe/fio#1008]
I compile fio for Android and use the following command.
UNAME=Android CROSS_COMPILE=/home/oceanchen/codebase/tool/android-toolchain/bin/arm-linux-androideabi- CC=/home/oceanchen/codebase/tool/android-toolchain/bin/arm-linux-androideabi-clang ./configure
make
Then, I got these error logs.

FIO_VERSION = fio-3.20-21-g00ca8
    CC init.o
  LINK fio
zbd.c:38: error: undefined reference to 'blkzoned_get_zoned_model'
zbd.c:72: error: undefined reference to 'blkzoned_report_zones'
zbd.c:105: error: undefined reference to 'blkzoned_reset_wp'
clang90: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:483: fio] Error 1

And I found Makefile lost oslib/linux-blkzoned.c.
I added these to pass compile, but I'm not sure it's the true answer.
diff --git a/Makefile b/Makefile
index e3962195..7eb5e899 100644
--- a/Makefile
+++ b/Makefile
@@ -176,6 +176,9 @@ endif
 ifeq ($(CONFIG_TARGET_OS), Android)
   SOURCE += diskutil.c fifo.c blktrace.c cgroup.c trim.c profiles/tiobench.c \
                oslib/linux-dev-lookup.c
+ifdef CONFIG_HAS_BLKZONED
+  SOURCE += oslib/linux-blkzoned.c
+endif
   LIBS += -ldl -llog
   LDFLAGS += -rdynamic
 endif
Please help this :)

**Comment by axboe** [comment]
I've turned that into a real patch, please git pull and verify it works for you.
