### ISSUE TITLE
Is it possible to build a 32-bit FIO running on arm64(Android)?

### ISSUE THREAD

**Issue by WangDacan** [axboe/fio#1009]
I have a android device, which only support 32-bit app. So I want to confirm does this project support to build a 32-bit FIO for arm64? If it support, is there a recommended method? 
Thx!!

**Comment by sitsofe** [comment]
@WangDacan I would imagine this is entirely down to your compiler and the libraries available. I personally don't do 32 bit ARM builds (or Android for that matter) so I can't help you with the details but I see no reason why it should work so long as you have a **32 bit ARM build environment targeting Android**.

If what you're saying is "how do I build a 32 bit ARM app when all I have is a 64 bit ARM build environment" then that's a general issue that would apply to any "app" and not just to fio. In your case (Android) you need to talk to your toolchain vendor (Google?) for instructions as there may be caveats (hint: maybe older Android toolchains defaulted to 32 bit only?).

As this isn't so much an issue in fio and more of a "How do I/Why is?" question is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.19/README#L58) (note that the list only accepts plain text emails). I'll close this here for now.
