### ISSUE TITLE
static build for Android fail

### ISSUE THREAD

**Issue by OceanOhen** [axboe/fio#1010]
Hi
When I try to build a static fio for Android, I got these error logs.
$ EXTFLAGS="-static" make
  LINK fio
ocean/codebase/tool/android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
clang90: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:486: fio] Error 1

**Comment by OceanOhen** [comment]
UNAME=Android CROSS_COMPILE=/usr/local/google/home/oceanchen/codebase/tool/android-toolchain/bin/arm-linux-androideabi- CC=/usr/local/google/home/oceanchen/codebase/tool/android-toolchain/bin/arm-linux-androideabi-clang ./configure --build-static
it also gets the same error log

**Comment by axboe** [comment]
This is a toolchain/library issue, not a fio problem. You don't have a static version of the log library. Sorry can't really help with that, I don't have any experience with building for Android, but probably google a bit and see where you can find a static log library.

**Comment by OceanOhen** [comment]
If I remove that, is it impact a lot ?

**Comment by axboe** [comment]
If you remove -llog? If it links with that removed, then you don't need it, and it should be fine like that.

**Comment by OceanOhen** [comment]
Yep, I tried to remove the '-l log'. And the compile process can pass. I just wonder what function will be changed.

**Comment by axboe** [comment]
If it links without that, then it's not used and you have nothing to worry about. Here's the commit that added the log library to the Android build:

```
commit ad3e7e97780c406fca5afa56239b2a6b71cf6277
Author: Danny Lin <danny@kdrag0n.dev>
Date:   Sun Oct 20 18:43:08 2019 -0700

    Makefile: Link to the system logging library on Android
    
    Android replaces syslog calls with calls to the Android system logging
    library, liblog. Link to liblog when compiling for Android to fix the
    following undefined reference errors:
    
    aarch64-linux-android-ld: log.o: in function `android_polyfill_vsyslog':
    /usr/include/syslog.h:185: undefined reference to `__android_log_print'
    aarch64-linux-android-ld: /usr/include/syslog.h:182: undefined reference to `__android_log_vprint'
```

**Comment by OceanOhen** [comment]
thank a lot :)
