### ISSUE TITLE
Some io engine is not supported

### ISSUE THREAD

**Issue by ChanChunSong** [axboe/fio#1012]
I found os-android.h didn't define some io engine such as pvsync2 and libaio. How do I enable these io engines or how do I know these engines are enabled by others?

**Comment by sitsofe** [comment]
@OceanOhen did my comment above make sense?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by ChanChunSong** [comment]
Sorry for late reply. I can build pass by installing the libaio by building the Android version of libaio.
Thanks for your reminder :)
