### ISSUE TITLE
FI/O measurements on virtual NVMe device

### ISSUE THREAD

**Issue by ShaoTziYang** [axboe/fio#1027]
Hi,

I am running FIO on a virtual NVMe device on QEMU environment.
The virtual device is running using nvme linux kernel driver, bandwidth is expected to be low since NVMe device is running on simulated code.

Here is the run result, the fio is run with one signal nvme write with 4k width and 4k size using libaio ioengine:

seq-write: (g=0): rw=write, bs=4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio 1.59
Starting 1 process

seq-write: (groupid=0, jobs=1): err= 0: pid=1589
  write: io=4096 B, bw=4357 B/s, iops=1 , runt=   940msec
    slat (usec): min=13677 , max=13677 , avg=13677.00, stdev= 0.00
    clat (usec): min=926147 , max=926147 , avg=926147.00, stdev= 0.00
     lat (usec): min=939831 , max=939831 , avg=939831.00, stdev= 0.00
    bw (KB/s) : min=    4, max=    4, per=100.00%, avg= 4.00, stdev= 0.00
  cpu          : usr=0.00%, sys=1.38%, ctx=2, majf=0, minf=21
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued r/w/d: total=0/1/0, short=0/0/0

     lat (msec): 1000=100.00%

Run status group 0 (all jobs):
  WRITE: io=4KB, aggrb=4KB/s, minb=4KB/s, maxb=4KB/s, mint=940msec, maxt=940msec

Disk stats (read/write):
  nvme0n1: ios=0/1, merge=0/0, ticks=0/0, in_queue=1388, util=100.00%

--debug=all is turned on, from the print message, I observed that bandwidth is measured after completion of transactions are received. However, from the debug message of our simulated device, it looks like multiple NVMe read transactions are observed after the fio-generated NVMe write. Where do the read transactions come from and why are those transactions generated?

**Comment by axboe** [comment]
Probably a system level activity that'll re-probe partitions when the device has been opened for write / written to. I'd check for udev or something like that. This isn't a fio issue, it's not fio doing the reads.
