### ISSUE TITLE
Getting error while installing Time::Hires module with MacOS Catalina (10.15.5)

### ISSUE THREAD

**Issue by Rohitoracleindia** [axboe/fio#1029]
HiRes.xs:102:13: error: typedef redefinition with different types ('int' vs 'enum clockid_t')
typedef int clockid_t;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/time.h:172:3: note: previous definition is here
} clockid_t;
  ^
1 error generated.
Reaping losing child 0x7fe543404690 PID 39032
make: *** [HiRes.o] Error 1
Removing child 0x7fe543404690 PID 39032 from chain.

**Comment by axboe** [comment]
What version of fio is this

**Comment by sitsofe** [comment]
@Rohitoracleindia What version of XCode are you using?

**Comment by Rohitoracleindia** [comment]
@axboe fio version: fio-3.19
@sitsofe XCode : 11.5 (11E608c)

**Comment by sitsofe** [comment]
@Rohitoracleindia I don't know how you're getting this as there's a test during configure to pick this up. What's the output of running `./configure`on your machine? Also just to check - are you working with pristine unpatched fio git source (and if so which hash)?

**Comment by sitsofe** [comment]
I can't reproduce this with the latest fio git master and 11.5.0.0.1.1588476445 of XCode command line tools on 10.15.5 (19F101). However I do trigger #1006 but that's not what's being reported here...

**Comment by Rohitoracleindia** [comment]
Hi, I am trying to configure version control using p4v command line and getting this issue. I tried to install Time::Hires module using cpan but no luck. Not sure of this can help here or not but wanted to give some clue.

**Comment by sitsofe** [comment]
@Rohitoracleindia Sorry I don't follow. The fio source https://github.com/axboe/fio has a configure script within it and is easily fetchable from git from the aforementioned location (`git clone https://github.com/axboe/fio` and you're done). If you cd into the fio directory you can run configure by just doing `./configure` and no extras are required. Where are you getting the source for fio from and what git hash does it correspond to? We (upstream) don't use perforce so it's all sounding strange...

**Comment by Rohitoracleindia** [comment]
Hello, I am able to resolve the issue. Actually issue was with path and after setting the path I was able to build the Time::Hires module.

Sorry for bothering you.

export CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
