### ISSUE TITLE
Questions about FIO testing NFS disks

### ISSUE THREAD

**Issue by cscowx** [axboe/fio#1030]
Questions about FIO testing NFS disks

fio -directory=/test/ -name=write.txt -direct=1 -iodepth 32 -thread -rw=write -ioengine=libaio -bs=4k -size=1G -numjobs=30 -group_reporting -ioscheduler=none -name=test

The /test directory is mounted over the NFS protocol

I follow the following FIO command and always report an error：

write.txt: Laying out IO file (1 file / 1024MiB)
write.txt: Laying out IO file (1 file / 1024MiB)
**test: you need to specify size=**
fio: pid=0, err=22/file:filesetup.c:950, func=total_file_size, **error=Invalid argument**
Segmentation fault (core dumped)
You have mail in /var/spool/mail/root

How can I test NFS disk performance with FIO?
Can you give me an example? Thank you!

**Comment by sitsofe** [comment]
Hi @cscowx :
```
fio -directory=/test/ -name=write.txt [...] -name=test
```

I think your double dashes have been eaten but do you know each name section starts a new job (see https://fio.readthedocs.io/en/latest/fio_doc.html#job-file-format)? You've made an empty job called "test" at the end...

As this isn't so much an issue in fio and more of a "How do I/Why is?" question it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.19/README#L58) (note that the list only accepts plain text emails).

**Comment by sitsofe** [comment]
@cscowx did this help?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
