### ISSUE TITLE
Add option to allow use of O_DSYNC (rather than O_SYNC).

### ISSUE THREAD

**Issue by anarazel** [axboe/fio#1033]
Hi,

Using O_DSYNC has obvious advantages over O_SYNC, but right now it can't be benchmarked with fio. Would you accept a patch that either allows sync/dsync as parameters for --sync or adds a new --dsync?

Thanks

**Comment by axboe** [comment]
Yeah I think that'd be fine. If it turns out clean enough to turn "sync" into a posval kind of setup where "dsync" becomes a valid option, than that'd be best. If not, then I guess adding "dsync" would be the next best thing.

**Comment by fxober** [comment]
Is this feature merged, there is a use case at Intel we would like to test?

**Comment by axboe** [comment]
Andres, did you ever write that patch?

**Comment by anarazel** [comment]
I did write and use it locally. Probably needs a bit more polish.... See PR...
