### ISSUE TITLE
dprint logs

### ISSUE THREAD

**Issue by selvakumars3** [axboe/fio#1041]
I have introduced the new fio engine , where I  have included "dprint " statement for the additional logs . when we run fio binary where do I see the logs update?

**Comment by vincentkfu** [comment]
Run fio with the --debug=X1,X2,... option to see the X1 and X2 debug prints. Run fio --help to see the different types of debug output available.

**Comment by selvakumars3** [comment]
> Run fio with the --debug=X1,X2,... option to see the X1 and X2 debug prints. Run fio --help to see the different types of debug output available.

Thanks vincet for the quick reply. I am not able to find more options on --debug. Could you please clarify?

**Comment by vincentkfu** [comment]
I would find the existing ioengine most similar to what you need and use it as a foundation for your new ioengine. Consider running with --debug=io and using dprint(FD_IO, "debug statements\n"); for your debug prints.
