### ISSUE TITLE
No I/O performed by ioengine, perhaps try --debug=io option for details?

### ISSUE THREAD

**Issue by selvakumars3** [axboe/fio#1042]
Hi,
I have added a new fio engine , however I have implemented required functions , when I run the  fio I see no I/O performed. My question is how to populate the I/O so that while print IOPS it can print this.
Relevant log,
[root@sji4wvaw0027-rp selvaku1]# /usr/local/bin/fio --debug=io  pcie.fio
fio: set debug option io
io       57711 load ioengine dummyioengine
file1: (g=0): rw=randread, bs=(R) 64B-64B, (W) 64B-64B, (T) 64B-64B, ioengine=dummyioengine, iodepth=1
io       57711 load ioengine dummyioengine
io       57711 load ioengine dummyioengine
io       57711 load ioengine dummyioengine
...
fio-3.10-dirty
Starting 4 processes
file1: Laying out IO file (1 file / 1MiB)
io       57711 declare unneeded cache /home/file1.0.0: 0/1048576
file1: Laying out IO file (1 file / 1MiB)
io       57711 declare unneeded cache /home/file1.3.0: 0/1048576
file1: Laying out IO file (1 file / 1MiB)
io       57711 declare unneeded cache /home/file1.2.0: 0/1048576
file1: Laying out IO file (1 file / 1MiB)
io       57711 declare unneeded cache /home/file1.1.0: 0/1048576
io       57778 declare unneeded cache /home/file1.0.0: 0/1048576
io       57780 declare unneeded cache /home/file1.2.0: 0/1048576
io       57779 declare unneeded cache /home/file1.3.0: 0/1048576
io       57781 declare unneeded cache /home/file1.1.0: 0/1048576
io       57778 fill: io_u 0x15c11c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
io       57780 fill: io_u 0x15c11c0: off=0x191c0,len=0x40,ddir=0,file=/home/file1.2.0
io       57778 prep: io_u 0x15c11c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
io       57779 fill: io_u 0x15c11c0: off=0x41380,len=0x40,ddir=0,file=/home/file1.3.0
io       57780 prep: io_u 0x15c11c0: off=0x191c0,len=0x40,ddir=0,file=/home/file1.2.0
io       57781 fill: io_u 0x15c11c0: off=0xa7040,len=0x40,ddir=0,file=/home/file1.1.0
io       57778 queue: io_u 0x15c11c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
io       57779 prep: io_u 0x15c11c0: off=0x41380,len=0x40,ddir=0,file=/home/file1.3.0
io       57780 queue: io_u 0x15c11c0: off=0x191c0,len=0x40,ddir=0,file=/home/file1.2.0
io       57781 prep: io_u 0x15c11c0: off=0xa7040,len=0x40,ddir=0,file=/home/file1.1.0
io       57779 queue: io_u 0x15c11c0: off=0x41380,len=0x40,ddir=0,file=/home/file1.3.0
io       57781 queue: io_u 0x15c11c0: off=0xa7040,len=0x40,ddir=0,file=/home/file1.1.0
0
0
io       57778  fio_q_status dummyioengine
0
io       57780  fio_q_status dummyioengine
0
io       57779  fio_q_status dummyioengine
io       57778 calling ->commit(), depth 1
io       57781  fio_q_status dummyioengine
io       57780 calling ->commit(), depth 1
io       57779 calling ->commit(), depth 1
io       57781 calling ->commit(), depth 1
io       57778 io_u_queued_complete: min=1
io       57780 io_u_queued_complete: min=1
io       57779 io_u_queued_complete: min=1
io       57778 getevents: 0
io       57780 getevents: 0
io       57781 io_u_queued_complete: min=1
io       57779 getevents: 0
io       57778 __get_io_u failed
io       57780 __get_io_u failed
io       57781 getevents: 0
io       57779 __get_io_u failed
io       57778 io_u_queued_complete: min=1
io       57780 io_u_queued_complete: min=1
io       57781 __get_io_u failed
io       57779 io_u_queued_complete: min=1
io       57778 getevents: 0
io       57780 getevents: 0
io       57781 io_u_queued_complete: min=1
io       57779 getevents: 0
io       57781 getevents: 0
file1: No I/O performed by dummyioengine, perhaps try --debug=io option for details?
file1: No I/O performed by dummyioengine, perhaps try --debug=io option for details?
file1: No I/O performed by dummyioengine, perhaps try --debug=io option for details?
file1: No I/O performed by dummyioengine, perhaps try --debug=io option for details?
io       57778 close ioengine dummyioengine
io       57778 free ioengine dummyioengine
io       57780 close ioengine dummyioengine
io       57780 free ioengine dummyioengine
io       57779 close ioengine dummyioengine
io       57779 free ioengine dummyioengine
io       57781 close ioengine dummyioengine
io       57781 free ioengine dummyioengine

file1: (groupid=0, jobs=1): err= 0: pid=57778: Wed Jul 15 10:19:42 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=2, majf=0, minf=69
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=66.7%, 4=33.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
file1: (groupid=0, jobs=1): err= 0: pid=57779: Wed Jul 15 10:19:42 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=3, majf=0, minf=69
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=66.7%, 4=33.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
file1: (groupid=0, jobs=1): err= 0: pid=57780: Wed Jul 15 10:19:42 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=2, majf=0, minf=68
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=66.7%, 4=33.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
file1: (groupid=0, jobs=1): err= 0: pid=57781: Wed Jul 15 10:19:42 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=3, majf=0, minf=67
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=66.7%, 4=33.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):

Disk stats (read/write):
    dm-2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
io       57711 ioengine sg unregistered
io       57711 ioengine mtd unregistered
io       57711 fio setup called for unregistered
io       57711 ioengine dummyioengine unregistered
io       57711 ioengine splice unregistered
io       57711 ioengine e4defrag unregistered
io       57711 ioengine falloc unregistered
io       57711 ioengine posixaio unregistered
io       57711 ioengine filecreate unregistered
io       57711 ioengine ftruncate unregistered
io       57711 ioengine net unregistered
io       57711 ioengine netsplice unregistered
io       57711 ioengine null unregistered
io       57711 ioengine sync unregistered
io       57711 ioengine psync unregistered
io       57711 ioengine vsync unregistered
io       57711 ioengine pvsync unregistered
io       57711 ioengine pvsync2 unregistered
io       57711 ioengine mmap unregistered
io       57711 ioengine cpuio unregistered

**Comment by sitsofe** [comment]
It would be easier to understand if you were able to link/post the new code in question - why no I/O is happening will depend on which functions you implemented and whether your engine is synchronous or not asynchronous. Could you also base your changes on the master version of fio please? Also as this isn't so much an issue in fio and more of a "How do I/Why is?" question it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.19/README#L58) (note that the list only accepts plain text emails)...

**Comment by sitsofe** [comment]
(Briefly it seems curious that `getevents()` is never finding any completion events - is there something wrong there?)

**Comment by selvakumars3** [comment]
Thanks @sitsofe  I rebased with master. Now I am getting different error,

**Comment by selvakumars3** [comment]
Thanks @sitsofe  I rebased with master. Now I am getting different error,
Also i am facing issue in posting the Q&A in the forum list. could you please help us exact steps needed to post q&a ?

I am not able to see IOPS value , I have written new fio engine . I see " io       17672 __get_io_u failed " error. kindly advice what went wrong
/usr/local/bin/fio   --debug=io pcie.fio
fio: set debug option io
io       17606 load ioengine pcieoptanememory
file1: (g=0): rw=randread, bs=(R) 64B-64B, (W) 64B-64B, (T) 64B-64B, ioengine=pcieoptanememory, iodepth=1
fio-3.20-dirty
Starting 1 process
file1: Laying out IO file (1 file / 1MiB)
io       17606 declare unneeded cache /home/file1.0.0: 0/1048576
io       17672 declare unneeded cache /home/file1.0.0: 0/1048576
io       17672 fill: io_u 0x19661c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
io       17672 prep: io_u 0x19661c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
io       17672 queue: io_u 0x19661c0: off=0xf700,len=0x40,ddir=0,file=/home/file1.0.0
0
io       17672  fio_q_status pcieoptanememory
io       17672 calling ->commit(), depth 1
io       17672 io_u_queued_complete: min=1
io       17672 getevents: 0
io       17672 __get_io_u failed
io       17672 io_u_queued_complete: min=1
io       17672 getevents: 0
io       17672 close ioengine pcieoptanememory
io       17672 free ioengine pcieoptanememory

file1: (groupid=0, jobs=1): err= 0: pid=17672: Wed Jul 15 15:28:54 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=1, majf=0, minf=67
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=66.7%, 4=33.3%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):

Disk stats (read/write):
    dm-2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
io       17606 ioengine io_uring unregistered
io       17606 ioengine sg unregistered
io       17606 ioengine mtd unregistered
io       17606 fio setup called for unregistered
io       17606 ioengine pcieoptanememory unregistered
io       17606 ioengine splice unregistered
io       17606 ioengine e4defrag unregistered
io       17606 ioengine falloc unregistered
io       17606 ioengine posixaio unregistered
io       17606 ioengine filestat unregistered
io       17606 ioengine filecreate unregistered
io       17606 ioengine ftruncate unregistered
io       17606 ioengine net unregistered
io       17606 ioengine netsplice unregistered
io       17606 ioengine null unregistered
io       17606 ioengine sync unregistered
io       17606 ioengine psync unregistered
io       17606 ioengine vsync unregistered
io       17606 ioengine pvsync unregistered
io       17606 ioengine pvsync2 unregistered
io       17606 ioengine mmap unregistered
io       17606 ioengine cpuio unregistered

**Comment by axboe** [comment]
Helping with writing/debugging an engine where we don't even have the source is beyond the scope of what we can help with.

**Comment by selvakumars3** [comment]
> Helping with writing/debugging an engine where we don't even have the source is beyond the scope of what we can help with.

Hi @axboe  thanks a lot for offering help. Attached the snippets for your reference.
/*
 PCIE memory fio engine
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/uio.h>
#include <errno.h>
#include <assert.h>
#include <string.h>

#include "../fio.h"

/*
 * libdummyioenginememory
 */


struct dummyioengine_data {

	struct io_u **aio_events;
	unsigned int aio_pending;
	unsigned int nr;
	unsigned int max_depth;
};

#define TRUE 1
static enum fio_q_status fio_dummyioengine_queue(struct thread_data *td,
					      struct io_u *io_u)
{
	
	bool success;
	static int io_count =0;

	int rc = FIO_Q_COMPLETED;

	fio_ro_check(td, io_u);
	printf("%d \n", io_count++);
	dprint(FD_IO, " fio_q_status dummyioenginememory \n");

	switch (io_u->ddir) {
	case DDIR_WRITE:
		success = TRUE;
		break;
	case DDIR_READ:
		success = TRUE;
		break;
	case DDIR_SYNC:
	case DDIR_DATASYNC:
	case DDIR_SYNC_FILE_RANGE:
		success = TRUE;
		if (!success) {
			log_err("dummyioenginememory: failed to flush file buffers\n");

		}

		return FIO_Q_COMPLETED;
	case DDIR_TRIM:
		log_err("dummyioenginememory: manual TRIM isn't supported on Windows\n");
		return FIO_Q_COMPLETED;
	default:
		assert(0);
		break;
	}
	if (success)
		rc = FIO_Q_QUEUED;
	else {
		 log_err("dummyioenginememory: Error in queuing\n");

	}

    //io_u->error = 0;
	//io_u->resid = 0;
	return rc;
}

static int fio_dummyioengine_getevents(struct thread_data *td, unsigned int min,
				    unsigned int max, const struct timespec *t)
{
	int ret;
	ret = 0;
	return ret;
}

static struct io_u *fio_dummyioengineaio_event(struct thread_data *td, int event)
{
	struct dummyioengine_data *sd = td->io_ops_data;

	return sd->aio_events[event];
}

static void fio_dummyioengineaio_cleanup(struct thread_data *td)
{
	struct dummyioengine_data *sd = td->io_ops_data;

	if (sd) {
		free(sd->aio_events);
		free(sd);
	}
}


static struct ioengine_ops ioengine = {
	.name = "dummyioenginememory",
	.queue = fio_dummyioengine_queue,
	.version = FIO_IOOPS_VERSION,
	.open_file = generic_open_file,
	.getevents	= fio_dummyioengine_getevents,
	.event		= fio_dummyioengineaio_event,
	.cleanup	= fio_dummyioengineaio_cleanup,
};

static void fio_init fio_dummyioengine_register(void)
{
	dprint(FD_IO, "fio setup called for fio_dummyioengine_register \n");
	register_ioengine(&ioengine);
	
}

static void fio_exit fio_dummyioengine_unregister(void)
{
	dprint(FD_IO, "fio setup called for unregistered \n");
	unregister_ioengine(&ioengine);
}

**Comment by axboe** [comment]
Just compare with the null engine, looks like you're doing the same thing. get_io_u() most often fails because the amount of IO asked for was done. What's in your pcie.fio file?

**Comment by sitsofe** [comment]
> Also i am facing issue in posting the Q&A in the forum list. could you please help us exact steps needed to post q&a ?

1. Set your email program to send ONLY plain text emails ("note that the list only accepts plain text emails").
2. Follow the instructions in https://github.com/axboe/fio/blob/fio-3.20/README#L58

I find I can send to the list from a GMail account so long as I observe the above (although forced wrapping of long lines in email I send can be a bit weird in GMail). You can see more details about what the list accepts over on http://vger.kernel.org/majordomo-info.html .

Re the snippet you posted:
```c
static int fio_dummyioengine_getevents(struct thread_data *td, unsigned int min,
				    unsigned int max, const struct timespec *t)
{
	int ret;
	ret = 0;
	return ret;
}
[...]
static struct ioengine_ops ioengine = {
	.name = "dummyioenginememory",
	.queue = fio_dummyioengine_queue,
	.version = FIO_IOOPS_VERSION,
	.open_file = generic_open_file,
	.getevents	= fio_dummyioengine_getevents,
	.event		= fio_dummyioengineaio_event,
	.cleanup	= fio_dummyioengineaio_cleanup,
};
```
 your engine is expected to be asynchronous because you are not indicating otherwise via `.flags` so I'd argue the body of your `.getevents` function (`fio_dummyioengine_getevents()`) looks strange... Based on that, I would recommend carefully reading the comments in https://github.com/axboe/fio/blob/d51e4ffa596b617cdb41680b31a4a3895a5307fc/engines/skeleton_external.c and, as @axboe mentioned, understanding https://github.com/axboe/fio/blob/37e8cc62319b30927a3147e25b16c3e00b84692f/engines/null.c . When you can completely follow the flow and reasoning of a working async engine I'd imagine your problem should be clear and you will be able to look at the other engines to get further ideas.

A few more tips:
- It's tough reading code dumps that don't preserve formatting. I've fixed up the formatting of your comment above but I'd recommend reading https://guides.github.com/features/mastering-markdown/ so you know what I changed in case you are asking again in the future.
- As your code becomes longer it will be painful to read as an inline comment on the web. You may want to look into https://docs.github.com/en/github/writing-on-github/creating-gists .
- Keep an eye out for people asking clarifying questions
- Working code makes for useful background reading

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
