### ISSUE TITLE
error=Invalid argument on Command Prompt

### ISSUE THREAD

**Issue by jaasoonl** [axboe/fio#1043]
New to coding but I'm receiving the "error=Invalid argument" every time I try to execute the command:

C:\>C:Users\Jason\Downloads\fio\fio.exe --filename=**pd2** --name=randwrite --ioengine=sync --iodepth=1 --rw=randrw --rwmixread=50 --rwmixwrite=50 --bs=4k --direct=0 --numjobs=8 --size=300G --runtime=7200 --group_reporting
fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
randwrite: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=sync, iodepth=1
...
fio-3.20
Starting 8 threads
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument
randwrite: Laying out IO file (1 file / 307200MiB)
fio: pid=0, err=22/file:filesetup.c:150, func=unlink, error=Invalid argument

Run status group 0 (all jobs):

Haven't been very successful in figuring out the problem, tried using different drives and sizes but unsure. Appreciate any help!

**Comment by sitsofe** [comment]
Hi @jaasoonl,

By default, fio will make a file with a filename based on the job file name (in your case "pd2") wherever you are standing. You appear to be standing in `C:\` ... Are you sure you have write permission on that directory?

(Also be aware that if your shell is PowerShell you may need to prefix with `&` if you ever need to manually call fio.exe from a path that contains spaces (https://ss64.com/ps/call.html ) and that PowerShell will autoconvert number literals with certain suffixes (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_numeric_literals?view=powershell-7#real-literals ) but neither of these points affect your example above)

If this answers your question could you close this issue? Thanks!

**Comment by jaasoonl** [comment]
Hi @sitsofe 

Thanks for the quick reply! pd2 is my Windows drive indicator for that hard drive I want to test. I've opened command prompt in admin mode, and I've also changed C: to E: but with no success. Would there be any other potential issues? 

Thanks!

**Comment by sitsofe** [comment]
@jaasoonl I'd stand in your regular home directory and simplify the job dramatically:
./fio.exe --name=test --size=1M --filename=pd2

and see what happens.

**Comment by jaasoonl** [comment]
It works haha 

I'll figure it out from there, apologies about the complexity I copied pasted from some other experienced user :) 

Thanks again for your help!
