### ISSUE TITLE
providing ratemin parameter requires that a maximum also be set..

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#105]
Examin the following command.
<pre><code>
 fio --direct=1 --latency-log  --bandwidth-log --name=mpathyu --filename=/dev/mapper/mpathyu --bs=4096 --rwmixread=50 --runtime=259200 --time_based=1 --rw=randrw --verify=crc32c-intel  --iodepth=16   --ratemin=4096    --ioengine=libaio
fio: minimum rate exceeds rate
</code></pre>
I imagine that this is due to either the default being 0 or -1 (meaning unlimited).  The work around is of course to provide a maximum.

**Comment by DaveGlen** [comment]
I can think of several situations where someone would want to set a ratemin without using rate to limit performance.

I made a code change and a pull request for this, it would have to be approved by someone with write access.

**Comment by rustyscottweber** [comment]
Attempting this with the latest branch makes me think that it might be fixed already.

**Comment by DaveGlen** [comment]
It is. The commits were made on 8/17 and 8/18.

Thanks for catching it to begin with :)
