### ISSUE TITLE
Assertion `iolog->pending->nr_samples < iolog->pending->max_samples' failed

### ISSUE THREAD

**Issue by karlatec** [axboe/fio#1051]
Hello!

I get the following assertion when trying to run my job configuration.
```
fio: stat.c:2563: get_cur_log: Assertion `iolog->pending->nr_samples < iolog->pending->max_samples' failed.
Aborted
```

My  fio config below. I am trying to run a scenario to see how IOPS scale for a single CPU with each added nvme.
I want effective iodepth per filename to be 128, so iodepth in config file = 128 * number_of_disks.

```
[global]
direct=1
thread=1
norandommap=1
group_reporting=1
time_based=1
ioengine=libaio

rw=randread
rwmixread=70
bs=4096
runtime=30
ramp_time=0
numjobs=1
log_avg_msec=0

[filename0]
iodepth=2816
cpus_allowed=20
filename=/dev/nvme0n1
filename=/dev/nvme1n1
filename=/dev/nvme2n1
filename=/dev/nvme3n1
filename=/dev/nvme4n1
filename=/dev/nvme5n1
filename=/dev/nvme6n1
filename=/dev/nvme7n1
filename=/dev/nvme8n1
filename=/dev/nvme9n1
filename=/dev/nvme10n1
filename=/dev/nvme11n1
filename=/dev/nvme12n1
filename=/dev/nvme13n1
filename=/dev/nvme14n1
filename=/dev/nvme15n1
filename=/dev/nvme16n1
filename=/dev/nvme17n1
filename=/dev/nvme18n1
filename=/dev/nvme19n1
filename=/dev/nvme20n1
filename=/dev/nvme21n1
filename=/dev/nvme22n1
```

Command used:
```
sudo /usr/src/fio/fio kernel_fio.fio --output-format=json --output=/tmp/result.json --write_lat_log=/tmp/test-lat.txt
```

This issue does not happen if I either:
- remove `--write_lat_log=/tmp/test-lat.txt` from command
- enable gtod_recude=1 option

System & fio info:
- Fedora 30 5.4.14
- gcc 9.2.1
- fio-3.21

**Comment by sitsofe** [comment]
So you want one job that will round robin I/Os between 22 disks? As it's one thread you're aware it won't be able to use more than one CPU at a time right?

Both the options you specified would turn off latency recording (e.g. see https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-gtod-reduce ) so I'm not surprised the issue "goes away" with them

@axboe I wonder, if fio isn't able to regrow the log of I/Os quicker than the new I/Os stack up then you would hit the assertion? @karlatec Maybe adjusting the numbers defined for `DEF_LOG_ENTRIES` and `MAX_LOG_ENTRIES` in iolog.h would help? 

Unfortunately I don't have a setup with 22 NVMe disks so is there anything you can do to cut this job down further but still make it reproducible?
- Reduce the number of filenames
- Switch the disks to files

**Comment by axboe** [comment]
You should be able to emulate something similar by just using null_blk with nr_devices=22 or something like that.

**Comment by sitsofe** [comment]
@axboe Oh yes, good point...

**Comment by karlatec** [comment]
> As it's one thread you're aware it won't be able to use more than one CPU at a time right?

@sitsofe 
Yes, that's exactly how I want it :)

> Unfortunately I don't have a setup with 22 NVMe disks so is there anything you can do to cut this job down further but still make it reproducible?

I see that it is possible to reproduce with just 1 target nvme. Just leave iodepth at ridiculously high value

> Maybe adjusting the numbers defined for DEF_LOG_ENTRIES and MAX_LOG_ENTRIES in iolog.h would help?

Setting `DEF_LOG_ENTRIES` to 4096 did the trick.


** Note: I updated original issue description ** The issue would not reproduce with what I pasted in. log_avg_msec should be 0 or not present in config file to reproduce the issue. For log_avg_msec=250 it seems to run smoothly

**Comment by sitsofe** [comment]
On Linux this is easy to reproduce with something like
```
fio --name=issue1051 --thread --ioengine=libaio --filename=/tmp/fio.tmp --size=10M --iodepth=2049 --write_lat_log=/tmp/1051 --time_based=1 --runtime=5
```

Any of the "real" async engines on Linux (io_uring, libaio, posixaio) is able to reproduce the issue. posixaio on macOS mysteriously **isn't** able to reproduce the issue...

gdb confirms the issue when the assert hits:
```
2567			assert(iolog->pending->nr_samples < iolog->pending->max_samples);
(gdb) p iolog->pending->nr_samples
$1 = 1024
(gdb) p iolog->pending->max_samples
$2 = 1024
```

setting `iodepth=2048` makes the issue go away too.

**Comment by axboe** [comment]
Can you try current -git? Should have this as the top commit:

https://git.kernel.dk/cgit/fio/commit/?id=b5aba537d844f73187eb931179ac59e7da570e7c

**Comment by sitsofe** [comment]
That fixes the problem with my test case above. @karlatec does that patch solve things for you too?

**Comment by karlatec** [comment]
Same here, mentioned commit fixes the problem.

**Comment by sitsofe** [comment]
@karlatec thanks for the update. Closing this issue as fixed.
