### ISSUE TITLE
Passing an explicit --enable-libnbd should error if it can't find libnbd

### ISSUE THREAD

**Issue by joshtriplett** [axboe/fio#1052]
The behavior I've seen in most configure scripts is that autodetection will enable features if configure finds the corresponding dependencies, but if you pass an explicit `--enable-something` option, you'll get an error if configure can't find the corresponding dependencies.

Running `./configure --enable-libnbd` without libnbd installed will silently succeed and leave the NBD engine disabled. I'd expect it to produce an error.

**Comment by axboe** [comment]
I agree, that would be a more desirable outcome.

**Comment by joshtriplett** [comment]
Awesome, thank you!
