### ISSUE TITLE
compile issue of 2.2.9 on SLES 11.4 "storage size of ‘ops’ isn’t known"

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#107]
<pre><code>
fio-app:/tmp/fio-fio-2.2.9 # make
    CC gettime.o
gettime.c: In function ‘fio_monotonic_clocktest’:
gettime.c:566: warning: ‘prev’ may be used uninitialized in this function
    CC ioengines.o
    CC stat.o
    CC log.o
    CC time.o
    CC filesetup.o
    CC eta.o
    CC verify.o
    CC memory.o
    CC io_u.o
    CC parse.o
    CC mutex.o
    CC options.o
    CC lib/rbtree.o
    CC smalloc.o
    CC filehash.o
    CC profile.o
    CC debug.o
    CC lib/rand.o
    CC lib/num2str.o
    CC lib/ieee754.o
    CC crc/crc16.o
    CC crc/crc32.o
    CC crc/crc32c-intel.o
    CC crc/crc32c.o
    CC crc/crc64.o
    CC crc/crc7.o
    CC crc/fnv.o
    CC crc/md5.o
    CC crc/murmur3.o
    CC crc/sha1.o
    CC crc/sha256.o
    CC crc/sha512.o
    CC crc/test.o
    CC crc/xxhash.o
    CC engines/cpu.o
    CC engines/mmap.o
    CC engines/sync.o
    CC engines/null.o
    CC engines/net.o
    CC memalign.o
    CC server.o
    CC client.o
    CC iolog.o
    CC backend.o
    CC libfio.o
    CC flow.o
    CC cconv.o
    CC lib/prio_tree.o
    CC json.o
    CC lib/zipf.o
    CC lib/axmap.o
    CC lib/lfsr.o
    CC gettime-thread.o
    CC helpers.o
    CC lib/flist_sort.o
    CC lib/hweight.o
    CC lib/getrusage.o
    CC idletime.o
    CC td_error.o
    CC profiles/tiobench.o
    CC profiles/act.o
    CC io_u_queue.o
    CC filelock.o
    CC lib/tp.o
    CC lib/bloom.o
    CC lib/gauss.o
    CC lib/mountcheck.o
    CC workqueue.o
    CC engines/libaio.o
    CC engines/posixaio.o
    CC engines/falloc.o
    CC engines/e4defrag.o
    CC engines/splice.o
    CC engines/mtd.o
    CC lib/libmtd.o
lib/libmtd.c: In function ‘mtd_write’:
lib/libmtd.c:1129: error: storage size of ‘ops’ isn’t known
lib/libmtd.c:1165: error: ‘MEMWRITE’ undeclared (first use in this function)
lib/libmtd.c:1165: error: (Each undeclared identifier is reported only once
lib/libmtd.c:1165: error: for each function it appears in.)
lib/libmtd.c:1172: error: ‘MTD_OPS_AUTO_OOB’ undeclared (first use in this function)
lib/libmtd.c:1129: warning: unused variable ‘ops’
make: *** [lib/libmtd.o] Error 1
</code></pre>

Normally this error is indicative of the struct type not existing, in this case mtd_write_req.  To perpetuate my hypothesis even further, I cannot find the struct type anywhere in the fio-project.  Is this provided by another source module?  or is this just missing implementation?

**Comment by axboe** [comment]
Should be fixed in current -git, please retry and report.

**Comment by rustyscottweber** [comment]
I tried this earlier with the latest repo, but it looks like you or someone must have pushed some changes in.  Latest seems to compile fine, but I will let you know if I run into other issues that might seem related to the changes that were pushed.

**Comment by axboe** [comment]
I checked in a fix.
