### ISSUE TITLE
Install newer version fio with S3 http support 

### ISSUE THREAD

**Issue by wxgsdy** [axboe/fio#1074]
Hi there,

We are trying to build testing automation on top of FIO, running on AWS EC2 instance. Specially, we need the S3 http support. 

We are trying to figure out a easy way to install FIO on the Amazon Linux instance. We have tried the following way: 
1. install fio through `yum repo`, but it looks like we can only get older version of fio without S3 http support; 
2. Manually build fio source code and maintain the binary file -> this way would work but cost too much to maintain a binary file ourselves. 

My question is, is there a simpler way you can recommend, how we can install fio on the linux instance easily with S3 http support ? like where we can get the fio so we don't need to build and maintain our own. 

Thanks

**Comment by sitsofe** [comment]
@wxgsdy We (upstream) don't provide pre-built fio fbinary or Linux so if your distro doesn't choose to package it with the options you want you will have to build it yourself. I suppose you could try asking your vendor if they would pre-build it for you with different options? Having said that building fio is relatively small and fast compared to other tools and if you provide your own repo...
