### ISSUE TITLE
getting "call trace" errors for fio for NVME with direct=0 and bs=128k

### ISSUE THREAD

**Issue by anilreddy3** [axboe/fio#1077]
getting "call trace" errors for fio for NVME with direct=0 and bs=128k
fio cmd used:
fio --rw=rw --rwmixread=0 --bs=128k --ioengine=libaio --direct=0 --iodepth=8 --group_reporting --name=128k-libaio_direct-0 --numjobs=8 --runtime=60 --filename=/dev/nvme1n1

[ 1129.692625] INFO: task fio:5156 blocked for more than 122 seconds.
[ 1129.700891]       Not tainted 5.4.42-20.07-RC1+ #5
[ 1129.709239] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this messa.
[ 1129.719823] fio             D    0  5156   5145 0x00000200
[ 1129.728069] Call trace:
[ 1129.733283]  __switch_to+0xd4/0x250
[ 1129.739526]  __schedule+0x2a0/0x6d8
[ 1129.745778]  schedule+0x48/0xe8
[ 1129.751677]  schedule_preempt_disabled+0x28/0x40
[ 1129.759062]  __mutex_lock.isra.8+0x204/0x578
[ 1129.766094]  __mutex_lock_slowpath+0x24/0x30
[ 1129.773126]  mutex_lock+0x44/0x60
[ 1129.779198]  blkdev_put+0x2c/0x100
[ 1129.785365]  blkdev_close+0x2c/0x40
[ 1129.791613]  __fput+0x90/0x230
[ 1129.797433]  ____fput+0x20/0x30
[ 1129.803339]  task_work_run+0x88/0x138
[ 1129.809756]  do_notify_resume+0x210/0x4a0
[ 1129.816532]  work_pending+0x8/0x10

Fio test with blocksize=128 is accumulating page/buffer cache more than 100GB, and to flush/write back this data to device is taking more time like. And while flush operation in progress in background the fio thread trying to close disk by acquiring the lock, which are getting blocked on lock for more than 120seconds and leading to this call trace message.
**looks fio thread trying close the disk while still fio test is in progress is this a bug??**

**Comment by axboe** [comment]
That's expected behavior on the kernel side, even if a bit annoying as it's not really a bug. In any case, certainly not a fio issue.
