### ISSUE TITLE
Fio segfaults and hangs when using io_submit_mode=offload

### ISSUE THREAD

**Issue by ajgopala** [axboe/fio#1085]
I am observing a bunch of FIO behaviors which I fail to understand.

1. Fio prints out read and write IOPS for a while and then it stops printing that number. It just prints a progress and ETA value. Then after progress reaches 100% it changes the time remaining to 3 days or something again. It resets the time .. what does this mean?

2. FIO runs much longer than the time specified in runtime value. I have even set time_based=1. Is this expected?

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/fio/tree/REPORTING-BUGS

**Comment by ajgopala** [comment]
Thanks for the link.

1. I noticed I am running 3.16 (not 3.23). I will try to use the latest version
1. I don't actually know if this is a FIO bug. I just want to understand FIO behavior. Is this expected behavior or not.
1. I cannot give you reproduction instructions because I am running this on top of BTRFS on top of a custom Block layer that I am implementing. It might very well be a bug in my code that is causing FIO to misbehave.
1. Since FIO is not actually throwing any error per say -- the IOPS value simply vanishes -- I was curious to know if that means something in FIO.

Does this configuration look wrong?

```runtime=600
rw=randrw
rwmixwrite=90
random_distribution=random
percentage_random=100
iodepth=16
ioengine=libaio
direct=1
io_submit_mode=offload
verify=sha3-256
bs=4096
time_based=1
fallocate=none
size=50%
filesize=32GB
directory=/tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab
```

**Comment by ajgopala** [comment]
Also, is it absolutely required for FIO to lay down the file? Can FIO skip that step and just start running the workload instead? The thing is the laying out step tries to write 16GB worth of data in above configuration, but if the runtime is say 20 seconds, I don't want it to lay out 16GB because that's overkill

**Comment by axboe** [comment]
The most common cause of what you're describing is that requests are getting lost and hence fio isn't getting the io completions. If you're using some private block layer, then that would be the prime suspect. I'd start there.

**Comment by axboe** [comment]
In short, I'd be very surprised if this is a bug in fio. It may help you debut the issue in your kernel code, though.

**Comment by ajgopala** [comment]
> In short, I'd be very surprised if this is a bug in fio. It may help you debut the issue in your kernel code, though.

Absolutely. Make sense.

> hence fio isn't getting the io completions

Can FIO (may be via the trace option) tell me which requests are not getting completed? If I know which offset range it was reading/writing to, I can correlate that with my private block layer and go forward with the debugging.

Thanks a lot for the quick response!

**Comment by ajgopala** [comment]
I tried this command to get the trace file output. If I try to `cat fio1.trace` after starting FIO, this file does not even exist.

```
fio --output=fio1.out --write_iolog=fio1.trace fio1
```

Is it created only after it is done laying out the file?

**Comment by ajgopala** [comment]
I got this error. Not sure what it means though.

```
file     418   file not found in hash /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0
```

```
Run status group 0 (all jobs):
fio: file hash not empty on exit
```

```# fio --write_iolog=fio1.trace --debug=file fio1
fio: set debug option file
file     414   dup files: 0
file     414   add file ssgb-job-1.0.0
file     414   resize file array to 2 files
file     414   file 0x7f8b4685f510 "/tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0" added at 0
ssgb-job-1: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
fio-3.16
Starting 1 process
file     414   setup files
file     414   get file size for 0x7f8b4685f510/0//tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0
ssgb-job-1: Laying out IO file (1 file / 3276MiB)
file     414   layout unlink /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0
file     414   open file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0, flags 241
file     414   truncate file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0, size 3435970560
file     420   dup files: 1
file     423   dup files: 1
file     422   dup files: 1
file     424   dup files: 1
file     425   dup files: 1
file     426   dup files: 1
file     427   dup files: 1
file     428   dup files: 1
file     421   dup files: 1
file     430   dup files: 1
file     431   dup files: 1
file     432   dup files: 1
file     433   dup files: 1
file     434   dup files: 1
file     429   dup files: 1
file     419   dup files: 1
file     418   trying file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0 0
file     418   fd open /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0
file     418   file not found in hash /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0
file     418   get file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0, ref=0
file     418   goodf=1, badf=2, ff=21
file     418   get_next_file_rr: 0x7f8b4685f510
file     418   get_next_file: 0x7f8b4685f510 [/tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0]
file     418   get file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0, ref=1
file     418   trying file /tmp/dced6368-f2f3-11ea-9ece-2bf36d3e82ab/ssgb-job-1.0.0 21
fio: pid=418, got signal=11
```

**Comment by ajgopala** [comment]
I also see a FIO segfault in dmesg.  Not sure what to make of it.

```
[Thu Sep 10 04:45:49 2020] fio[17051]: segfault at c0 ip 00007fd38ff04a26 sp 00007fd364afe5e0 error 4
[Thu Sep 10 04:45:49 2020] fio[17052]: segfault at c0 ip 00007fd38ff04a26 sp 00007fd3652ff5e0 error 4
[Thu Sep 10 05:07:08 2020] fio[28391]: segfault at c0 ip 00007f8b5115fa26 sp 00007f8b25d595e0 error 4 in libc-2.31.so[7f8b5110b000+178000]
[Thu Sep 10 05:22:27 2020] fio[4167]: segfault at c0 ip 00007f07197dba26 sp 00007f06edbd45e0 error 4 in libc-2.31.so[7f0719787000+178000]
```

**Comment by axboe** [comment]
Didn't notice you were using offload, that can be a bit iffy... Can you try without ```io_submit_mode=offload``` set in the job file?

**Comment by axboe** [comment]
Tested it here, looks like a bug with offload with verify. I'm taking a look.

**Comment by ajgopala** [comment]
Thank you! Let me know if you need more info. My cluster is still up. I can run few more commands if you want me to.

Another thing that I noticed — I think this is just me misunderstanding FIO — I tried to disable pre allocations with fallocate=none but as you can see from above it still tries to truncate the file. Not sure why a truncate is needed.

**Comment by ajgopala** [comment]
Fyi - I remove offload and verify and FIO succeeded. I will wait for the fix and keep it disabled until then.

**Comment by sitsofe** [comment]
Fio has abfd235a05330eae8444f0e4c0039bbdf9f160a3 which disables `io_submit=offload` for engines that are it can't cope with.

**Comment by sitsofe** [comment]
Is this one still an issue @ajgopala / @axboe ?

**Comment by axboe** [comment]
Should not be, it's explicitly disabled for the broken case.
