### ISSUE TITLE
configure --enable-libaio-uring issue

### ISSUE THREAD

**Issue by ssampath** [axboe/fio#1088]
ssgroot@SudheFMdev01:~/GIT_REPOS/fio$ ./configure --enable-libaio-uring
Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no

Static build                  no
Wordsize                      64
zlib                          yes
ERROR
ERROR: User requested feature libaio io_uring
ERROR: configure was not able to find it
ERROR
Configure failed, check config.log and/or the above output
ssgroot@SudheFMdev01:~/GIT_REPOS/fio$

However, I can run 'io_uring based examples' from the liburing repository that I have compiled.

ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$ ./io_uring-cp link-cp test.out
ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$ echo $?
0
ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$ ls -l test.out
-rw-r--r-- 1 ssgroot ssgroot 69896 Sep 14 13:17 test.out
ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$

Also, the kernel configuration has "CONFIG_IO_URING=y" set.

ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$ uname -r
5.4.0-42-generic

ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$ sudo grep URING /boot/config-5.4.0-42-generic
CONFIG_IO_URING=y
ssgroot@SudheFMdev01:~/GIT_REPOS/liburing/examples$

I am unable to understand what I am missing to get fio to work with io_uring.  Any help appreciated.

Thanks.

**Comment by axboe** [comment]
You don't need to do anything, it's enabled by default as it has no external requirements. You're trying to use the libaio io_uring emulation, which isn't supported, it was just a test thing.
