### ISSUE TITLE
 --ioengine=windowsaio  --size=80% results in error

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1089]
FIO 3.19 and 3.22

I am trying to run a series of FIO tests with an increasing number of files while maintaining the volume filled at 80%. Using --unlink=1 --thread --direct=1  --ioengine=windowsaio --name=Hvy2Bit --size=80%

 results in 

fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument
Hvy2Bit: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1057, func=total_file_size, error=Invalid argument

From the MAN page
 If size=20% is given, fio will use 20% of the full size of the given files or devices.
What am I missing?
thanks

**Comment by sitsofe** [comment]
Hi @Gt3pccb,

Does the file already exist? If not then you can't ask for 80% of its size :-) From the docs (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size ):

> If size=20% is given, fio will use 20% of the full size of the given files or devices.

This is **not** in reference to filesystems - maybe you are thinking of free space within a filesystem ("while maintaining the volume filled")? The closest you get to that is [`fill_fs`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-fill-device) but that is a "use it all" option and by its very nature is incompatible with `size` (I only mention it for completeness).

To do what you want you need to run some other tool that gets the current available space of your filesystem, works out what 80% of it is and calls fio with an appropriate absolute value for size.

**Comment by sitsofe** [comment]
I'm going to close this issue because size percentages only work when the file already exists.
