### ISSUE TITLE
Unclear value units for terse/minimal output of fio

### ISSUE THREAD

**Issue by Taragos** [axboe/fio#1094]
There is no mention of the unit value that fio uses for outputting some of its values in a terse/minimal format.
The values for:

- Total I/O
- bandwidth
- runtime

are clearly stated, while:

- Submission latency values
- Completion latency values
- Total Latency values
- Bandwidth

are not-defined in the documentation.

Only mention of those values I could find: https://www.andypeace.com/fio_minimal.html
**Which values does fio use in it's terse/minimal output?**

**Comment by Taragos** [comment]
I just found a few information in the official fio documentation (don't know how I didn't notice those lines before)
It was mentioned that the minimal output values for slat is always in microseconds. Seeing that clat and lat both refer to the slat paragraph I would assume they are also in milliseconds.

But what about the bandwith values like READ_bw_max, can one safely assume they are also in KB like the value READ_bandwidth?

**Comment by sitsofe** [comment]
Using a rate limited job should allow us to inspect the output:
```
fio --output-format=terse --name=test --ioengine=null --bs=3k --rate=6k --time_based=1 --runtime=5 --size=1m
```

```
{
  "fio version" : "fio-3.23-31-gf0d5e",
[...]
  "jobs" : [
    {
      "jobname" : "test",
[...]
      "read" : {
[...]
        "bw_min" : 5,
        "bw_max" : 11,
```

Here's what I got using terse (description of the columns is at the bottom of the section in https://fio.readthedocs.io/en/latest/fio_man.html#terse-output ):
```
fio --output-format=terse --name=test --ioengine=null --rate=6k --time_based=1 --runtime=5 --size=1m       
3;fio-3.23-31-gf0d5e;test;0;0;32;6;1;5001;0;0;0.000000;0.000000;0;6;1.798625;1.769192;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=1;50.000000%=1;60.000000%=1;70.000000%=1;80.000000%=1;90.000000%=6;95.000000%=6;99.000000%=6;99.500000%=6;99.900000%=6;99.950000%=6;99.990000%=6;0%=0;0%=0;0%=0;4;20;7.669125;5.364469;7;15;100.000000%;8.333333;3.265986;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0.000000%;0.000000%;7;0;28;100.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;87.50%;0.00%;12.50%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%
```

I think that means the value you are referring (`READ_bw_max`) to is `;15;` which in my example is in powers of 2 kilobytes. I would also guess it is per second unlike latency.

**Comment by sitsofe** [comment]
@Taragos would you like to submit a patch to update the documentation? It would mean changing the HOWTO and fio.1...

**Comment by sitsofe** [comment]
Closing due to lack of reply but if someone wants to submit a patch please feel free to do so!

**Comment by sitsofe** [comment]
Reopening as I've got a small patch. @thaotran9 does https://github.com/sitsofe/fio/commit/147dd8d621b5235350c2cd73dc20e0b3e68c1d43 help?
