### ISSUE TITLE
Client-server configuration does not work in version 3.22

### ISSUE THREAD

**Issue by alexeistepanov** [axboe/fio#1095]
Trying to run some workload but it very quickly fails without doing any I/O:
```
$ sudo fio --client=servername workload.fio
hostname=servername, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.22, flags=0
client: host=servername disconnected
```
When trying to run the same workload.fio file locally on the server "servername" it is perfectly accepted.
The same client-server setup is also working now after rolling back fio to version 3.1.

**Comment by axboe** [comment]
What workload are you trying to run? Please see:

https://github.com/axboe/fio/blob/master/REPORTING-BUGS

**Comment by alexeistepanov** [comment]
Hi Jens, the OS is Ubuntu 18.04.5 LTS with kernel 4.15.0-118-generic, the workload is very simple at the moment:
```
[global]
filename=/dev/sdb
direct=1
ioengine=libaio
stonewall
thread
group_reporting
norandommap
randrepeat=0
numjobs=1
[workload]
runtime=30
log_avg_msec=1000
disable_clat=1
disable_slat=1
rw=randread
blocksize=4k
iodepth=1
write_lat_log=workload
write_iops_log=workload
```

The server is running as
```
sudo fio --server
```

As said, when the same workload is started locally, it performs the reads and all the requested measurements.

The network connectivity is OK:
```
$ fio --version
fio-3.22
$ telnet servername 8765
Trying 192.168.168.2...
Connected to servername.
Escape character is '^]'.
lkjdsnfslkjnfkjdsnfkjsnf
fio: server bad crc on command (got 736a, wanted a618)
Connection closed by foreign host.
```

Basically the client and the server are two identically deployed VMs located on the same hardware. As already said, when rolling down to fio 3.1 bundled with Ubuntu, the same environment starts working without any other changes.

So maybe I'm building it wrong? Does the client/server feature require some implicit dependencies? E.g. like libaio-dev is required for libaio support of something like that? 

Thanks, regards, Alexei

**Comment by alexeistepanov** [comment]
Right, that's what I mean. When I start this same workload directly on the "server" it works just fine.

**Comment by axboe** [comment]
Just tried it here, and it works for me:

```
./fio --client=localhost repo.fio                         2016.417s
hostname=p1, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.23-28-g7064, flags=1
<p1> workload: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
<p1> Starting 1 thread
<p1> s: 0 (f=0)[r(1)][16.7%][r=221M][r=55.2k IOPS][eta 00m:25s]
```

Are you fio client and server the same version?

**Comment by alexeistepanov** [comment]
Yes, they both initially had 3.22 built from git, now I reverted both of them to 3.1
```
HEAD is now at 477b6753 Fio 3.22
$ make
FIO_VERSION = fio-3.22
```
I used to see the different versions on the client/server sides, normally fio explicitly tells about it to the stdout on the server side.

**Comment by axboe** [comment]
Just checked 3.22 and there does seem to be a bug there. Upgrade to 3.23 and it should be fine again.

**Comment by alexeistepanov** [comment]
Right, I've just got some time to rebuild the binaries and 3.23 seems to work. Thanks!
