### ISSUE TITLE
Avoid arithmetic on a pointer to void error in parse.h

### ISSUE THREAD

**Issue by chengli-rutgers** [axboe/fio#1096]
Hi guys --

We found there is an arithmetic on a pointer to void error in parse.h:128 when compiled with c++14 compiler. 
```
parse.h:128:13 error: arithmetic on a pointer to void
              return ret + offset;
                       ~~~ ^
```

To broaden fio's impact, we would like to see it can be compiled with recent c++ compilers.

More specifically, we would like to make the following change from
```
return ret + offset;
```
to 
```
return (void*) ((uint_8*) ret + offset);
```
We would like to get an opinion on whether this is something the fio community can help fix. Or, we could work on a patch to fix this issue as well.

**Comment by axboe** [comment]
Sure, if it's done cleanly enough. But have you checked the scope of this? It'll be quite a bit more than just that one spot in parse.h

**Comment by chengli-rutgers** [comment]
Thanks for the comments. The compiler only complains this spot so far. Please let us know if anything else must be handled if we change this line.

Our current plan is to only change this line and cherry pick it back to our branch.

**Comment by axboe** [comment]
You should be able to add -Wpointer-arith to the Makefile, that'll find a bunch more. I'm surprised your compiler only complains about the parse.h instance.

**Comment by chengli-rutgers** [comment]
You are right. The mainstream fio contains a bunch more.

Looks like we walked around most of the other `arithmetic on a pointer` instances by not linking them. But, the one in the parse.h are shared by many core source code so it is hard to walk around. So, the compiler only complains this particular instance. 

Is it still a valid patch (though not comprehensive) if we only change the instance in parse.h?

**Comment by axboe** [comment]
Yeah that's fine, feel free to send that patch in. Do note spacing though, follow the fio general codestyle. Which means it needs to look like this:

```
return (void *) ((uint_8 *) ret + offset);
```

and I think it'd be cleaner as:

```
return (void *) ((uintptr_t) ret + offset);
```

**Comment by sitsofe** [comment]
The original instance of this has been closed by https://github.com/axboe/fio/pull/1098 . As no one is working on the comprehensive case mentioned in https://github.com/axboe/fio/issues/1096#issuecomment-704614087 do we win much from keeping this open?
