### ISSUE TITLE
3.23 fails to build on FreeBSD i386

### ISSUE THREAD

**Issue by krionbsd** [axboe/fio#1099]
Some log files of failures:

http://beefy5.nyi.freebsd.org/data/121i386-default/551848/logs/fio-3.23.log
http://beefy10.nyi.freebsd.org/data/114i386-default/551848/logs/fio-3.23.log

**Comment by axboe** [comment]
Can you try current -git?

**Comment by krionbsd** [comment]
Unfortunately I don't have i386 at this moment, those builds were done on official freebsd build cluster

**Comment by axboe** [comment]
Should work in -git, and next release.

**Comment by krionbsd** [comment]
Cool, thanks a lot!
