### ISSUE TITLE
Avoid global variable initialization in getopt_long.c

### ISSUE THREAD

**Issue by chengli-rutgers** [axboe/fio#1100]
Hi guys --

Our Address Sanitizer (ASAN) analysis complains about a few global variables that are initialized in the getopt_long.c file. More specifically, the following variables can be cleaned up without a global initialization:

```
char *optarg = NULL;
int optind = 0, opterr = 0, optopt = 0;
```

1) optarg is initialized in oslib/getopt_long.c:49 so no need to initialize it in line 19.
2) optind is initialized in init.c:2477 so no need to initialize it in line 20.
3) opterr is initialized in oslib/getopt_long.c:188 so no need to initialize it in line 20.
4) opterr appears not to be used.

Also, we assume global variables will be initialized to zero by default.

So, we propose to change the code to the following:

```
char *optarg;
int optind, opterr, optopt;
```
Is it something that the fio community can help fix? Or, we can work on a patch to fix it as well.

**Comment by axboe** [comment]
Would be great if you can send a patch.
