### ISSUE TITLE
Fio doesn't show read and write values in majority of the cases

### ISSUE THREAD

**Issue by balvansh** [axboe/fio#1101]
Hi all,

Sorry as I am new to the FIO benchmark and benchmarking IO as a whole. I am testing tmpfs directories on my virtual machine. I am using a script to start multiple instances of FIO benchmark to test the multiple tmpfs directories (2-4 directories). However, most of the times I don't get the read and write values for at least one of the directories and the other results I get are very small for the size I am testing (2G- 4G). Below is the output I get, 

```
test1: (groupid=0, jobs=1): err= 0: pid=1537: Tue Oct 13 12:12:38 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=213, majf=0, minf=5
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=262179/w=786397/d=0, short=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
```

Is there an issue here with fio or my implementation of the filesystems causing an issue here?

**Comment by balvansh** [comment]
Sure, 

I am using a modified Debian based OS running on Linux Kernel 4.4.137. And the fio version is `fio-2.1.11`. 
The following is the command I am using - 
`taskset 0x2 fio --randrepeat=1 --ioengine=libaio --gtod_reduce=1 --name=test1 --bs=4k --iodepth=64 --readwrite=randrw --rwmixwrite=75 --size=2G --filename=/root/test1/testfile &`

My test requires FIO to be pinned to a vCPU.

**Comment by sitsofe** [comment]
FYI: fio can pin itself too - https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-cpus-allowed .

**Comment by balvansh** [comment]
Thank you for your help. I did compile the new fio and unfortunately, the problem still exists. 

```
Jobs: 1 (f=0): [f(1)][-.-%][r=36.5MiB/s,w=109MiB/s][r=9354,w=27.9k IOPS][eta 00m:00s]s]
test3: (groupid=0, jobs=1): err= 0: pid=16593: Tue Oct 13 21:51:25 2020
  cpu          : usr=0.00%, sys=0.00%, ctx=1, majf=0, minf=6
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=131562,392726,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64
```

Also I observed that `cpus_allowed` isn't working in my case which makes me wonder if there might be some issue from my end in the implementation of the filesystem for the VM. 

Thank you.

**Comment by sitsofe** [comment]
@balvansh I'm sorry I still don't follow. You say:

> However, most of the times I don't get the read and write values for at least one of the directories and the other results I get are very small for the size I am testing (2G- 4G).

Can you clarify the sort of output you're expecting to see (value foo should be 100 and value bar should 25) vs what you actually see (value for is 100 and value bar is not reported at all). Also full fio output include headers is useful.

**Comment by sitsofe** [comment]
@balvansh ping?

**Comment by balvansh** [comment]
@sitsofe since no one has faced a similar issue I am trying to debug and check if my system has a bug which is causing this issue.

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
