### ISSUE TITLE
Need to specify size

### ISSUE THREAD

**Issue by thomasvl-itr** [axboe/fio#1104]
Hello,

I am doing some test on nvme drives and ssd drives
I have the following script:
fio \
                --filename=$d \
                --bs=4k \
                --iodepth=128 \
                --numjobs=4 \
                --runtime=300 \
                --time_based \
                --direct=1 \
                --rw=randread \
                --ioengine=libaio \
                --group_reporting \
                --name=iops-randread \
                --output iops-randread-$dev-$2.out
        echo
        echo
done

There is no problem for nvme drives but for ssd I have the following error message:
iops-randread: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:824, func=total_file_size, error=Invalid argument

Why do I have to specify size while it is already limited by runtime ? And why does it work with nvme drives but not ssds ?

Thank you

Thomas

**Comment by sitsofe** [comment]
Hello @thomasvl-itr,

This suggests that the path to your SSD device was somehow not correct. Are you 100% sure that `$d` was the path to a real block device? If not you are expecting fio to create the file and in that case the file must have a size. Can you let us know? Maybe in your script do `file $d` or use `blockdev --report [...]` so you can confirm. It may also help if you add `set -x` at the top of your script so you can see what everything was set to.

You may also want to set [`allow_file_create=false`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-allow-file-create .) if fio should only ever be using pre-existing files.

Also be aware that if `$d` isn't being expanded by something else then fio will be expected to be an already defined environment variable (see https://fio.readthedocs.io/en/latest/fio_man.html#environment-variables ).

**Comment by sitsofe** [comment]
@thomasvl-itr any follow up on this?

**Comment by thomasvl-itr** [comment]
Hello,

I added a set -x at the beginning of my script, here is the output:
+ '[' 2 -eq 0 ']'
+ for d in '$1'
++ echo sdb
++ cut -d/ -f3
+ dev=sdb
++ cat /sys/block/sdb/device/model
+ model='Samsung SSD 860 '
++ cat /sys/block/sdb/size
+ size=488397168
+ echo 'READ read sdb on ubuntu with '\''Samsung SSD 860 '\'' (size: 488397168)'
READ read sdb on ubuntu with 'Samsung SSD 860 ' (size: 488397168)
+ sudo fio --filename=sdb --bs=64k --iodepth=64 --numjobs=4 --size=100% --runtime=10 --time_based --direct=1 --rw=randread --ioengine=libaio --group_reporting --readonly --name=raw-read --output bw-randrw-sdb-20201025-1413.out

Each of my devices seem to be correctly detected (I have sdb, sdc, sdd and sde for each output)

Script for my nvme drives is the same, only the path to the drives is different

Files are created after the script, allow_file_create should be set as true no ?

Thank you

Thomas

[cid:e36d5e39-5ef7-4de5-90fc-c08b286390f7]

Thomas Van Liefde  I  Electrical Engineer  I  Sesame by ITRenew

m. +33 169 307 334  I  e. thomas.van-liefde@itrenew.com

www.sesame.com

________________________________
De : Sitsofe Wheeler <notifications@github.com>
Envoyé : mercredi 21 octobre 2020 14:52
À : axboe/fio <fio@noreply.github.com>
Cc : Thomas Van-Liefde <Thomas.Van-Liefde@itrenew.com>; Mention <mention@noreply.github.com>
Objet : Re: [axboe/fio] Need to specify size (#1104)


Hello @thomasvl-itr<https://github.com/thomasvl-itr>,

This suggests that the path to your SSD device was somehow not correct. Are you 100% sure that $d was the path to a real block device? If not you are expecting fio to create the file and in that case the file must have a size. Can you let us know? Maybe in your script do file $d or use blockdev --report [...] so you can confirm. It may also help if you add set -x at the top of your script so you can see what everything was set to.

You may also want to set [allow_file_create=false](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-allow-file-create .) if fio should only ever be using pre-existing files.

Also be aware that if $d isn't being expanded by something else then fio will be expected to be an already defined environment variable (see https://fio.readthedocs.io/en/latest/fio_man.html#environment-variables ).

**Comment by sitsofe** [comment]
Just to double check: using `--filename=/dev/sdb` doesn't make a difference? Also if the block device files already exist why wouldn't it be safer to set `allow_file_create=false` because by definition the "file" (in this case the file representing the block device) already exists?

**Comment by thomasvl-itr** [comment]
My filename just had the device name and not /dev/device. I added the /dev and it now works as it should be
With my nvme device I could put directly the name of my nvme (nvme0n1 for example) and it worked, I thought I could do the same with SATA device and put directly the name (sdb for example)

Thank you !

**Comment by sitsofe** [comment]
I'm glad you got to the bottom of it. Closing this ticket.
