### ISSUE TITLE
The error "Bad system call" occurs

### ISSUE THREAD

**Issue by XTStarry** [axboe/fio#1107]
When I execute binary files using java code：
```java
process = Runtime.getRuntime().exec("sh");
successResult = new BufferedReader(new InputStreamReader(process.getInputStream()));
errorResult = new BufferedReader(new InputStreamReader(process.getErrorStream()));
dataOutputStream = new DataOutputStream(process.getOutputStream());

 // write command, the "command" is a shell command string
dataOutputStream.write(command.getBytes());
dataOutputStream.writeBytes("\n");
// flush buffer
dataOutputStream.flush();

dataOutputStream.close();
```
 on an Android device, the error "Bad system call" is returned.
Just "Bad system call", no others.

The error occurs in version 2.9.9. But I have the correct results with version 2.6.0.

**Comment by sitsofe** [comment]
@XTStarry I'm afraid I can't see anything about fio in the above (and there's no 2.6.0 version of fio see https://github.com/axboe/fio/tags?after=fio-2.7 ). Please post ALL the information requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS if you are reporting an fio bug. Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
