### ISSUE TITLE
Idea: provide a static binary every time a new fio version is released (fio/releases)

### ISSUE THREAD

**Issue by bavarianbidi** [axboe/fio#1108]
hey there,

just used `fio` quite often and last week i had to create `fio` by my own instead of using a pre-build package (provided by my linux distribution). However, i'm in a isolated network without access to the internet so i have done a `static build` of fio by running `EXTFLAGS="-static" make` and copied the fio-binary to the remote host and it works like a charm.

From my (very simplified view) on `fio`, i guess it should be very easy to extend the `travis-build` job / your current release process to build and share a static linux binary of `fio`. 

What do you think?

**Comment by sitsofe** [comment]
I think this is the same situation as over in https://github.com/axboe/fio/issues/858#issuecomment-619492064 (which was for docker). We're not really geared up to distribute Linux binaries (most people on Linux are familiar with compiling things themselves or are OK with their distro's version) and I can see it being a can of worms ("why did it fail in network mode?"). You even demonstrated how easy compiling it for yourself is! :-)

FYI: Did you know fio's `configure` even has a [`--build-static`](https://github.com/axboe/fio/blob/8bfe330eb42739d503d35d0b7d96f98c5c544204/configure#L198) flag?

**Comment by bavarianbidi** [comment]
> I think this is the same situation as over in [#858 (comment)](https://github.com/axboe/fio/issues/858#issuecomment-619492064) (which was for docker). We're not really geared up to distribute Linux binaries (most people on Linux are familiar with compiling things themselves or are OK with their distro's version) and I can see it being a can of worms ("why did it fail in network mode?"). You even demonstrated how easy compiling it for yourself is! :-)

totally fair! and yes, it isn't a big thing to build a static binary!

> FYI: Did you know fio's `configure` even has a [`--build-static`](https://github.com/axboe/fio/blob/8bfe330eb42739d503d35d0b7d96f98c5c544204/configure#L198) flag?

Ah, thanks for this hint ;-)

Thanks for your answer!

**Comment by bavarianbidi** [comment]
Just one last thing:

i offer myself to do all the work (implement build steps, ...) which is required to build official docker-images and/or static binaries.
Feel free to get in contact with me, otherwise just close this issue.

**Comment by axboe** [comment]
I'd be fine with such an addition, so a static build (and others) would be part of the CI artifacts. So feel free to implement that.

**Comment by sitsofe** [comment]
Closing this because none of the core developers are working on it. If someone does want to work on this please submit a pull request and re-open this issue at that point.
