### ISSUE TITLE
No way to determine where to put verification dumps and state files while verifying data.

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#111]
While using the verify_dump parameter, state files are output to the current working directory.  It would be more ideal to be able to put these into a predetermined folder based off of a parameter in the job file rather than have them repeatedly dumped to the working directory.  This would make the file out put for dumps and state files behave much like the write_bw_log or write_iops_log parameters do.
My current working directory after firing a complex fio job looks like this
<pre><code>
fio-app:~# ls
.ICE-unix        fio-fio-2.2.8                  local-mpathyv-4-verify.state   local-mpathza-9-verify.state   local-mpathzf-22-verify.state  local-mpathzk-8-verify.state   local-mpathzp-3-verify.state   local-mpathzu-25-verify.state  unique
.X0-lock         fio-fio-2.2.8.zip              local-mpathyw-13-verify.state  local-mpathzb-10-verify.state  local-mpathzg-19-verify.state  local-mpathzl-11-verify.state  local-mpathzq-21-verify.state  mechanize                      virtual-fusion.y1FnVT
.X11-unix        fio-fio-2.2.9                  local-mpathyw-5-verify.state   local-mpathzb-16-verify.state  local-mpathzg-23-verify.state  local-mpathzl-20-verify.state  local-mpathzq-6-verify.state   multipath.conf.ha.sles11sp2    virtual-root.FRLbPR
.esd-0           fio-fio-2.2.9.zip              local-mpathyx-0-verify.state   local-mpathzc-15-verify.state  local-mpathzh-24-verify.state  local-mpathzm-10-verify.state  local-mpathzr-24-verify.state  orbit-fusion                   virtual-root.Xlh0Wi
.esd-1000        keyring-fwqvNu                 local-mpathyx-14-verify.state  local-mpathzc-7-verify.state   local-mpathzh-7-verify.state   local-mpathzm-25-verify.state  local-mpathzr-5-verify.state   orbit-gdm                      xwlog
.esd-107         keyring-vxfh1H                 local-mpathyy-1-verify.state   local-mpathzd-18-verify.state  local-mpathzi-17-verify.state  local-mpathzn-13-verify.state  local-mpathzs-1-verify.state   orbit-root
authfirewall.py  libstorage-OcPF6t              local-mpathyy-11-verify.state  local-mpathzd-8-verify.state   local-mpathzi-6-verify.state   local-mpathzn-26-verify.state  local-mpathzs-23-verify.state  perflogs
file2Hi3rw       local-mpathyu-15-verify.state  local-mpathyz-12-verify.state  local-mpathze-17-verify.state  local-mpathzj-18-verify.state  local-mpathzo-12-verify.state  local-mpathzt-0-verify.state   pulse-BznrqHrYvtx8
fileyaPgy8       local-mpathyu-3-verify.state   local-mpathyz-2-verify.state   local-mpathze-21-verify.state  local-mpathzj-9-verify.state   local-mpathzo-4-verify.state   local-mpathzt-26-verify.state  pulse-H33KYWr7zj2p
fio              local-mpathyv-16-verify.state  local-mpathza-14-verify.state  local-mpathzf-20-verify.state  local-mpathzk-19-verify.state  local-mpathzp-22-verify.state  local-mpathzu-2-verify.state   pulse-HqV2KMTHmRC4
</code></pre>

**Comment by axboe** [comment]
We should just add a 'verify_dump_path' option. Or maybe a more generic parameter, so it would cover other files too - like the verification state saves shown above as well.

**Comment by DaveGlen** [comment]
An option to store all generated files to the same settable path would be great. 
Right now I do that in shell wrappers instead of specifying in the path of write_bw_log and the like.

**Comment by axboe** [comment]
Can you try current -git? I added support for --aux-path as a command line option, which you can set to something that isn't cwd. Note that this is a fio option, not a job file option.

**Comment by axboe** [comment]
Tested it myself today. There was a typo in the verify state string generation, but I've fixed that up. Works for me now.
