### ISSUE TITLE
[Question] Detect bw/iops drop with fio

### ISSUE THREAD

**Issue by yhemery** [axboe/fio#1112]
Hi,

I'm looking for a fio setup which would allow me to detect sudden performance drops, and stop the associated jobs. The idea is to detect thermal throttling or other performance bottlenecks, for example an SLC cache filled on a SSD.

The "Steady State" option seems to be a good starting point, but it doesn't look like we can stop a job when we leave this steady state, only when we reach it.

Did I miss an option, or is this something not currently possible with fio ?

Thanks.

**Comment by yhemery** [comment]
Sadly no, I have some latency spikes in normal conditions :

`     lat (usec): min=12993, max=60813, avg=22020.75, stdev=2501.51`

If my use case is not possible with fio yet and is too specific, I'll analyse the fio output in a separated script, that's not a big deal.

**Comment by vincentkfu** [comment]
Consider these two options:

https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-rate-min
https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-rate-iops-min

**Comment by yhemery** [comment]
Hi,

That seems to be the best solution available today indeed, thanks @vincentkfu . This highlighted some short performance drops on my test setup, that's perfect.
