### ISSUE TITLE
fio-3.4 version number issue

### ISSUE THREAD

**Issue by DreamInit** [axboe/fio#1118]
fio-3.4 file FIO-VERSION-GEN 
DEF_VER=fio-3.3

**Comment by sitsofe** [comment]
@DreamInit Hi,

Thanks for reporting. This was actually "fixed" in fio-3.5 (see https://github.com/axboe/fio/commit/cd174b909109e527e41ca42ac761c5f7d29f25e5 ). As we (upstream) only support the latest fio (see https://github.com/axboe/fio/releases for which version we're up to) we'll consider this one closed.
