### ISSUE TITLE
run job only if filename=/dev/blockdevice

### ISSUE THREAD

**Issue by vasukulkarni** [axboe/fio#112]
if user specify filename=/dev/devicename and the devicename doesn't exist, it ends up creating huge data file based on fio job config file, can there be some parameter to specify only use block device if not exit the job with error code

**Comment by vasukulkarni** [comment]
Seen with latest stable release 2.2.9

**Comment by axboe** [comment]
You can set:

allow_file_create=0

then fio won't ever create any files for jobs. If you had that for the above case, then it would have errored out instead of filling /dev with a non-special file.

**Comment by vasukulkarni** [comment]
Thanks @axboe , will set that parameter
