### ISSUE TITLE
how to use zone append 

### ISSUE THREAD

**Issue by fengjiansunren** [axboe/fio#1121]
hwo can i use zone append ? i can't find zone append in fio , just find follow:

```
; Using the libaio ioengine, random write to a (zoned) block device,
; writing at most 32 zones at a time. Target zones are chosen randomly
; and writes directed at the write pointer of the chosen zones

[global]
name=zbd-rand-write
group_reporting
rw=randwrite
zonemode=zbd
zonesize=256M
max_open_zones=32
bs=512K
direct=1
numjobs=16
time_based=1
runtime=180

[dev1]
filename=/dev/sdj
ioengine=psync
```

**Comment by sitsofe** [comment]
As mentioned in https://www.spinics.net/lists/fio/msg08659.html it sounded like the kernel interface was unstable/had yet to be completely decided. Do you know if said kernel interface is now stable?

**Comment by sitsofe** [comment]
Setting to needsreporterinfo pending reply from @fengjiansunren .

**Comment by sitsofe** [comment]
(It also looks like @fengjiansunren left a comment on https://github.com/axboe/fio/pull/1026#issuecomment-723847972 )

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
