### ISSUE TITLE
about verify_backlog

### ISSUE THREAD

**Issue by jiang4357291** [axboe/fio#1122]
I have read the [fio doc](https://fio.readthedocs.io/en/latest/fio_doc.html) abut verify_backlog, but still confused,
what's the difference between those two params?
--verify=crc32c-intel --verify_fatal=1 --verify_async=4  --verify_dump=1
--verify=crc32c-intel --verify_fatal=1 --verify_async=4  --verify_dump=1 --verify_backlog=1048576

**Comment by sitsofe** [comment]
@jiang4357291 before I answer this what do YOU understand by what was written on each of the following:
- `verify=crc32c-intel` from https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify
- `verify_backlog` from https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-backlog
- `verify_async ` from https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-async

The reason I ask is it would be for us to understand what people are taking away from the existing documentation because maybe you will have suggestions on how to fix it...

(Setting to needsreporterinfo pending reply from @jiang4357291 )

**Comment by jiang4357291** [comment]
- verify=crc32c-intel ：set verification method to crc32c, this will compute crc32c sum of the data area and store it in the header of each block
- verify_backlog : This one is which i'm confused, I'm not sure if i understand correctly. If not set, fio will verify only one time when job finished? If set to N, fio will verify  once when N blocks is written, then start written another blocks?
- verify_async : start several threads to verify instead of do verification in io thread

**Comment by sitsofe** [comment]
@jiang4357291 That's pretty much it! So back to your question - what do you think the difference between your jobs is?

**Comment by jiang4357291** [comment]
@sitsofe The first one will only do one verification after io job completed, the second will verify once every 1048576 blocks,is this right? what confused me is i can see read iops in the second one, it must be veriry read, but the read iops is always zero in the first one, so i'm not sure whether fio has complete verify or not

**Comment by sitsofe** [comment]
@jiang4357291 

> The first one will only do one verification after io job completed, the second will verify once every 1048576 blocks,is this right?

Very nearly. The one subtlety is that a `verify_backlog` job will actually ALSO do a post verification phase by default too:
```
fio --debug=verify --name=test --rw=write --size=10M --verify=crc32c --verify_backlog=1
```

That verifies after every I/O is written AND there's a post write phase verification too (notice something like `verify   771   starting loop` which corresponds to https://github.com/axboe/fio/blob/fio-3.23/backend.c#L627 and is not to do with the backlog verify)! If you want to turn that off the post verification pass you'll have to add `--do_verify=0`

> what confused me is i can see read iops in the second one, it must be veriry read, but the read iops is always zero in the first one, so i'm not sure whether fio has complete verify or not

I think we'd have to see the full job to know more to understand this part...

**Comment by jiang4357291** [comment]
@sitsofe  Thanks a lot.
