### ISSUE TITLE
Memory consumption increased by ~x3 since v3.17

### ISSUE THREAD

**Issue by cpaelzer** [axboe/fio#1123]
Hi,
I was tracking an OOM issue in Ubuntu autopkgtest testing.
I found that fio memory consumption increased from ~425M to ~1.1G.

The load isn't that huge, a 100M image file with 93M Filesystem and 91M file.
The fio load on that is a time based run like

While I found this exclusively on ppc64 at fist, that was only because it had the
tightest memory. I can reproduce it even on an x86 container on my laptop with:

```
$ cat > memincrease.fio << EOF
[global]
directory=/tmp/
filename=datafile.tmp
bs=64k
ioengine=sync
size=100M
rw=read

[memincrease]
stonewall
runtime=10
time_based
EOF
$ fio testme.fio
```

Info from "smem -tk" while running:

```
         PID User     Command                         Swap      USS      PSS      RSS 
good   70469 root     /usr/local/bin/fio /tmp/tmp        0   425.9M   426.2M   429.8M 
middle 67731 root     /usr/local/bin/fio /tmp/tmp        0   775.5M   775.8M   779.4M 
bad    90283 root     /usr/local/bin/fio /tmp/tmp        0     1.1G     1.1G     1.1G 
```

While bisecting I found a third state that has ~777M memory consumption,
therefore two bisect results:

- consider ~777M  bad/new

```
git bisect start
# new: [ac694f66968fe7b18c820468abd8333f3df333fb] Fio 3.18
git bisect new ac694f66968fe7b18c820468abd8333f3df333fb
# old: [08ce9dc20b8a4e55db7af6d869ddfa49b4a02d03] Fio 3.17
git bisect old 08ce9dc20b8a4e55db7af6d869ddfa49b4a02d03
# old: [5d3a1a0dc53b73aeaddd3f6c9aab3336ca3ff0b9] Merge branch 'master' of https://github.com/bvanassche/fio
git bisect old 5d3a1a0dc53b73aeaddd3f6c9aab3336ca3ff0b9
# old: [2c1520d72d10ee4d203f0d7f1d31d0ac6d3d84a4] t/read-to-pipe-async: Complain if pthread_detach() fails
git bisect old 2c1520d72d10ee4d203f0d7f1d31d0ac6d3d84a4
# new: [4ee9c375b64de236356cc97843d84978edeba491] stat: ensure we align correctly
git bisect new 4ee9c375b64de236356cc97843d84978edeba491
# old: [283feb79db4b21f8b447e62a8635dc5124904151] stat: Remove several superfluous if-tests
git bisect old 283feb79db4b21f8b447e62a8635dc5124904151
# old: [ebae36a28aeedcb39ae86fde020502cfbb9dc65b] client: Fix memory leaks in handle_job_opt()
git bisect old ebae36a28aeedcb39ae86fde020502cfbb9dc65b
# old: [7a4e480d8875a31bee6f2a39c87c25e276cec616] Whitespace standardization
git bisect old 7a4e480d8875a31bee6f2a39c87c25e276cec616
# new: [6447b4c297fefce060f6f3c44f7a5c34a869eaa3] Merge branch 'priorityQueuing' of https://github.com/Seagate/fio
git bisect new 6447b4c297fefce060f6f3c44f7a5c34a869eaa3
# new: [b2a432bfbb6d10e93f2c8f8092d6db672d45af0d] Per-command priority: Priority logging and libaio/io_uring cmdprio_percentage
git bisect new b2a432bfbb6d10e93f2c8f8092d6db672d45af0d
# first new commit: [b2a432bfbb6d10e93f2c8f8092d6db672d45af0d] Per-command priority: Priority logging and libaio/io_uring cmdprio_percentage
```

- consider ~777M  good/old

```
git bisect start
# old: [08ce9dc20b8a4e55db7af6d869ddfa49b4a02d03] Fio 3.17
git bisect old 08ce9dc20b8a4e55db7af6d869ddfa49b4a02d03
# new: [ac694f66968fe7b18c820468abd8333f3df333fb] Fio 3.18
git bisect new ac694f66968fe7b18c820468abd8333f3df333fb
# old: [5d3a1a0dc53b73aeaddd3f6c9aab3336ca3ff0b9] Merge branch 'master' of https://github.com/bvanassche/fio
git bisect old 5d3a1a0dc53b73aeaddd3f6c9aab3336ca3ff0b9
# old: [2c1520d72d10ee4d203f0d7f1d31d0ac6d3d84a4] t/read-to-pipe-async: Complain if pthread_detach() fails
git bisect old 2c1520d72d10ee4d203f0d7f1d31d0ac6d3d84a4
# old: [4ee9c375b64de236356cc97843d84978edeba491] stat: ensure we align correctly
git bisect old 4ee9c375b64de236356cc97843d84978edeba491
# new: [3e306f32b029445a0d1457897fbf700c92940a84] gfio: display slat, clat, and lat percentiles
git bisect new 3e306f32b029445a0d1457897fbf700c92940a84
# old: [f07528f0629efa0c55bbdb1bdcc9dfdacc32fb47] Merge branch 'openbsd_swap' of https://github.com/bsdkurt/fio
git bisect old f07528f0629efa0c55bbdb1bdcc9dfdacc32fb47
# old: [f07528f0629efa0c55bbdb1bdcc9dfdacc32fb47] Merge branch 'openbsd_swap' of https://github.com/bsdkurt/fio
git bisect old f07528f0629efa0c55bbdb1bdcc9dfdacc32fb47
# old: [ab45cf076766ce1ed49d28380c059343305cde4a] Merge branch 'stat-averaging-interval-start-fix' of https://github.com/maciejsszmigiero/fio
git bisect old ab45cf076766ce1ed49d28380c059343305cde4a
# new: [56440e63ac17d020a58e20a2341333a98f18a7ff] fio: report percentiles for slat, clat, lat
git bisect new 56440e63ac17d020a58e20a2341333a98f18a7ff
# new: [df8781b62a9d0dffae40d86916feff3659a5fb7e] fio: groundwork for adding slat, lat percentiles
git bisect new df8781b62a9d0dffae40d86916feff3659a5fb7e
# first new commit: [df8781b62a9d0dffae40d86916feff3659a5fb7e] fio: groundwork for adding slat, lat percentiles
```

Both identified changes commit df8781b6 and commit b2a432bf by the bisects are around slat/clat/lat statistical data. That could bump the memory, but so much? Especially since I haven't explicitly "enabled" anything in that regard.

The identified commits made me think of the disable options

- disable_clat
- disable_slat
- disable_lat
- disable_bw_measurement

But even with all of them set the consumption still is at ~1.1G

I'm not entirely sure it is "a bug" (up to you), but it surely is a huge change
of behavior for any small environment (OOMs like in my case) and anyone who
measures with page cache as well I'd guess.

I wanted to ask if there at least should be an option that allows cutting
memory consumption back down somehow?

**Comment by sitsofe** [comment]
@cpaelzer For at least df8781b62a9d0dffae40d86916feff3659a5fb7e I'm not surprised memory usage went up because `io_u_plat` became three times bigger than it used to be (see https://github.com/axboe/fio/blob/df8781b62a9d0dffae40d86916feff3659a5fb7e/stat.h#L201 ). This also isn't memory that is allocated on demand so the disabling options would have no impact on it... C arrays aren't sparse so if you wanted to make it only allocate when appropriate options are on you would probably have to do some sort of indirection where you have a small array that tells you how to get to the real one. I also don't know how easy dropping a data structure will be given client/server mode and serialisation...

**Comment by axboe** [comment]
Can be worked around by shrinking max-jobs, something I wish we could do dynamically. Add ```---max-jobs=N``` to your command line, where N is the most number of jobs you'd use.

**Comment by cpaelzer** [comment]
Thanks for the hint @axboe since my workload only needs 1 job I can set it to one without any impact to the I/O and results.
On the memory side thou, this has a massive effect it is down from 1.1G to ~10M which is two orders of magnitude down - impressing and unexpected.

I'm fine from my current POV and can work around the problem with that, but I wanted to ask if it seems reasonable to ask for a feature that fio could pre-process the #threads it really will need and only run with that?

**Comment by axboe** [comment]
> I'm fine from my current POV and can work around the problem with that, but I wanted to ask if it seems reasonable to ask for a feature that fio could pre-process the #threads it really will need and only run with that?

Definitely, that's what I was alluding to when mentioning it should be dynamic. It's been on my mental TODO list for quite a while, maybe it's time to do it :-)

**Comment by axboe** [comment]
Alright, did that. Can you try the segmented-threads branch? Work in progress, but ran a few tests and it works for me. Running a basic job:

Before:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 404933 axboe     20   0 1368768   1.1g   1.1g S  14.7   3.5   0:00.44 fio
```

After:
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  19611 root      20   0  181108   1072      8 R  97.9   0.0   0:05.30 fio                     
```

which is quite a substantial difference...

The basic premise is that instead of allocating enough room for the max number of threads up front, we split the structure into an intermediate thread_segment that we can add on demand. If we need a new segment, we add enough for 8 threads. The upper limit is still the same as before, but we just add it in chunks as needed.

**Comment by axboe** [comment]
Just use 'master' for the test, I pulled in the branch.

**Comment by cpaelzer** [comment]
Hi @axboe and thanks!
I tested a few cases I had with current master (commit 2ee239fb) and can confirm that

 - a) all my tests still work
 - b) the memory pressure is gone

**Comment by axboe** [comment]
Great! Thanks for both verifying the memory consumption is fixed, but also that it didn't inadvertently break other jobs. Closing this one.

**Comment by sitsofe** [comment]
Nice work @axboe !
