### ISSUE TITLE
When do_verify=1 phase runs, statistics are recorded for verifying reads

### ISSUE THREAD

**Issue by oulaiwanle** [axboe/fio#1124]
HI:
  When running the below FIO cmd  , the report has no read details.
```
fio --name=aa --direct=1 --ioengine=libaio --do_verify=1 --verify=md5 --verify_dump=1  --refill_buffers --blocksize=4k --rw=randwrite --iodepth=1 --group_reporting --size=10G --randrepeat=0 --serialize_overlap=1 --filename=/dev/nvme0n1 --verify_backlog=1000 --runtime=10 --time_based --verify_backlog=1000
```

 Report  below:
```
aa: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.23
Starting 1 process
Jobs: 1 (f=1): [V(1)][30.0%][r=19.9MiB/s,w=19.6MiB/s][r=5087,w=5005 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][40.0%][r=22.3MiB/s,w=19.5MiB/s][r=5703,w=5000 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][50.0%][r=22.3MiB/s,w=23.5MiB/s][r=5701,w=6006 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][60.0%][r=23.2MiB/s,w=23.5MiB/s][r=5926,w=6006 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][70.0%][r=26.1MiB/s,w=27.4MiB/s][r=6683,w=7007 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][80.0%][r=23.5MiB/s,w=23.4MiB/s][r=6011,w=6000 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][90.0%][r=21.4MiB/s,w=19.6MiB/s][r=5488,w=5005 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][100.0%][r=22.1MiB/s,w=23.5MiB/s][r=5658,w=6006 IOPS][eta 00m:00s]

aa: (groupid=0, jobs=1): err= 0: pid=2615: Thu Nov 12 17:16:15 2020
  write: IOPS=5999, BW=23.4MiB/s (24.6MB/s)(234MiB/10001msec); 0 zone resets
    slat (usec): min=10, max=703, avg=16.38, stdev=11.65
    clat (nsec): min=1121, max=803607, avg=17461.28, stdev=15221.22
     lat (usec): min=24, max=843, avg=33.92, stdev=20.44
    clat percentiles (usec):
     |  1.00th=[   14],  5.00th=[   14], 10.00th=[   15], 20.00th=[   15],
     | 30.00th=[   16], 40.00th=[   16], 50.00th=[   16], 60.00th=[   17],
     | 70.00th=[   17], 80.00th=[   18], 90.00th=[   21], 95.00th=[   24],
     | 99.00th=[   34], 99.50th=[   61], 99.90th=[  281], 99.95th=[  343],
     | 99.99th=[  537]
   bw (  KiB/s): min=17568, max=32000, per=100.00%, avg=23997.47, stdev=3228.71, samples=19
   iops        : min= 4392, max= 8000, avg=5999.37, stdev=807.18, samples=19
  lat (usec)   : 2=0.02%, 4=0.03%, 10=0.03%, 20=52.40%, 50=15.97%
  lat (usec)   : 100=0.23%, 250=30.36%, 500=0.81%, 750=0.09%, 1000=0.05%
  lat (msec)   : 2=0.01%, 4=0.01%, 10=0.01%
  cpu          : usr=27.45%, sys=8.21%, ctx=119712, majf=0, minf=40
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=59240,60000,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=23.4MiB/s (24.6MB/s), 23.4MiB/s-23.4MiB/s (24.6MB/s-24.6MB/s), io=234MiB (246MB), run=10001-10001msec

Disk stats (read/write):
  nvme0n1: ios=58332/59000, merge=0/0, ticks=5706/924, in_queue=8, util=99.30%
```
We  can see test size=10G  larger then real test size=234M ;and  use verify_backlog=1000 ,it shuld be verified during test.
but the Report has no  read details ,write times=runtime=60s(Is that main no read?)

I'm wondering if the above behavior is right.
 Fio verision is fio-3.23

Thanks

**Comment by sitsofe** [comment]
@oulaiwanle,

`rw=randwrite`

Fio doesn't time the verification I/Os and you never asked for a reads as part of your job? What reads were you expecting to see timing on?

**Comment by sitsofe** [comment]
Setting needreporterinfo pending reply from @oulaiwanle

**Comment by oulaiwanle** [comment]
If fio doesn't collect detailed data on the verification I/Os ,why it has read details when use the cmd below:

fio --name=aa --direct=1 --ioengine=libaio --do_verify=1 --verify=md5 --verify_dump=1 --verify_backlog=1000 --refill_buffers --blocksize=4k --rw=randwrite --iodepth=1 --group_reporting --size=1m --randrepeat=0 --serialize_overlap=1 --filename=/dev/nvme0n1 --verify_backlog=1000 --runtime=10 --time_based
aa: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.23
Starting 1 process
Jobs: 1 (f=1): [w(1)][30.0%][r=15.0MiB/s,w=14.9MiB/s][r=4093,w=3805 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][40.0%][r=16.0MiB/s,w=17.1MiB/s][r=4102,w=4390 IOPS][eta 00
Jobs: 1 (f=1): [w(1)][50.0%][r=15.0MiB/s,w=14.4MiB/s][r=4085,w=3686 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][60.0%][r=13.8MiB/s,w=13.6MiB/s][r=3529,w=3484 IOPS][eta 00
Jobs: 1 (f=1): [w(1)][70.0%][r=18.3MiB/s,w=18.0MiB/s][r=4674,w=4612 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][80.0%][r=20.4MiB/s,w=22.0MiB/s][r=5234,w=5632 IOPS][eta 00
Jobs: 1 (f=1): [w(1)][90.0%][r=21.6MiB/s,w=20.6MiB/s][r=5518,w=5269 IOPS][eta 00
Jobs: 1 (f=1): [V(1)][100.0%][r=22.3MiB/s,w=23.4MiB/s][r=5719,w=5989 IOPS][eta 00m:00s]
aa: (groupid=0, jobs=1): err= 0: pid=20807: Fri Nov 13 14:17:25 2020
  read: IOPS=9888, BW=38.6MiB/s (40.5MB/s)(188MiB/4867msec)
    slat (usec): min=2, max=26948, avg=31.22, stdev=639.51
    clat (nsec): min=825, max=8722.8k, avg=47875.71, stdev=156564.00
     lat (usec): min=15, max=27188, avg=79.34, stdev=660.22
    clat percentiles (usec):
     |  1.00th=[   15],  5.00th=[   15], 10.00th=[   16], 20.00th=[   17],
     | 30.00th=[   18], 40.00th=[   20], 50.00th=[   22], 60.00th=[   23],
     | 70.00th=[   24], 80.00th=[   37], 90.00th=[  121], 95.00th=[  133],
     | 99.00th=[  243], 99.50th=[  404], 99.90th=[ 2278], 99.95th=[ 3523],
     | 99.99th=[ 6652]
  write: IOPS=10.2k, BW=39.7MiB/s (41.6MB/s)(188MiB/4734msec); 0 zone resets
    slat (usec): min=10, max=29429, avg=55.54, stdev=616.54
    clat (nsec): min=789, max=9968.3k, avg=27868.19, stdev=128733.12
     lat (usec): min=23, max=29454, avg=83.70, stdev=631.57
    clat percentiles (usec):
     |  1.00th=[   14],  5.00th=[   15], 10.00th=[   16], 20.00th=[   17],
     | 30.00th=[   18], 40.00th=[   19], 50.00th=[   21], 60.00th=[   23],
     | 70.00th=[   24], 80.00th=[   24], 90.00th=[   26], 95.00th=[   33],
     | 99.00th=[  109], 99.50th=[  273], 99.90th=[ 1811], 99.95th=[ 3261],
     | 99.99th=[ 5276]
   bw (  KiB/s): min=12288, max=25168, per=46.73%, avg=19005.95, stdev=3957.24, samples=19
   iops        : min= 3072, max= 6292, avg=4751.42, stdev=989.30, samples=19
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.08%, 4=0.14%, 10=0.14%, 20=46.54%, 50=42.86%
  lat (usec)   : 100=0.96%, 250=8.54%, 500=0.37%, 750=0.09%, 1000=0.07%
  lat (msec)   : 2=0.10%, 4=0.07%, 10=0.03%
  cpu          : usr=25.49%, sys=9.88%, ctx=100108, majf=1, minf=32
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=48128,48128,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=38.6MiB/s (40.5MB/s), 38.6MiB/s-38.6MiB/s (40.5MB/s-40.5MB/s), io=188MiB (197MB), run=4867-4867msec
  WRITE: bw=39.7MiB/s (41.6MB/s), 39.7MiB/s-39.7MiB/s (41.6MB/s-41.6MB/s), io=188MiB (197MB), run=4734-4734msec

Disk stats (read/write):
  nvme0n1: ios=55222/47616, merge=0/0, ticks=2320/921, in_queue=0, util=72.10%

The differnt with two cmd is size=1m < real test size= 188MiB

Thanks

**Comment by sitsofe** [comment]
@oulaiwanle (For future posts can you also add the markup for the fixed width parts? Thanks!)

Oh you changed to a different fio for the second job? This will confuse things as you didn't draw attention to this... We (upstream) can only process problems that still happen in the newest fio (like your first comment) and I can well believe the behaviour has changed between different fio versions. Can you do your second case with the same fio as your original comment and we'll continue from there. Thanks!

**Comment by oulaiwanle** [comment]
@sitsofe 

Sorry ,I  have test it in the newest fio;and change test report in the second comment 
Thanks!

**Comment by sitsofe** [comment]
Does adding `--do_verify=0` change things?

**Comment by oulaiwanle** [comment]
If `--do_verify=0`,both of the two test reprots only have write detials:
'''
 nvme0n1: ios=51/331430, merge=0/0, ticks=8/4900, in_queue=0, util=99.30%
root@gaia:~/Desktop/fio-fio-3.23# ./fio --name=aa --direct=1 --ioengine=libaio --do_verify=0 --verify=md5 --verify_dump=1 --verify_backlog=1000 --refill_buffers --blocksize=4k --rw=randwrite --iodepth=1 --group_reporting --size=10G --randrepeat=0 --serialize_overlap=1 --filename=/dev/nvme0n1 --verify_backlog=1000 --runtime=10 --time_based
'''
'''
aa: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.23
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=141MiB/s][w=36.1k IOPS][eta 00m:00s]
aa: (groupid=0, jobs=1): err= 0: pid=11550: Tue Nov 17 14:25:56 2020
  write: IOPS=35.9k, BW=140MiB/s (147MB/s)(1401MiB/10001msec); 0 zone resets
    slat (usec): min=10, max=799, avg=10.87, stdev= 4.28
    clat (nsec): min=877, max=1361.3k, avg=15210.37, stdev=8762.81
     lat (usec): min=23, max=1372, avg=26.17, stdev= 9.94
    clat percentiles (usec):
     |  1.00th=[   14],  5.00th=[   14], 10.00th=[   14], 20.00th=[   15],
     | 30.00th=[   15], 40.00th=[   15], 50.00th=[   15], 60.00th=[   15],
     | 70.00th=[   16], 80.00th=[   16], 90.00th=[   16], 95.00th=[   17],
     | 99.00th=[   20], 99.50th=[   27], 99.90th=[  133], 99.95th=[  176],
     | 99.99th=[  351]
   bw (  KiB/s): min=137584, max=145160, per=100.00%, avg=143600.42, stdev=1820.50, samples=19
   iops        : min=34396, max=36290, avg=35900.21, stdev=455.09, samples=19
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=99.09%, 50=0.61%
  lat (usec)   : 100=0.15%, 250=0.11%, 500=0.02%, 750=0.01%, 1000=0.01%
  lat (msec)   : 2=0.01%
  cpu          : usr=44.23%, sys=11.71%, ctx=358994, majf=0, minf=15
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,358643,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=140MiB/s (147MB/s), 140MiB/s-140MiB/s (147MB/s-147MB/s), io=1401MiB (1469MB), run=10001-10001msec

Disk stats (read/write):
  nvme0n1: ios=51/355020, merge=0/0, ticks=8/5049, in_queue=0, util=99.34%
root@gaia:~/Desktop/fio-fio-3.23# ./fio --name=aa --direct=1 --ioengine=libaio --do_verify=0 --verify=md5 --verify_dump=1 --verify_backlog=1000 --refill_buffers --blocksize=4k --rw=randwrite --iodepth=1 --group_reporting --size=10M --randrepeat=0 --serialize_overlap=1 --filename=/dev/nvme0n1 --verify_backlog=1000 --runtime=10 --time_based
aa: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.23
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=118MiB/s][w=30.2k IOPS][eta 00m:00s]
aa: (groupid=0, jobs=1): err= 0: pid=11566: Tue Nov 17 14:26:43 2020
  write: IOPS=29.4k, BW=115MiB/s (121MB/s)(1149MiB/10000msec); 0 zone resets
    slat (usec): min=10, max=22386, avg=16.65, stdev=230.41
    clat (nsec): min=872, max=5595.6k, avg=15555.36, stdev=23672.35
     lat (usec): min=23, max=22412, avg=32.26, stdev=231.81
    clat percentiles (usec):
     |  1.00th=[   14],  5.00th=[   14], 10.00th=[   14], 20.00th=[   15],
     | 30.00th=[   15], 40.00th=[   15], 50.00th=[   15], 60.00th=[   15],
     | 70.00th=[   16], 80.00th=[   16], 90.00th=[   16], 95.00th=[   17],
     | 99.00th=[   24], 99.50th=[   41], 99.90th=[  151], 99.95th=[  237],
     | 99.99th=[  889]
   bw (  KiB/s): min=109496, max=122880, per=100.00%, avg=117836.21, stdev=3184.39, samples=19
   iops        : min=27374, max=30720, avg=29459.05, stdev=796.10, samples=19
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=98.36%, 50=1.23%
  lat (usec)   : 100=0.20%, 250=0.13%, 500=0.03%, 750=0.01%, 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%, 10=0.01%
  cpu          : usr=36.90%, sys=16.32%, ctx=295300, majf=0, minf=15
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,294268,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=115MiB/s (121MB/s), 115MiB/s-115MiB/s (121MB/s-121MB/s), io=1149MiB (1205MB), run=10000-10000msec

Disk stats (read/write):
  nvme0n1: ios=2386/291535, merge=0/0, ticks=392/4485, in_queue=20, util=91.22%

**Comment by sitsofe** [comment]
So I think what is happening is that the reads come from when fio does a "verify pass". Using `--verify=<valid value> --verify_backlog=<non-zero number>` doesn't actually stop a "verify pass" being done after the "regular" pass completes (hence you get reads). However, using `--verify=<valid value> --time_based` actually leads to the time being consumed by the "regular pass" so there is no time to do the "verify pass"...

**Comment by oulaiwanle** [comment]
So this behavior is expected ?

**Comment by sitsofe** [comment]
@oulaiwanle I'm unsure :-) Is it harmful?

**Comment by oulaiwanle** [comment]
Some times I just want to know how mang datas it is verified during the test .
But I find there is 100% write during test time in the report ,and it makes me confused

**Comment by sitsofe** [comment]
@oulaiwanle it's going to be tricky because verify_backlog reads are never recorded in the stats so I don't think there's anything that fits your use case perfectly. Would you like to rephrase your report as a feature request?

**Comment by oulaiwanle** [comment]
@sitsofe  
OK 
Thanks!

**Comment by sitsofe** [comment]
Closing as I think we've explained this one.
