### ISSUE TITLE
Are there any ways to generate a bitmap indicating which block is written with FIO?

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1125]
Hi,

I am seeking the method to generate a bitmap after the completion of the IO via FIO tool, ideally, I could decide the size of the bitmap, such as 1mb, is it possible

**Comment by sitsofe** [comment]
@wangyihanlarry While fio doesn't dump a bitmap you CAN have fio generate a log of every offset it touched - see the [`write_iolog`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-write-iolog) option. It would then be a matter of programming to convert that into your bitmap.

**Comment by wangyihanlarry** [comment]
@sitsofe, would you please give me a bit more details on the output of the file, I got the following outputs and I am wondering how to convert the third column into the address,

/dev/sdhu add
/dev/sdhu open
/dev/sdhu read **_129521664_** 2048 #how to get this into the address in 1m unit?
/dev/sdhu read 1589760000 10240
/dev/sdhu read 1810721792 12288
/dev/sdhu write 1009347584 3072
/dev/sdhu read 863098880 5120
/dev/sdhu read 1804161024 14336
/dev/sdhu write 817105920 1024
/dev/sdhu write 759179264 6144
/dev/sdhu write 1960665088 8192
/dev/sdhu read 143502336 1024
/dev/sdhu write 1836585984 8192
/dev/sdhu read 1398337536 15360
/dev/sdhu write 1994024960 4096
/dev/sdhu read 530178048 2048
/dev/sdhu read 842858496 3072

**Comment by sitsofe** [comment]
> I am asking this as I am not able to divide the 129521664 by any of 512 or 1024

```
>>> 129521664 % 512 == 0
True
```

512 divides 129521664 exactly so I don't understand your statement.

In the future rather than continuing a closed issue to ask new questions could you ask "How do I/Why is?" questions via the  [fio mailing list](https://github.com/axboe/fio/blob/fio-3.23/README#L58) (note that the list only accepts plain text emails)? Thanks!
