### ISSUE TITLE
Verify read write ZFS filesystem

### ISSUE THREAD

**Issue by danjde** [axboe/fio#1126]
Hi Devs,
is there an example i could use to test a partition formatted with ZFS filesystem?
I've setup on a 32bit machine (ZFS seems not designed for 32bit cpus), a large ZFS filesystem and would like to know if read/writing goes fine.

Thanks!

**Comment by sitsofe** [comment]
@danjde https://github.com/axboe/fio/blob/fio-3.24/examples/basic-verify.fio offers some good ideas about how to do verified writes. See https://fio.readthedocs.io/en/latest/fio_man.html#verification for more options related to verification.
