### ISSUE TITLE
run Fio return Bus error

### ISSUE THREAD

**Issue by renyson** [axboe/fio#1127]
hi, i run fio in android device to test zram, fio version: fio-2.20
`./fio -filename=/dev/block/zram0 -thread -rw=read -bs=4k -size=20M -group_reporting -numjobs=1 -name=mytest`
and it return Bus error
`135|onyx:/data # ./fio -filename=/dev/block/zram0 -thread -rw=read -bs=4k -size=20M -group_reporting -numjobs=1 -name=mytest                                                                                    
Bus error`
could you please help to figure out how to solve this problem?
thanks~

**Comment by sitsofe** [comment]
@renyson We (upstream) only support the latest fio (see https://github.com/axboe/fio/releases for which version we're up to). Can you reproduce the issue with latest fio please?

**Comment by renyson** [comment]
hi, i try the latest fio, it works!
