### ISSUE TITLE
libhdfs is very specific

### ISSUE THREAD

**Issue by fbacchella** [axboe/fio#113]
The current version of libhdfs needs strange environment variables to be used, and can only run a very specific subset of what fio can do. It's also badly documented and needs a lot of manual preparation.

I tried to rewrite it : https://github.com/fbacchella/fio/tree/newhdfs

I kept the idea of spliting file in chunks.

I'm doing it right ? There is not a lot of documentation about writing a engine, so I needed to do a little reverse engineering. I hope I understood it.

If it's right, I'll do a rebase and create a pull request.

I needed to change options, because with the new FIO_OPT_G_HDFS, there is too much groups. With my modification, only compiled one are created.

**Comment by axboe** [comment]
Sorry, I dropped the ball on this one. Looks reasonable, can you rebase/cleanup and resend?

**Comment by fbacchella** [comment]
Ok thanks, I'll do that as soon I'm sure everything is clean.

**Comment by axboe** [comment]
DId you get it cleaned up?

**Comment by fbacchella** [comment]
Yes, it's much better now. It should be ok for a pull request.

**Comment by axboe** [comment]
Work got done and pulled, closing this issue.
