### ISSUE TITLE
Run net use command on remote server

### ISSUE THREAD

**Issue by mirim-123** [axboe/fio#1131]
Hi,

I want map a share to drive letter by cmd command from remote server
I try run the following command from my PC:
psexec -u [user] -p [password] \\\\[remote server ip] cmd /c "net use J: [share path]"

Command complete successfuly, but I cant see the map share in remote server

What is the reason?

Thanks!

**Comment by sitsofe** [comment]
I'm afraid I don't know this answer to this one.

I'm closing this because this is a question related to the `psexec` command and this is the bug tracker for bugs related to fio code. Good luck!
