### ISSUE TITLE
fio: blocksize too large for data set

### ISSUE THREAD

**Issue by joecwdc** [axboe/fio#1132]
I am using a command that I have used in the past with fio w/o error in previous versions and now am getting "fio: blocksize too large for data set"
I am running on Ubuntu 20.04 using fio-3.16
I am not sure how to interpret the error message I am seeing.
The command I am using is:
```
fio --loops=1 --direct=1 --rw=read --unified_rw_reporting=0 --refill_buffers --random_generator=tausworthe64 --norandommap --randrepeat=0 --ioengine=libaio --bs=131072 --rwmixread=0 --iodepth=16 --numjobs=1 --time_based --runtime=30 --group_reporting --size=10% --name=p1 --offset=0% --filename=/dev/nvme0n1 --name=p2 --offset=10% --filename=/dev/nvme0n1 --name=p3 --offset=20% --filename=/dev/nvme0n1 --name=p4 --offset=30% --filename=/dev/nvme0n1 --name=p5 --offset=40% --filename=/dev/nvme0n1 --name=p6 --offset=50% --filename=/dev/nvme0n1 --name=p7 --offset=60% --filename=/dev/nvme0n1 --name=p8 --offset=70% --filename=/dev/nvme0n1 --name=p9 --offset=80% --filename=/dev/nvme0n1 --name=p10 --offset=90% --filename=/dev/nvme0n1 --name=p11 --offset=0% --filename=/dev/nvme1n1 --name=p12 --offset=10% --filename=/dev/nvme1n1 --name=p13 --offset=20% --filename=/dev/nvme1n1 --name=p14 --offset=30% --filename=/dev/nvme1n1 --name=p15 --offset=40% --filename=/dev/nvme1n1 --name=p16 --offset=50% --filename=/dev/nvme1n1 --name=p17 --offset=60% --filename=/dev/nvme1n1 --name=p18 --offset=70% --filename=/dev/nvme1n1 --name=p19 --offset=80% --filename=/dev/nvme1n1 --name=p20 --offset=90% --filename=/dev/nvme1n1
```

This same command works under fio-3.7 on CentOS

**Comment by sitsofe** [comment]
@joecwdc could you cut the command down such that you have the true minimum optionsthat still reproduce the issue? Thanks!

**Comment by joecwdc** [comment]
fio --loops=1 --direct=1 --rw=read --unified_rw_reporting=0 --refill_buffers --random_generator=tausworthe64 --norandommap --randrepeat=0 --ioengine=libaio --bs=131072 --rwmixread=0 --iodepth=16 --numjobs=1 --time_based --runtime=10 --group_reporting --size=10% --name=p1 --offset=0% --filename=/dev/nvme0n1 --name=p2 --offset=10% --filename=/dev/nvme0n1

It seems that adding the 2nd partition causes the error to be generated.

**Comment by sitsofe** [comment]
@joecwdc 
- Would you be able able to cut it down more? I think there are options in the start and the middle that likely don't impact the issue...
- If you run `file /dev/nvme0n1` what does it say?
- If the above says its special what does `blockdev --getsize64 /dev/nvme0n1` say but if it's regular what does `du -sh /dev/nvme0n1` say?

**Comment by joecwdc** [comment]
I think this is the smallest number of options that cause the error:

fio --bs=131072 --time_based --runtime=10 --size=10% --name=p1 --offset=0% --filename=/dev/nvme0n1 --name=p2 --offset=10% --filename=/dev/nvme0n1

# file /dev/nvme0n1
/dev/nvme0n1: block special (259/109)

# blockdev --getsize64 /dev/nvme0n1
107374182400

**Comment by sitsofe** [comment]
@joecwdc Thank you!

**Comment by sitsofe** [comment]
I've just tried this with Ubuntu 20.04 and fio 7914c6147adaf3ef32804519ced850168fff1711 (basically post 3.24) and the following worked:
```
# Create a fake 100Gbyte disk at /dev/nullb0
modprobe null_blk gb=100 nr_devices=1 hw_queue_depth=156 queue_mode=2
./fio --allow_file_create=0 --bs=131072 --time_based --runtime=10 --size=10% --name=p1 --offset=0% --filename=/dev/nullb0 --name=p2 --offset=10% --filename=/dev/nullb0 
```

Can you see if the issue occurs with the latest fio built from source?

**Comment by joecwdc** [comment]
This works with the latest.  So I will chalk this up to distribution lag.

Is there any way to make the error message "fio: blocksize too large for data set" clearer?

Thanks.

**Comment by sitsofe** [comment]
@joecwdc What would you suggest it be changed to?

I think that message is meant to trigger when you ask for a block size that is bigger than the region you are operating in (see https://github.com/axboe/fio/blob/9107a641e67f27003fa6cbe7b55b1ec6a0239197/filesetup.c#L1201 ). Unfortunately a bug was introduced that falsely made that message fire but it looks like it was fixed by 0d0601479d593ca9e96e35f43e2c0586f8358f34 ...

**Comment by joecwdc** [comment]
Given the additional detail, I am not sure the message can be made clearer, but your comment "block size that is bigger than the region you are operating in" made it clearer to me.

Thanks.

**Comment by sitsofe** [comment]
@joecwdc how does https://github.com/sitsofe/fio/commit/859d5476f33debd5caa4a49373910efb0de9df4c look to you?

**Comment by joecwdc** [comment]
Looks good to me.

**Comment by akshay225** [comment]
> 
> 
> This works with the latest. So I will chalk this up to distribution lag.
> 
> Is there any way to make the error message "fio: blocksize too large for data set" clearer?
> 
> Thanks.

Hello, I am seeing the same issue. How do I get the latest fio/install the latest fio, I already have a fio in my ubuntu. Thanks

**Comment by joecwdc** [comment]
It would most likely require an update to the OS, if that is not possible, you should be able to build the latest version from source from this repo.
