### ISSUE TITLE
IO engine that uses the Linux SG v4 interface to talk to SCSI devices

### ISSUE THREAD

**Issue by donny372** [axboe/fio#1141]
There is a patch to add sgv4 engine to linux kernel.
https://lore.kernel.org/linux-block/20190706210826.17964-1-dgilbert@interlog.com/T/

Should we add an sgv4 engine in fio? or we can use it directly on a linux machine with this patch.

**Comment by axboe** [comment]
Don't think the kernel bits ever made it in - but even if they did, don't see what this brings that bsg doesn't already do.
