### ISSUE TITLE
[FAQ] what is the manual to use fio to test write hint and stream id for nvme device

### ISSUE THREAD

**Issue by gaowayne** [axboe/fio#1146]
as title

**Comment by axboe** [comment]
Look at the man page, search for write_hint.

**Comment by gaowayne** [comment]
@axboe hello expert, I got this write_hint now. but could you please give some example, how we issue mixed different hint IOs with fio, we want to test the mixed long life short life at the same time. current fio support this?

**Comment by axboe** [comment]
Just setup multiple jobs, using different write hints.

**Comment by gaowayne** [comment]
@axboe we can set this within one fio process, right? we specify jobs=4, but how we specify different write hint for each of my 4 jobs? can you show me one example?

**Comment by axboe** [comment]
If you just set numjobs=4, then you'd have 4 of the same jobs. You want something ala

```
[global]
rw=write
filename=/some/mount/file

[short-life]
write_hint=short

[long-life]
write_hint=long
```

as the bare bones of it.

**Comment by gaowayne** [comment]
@axboe buddy can you give me one full example fio, I am sorry I still not get it, how to specify which job run short life, which job run long life.

**Comment by axboe** [comment]
Ask on the fio list, that's where general "How do I...?" questions are more appropriate, this isn't a bug. And probably do a bit of research and play with fio a bit, then you should be able to figure it out.

**Comment by gaowayne** [comment]
@axboe ah, yes man, I am sorry, I should look at the document first. 👍 

See the examples/ directory for inspiration on how to write job files. Note the copyright and license requirements currently apply to examples/ files.

So let’s look at a really simple job file that defines two processes, each randomly reading from a 128MiB file:

; -- start job file --
[global]
rw=randread
size=128m

[job1]

[job2]

; -- end job file --
As you can see, the job file sections themselves are empty as all the described parameters are shared. As no filename option is given, fio makes up a filename for each of the jobs as it sees fit. On the command line, this job would look as follows:

$ fio --name=global --rw=randread --size=128m --name=job1 --name=job2

**Comment by sitsofe** [comment]
@gaowayne  As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.23/README#L58) (note that the list only accepts plain text emails). Thanks!
