### ISSUE TITLE
--directory parse hint on Windows

### ISSUE THREAD

**Issue by jzabroski** [axboe/fio#1168]
**Description of the new feature**
Consider adding a note that `:` should be escaped on Windows.

**Comment by jzabroski** [comment]
@sitsofe I can add a PR for this :)

**Comment by sitsofe** [comment]
(There is a brief mention in the [documentation for the directory option](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-directory) so you may want to start your improvement with the HOWTO/fio.1 manpage)

**Comment by jzabroski** [comment]
I've never found the perfect command line parser library.  I thought object-oriented shells would solve some of these problems but they created new problems.  Maybe my grand kids will enjoy pistachio shells without biting into bitter Navel orange worms.

**Comment by sitsofe** [comment]
I think the way to go is to improve the documentation for the directory option (man page and HOWTO). I'll close this issue but if you get a chance feel free to submit a PR improving it.
