### ISSUE TITLE
Exact end of Job

### ISSUE THREAD

**Issue by projectHolsey** [axboe/fio#1176]
Hey,

Using FIO version 3.25
Windows server 2016

Apologies for asking here, could not load the mailing list properly to send there

Does the "timestamp_ms" correspond to the exact end of FIO Job? 
Looking at power draw during FIO workloads, this value looks ~0.25s out.

If not, is there a way of getting this value / working it out?

**Comment by sitsofe** [comment]
(The mailing list only accepts plain text emails so you have to set your mailer not to include an HTML part and then the mails are accepted)

@projectHolsey From what I can see `timestamp_ms` is set when the JSON output is "created" (see https://github.com/axboe/fio/blob/f9eb98cba4cfc5351bace61c21eda67fb625266b/stat.c#L2218-L2230 ). Technically a job's length is available as `job_runtime` but if you want to change that into a wall time I think that would be a new feature (e.g. to record the clock wall time when the job starts).

**Comment by sitsofe** [comment]
Please be aware that most new feature requests are only completed through the work of new contributors (the fio developers are busy with non-fio work). Would you like to take an attempt to code this up so we can review it?

**Comment by sitsofe** [comment]
Closing because none of the core developers are working on it and no follow up from the reporter. If someone does want to work on this please submit a pull request and re-open this issue at that point.
