### ISSUE TITLE
"fio: engine http not loadable" error when trying to run file to s3 protocol

### ISSUE THREAD

**Issue by delillol** [axboe/fio#1178]
**Please acknowledge the following before creating a ticket**

- [X ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
1) I performed a "yum install fio" on my RHEL8.3 server (x86_64).
2) I built the following config file to do a simple test to a cluster that uses s3 protocol (in this case, Noobaa)

~# cat s3_testfile.fio 
[global]
ioengine=http
name=test
direct=1
filename=firsttest
http_verbose=0
https=on
http_mode=s3
http_s3_key=${S3_KEY}
http_s3_keyid=${S3_ID}
http_host=http://${myHost}:31699
group_reporting

[create]
rw=write
bs=4k
size=64k
io_size=4k
verify=sha256

3) The job fails with the following error:
~# fio s3_testfile.fio 
fio: engine http not loadable
fio: failed to load engine
Bad option <http_verbose=0>
Bad option <http_mode=s3>
Did you mean zonemode?
.
.
.
fio: job global dropped

4) Are there any prerequisite packages that are required for me to yum install (or pip install) to get the http engine to load?  I was able to do a different test using the libaio engine, so I can get successful fio runs on this server.

**Environment**: 
RHEL8.3 x86

~# uname -r
4.18.0-240.1.1.el8_3.x86_64

**fio version**: 
~# fio -version
fio-3.19

**Reproduction steps**

**Comment by sitsofe** [comment]
Hi @delillol,

As you're dealing with a distribution package of fio (you can see you're far behind the [latest fio](https://github.com/axboe/fio/releases) which is pretty much the only one that we (fio upstream) support) you will have to report this to whoever distributed you fio - it could be they have [chosen not to configure in the HTTP ioengine](https://git.centos.org/rpms/fio/blob/c8/f/SPECS/fio.spec#_16). You can always try build fio by hand (it's not a difficult [build](https://github.com/axboe/fio/blob/fio-3.25/README#L132)) but you'll also need the correct packages to get the http ioengine (see https://github.com/axboe/fio/blob/master/configure#L1705-L1756 which hints at development libraries for curl which is configured to use openssl and openssl development libraries).

Setting to needsinfo pending a reply from the author.

**Comment by delillol** [comment]
Building fio 3.25 with the link that you provided above got me past the http problem.   Thank you for the information.  I will close this out.
