### ISSUE TITLE
Installing v3.5

### ISSUE THREAD

**Issue by Furjoza** [axboe/fio#1184]
Hi,

I am trying to install FIO v3.5 on one of my Linux systems.
"sudo ./configure" # works as expected
"sudo make" ends with:
"error: static declaration of ‘gettid’ follows non-static declaration" in many different files.
GCC used: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
I have tried newer once like 7.5.0 and 9.2.1 as well. Didn't help.

Current v3.25 is installing without any issues.

**Comment by sitsofe** [comment]
@Furjoza we only support the latest fio so we can offer any help with that one. Probably a long since fixed bug (you can try [searching for gettid in commits)](https://github.com/axboe/fio/search?q=gettid&type=commits)
