### ISSUE TITLE
Disabling bw, clat and slat logging corrupts the total latency measured

### ISSUE THREAD

**Issue by MackatITU** [axboe/fio#1191]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
When i run Fio while having disabled clat, slat and bandwidth tracking it "corrupts" the latency mentioned in standard Fio output and the corresponding .log file when having write_lat_log enabled. 
An example of the standard Fio output:
```
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=1
fio-3.20-90-g5bd52
Starting 1 thread
Jobs: 1 (f=1): [f(1)][100.0%][w=27.9MiB/s][w=7130 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=132792: Wed Feb 17 13:32:25 2021
  write: IOPS=58.1k, BW=227MiB/s (238MB/s)(13.3GiB/60001msec); 0 zone resets
     lat (msec): min=8647.6G, max=8647.8G, avg=8647619836547.01, stdev=261316.04
   bw (  KiB/s): min=211896, max=233896, per=100.00%, avg=232696.74, stdev=3820.07, samples=119
   iops        : min=52974, max=58474, avg=58174.18, stdev=955.02, samples=119
  cpu          : usr=20.81%, sys=30.63%, ctx=3485886, majf=0, minf=54484
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,3485870,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=227MiB/s (238MB/s), 227MiB/s-227MiB/s (238MB/s-238MB/s), io=13.3GiB (14.3GB), run=60001-60001msec

Disk stats (read/write):
  nvme0n1: ios=49/3485870, merge=0/0, ticks=5/39119, in_queue=39125, util=97.71%
```

Here the reported average total latency is measured to be 8647619836547.01 msec, and the min,max values are also looking suspicious. 
I understand that to capture the total latency we need the submission and completion latency which, as I have mentioned, is disabled. 
So why is the total latency then reported upon if it's clearly faulty?

**Environment**: 
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**fio version**: 
fio-3.25-98-gab02b

**Reproduction steps**

Run the following Fio file:
```
[global]
bs=4k
iodepth=1
numjobs=1
direct=1
thread=1
filename=/dev/nvme0n1
ioengine=io_uring
disable_clat=1
disable_slat=1
disable_bw=1

[test]
rw=randwrite
time_based
runtime=60s
write_lat_log=test

```

**Comment by MackatITU** [comment]
Updated Fio to have the newest version - the bug still persists. 
Fio version: fio-3.25-98-gab02b

**Comment by sitsofe** [comment]
Hmm I think I can see what happens. Because all the latency measuring options are disabled

```
disable_clat=1
disable_slat=1
disable_bw=1
```

This triggers fio into think you want to do `gtod_reduce=1` (see https://github.com/axboe/fio/blob/fio-3.25/io_u.c#L1844-L1848 ). This leads fio to no longer record things like completion time (https://github.com/axboe/fio/blob/fio-3.25/io_u.c#L2052-L2053 ) leading to the corruption. There's a strong argument why do you try to measure latency when you turn it off but there's another argument that fio could bail out early when it spots conflicting options.

**Comment by MackatITU** [comment]
> There's a strong argument why do you try to measure latency when you turn it off but there's another argument that fio could bail out early when it spots conflicting options.

My main point is that Fio should not report on total latency if we know the numbers are going to be faulty due to disabling clat and slat. 
Furthermore, note that I haven't disabled the total latency (see https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-disable-lat). What I have done is disabling completion and submission latency - but not the total latency as you suggest in the quote above.

**Comment by sitsofe** [comment]
@MackatITU If you choose to disable submission and completion latencies you are correct that total latency should go away (since it can no longer be calculated) and thus by extension any option that relies on any latency being available should be marked as a conflict.

Would you like to submit a patch fixing all the above?

**Comment by MackatITU** [comment]
> Would you like to submit a patch fixing all the above?

Sorry, I am too busy with work elsewhere.

**Comment by sitsofe** [comment]
@MackatITU fair enough. I'll close this one for now but if someone wants to fix it up to be more noisy for the user we can review the patches.
