### ISSUE TITLE
Fio report "fio: pid=33198, err=27/file:io_u.c:1854, func=io_u error, error=File too large"

### ISSUE THREAD

**Issue by dance-wolf** [axboe/fio#1192]
**Description of the bug:**
execute fio command "fio --name=16kB_random_WR_32job_QD1 --directory=/tmp/u01 --filename=test_file  --direct=1 --thread=1 --rw=randwrite --ioengine=psync --bs=16k --numjobs=32 --iodepth=1 --runtime=600 --time_based=1 --size=28375g --norandommap=1 --randrepeat=0 --group_reporting --log_avg_msec=1000 --bwavgtime=1000 --minimal >>random_write_read.log" then fio report "fio: pid=33198, err=27/file:io_u.c:1854, func=io_u error, error=File too large"

**Environment**: CentOS7.5
**fio version**: FIO-2.6/FIO-3.5
**Reproduction steps**
1. create an EXT4 file system on drive partition,and mount it to a specified directory
2. then execute fio command such as "fio --name=16kB_random_WR_32job_QD1 --directory=/tmp/u01 --filename=test_file  --direct=1 --thread=1 --rw=randwrite --ioengine=psync --bs=16k --numjobs=32 --iodepth=1 --runtime=600 --time_based=1 --size=28375g --norandommap=1 --randrepeat=0 --group_reporting --log_avg_msec=1000 --bwavgtime=1000 --minimal >>random_write_read.log"
3. check the feedback and fio log show “error=File too large"

**Comment by sitsofe** [comment]
Hi @dance-wolf,

As we (upstream) [only support the latest version of fio](https://github.com/axboe/fio/blob/master/.github/SUPPORT.md#reporting-bugs) (see [the releases page](https://github.com/axboe/fio/releases) for which version we're up to) can you reproduce your issue with the latest fio? The "Source" and "Building" sections of the [README](https://github.com/axboe/fio/blob/master/README) give instructions on how to build fio. Thanks!

Setting to needsreporterinfo pending reporter reply.

**Comment by dance-wolf** [comment]
> Hi @dance-wolf,
> 
> As we (upstream) [only support the latest version of fio](https://github.com/axboe/fio/blob/master/.github/SUPPORT.md#reporting-bugs) (see [the releases page](https://github.com/axboe/fio/releases) for which version we're up to) can you reproduce your issue with the latest fio? The "Source" and "Building" sections of the [README](https://github.com/axboe/fio/blob/master/README) give instructions on how to build fio. Thanks!
> 
> Setting to needsreporterinfo pending reporter reply.

@sitsofe Thanks for your reply. Try reproduce this issue use FIO-3.25, Then the newest show same issue.
<img width="692" alt="wfp-fio3 25 - Copy" src="https://user-images.githubusercontent.com/79236420/108586467-ba67a300-7389-11eb-86e2-40308a9df97b.PNG">

**Comment by sitsofe** [comment]
@dance-wolf How big is your your /tmp filesystem?

**Comment by dance-wolf** [comment]
> @dance-wolf How big is your your `/tmp` filesystem (i.e. what does `df -h /tmp` say)?

@sitsofe . File size as below. For the fio command, the "--size" parameter large than 28000G
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1     28T   63G   27T   1% /tmp/u01

**Comment by sitsofe** [comment]
So your command above is saying you have 27T **available** but the file you are trying to make is just over 27.7T . If you reduce the size of the file you are trying to make by 1T do you find it fits?

**Comment by dance-wolf** [comment]
> @dance-wolf So your command above is saying you have 27T **available** space but the file you are trying to make is just over 27.7T ... If you reduce the size of the file you are trying to make by 1T do you find it fits?

@sitsofe Rerun the same workload with different "--size" parameter(FIO-3.25).issue will "--size=17408g"

Size   parameter | FIO feedback
-- | --
14436g | normal
15360g | normal
16384g | FIO   feedback"16kB_random_WR_32job_QD1: Laying out IO file(s) (1 file(s) /   16777216MB)"
17408g | feedback show   "func=io_u error, error=File too large".

**Comment by axboe** [comment]
What happens when you try and write 17TB with eg dd to that same location?

**Comment by dance-wolf** [comment]
> What happens when you try and write 17TB with eg dd to that same location?
looks dd command also report "File too large" 
![image](https://user-images.githubusercontent.com/79236420/108933616-6ceb7e80-7686-11eb-811f-41b429d66fcb.png)

**Comment by axboe** [comment]
I think we can safely conclude that this isn't a fio specific issue. It's likely tmpfs doesn't support > 16TB files/size.
