### ISSUE TITLE
clock setaffinity failed: Invalid argument inside container(lxc)

### ISSUE THREAD

**Issue by stutiredboy** [axboe/fio#1197]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

while run inside lxc container, we got error `clock setaffinity failed: Invalid argument`.

the lxc was limited to use specific cpus, such as 4-6.

lxc config: `lxc.cgroup.cpuset.cpus = 4-6`

**Environment**: Linux 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux

**fio version**: 3.12 and 3.25

**Reproduction steps**

just run fio inside container, the container should cpu cores limited.

**Comment by sitsofe** [comment]
@stutiredboy Fio expects that all the CPUs it can see can be used during clock stability testing. If you artificially restrict CPUs outside of fio I would guess the [CPU binding in `fio_monotonic_clocktest()`](https://github.com/axboe/fio/blob/60c52212520b905a1740d3c8815c34cc48471c5c/gettime.c#L706-L720) would throw that message.

Would you like to submit a patch that changes that part of fio to [only include CPUs by affinity like nproc does](https://github.com/coreutils/gnulib/blob/7c748055361ce5e9400d4dd460df0b84c735eff4/lib/nproc.c#L69)?

**Comment by axboe** [comment]
I added some basic code for this, please check with current -git.

**Comment by axboe** [comment]
Considering this one fixed, please reopen if there are issues.
