### ISSUE TITLE
Wrong read speed result for Samsung SSD 970 EVO Plus

### ISSUE THREAD

**Issue by tim77** [axboe/fio#1202]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Strange speed results for Samsung SSD 970 EVO Plus (1TB version and others). By datasheet speed rated at 3500MB/s. In `gnome-disks` i have ~3500MB/s sequential read but `kdiskmark` and `fio` shows me only ~1500MB/s. And write speed ~2900MB/s. So read speed shows half of stated speed.

**Environment**: 
- Fedora 33
- kernel 5.10.20

**fio version**: 3.21

**Reproduction steps**

```sh
echo 3 | sudo tee /proc/sys/vm/drop_caches
fio --ioengine=libaio --direct=1 --randrepeat=0 --refill_buffers --end_fsync=1 --filename=test-fio.tmp --name=readjob --size=128M --bs=1m --rw=read --iodepth=8 --loops=5
```

Seems like this issue appears first time in 5.10 kernel. In 5.9 no such weird speed deviation.

Downstream bug report: https://github.com/JonMagon/KDiskMark/issues/48

**Comment by axboe** [comment]
This sounds like a kernel issue, not a fio issue. Are you familiar with building and booting your own kernels? Would likely be the easiest to pin-point by doing a bisect between 5.9 and 5.10.

Are you using an IO scheduler for the nvme device? Assuming you have just the one NVMe device, do:

```
$ cat /sys/block/nvme0n1/queue/scheduler
```

and see what that says.

**Comment by tim77** [comment]
```
❯ cat /sys/block/nvme0n1/queue/scheduler
[none] mq-deadline kyber bfq
```

**Comment by axboe** [comment]
OK, can't be the scheduler then. Are you able to build and boot kernels? If not, we can tentatively try -rc builds, if they are available...

**Comment by tim77** [comment]
Yep. Need some time. Forgot to say that we tried kernel 5.11.5 and problem is still here.

Maybe we should report to Red Hat bugzilla into `kernel` as well?

**Comment by axboe** [comment]
Yes, report it to RH if that's your distro, or send an email to linux-kernel@vger.kernel.org with the details - note, however, that particularly the latter will end up with folks (or me) asking you go bisect it as well. I'll be happy to debug it with you here, as long as you can bisect, build, and boot each kernel and run your test case. Then we should trivially be able to narrow it down to the change that caused it.

**Comment by axboe** [comment]
Closing, not a fio issue.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tim, have you reported it?
