### ISSUE TITLE
fio io_uring single CPU core performance is only half of SPDK with the same core with intel P5800 Optane drive

### ISSUE THREAD

**Issue by gaowayne** [axboe/fio#1206]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
iouring single core is 100% but it only get half performance of SPDK single core on P5800 gen2 optane SSD

**Environment**: Fedora OS
Linux cyp03.lab7217.local 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**fio version**: 3.21

job1: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=8
fio-3.21
Starting 1 thread
^Cbs: 1 (f=1): [w(1)][0.9%][w=2877MiB/s][w=736k IOPS][eta 59m:28s]
fio: terminating on signal 2

job1: (groupid=0, jobs=1): err= 0: pid=507367: Fri Mar 12 07:58:17 2021
  write: IOPS=638k, BW=2492MiB/s (2613MB/s)(78.6GiB/32308msec); 0 zone resets
    clat (usec): min=5, max=175, avg=12.24, stdev= 2.81
     lat (usec): min=5, max=180, avg=12.34, stdev= 2.82
    clat percentiles (nsec):
     |  1.00th=[ 7520],  5.00th=[ 8512], 10.00th=[ 9152], 20.00th=[10048],
     | 30.00th=[10688], 40.00th=[11328], 50.00th=[11968], 60.00th=[12608],
     | 70.00th=[13248], 80.00th=[14144], 90.00th=[15296], 95.00th=[16320],
     | 99.00th=[20352], 99.50th=[25984], 99.90th=[35584], 99.95th=[37632],
     | 99.99th=[41728]
   bw (  MiB/s): min= 1734, max= 2886, per=100.00%, avg=2492.13, stdev=276.79, samples=64
   iops        : min=444056, max=738838, avg=637984.69, stdev=70857.66, samples=64
  lat (usec)   : 10=19.00%, 20=79.91%, 50=1.08%, 100=0.01%, 250=0.01%
  cpu          : usr=99.86%, sys=0.00%, ctx=52, majf=0, minf=119
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=100.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.1%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,20611600,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=8

==above is the fio test result==same SPDK perf can reach 4000MB/s for randwrite with only 1 CPU core but fio io_uring is half.
is there any bottleneck that io_uring can improve on this part?

**Reproduction steps**

**Comment by axboe** [comment]
Not that it likely matters here, but use the latest version of fio, 3.26. What matters more is that you didn't include the job file - not for the run pasted, but neither for the SPDK variant as well. The very first thing it asks you is if you've read the REPORTING-BUGS, and you have not. Please do.

**Comment by gaowayne** [comment]
@axboe I updated the bug detail. basically with some reason io_uring cannot scale well on P5800 optane SSD drive. can we chat on on private channel like slack for more detail?

**Comment by axboe** [comment]
Shoot me an email at axboe@kernel.dk
