### ISSUE TITLE
"Running Output" is not produced incase of Linux FIO execution 

### ISSUE THREAD

**Issue by surajk2** [axboe/fio#1207]
**Please acknowledge the following before creating a ticket**

- [Yes ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Running Output is not produced incase of Linux FIO execution  when executed by forking the process and running the FIO executable. Code Snippet is attached in below file.

As per https://fio.readthedocs.io/en/latest/fio_doc.html#interpreting-the-output,
Fio spits out a lot of output. While running, fio will display the status of the jobs created. An example of that would be:
Jobs: 1 (f=1): [_(1),M(1)][24.8%][r=20.5MiB/s,w=23.5MiB/s][r=82,w=94 IOPS][eta 0

Able to get the running output in Windows PC by creating process and executing FIO.
Able to do it from command shell in linux(centos7), but it is not working by creating new process and executing FIO.
As per the doc, it needs a USR1 signal. I have used that also in below code, still the behavior is same.

Command from code:
		const char* FIOdebugStr = "FIO-3_25 test1.fio --output=FIO_output.json --output-format=json";
		execl("/bin/sh","sh","-c", FIOdebugStr,(char*)0);

Please refer the below attached file for whole code.

**Environment**: Centos 7 

**fio version**: 3.25

**Reproduction steps**

[FIO_running_output_issue_Centos7.txt](https://github.com/axboe/fio/files/6132063/FIO_running_output_issue_Centos7.txt)

**Comment by surajk2** [comment]
with command line option eta = always. Able to get running output from program code as well.

**Comment by surajk2** [comment]
reopening to mark the solution and tag the person who helped.

**Comment by ankit-sam** [comment]
Hi Suraj, please check with FIO option
eta=always

By default eta is set to auto which prints ETA only when output is TTY, whereas eta=always disregards the output type and prints ETA whenever requested

**Comment by surajk2** [comment]
Hi Ankit,
Using 'eta=always' worked fine. 
Thank you for checking this.

Note: In Windows FIO,  'ETA=auto' (default option) works well for JSON output type.
