### ISSUE TITLE
io_limit value being ignored by fio 

### ISSUE THREAD

**Issue by vinno6184** [axboe/fio#1208]
**Please acknowledge the following before creating a ticket**

- [ yes] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
IO_limit value being ignored by fio-3.25

**Environment**: Amazon Linux II

**fio version**: 3.25

**Reproduction steps**
My Config file below.  I want fio to stop the run once the the I/O reaches 5GiB , but for some reason it completes its full run 

[global]
ioengine=psync
rw=write
size=1G
directory=/var/lib/docker/
thread=1
bs=16k
numjobs=16
runtime=200
io_size=10GiB
io_limit=5GiB
name=fio_test_filee
direct=1
time_based=1
group_reporting=1
norandommap=1

[vin-write-4g]

###########
Final Output:
Run status group 0 (all jobs):
  WRITE: bw=62.8MiB/s (65.8MB/s), 62.8MiB/s-62.8MiB/s (65.8MB/s-65.8MB/s), io=12.3GiB (13.2GB), run=200004-200004msec

Thanks in advance!

**Comment by ankit-sam** [comment]
Hi @vinno6184 looking at the config file and what you are expecting, there are few things which is not right.

You are trying to run a time_based job, with runtime as 200 seconds. This will take precedence over any size or io_size limitation. FIO will continue till the runtime. Now even if you remove time_based and runtime options there are few other things to consider.

io_size and io_limit are the same thing. So specify only one of them.
Next is numjobs=16, with this each job will write 5GiB, so a total of 80GiB.
