### ISSUE TITLE
is it possible for the FIO tool to write IO with non-dedupable and non-compressible pattern?

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1209]
is it possible for the FIO tool to write IO with non-dedupable and non-compressible pattern?

I know how to write the dedupable and comressible data, but how to make the data unique so that we can not compress/dedup them?

**Comment by wangyihanlarry** [comment]
Any update on this?

**Comment by axboe** [comment]
The answer is yes, it’s described in the man page.
