### ISSUE TITLE
Write and Verification

### ISSUE THREAD

**Issue by sarthak-k** [axboe/fio#1211]
I want to know if this is something possible:

I want to write a file with defined `randomseed` but do **not want** to verify it immediately, later on I want another FIO job to run just to verify data of the file. If yes, can some one point me to the example or give one?

**Comment by axboe** [comment]
Sure, just add do_verify=0 to the write workload. And for the verify side, it's identical to the write job file, except you change write to read or randwrite to randread. That's it.

**Comment by sarthak-k** [comment]
I have FIO Write Job:
```
[global]
bs=4k
rw=randwrite
randseed=4
random_generator=lfsr
direct=1
ioengine=posixaio
iodepth=128
do_verify=0

[write-data]
filename=write.data
size=128Mb
```

FIO Read Job

```
[global]
bs=4k
rw=randread
randseed=4
random_generator=lfsr
direct=1
ioengine=posixaio
iodepth=128
verify=crc32c

[write-data]
filename=write.data
size=128Mb
```
But if I change than `randseed` for write job to 5 and generate new data, the read job still successfully read and verify? the data. I do want to verify the integrity of data but with separate jobs, is that possible?

**Comment by axboe** [comment]
The randseed just tells fio what IO pattern to generate (in this case), which means if you change it for the read job file, it'll just read the data in a different order from how you wrote it originally. Each 4k block is still valid, so yes it'll verify correctly like that. Your write job also needs verify=crc32c added.

That said, I do think that fio could tighten up a bit in terms of verification. Fio will just verify based on the header that was written, since that contains information on data, checksum, type of verifier, etc.

**Comment by axboe** [comment]
Actually I'm wrong about that, that did get fixed a long time ago - if verify=x is given, fio will use that to verify. If none is given, it'll verify if there's a valid header, using the verify type that was used to generate it.

**Comment by sarthak-k** [comment]
What do you mean by `verify=x`, does x means `randseed` we used?

**Comment by axboe** [comment]
No, ```randseed``` takes an integer, that's a seed for the random number generator. ```verify``` takes a verify type, like ```crc32c``` or any of the other types supported (see ```fio --cmdhelp=verify```). They have nothing to do with each other.

**Comment by sarthak-k** [comment]
So basically, when we verify using `crc32c` or for with any other for that matter, it will verify the header which contains the information about data, checksum, etc. Can we somehow guarantee that data returned by underlying storage engine doesn't return out of order data or in general data integrity?

**Comment by axboe** [comment]
It'll first verify the actual header, and fail if that doesn't pass checksum. It will then verify the actual data, comparing the read checksum with what is in the header. For out-of-order data, if you mean stale data, then yes that could verify correctly if the full block is just an old (but valid) version.

**Comment by axboe** [comment]
That's the downside of doing the split verification, as otherwise the sequence of the written data will also be factored in. That catches cases like returning stale or out-of-order data too.

**Comment by sarthak-k** [comment]
Lets consider hypothetical condition, I write block 1 (`B1`) with some random data. Now when I'm reading `B1` from the storage (the storage engine have some bug) and returns me the data of block 2 (`B2`) against the read request of `B1`. Does this situation is covered by the verification in FIO? 

_Sorry for not adding this example in previous comment itself._

**Comment by axboe** [comment]
I'm assuming that B1 and B2 are both validly written originally, so both would pass verification if verified in the right order. And yes, fio will catch this, IFF he verify is done as part of the write workload. Otherwise fio doesn't know the write generation to expect, and hence cannot verify it.

**Comment by sarthak-k** [comment]
Is this assuming that write and verification happens in the same job or different as well?

**Comment by sarthak-k** [comment]
Is there a plan to support storing sequence of written data so the cases like returning stale or out-of-order data can be covered as well in split verification?

**Comment by axboe** [comment]
It is stored already, there’s just no sane way to verify it when it’s being read back from a separate job.

**Comment by sarthak-k** [comment]
It is stored in memory or in the header or data block? Anyway that we can extract this information?

**Comment by axboe** [comment]
It’s in the header, if it was in memory then what I wrote before would not be true. We have the information on read verify in what the write sequence is, but how would you know if it’s valid or not against a read? If we limit it to pure random write workload, then we’d know, as it matches the read generation. But for any kind of mixed or other workload being verified l, we don’t. It’d be easy enough to verify it on a new option being set to allow that, with the explicit info that it’ll most certainly fail if the original workload wasn’t a pure write workload.

**Comment by axboe** [comment]
Reopen if you are interested in working on this.
