### ISSUE TITLE
allow configure to select different libcurl installations

### ISSUE THREAD

**Issue by sparvu** [axboe/fio#1214]
**Description of the new feature**

On Debian 9.13 amd64, if I try to compile latest fio and link against libcurl which is installed somewhere else than OS prefixes /usr/lib /usr/local , fio wont be able to pick-up the correct library. It should be possible to have a mechanism via configure to allow such configurations, without manually hacking into Makefile.

Example:

```
$ uname -a
Linux debian9 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux

$ ls -lrt /opt/kronometrix/lib/
total 12932
-rwxr-xr-x 1 krmx krmx 3416752 Apr  7 13:36 libcrypto.so.1.1
-rwxr-xr-x 1 krmx krmx  689504 Apr  7 13:36 libssl.so.1.1
-rw-r--r-- 1 krmx krmx 5662058 Apr  7 13:36 libcrypto.a
-rw-r--r-- 1 krmx krmx 1029512 Apr  7 13:36 libssl.a
lrwxrwxrwx 1 krmx krmx      13 Apr  7 13:36 libssl.so -> libssl.so.1.1
lrwxrwxrwx 1 krmx krmx      16 Apr  7 13:36 libcrypto.so -> libcrypto.so.1.1
drwxr-xr-x 2 krmx krmx    4096 Apr  7 13:36 engines-1.1
-rwxr-xr-x 1 krmx krmx  207264 Apr  7 13:38 libexpat.so.1.7.0
lrwxrwxrwx 1 krmx krmx      17 Apr  7 13:38 libexpat.so.1 -> libexpat.so.1.7.0
lrwxrwxrwx 1 krmx krmx      17 Apr  7 13:38 libexpat.so -> libexpat.so.1.7.0
-rwxr-xr-x 1 krmx krmx     952 Apr  7 13:38 libexpat.la
-rw-r--r-- 1 krmx krmx  359462 Apr  7 13:38 libexpat.a
drwxr-xr-x 3 krmx krmx    4096 Apr  7 13:38 cmake
-rwxr-xr-x 1 krmx krmx  643168 Apr  7 13:39 libcurl.so.4.7.0
lrwxrwxrwx 1 krmx krmx      16 Apr  7 13:39 libcurl.so.4 -> libcurl.so.4.7.0
lrwxrwxrwx 1 krmx krmx      16 Apr  7 13:39 libcurl.so -> libcurl.so.4.7.0
-rwxr-xr-x 1 krmx krmx     990 Apr  7 13:39 libcurl.la
-rw-r--r-- 1 krmx krmx 1191816 Apr  7 13:39 libcurl.a
drwxr-xr-x 2 krmx krmx    4096 Apr  7 13:39 pkgconfig
drwxr-xr-x 2 krmx krmx    4096 Apr  7 14:12 sa
```

If I run ./configure --prefix=/opt/kronometrix fio wont be able to detect my libcurl installation, even if I have the curl binary in my PATH nor a proper LD_LIBRARY_PATH defined.

Is there any way at this moment to allow configure to pickup my own curl library?

**Comment by sparvu** [comment]
As a simple workaround I found that this will force configure to look for correct libcurl:

```
env CFLAGS="-I/opt/kronometrix/include" LDFLAGS="-L/opt/kronometrix/lib" ./configure --prefix=/opt/kronometrix
```

**Comment by sitsofe** [comment]
@sparvu your solution sounds right. If your libraries aren't in a standard library search path it will be up to you to teach what you're compiling how to find them!

(For the record you can see the curl compilation flags over on https://github.com/axboe/fio/blob/1588c8f571f67a004571e51cdbb5de97c3e4f457/configure#L1818-L1826 so you did what was need to make `-lcurl` find the library but that's more of a compiler question)
