### ISSUE TITLE
`size` not honored if `filesize` and `nrfiles` is set

### ISSUE THREAD

**Issue by Nikratio** [axboe/fio#1218]
I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

The `fio` manpage says:

```
       filesize=irange(int)
              Individual file sizes. May be a range, in which case fio will select sizes for files  at
              random  within  the  given range and limited to size in total (if that is given). If not
              given, each created file is the same size.  This option overrides size in terms of  file
              size, which means this value is used as a fixed size or possible range of each file.
```

I would like to use this to create a number of files with different sizes, summing up to a fixed total.

I think the following should do this:

```
[foo]
name=foo
ioengine=psync
randseed=42
nrfiles=200
filesize=4KiB-2GiB
size=20GiB
```

However, rather than limiting the size to 20 GiB, this gives me 100+ GB:

```
> fio ~/foo.fio
foo: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.26
Starting 1 process
foo: Laying out IO files (200 files / total 187573MiB)
^C
fio: terminating on signal 2
```

This is under Linux (Arch)

**Comment by sitsofe** [comment]
@Nikratio Hi,

I'm afraid they don't combine in that way. The text you references says this:

> This option [`filesize`] _overrides_ `size` in terms of file size, which means this value is used as a fixed size or possible range of each file.

So I don't think the intention was for that option to behave as you describe (sum of filesizes is restricted to size). Doing so sounds like it might be challenging (what do you do if you've used up all of size before you've got through `nrfiles`) but did you want to submit a patch to try and support your requirement?
