### ISSUE TITLE
Allow for multiple output formats for the same run

### ISSUE THREAD

**Issue by jshook** [axboe/fio#123]
I would like to pass --output-format=normal --output-format=json --output=result.json, or something comparable. Alternately, something that can read the json format and yield the normal output would work as well.

**Comment by axboe** [comment]
I see your point. It's not super easy to add, since all the printing isn't done in one spot. Easy to add if we can intermingle :-)

Might be doable by buffering the output first, then outputting. Then we can avoid them stepping on each other.

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=a666cab8ed3d2a2fa782be345425a2e88734a007

Should work as-of this commit. Please test and report back.

**Comment by Stan-He** [comment]
Is there a way to split different output-format into different output files?
--output-format=normal --output-normal=stdout --output-json=result.json

**Comment by stulluk** [comment]
> Is there a way to split different output-format into different output files?
> --output-format=normal --output-normal=stdout --output-json=result.json

Exactly needed...

**Comment by axboe** [comment]
That wouldn't be hard to add at all.

**Comment by Stan-He** [comment]
Now I use a workaround to fix this
--output-format=normal,json --output=stdout
then I use a python script to split the json content and normal content
