### ISSUE TITLE
`sync_file_range=wait_before,write:8' in 'man fio' is not supported by fio 3.19/3.27

### ISSUE THREAD

**Issue by wangyugui** [axboe/fio#1234]
**Description of the bug:**
`sync_file_range=wait_before,write:8' in 'man fio' is not supported by fio 3.19/3.27

**Environment**: centos 7.9/centos 8.4

**fio version**: 3.19/3.27

**Reproduction steps**
add `sync_file_range=wait_before,write:8' to x.fio, and then run 'fio x.fio'

**Comment by sitsofe** [comment]
Hi @wangyugui,

Do simpler commands like `sync_file_range=write:8` work for you?

**Comment by wangyugui** [comment]
sync_file_range=write:8 works.

it seems a option parse problem.
