### ISSUE TITLE
Can we please get a python api for fio.

### ISSUE THREAD

**Issue by ayushbindlish** [axboe/fio#1236]
I want to automate fio testcases. Is there a python api available for it? Or do we have an api in some other language?

**Comment by sitsofe** [comment]
(Please don't skip the appropriate section when filing an issue https://github.com/axboe/fio/issues/new/choose - there's a section titled "Feature enhancement request" which contains some useful extra information)

Currently programs have to consume fio's output to consume it and pass parameters to it to drive it and that's the only API it exposes. Several others have successfully used this interface (see https://github.com/axboe/fio/blob/master/t/run-fio-tests.py , https://github.com/intel/fiovisualizer , https://github.com/louwrentius/fio-plot ).

If someone wants to contribute a semi-interactive API to fio that would be great. However currently none of the core developers have time to work on such an enhancement I'll close this ticket. If later someone wants to work on this please submit a pull request and re-open this issue at that point and we can review it.
