### ISSUE TITLE
RNR NACK when librpma writes in a file in a pmem formated with ext4

### ISSUE THREAD

**Issue by Xarboule** [axboe/fio#1238]
**Description of the bug:**

When the librpma_apm server is setup to write in a file in a PMEM module formated in ext4 and mounted with DAX option, RNR NACKs packets appear during the transfer (meaning that the server is "not ready" to receive data).
Each time a RNR NACK is sent, the client waits a moment to let the server become ready, and retries, which ruins performances.
In our tests, each 10KB transfer was sent twice, following this pattern :

- Client sends 10KB
- Server returns RNR NACK
- Client waits...
- Client sends 10KB
- Server returns ACK

The exact same job file writing in our PMEM in DAX mode (/dev/dax1.0) works perfectly. 

**Environment**: 
- Client and Server: Ubuntu 20.04, Mellanox ConnectX-5
- Server: 128GB Optane DCPMM, in fsdax mode (/dev/pmem0), with ext4, mounted in DAX mode. DDIO is deactivated, so we can enable "direct_write_to_pmem".

**fio version**: 3.27

**Reproduction steps**

- Format the NVMM module in ext4, and mount it with `mount -o dax /dev/pmem0 /mnt/pmem0`
- Create an empty file ( /mnt/pmem0/my_file )
- Start the server, start a wireshark capture, start the client

***client.fio***
```
[global]
ioengine=librpma_apm_client
create_serialize=0
serverip=<--replaceme-->
port=7204
thread

[client]
numjobs=1
group_reporting=1
sync=1
iodepth=2
iodepth_batch_submit=1
rw=write
blocksize=10KB
size=20KB
```

***server.fio***
```
[global]
ioengine=librpma_apm_server
create_serialize=0
kb_base=1000
serverip=<--replaceme-->
port=7204
thread

[server]
direct_write_to_pmem=1
numjobs=1
size=100MiB
filename=/mnt/pmem0/my_file
```

**Partial workaround**

We had to convert our PMEM namespace mode from "fsdax" to "dax", which transforms "/dev/pmem1" into "/dev/dax1.0" with the following command :
`sudo ndctl create-namespace -f -e namespace1.0 --mode=dax`

Then replace `filename=/mnt/pmem0/my_file` by `filename=/dev/dax1.0` in server.fio

**Comment by janekmi** [comment]
Hi @Xarboule

Thank you for the extensive bug report. It seems, the last thing missing is a description of how you create a `/mnt/pmem0/my_file` file?

**Comment by Xarboule** [comment]
I just used `touch myfile` in my NVM module mounted in EXT4 (dax) and fio resized it to 100MiB.

**Comment by yangx-jy** [comment]
@Xarboule 

Did you get the following error when running fio on EXT4(dax)?
```
Jul 14 22:31:26.599826 [24647] *WARN*  cq.c: 160: rpma_cq_get_completion: failed rpma_completion(op_context=0x1, op_status=remote access error)
```

**Comment by grom72** [comment]
We are working on this issue on the librpma level already
https://github.com/pmem/rpma/pull/1220
and as soon as we complete the librpma part, we will focus on fio fix.

**Comment by ldorau** [comment]
Hi @Xarboule, could you test the pull request https://github.com/axboe/fio/pull/1329 with librpma v0.10.0 (required version)?
https://github.com/pmem/rpma/releases/tag/0.10.0

**Comment by Xarboule** [comment]
Hi @ldorau, I'm sorry, I don't have this hardware setup anymore.
I may be able to recreate this in some weeks, but not right now.

**Comment by grom72** [comment]
RNR NAK is the normal way to avoid transport timeouts when the responder needs more time to handle a request (according to IBTA Spec).  Page fault and related to it additional time in the case of fsdax is a typical example when RNR NAK is used. We can reduce but not fully eliminate such behavior with ``ibv_advise_mr(3)``. 
I propose to close this issue as the fix significantly reduces the frequency of RNR NAK.
