### ISSUE TITLE
Crash with kb_base=1000

### ISSUE THREAD

**Issue by viccornell** [axboe/fio#1244]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
fio crashes with error when kb_base is set to 1000. Setting kb_base avoid the crash.

fio: io_u error on file jobSR.0.0: Invalid argument: read offset=15000, buflen=1000
fio: io_u error on file jobSR.0.0: Invalid argument: read offset=14000, buflen=1000

**Environment**:
Linux home2 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.3.2011

**fio version**: 3.25 and 3.27x

**Reproduction steps**

Run:
fio --kb_base =1000 --size=1g --bs=1K --iodepth=16 --direct=1 --ioengine=posixaio  --name=jobSR --rw=read --stonewall

If you remove the kb_base option or set it to 1024 then it runs without error

**Comment by axboe** [comment]
I don't see a crash, but I do see the kernel telling you that doing 1000b O_DIRECT is not valid. O_DIRECT must be (at least) sector aligned, and hence a power-of-2.

**Comment by viccornell** [comment]
Ah. OK. I guess “crash” was a bit of dramatic license. What I should have said was that the program exited with an error. It looks like my customers’ benchmark script is even worse than I thought. Thanks for the quick reply and the info about O_DIRECT. 

Best Regards,

Vic

**Comment by axboe** [comment]
No problem, please close the issue.

**Comment by viccornell** [comment]
Error explained. Thanks.
