### ISSUE TITLE
Please help to check whether there is any error in my configuration file. I failed to execute it on Windows,Thanks

### ISSUE THREAD

**Issue by guoweifeng216** [axboe/fio#1245]
**Please acknowledge the following before creating a ticket**

- [ ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
[global]
filename=H:
size=100%
thread
ioengine=windowsaio
runtime=3600
continue_on_error=none
exitall_on_error
bs_unaligned
random_generator=tausworthe64
rw=randwrite

[random write 1njobs]
stonewall
direct=0
bssplit=512/10:1k/10:1.5k/10:3k/10:9k/10:127k/10:128k/10:512k/10:1m/10:2m/10
iodepth=32
numjobs=1

**Environment**: 

**fio version**: 

**Reproduction steps**

**Comment by sitsofe** [comment]
@guoweifeng216 Per the information in https://github.com/axboe/fio/blob/master/REPORTING-BUGS this is actually a "How do I/Why is?" question (you are asking "Why is my configuration file wrong?") rather than a bug report. Please can you send your question to the mailing list. Thanks!

**Comment by guoweifeng216** [comment]
I have update the information
