### ISSUE TITLE
FIO read/write Size

### ISSUE THREAD

**Issue by ambharesh** [axboe/fio#1249]
Hi,
I have few doubts in using FIO for memory tests. I'm using dev-dax engine , the size of dax namespaces are 64 GB and I want to clarify few things.

1. I have mentioned size as 100GB for a 64GB file but FIO ran without any issues. What is the parameter that will define the read/write size of FIO.

2. Does dev-dax engine support overflow of filename memory, because if my file /dev/dax0.0 size is only 64GB how does it write 100GB? and ideally what should be the maximum size we should give for a namespace.
``
[global]
thread
group_reporting

ioengine=dev-dax
iodepth=4
direct=0
filename=/dev/dax0.0
filesize=64GB

bs=2M
numjobs=200\
[job1]
rw=write
rwmixread=50
percentage_random=10
size=100G``

**Comment by sitsofe** [comment]
These are questions that would be better aimed at the mailing list but
> What is the parameter that will define the read/write size of FIO.
1. There's an interaction between the two as described over on https://fio.readthedocs.io/en/latest/fio_man.html#i-o-size but `filesize` when there is one file will "win". Look what happens with a simple fio job (`16 * 4 = 64`):
```
$ ./fio --name=go --filename=/tmp/fio.tmp --bs=4k --filesize=64k --size=100k
[...]
     issued rwts: total=16,0,0,0 short=0,0,0,0 dropped=0,0,0,0
```
2. It doesn't write 100G. See the above.
