### ISSUE TITLE
 fio: client timeout on cmd SEND_ETA

### ISSUE THREAD

**Issue by psuriset** [axboe/fio#125]
Clients:  16 VM's on KVM node.  Server same kvm host. 
While running 32 jobs with any ioengine on vm's concurrently, i notice this. 
same test with job=1, iodepth=32 has no issues.  

Working config: 
--
jobs=1
iodepth=32
ioengine=libaio
---

Error noticed with: 
---
jobs=32
iodepth=1
ioengine=libaio/sync
----

Error:

fio: client vm  timeout on cmd SEND_ETA
fio: client vm timed out

**Comment by axboe** [comment]
Can you provide the full job file and fio invocation used?

**Comment by psuriset** [comment]
job file and error
https://gist.github.com/psuriset/06c8571f347c70aaff07

**Comment by psuriset** [comment]
Rebuild fio rpm with  FIO_NET_CLIENT_TIMEOUT changing from 5000 to 10000 solved the problem. 
https://github.com/axboe/fio/blob/master/client.c#L1601

Is this expected to be the case? 

I havent noticed same issue with other configs.

**Comment by axboe** [comment]
OK, that's reassuring, so it's probably just that the timeout is too slow, not a functional issue. 5s is way on the low side, it's only really meant to catch things not replying forever. I'll bump it to 30s.

**Comment by psuriset** [comment]
Seems like this probelm is not going away with increased timeout
i am noticing again.

**Comment by psuriset** [comment]
https://gist.github.com/psuriset/137c0dee5969d10dec65

**Comment by psuriset** [comment]
Majorly noticed with HDD. Some times with HDD too

**Comment by axboe** [comment]
Can you retry with both 2.2.13 that was just released, and with the 'server' branch from git? The latter is a rewrite of some of the command handling, and also some more tolerance towards single failed ETA commands. If 2.2.13 doesn't work, I'm hopeful that the 'server' branch will. I hope to merge this into master for the next release.
