### ISSUE TITLE
Undefined behavior due to the double releases on the lock td->io_u_lock?

### ISSUE THREAD

**Issue by anson-lo** [axboe/fio#1254]
Dear developers, thank you very much for your checking! It seems there is an error in the method verify_async_thread. The lock may be unlocked twice that may lead to undefined behavior. Is that true?

https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/verify.c#L1407
https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/verify.c#L1414
https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/verify.c#L1420

```
static void *verify_async_thread(void *data)
{
	...;
		pthread_mutex_lock(&td->io_u_lock);

		while (flist_empty(&td->verify_list) &&
		       !td->verify_thread_exit) {
			ret = pthread_cond_wait(&td->verify_cond,
							&td->io_u_lock);
			if (ret) {
				pthread_mutex_unlock(&td->io_u_lock);  // release the lock and break
				break;
			}
		}

		flist_splice_init(&td->verify_list, &list);
		pthread_mutex_unlock(&td->io_u_lock); // release the lock again

		...;
}
```

Best,

**Comment by sitsofe** [comment]
@anson-lo Hi,

This does indeed look like an error. Would you like to submit a pull request to fix it?

**Comment by anson-lo** [comment]
@sitsofe Sure, I have created a PR, and please check it. Also, can you look at another issue #1253 I proposed?
