### ISSUE TITLE
fio error while trying to replay blktraces on multi-cpu ESXi VM

### ISSUE THREAD

**Issue by rv-chan** [axboe/fio#1257]
**Description of the bug:**
I am trying to replay IO traces collected by blktrace on Ubuntu18/20/21 VMs on VMware ESXi.
Things work fine on a 1 vcpu VM. 
On multi-vcpu VMs, blktrace creates multiple trace files per cpu - tracefile.blktrace.0/1/2... and there are issues.

If I use 'read_iolog=tracefile', (thinking fio replay will add and use the suffixes) fio reports:
   JOB1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
   fio-3.25
   Starting 1 process
   fopen read iolog: No such file or directory
   fio: pid=1573969, err=22/file:iolog.c:719, func=failed initializing iolog, error=Invalid argument
 
If I use 'read_iolog=tracefile.blktrace.0:tracefile.blktrace:1', fio reports:
  JOB1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
   fio-3.25
   Starting 1 process
   fio: iolog version 1 is no longer supported
   fio: pid=1574057, err=22/file:iolog.c:719, func=failed initializing iolog, error=Invalid argument

Single tracefiles work just fine.

**Environment**: 
fio-3.16/18/25 were all tried on ESXi (7.x) VMs running Ubuntu 18/20/21.04

**fio version**: 
fio-3.16/18/25

**Comment by rv-chan** [comment]
Additional things were tried and observed more issues.

Used this replay config:
    read_iolog=tracefile.blktrace.0
    merge_blktrace_file=tracefile.blktrace.1

fio prints just a single line and exits almost immediately:
   JOB1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
 
Used another two sets of replay config:
    # read_iolog=tracefile.blktrace.0 //commented out
    merge_blktrace_file=tracefile.blktrace.0:tracefile.blktrace.1
 
    and
    # read_iolog=tracefile.blktrace.0 //commented out
    merge_blktrace_file=tracefile

Both of the above segfault and dump core.
One of those cores (second one) is attached.

Any help is greatly appreciated!

[_usr_bin_fio.0.crash.gz](https://github.com/axboe/fio/files/6912939/_usr_bin_fio.0.crash.gz)

Thanks,
Ravi

**Comment by axboe** [comment]
It's in the documentation, read the read_iolog section. You are supposed to use blkparse to first turn a multi-cpu trace into a sorted single trace first.

**Comment by rv-chan** [comment]
Thanks much! I was able to replay with this method.

There was this one other issue of read_iolog_chunked not working for the blktrace.

I see that fio receives signal 11 and terminates.
--------
JOB1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.25
Starting 1 process
fio: pid=7602, got signal=11


Run status group 0 (all jobs):
--------

I guess, chunked reads are for only iolog and not blktrace?
If you could confirm this, I will go ahead and close the issue.
This also happened in the same environ as above.

Thanks.
Ravi

**Comment by axboe** [comment]
Yes, should add a check and abort for blktrace based replay and the chunked setting being set (or just ignore it).

**Comment by axboe** [comment]
Pushed a fix for that issue, would be great if you could test.
