### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DamonPalovaara** [axboe/fio#1262]
https://github.com/axboe/fio/blob/df9e8b65a52fdab5a1ac48847c44d7201faa3cf1/HOWTO#L2603

Should it be =bool not =boot?

**Comment by sitsofe** [comment]
@DamonPalovaara you're correct - would you like to submit a patch for the HOWTO and fio.1?

**Comment by sitsofe** [comment]
Fixed by #1265 .
