### ISSUE TITLE
NetBSD arm64 Big Endian "make: Invalid line type"

### ISSUE THREAD

**Issue by rbrasga** [axboe/fio#1267]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

`make` command fails. I will attempt to manually modify the Makefile, because I believe it has to do with incompatibility with the shell (and I have tried `sh`, `bash`, `ksh`)

```
arm64# make -f Makefile make: "/root/sef-fio/Makefile" line 1: Invalid line type
make: "/root/sef-fio/Makefile" line 1: Invalid line type
...
make: "/root/fio/Makefile" line 513: Invalid line type
make: Fatal errors encountered -- cannot continue
make: stopped in /root/sef-fio
arm64#
```

**Environment**: NetBSD 9.0 on aarch64 big endian on a raspberry pi 3

**fio version**: I have tried a handful of `fio-3.x` and `master`

**Reproduction steps**

* **NetBSD 9.x**
* Big Endian likely does not matter here.
* Raspberry Pi 3 likely does not matter either.
   * With an ARM64/AARCH64 processor architecture

```
./configure
make
#Also tried running this `sh ./configure`, `ksh ./configure`, `bash ./configure`
```
Any ideas?

**Comment by axboe** [comment]
See the documentation, you probably want to use gmake (gnu make)

**Comment by rbrasga** [comment]
I came to the same conclusion as well. Thank you!

> 'gmake' refers specifically to GNU make. 'make' refers to the system's default make implementation; on most Linux distros this is GNU make, but on other unixes, it could refer to some other implementation of make, such as BSD make

https://stackoverflow.com/questions/1194957/what-is-the-difference-between-gmake-and-make

Closing issue.

**Comment by axboe** [comment]
It's also in the README:

```
Building
--------

Just type::

 $ ./configure
 $ make
 $ make install

Note that GNU make is required. On BSDs it's available from devel/gmake within
ports directory; on Solaris it's in the SUNWgmake package.  On platforms where
GNU make isn't the default, type ``gmake`` instead of ``make``.

```

**Comment by axboe** [comment]
It's also in the README:

```
Building
--------

Just type::

 $ ./configure
 $ make
 $ make install

Note that GNU make is required. On BSDs it's available from devel/gmake within
ports directory; on Solaris it's in the SUNWgmake package.  On platforms where
GNU make isn't the default, type ``gmake`` instead of ``make``.

```
