### ISSUE TITLE
Is it possible to modify FIO to measure low latency in the range of nano seconds ?

### ISSUE THREAD

**Issue by Naveenaz** [axboe/fio#128]
As per my understanding current FIO tool measures latency in the order of usec (micro) seconds.
Just wanted to check if there is a way, where we can tweak FIO and make it measure much lower read/write latency in the order of 'nano' seconds ?

If yes, Could you please guide how to go about changing the code.

If not, is there any other tool / method with which we can measure low latency in the order of nano seconds ?

**Comment by axboe** [comment]
That would not be impossible to do. Fio supports three clock sources:

1) gettimeofday(). Only usec granularity.
2) clock_gettime(). nsec granularity
3) cpu clock source, nsec granularity

Fio currently wraps all of them in struct timeval, which is what gettimeofday() uses and only has seconds/usecs. So first patch would need to change fio_gettime() to use a struct timespec instead. If you can do that, then I can provide you with further instructions for moving toward a nsec granular internal clock.

**Comment by Naveenaz** [comment]
Forked source code from you. Could you please let me know in which files exactly I need make changes.

**Comment by axboe** [comment]
I already told you... Work from fio_gettime() and out. Make that take a struct timespec. Fix up everything around it.

**Comment by axboe** [comment]
Closing, feel free to submit a patch when the issue has been resolved.
