### ISSUE TITLE
--eta never causes empty logs

### ISSUE THREAD

**Issue by botkevin** [axboe/fio#1296]
**Please acknowledge the following before creating a ticket**

- [x ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Using --eta never causes --bandwidth-log to not output any data into logs

**Environment**: Centos 8 Kernel 4.18.0-305.12.1.el8_4.x86_64

**fio version**: 3.19

**Reproduction steps**
run fio with `--eta never` and `--bandwidth-log` options to see that the aggregate logs are empty

**Comment by vincentkfu** [comment]
Resolved by the patch for https://github.com/axboe/fio/issues/1599
