### ISSUE TITLE
local-test_name-0-verify.state

### ISSUE THREAD

**Issue by bokidigital** [axboe/fio#1300]
When doing:

sudo fio --name=verify --trigger=reboot --trigger-timeout=2 --numjobs=1 --filename=/dev/sdb --rw=randwrite --verify=md5

it will generate a file:
local-verify-0-verify.state

Can I say every disk sector/block stored in this file (local-verify-0-verify.state) means verified? or just means it had sent out the write command to disk but not yet verified?

or

it will store which sector/block was verified?

**Comment by axboe** [comment]
It's just a circular array of the last issued writes, which can be used for powercut verification. You can inspect the state with t/fio-verify-state <filename>.

**Comment by bokidigital** [comment]
It is the last issued writes, so it didn't guarantee the data ( stored in local-test_name-0-verify.state) is verified?

If I do a powercut test, should I expect the fio test pass? My understanding is the result will fail since no guarantee the data is verified in writes state.


ex:
sudo fio --name=test --numjobs=1 --filename=/dev/sdb --rw=write --verify=md5
#powercut the system after 10 seconds.
#OS boot
sudo fio --name=test --numjobs=1 --filename=/dev/sdb --rw=read --verify=md5 --verify_state_load=1

**Comment by axboe** [comment]
The state file is _exclusively_ for writes. It just tells you what writes were issued and acknowledge.

Your test may fail, as buffered writes are most certainly not stable. This means it's not a a valid test. If you used O_DIRECT | O_SYNC, then yes it should work.

Caveat here is that this kind of test should generally be run in fio client/server mode, so that the state file itself isn't involved in any powercut scenario.

**Comment by bokidigital** [comment]
Sorry, do you mean if I add direct=1 and sync=1 then the test will pass?

( In our lab environment, we tested fio directly on the client system, no server here )

ex:
sudo fio --name=test --direct=1 --sync=1 --numjobs=1 --filename=/dev/sdb --rw=randwrite --verify=md5
#powercut the system after 10 seconds.
#OS boot
sudo fio --name=test --direct=1 --sync=1 --numjobs=1 --filename=/dev/sdb --rw=randread --verify=md5 --verify_state_load=1
