### ISSUE TITLE
A possible data race bug

### ISSUE THREAD

**Issue by ryancaicse** [axboe/fio#1303]
Hi, when the method **clock_thread_fn** are executed by multiple threads
https://github.com/axboe/fio/blob/5711325cbb37d10c21a6975d1f1ebea11799c05e/gettime.c#L716-L733

Is it possible to race among threads on **Line 634** and **Line 640**?

https://github.com/axboe/fio/blob/5711325cbb37d10c21a6975d1f1ebea11799c05e/gettime.c#L633-L643

Thank for your checking.

**Comment by axboe** [comment]
How so? It's thread private date.

**Comment by ryancaicse** [comment]
Thank you for your time.
It seems my detector is imprecise for handling arrays.
