### ISSUE TITLE
Possible NPD under concurrency

### ISSUE THREAD

**Issue by ryancaicse** [axboe/fio#1305]
Hi, thank you for your checking. In below code, `fd` could be `null`, passing to the child thread.
https://github.com/axboe/fio/blob/a7194b2d3d427e7e5678c55a128639df9caf4a48/backend.c#L2431-L2448

In the child thread, would it induce NPD via dereferencing `fd`?
https://github.com/axboe/fio/blob/a7194b2d3d427e7e5678c55a128639df9caf4a48/backend.c#L1615-L1621

**Comment by ammarfaizi2** [comment]
No need to go that far, we have a potential NULL pointer dereference here.

If the `fd = calloc(1, sizeof(*fd))` fails, `fd->td = fd` would segfault.
```c
			fd = calloc(1, sizeof(*fd));
			fd->td = td;
			fd->sk_out = sk_out;
```

**Comment by axboe** [comment]
We've got plenty of "doesn't check alloc failure" cases, mostly born out of the fact that platforms generally just do overcommit and it's not a real world problem for something like fio.

As for the "race", see previous reply.

**Comment by ryancaicse** [comment]
@axboe Hi, there is another problem, where the parent thread set `fd` to `null` and then the child thread may dereference from a null pointer (**Line 1621** and **Line 1619**).

The parent thread,

https://github.com/axboe/fio/blob/a7194b2d3d427e7e5678c55a128639df9caf4a48/backend.c#L2439-L2448

The child thread,
https://github.com/axboe/fio/blob/a7194b2d3d427e7e5678c55a128639df9caf4a48/backend.c#L1615-L1621

**Comment by ammarfaizi2** [comment]
> @axboe Hi, there is another problem, where the parent thread set fd to null and then the child thread may dereference from a null pointer (Line 1621 and Line 1619).

Get real and stop reporting random invalid issues!

The pointer is copied by value via `pthread_create(..., ..., thread_main, fd)`, so `fd = NULL` after `pthread_create()` does not affect any variable in the `thread_main()`.

**Comment by ryancaicse** [comment]
@ammarfaizi2 Thank you for your reply. This would be the last issue I report in fio, liburing, etc.

`fd` is a thread-shared pointer variable and sets to `null`, so it could affect the `thread_main()` in the child thread.

**Comment by ammarfaizi2** [comment]
> `fd` is a thread-shared pointer variable and sets to `null`, so it could affect the `thread_main()` in the child thread.

Pointer is just a scalar value like an integer, and that variable is local. When it is passed to `pthread_create()`, it is copied by value. In your case, it's just like this.
```c
void fx(void)
{
	struct fork_data *fd;
	fd = calloc(1, sizeof(*fd));
	fy(fd);
	fd = NULL;
}

void fy(struct fork_data *fd)
{
	struct something *p = fd->something;
}
```
If you think that `fd = NULL;` affects any variable in `fy()`, then you are just wrong. Learn C seriously.

**Comment by ryancaicse** [comment]
@ammarfaizi2 I make a mistake here. Thank you indeed for your explaination.
