### ISSUE TITLE
Missing locking on nr_verify_threads?

### ISSUE THREAD

**Issue by ryancaicse** [axboe/fio#1306]
In the main thread, **td->nr_verify_threads++** is not guarded by a lock, where, I guess, misses a lock.
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1468-L1483

In the child thread, **td->nr_verify_threads--;** is guarded by the lock **io_u_lock**.
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1448-L1455

Therefore, I infer there is a contradiction.

**Comment by ryancaicse** [comment]
Similarly,

For this thread-shared access **td->verify_thread_exit**, would it be better to guard it by a lock?
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1404-L1407

**In other places, all write accesses have been guarded.**
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1407-L1419
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1490-L1493
https://github.com/axboe/fio/blob/572782274da6f7223627f734c6e1818a03c71a6d/verify.c#L1503-L1505

**Comment by axboe** [comment]
I'm not interested in these drive-by "race" analysis, since they seemed very half assed. It's init code, and there's no race there.

For any of my projects (I've seen liburing and fio so far), stop reporting these UNLESS you actually understand the code and what it does. You're just wasting everybody's time.

**Comment by ryancaicse** [comment]
@axboe OK, thank you for your time. I would try my best to understand them more before reporting bugs.
