### ISSUE TITLE
when using -rwmixread=50, write and read always have same bandwidth. 

### ISSUE THREAD

**Issue by SHTUSIST** [axboe/fio#1309]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
when using -rwmixread=50, write and read always have same bandwidth.  No matter whatever i used for storage medium, HDD, SSD or  NVM. 
For example, when using -rw=randrw -rwmixread=50. Below is output.
......
Run status group 0 (all jobs):
   READ: bw=25.8MiB/s (27.1MB/s), 25.8MiB/s-25.8MiB/s (27.1MB/s-27.1MB/s), io=258MiB (271MB), run=10001-10001msec
  WRITE: bw=25.7MiB/s (26.9MB/s), 25.7MiB/s-25.7MiB/s (26.9MB/s-26.9MB/s), io=257MiB (269MB), run=10001-10001msec

 I think it is impossible that disks'read bandwidth is same with write bandwidth.  SSD's read bandwidth is same with SSD's write bandwidth as well. 

**Environment**: Linux 5.11.0-37-generic #41~20.04.2-Ubuntu

**fio version**: 3.16, but I have tried other versions. They also has same problem. 

**Reproduction steps**
fio --name=test  -size=5GB -runtime=10 -filename=1.txt -rw=randrw -rwmixread=50

**Comment by axboe** [comment]
It's really an artifact of asking for 50% reads and 50% writes, then you naturally end up with one being throttled by the speed of the other. That's not really a fio issue...
