### ISSUE TITLE
Unable to use parameter --sync=dsync

### ISSUE THREAD

**Issue by arthuravila26** [axboe/fio#1311]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
When I try to run the test using the parameter --sync=dsync I got the error like:
`fio: failed parsing sync=dsync`
Also, when I ran --sync=1 it works just fine but as the documentation says that 1 means Same as sync.

The full command that I'm using:
fio --randrepeat=1 --ioengine=libaio --direct=1 --name=test --filename=test --bs=4k --size=200MB --readwrite=write --ramp_time=4 --runtime=60 --time_based --sync=dsync

**Environment**: CentOS 7.4.1708

**fio version**: fio-2.2.10

**Reproduction steps**
Just run the command provided in the Description.

**Comment by axboe** [comment]
2.2.10 is ancient, have you tried if it reproduces in the current version?

**Comment by axboe** [comment]
You clicked you did read the REPORTING-BUGS, but one of the first things that says is:

> If you are not running the newest release of fio please upgrade first.

Please reopen if this issue persists in the newest fio release.
