### ISSUE TITLE
Four places with memory leaks

### ISSUE THREAD

**Issue by ycaibb** [axboe/fio#1319]
`map` is leaked at `Line 42`
https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/t/axmap.c#L42-L46

`map` is leaked at `Line 192`
https://github.com/axboe/fio/blob/6202c70d8d5cbdd3fb4bc23b96f691cbd25a327e/t/axmap.c#L191-L195

`ts_lcl ` is leaked at `Line 499`
https://github.com/axboe/fio/blob/e86afa536b175a90546e20d7d19f2418ee1bca78/stat.c#L489-L499
`pthreads` is leaked
https://github.com/axboe/fio/blob/e86afa536b175a90546e20d7d19f2418ee1bca78/t/memlock.c#L51-L62

**Comment by axboe** [comment]
Only the stat one is really interesting, the rest are just shortlived test programs and those resources get cleaned up by the OS when they exit.

**Comment by ycaibb** [comment]
Thanks
