### ISSUE TITLE
Incorrect error message from __file_invalidate_cache()

### ISSUE THREAD

**Issue by rgmiller** [axboe/fio#132]
I've noticed a case where `__file_invalidate_cache()` will not print a correct error message.  At line 414 (of filesetup.c), `posix_fadvise()` is called.  If there's an error, then the program will eventually hit line 447, where the error message is printed.  This message is constructed using `strerror( errno)`.  However, `posix_fadvise()` doesn't set errno.  Any error codes are stored in its return value.  (At least for Linux; I haven't tried on other OS's.)  This leads to the following rather confusing error message:

>fio: cache invalidation of test_output/datafile.tmp failed: Success

One simple fix would be to just assign errno to ret immediately after the call to `posix_fadvise()`.  I'm not sure if that's the best solution or not.

**Comment by axboe** [comment]
Fixed and committed, same thing was true for the IO engine ->invalidate() hook.

**Comment by rgmiller** [comment]
Need to re-open:  The value of ret will never be less than 0 (line 417).  According to the man page, `posix_fadvise()` either returns either 0, 9 (EBADF), 22 (EINVAL) or 29 (ESPIPE).   I think the conditional needs to be `(ret != 0)` (or just get rid of it entirely and always assign errval to ret).

**Comment by axboe** [comment]
Good catch. Updated, close if you're happy with it.

**Comment by rgmiller** [comment]
Yep.  Looks good now.  Thanks for the quick turnaround.
