### ISSUE TITLE
Access to unusable blocks on the zoned block device

### ISSUE THREAD

**Issue by ryderhsu0129** [axboe/fio#1323]
We try to use fio(v.3.26) to access the NVMe ZNS device, 
the zone capacity of this device is smaller than the zone size(ZCAP < ZSZE),
as expected, fio will skip access to blocks between zone capacity and zone size, and access to the next zone,
but from the results, the fio will access to unusable blocks caused some error,
the following is the command line we issued :
`fio --name=zbd --filename=/dev/nvme0n1 --direct=1 --zonemode=zbd --ioengine=libaio --iodepth=1 --rw=write --bs=256K --offset=0 --size=16G`

please help clarify this issue, thanks!

**Comment by sitsofe** [comment]
Mentioning @floatious, @damien-lemoal for comment.

**Comment by damien-lemoal** [comment]
Please try again with the latest fio version and check if the problem persists.

Also, could you please clarify the problem description ? You say: "as expected, fio will skip access to blocks between zone capacity and zone size, and access to the next zone" but then say "from the results, the fio will access to unusable blocks caused some error". Did you mean "as expected, fio SHOULD skip access..." ? Or is fio behaving correctly for reads but not for writes ?

Please also copy paste the error message you are seeing.

**Comment by ryderhsu0129** [comment]
> Please try again with the latest fio version and check if the problem persists.
> 
> Also, could you please clarify the problem description ? You say: "as expected, fio will skip access to blocks between zone capacity and zone size, and access to the next zone" but then say "from the results, the fio will access to unusable blocks caused some error". Did you mean "as expected, fio SHOULD skip access..." ? Or is fio behaving correctly for reads but not for writes ?
> 
> Please also copy paste the error message you are seeing.

Sorry for not describing it clearly,
It's unable to write to blocks in the interval between zone capacity(ZCAP) and zone size(ZSZE),
but fio will write blocks in this range cause some error.

We will try again with the latest version and update the result.

**Comment by floatious** [comment]
I didn't see any --max_open_zones argument on the command line.

Since you are using a ZNS device,
your kernel should be recent enough to have max_open_zones in sysfs.

If you use a more recent version of fio, it should be able to automatically
get the correct value from sysfs, such that you don't need to specify it
manually.

**Comment by ryderhsu0129** [comment]
It's working on latest fio version(3.29), thanks for your suggestions.
