### ISSUE TITLE
io_uring - Invalid argument

### ISSUE THREAD

**Issue by vbienf** [axboe/fio#1324]
**Please acknowledge the following before creating a ticket**

- [+] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Its my first time using of this engine, so maybe I do something wrong. Read and google all information, but didn't find any solution. If I run the same command for libaio or for sync ( without sqthread_poll) - all works.

**Environment**: 
Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-91-generic x86_64)

**fio version**: 
fio-3.29-5-ga3e3

**Reproduction steps**
1. git clone master branch
2. install fio (configure, makem make install)
3. Run command:
sudo fio  --size=50G --rw=randwrite --iodepth=1 --bs=8kb --numjobs=1 --filename=/dev/nvme5n1 --ioengine=io_uring --sqthread_poll=1 --direct=1 --name=test

Result:
/fio$ sudo fio  --size=50G --rw=randwrite --iodepth=1 --bs=8kb --numjobs=1 --filename=/dev/nvme5n1 --ioengine=io_uring --sqthread_poll=1 --direct=1 --name=test
test: (g=0): rw=randwrite, bs=(R) 8192B-8192B, (W) 8192B-8192B, (T) 8192B-8192B, ioengine=io_uring, iodepth=1
fio-3.29-5-ga3e3
Starting 1 process
fio: pid=51194, err=22/file:engines/io_uring.c:781, func=io_queue_init, error=Invalid argument

Run status group 0 (all jobs):

Disk stats (read/write):
  nvme5n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Comment by axboe** [comment]
For older kernels, you need to use ```registerfiles``` as well for sqpoll.

**Comment by vbienf** [comment]
> For older kernels, you need to use `registerfiles` as well for sqpoll.

Hi axboe! Thanks for your answer.

I added this parameter to command line, but still see an error:

sudo fio --size=50G --rw=randwrite --iodepth=1 --bs=8kb --numjobs=1 --filename=/dev/nvme5n1 --ioengine=io_uring --sqthread_poll=1 --registerfiles=1 --direct=1 --name=test
test: (g=0): rw=randwrite, bs=(R) 8192B-8192B, (W) 8192B-8192B, (T) 8192B-8192B, ioengine=io_uring, iodepth=1
fio-3.29-5-ga3e3
Starting 1 process
fio: pid=12420, err=22/file:engines/io_uring.c:781, func=io_queue_init, error=Invalid argument


Run status group 0 (all jobs):

Disk stats (read/write):
  nvme5n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

also, double check with registerfiles=0, still same error

**Comment by axboe** [comment]
Can you try and do:

# sudo strace -o xx -f fio <insert your arguments here>

and find io_uring_setup() in there and see what arguments are passed? It could just be that the old ubuntu kernel doesn't support SQPOLL. It sure looks like it, if init is failing with an invalid flag.

**Comment by vbienf** [comment]
> Can you try and do:
> 
> `# sudo strace -o xx -f fio <insert your arguments here>`
> 
> and find io_uring_setup() in there and see what arguments are passed? It could just be that the old ubuntu kernel doesn't support SQPOLL. It sure looks like it, if init is failing with an invalid flag.

I didn't find nothing with "**io_uring**" in this trace.
closest syscall to this error:
```
19819 stat("/tmp/fio-dump-status", 0x7fff6f52fd60) = -1 ENOENT (No such file or directory)
19819 nanosleep({tv_sec=0, tv_nsec=100000000}, NULL) = 0
19819 futex(0x7f8004ad7050, FUTEX_WAKE, 1) = 1
19819 wait4(19904,  <unfinished ...>
19904 <... futex resumed> )             = 0
19819 <... wait4 resumed> 0x7fff6f530de4, WNOHANG, NULL) = 0
19904 futex(0x7f8004ad7000, FUTEX_WAKE, 1 <unfinished ...>
19819 wait4(19904,  <unfinished ...>
19904 <... futex resumed> )             = 0
19819 <... wait4 resumed> 0x7fff6f530de4, WNOHANG, NULL) = 0
19819 stat("/tmp/fio-dump-status", 0x7fff6f52fd60) = -1 ENOENT (No such file or directory)
19819 nanosleep({tv_sec=0, tv_nsec=10000000},  <unfinished ...>
19904 openat(AT_FDCWD, "/sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size", O_RDONLY) = 6
19904 read(6, "64\n", 32)               = 3
19904 close(6)                          = 0
19904 syscall_0x1a9(0x1, 0x7fff6f530ab0, 0, 0x1, 0x1, 0x7f80038a4c40) = -1 (errno 22)
19904 write(1, "fio: pid=19904, err=22/file:engi"..., 95) = 95
19904 munmap(NULL, 0)                   = -1 EINVAL (Invalid argument)
19904 munmap(NULL, 0)                   = -1 EINVAL (Invalid argument)
19904 munmap(NULL, 0)                   = -1 EINVAL (Invalid argument)
19904 close(0)                          = 0
19904 exit_group(22)                    = ?
19904 +++ exited with 22 +++

```
btw, in the beginning of this trace, if I understand correctly,  I see that fio runs libaio:
`19819 openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libaio.so.1", O_RDONLY|O_CLOEXEC) = 3`

**Comment by axboe** [comment]
It's this one:

```
19904 syscall_0x1a9(0x1, 0x7fff6f530ab0, 0, 0x1, 0x1, 0x7f80038a4c40) = -1 (errno 22)
```

your strace is just too old and doesn't understand it. Unfortunately since it doesn't understand it, it doesn't decode the 2nd argument for us, which is what we need. But I think it's pretty certain that your kernel just doesn't support SQPOLL, which is consistent with the setup error. You'll want to upgrade post an ancient 5.4.

**Comment by vbienf** [comment]
> It's this one:
> 
> ```
> 19904 syscall_0x1a9(0x1, 0x7fff6f530ab0, 0, 0x1, 0x1, 0x7f80038a4c40) = -1 (errno 22)
> ```
> 
> your strace is just too old and doesn't understand it. Unfortunately since it doesn't understand it, it doesn't decode the 2nd argument for us, which is what we need. But I think it's pretty certain that your kernel just doesn't support SQPOLL, which is consistent with the setup error. You'll want to upgrade post an ancient 5.4.

but I use kernel version Linux 5.4.0-91-generic x86_64. And I know, that Intel's team run test on ubuntu 18 with io_uring. Can you help me, what exactly I need to update?

**Comment by axboe** [comment]
Try current -git of fio, that should fix it.

**Comment by vbienf** [comment]
> Try current -git of fio, that should fix it.

yep. It works! Thanks @axboe for your help!
