### ISSUE TITLE
bssplit is off by 8x

### ISSUE THREAD

**Issue by srosenberg** [axboe/fio#1325]
**Please acknowledge the following before creating a ticket**

- [ yes ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

block sizes specified in `bssplit` are multiplied by `8` as confirmed by `blktrace` in a sequential write job

**Environment**: 

```
Ubuntu 20.04.2 LTS
```

**fio version**:

Built from master,

```
/usr/local/bin/fio -version
fio-3.29-7-g01686
```

**Reproduction steps**

### Config file

```
cat fio.cfg

[global]
thread=1
ioengine=libaio
direct=1
fadvise_hint=0
group_reporting=1
randrepeat=0
verify=0
time_based=1
runtime=1m
ramp_time=2s
size=100%

[wr-bw]
rw=write
bs=4096
bssplit=4k/72:8k/18:12k/3:16k/7
iodepth=256
numjobs=1
stonewall
```

**NOTE**: our desired block size distribution is given by,

```
bssplit=4k/72:8k/18:12k/3:16k/7
```

### Run

Start `blktrace`,

```
blktrace -d /dev/md0 -o blktrace_run.bin
```

Start `fio`,

```
/usr/local/bin/fio --filename="/dev/md0" fio.cfg
```

#### Analyze `blktrace` results

Parse out writes and compute their histogram,

```
blkparse blktrace_run.bin -a write|awk '/ Q / { if ($7 ~ /W/) print $10 }' |sort |uniq -c |sort -rn >run_writes.txt
```

Count total number of writes,

```
cat run_writes.txt|awk '{total += $1} END {print total}'
11230124
```

Output percentage of block sizes written,

```
cat run_writes.txt|awk 'BEGIN {total = 11230124; blockSize = 4096} {printf("%d (%f%%)\n", $2*blockSize, 100.0 *($1 / total))}'|head
32768 (72.003301%)
65536 (18.000451%)
131072 (6.994126%)
98304 (3.002122%)
```

N.B. Percentages are matching up but the block sizes are _consistently_ off by 8x. (I've repeated this several times with different values of `bssplit`, each time I get the same distribution _modulo_ the scaling of the block sizes by `8`).

**Comment by sitsofe** [comment]
@srosenberg How big are the sectors of your md0 device? Why don't you try a simpler fio command that doesn't use bssplit but also uses an iodepth of 1 and check that blktrace output is what you expect...

**Comment by srosenberg** [comment]
> @srosenberg How big are the sectors of your md0 device? 

```
fdisk -l /dev/md0
Disk /dev/md0: 1.1 TiB, 1207553753088 bytes, 294812928 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 524288 bytes / 1572864 bytes
```

> Why don't you try a simpler fio command that doesn't use bssplit but also uses an iodepth of 1 and check that blktrace output is what you expect...

I did; e.g., removing `bssplit` and setting `iodepth` to 1, I get the following distribution from blktrace,

```
cat run_writes.txt|awk 'BEGIN {total = 855260; blockSize = 4096} {printf("%d (%f%%)\n", $2*blockSize, 100.0 *($1 / total))}'|head
32768 (100.000000%)
```

It's again 8x of the expected (4096) owing to `bs=4096` in fio.cfg.

**Comment by axboe** [comment]
And you're certain you're not mixing up sectors in blktrace with bytes? The 8x is a bit suspicious, since that would be the the multiplier there.

Might be useful to use write_iolog with fio and see what fio is doing, because that's all fio really controls.

**Comment by srosenberg** [comment]
> And you're certain you're not mixing up sectors in blktrace with bytes?

Fairly certain because it's matching up with our internal IO workload; e.g., our max chunk size is 32kb, and it shows up as the more frequent block size after post-processing blktrace.

> The 8x is a bit suspicious, since that would be the the multiplier there.

Indeed; 512 bytes is a typical sector size, but this raid0 ssd array has 4096. Any clues where it might be coming from?

> 
> Might be useful to use write_iolog with fio and see what fio is doing, because that's all fio really controls.

Let me try that and report back.

**Comment by srosenberg** [comment]
> > Might be useful to use write_iolog with fio and see what fio is doing, because that's all fio really controls.
> 
> Let me try that and report back.

Says it's writing 4096 :)

```
fio version 2 iolog
/dev/md0 add
/dev/md0 open
/dev/md0 write 0 4096
/dev/md0 write 4096 4096
/dev/md0 write 8192 4096
/dev/md0 write 12288 4096
/dev/md0 write 16384 4096
/dev/md0 write 20480 4096
/dev/md0 write 24576 4096
...
```

**Comment by srosenberg** [comment]
I am beginning to think that `blktrace` hardcodes the sector size to `512` regardless of the device?! [1]. E.g.,

```
259,0    0     1329     0.103408288 14521  Q  WS 1712 + 8 [fio]
259,0    0     1335     0.103478873 14521  Q  WS 1720 + 8 [fio]
```

clearly says `fio` issued writes to 8 sectors at offset 1712 whereas in reality it was a single write (of 4096) from the perspective of the ssd controller?

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/types.h#n120

**Comment by axboe** [comment]
Yes, that is a very likely reason. The 8x made me suspicious because of exactly that, doesn't seem accidental.

**Comment by srosenberg** [comment]
@sitsofe @axboe Sorry for the noise, and thanks for your help! Would it make sense to update the `blktrace` manual as well as confirm that's the intended logic?
