### ISSUE TITLE
randwrite and randrw with --rwmixread=0 --rwmixwrite=100

### ISSUE THREAD

**Issue by LiliDeng** [axboe/fio#133]
Hi guys, do you know below two commands differences?

fio -filename=./test -iodepth=64 -ioengine=libaio -direct=1 -thread -rw=randwrite  -bs=8k -size=134G -numjobs=64 -runtime=300 -group_reporting -name=test-rand-write 

fio --filename=./test --iodepth=64 --ioengine=libaio --direct=1 --rw='randrw' --bs=8k --size=134G --numjobs=8 --runtime=300 --group_reporting --name=test-rand-write --norandommap --randrepeat=0 --refill_buffers --scramble_buffers=1 --time_based --rwmixread=0 --rwmixwrite=100

**Comment by axboe** [comment]
You're going to have to be more specific than that, what are you asking? rw=randwrite and rw=randrw --rwmixwrite=100 are identical, if that's the question. But there are a lot of other differences between the two job definitions.

**Comment by LiliDeng** [comment]
Other parameter are the same, but the results run out from randwrite and randrw with --rwmixread=0 --rwmixwrite=100 are different.

**Comment by axboe** [comment]
Different how? Again, you're going to be more specific than that. The two jobs you listed, there was a lot of differences outside of just being randwrite or randrw/rwmixwrite=100.

I don't mind help you get to the bottom of this, but I generally don't like to waste my time guessing. Provide all the information that you have and think could be useful, then we can take a look at it.

**Comment by axboe** [comment]
static inline enum fio_ddir get_rand_ddir(struct thread_data *td)               
{                                                                               
        uint64_t frand_max = rand_max(&td->rwmix_state);                        
        unsigned int v;                                                         
        unsigned long r;                                                        
                                                                                
        r = __rand(&td->rwmix_state);                                           
        v = 1 + (int) (100.0 * (r / (frand_max + 1.0)));                        
                                                                                
        if (v <= td->o.rwmix[DDIR_READ])                                        
                return DDIR_READ;                                               
                                                                                
        return DDIR_WRITE;                                                      
}

This is the code that will generate the data direction, in io_u.c. For rwmixwrite=100, rwmix[DDIR_READ] is 0. The smallest number that 'v' can be us 1, so we'll never generate a read. So I'm assuming you aren't talking about potentially reads being mixed in.
