### ISSUE TITLE
fio continuing on header verification error

### ISSUE THREAD

**Issue by jml9904** [axboe/fio#134]
On encountering errors similar to:

verify: bad magic header 0, wanted acca at file /test/c59207d6-4336-48b3-a93b-4863bd07553e/mounts/lvm-xfs/lvm-xfs.dat offset 1456209920, length 512

with the fio control file below, I would expect fio to dump <id>.expected / <id>.received files. The dumps do occur if there is payload corruption but not on header issues. Is it possible to also dump on header corruption?

Thanks!

Control file:

[global]
name=single_path_drop_test_loop_0000-fio
bs=128k
direct=1
ioengine=libaio
verify=md5
verify_pattern=0xaa555aa5
verify_interval=512
verify_fatal=0
verify_dump=1
filename=/dev/xxxxxxxx
size=48318382080

[test-phase]
unlink=1
continue_on_error=all
rw=readwrite
rwmixread=70
do_verify=1
time_based=1
runtime=85

**Comment by jml9904** [comment]
... ideally, it'd stop on that first error too... verify_fatal=1 and continue_on_error=none don't seem to cause it to stop.

**Comment by axboe** [comment]
For the data dumps, fio uses the information in the (validated) header to generate them. Since the header is corrupt for your case, fio can't really tell you more than it already did. It should stop, though, depending on the settings for that. If it doesn't, then that is a bug.

**Comment by jml9904** [comment]
Would it be possible to dump anyway (so we can see the information in the header itself)? It'd help us determine exactly what/where the data corruption is occurring. I don't expect fio to tell me anything new, just want to see what it saw.

**Comment by axboe** [comment]
Sure, that part is not a problem. But you have the information right there to do it manually as well:

/test/c59207d6-4336-48b3-a93b-4863bd07553e/mounts/lvm-xfs/lvm-xfs.dat offset 1456209920, length 512

that's the file, the byte offset, and the length of the header.

**Comment by jml9904** [comment]
Yup. I could probably script an od command to do that. Especially on a raw device, though, it'd be nice if a future version could do the dumps natively.

**Comment by axboe** [comment]
Sure, I can add that, I can see how it would be useful. I just tested continue_on_error=all, and it marches on with verification failures. continue_on_error=none, and it exits on the first one. So that part seems to work fine here, using current -git.

**Comment by jml9904** [comment]
I'll retry the continue_on_error bit. Perhaps something weird here. Thanks a million!!!

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=16758b598075628288c2fbefa822f81f282577b5

That's the one-liner to dump the header as well, it'll show up as file.offset.hdr_fail, similar to the expected/received files. Let me know if you see issues with the continue_on_error, that should definitely work fine.

**Comment by jml9904** [comment]
The continue_on_error seems OK. One more thing - can we also dump the "expected" comparison data?

**Comment by axboe** [comment]
I can't dump the expected header, that would require a crystal ball :-). It's not like the data, which fio can re-generate if it has a valid header. Without a valid header, we can't do anything but dump the corrupt header. For the data, fio does spit out both the bad and good data.

**Comment by jml9904** [comment]
Got it. I can extract the expected data from the error message then. Some of the early dumps I got were really trashed, but I think that was due to the fault injection working _too_ well. 

Thanks again...

**Comment by axboe** [comment]
Let's back up a bit... Fio is now dumping the corrupt header. That includes the header contents we got, the offset, file, length. That's the same as what is in the error message. It's all the information that fio has. What are you looking to get out of the error message?

**Comment by jml9904** [comment]
"wanted acca at file /dev/dssd0000 offset 42299392"

I can look at the actual sector dump to see what ended up at that offset instead of 0xacca... did we get zeroes instead? corrupt data? etc...

That's what I was after. Exactly what did we expect, and what did we get instead?

**Comment by axboe** [comment]
The comment from yesterday:

https://github.com/axboe/fio/issues/134#issuecomment-165155574

mentions that fio dumps the header as a file now. It'll show up as file.offset.hdr_fail. With that in hand, you can see what is there instead of 0xacca. You might have to consult the header definition, but generally I would not expect people to look at that, you'd probably just hexdump the stored file and look at the contents.

**Comment by jml9904** [comment]
Right. I'll pull the definitions and go from there - the hexdump does indeed show me the differences. BTW, continue_on_error is fine... typo in script was screwing things up.

Gracias!
