### ISSUE TITLE
couldn't able to load io engine libcufile

### ISSUE THREAD

**Issue by saibha** [axboe/fio#1340]
**Please acknowledge you have done the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Comment by axboe** [comment]
Please file a proper bug report, thanks.

**Comment by saibha** [comment]
i have to enable libcufile by using configure file 

cli which i have used 
./configure --enable-libcufile

error message:-
ERROR
ERROR: User requested feature libcufile
ERROR: configure was not able to find it
ERROR
Configure failed, check config.log and/or the above output

**Comment by sitsofe** [comment]
@saibha You don't have the cuda includes available to compile against - look at your last screenshot. See https://github.com/axboe/fio/blob/6a16e9e9531a5f746c4e2fe43873de1db434b4fc/ci/actions-install.sh#L54 for the package the CI has installed.

**Comment by saibha** [comment]
@sitsofe could you please elaborate your resolution  and also kindly help us what will be workaround i need to do as per your resolution

**Comment by axboe** [comment]
Helping with other projects is beyond the scope of fio.

**Comment by saibha** [comment]
@axboe ,I'm was just asking for detailed resolution so that i can work on my project .I have tried to install nvidia-cuda-dev by using the yum to install.as per the resolution I have in comments but I'm below issue. I was just cross checking whether i have followed right resolution or not 
![image](https://user-images.githubusercontent.com/47551371/154294378-ffae6970-7987-4408-83ae-1b2292f6f8b0.png)

**Comment by saibha** [comment]
@sitsofe Thanks a lot for your inputs
