### ISSUE TITLE
Ubuntu 20 engine libaio not loadable

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1343]
when I run the following fio
fio --filename=/mnt/podnfs --direct=1 --rw=write --bs=512K --ioengine=libaio --iodepth=128 --size=10g --runtime=12 --numjobs=10 --time_based --group_reporting --name=thr
**fio: engine libaio not loadable
fio: failed to load engine**

 fio --enghelp
Available IO engines:
        cpuio
        mmap
        sync
        psync
        vsync
        pvsync
        pvsync2
        null
        net
        netsplice
        ftruncate
        filecreate
        filestat
        filedelete
        exec
        posixaio
        falloc
        e4defrag
        splice
        mtd
        sg
        io_uring

apt list |grep libaio

libaio-dev/focal,now 0.3.112-5 amd64 [installed]
libaio-dev/focal 0.3.112-5 i386
libaio1/focal,now 0.3.112-5 amd64 [installed]
libaio1/focal 0.3.112-5 i386

I have uninstalled FIO and recompiled but still can't get FIO to load libaio
Any help would be greatly appreciated

**Comment by axboe** [comment]
Paste the configure output in here, and also check what config.log says around where libaio is checked.

**Comment by dpronin** [comment]
If you compile yourself check if `config-host.h` contains `CONFIG_LIBAIO` defined upon running configure script. Your engines list gives a hint that there is no 'libaio' engine available that leads me to a thought that FIO has not been compiled with libaio enabled by some reason. For example, when configuring, it could not be found:

Check out the `configure` script, there is a snippet:
```
##########################################
# linux-aio probe
if test "$libaio" != "yes" ; then
  libaio="no"
fi
if test "$esx" != "yes" ; then
  cat > $TMPC <<EOF
#include <libaio.h>
#include <stddef.h>
int main(void)
{
  io_setup(0, NULL);
  return 0;
}
EOF
  if compile_prog "" "-laio" "libaio" ; then
    libaio=yes
  else
    if test "$libaio" = "yes" ; then
      feature_not_found "linux AIO" "libaio-dev or libaio-devel"
    fi
    libaio=no
  fi
```
