### ISSUE TITLE
FIO verify job fail with error=Permission denied

### ISSUE THREAD

**Issue by LamNguyen25** [axboe/fio#1346]
Hi,
I'm running FIO job on Windows instances by running python scripts using Popen. 

The error is from this command: Verify if we can read the same size of data (run FIO command with random read on each device)

cmd = ['PowerShell.exe', '& $Env:ProgramFiles\\fio\\fio.exe', '--output=verify_vol-096da7c71479c12cf_ev_writes.out', '--direct=1', '--ioengine=windowsaio', '--filename=\\\\.\\PHYSICALDRIVE3', '--iodepth=32', '--verify=crc32c', '--rw=randwrite', '--
verify_dump=1', '--verify_fatal=1', '--randseed=4250', '--do_verify=1', '--name=vol-096da7c71479c12cf_ev_writes', '--bsrange=4k-128k', '--verify_pattern=0xFF', '--norandommap=1', '--replay_no_stall=1', '--read_iolog=read_vol-096da7c71479c12cf_ev_writes
.iolog']

p=Popen(cmd)

The fio version I am using is 3.27

I observe the following error: https://github.com/axboe/fio/blob/master/engines/windowsaio.c#L469

fio: norandommap given for variable block sizes, verify limited
vol-096da7c71479c12cf_ev_writes: (g=0): rw=randwrite, bs=(R) 4096B-128KiB, (W) 4096B-128KiB, (T) 4096B-128KiB, ioengine=windowsaio, iodepth=32
fio-3.27
Starting 1 thread
windowsaio: failed to flush file buffers
fio: pid=636, err=13/file:ioengines.c:390, func=td_io_queue, error=Permission denied

vol-096da7c71479c12cf_ev_writes: (groupid=0, jobs=1): err=13 (file:ioengines.c:390, func=td_io_queue, error=Permission denied): pid=636: Sat Feb 19 06:36:34 2022
  read: IOPS=1992, BW=128MiB/s (135MB/s)(75.3GiB/600917msec)
    slat (nsec): min=1845, max=328282, avg=6763.18, stdev=6002.32
    clat (usec): min=177, max=81673, avg=16029.83, stdev=1852.24
     lat (usec): min=196, max=81681, avg=16036.60, stdev=1852.21
    clat percentiles (usec):
     |  1.00th=[12125],  5.00th=[13304], 10.00th=[13960], 20.00th=[14615],
     | 30.00th=[15139], 40.00th=[15664], 50.00th=[16057], 60.00th=[16450],
     | 70.00th=[16909], 80.00th=[17433], 90.00th=[18220], 95.00th=[18744],
     | 99.00th=[20055], 99.50th=[20579], 99.90th=[21890], 99.95th=[24773],
     | 99.99th=[44827]
   bw (  KiB/s): min=130741, max=282812, per=100.00%, avg=131586.39, stdev=4779.09, samples=1184
   iops        : min= 1872, max= 4374, avg=1994.53, stdev=82.81, samples=1184
  lat (usec)   : 250=0.01%, 500=0.01%, 750=0.02%, 1000=0.03%
  lat (msec)   : 2=0.09%, 4=0.07%, 10=0.05%, 20=98.77%, 50=0.95%
  lat (msec)   : 100=0.01%
  cpu          : usr=1.83%, sys=0.67%, ctx=0, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=3.4%, 32=96.6%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.1%, 16=0.1%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwts: total=1197568,0,0,1 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
   READ: bw=128MiB/s (135MB/s), 128MiB/s-128MiB/s (135MB/s-135MB/s), io=75.3GiB (80.9GB), run=600917-600917msec

Can someone please help me troubleshoot the issue below?
Thank in advance!

**Comment by sitsofe** [comment]
Did you see the warning about filesystems over in https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename ?

However, as this isn't so much an issue in fio and more of a "[How do I/Why is?](https://github.com/axboe/fio/blob/master/.github/SUPPORT.md#general-questions)" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.29/README#L58) (note: the list only accepts plain text emails).

**Comment by LamNguyen25** [comment]
you meant this can be an error with the filename?

sorry I wasn't aware of this. should I send an email to fio@vger.kernel.org?

**Comment by LamNguyen25** [comment]
I noticed that the error comes from [DDIR_SYNC_FILE_RANGE](https://github.com/axboe/fio/blob/master/engines/windowsaio.c#L469), but [sync_file_range](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-sync-file-range) is only supported on Linux. Is this true?
