### ISSUE TITLE
no way to enable debug compile then we can gdb debug fio code line by line

### ISSUE THREAD

**Issue by gaowayne** [axboe/fio#1369]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
./configure --extra-cflags=-od --disable-optimizations  --extra-cflags=-g 

tried this, but gdb cannot get breakpoint hit. 

**Environment**: 

**fio version**: 3.29

**Reproduction steps**

./fio /tmp/null.fio

**Comment by gaowayne** [comment]
I figure out already. 
![image](https://user-images.githubusercontent.com/67108838/159146904-a0c72b8b-23da-4766-99d5-45d59096965d.png)

**Comment by gaowayne** [comment]
closed

**Comment by gaowayne** [comment]
@axboe  man, after I use the latest master code, above way to enable debug mode is not working anymore, could you please shed me light how to enable debug so that I can gdb step by step debug?

**Comment by gaowayne** [comment]
sorry, I figure it out

**Comment by gaowayne** [comment]
I can debug the posixaio engine, but enable I add g++ -O0 -g -shared -rdynamic -fPIC -o cpp_null null.c -include ../config-host.h -DFIO_EXTERNAL_ENGINE
I still cannot debug cpp_null engine. could you please shed some light?

**Comment by axboe** [comment]
This is really beyond what we can help with here, you just need to figure out what is going on with your external build.

**Comment by gaowayne** [comment]
@axboe I am just using the null.c example external build, it can run well, just I cannot build out debug version so that I can debug that part code.  :(

**Comment by axboe** [comment]
I know, but this is more of a normal "how do I debug this" question than it is a fio question, and as such really beyond the scope of what can be expected in terms of help from a project. It's not fio specific at all.

**Comment by gaowayne** [comment]
> I know, but this is more of a normal "how do I debug this" question than it is a fio question, and as such really beyond the scope of what can be expected in terms of help from a project. It's not fio specific at all.

can you take this as how to debug fio external C++ plugin engine question?  :)

**Comment by gaowayne** [comment]
I tried -ggdb also does not work.
Could you please make a quick try?

**Comment by axboe** [comment]
No, I don't have any time to help you debug this, and as explained, it's outside the scope of what can be expected here.
