### ISSUE TITLE
failure on receiving state file: No such file or directory

### ISSUE THREAD

**Issue by gang2015** [axboe/fio#137]
The error happens in my power cut test with fio running server/client mode.
fio version is  "fio-2.3-11-g5f3b"
1. server:
   There are two config files on server: 
write-test.fio

 [global]
overwrite=1
direct=1
refill_buffers=1
randrepeat=0
disable_slat=1
disable_lat=1
ioengine=libaio
filename=/dev/nvme0n1
blocksize=4k
iodepth=32
[write]
time_based=1
runtime=20m
rw=randwrite
verify=md5
do_verify=0  

-----------------
    
  verifyserver.fio : 

  [global]
overwrite=1
direct=1
refill_buffers=1
randrepeat=0
disable_slat=1
disable_lat=1
ioengine=libaio
filename=/dev/nvme0n1
blocksize=4k
iodepth=32
[read]
verify_state_load=1
verify=md5
verify_only
rw=randread

  ------------------------------------

 run fio cmd # fio --server
fio: server listening on 0.0.0.0,8765

---------------------

2.  client:
We run fio cmd, and call power_off_server.sh to power circle the server after 25 seconds.

----------------

 #  fio --client=server_ip --trigger-timeout=25s --remote-config=write-test.fio --trigger="power_off_server.sh"
hostname=server_ip, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-2.3-11-g5f3b, flags=1
<server_ip> write: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=32
<server_ip> Starting 1 process
client <server_ip>: timeout on SEND_ETAs] [0/41.5K/0 iops] [eta 19m:36s]
client <server_ip>: timeout on SEND_ETA
...
client <server_ip>: timeout on SEND_ETA
fio: client server_ip, timeout on cmd SEND_ETA
fio: client server_ip timed out

-------------------------

Then client gets state file from server: server_ip-write-0-verify.state

After server is up, ran fio on server: # fio --server
And client ran fio to do the remote verify:  # fio --client=server_ip --remote-config=verifyserver.fio

The server always complains failure on receiving state file, while the state file exists in client folder.
fio: server listening on 0.0.0.0,8765
fio: failure on receiving state file: No such file or directory
-------------
fio: mutex.c:163: fio_mutex_down: Assertion `mutex->magic == 0x4d555445U' failed.

Is it a bug, or I mis-use the server/client verification?

**Comment by axboe** [comment]
Two things going on here, one is a fio bug and the other is a user error. If you look at your two job files, they have separate section names. For the write-test.fio, the job that runs is called 'write'. So your state file ends up being named something ala:

<ip address>-write-0-verify.state

After the reboot, you run verifyserver.fio, which has a job called 'read'. So the server would request a file ala:

<ip address>-read-0-verify.state

which doesn't exist. Fio apparently doesn't handle that error case, and ends up failing. I'll fix up that part, and also include the requested file name in the error output. If fio had that, I suspect you would have noticed the problem. For now, rename your job sections to have the same name, and it should work fine.

**Comment by axboe** [comment]
Fixed the error handling as well, you would now have seen:

fio: server listening on 0.0.0.0,8765
fio: failure on receiving state file <ip addr>-read-0-verify.state: No such file or directory216.160.245.100

on the server side, and the client would have disconnected like before.

**Comment by axboe** [comment]
Gah, the web interface sucks. For all the above comments, there's an IP address before the rest of the state file names...

**Comment by gang2015** [comment]
Thanks for the explanation.
After I correct the job name in verify config the same as write config, and remove  randrepeat setting, the server/client mechanism work with verification now.

randrepeat set as 0 will cause the verification can't replay the rand sequence, and fail to verify the previous write data.

**Comment by axboe** [comment]
> randrepeat set as 0 will cause the verification can't replay the rand sequence, and fail to verify the previous write data.

That's expected, as the sequences, data contents, etc will then be different between runs. You need either randrepeat=1, or run the two jobs with the same randseed.

**Comment by gang2015** [comment]
Yes. randrepeat as 1 or the same randseed works for my use case.
