### ISSUE TITLE
build will when try to enable cpp null engine

### ISSUE THREAD

**Issue by gaowayne** [axboe/fio#1371]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
follow cpp null engine guide in the code, there is build error.

**Environment**:  FedoraOS33

**fio version**: v3.29

**Reproduction steps**
run below build command then you get build error need fix that is related with kernel API. disable treat warning as error cannot fix this

root@wcp116:/home/intel/wayne/debugfio/fio/engines# g++ -O0 -g -shared -rdynamic -fPIC -o cpp_null null.c -DFIO_EXTERNAL_ENGINE
In file included from ../os/os.h:39,
                 from ../thread_options.h:5,
                 from ../fio.h:18,
                 from null.c:19:
../os/os-linux.h:147:19: error: ‘int gettid()’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  147 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from ../fio.h:12,
                 from null.c:19:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘__pid_t gettid()’
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
null.c: In function ‘void get_ioengine(ioengine_ops**)’:
null.c:270:28: error: invalid conversion from ‘int (*)(thread_data*, io_u*)’ to ‘fio_q_status (*)(thread_data*, io_u*)’ [-fpermissive]
  270 |  ioengine.queue          = fio_null_queue;
      |                            ^~~~~~~~~~~~~~
      |                            |
      |                            int (*)(thread_data*, io_u*)
null.c: In function ‘null_data* null_init(thread_data*)’:
null.c:100:1: warning: control reaches end of non-void function [-Wreturn-type]
  100 | }

**Comment by axboe** [comment]
Please fill in the bug report as requested, most important being how to reproduce.

**Comment by gaowayne** [comment]
> Please fill in the bug report as requested, most important being how to reproduce.

updated above. thank you so much. :)

**Comment by gaowayne** [comment]
@axboe hello I updated reproduce steps above. 
go to engines folder and run below make command to try to build cpp null.
g++ -O0 -g -shared -rdynamic -fPIC -o cpp_null null.c -DFIO_EXTERNAL_ENGINE

**Comment by axboe** [comment]
See the commit fixing it, you need -include ../config-host.h as well,

**Comment by gaowayne** [comment]
I tried, still have below error. 
```
root@wcp116:/home/intel/wayne/debugfio/fio/engines# g++ -O0 -g -shared -rdynamic -fPIC -o cpp_null null.c -I ../config-host.h -DFIO_EXTERNAL_ENGINE 
cc1plus: warning: ../config-host.h: not a directory
In file included from ../os/os.h:39,
                 from ../thread_options.h:5,
                 from ../fio.h:18,
                 from null.c:21:
../os/os-linux.h:147:19: error: ‘int gettid()’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  147 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from ../fio.h:12,
                 from null.c:21:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘__pid_t gettid()’
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
null.c: In function ‘null_data* null_init(thread_data*)’:
null.c:103:1: warning: control reaches end of non-void function [-Wreturn-type]
  103 | }
      | ^
root@wcp116:/home/intel/wayne/debugfio/fio/engines# 
```

**Comment by axboe** [comment]
-i, not -I. The latter is for a directory. Just copy paste what's in the file, it's correct.

**Comment by gaowayne** [comment]
root@wcp116:/home/intel/wayne/debugfio/fio/engines# g++ -O0 -g -shared -rdynamic -fPIC -o cpp_null null.c  -i ../config-host.h -DFIO_EXTERNAL_ENGINE 
g++: error: unrecognized command line option ‘-i’

**Comment by axboe** [comment]
Argh, it's -include of course, that's what I tested. Pull again.

**Comment by gaowayne** [comment]
child fio process failed to start well. :(
```
root@wcp116:/home/intel/wayne/debugfio/fio# LD_LIBRARY_PATH=./engines ./fio examples/cpp_null.fio
Enter int: 1
fio: time_based requires a runtime/timeout setting
null: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=cpp_null, iodepth=1
fio-3.29-1-g174cf-dirty
Starting 1 process
fio: pid=245113, got signal=11


Run status group 0 (all jobs):
root@wcp116:/home/intel/wayne/debugfio/fio# 
```

**Comment by axboe** [comment]
Works for me:

```
axboe@m1 ~/gi/fio (master)> LD_LIBRARY_PATH=./engines ./fio examples/cpp_null.fio
fio: time_based requires a runtime/timeout setting
null: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=cpp_null, iodepth=1
fio-3.29-142-g1953e1
Starting 1 process
Jobs: 1 (f=1)
null: (groupid=0, jobs=1): err= 0: pid=56931: Sun Mar 20 09:48:57 2022
  read: IOPS=11.3M, BW=43.2GiB/s (46.4GB/s)(100GiB/2315msec)
   bw (  MiB/s): min=41102, max=45450, per=99.62%, avg=44065.14, stdev=2034.85, samples=4
   iops        : min=10522346, max=11635346, avg=11280677.00, stdev=520919.84, samples=4
  cpu          : usr=99.52%, sys=0.00%, ctx=11, majf=0, minf=9
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=26214400,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=43.2GiB/s (46.4GB/s), 43.2GiB/s-43.2GiB/s (46.4GB/s-46.4GB/s), io=100GiB (107GB), run=2315-2315msec
```

Your git sha seems to indicate you're running a modified code base since it's marked dirty. If you are, I'd say it's on you debugging what is going on here. Doing a gdb backtrace from the core dump would be a good start.

**Comment by axboe** [comment]
174cf isn't a valid start of a sha either, so you're running with both unknown commits and changes...

**Comment by gaowayne** [comment]
yeah, I fork to my repo with v3.29, let me check master. :)

**Comment by gaowayne** [comment]
with master code it works for me, should be my manual merge problem. thank you so much man
