### ISSUE TITLE
ubuntu 18.04 fio: engine io_uring not loadable fio: failed to load engine

### ISSUE THREAD

**Issue by qiaobaaa** [axboe/fio#1373]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
when I running:  fio -filename=/dev/nvme0n1 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=io_uring -bs=16k                                          -size=200G -numjobs=10 -runtime=1000 -group_reporting -name=mytest, An error like this will appear ：fio: engine io_uring not loadable fio: failed to load engine，I know how to solve the problem that the libaio engine is not loaded, but I don't know how to solve the loading of io_uring, could you help me? 

**Environment**: Linux version 5.4.0-104-generic (buildd@ubuntu) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #118~18.04.1-Ubuntu

**fio version**: fio-3.1

**Reproduction steps**
root@sivp-NF5180M6:/home/sivp# fio -filename=/dev/nvme0n1 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=io_uring -bs=16k -size=200G -numjobs=10 -runtime=1000 -group_reporting -name=mytest
fio: engine io_uring not loadable
fio: failed to load engine

**Comment by axboe** [comment]
3.1 didn't support io_uring, that version literally predates io_uring by years. You need to upgrade to a newer version.

**Comment by qiaobaaa** [comment]
> 3.1 didn't support io_uring, that version literally predates io_uring by years. You need to upgrade to a newer version.

Thank you for your reply and good luck with your work

**Comment by ZhaoKunn** [comment]
Hi have you solved the problem now?
I also encountered this problem locally.
fio version:fio-3.30

**Comment by axboe** [comment]
There's no problem for us to solve, the distro is using a kernel that is too old.
