### ISSUE TITLE
fio: io_u error on file /dev/md0: Resource temporarily unavailable: read offset=64749568, buflen=16384 fio: pid=74441, err=11/file:io_u.c:1846, func=io_u error, error=Resource temporarily unavailable

### ISSUE THREAD

**Issue by qiaobaaa** [axboe/fio#1374]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
When I use the io_uring engine to test the raid5 volume with the following command, it will report an error, but if I only test a single ssd, the same command will not report an error . md0 is a raid5 array, which consists of three working disks nvme0n1, nvme1n1 and nvme2n1 and a free nvme3n1. 

The raid5 information is as follows: root@sivp-NF5180M6:/home/sivp/fio/test# mdadm --detail /dev/md0/dev/md0:
           Version : 1.2
     Creation Time : Thu Mar 24 12:06:41 2022
        Raid Level : raid5
        Array Size : 3515360256 (3352.51 GiB 3599.73 GB)
     Used Dev Size : 1757680128 (1676.25 GiB 1799.86 GB)
      Raid Devices : 3
     Total Devices : 4
       Persistence : Superblock is persistent

     Intent Bitmap : Internal

       Update Time : Thu Mar 24 15:25:54 2022
             State : active
    Active Devices : 3
   Working Devices : 4
    Failed Devices : 0
     Spare Devices : 1

            Layout : left-symmetric
        Chunk Size : 512K

Consistency Policy : bitmap

              Name : sivp-NF5180M6:0  (local to host sivp-NF5180M6)
              UUID : f6b7dc67:ecb3eb16:dd3b94fc:340f6a36
            Events : 1574

    Number   Major   Minor   RaidDevice State
       0     259        1        0      active sync   /dev/nvme0n1
       1     259        2        1      active sync   /dev/nvme1n1
       4     259        0        2      active sync   /dev/nvme2n1

       3     259        5        -      spare   /dev/nvme5n1

Command: root@sivp-NF5180M6:/home/sivp/fio/test# fio -filename=/dev/md0 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=io_uring -bs=16k -size=1G -numjobs=1 -runtime=1000 -group_reporting -name=mytest
mytest: (g=0): rw=randread, bs=(R) 16.0KiB-16.0KiB, (W) 16.0KiB-16.0KiB, (T) 16.0KiB-16.0KiB, ioengine=io_uring, iodepth=1
fio-3.29-146-gc822
Starting 1 thread
**fio: io_u error on file /dev/md0: Resource temporarily unavailable: read offset=64749568, buflen=16384
fio: pid=74441, err=11/file:io_u.c:1846, func=io_u error, error=Resource temporarily unavailable**

**mytest: (groupid=0, jobs=1): err=11 (file:io_u.c:1846, func=io_u error, error=Resource temporarily unavailable): pid=74441: Thu Mar 24 15:27:09 2022**
  cpu          : usr=0.00%, sys=0.00%, ctx=5, majf=0, minf=2
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):

Disk stats (read/write):
    md0: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=1/8, aggrmerge=15/195, aggrticks=0/4, aggrin_queue=2, aggrutil=12.57%
  nvme0n1: ios=3/10, merge=32/250, ticks=1/1, in_queue=0, util=10.47%
  nvme2n1: ios=0/14, merge=0/281, ticks=0/10, in_queue=4, util=12.57%
  nvme5n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme1n1: ios=3/11, merge=31/250, ticks=1/6, in_queue=4, util=10.47%

**Test a single ssd**: root@sivp-NF5180M6:/home/sivp/fio/test# fio -filename=/dev/nvme0n1 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=io_uring -bs=16k -size=1G -numjobs=1 -runtime=1000 -group_reporting -name=mytest
mytest: (g=0): rw=randread, bs=(R) 16.0KiB-16.0KiB, (W) 16.0KiB-16.0KiB, (T) 16.0KiB-16.0KiB, ioengine=io_uring, iodepth=1
fio-3.29-146-gc822
Starting 1 thread
Jobs: 1 (f=1): [r(1)][100.0%][r=135MiB/s][r=8609 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=83205: Thu Mar 24 15:35:52 2022
  read: IOPS=8106, BW=127MiB/s (133MB/s)(1024MiB/8084msec)
    slat (nsec): min=3401, max=40596, avg=5241.06, stdev=850.75
    clat (usec): min=69, max=306542, avg=116.84, stdev=1346.70
     lat (usec): min=79, max=306548, avg=122.31, stdev=1346.71
    clat percentiles (usec):
     |  1.00th=[   79],  5.00th=[   83], 10.00th=[   85], 20.00th=[   89],
     | 30.00th=[   97], 40.00th=[   98], 50.00th=[   99], 60.00th=[  100],
     | 70.00th=[  101], 80.00th=[  102], 90.00th=[  103], 95.00th=[  104],
     | 99.00th=[  137], 99.50th=[  338], 99.90th=[ 4621], 99.95th=[10028],
     | 99.99th=[10159]
   bw (  KiB/s): min=40992, max=149312, per=100.00%, avg=129802.00, stdev=28610.98, samples=16
   iops        : min= 2562, max= 9332, avg=8112.62, stdev=1788.19, samples=16
  lat (usec)   : 100=60.91%, 250=38.53%, 500=0.13%, 750=0.09%, 1000=0.04%
  lat (msec)   : 2=0.17%, 4=0.02%, 10=0.05%, 20=0.05%, 50=0.01%
  lat (msec)   : 250=0.01%, 500=0.01%
  cpu          : usr=2.55%, sys=9.46%, ctx=65573, majf=0, minf=0
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=65536,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=127MiB/s (133MB/s), 127MiB/s-127MiB/s (133MB/s-133MB/s), io=1024MiB (1074MB), run=8084-8084msec

Disk stats (read/write):
  nvme0n1: ios=63773/509, merge=837/19757, ticks=7297/2120, in_queue=2876, util=96.87%

**Environment**: Linux version 5.4.0-104-generic (buildd@ubuntu) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu118.04)) https://github.com/axboe/fio/pull/11818.04.1-Ubuntu

**fio version**: fio-3.29-146-gc822

**Reproduction steps**:fio -filename=/dev/md0 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=io_uring -bs=16k -size=1G -numjobs=1 -runtime=1000 -group_reporting -name=mytest

**Comment by axboe** [comment]
This is a known issue with 5.4 and io_uring on certain devices, it'll require the application to re-submit the IO. Fio doesn't do that.

I would not recommend running ancient kernels with io_uring.

**Comment by qiaobaaa** [comment]
> This is a known issue with 5.4 and io_uring on certain devices, it'll require the application to re-submit the IO. Fio doesn't do that.
> 
> I would not recommend running ancient kernels with io_uring.

Thank you , which means that upgrading the linux kernel may solve this error, such as linux5.10?
