### ISSUE TITLE
Windows compile and dependencies missing

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1378]
If I install FIO in a Windows 2022 from [Bex' Site](https://bsdio.com/) 3.27, Fio runs just fine. If I compile then Fio will not start because is not finding its dependencies.
If I run the exe I compiled Fio in later versions it runs just fine.
What is the difference in the compile switches 
I am currently using
make clean && make -j
![Fio-Dependencies](https://user-images.githubusercontent.com/50630795/161321184-caef077c-5c88-4d56-a57d-a65641be5e9a.jpg)

**Comment by axboe** [comment]
No idea on windows, maybe ask Ben how he's doing it?

**Comment by vincentkfu** [comment]
Here are the files involved in fio's automated AppVeyor builds:

https://github.com/axboe/fio/blob/master/ci/appveyor-install.sh
https://github.com/axboe/fio/blob/master/.appveyor.yml

Here is a log of a successful build: https://ci.appveyor.com/project/axboe/fio/builds/43077752/job/ljjat55pm3k0nwvq

**Comment by Gt3pccb** [comment]
> Here are the files involved in fio's automated AppVeyor builds:
> 
> https://github.com/axboe/fio/blob/master/ci/appveyor-install.sh https://github.com/axboe/fio/blob/master/.appveyor.yml
> 
> Here is a log of a successful build: https://ci.appveyor.com/project/axboe/fio/builds/43077752/job/ljjat55pm3k0nwvq

thank you!

**Comment by Gt3pccb** [comment]
@axboe the compiles are still failing to compile a FIO.exe that will run. Here are the logs, for MSYS2 and the dependency logs  
[MINGW64.txt](https://github.com/axboe/fio/files/8412168/MINGW64.txt)
[fio-DependecyWalker-.zip](https://github.com/axboe/fio/files/8412186/fio-DependecyWalker-.zip)

**Comment by sitsofe** [comment]
@Gt3pccb What happens if you try and compile and run a simple hello.c file into an exe - do you get the same issue?
