### ISSUE TITLE
cpp null engine does not work for qd=128

### ISSUE THREAD

**Issue by gaowayne** [axboe/fio#1381]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
cpp null engine does not work for qd=128

**Environment**: FedoraOS33

**fio version**: 3.29 master

**Reproduction steps**
1. modify the code like below to increase the qd to 32, also modify the cpp_null.fio add queue depth as 128 so that init code will allocated one 128 entries array
2. run this modified code, it report below error
root@wcp116:/home/intel/wayne/debugfio/old/fio/engines# g++ -O0 -g -ggdb -shared -rdynamic -fPIC -o cpp_null null.c -include ../config-host.h -DFIO_EXTERNAL_ENGINE
root@wcp116:/home/intel/wayne/debugfio/old/fio/engines# cd ..
root@wcp116:/home/intel/wayne/debugfio/old/fio# LD_LIBRARY_PATH=/home/intel/wayne/debugfio/old/fio/engines/ ./fio examples/cpp_null.fio
fio: time_based requires a runtime/timeout setting
null: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=cpp_null, iodepth=128
fio-3.29-157-g6deb
Starting 1 process
Jobs: 1 (f=0): [r(1)][-.-%][eta 00m:00s]]
Enter init in null: fio: io_u.c:1968: io_completed: Assertion `io_u->flags & IO_U_F_FLIGHT' failed.
fio: pid=433165, got signal=6=49KiB/s][r=12 IOPS][eta 02d:08h:53m:19s]

null: (groupid=0, jobs=1): err= 0: pid=433165: Mon Apr  4 15:19:15 2022
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=0
  IO depths    : 1=0.8%, 2=1.6%, 4=3.1%, 8=6.2%, 16=12.4%, 32=24.8%, >=64=51.2%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=50.0%
     issued rwts: total=129,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

3. if run unmodified code, it run well bug qd=1 always even fio specify qd=128
root@wcp116:/home/intel/wayne/debugfio/old/fio# LD_LIBRARY_PATH=/home/intel/wayne/debugfio/old/fio/engines/ ./fio examples/cpp_null.fio
fio: time_based requires a runtime/timeout setting
null: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=cpp_null, iodepth=128
fio-3.29-157-g6deb
Starting 1 process
1obs: 1 (f=0): [r(1)][-.-%][eta 00m:00s]
Jobs: 1 (f=1): [r(1)][100.0%][r=5379MiB/s][r=1377k IOPS][eta 00m:00s]IOPS][eta 02m:59s]
null: (groupid=0, jobs=1): err= 0: pid=433042: Mon Apr  4 15:16:36 2022
  read: IOPS=1376k, BW=5376MiB/s (5637MB/s)(100GiB/19049msec)
   bw (  MiB/s): min= 4946, max= 5403, per=100.00%, avg=5378.39, stdev=72.49, samples=38
   iops        : min=1266315, max=1383364, avg=1376867.08, stdev=18556.97, samples=38
  cpu          : usr=99.98%, sys=0.02%, ctx=26, majf=0, minf=3
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=26214400,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

what is correct way to create the simplest qd=128 engine for testing purpose?

**Comment by gaowayne** [comment]
sorry, let me paste before and after code
before is original code, you can run null engine with qd=128 well, but actually since we return busy when events > 0, the final result is that even fio specify qd=128, but we can only queued qd=1 in the fio please refer above #3. 
IO depths : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
I tried change events>32 try to increase actual QD, but it failed at fio framework code as above #2
 io_completed: Assertion `io_u->flags & IO_U_F_FLIGHT' failed.
before
```
static enum fio_q_status null_queue(struct thread_data *td,
                                    struct null_data *nd, struct io_u *io_u)
{
        fio_ro_check(td, io_u);

        if (td->io_ops->flags & FIO_SYNCIO)
                return FIO_Q_COMPLETED;
        if (nd->events)
                return FIO_Q_BUSY;

        nd->io_us[nd->queued++] = io_u;
        return FIO_Q_QUEUED;
}
```
after change
```
static enum fio_q_status null_queue(struct thread_data *td,
                                    struct null_data *nd, struct io_u *io_u)
{
        fio_ro_check(td, io_u);

        if (td->io_ops->flags & FIO_SYNCIO)
                return FIO_Q_COMPLETED;
        if (nd->events>31)
                return FIO_Q_BUSY;

        nd->io_us[nd->queued++] = io_u;
        return FIO_Q_QUEUED;
}
```
sorry last night forget to paste the code, hope this clarify things

**Comment by gaowayne** [comment]
BTW, man, I solved the debug problem, would you like me to post my method, if others need it? :)

**Comment by axboe** [comment]
I don't know why you're changing the code, just change the iodepth batch submit + complete counts. You're not supposed to change the engines to accomplish this, that would defeat the purpose of having a configurable IO generator.

You're writing past memory, that bug is why the code ends up crashing in odd ways.

**Comment by gaowayne** [comment]
> I don't know why you're changing the code, just change the iodepth batch submit + complete counts. You're not supposed to change the engines to accomplish this, that would defeat the purpose of having a configurable IO generator.
> 
> You're writing past memory, that bug is why the code ends up crashing in odd ways.

thank you so much man. I am trying to understand this and write our own engine plugin to test, could you please specify more detail for "just change the iodepth batch submit + complete counts", or libaio can do this, what its different with null engine, I see posixaio is the same with null engine. could you please shed some light?

**Comment by gaowayne** [comment]
@axboe buddy I solved this by change engine option like below.
	ioengine.name           = "cpp_null";
	ioengine.version        = FIO_IOOPS_VERSION;
	ioengine.queue          = fio_null_queue;
	//ioengine.commit         = fio_null_commit;
	ioengine.getevents      = fio_null_getevents;
	ioengine.event          = fio_null_event;
	ioengine.init           = fio_null_init;
	ioengine.cleanup        = fio_null_cleanup;
	ioengine.open_file      = fio_null_open;
	ioengine.flags          = FIO_DISKLESSIO | FIO_FAKEIO | FIO_ASYNCIO_SYNC_TRIM;
