### ISSUE TITLE
Questions on the IOdepth

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1388]
Hi all,

I have a question regarding to the meaning of the IOdepth, I am trying to understanding the output the FIO with the help of the [link ](https://tobert.github.io/post/2014-04-17-fio-output-explained.html). from the description, the IOdepth means:

Fio has an iodepth setting that controls how many IOs it issues to the OS at any given time. This is entirely application-side, meaning it is not the same thing as the device's IO queue. In this case, iodepth was set to 1 so the IO depth was always 1 100% of the time.

However, when I was running with the following command, the IOdepths always set with 1=100% from the output no matter how I adjusted the value of the iodepth, is there anything wrong?

- IO depth set as 2 in the parameter, output is  1=100%

[root@VM-4-234-centos ~]# fio -name=mytest -filename=/dev/vdb -rw=read -iodepth=2 -size=10G
mytest: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=2
fio-3.12
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=779MiB/s][r=200k IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=4136: Tue Apr 12 11:17:09 2022
  read: IOPS=201k, BW=785MiB/s (823MB/s)(10.0GiB/13050msec)
    clat (nsec): min=1590, max=24010k, avg=2378.22, stdev=23618.31
     lat (usec): min=2, max=24010, avg= 3.01, stdev=23.62
    clat percentiles (nsec):
     |  1.00th=[  1688],  5.00th=[  1736], 10.00th=[  1768], 20.00th=[  1800],
     | 30.00th=[  1848], 40.00th=[  1896], 50.00th=[  1928], 60.00th=[  1960],
     | 70.00th=[  2024], 80.00th=[  2064], 90.00th=[  2128], 95.00th=[  2192],
     | 99.00th=[  2384], 99.50th=[  2512], 99.90th=[  9664], 99.95th=[ 78336],
     | 99.99th=[839680]
   bw (  KiB/s): min=759144, max=814872, per=99.98%, avg=803353.85, stdev=11265.15, samples=26
   iops        : min=189786, max=203718, avg=200838.38, stdev=2816.35, samples=26
  lat (usec)   : 2=66.06%, 4=33.64%, 10=0.21%, 20=0.02%, 50=0.01%
  lat (usec)   : 100=0.01%, 250=0.01%, 750=0.01%, 1000=0.05%
  lat (msec)   : 2=0.01%, 4=0.01%, 50=0.01%
  cpu          : usr=42.14%, sys=57.62%, ctx=45, majf=0, minf=31
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=2621440,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=2

Run status group 0 (all jobs):
   READ: bw=785MiB/s (823MB/s), 785MiB/s-785MiB/s (823MB/s-823MB/s), io=10.0GiB (10.7GB), run=13050-13050msec

Disk stats (read/write):
  vdb: ios=21542/0, merge=0/0, ticks=60475/0, in_queue=60475, util=43.30%

- IO depth set as 3 in the parameter, output is  1=100%
 [root@VM-4-234-centos ~]# fio -name=mytest -filename=/dev/vdb -rw=read -iodepth=3 -size=10G
mytest: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=3
fio-3.12
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=786MiB/s][r=201k IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=4270: Tue Apr 12 11:23:33 2022
  read: IOPS=201k, BW=786MiB/s (825MB/s)(10.0GiB/13020msec)
    clat (nsec): min=1569, max=2118.2k, avg=2366.16, stdev=18439.45
     lat (usec): min=2, max=2119, avg= 2.99, stdev=18.44
    clat percentiles (nsec):
     |  1.00th=[  1688],  5.00th=[  1720], 10.00th=[  1768], 20.00th=[  1800],
     | 30.00th=[  1848], 40.00th=[  1880], 50.00th=[  1928], 60.00th=[  1976],
     | 70.00th=[  2024], 80.00th=[  2064], 90.00th=[  2128], 95.00th=[  2224],
     | 99.00th=[  2480], 99.50th=[  2640], 99.90th=[  9664], 99.95th=[ 26496],
     | 99.99th=[839680]
   bw (  KiB/s): min=794496, max=815392, per=100.00%, avg=805322.73, stdev=4852.05, samples=26
   iops        : min=198624, max=203848, avg=201330.65, stdev=1213.01, samples=26
  lat (usec)   : 2=65.81%, 4=33.91%, 10=0.20%, 20=0.04%, 50=0.01%
  lat (usec)   : 100=0.01%, 250=0.01%, 500=0.01%, 1000=0.05%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=42.97%, sys=56.97%, ctx=24, majf=0, minf=31
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=2621440,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=3

Run status group 0 (all jobs):
   READ: bw=786MiB/s (825MB/s), 786MiB/s-786MiB/s (825MB/s-825MB/s), io=10.0GiB (10.7GB), run=13020-13020msec

Disk stats (read/write):
  vdb: ios=21576/0, merge=0/0, ticks=59795/0, in_queue=59795, util=42.93%

**Comment by bardavid** [comment]
See HOWTO notes on iodepth


*    Note that increasing iodepth beyond 1 will not affect synchronous
ioengines*

**Comment by axboe** [comment]
Yes, you are using a sync engine, the queue depth can only ever be 1 when one task/thread is used.
