### ISSUE TITLE
fio 3.29-154-g06bb windows build does not run

### ISSUE THREAD

**Issue by mgerdts** [axboe/fio#1389]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

fio from fio-3.29-154-g06bb-x64.msi does not run on WS 2022

**Environment**: Windows Sserver 2022

**fio version**: 3.29-154-g06bb-x64

**Reproduction steps**

Download [fio-3.29-154-g06bb-x64.msi](https://bsdio.com/fio/releases/fio-3.29-154-g06bb-x64.msi), install it, then from powershell run `"C:\Program Files\fio\fio.exe"`.  The command exits immediately without even displaying the usage message.  When given valid arguments the same thing happens.

I'm not much of a Windows developer.  When I performed a debug build of something completely unrelated a while back, then copied the .exe to a different Windows machine, it acted the same way.  I suspect that this is a non-release build that depends on a mising dll.  In a private chat with @bcran, I was told that this snapshot build should have been built the same as any other release and this behavior was unexpected.

**Comment by vincentkfu** [comment]
I tried the same installer in WS 2019 and saw the same behavior you did. Consider trying the installers from appveyor. This page has a link to the cygwin fio 3.30 build: https://ci.appveyor.com/project/axboe/fio/builds/43157833/job/nw4vlgaj4sq6p3rx/artifacts. I was able to run a very simple test with this build. The download will only be available for another 15 days.

**Comment by vincentkfu** [comment]
@bcran This appears in the event viewer after running fio.exe from the installer on bsdio.com:

```
Faulting application name: fio.exe, version: 0.0.0.0, time stamp: 0x624c97a8
Faulting module name: fio.exe, version: 0.0.0.0, time stamp: 0x624c97a8
Exception code: 0xc000001d
Fault offset: 0x0000000000094161
Faulting process id: 0x1384
Faulting application start time: 0x01d8558fbe267dbe
Faulting application path: C:\Program Files\fio\fio.exe
Faulting module path: C:\Program Files\fio\fio.exe
Report Id: 4ce86cf7-2434-401a-b869-1795b42fb340
Faulting package full name: 
Faulting package-relative application ID: 
```

Also:
```
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program fio.exe because of this error.

Program: fio.exe
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0
```

and finally:
```
Fault bucket 2305388492363119245, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: fio.exe
P2: 0.0.0.0
P3: 624c97a8
P4: fio.exe
P5: 0.0.0.0
P6: 624c97a8
P7: c000001d
P8: 0000000000094161
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE046.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE067.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE087.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE085.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE096.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_fio.exe_4732ca61918c524448199fcb5aecec682d20_ca6b216a_9919e17f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91d60b81-689a-4a39-9624-042b31802774
Report Status: 268435456
Hashed bucket: 8e20db06d1351d32bffe629e8c93ba8d
Cab Guid: 0
```

**Comment by mgerdts** [comment]
This is no longer an issue now that Windows builds are available at https://github.com/axboe/fio/releases.
