### ISSUE TITLE
Adding eta or aux-path or output-format to a .fio answer file causes checks to fail

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1395]
I have these params in a .fio file that I want to pass to FIO
FIO version fio-3.29 or 3.29-154-g06bb running in Windows
[global]
 

bs=64K
cpus_allowed_policy=split 
description=NoDescription
direct=1 
directory=c\:\\1:
fallocate=truncate 
filesize=1MB
group_reporting=1 
iodepth=32
ioengine=windowsaio 
name=NoName
no_completion_thread=1
nrfiles=1
output-format=json+ 
overwrite=0 
ramp_time=5 
refill_buffers 
runtime=30 
sync=sync 
thread 
time_based 
unlink=1
aux-path=c\:\\FIONoName 
 
[Job-NoName-1]
clocksource=cpu

**fio  .\TestNbr1-randwrite-nJbbs1-nFiles1-QD32-IOSizebs=64K.fio**
**Bad option <eta=never>
Did you mean ba?
Bad option <output-format=json+>
Bad option <aux-path="c\:\\FIONoName">(1)
fio: job global dropped**

(1) aux-path="c\:\\FIONoName" or aux-path=c\:\\FIONoName or aux-path='c\:\\FIONoName' all fail the same however they all work as a line argument

**fio --eta=never --aux-path="c\:\\FIONoName" --output-format=json+ .\TestNbr1-randwrite-nJbbs1-nFiles1-QD32-IOSizebs=64K.fio**
Runs just fine.

**Comment by axboe** [comment]
Some options, like the two listed, are global options and cannot be used in a job file. These are listed under "command line options" in the documentation.
