### ISSUE TITLE
Invalid comparison function

### ISSUE THREAD

**Issue by yugr** [axboe/fio#140]
bs_cmp (from options.c) is passed to qsort to compare bssplit structures. But it does not satisfy qsort symmetry requirement i.e.
  bs_cmp(a, b) != - bs_cmp(b, a)
This triggers UB at runtime and may cause qsort to fail to sort the array.

The fix should be as simple as replacing the current code with
```
  return (int)bsp1->perc - (int)->bsp2->perc;
```

**Comment by yugr** [comment]
The problem was found when running Phoronix under SortChecker tool (https://github.com/yugr/sortcheck).

**Comment by axboe** [comment]
Indeed, should return int difference. Fix committed.
