### ISSUE TITLE
Opposite IO performance for numa setting

### ISSUE THREAD

**Issue by gang2015** [axboe/fio#141]
I setup a read test on a server with two numa nodes. fio runs random or sequential read with numa_cpu_node set 0 or 1 seperately.

config example:
[global]
overwrite=1
direct=1
ioengine=libaio
filename=/dev/nvme1n1
blocksize=4k
iodepth=1
time_based=1
runtime=30m
[read]
numa_cpu_nodes=1
numa_mem_policy=bind:1
rw=read

My nvme drive is on PCIe with numa node =1. So I expect that there is be better performance for numa_cpu_nodes=1. During the test, I do see that fio process was running on the correct cpu core with numa bind. However, I get the opposite performance result: numa=1 always has much lower IOPS and higher latency. CPU load also shows higher on higher bandwidth. I can't explain the result. Is there anyone ran similar test before? 

<pre>
                         Bandwidth (B)        IOPS          Latency 99.99%       Latency mean   CPU_load
Seq read, bs=4k              189M              47.2K                  64              18            24%
iodepth=1,
numa_cpu_nodes=0

Seq read, bs=4k              93M                23.8K                 85              37             15%
iodepth=1, 
numa_cpu_nodes=1
</pre>

**Comment by axboe** [comment]
Are you sure the device is on node1? Even with that, though, the performance discrepancy is much bigger than I would think. I'd try simple CPU binding first:

export NODE0=$(cat /sys/devices/system/node/node0/cpulist)
export NODE1=$(cat /sys/devices/system/node/node1/cpulist)

and then use cpus_allowed=${NODE0} to just run on node0, and similarly for node1. Check that the kernel thinks the device is on the right node as well. Let's say your nvme pci device is 0a:00.0, do

cat /sys/bus/pci/devices/0000\:0a\:00.0/numa_node

to verify that.

**Comment by gang2015** [comment]
I confirmed the device is on node 1. 
% cat /sys/block/nvme1n1/device/numa_node 
1
And the core list for nodes:
% cat /sys/devices/system/node/node0/cpulist 
0-21,44-65
% cat /sys/devices/system/node/node1/cpulist
22-43,66-87


With the config changed to cpus_allowed = ${NODE0}
I still get the similar results, and they are always consistent. It can't be explained by numa setting. Do you have similar test run on other servers?

<pre>
                      bandwidth    IOPS      latency mean
cpus_allowed={NODE0}     140M         35K        25
cpus_allowed={NODE1}     80M           20K        46

</pre>

**Comment by axboe** [comment]
Check the irq affinity settings. Sounds like they are wrong. Also be weary of irqbalance subsequently screwing them up.

**Comment by gang2015** [comment]
The system default irq setting shows the nvme1 irq is associated to numa node 1 cpus.

<pre>
           CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       CPU8       CPU9       CPU10      CPU11      CPU12      CPU13      CPU14      CPU15      CPU16      CPU17      CPU18      CPU19      CPU20      CPU21      CPU22      CPU23      CPU24      CPU25      CPU26      CPU27      CPU28      CPU29      CPU30      CPU31      CPU32      CPU33      CPU34      CPU35      CPU36      CPU37      CPU38      CPU39      CPU40      CPU41      CPU42      CPU43      CPU44      CPU45      CPU46      CPU47      CPU48      CPU49      CPU50      CPU51      CPU52      CPU53      CPU54      CPU55      CPU56      CPU57      CPU58      CPU59      CPU60      CPU61      CPU62      CPU63      CPU64      CPU65      CPU66      CPU67      CPU68      CPU69      CPU70      CPU71      CPU72      CPU73      CPU74      CPU75      CPU76      CPU77      CPU78      CPU79      CPU80      CPU81      CPU82      CPU83      CPU84      CPU85      CPU86      CPU87      
 192:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0         44          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  728201258          0          0          0          0          0          0          0          0  IR-PCI-MSI-edge      nvme1q0, nvme1q1
 193:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0         19          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  237504571          0          0          0          0          0          0          0  IR-PCI-MSI-edge      nvme1q2
 194:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          9          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  165590910          0          0          0          0          0          0  IR-PCI-MSI-edge      nvme1q3
 195:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          4          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  240585998          0          0          0          0          0  IR-PCI-MSI-edge      nvme1q4
 196:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  195690567          0          0          0          0  IR-PCI-MSI-edge      nvme1q5
 197:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          1          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  105732509          0          0          0  IR-PCI-MSI-edge      nvme1q6
 198:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0         76          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  216834466          0          0  IR-PCI-MSI-edge      nvme1q7
 199:          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0         46          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  144862452          0  IR-PCI-MSI-edge      nvme1q8
 
</pre>

I am running the profiling with irqbalance disabled. Will report the results later.

**Comment by gang2015** [comment]
Even disable irqbalance service, still got the same performance as before.
Do you have more details about irq afinity settings?

**Comment by franciozzy** [comment]
This issue is really old, but I thought it was worth commenting on it. There are a few things worth noting here:

When fio (using libaio as in your example) runs at about 100% of cpu time, it is spending all of its time between io_submit()s and io_getevent()s. Think of fio telling the kernel "submit these 64 requests", but by the time it finishes doing that, some of those requests are completed. Then it calls io_getevent() and collect those completed requests. It then immediately goes back to io_submit() and submits more requests, attempting to sustain those 64 outstanding requests. It is therefore constantly busy. That often happens when your io device is really fast (eg. most NVMe drives), since CPUs struggle to keep up with it.

Now look at the interrupt distribution you pasted above. I bet that if you match those irqs to the submitting cpus from /sys/block/nvme1n1/mq, you'll find that CPU83 is associated with nvme1q5 and is also set in the mask for irq 196. This means that when an IO completes, it raises an interrupt for cpu83 which is also where your fio thread is running. The irq handling therefore takes time away from your fio task which is 100% busy submitting requests and fetching completions. It therefore slows it down.

There are many implications of fiddling with task setting, interrupt distribution and numa pinning for memory allocation. Depending on your workload, turbo settings, what else is happening on your system (even if it seems relatively idle), things may go faster or slower. There isn't a magical answer to make everything faster, otherwise that would be the default for everyone.

The best recommendation I can give for anyone running into these issues is to run a more comprehensive set of workloads and analyse all the results combined. Plot graphs with iodepth ranging from 1 to 128 using 4k requests. Try random and sequential, one at a time. Then repeat varying from 1 thread to 128 threads, each having iodepth set to 1. Collect the cpu utilisation of your whole system for all of that. Mess about with task setting and interrupt affinity and repeat. Only then you'll be able to figure out why your results look like they do on your particular setup.

**Comment by gpkulkarni** [comment]
any more findings/conclusions on this issue?

**Comment by sitsofe** [comment]
@gpkulkarni Well @franciozzy gave an extremely detailed theory (along with a test methodology) to explain the original behaviour. Is it the case that you are finding your fio threads are maxing out the CPU their running on and if so then wouldn't @franciozzy's theory fit your case too? Given the original reporter (@gang2015) disappeared I don't know that there is any other finding or conclusion that can be reached at this stage.

@axboe Perhaps this issue is probably better off closed at this stage?

**Comment by axboe** [comment]
Agree

**Comment by franciozzy** [comment]
@microyahoo specifically the elrepo (I want to guess kernel-lt) rebuild, so something you probably want to raise at https://elrepo.org/bugs/

**Comment by microyahoo** [comment]
hi @axboe, thanks for your quick reponse, yes, it's a kernel question.
@franciozzy, thanks, I have raised an issue to follow up. https://elrepo.org/bugs/view.php?id=1509
