### ISSUE TITLE
 fatal error: nfsc/libnfs.h: No such file or directory

### ISSUE THREAD

**Issue by SPURSGO** [axboe/fio#1412]
fatal error: nfsc/libnfs.h: No such file or directory

    CC io_u_queue.o
    CC filelock.o
    CC rate-submit.o
    CC workqueue.o
    CC optgroup.o
    CC steadystate.o
    CC helper_thread.o
    CC zone-dist.o
    CC dedupe.o
    CC zbd.o
    CC engines/windowsaio.o
    CC engines/nfs.o
    CC oslib/asprintf.o
engines/nfs.c:3:10: fatal error: nfsc/libnfs.h: No such file or directory
    3 | #include <nfsc/libnfs.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:521: engines/nfs.o] Error 1
make: *** Waiting for unfinished jobs....

in my cygwin, <nfsc/libnfs.h> file path is : /cygwin64\usr\include

**Comment by axboe** [comment]
Not sure you filed a duplicate since you knew about the other one?
