### ISSUE TITLE
What am I doing wrong with directory and file allocation on a per job basis in Windows. 

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1421]
Hello I am having troubles getting FIO 3.30 to write to different directories and files.
For example I want 10 jobs writing to 10 different directories, 1 file per directory. 

The following specs result on all jobs writing their 10 files to D\:\\F\1 instead of one file per dir. The same is true if I add the directory to each job and remove the filename_format

10 jobs use 10 different directories 1 file per directory 

blocksize_range=4k-64K
continue_on_error=none 
cpus_allowed_policy=split 
create_on_open=0 
description=Cache
direct=1 
directory=D\:\\F\1:D\:\\F\2:D\:\\F\3:D\:\\F\4:D\:\\F\5:D\:\\F\6:D\:\\F\7:D\:\\F\8:D\:\\F\9:D\:\\F\10:
disable_clat=1 
disable_slat=1  
iomem=mmap
do_verify=0 
exitall_on_error 
fallocate=truncate 
group_reporting=1 
io_limit=500gb 
iodepth=16
ioengine=windowsaio 
name=Test1
no_completion_thread=1
numjobs=10
nrfiles=1
offset=0 
overwrite=0 
ramp_time=20 
readwrite=write
runtime=30 
scramble_buffers=1  
size=600gb 
sync=sync 
thinktime=0 
thread 
time_based 
unlink=1 
 
[Job-1]
clocksource=cpu
filename_format=J1.$jobnum.$filenum
 
 
[Job-2]
clocksource=cpu
filename_format=J2.$jobnum.$filenum
 
 
[Job-3]
clocksource=cpu
filename_format=J3.$jobnum.$filenum
 
 
[Job-4]
clocksource=cpu
filename_format=J4.$jobnum.$filenum
 
 
[Job-5]
clocksource=cpu
filename_format=J5.$jobnum.$filenum
 
 
[Job-6]
clocksource=cpu
filename_format=J6.$jobnum.$filenum
 
 
[Job-7]
clocksource=cpu
filename_format=J7.$jobnum.$filenum
 
 
[Job-8]
clocksource=cpu
filename_format=J8.$jobnum.$filenum
 
 
[Job-9]
clocksource=cpu
filename_format=J9.$jobnum.$filenum
 
 
[Job-10]
clocksource=cpu
filename_format=J10.$jobnum.$filenum

thank you

**Comment by vincentkfu** [comment]
I haven't looked at any of the code or done any actual testing, but according to the documentation you need `numjobs={something}` when you specify multiple directories with the `directory` option.

https://fio.readthedocs.io/en/latest/fio_doc.html#target-file-device

**Comment by Gt3pccb** [comment]
Yes, I forgot to add it to the past, but even with the numbjobs= does not work..

**Comment by Gt3pccb** [comment]
Also in the past this 
fio .\nJbs2-nFls10-nDrs10.fio --aux-path="c:\fioAuxPath\" --output-format=json+ --output="1.json" 
resulted in the Json 1.json being written to C:\fioAuxPath\
But since 3.27 it does not work.
I think that at one point something broke in the parsing and maybe assignment logic?

--aux-path=path

    Use the directory specified by path for generated state files instead of the current working directory.

thank you

**Comment by vincentkfu** [comment]
My reading of the documentation is that if you have

```
--directory=E:\1:E:\2:E:\3:E:\4:E:\5:E:\6::E:\7:E:\8:E:\9:E:\10
--numjobs=10
--nrfiles=100
```

job 1 will use E:\1 for its 100 files, job 2 with use E:\2 for its 100 files, etc

For the `aux-path` problem please open a separate issue
