### ISSUE TITLE
err=95/file:filesetup.c:805

### ISSUE THREAD

**Issue by corniger** [axboe/fio#1423]
Hello
I am mounting remote filesystem over Ethernet network. It is hosted on a SMB protocol server (Tuxera).
My PC is debian derived OS. I can touch a file in a remote directory, this appears to work ok.
I can also successfully run fio for a read test in the remote directory.
But when I attempt write test, this error occurs,
alexander@ms7816:/run/user/1000/gvfs/smb-share:server=7879,share=500gbntfs/tr/qBittorrent/STREAM$ touch temp.file
alexander@ms7816:/run/user/1000/gvfs/smb-share:server=7879,share=500gbntfs/tr/qBittorrent/STREAM$ ls
00000.m2ts  Bonnie  Bonnie.166667  temp.file
alexander@ms7816:/run/user/1000/gvfs/smb-share:server=7879,share=500gbntfs/tr/qBittorrent/STREAM$fio --name TEST --eta-newline=5s --filename=temp.file --rw=randrw --size=2g --io_size=10g --blocksize=4k --ioengine=libaio --fsync=1 --iodepth=1 --direct=1 --numjobs=1 --runtime=60 --group_reporting
TEST: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.30
Starting 1 process
fio: pid=323398, err=95/file:filesetup.c:805, func=open(temp.file), error=Operation not supported

Please help, how to derive what's causing it? Exactly what is that operation that is not supported?

**Comment by vincentkfu** [comment]
It looks like there was an error opening the file. Here is the code that printed the error message: https://github.com/axboe/fio/blob/master/filesetup.c#L805

Try running without `direct=1`. If you are using an iodepth of 1 you might as well use the `psync` ioengine.

**Comment by vincentkfu** [comment]
Closed due to lack of response from reporter.
