### ISSUE TITLE
fio: command payload too large for "rw" operation 

### ISSUE THREAD

**Issue by ekuric** [axboe/fio#143]
I am using fio-2.5-4-gab91, where I am running read,write, rw for 4k,64k,1024k 
read/write works ok as well as rw for 4k and 64k. However for rw and 1024k it stops as showed below  
is this known problem. I am using latest git clone of axboe/fio

fio: command payload too large: 1200
fio: server bad crc on command (got 0, wanted f999)
fio: command payload too large: 1272
fio: server bad crc on command (got 0, wanted c004)
fio: command payload too large: 1272
fio: server bad crc on command (got 0, wanted dabf)
fio: command payload too large: 1200
fio: server bad crc on command (got 0, wanted ec54)

**Comment by axboe** [comment]
Not a known problem until now. Can you share the job file that you ran? I'll get this fixed up when I can reproduce it, that's the fastest way.

**Comment by ekuric** [comment]
thanks @axboe.
this one is from randrw, only rw and randrw has this issue.  read/write, randread/randwrite are fine, I am writing to ceph rbd ( rados block device ),not sure could this be reason for issue but all except rw/randrw operations is fine. 

fio.job
[global]
bs=1024k
ioengine=libaio
iodepth=32
direct=1
sync=0
time_based=1
runtime=30
clocksource=gettimeofday
ramp_time=5
[job1]
rw=randrw
size=2048M
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
log_avg_msec=1000
directory=/mnt/ceph
numjobs=35

**Comment by axboe** [comment]
Thanks, can you try current -git? Looks like there's a bug in breaking down vectored entries into chunks, I've just disabled the length checking for now.

**Comment by ekuric** [comment]
sure, will do that and feedback result, thank you

**Comment by axboe** [comment]
I made a real fix as well now, so when you do re-test, include the git head as well of what you ran and tested. Thanks!

**Comment by esramirez** [comment]
@ekuric please, let me know also if the fix worked for you. 

Thanks

**Comment by ekuric** [comment]
@axboe @esramirez yes, it works fine with latest bits, rw operations now do not fail with issue stated in subject of this report. thank you
