### ISSUE TITLE
fio 128k read perfomance  drops due to cpuclocktest  of another fio process

### ISSUE THREAD

**Issue by parrot18** [axboe/fio#1430]
**Please acknowledge the following before creating a ticket**

- [ ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

**Description of the bug:**

I have 2*4T NVMe SSD on my X86 server with purley CPU
Run 2 fio processes successively，
cmd is "fio -ioengine=libaio -direct=1 -iodepth=128 -time_based -bs=128k -runtime=1200s -rw=read -filename=/dev/nvme0n$x -numjobs=1 -thread -group_reporting -norandommap -name=read"
when fio1 begins to send read cmd，BW is about 3GB/s （match a Gen 3.0 NVMe SSD's sequential reading spec）
start fio2，and fio2 will perform  fio_monotonic_clocktest，then BW of fio1 starts to drop and  stabilizes at 1.7GB/s，and doesn't go back to where it was ，even if the fio2 's clocktest is over.

I've tried to locate the problem and converge the root of the problem to this commit :
commit a250edd0678ac6aef34bfbd01423a7b87a1d5f8d
Author: Jens Axboe [[axboe@kernel.dk](mailto:axboe@kernel.dk)](mailto:axboe@kernel.dk)
Date:   Tue Oct 17 12:11:44 2017 -0600

  gettime: improve cpu clock test
  We're missing a synchronization before reading and comparing
  with the current *t->seq in the loop. Rewrite the loop to
  use compare-and-exchange for the increment, and ensure that
  we have the proper synchronization inserted. This should both
  be faster and more reliable.
  Signed-off-by: Jens Axboe [[axboe@kernel.dk](mailto:axboe@kernel.dk)](mailto:axboe@kernel.dk)
I tried to hard code the 
- sync_sync="yes"
- cmp_swap="yes"
to "no" in configure file, the problem is sloved.
but I don't understand the root cause of this problem，does anyone know where the problem is？

some other clues：
1、fio1 's 128k write (about 2.7GB/s) also drops when fio2 running  clocktest, but the BW of fio1 will recover to its original state when fio2 's clocktest ends. so does the 4k randrand (about 645k IOPS) test.
2、Centos 8 with 4.18 kernel with fio-3.7, has no such problem, performance will drop and will recover when the cpuclocktest ends.
**Environment**: 
Centos7U6 kernel：3.10.0-1160.42.2.el7.x86_64 
**fio version**: 
fio-3.7
**Reproduction steps**

1、fio-3.7  Centos7U6 kernel：3.10.0-1160.42.2.el7.x86_64  NVMe SSD disk *2
2、fio  -name=fio-pre -rw=write -direct=1 -ioengine=libaio -numjobs=1 -group_reporting -size=100% -loop=2 -filename=/dev/nvme0n$x -bs=128k -iodepth=128 -thread
3、run fio 1 128K sequential read case，wait for the bandwidth to stabilize to 3G
fio -ioengine=libaio -direct=1 -iodepth=128 -time_based -bs=128k -runtime=1200s -rw=read -filename=/dev/nvme0n1 -numjobs=1 -thread -group_reporting -norandommap -name=read
4、open another session， run fio 2
fio -ioengine=libaio -direct=1 -iodepth=128 -time_based -bs=128k -runtime=1200s -rw=read -filename=/dev/nvme0n2 -numjobs=1 -thread -group_reporting -norandommap -name=read
5、It can be observed fio1 's bandwidth drops to 1.7GB/s and never recover

**Comment by parrot18** [comment]
another reporedutions step：
1、fio-3.7 Centos7U6 kernel：3.10.0-1160.42.2.el7.x86_64 NVMe SSD disk *2
2、fio -name=fio-pre -rw=write -direct=1 -ioengine=libaio -numjobs=1 -group_reporting -size=100% -loop=2 -filename=/dev/nvme0n$x -bs=128k -iodepth=128 -thread
3、 run fio 1 128K sequential read case，wait for the bandwidth to stabilize to 3G
fio -ioengine=libaio -direct=1 -iodepth=128 -time_based -bs=128k -runtime=1200s -rw=read -filename=/dev/nvme0n1 -numjobs=1 -thread -group_reporting -norandommap -name=read
4、run fio --cpuclock-test
5、It can be observed fio1 's bandwidth drops to 1.7GB/s and never recover
if step 3 is 128k sequential write， it will be like
normal write BW：
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/10443956/180371123-e0805b1d-3041-4224-832a-e243a94c4546.png">
running  fio --cpuclock-test
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/10443956/180371168-85f726a7-a048-478c-93eb-0059f1c905c8.png">
cpuclock test end
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/10443956/180371216-6c0a971b-34e0-4b77-95b4-d890dee336f0.png">

**Comment by vincentkfu** [comment]
If this works with CentOS 8/kernel 4.18 but is broken with CentOS 7/kernel 3.10 then it sounds more like a kernel issue rather than a fio issue.

**Comment by parrot18** [comment]
it seems not to be related with kernel
I update kernel to 4.18 under centos7.6 
the performance drop still happens

**Comment by parrot18** [comment]
it's so weird that only fio's cpuclock test cause the fio1's performance drop.
when I run stress-ng with memory barrier benchmark, fio1's BW won't  drop.
