### ISSUE TITLE
zbd random write example mentions libaio but actually uses psync

### ISSUE THREAD

**Issue by ThunderEX** [axboe/fio#1433]
https://github.com/axboe/fio/blob/7006d70c7c8b9a39cf3dfdd839d1975295c10527/examples/zbd-rand-write.fio#L20
In this example, the comment in the first line mentions usage of libaio, but in last line, it's using psync.
I think one of them should be wrong. Could you please correct this example?

**Comment by vincentkfu** [comment]
Thanks for reporting!
