### ISSUE TITLE
FIO causes system auto reboot

### ISSUE THREAD

**Issue by jackylee0908** [axboe/fio#1434]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

I met a problem when executing FIO stress test on a RAID0 which built from 6x SSDs thru mdadm under Yocto OS, below is the information:

1. 6x PCIe NVMe SSD are the same vendor and model which is with 1.02TB automotive grade.
2. FIO parameter used for the test: fio --filename=/dev/md127 --direct=1 --rw=randrw --bs=64k --ioengine=libaio --iodepth=64 --runtime=43200 --numjobs=16 --time_based --group_reporting --name=randomrw --eta-newline=1
3. The system auto restart after 30 minutes run
4. The question is that I'd want to know why it would cause the system auto restart randomly, is that a software issue or software limitation, or a hardware issue? Would you suggest on how to isolate the issue?

I found that:

1. Both RAID0 and non-RAID mode are failed with same FIO parameter(only the --filename is with different target).
2. When issue occurs, re-run the test by same FIO parameter will encounter the issue again immediately, except that you format the SSD, but will fail again after ~30mins run.
3. Did not enounter this issue with given --size parameter.
4. When issue occurs, the SSD encounters over current issue. (accept: under 2A, over current: 5.5A)

**Environment**: 
Yocto

**fio version**: 3.17-dirty

**Reproduction steps**
As above issue description

**Comment by axboe** [comment]
This could be a kernel bug or it could be a hardware issue. It's certainly not a fio issue.
