### ISSUE TITLE
Fio: io_u error when running fio on a 'LBA data size + Metadata size' ssd drive under spdk ioengine.

### ISSUE THREAD

**Issue by ningqingqing** [axboe/fio#1435]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
I want to run fio on a  'LBA data size(4KB) + Metadata size(16B)' ssd drive under spdk ioengine, but after I set bs to 4112, I always see Fio: io_u error:  Input/output error: write offset=8224, buflen=4112.

**Environment**: --linux, centos system

**fio version**: fio-3.30-76-g9c1c

**Reproduction steps**
       1: I downloaded spdk ioengine
       2: Run setup.sh file in scripts folder. unbind nvme driver to vfio
       3: Run fio test, then fio error occurred 
       FIO parameter: 
       [global]
       ioengine=spdk
       iodepth=128
       numjobs=1
       group_reporting=1
       direct=1
       time_based=1
       log_avg_msec=100
       [seq-read]
       thread=1
       rw=read
       stonewall
       runtime=10

**Comment by axboe** [comment]
spdk is raw IO, you can't run that with unaligned block sizes.

**Comment by ningqingqing** [comment]
> spdk is raw IO, you can't run that with unaligned block sizes.

Hi, axboe, do you know which ioengine can be used to run unaligned block sizes?

**Comment by axboe** [comment]
You can't do regular IO like that. You could use the io_uring_cmd engine for nvme passthrough, if you're using nvme and a 5.19 kernel. Then you could set it up to use DI/PI for the extra meta data for writes.

**Comment by ningqingqing** [comment]
> You can't do regular IO like that. You could use the io_uring_cmd engine for nvme passthrough, if you're using nvme and a 5.19 kernel. Then you could set it up to use DI/PI for the extra meta data for writes.

I am using nvme, but kernel version is 5.12, is it possible to setup io_using_cmd on 5.12 kernel, or this can only be available on 5.19 or above version?

**Comment by axboe** [comment]
It's only available from 5.19 onwards.

**Comment by ningqingqing** [comment]
> It's only available from 5.19 onwards.

I see, thank you so much!
