### ISSUE TITLE
FIO hangs when executing following profile

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1436]
Hi,

I met an issue when running FIO with following profile, it is supposed to stop at 600S, but it hangs for one day, do u you know how to check the reason for the IO hang?

`[global]
            ioengine=libaio
            exitall_on_error=1
            invalidate=1
            direct=1
            runtime=600
            allow_file_create=0
            refill_buffers=1
            group_reporting
            iodepth_batch_submit=2
            iodepth=16
[vdn-10G-comp57%]
filename=/dev/vdn
size=10G
bsrange=8k-256k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=57%
buffer_pattern=0x3aec975b
[vdn-10G-comp15%]
stonewall
filename=/dev/vdn
size=10G
bsrange=4k-128k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=15%
buffer_pattern=0xbe485319
buffer_compress_chunk=2k
`

Checked with iostat and found the IO should actually stopped

Every 1.0s: iostat                      VM-0-39-centos: Mon Aug  8 11:51:56 2022

Linux 5.4.119-19-0009.1 (VM-0-39-centos)        08/08/2022      _x86_64_
(48 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.06    0.00    0.08    0.04    0.00   99.82

Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
vda               0.81         1.60         7.25     359458    1630694
scd0              0.00         0.00         0.00        538          0
vdb               0.00         0.00         0.00       1048          0
vdc               0.00         0.00         0.00       1048          0
vdd               0.00         0.00         0.00       1048          0
vde               0.00         0.00         0.00       1048          0
vdl              10.08        39.83        23.30    8960524    5240425
vdn               0.51         0.01        46.61       2096   10485416
vdo              12.47        39.73        39.67    8936551    8922798
vdq               3.04        93.26        93.23   20977800   20971520

**Comment by axboe** [comment]
Please read the reporting bugs file - what fio version are you using?
