### ISSUE TITLE
The flag '--output-format=json' prevents realtime eta stats from being printed

### ISSUE THREAD

**Issue by ubehera** [axboe/fio#144]
This is true even with '--eta=always' flag set.

**Comment by sitsofe** [comment]
@ubehera ETA only appears with normal output but you can specify multiple output formats as mentioned in the [fio HOWTO entry for `--output-format`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-output-format) e.g.:

```
./fio --ioengine=null --size=100G --name=normaljson --output-format=normal,json
```

You'll have to cope with the fact that the normal/ETA and json can overlap each other on the same line but that's a different issue...

If this answers the initial question/request could you close this issue? Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
