### ISSUE TITLE
error: failed to setup shm segment

### ISSUE THREAD

**Issue by GOGOYAO** [axboe/fio#1441]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

I run ` fio --name=write_iops_test   --filename=./fio.test --filesize=250G  --time_based --ramp_time=2s --runtime=1m   --direct=1 --verify=0 --randrepeat=0 --bs=4K --iodepth=256 --rw=randwrite` and get error `failed to setup shm segment`.
**Environment**: 
My operating system is CentOS Linux release 7.4.1708 (Core).
My shm size is as follows
![image](https://user-images.githubusercontent.com/18675094/184322105-a51a3d03-6cef-433a-ad86-c5d5cc50d2ba.png)

**fio version**: 
fio-3.7
**Reproduction steps**

**Comment by axboe** [comment]
If you use ```---max-jobs=8``` for example, it'll probably work. Newer fio releases will do this automatically, consider upgrading from 3.7 which is pretty ancient.

**Comment by erikschul** [comment]
**For MacOS users:**

I solved this temporarily using
```
sudo sysctl -w kern.sysv.shmall=65536
sudo sysctl -w kern.sysv.shmmax=16777216
```
