### ISSUE TITLE
fio doesn't exit on an I/O error with `--continue_on_error=none`

### ISSUE THREAD

**Issue by Hi-Angel** [axboe/fio#1443]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

Documentation says *(in short)*: `continue_on_error=none — Exit on any I/O or verify errors.` However, if a disk returns an IO error, FIO silently ignores it even if `--continue_on_error=none` is passed.

For steps-to-reproduce here I use a dmsetup's `error` device, and I confirmed it actually returns IO errors by using a `cat /dev/mapper/test > /dev/null` and seeing cat would fail with an IO error.

**Environment**: Ubuntu 18.04

**fio version**: latest master `fio-3.31-11-g4deb` and an older `fio-3.1`.

**Reproduction steps**

1. Create a ram disk as `sudo modprobe rd rd_nr=1 rd_size=$(( 100 * 1024 ))`
2. Create a virtual device that would sporadically return errors as `sudo dmsetup create test --table '0 123 error /dev/ram0 0 10 2'`
3. Run fio as `fio --name=temp-fio --rw=randwrite --rwmixwrite=30 --filename=/dev/mapper/test --time_based --runtime=1h --exitall_on_error --continue_on_error=none`
4. Run `journalctl -f` and wait for a message like `kernel: Buffer I/O error on dev dm-281, logical block 70, lost async page write` to appear

**Expected**

`fio` would exit immediately upon seeing the error

**Actual**

`fio` would continue running until it's interrupted or the time runs out.

**Comment by axboe** [comment]
The error might not be directly visible to fio, if it's an async buffered write. The write most likely completed just fine in terms of fio, in that the write(2) (or similar) system call returned the full size of the write and not an error. You'd only see the error when you later fsync'ed the file descriptor. So I don't think there's much fio could do here. If you set ```---direct=1``` as an option it'd likely look different.

continue_on_error=none is also the default behavior. fio will always exit on any IO error, unless it's explicitly told not to.

**Comment by Hi-Angel** [comment]
Oh, this is cool! I confirm that `--direct=1` works. Yeah, your explanation makes sense, thank you!

I'll send a clarification to the documentation section shortly then
