### ISSUE TITLE
filerange option

### ISSUE THREAD

**Issue by nevubm** [axboe/fio#1449]
Is there a way to use only a certain range in a file? If not could this be added as a feature?

For example, this could be useful for testing specific regions of a spinning hard drive, or reading compressible vs random regions in one file to test compression throughput.

**Comment by vincentkfu** [comment]
See the `size` option and there is also some related discussion in the entry for the `io_size` option.

https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size
