### ISSUE TITLE
libaio and direct=1 error with panfs

### ISSUE THREAD

**Issue by Danielee4** [axboe/fio#145]
Hi, 
    I tried a test with panfs, the config file contains the following options:

ioengine=libaio
direct=1

and every time the fio test fails with the error:

hostname=node02, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-2.2.10, flags=1
<node02> fio: io_u error on file /panfs/pasto/home//192.168.0.2.testfile.0.1.scratch: Invalid argument: read offset=547143680, buflen=4096
<node02> fio: io_u error on file /panfs/pasto/home//192.168.0.2.testfile.0.1.scratch: Invalid argument: read offset=390074368, buflen=4096
<node02> fio: pid=63586, err=22/file:io_u.c:1589, func=io_u error, error=Invalid argument
<node02> fio: io_u error on file /panfs/pasto/home//192.168.0.2.testfile.0.0.scratch: Invalid argument: read offset=129519616, buflen=4096
<node02> fio: io_u error on file /panfs/pasto/home//192.168.0.2.testfile.0.0.scratch: Invalid argument: read offset=1589760000, buflen=4096
<node02> fio: pid=63585, err=22/file:io_u.c:1589, func=io_u error, error=Invalid argument

The same test in the local filesystem works fine. 
Any suggestions or idea to solve this issue?

Daniele

**Comment by axboe** [comment]
I don't know what panfs is, but from the error message, it doesn't look like it supports O_DIRECT. If that's the case, you can't use direct=1/buffered=0.

**Comment by Danielee4** [comment]
The strange is that the test with the options:

ioengine=posixaio
direct=1

works fine, could be a filesystem  posix/non posix issues ?

**Comment by axboe** [comment]
Then it's because panfs doesn't support the aio ops. If posixaio and O_DIRECT works, then direct IO is supported. But since it fails with libaio, then the file system doesn't support the async IO methods.

**Comment by dirtyharrycallahan** [comment]
FWIW: Panfs is the file system used with storage products from Panasas. It is a scale-out NAS.
