### ISSUE TITLE
fio is not running in IPv6 network

### ISSUE THREAD

**Issue by bose-abhishek** [axboe/fio#1451]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
fio is not running in IPv6 network

**Environment**: Openshift Container Platform-4.11 / Kubernetes-1.24.0

**fio version**: fio-3.29

**Reproduction steps**
While running fio in an IPv6 network, the job is failing with the following error message:
```
fio: failed to resolve <fd01:0:0:3::1c6> (Address family for hostname not supported)
fio: failed adding client fd01:0:0:3::1c6
```
Question: Is fio supported with IPv6? I have checked the [documentation](https://fio.readthedocs.io/en/latest/fio_doc.htm), where IPv6 is sparsely mentioned, so I assume fio should work in an IPv6 environment.

Thanks.

**Comment by axboe** [comment]
You did not read the REPORTING-BUGS as indicated, as information is missing from this report that is mentioned in there. Most related would be the "how to reproduce".

**Comment by axboe** [comment]
Closing this one, reopen if you provide the information requested.

**Comment by bose-abhishek** [comment]
Apologies if there was lack of information. The issue was observed when client IP address was provided in an IPv6 format.
I tried this in baremetal RHEL server as well and found the same error message.

```
At host-1
# fio --server=ip6:fc00:1000::10
fio: server listening on fc00:1000::10,8765

At host-2
# fio --client=fc00:1000::10 job.fio 
fio: failed to resolve <fc00:1000::10> (Address family for hostname not supported)
fio: failed adding client fc00:1000::10
```
Tried with IPv6 notation.
```
# fio --client=[fc00:1000::10] job.fio 
fio: failed to resolve <[fc00:1000::10]> (Name or service not known)
fio: failed adding client [fc00:1000::10]
```
```
host-1 is reachable from host-2
# ping6 fc00:1000::10
PING fc00:1000::10(fc00:1000::10) 56 data bytes
64 bytes from fc00:1000::10: icmp_seq=1 ttl=64 time=0.171 ms
64 bytes from fc00:1000::10: icmp_seq=2 ttl=64 time=0.199 ms
```

Here is the job file I tried with, though the job file isn't relevant here as it cannot connect to the remote server.
```
# cat job.fio 
[global]
ioengine=libaio
direct=1
rw=write
bs=4k
numjobs=1
time_based=1
runtime=300
size=10G
iodepth=1

[device]
filename=/dev/nvme0n1
```
Let me know if you need any further information.
Thanks.

**Comment by axboe** [comment]
Add ip6 on the client one too?

**Comment by bose-abhishek** [comment]
Thanks @axboe , setting ip6 at the client end seem to resolve the issue.

```
# fio --client=ip6:fc00:1000::10 job.fio 
hostname=<host-1>, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.19, flags=1
<host-1> device: (g=0): rw=write, bs=(R) 4096KiB-4096KiB, (W) 4096KiB-4096KiB, (T) 4096KiB-4096KiB, ioengine=libaio, iodepth=1
<host-1> Starting 1 process
...
```
I would like to suggest if this information can be added in the fio [documentation](https://fio.readthedocs.io/en/latest/fio_doc.html).

**Comment by axboe** [comment]
> I would like to suggest if this information can be added in the fio [documentation]

Would you be up for sending a patch for that?

**Comment by bose-abhishek** [comment]
Here is the PR: https://github.com/axboe/fio/pull/1456
