### ISSUE TITLE
Layout files in parallel

### ISSUE THREAD

**Issue by asomers** [axboe/fio#1453]
**Description of the new feature**
If fio is configured to use multiple directories, or multiple filenames, it should lay them out in parallel to maximize use of disk bandwidth.

**Background**
I use fio to burn-in hard drives on new servers that have multiple ZFS pools.  It does a good job of creating a mixed read/write workload across all pools, once all of the files are laid out.  But file layout can take a very long time.  Would it be possible to do the layout in parallel too?

**Comment by axboe** [comment]
```create_serialize```?

**Comment by asomers** [comment]
Thank you!  I didn't know about that setting.  FTR, to use this it's also necessary to set `numjobs` equal to the number of directories, like this:
```ini
[global]
numjobs=4
create_serialize=0

[job1]
directory=/POOL0:/POOL1:/POOL2:/POOL3
```

**Comment by Gt3pccb** [comment]
IMHO the numjobs = num of directories does not make much sense when testing file systems. One should be able to assign multiple directories and number of files on a per job basis.
