### ISSUE TITLE
Fio can silently drop log entries when using the log compression option

### ISSUE THREAD

**Issue by aggieNick02** [axboe/fio#1457]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
The log compression option is powerful, allowing per I/O logging with reduced memory usage. Unfortunately, it can result in dropped log entries. Using the null ioengine seems to make the issue reproduce pretty reliably.

The number of entries dropped varies, and can vary between different logs in a single run. Turning off compression makes the issue go away.

Turning the `log_compression` parameter down, while perhaps not something one would do in production, seems to make the problem more pervasive, plus gives a repro that is much faster to run. In the repro below I've reduced `size` from a typical `1000G` and `log_compression` from a typical `10M` by a factor of 1024 to `1000M` and `10K`, respectively

**Environment**: Ubuntu 20.04.4 LTS

**fio version**: fio-3.31-31-ga5a2 (head of master, also reproduces in fio-3.30

**Reproduction steps**
Create a new directory and cd to it. Then run:

```
fio --filename=/dev/nvme1n1 --name=job --per_job_logs=0 --write_bw_log=fio_0 --ioengine=null --direct=1 --size=1000M --rw=write --bs=128K --iodepth=1 --log_offset=1 --log_store_compressed=1 --log_compression=10K
```

Notice total I/O (all writes) is 8000

Now inflate the bw log, and then count the number of lines to see how many I/O were recorded:

```
fio --inflate-log=fio_0_bw.log.fz > fio_0_bw.log
wc -l fio_0_bw.log
```

and observe the output:
```
3904 fio_0_bw.log
```

With the offset logged, it makes it easy to see where a drop has happened. It actually happened at this exact spot two times in a row, interestingly.
```
6, 5461333333, 1, 131072, 402391040, 0
6, 5242880000, 1, 131072, 402522112, 0
9, 4369066666, 1, 131072, 939524096, 0
9, 2114064516, 1, 131072, 939655168, 0
```

**Comment by aggieNick02** [comment]
Bug does not appear to occur if `--log_store_compressed=1` is omitted.

(Storing compressed is a really nice option - files are much smaller, and each one can be inflated and then gzip'ed in parallel to end up with reasonably sized log files that are in a friendly format for use by other tools.)

**Comment by vincentkfu** [comment]
Have you tried `log_compression_cpus`? https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-compression-cpus

Pin the fio job thread to one CPU and the compression thread to another one on the same NUMA node. Make sure the two CPUs are not hyperthreaded siblings of each other.

**Comment by aggieNick02** [comment]
Thanks for the idea. The problem still reproduces when doing this, which isn't super surprising.

(The bug is almost certainly in the code that implements `log_store_compressed`, since it does not seem to reproduce with just `log_compression`. The `log_store_compressed` happens after the actual I/O is done and is also single threaded - which is good for actually debugging/fixing. I'm working on debugging the issue now.)

**Comment by aggieNick02** [comment]
So I want to clean things up a bit as there are other details about log compression to address (e.g. `log_compression` does not affect in-memory size at all, other than as a boolean), but the bug is that `iolog_flush` in `iolog.c` needs to call
```
workqueue_flush(&log->td->log_compress_wq);
```
after its declarations.

This fixes the easy to repro bug, and I'm guessing the original that led me to the reproduction. Without it, work that has been queued up to be compressed but not yet processed can be lost when the job finishes. So in general, the lost data will be towards the end of the run.

I'll try to get a PR together quickly, and also look at adding a couple tests to keep this working (line count of log file should equal number of IOs, and offset with `qd=1` should be monotonic within the log file). We can test both with just compression and with compressed storage and subsequent inflation.

**Comment by aggieNick02** [comment]
PR to fix this and add tests to keep it fixed has been submitted. I'll do a separate one to clean up the documentation on log_compression, since it no longer affects chunk size, but is effectively a boolean control.

**Comment by rustyscottweber** [comment]
I unknowingly ran into this issue while running fio-3.19 as it was the stock version that comes with RHEL these days.  It was a 120 hour long test for system reliability. Log stops after 17 hours, failing silently, and even includes a single final data point that seemingly fits the 120 hour timeline.  That's 120 hours of my life I'm never getting back.  Thanks for finding this issue and fixing it. RHEL really needs to update their crap.
