### ISSUE TITLE
Error message: "Operation not supported" when issuing fio trim test

### ISSUE THREAD

**Issue by ningqingqing** [axboe/fio#1467]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<Log shows "Operation not supported" when issuing fio trim test, we confirmed trim is supported on testing device because we can issue trim command in other ways>

**Environment**: <linux, centos system>

**fio version**: <fio-3.25>

**Reproduction steps**
<Run test with command "sudo fio xxx.fio --filename=xxx"
Here is fio file parameters:
[global]
per_job_logs=1
max_latency=8s
percentile_list=1:5:10:20:30:40:50:60:70:80:90:95:99:99.9:99.99:99.999:99.9999

[wrkldtrim1]
readwrite=trim
numjobs=1
iodepth=1
ioengine=libaio
bs=1024K
ba=1024K
randrepeat=1
refill_buffers=0
direct=1
size=20%
offset=0%
ramp_time=0
runtime=0
group_reporting=1
log_avg_msec=1000
log_hist_msec=1000
disk_util=1>

We also try to add debug parameter to check any error in trim test.
Here is fail log:
[trim.log](https://github.com/axboe/fio/files/9534896/trim.log)

**Comment by axboe** [comment]
That log just shows that you didn't set size= and this is why the job terminates.

**Comment by ningqingqing** [comment]
> That log just shows that you didn't set size= and this is why the job terminates.

I set size=20% in fio file. and I can find "parse    19500 size=20%" in fail log. 
Could you help point out where log shows "didn't set size="

**Comment by vincentkfu** [comment]
FIo is unable to obtain the file size. So it can't use size=20%.

```
file     19500 get file size for 0x7f6eea1672f0/0//dev/nvme0n1
wrkldtrim1: you need to specify size=
process  19500 pid=0: runstate SETTING_UP -> NOT_CREATED
fio: pid=0, err=22/file:filesetup.c:1055, func=total_file_size, error=Invalid argument
```

I think the most likely explanation is that there is a problem with your test environment.

**Comment by ningqingqing** [comment]
> FIo is unable to obtain the file size. So it can't use size=20%.
> 
> ```
> file     19500 get file size for 0x7f6eea1672f0/0//dev/nvme0n1
> wrkldtrim1: you need to specify size=
> process  19500 pid=0: runstate SETTING_UP -> NOT_CREATED
> fio: pid=0, err=22/file:filesetup.c:1055, func=total_file_size, error=Invalid argument
> ```
> 
> I think the most likely explanation is that there is a problem with your test environment.

Please help check this log, I changed size to 100%, but still failed.
[trimfail.log](https://github.com/axboe/fio/files/9539432/trimfail.log)

**Comment by axboe** [comment]
If fio can't get the file size, it doesn't make it any better to use 100% rather than 20%. You need to set an actual size in mb/gb/whatever.

**Comment by ningqingqing** [comment]
> If fio can't get the file size, it doesn't make it any better to use 100% rather than 20%. You need to set an actual size in mb/gb/whatever.

I set size=20G, please help check log.
[trim_20G.log](https://github.com/axboe/fio/files/9540620/trim_20G.log)

**Comment by axboe** [comment]
Fio is crashing:

fio: pid=74150, got signal=11                                                   

Please try and update to the latest one and report if it still happens.

**Comment by ningqingqing** [comment]
Try with fio3.32, still failed.
[trim-with-fio3.32.log](https://github.com/axboe/fio/files/9544888/trim-with-fio3.32.log)

**Comment by axboe** [comment]
Can you include the exact job file and command line arguments you are using now?

**Comment by ningqingqing** [comment]
Command line: sudo ~/Desktop/fio-fio-3.32/fio wrkld_trim1__1_1.fio --filename=/dev/nvme0n1 --debug=all --output-format=json --output=trim.json
Wkld file:  .fio file is not support to upload, so I change to .log
[wrkld_trim1__1_1.log](https://github.com/axboe/fio/files/9544955/wrkld_trim1__1_1.log)

**Comment by axboe** [comment]
It runs just fine for me, ran without the debug options to avoid a ton of spewage:

```
axboe@m1pro-kvm ~/g/fio (master)> sudo ./fio trim-test.fio --filename=/dev/nvme1n1
wrkldtrim1: (g=0): rw=trim, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=1
fio-3.32-12-ge577-dirty
Starting 1 process
Jobs: 1 (f=0)
wrkldtrim1: (groupid=0, jobs=1): err= 0: pid=536: Sun Sep 11 23:55:34 2022
  trim: IOPS=24.0k, BW=23.5GiB/s (25.2GB/s)(20.0GiB/852msec)
    clat (usec): min=32, max=1263, avg=41.32, stdev=17.03
     lat (usec): min=32, max=1263, avg=41.36, stdev=17.04
    clat percentiles (usec):
     |  1.00th=[   34],  5.00th=[   34], 10.00th=[   34], 20.00th=[   35],
     | 30.00th=[   36], 40.00th=[   38], 50.00th=[   39], 60.00th=[   41],
     | 70.00th=[   42], 80.00th=[   43], 90.00th=[   46], 95.00th=[   57],
     | 99.00th=[  116], 99.50th=[  145], 99.90th=[  217], 99.95th=[  231],
     | 99.99th=[  306]
   bw (  MiB/s): min=22838, max=22838, per=95.01%, avg=22838.00, stdev= 0.00, samples=1
   iops        : min=22838, max=22838, avg=22838.00, stdev= 0.00, samples=1
  lat (usec)   : 50=93.51%, 100=5.03%, 250=1.43%, 500=0.02%
  lat (msec)   : 2=0.01%
  cpu          : usr=1.88%, sys=7.76%, ctx=23897, majf=0, minf=23
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,0,20480,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   TRIM: bw=23.5GiB/s (25.2GB/s), 23.5GiB/s-23.5GiB/s (25.2GB/s-25.2GB/s), io=20.0GiB (21.5GB), run=852-852msec

Disk stats (read/write):
  nvme1n1: ios=49/0, merge=0/0, ticks=7/0, in_queue=544, util=87.94%
```

Tried a SCSI device too, no issues. Can you you do this for me:

# grep . /sys/block/nvme1n1/queue/discard_*

and send the output.

**Comment by ningqingqing** [comment]
$ grep . /sys/block/nvme0n1/queue/discard_*
/sys/block/nvme0n1/queue/discard_granularity:0
/sys/block/nvme0n1/queue/discard_max_bytes:0
/sys/block/nvme0n1/queue/discard_max_hw_bytes:0
/sys/block/nvme0n1/queue/discard_zeroes_data:0

**Comment by axboe** [comment]
Your device doesn't support trim...

**Comment by ningqingqing** [comment]
Does FIO follows nvme spec 1.4 or 2.0? 
We confirmed trim is supported because we can issue trim command in other ways.
Is there any possible that something changed in 2.0 spec that caused this issue?

**Comment by axboe** [comment]
This isn't a fio issue, the kernel doesn't think the drive supports discard. Fio doesn't issue raw trim/discard commands.

**Comment by ningqingqing** [comment]
Thank you so much. I will check with my kernel team on this.
