### ISSUE TITLE
fio on windows can only be killed from the command line forcefully using taskkill

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#147]
On a headless windows server, while running fio, sometimes using or getting to the direct console to press ctrl+c to end a long running fio job can be difficult or even impossible in automation scenarios.  Sometimes it's best to use taskkill to end the process when we don't know how long we are actually going to need to run fio for and would like to end the process early.
However I noticed that fio doesn't respond to taskkill unless it is a force kill which doesn't send a message to the process at all and stops the process by reclaiming it the same manner as if the process had encountered a fatal error.  This leaves me questioning whether or not I will have correct logs and whether or not some error could possibly be masked by the forced kill.
Examlpe

<pre><code>
C:\Users\Administrator>tasklist
fio.exe                       3028 RDP-Tcp#26                 2    245,424 K
C:\Users\Administrator>taskkill /t /pid 3028 
ERROR: The process with PID 3028 (child process of PID 812) could not be terminated.
Reason: This process can only be terminated forcefully (with /F option).

C:\Users\Administrator>taskkill /t /f  /pid 3028 
SUCCESS: The process with PID 14164 (child process of PID 812) has been terminated.
</code></pre>

However, the output from fio looks like the following because it stopped dead in it's tracks meaning it's never given the chance to exit gracefully.

<pre><code>
Jobs: 1 (f=1): [m(1)] [5.5% done] [19709KB/19522KB/0KB /s] [4927/4880/0 iops] [eta 06m:19s]
</code></pre>

I realize that taskkill on windows is different than kill on linux, but they do have much of the same purpose and it seems logical to me that I should be able to ask fio to terminate gracefully from taskill on windows just like I might be able to do with the kill -SIGINT command on linux since windows taskkill sends a similar message "WM_CLOSE".
It seems like a good idea to me that the windows builds of Fio should treat the WM_CLOSE message from windows in the same mannor in which it treats SIGINT or SIGTERM signals in linux.

**Comment by sitsofe** [comment]
@bcran any thoughts on this?

**Comment by sitsofe** [comment]
This request isn't straightforward - in order to get the `WM_CLOSE` message, an application has to have a window associated with it (even if it's a hidden one) - see http://stackoverflow.com/questions/23197669/send-wm-close-message-to-a-process-with-no-window/23197789#23197789 . One workaround is for a user to run fio in a terminal and then use taskkill to send a message to the terminal which in turn will try and (politely) exit fio before aggressively stopping it.

**Comment by sitsofe** [comment]
@rustyscottweber did the last suggestion answer your request? If so could you close this issue?

**Comment by rustyscottweber** [comment]
No.  The problem with this solution is that it forces a close of the process without allowing fio to close gracefully.  However, looking at the code, it sounds like the real fix this, because windows sucks, is finding out how to send ctrl + C through windows RM.  However, this is outside the purview of FIO.

**Comment by sitsofe** [comment]
@rustyscottweber You're right that this is beyond the purview of fio but I'm surprised that neither suggestion allows fio to exit cleanly because I tried both here and they worked!

As you stated the first suggestion (launch fio via start) doesn't lead to a clean exit - fio receives notice that it should exit but doesn't appear to have a chance to close down before being killed. I guess the parent terminal going away too quickly results in the child process' death too.

However, the second suggestion (use a different program to taskkill that knows how to Ctrl-C to a console program) works (but hooking that up via WinRM is left as an exercise for the reader). I suppose another hack would be to abuse triggers (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-trigger-file ).

At any rate do you think you could close this issue? It doesn't sound like there's much that can be done in fio itself about this...

**Comment by rustyscottweber** [comment]
Closing this issue as there isn't really a good way to send a standard message to a process in windows.

**Comment by jzabroski** [comment]
Hit this issue today when an AWS support rep suggested using fio on Windows.

**Comment by sitsofe** [comment]
@jzabroski Are you sure you meant to post on a closed issue? Your issue _might_ be the same (and thus might not have a solution - see the above comments) but without more detail it's totally unactionable :-( I would suggest one of the following:

- If you're looking for new responses I would recommend posting something to the fio mailing list (see https://github.com/axboe/fio/blob/master/.github/SUPPORT.md#general-questions )
- If you're only posting a "me too" I recommend sticking to using GitHub's reaction on the comment

While it's interesting that your AWS rep pointed you at fio it would be even better if they helped contribute code to fio that helps solves your issue :-)

**Comment by jzabroski** [comment]
> While it's interesting that your AWS rep pointed you at fio it would be even better if they helped contribute code to fio that helps solves your issue :-)

I contribute a lot of open source code, but I really have no interest in supporting something that AWS links to with zero instructions on how to run it on Windows.  They even linked me to an [8 month old AppVeyor build](https://ci.appveyor.com/project/axboe/fio/builds/33014641/job/qlyklq50fhuheo87/artifacts) and gave very vague instructions on which artifact to install.  I believe I guessed right by picking `Environment: ARCHITECTURE=x64, CONFIGURE_OPTIONS=, DISTRO=cygwin`.

> * If you're only posting a "me too" I recommend sticking to using GitHub's reaction on the comment

I don't see this as a "me too".  I see this as a way to flag that a 5 year old issue is still active despite being closed.  I read the complete thread before responding, and do understand it may be a PITA to fix for Windows, but I think its helpful (both for my future self and others) to make this note.  Thank you for understanding.  And I do understand that "me too" comments can be annoying.  I run two projects with over 2M downloads each, and it's rough getting inbox messages where people just type in a stack trace into Google and go to the first thread and say "I am also getting this."  Enjoy the rest of your weekend.

**Comment by jzabroski** [comment]
@sitsofe I logged two feature requests which are probably better than trying to fix this issue if its as difficult as the OP suggests.  I must confess, I don't understand why it's hard, but I've never maintained cross-platform C code before, so I am probably super naive.

**Comment by sitsofe** [comment]
@jzabroski 

> I don't understand why [politely killing a command line program on Windows using taskkill] hard

To summarise: It is very hard to send arbitrary signals to Windows programs (whereas on POSIX systems it is very easy and there are standard commands to do it). On Windows, if your program doesn't have a window (which console programs like fio don't) then the `WM_CLOSE` message can't actually be delivered and besides a forceful kill that's the only message that taskkill sends other than it's forceful kill. You can read more about this behaviour https://stackoverflow.com/a/140394/2732969 . If you use a non-standard program (see answers to https://stackoverflow.com/q/813086/2732969 ) then you can send an appropriate message and trigger a polite stop of fio that way.

**Comment by rustyscottweber** [comment]
For completeness. I solved my particular issue here by sending ctrl+C to the running program through windows remote management. This was not a trivial task and required adding code to a python project that I use, pywinrm.
