### ISSUE TITLE
FIO json results have "N" : 0 displacing percentile list

### ISSUE THREAD

**Issue by Flounden** [axboe/fio#1478]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
After an FIO run is completed we are seeing the json output file contain this bizarre line "N" : 0 which we have not seen before.  There is also the missing percentile list that are being replaced with this same "N" : 0 line.

**Environment**: Issue is with CentOS8.2 with kernel 5.4.134.  Was working correctly when we used CentOS w/kernel 4.9.5

**fio version**: With the reported problem - FIO 3.32 and 3.19  and without the problem was 3.9

**Reproduction steps**
 Attached are the cfg file that I ran with along with a sample of the issue where it ran correctly on the older OS and another sample of the problem where it was ran on the later version of OS and FIO.

[cfg_file.txt](https://github.com/axboe/fio/files/9761163/cfg_file.txt)

[FIO_Issues_example.txt](https://github.com/axboe/fio/files/9761164/FIO_Issues_example.txt)

**Comment by ankit-sam** [comment]
fio-3.9 is a bit old so there are a lot of changes compared to fio-3.32
Looking at the issue which you mentioned "N" is the number of latency samples, which should should be equal to the number of I/O's. The percentile list is still there but guarded by the condition that number of latency samples are not 0.

Check this:
https://github.com/axboe/fio/blob/fio-3.32/stat.c#L1405

looking at the log which you shared everything is 0 both on fio 3.9 and fio 3.32, so you will have to check that first.

**Comment by Flounden** [comment]
Thank You Ankit.  It looks like then we will have to rebuild our parser.
