### ISSUE TITLE
Specified rwmixwrite and rwmixread doesn't appear to have an effect

### ISSUE THREAD

**Issue by tomc603** [axboe/fio#1483]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

When running fio on an NVMe using jobs broken into random read and random write, specifying the `--rwmixwrite` and `--rwmixread` doesn't appear to actually change the read/write IOPS or bandwidth. When requesting a 25% write mix, fio doesn't appear to issue the correct ratio, but I could be understanding the purpose of the command line options incorrectly, or applying conflicting options. These results can be reproduced with multiple revisions of the Samsung PM9A3 in multiple test hosts I have direct access to, but also appears to be occurring with multiple models.

Snipped output in the log file looks like:

```
writer: (groupid=0, jobs=8): err= 0: pid=4767: Mon Oct 31 16:56:37 2022
  write: IOPS=36.5k, BW=143MiB/s (149MB/s)(501GiB/3600005msec); 0 zone resets
...
reader: (groupid=1, jobs=64): err= 0: pid=4775: Mon Oct 31 16:56:37 2022
  read: IOPS=273k, BW=1067MiB/s (1119MB/s)(3751GiB/3600004msec)
...
Run status group 0 (all jobs):
  WRITE: bw=143MiB/s (149MB/s), 143MiB/s-143MiB/s (149MB/s-149MB/s), io=501GiB (538GB), run=3600005-3600005msec

Run status group 1 (all jobs):
   READ: bw=1067MiB/s (1119MB/s), 1067MiB/s-1067MiB/s (1119MB/s-1119MB/s), io=3751GiB (4028GB), run=3600004-3600004msec
```

**Environment**:

Ubuntu 20.04.5 LTS
Kernel: 5.15.0-52-generic \#58~20.04.1-Ubuntu
Processor: AMD 7662
RAM: 768GB - 1TB

**fio version**: fio-3.32

**Reproduction steps**

Job command line:

```
fio --output=fio-logfile.log --exitall_on_error --bs=4K --direct=1 --fadvise_hint=random \
    --filename=/mnt/testing/fio --group_reporting=1 --iodepth=16 --ioengine=libaio \
    --ioscheduler=mq-deadline --log_avg_msec=1000 --log_compression=1m \
    --log_store_compressed=1 --ramp_time=10 --randrepeat=0 --runtime=1h \
    --rwmixread=75 --rwmixwrite=25 --size=1T --thread --time_based \
    --write_bw_log=fio-logs/fio-stress --write_iops_log=fio-logs/fio-stress \
    --write_lat_log=fio-logs/fio-stress \
    --name=writer --new_group --stonewall --numjobs=8 --rw=randwrite --exitall \
    --name=reader --new_group --numjobs=64 --rw=randread
```

I have also attempted to specify `rwmixwrite` and `rwmixread` in the job definitions, but that doesn't appear to change the outcome.

**Comment by vincentkfu** [comment]
`rwmixread` and `rwmixwrite` are only relevant when you have `rw=randrw`. Your `writer` jobs create 8 100% write jobs and your `reader` jobs create 64 100% read jobs and they are all independent of each other.

Something like the following will give you  a 75/25 r/w mix:

```
# ./fio --name=test --ioengine=null --rwmixwrite=25 --filesize=1G --rw=randrw
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.32-75-gc470
Starting 1 process

test: (groupid=0, jobs=1): err= 0: pid=9270: Tue Nov  1 20:01:22 2022
  read: IOPS=1754k, BW=6853MiB/s (7186MB/s)(768MiB/112msec)
    clat (nsec): min=33, max=16589, avg=49.25, stdev=52.70
     lat (nsec): min=64, max=16675, avg=96.77, stdev=106.07
    clat percentiles (nsec):
     |  1.00th=[   33],  5.00th=[   34], 10.00th=[   34], 20.00th=[   35],
     | 30.00th=[   50], 40.00th=[   50], 50.00th=[   51], 60.00th=[   51],
     | 70.00th=[   51], 80.00th=[   51], 90.00th=[   52], 95.00th=[   52],
     | 99.00th=[  133], 99.50th=[  135], 99.90th=[  135], 99.95th=[  137],
     | 99.99th=[  141]
  write: IOPS=586k, BW=2290MiB/s (2401MB/s)(256MiB/112msec); 0 zone resets
    clat (nsec): min=33, max=15380, avg=49.74, stdev=61.97
     lat (nsec): min=72, max=15443, avg=108.77, stdev=77.08
    clat percentiles (nsec):
     |  1.00th=[   33],  5.00th=[   34], 10.00th=[   34], 20.00th=[   35],
     | 30.00th=[   50], 40.00th=[   51], 50.00th=[   51], 60.00th=[   51],
     | 70.00th=[   52], 80.00th=[   52], 90.00th=[   52], 95.00th=[   53],
     | 99.00th=[  135], 99.50th=[  135], 99.90th=[  137], 99.95th=[  139],
     | 99.99th=[  145]
  lat (nsec)   : 50=25.11%, 100=72.10%, 250=2.78%
  lat (usec)   : 10=0.01%, 20=0.01%
  cpu          : usr=97.30%, sys=2.70%, ctx=2, majf=0, minf=9
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=196498,65646,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=6853MiB/s (7186MB/s), 6853MiB/s-6853MiB/s (7186MB/s-7186MB/s), io=768MiB (805MB), run=112-112msec
  WRITE: bw=2290MiB/s (2401MB/s), 2290MiB/s-2290MiB/s (2401MB/s-2401MB/s), io=256MiB (269MB), run=112-112msec
```

You can either create jobs that submit both read and write commands like the example above or if it's important that jobs issue only read or write commands, consider the `flow` option. See the manpage for details. The HOWTO and online documentation are not up to date.

There is an example at https://github.com/axboe/fio/blob/master/examples/flow.fio

**Comment by tomc603** [comment]
Thank you @vincentkfu for the feedback. I've got a device preparing for testing now, using `flow=` to control the ratio of IO between concurrent jobs. I've seen this pattern crop up quite a few times in the wild, and likely just cargo culted it myself without completely understanding how the mix values were implemented. I'll be sure to spread this new knowledge to everyone I know.
