### ISSUE TITLE
Some enhancement requests

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#149]
This is a great tool but can be improvised further:

1. IO Range: User should be able to specify a LBA range or Range Percentage i.e first 10-30% of storage space
2. Seek patterns: Reverse sequential, Butterfly, reverse butterfly, Worm(overlapped writes)

**Comment by axboe** [comment]
You can do ranges, with a combination of size= and offset=. Only size takes a percentage, though. Similarly, you can do reverse sequential or worm. rw=write:-2k bs=4k would write sequentially, but seek back 2k for every 4k write. Read the man page / documentation to see how you could do reverse sequential as well.

In general, if there are areas you feel could be improved, take the time to understand how it currently works and suggest a patch to implement the improvement.

**Comment by shivapahwa** [comment]
Thanks a lot for taking the time to respond. Sorry for not abing able to interprit the man page correctly.
