### ISSUE TITLE
FIO version 3.33 for Linux sometimes generates erroneous READ statistics during testing of WRITE with verify

### ISSUE THREAD

**Issue by george-eldridge** [axboe/fio#1492]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
About 5% of the time FIO 3.33 for Linux will generate erroneous READ statistics during testing of WRITE with verify. The time of the READ test will be much less than the time of the WRITE test. The amount of data reported for the READ test is 1GB less than amount of data reported for the WRITE test. The READ throughput numbers that are reported are unrealistically high.

**Environment**:
System Information:
Operating System:     Red Hat Enterprise Linux 8.6 (Ootpa)
Kernel Version:       4.18.0-372.9.1.el8.x86_64
Python Version:       3.9.12

**fio version**: fio-3.33

**Reproduction steps**
Create 20 jobs that are 15 minutes each and alternate between READ (rw=read) and WRITE (rw=write) with verify enabled and various block sizes
Run the jobs and collect the output. In some cases of the WRITE test (1 or 2 out of the 20 jobs) there will be erroneous READ statistics produced along with the WRITE statistics.

Sample Output:
====================================================================================================
Run count: 20
11/24/2022, 11:30:17
====================================================================================================
nvme1n1_job_00: (g=0): rw=write, bs=(R) 64.0KiB-64.0KiB, (W) 64.0KiB-64.0KiB, (T) 64.0KiB-64.0KiB, ioengine=libaio, iodepth=8
fio-3.33
Starting 1 thread

nvme1n1_job_00: (groupid=0, jobs=1): err= 0: pid=606650: Thu Nov 24 11:45:17 2022
  read: IOPS=1770k, BW=108GiB/s (116GB/s)(1089GiB/10080msec)
    slat (nsec): min=2520, max=374951, avg=2925.48, stdev=432.99
    clat (usec): min=30, max=26553, avg=337.09, stdev=130.97
     lat (usec): min=34, max=26556, avg=340.01, stdev=130.96
    clat percentiles (usec):
     |  1.00th=[  145],  5.00th=[  153], 10.00th=[  182], 20.00th=[  239],
     | 30.00th=[  265], 40.00th=[  289], 50.00th=[  318], 60.00th=[  351],
     | 70.00th=[  379], 80.00th=[  433], 90.00th=[  506], 95.00th=[  578],
     | 99.00th=[  709], 99.50th=[  758], 99.90th=[  914], 99.95th=[ 1029],
     | 99.99th=[ 1352]
  write: IOPS=20.1k, BW=1254MiB/s (1315MB/s)(1090GiB/889921msec); 0 zone resets
    slat (nsec): min=2630, max=553871, avg=4670.12, stdev=986.55
    clat (usec): min=32, max=3005, avg=53.90, stdev=11.30
     lat (usec): min=43, max=3015, avg=58.57, stdev=11.25
    clat percentiles (usec):
     |  1.00th=[   43],  5.00th=[   43], 10.00th=[   44], 20.00th=[   45],
     | 30.00th=[   47], 40.00th=[   49], 50.00th=[   51], 60.00th=[   54],
     | 70.00th=[   57], 80.00th=[   62], 90.00th=[   70], 95.00th=[   77],
     | 99.00th=[   93], 99.50th=[   98], 99.90th=[  112], 99.95th=[  116],
     | 99.99th=[  131]
   bw (  MiB/s): min=   81, max= 1447, per=99.75%, avg=1251.10, stdev=76.49, samples=1784
   iops        : min= 1300, max=23164, avg=20017.50, stdev=1223.86, samples=1784
  lat (usec)   : 50=23.35%, 100=26.54%, 250=11.57%, 500=33.31%, 750=4.95%
  lat (usec)   : 1000=0.24%
  lat (msec)   : 2=0.03%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  cpu          : usr=11.95%, sys=14.07%, ctx=27556111, majf=0, minf=3128
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=100.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.1%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=17838521,17859401,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=8

Run status group 0 (all jobs):
   **READ: bw=108GiB/s (116GB/s), 108GiB/s-108GiB/s (116GB/s-116GB/s), io=1089GiB (1169GB), run=10080-10080msec**
  WRITE: bw=1254MiB/s (1315MB/s), 1254MiB/s-1254MiB/s (1315MB/s-1315MB/s), io=1090GiB (1170GB), run=889921-889921msec

Disk stats (read/write):
  nvme1n1: ios=17837195/17857445, merge=0/0, ticks=5985093/954981, in_queue=6940074, util=100.00%
====================================================================================================

The READ statistics have much less than the 900 seconds of the test. The READ data is 1GB less than the WRITE data. The READ performance is unrealistically high (116 GB/s)

Parameters for the job:

[global]
norandommap
refill_buffers
group_reporting
time_based
direct=1
randrepeat=0
thread=1
ioengine=libaio
numjobs=1
iodepth=8
bs=64k
ba=64k
rw=write
random_generator=tausworthe64
runtime=900
do_verify=1
verify=pattern
verify_dump=1
verify_backlog=2
verify_pattern=0xe8a6fdab8b724bf155df6bfceadc503716681501893a95104f3e8dd0dd94e8ec
buffer_pattern=0xe8a6fdab8b724bf155df6bfceadc503716681501893a95104f3e8dd0dd94e8ec

[nvme1n1_job_00]
filename=/dev/nvme1n1
offset=93%

[BugReport.txt](https://github.com/axboe/fio/files/10106672/BugReport.txt)

**Comment by vincentkfu** [comment]
There seems to be two problems here: (1) absurdly high read bandwidth measurements and (2) some of the blocks written are not verified.

I believe the problem with (1) is because of `verify_backlog`. In the above job file, `verify_backlog` instructs fio to attempt to verify after every two write operations. There is not a 100% read phase for the job like there is for a job with the default verify mode. So fio's housekeeping for the verify phase is faulty and does not reflect the full time during which verify reads are being issued. If you want to calculate read bandwidth you should just use the total job runtime in the denominator instead of the short duration fio reports.

I will also note that the job file sets `verify_backlog=2` and `iodepth=8`. The values for these two options don't quite work together although fio tries to carry on. `iodepth=8` tells fio to put 8 IOs in flight before reaping completions, but `verify_backlog=2` instructs fio to issue reads after two write operations have completed. Fio ends up issuing 8 writes and afterwards issues the read commands to verify those 8 writes. So in essence fio is operating as if the job file specified `verify_backlog=8`. Fio can't have a mix of writes and reads to the same blocks in fight because there is no guarantee that the writes will complete before the reads.

BugReport.txt only mentioned that jobs 10 and 20 showed very high read bandwidth, but many other jobs also have `verify_backlog=2`. For example, `Run count: 2` and `Run count: 3` both have `verify_backlog=2` yet the output for those jobs show no read commands issued by fio. Is there any light you can shed here?

Issue (2) is more of a concern. Do you have a simpler way of reproducing this issue? Is there an older version of fio where this issue did not occur? It's not a problem if the difference between the number of read and write commands is less than the iodepth but your results show a considerably larger difference.

**Comment by george-eldridge** [comment]
<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I began running some tests to determine the impact of various parameters. I used a simple set of FIO base commands:</p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tt><span class="error">[global]</span></tt><br><tt>norandommap</tt><br><tt>refill_buffers</tt><br><tt>group_reporting</tt><br><tt>time_based</tt><br><tt>direct=1</tt><br><tt>randrepeat=0</tt><br><tt>thread=1</tt><br><tt>ioengine=libaio</tt><br><tt>numjobs=1</tt><br><tt>iodepth=8</tt><br><tt>bs=64k</tt><br><tt>ba=64k</tt><br><tt>rw=write</tt><br><tt>random_generator=tausworthe64</tt><br><tt>runtime=900</tt><br><tt>do_verify=1</tt><br><tt>verify=pattern</tt><br><tt>verify_dump=1</tt><br><tt>verify_backlog=8</tt><br><tt>verify_backlog_batch=8</tt><br><tt>verify_pattern=0xe8a6fdab8b724bf155df6bfceadc503716681501893a95104f3e8dd0dd94e8ec</tt><br><tt>buffer_pattern=0xe8a6fdab8b724bf155df6bfceadc503716681501893a95104f3e8dd0dd94e8ec</tt></p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tt><span class="error">[nvme0n1_job_00]</span></tt><br><tt>filename=/dev/nvme0n1</tt><br><tt>offset=93%</tt></p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I then varied the iodepth, verify_backlog and verify_backlog_batch parameters. The following table shows the results:</p><div class="table-wrap" style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

iodepth | verify_backlog | verify_backlog_batch | rMB/s | wMB/s | % verify | comments
-- | -- | -- | -- | -- | -- | --
1 | not used | not used | 0 | 1290 | 0% |  
1 | 1 | not used | 733 | 733 | 100% |  
2 | not used | not used | 0 | 1996 | 0% |  
2 | 2 | not used | 390 | 428 | 91% |  
2 | 4 | not used | 350 | 417 | 84% |  
2 | 8 | not used | 416 | 418 | 100% |  
2 | 16 | not used | 194 | 194 | 100% |  
4 | not used | not used | 0 | 1989 | 0% |  
4 | 4 | not used | 610 | 744 | 82% |  
4 | 8 | not used | 587 | 693 | 85% |  
4 | 16 | not used | 700 | 712 | 98% |  
4 | 32 | not used | 636 | 636 | 100% | high variability
4 | 64 | not used | 521 | 521 | 100% |  
8 | not used | not used | 0 | 1995 | 0% |  
8 | 8 | not used | 895 | 1146 | 78% |  
8 | 16 | not used | 888 | 1062 | 84% |  
8 | 32 | not used | 939 | 977 | 96% |  
8 | 64 | not used | 902 | 902 | 100% | high variability
8 | 128 | not used | 1015 | 1015 | 100% | high variability
8 | 8 | 8 | 900 | 1159 | 78% |  
8 | 8 | 16 | 1117 | 1117 | 100% |  
8 | 8 | 32 | 1560 | 1560 | 100% |  
8 | 8 | 64 | 1788 | 1788 | 100% |  
8 | 8 | 128 | 1920 | 1920 | 100% |  
8 | 8 | 256 | 1963 | 1963 | 100% |  
8 | 8 | 512 | 1985 | 1985 | 100% |  
8 | 8 | 1024 | 1994 | 1994 | 100% |  
8 | 8 | 2048 | 2002 | 2002 | 100% | Best performance
8 | 8 | 4096 | 2002 | 2002 | 100% |  
8 | 8 | 8192 | 1998 | 1998 | 100% |  
8 | 16 | 256 | 1916 | 1916 | 100% |  
8 | 32 | 256 | 1312 | 1312 | 100% |  
8 | 64 | 256 | 1342 | 1342 | 100% |  
8 | 128 | 256 | 1344 | 1344 | 100% |  
16 | not used | not used | 0 | 2000 | 0% |  
16 | 16 | 256 | 1754 | 1754 | 100% |  
16 | 16 | 512 | 1860 | 1860 | 100% |  
16 | 16 | 1024 | 1900 | 1900 | 100% |  
32 | not used | not used | 0 | 1989 | 0% |  
32 | 32 | 256 | 1658 | 1658 | 100% |  
32 | 32 | 512 | 1712 | 1712 | 100% |  
32 | 32 | 1024 | 1734 | 1734 | 100% |  
32 | 32 | 2048 | 1741 | 1741 | 100% |  
64 | not used | not used | 0 | 1992 | 0% |  
64 | 64 | 256 | 1370 | 1370 | 100% |  
64 | 64 | 512 | 1434 | 1434 | 100% |  
64 | 64 | 1024 | 1490 | 1490 | 100% |  
64 | 64 | 2048 | 1510 | 1510 | 100% |  
64 | 64 | 4096 | 1528 | 1528 | 100% |  
64 | 64 | 8192 | 1443 | 1443 | 100% |  
128 | not used | not used | 0 | 1978 | 0% |  
128 | 128 | 2048 | 1182 | 1182 | 100% |  
128 | 128 | 4096 | 1188 | 1188 | 100% |  
128 | 128 | 8192 | 1138 | 1138 | 100% |  

</div><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For iodepth greater than 1 the obvious verify_backlog setting of 8 results in less than 100% verification of the writes!</p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For iodepth=8 the verify_backlog value needed to be increased to 64 to get 100% verification of the writes. At this setting the performance was highly variable.</p><p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I then tried the verify_backlog_batch parameter. With iodepth=8 and verify_backlog=8, a verify_backlog_batch value of 16 achieved 100% verification. However, the best performance was achieved when the verify_backlog_batch value was increased to 2048. The behavior of the verify_backlog_batch parameter did not match the description in the FIO documentation.</p>
</body>
</html>

**Comment by kawasaki** [comment]
This issue looks same as #1515. PR #1514 is the fix candidate for #1515. I confirmed the PR avoids the weird numbers of this issue #1492. I suggest to label this issue as "duplicated".

**Comment by george-eldridge** [comment]
I have confirmed that PR #1514 does fix this issue. I will close this issue as duplicated.
