### ISSUE TITLE
fio can not parse allow_mounted_write

### ISSUE THREAD

**Issue by FunkyGod** [axboe/fio#1494]
can not parse allow_mounted_write
# fio -direct=1 -iodepth=32 -rw=write -ioengine=libaio -bs=1024k -size=100G -numjobs=1 -runtime=600 -group_reporting -filename=/dev/sda5 -allow_mounted_write=true -name=write1
fio: failed parsing allow_mounted_write=true

**Comment by FunkyGod** [comment]
fio -v
fio-3.33

**Comment by vincentkfu** [comment]
Try `allow_mounted_write=1`
