### ISSUE TITLE
ioengine sg unable to successfully execute read capacity to get block size and maximum lba

### ISSUE THREAD

**Issue by ningqingqing** [axboe/fio#1495]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<We want to do random write with sg ioengine, but got an error shows sg unable to successfully execute read capacity to get block size and maximum lba>

**Environment**: <linux, CentOS>

**fio version**: <FIO3.29>

**Reproduction steps**
<Run FIO test with this command: fio --name=4K_rand_write_qd128 --rw=randwrite --direct=1 --iodepth=128 --blocksize=131072 --ioengine=sg --filename=/dev/nvme0n1 --sg_write_mode=write --numjobs=1 --refill_buffers --norandommap --randrepeat=0 --rwmixread=0 --group_reporting --writefua=0 --size=100000000 --thread --log_avg_msec=500 --write_bw_log=bw_log
We got error message shows: ioengine sg unable to successfully execute read capacity to get block size and maximum lba
file:engines/sg.c:1241, func=fio_sgio_read_capacity, error=Success>

**Comment by vincentkfu** [comment]
The sg ioengine tries to use the SG_IO IOCTL to read the capacity of the specified NVMe device. This returns an ENOTTY (Inappropriate IOCTL for device) because an NVMe device is not a SCSI device.

I don't think there is a bug here. Why are you trying to use SCSI commands to access an NVMe device?

**Comment by ningqingqing** [comment]
We want send write operations include the force unit access(fua), so we need to use the writefua parameter, and the information we get is that writefua is only available in sg ioengine. That's why we use sg ioengine.
Since the sg engine is not available on NVMe devices, do you know how to send writefua command on NVMe devices?

**Comment by ankit-sam** [comment]
Hi @ningqingqing currently there is no way to send write with fua bit set. But I believe it can be done easily, just use the io_uring_cmd engine and modify the nvme command creation part.

`https://github.com/axboe/fio/blob/master/engines/nvme.c#L8`

You can update it and send any read/write passthrough command. You just need to use the nvme character device node (/dev/ngXnY)
I don't see any way to do this with block device.

**Comment by ningqingqing** [comment]
Thank you very much.
