### ISSUE TITLE
Limitations with sequential read for 1 FIO process.

### ISSUE THREAD

**Issue by vbienf** [axboe/fio#1496]
**Please acknowledge the following before creating a ticket**

- [* ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
When I ran 1 FIO I can't reach maximum performance with all my SSDs, but if I run 2 FIO process in parallel - it works. 

Is it limitation of FIO or something else?

**Environment**: 
OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.8.0-50-generic x86_64)
CPU: Intel(R) Xeon(R) Platinum 8368 (38 cores, 76 threads)
SSDs: 8x Samsung PM9A3 Gen4. Sequential read from spec = 6.9GB/s. Expected number from 8 ssds = 55.2 GB/s

**fio version**: 
fio-3.29-70-gb65c1 (not last, but I didn't find in release notes what can improve this)

**Reproduction steps**
1. Sequential write to 8 ssds: 
`sudo -E fio --random_generator=tausworthe64 --per_job_logs=0 --buffer_compress_chunk=4096 --rw=write --size=1000g --ramp_time=0 --ioengine=libaio --buffer_compress_percentage=67 --refill_buffers=1 --randrepeat=0 --norandommap=1 --name=write_jobs_1_iod_32_bs_1024kb --direct=1 --group_reporting=1 --filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1:/dev/nvme5n1:/dev/nvme6n1:/dev/nvme7n1:/dev/nvme8n1 --runtime=0 --iodepth=32 --numjobs=1 --bs=1024kb`
2. Sequential read from 8 SSDs:
`sudo -E /home/pliops/workspace/fio//fio --random_generator=tausworthe64 --per_job_logs=0 --buffer_compress_chunk=4096 --size=1000g --ramp_time=0 --ioengine=libaio --buffer_compress_percentage=67 --refill_buffers=1 --randrepeat=0 --norandommap=1 --name=read_jobs_76_iod_4_bs_128kb --direct=1 --group_reporting=1 --filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1:/dev/nvme5n1:/dev/nvme6n1:/dev/nvme7n1:/dev/nvme8n1 --runtime=100 --time_based=1 --cpus_allowed_policy=split --rw=read --iodepth=4 --numjobs=76 --bs=128kb`
Total BW = **46.4GB/s**
2. Sequential read from 8 SSDs, but with 2 FIO in parralel:
`sudo -E /home/pliops/workspace/fio//fio --random_generator=tausworthe64 --per_job_logs=0 --buffer_compress_chunk=4096 --size=1000g --ramp_time=0 --ioengine=libaio --buffer_compress_percentage=67 --refill_buffers=1 --randrepeat=0 --norandommap=1 --name=read_jobs_38_iod_4_bs_128kb --direct=1 --group_reporting=1 --filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1 --runtime=100 --time_based=1 --cpus_allowed_policy=split --rw=read --iodepth=4 --numjobs=38 --bs=128kb`
`sudo -E /home/pliops/workspace/fio//fio --random_generator=tausworthe64 --per_job_logs=0 --buffer_compress_chunk=4096 --size=1000g --ramp_time=0 --ioengine=libaio --buffer_compress_percentage=67 --refill_buffers=1 --randrepeat=0 --norandommap=1 --name=read_jobs_38_iod_4_bs_128kb --direct=1 --group_reporting=1 --filename=/dev/nvme5n1:/dev/nvme6n1:/dev/nvme7n1:/dev/nvme8n1 --runtime=100 --time_based=1 --cpus_allowed_policy=split --rw=read --iodepth=4 --numjobs=38 --bs=128kb`
Total BW = **28.0GB/s+28.0GB/s (56.0GB/s )**

**Comment by vincentkfu** [comment]
I recommend that you have a single job for each device to maximize throughput. With

```
filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1:/dev/nvme5n1:/dev/nvme6n1:/dev/nvme7n1:/dev/nvme8n1
```

fio is accessing files in a [round robin fashion](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-file-service-type). So by the time fio is accessing `nvme8n1` the operation on `nvme0n1` has long been completed. I would use a job file such as:


```
[global]
rw=write
size=1000G
# other options common across all jobs here
...

[nvme0n1]
filename=/dev/nvme0n1

[nvme1n1]
filename=/dev/nvme1n1

...

[nvme8n1]
filename=/dev/nvme8n1
```

Also for jobs 2 and 3 you have `numjobs=76` and `numjobs=38` respectively. These options direct fio to create the specified number of identical fio jobs and run all of them in parallel. So for job 2 you will have 76 fio jobs that each read LBA 0 `/dev/nvme0n1` and then read LBA 0 from `/dev/nvme1n1` and so on. I think this is not your intention. You can run fio with `--debug=io` or enable `--log_offset=1 --write_bw_log=test` to better see what fio is doing.

**Comment by vbienf** [comment]
Hi @vincentkfu ! Thank you for answering me! I'm using this `filename=/dev/nvme0n1:/dev/nvme1n1:...` exactly to simulate "round robin"-raid behavior. I have run my test with 1 FIO after rebooting and then it worked! So, in my case it was something like server issue, not FIO. I will close this issue, because the problem is solved by reboot.
