### ISSUE TITLE
Cannot verify

### ISSUE THREAD

**Issue by andreas-gruenbacher** [axboe/fio#15]
I'm getting totally weird results when trying to verify the contents of a file. My job file, test.fio, is based on examples/surface-scan.fio:

[global]
thread
bs=64k
direct=1
ioengine=sync
verify=meta
verify_pattern=0xaaff
verify_interval=512
size=1m

[write]
filename=test.tmp
rw=write
do_verify=0

[verify]
stonewall
create_serialize=0
filename=test.tmp
rw=read
do_verify=1
continue_on_error=verify

I do this:
(1) Run "fio test.fio"; everything works as expected.
(2) Run "fio --section=write test.fio"; also good.
(3) Run "fio --section=verify test.fio"; also good.
(4) Overwrite a block in the middle of the file:
  "dd if=/dev/zero of=test.tmp bs=512 seek=123 count=1"
(5) Run "fio --section=verify test.fio". Fio then says the following:

verify: Laying out IO file(s) (1 file(s) / 1MB)
verify: bad magic header 5cda, wanted acca at file test.tmp offset 0, length 47328155
verify: bad magic header c468, wanted acca at file test.tmp offset 65536, length 428267661
verify: bad magic header c381, wanted acca at file test.tmp offset 131072, length 353269872
verify: bad magic header 9ece, wanted acca at file test.tmp offset 196608, length 474993625
verify: bad magic header bae6, wanted acca at file test.tmp offset 262144, length 400783196
verify: bad magic header a6a8, wanted acca at file test.tmp offset 327680, length 312186069
verify: bad magic header aa25, wanted acca at file test.tmp offset 393216, length 314692932
verify: bad magic header c9c5, wanted acca at file test.tmp offset 458752, length 193190200
verify: bad magic header a39d, wanted acca at file test.tmp offset 524288, length 476001395
verify: bad magic header 79c2, wanted acca at file test.tmp offset 589824, length 431042360
verify: bad magic header e4c7, wanted acca at file test.tmp offset 655360, length 458333336
verify: bad magic header 3613, wanted acca at file test.tmp offset 720896, length 426215106
verify: bad magic header a51d, wanted acca at file test.tmp offset 786432, length 336098467
verify: bad magic header d2cb, wanted acca at file test.tmp offset 851968, length 57784921
verify: bad magic header 1468, wanted acca at file test.tmp offset 917504, length 496321165
verify: bad magic header 97c2, wanted acca at file test.tmp offset 983040, length 131846904
- Why does fio decide to regenerate "test.tmp" in this case? Can I prevent it from doing that?
- Why does  the file end up containing seemingly random garbage when the verify pattern should be a different one?
- The reported verify block lengths are random garbage. (The offsets are only meaningful "by accident".) It seems that inside verify_io_u(), hdr_inc should be used instead of hdr->len in most places. The pattern seems to repeat in other places too, though.

Thanks!

**Comment by sitsofe** [comment]
> Hmm, and what's the relationship between "buffer_pattern" and "verify_pattern" in job descriptions?

With recent fio versions `buffer_pattern` controls the default contents of a block even when verification is not used but a verification header is still written when using most `verify=` options (such as `verify=crc32c`). `verify=pattern verify_pattern=0xff` says there should be NO verification header and the entire block should consist only of the pattern 0xff (which is useful when verifying data from other tools). They also support different syntaxes (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-buffer-pattern , http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-pattern and the pattern section of http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify ).

**Comment by andreas-gruenbacher** [comment]
Well, let's assume that this issue has been resolved then.
