### ISSUE TITLE
Where is the testing files written to when the -filename option is /dev/devicename

### ISSUE THREAD

**Issue by crystaldust** [axboe/fio#150]
I'm using fio by specifying -filename option to /dev/sda1, while the file size is much bigger thant the spare disk space, so after testing I got my disk full, now I want to delete the testing files, but just can't figure out where the file is written to, how could I deal with this problem?

**Comment by axboe** [comment]
If you run with filename=/dev/sda1, then fio writes (or reads) directly to the device. It doesn't use files or the file system. If the device was mounted and you had writes in your workload, you may be in trouble with data corruption on that device... Newer versions of fio detect and warn about this, however.

**Comment by crystaldust** [comment]
Yes, too true, I did this and got my grub2 broken, very hard to fix it, but I'm lucky that this is in a virtual box machine, data is still there and I can take it back.
