### ISSUE TITLE
Segmentation fault when verify_pattern string has multiple elements

### ISSUE THREAD

**Issue by horshack-dpreview** [axboe/fio#1500]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Segmentation fault whenever a multi-part pattern is specified via the verify_pattern option

**Environment**: Ubuntu 22.04.1 LTS

**fio version**: 3.33-68

**Reproduction steps**
Any invocation that includes a multi-part pattern specification. Examples:
`-verify_pattern=0x110x22`
`-verify_pattern=%o0x11`

**Root Cause**
I'm not presently set up to do pull requests so I'm describing the issue and fix here:

`pattern.c:parse_and_fill_pattern` is called with `out=NULL` to calculate the length of the pattern. All the parse_* routines called by `parse_and_fill_pattern` accept an `out=NULL` to signify same but `parse_and_fill_pattern` is incrementing `out` during this calculation invocation, causing its value to be `NULL`+\<running calculated pattern length\>. The fix is to only increment `out` if its not-NULL:
```
                assert(filled);
                assert(filled <= out_len);
		out_len -= filled;
                if (out)
                    out += filled;
                total += filled;
	} while (in_len);
```

**Comment by vincentkfu** [comment]
Thanks for reporting this and providing a fix.
