### ISSUE TITLE
randrepeat is not overridden by randseed flag when FIO_RAND_BLOCK_OFF is initialized.

### ISSUE THREAD

**Issue by freeeborn** [axboe/fio#1502]
fixup_options has following code:

         /*
	 * If randseed is set, that overrides randrepeat
	 */
         if (fio_option_is_set(o, rand_seed))
		o->rand_repeatable = 0;

https://github.com/axboe/fio/blob/7cbbc6459d9b5f9d687ab55ef5bfe3ae86a99d05/init.c#L929

However, random seeds are initialized before fixup:

	if (setup_random_seeds(td)) {
		td_verror(td, errno, "setup_random_seeds");
		goto err;
	}

	if (fixup_options(td))
		goto err;

https://github.com/axboe/fio/blob/7cbbc6459d9b5f9d687ab55ef5bfe3ae86a99d05/init.c#L1536

this causes --randseed to be ignored for block offsets unless --randrepeat=0 is also specified

if (td->o.rand_repeatable)
		td->rand_seeds[FIO_RAND_BLOCK_OFF] = FIO_RANDSEED * td->thread_number;

https://github.com/axboe/fio/blob/7cbbc6459d9b5f9d687ab55ef5bfe3ae86a99d05/init.c#L1068

which causes sequence of block offsets for loads with randwrite and io_size does not depend on randseed.

**Comment by vincentkfu** [comment]
The description for `randseed` says that it overrides `randrepeat`. So you have correctly identified a bug. Can you confirm that calling `fixup_options()` before seeding the random number generators resolves the issue?

https://github.com/vincentkfu/fio/tree/1502

The random number seed code would benefit from some cleanups and it seems as if `allrandrepeat` overrides both `randseed` and `randrepeat` although this is not documented.
