### ISSUE TITLE
PMDK dev-dax/libpmem engine no longer compiled on the latest fio

### ISSUE THREAD

**Issue by yizhanglinux** [axboe/fio#1523]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
PMDK dev-dax/libpmem engine no longer compiling on the latest fio

**Environment**: 
latest fio which includes pmemblk remove patch

**fio version**: 

**Reproduction steps**
./configure
```
latest fio:
libpmem                       yes
libpmem1_5                    yes
libpmem2                      no
PMDK dev-dax engine           no
PMDK libpmem engine           no

fio w/o pmemblk remove patch:
libpmem                       yes
libpmem1_5                    yes
libpmem2                      no
libpmemblk                    yes
PMDK pmemblk engine           yes
PMDK dev-dax engine           yes
PMDK libpmem engine           yes
```
PMDK pmemblk engine was removed, that should be expected. But PMDK dev-dax/libpmem engine no longer compiled during configure? Or did I miss some steps?

**Comment by vincentkfu** [comment]
Thanks for reporting the issue. Please try this branch: https://github.com/vincentkfu/fio/commits/1523

**Comment by yizhanglinux** [comment]
> Thanks for reporting the issue. Please try this branch: https://github.com/vincentkfu/fio/commits/1523

Yeah, works now, thanks for the quick fix.
```
libpmem                       yes
libpmem1_5                    yes
libpmem2                      no
PMDK dev-dax engine           yes
PMDK libpmem engine           yes
```
Feel free to add:
Tested-by: Yi Zhang <yi.zhang@redhat.com>
