### ISSUE TITLE
Skip layout files?

### ISSUE THREAD

**Issue by FDUdannychen** [axboe/fio#1533]
FIO spends a long time on layout files, even they are created, there should be an option that tells FIO to skip this step. The file names are confirmed /dir1/files-64k/file-64k-{0 to 1799999}, and the file size is 64k. FIO checks all the files before starting the real test.

[global]
do_verify=0
iodepth=64
rw=randwrite
time_based=1
runtime=24h
allow_file_create=0
create_on_open=1
create_serialize=0
file_service_type=random:16
directory=/dir1

[filesize-64k-block-4k-iops-72]
filename_format=files-64k/file-64k-$filenum
filesize=64k
nrfiles=1800000
bs=4k
rate_iops=72

**Comment by horshack-dpreview** [comment]
Looking at the source, the only pre-workload activity fio performs on the files for your test config is to obtain all the file sizes, which it does to initialize some internal test parameters. How long is that taking on the 1,800,000 files in your config?

**Comment by FDUdannychen** [comment]
@horshack-dpreview It can't be completed in 3+ days, then I kill the process. It's slow because the test is targeting a SMB directory on remote server. I understand that FIO needs to obtain all the file sizes to initialize the test, however all the file sizes are given in the config file, this step can be optimized. I wonder if there is a possible way.

**Comment by axboe** [comment]
It would be possible to add a switch for this, if the file size is already given in the job file. Or maybe just gauge it on the other options, eg you have create_on_open here, so really should be no need to iterate and stat. Worst case is that the open will fail and fio will abort, but if that happens in the check phase or when the job runs, doesn't seem like a massive difference.

**Comment by Gt3pccb** [comment]
@FDUdannychen I suffer the same pain for read tests. The "way around" is to do a sequential write job and unlink=0. with 1MB IOs it is a **lot faster** than letting FIO to lay the files. Then use the opendir for your read test.

**Be aware that FIO is not consistent with the directory syntax.  For writes directory=e\:\dir1 for opendir=e:\dir1**
I have asked Vincent to fix the directory syntax so it is consistent across all the directory functions.
