### ISSUE TITLE
Oversimplified data pattern of "buffer_compress_percentage" make compressor throughput unrealistic

### ISSUE THREAD

**Issue by taovcu** [axboe/fio#1539]
**The limitation of "buffer_compress_percentage"**

I'm using fio with "buffer_compress_percentage" parameter to evaluate our storage system with compressor integrated. I noticed that if this parameter is set, then fio will attempt to provide I/O buffer content (on WRITEs) by providing a mix of random data followed by zeros in default. "Random data + zeros" will dramatically simplify the compressor behavior, making the system throughput unrealistic. 

**A potential solution to resolve the limitation**

We can simply chunk (e.g. in 8 bytes) and shuffle the "Random data + zeros" to make the pattern more realistic, and trigger the compressor's regular processing logic. 

Do you guys think this potential change of fio source code make sense? Thanks.

**Comment by arainchik** [comment]
You can use `buffer_pattern=0xdeadcafe`or `buffer_pattern='filename'` to avoid zero-filled pattern when using `buffer_compress_percentage`:

From fio manpage:
```
buffer_compress_percentage=int
              If this is set, then fio will attempt to provide I/O buffer con‐
              tent (on WRITEs) that compresses to  the  specified  level.  Fio
              does  this  by  providing a mix of random data followed by fixed
              pattern data. The fixed pattern is either zeros, or the  pattern
              specified  by  buffer_pattern. 
```

**Comment by anandvishes** [comment]
Hi, 

I am trying to pass a text file to --buffer_pattern,
fio --name=mytest --rw=randwrite --ioengine=libaio --bs=4k --size=1G --buffer_pattern='random_hexcode.txt' --filename=/pool1/fs1/test.dat

I am getting the below error.
fio: failed parsing buffer_pattern=random_hexcode.txt

[root@ixa00396852_023 temp]# cat random_hexcode.txt
0xabcde.

Can someone help me on this?

TIA
