### ISSUE TITLE
fio-2.7 fails to build on SuperH

### ISSUE THREAD

**Issue by tpetazzoni** [axboe/fio#154]
It fails with the following error messages. This is due to the fact that t/stest (and various other tests) use gettime.o and mutex.o, which rely on macros defined in arch-<architecture>.h. Those macros use the arch_flags variable, but it is only available when libfio.o is linked into the code, and this is not the case for those tests.

gettime.o: In function `fio_gettime':
/home/thomas/projets/buildroot/output/build/fio-fio-2.7/gettime.c:163: undefined reference to `arch_flags'
gettime.o: In function `utime_since_now':
/home/thomas/projets/buildroot/output/build/fio-fio-2.7/gettime.c:164: undefined reference to `arch_flags'
gettime.o: In function `mtime_since_now':
/home/thomas/projets/buildroot/output/build/fio-fio-2.7/gettime.c:164: undefined reference to `arch_flags'
gettime.o: In function `time_since_now':
/home/thomas/projets/buildroot/output/build/fio-fio-2.7/gettime.c:164: undefined reference to `arch_flags'
mutex.o: In function `fio_mutex_up':
/home/thomas/projets/buildroot/output/build/fio-fio-2.7/mutex.c:189: undefined reference to `arch_flags'
collect2: error: ld returned 1 exit status
Makefile:375: recipe for target 't/stest' failed
make[2]: *** [t/stest] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=71471cb1d05f3877c8fb935fbf70a6bae789ac49

This should fix it, I have committed it. Can you give it a go?

**Comment by tpetazzoni** [comment]
Builds fine, thanks!

**Comment by axboe** [comment]
Great, thanks for reporting! That must have been broken for a while, so good to get it fixed.
