### ISSUE TITLE
Bandwidth reported changed considerably after upgrade to the latest version from 3.16

### ISSUE THREAD

**Issue by manojisnow** [axboe/fio#1553]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Testing a storage device using fio with the config below. But the bandwidth reported by 3.34(~2500KiB/S) is very different from what was reported with 3.16(~12000KiB/s) . I would like to understand the way the calculation was done in the 2 different versions, and if there is anything that changed that is causing this difference.  

**Environment**:  SUSE Linux Enterprise Server 15 SP4

**fio version**: 3.34

**Reproduction steps**
Below is the config used on both the versions

fio --name=test --directory=/path/to/the/directory --bs=20k --create_on_open=1 --direct=1 --fallocate=native --filesize=20k --ioengine=libaio --nrfiles=50000 --numjobs=1 --openfiles=1 --rw=write --fsync_on_close=1

**Comment by axboe** [comment]
I did your homework for you, it was literally 5 min to run through fio-3.16 until current master. This is the commit it flagged:

```
commit 4ef1562a013513fd0a0048cca4048f28d308a90f
Author: Adam Kupczyk <akupczyk@redhat.com>
Date:   Mon Dec 28 14:55:17 2020 +0100

    io_u: Fix bad interaction with --openfiles and non-sequential file selection poli
cy
```

which does look like a good fix. The older versions were buggy and ended up just using the same file, rather than alternate service between them. You cannot trust the bandwidth of the older broken versions.

**Comment by manojisnow** [comment]
Thanks for shedding light!
