### ISSUE TITLE
r/w stat runtime Extremely large

### ISSUE THREAD

**Issue by Dragonchang** [axboe/fio#1558]
**Please acknowledge the following before creating a ticket**

- [ ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
r/w stat runtime Extremely large
read: IOPS=0, BW=0B/s (0B/s)(8046MiB/15372283518324msec)

**Environment**: 
Linux version 5.8.0-25-generic (buildd@lcy01-amd64-022) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1) #26-Ubuntu SMP Thu Oct 15 10:30:38 UTC 2020

[sda5_mixrw-w70_1024k_result3.log](https://github.com/axboe/fio/files/11238733/sda5_mixrw-w70_1024k_result3.log)

**fio version**: 
fio-3.33

**Reproduction steps**

**Comment by Dragonchang** [comment]
read: IOPS=0, BW=0B/s (0B/s)(8046MiB/15372283518324msec)

**Comment by vincentkfu** [comment]
Please follow the instructions here: https://github.com/axboe/fio/blob/master/REPORTING-BUGS
