### ISSUE TITLE
Not able to force a data verify failure with verify_backlog and bs=4k

### ISSUE THREAD

**Issue by craigman87** [axboe/fio#1566]
**Please acknowledge you have done the following before creating a ticket**

- [ X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

1) A description of what you think the bug is
I am intentionally executing 8 separate fio processes with verify_backlog enabled with the expectation of hitting a data verification failure in fio. However, if I use a blocksize of 4kb then all data verify checks pass. 

2) Environment (e.g. Linux distro version, kernel version). This is mostly needed if it's a build bug.
Amazon Linux (4.14.311-233.529.amzn2.x86_64) 

3) How to reproduce. Please include a full list of the parameters
 
My fio job file
```
[global]
buffered=0
direct=1
group_reporting
verify_dump=1
ioengine=libaio
serialize_overlap=1
disable_clat=1
overwrite=1
size=32k
verify=crc32
disable_slat=1
do_verify=1
randrepeat=0
time_based
disable_lat=1
continue_on_error=read
runtime=10s
verify_fatal=1
verify_backlog=10

[fio_job]
rw=randwrite
filename=/dev/nvme1n1
numjobs=1
bs=4k
refill_buffers=1
iodepth=32
```

I execute 8 processes that use same fio job targeting the same device handle. I expect the 8 fio processes to overwrite each other and force data verify failures.  
`sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out2.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out3.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out4.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out5.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out6.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out7.log & sudo ./fio fio.cfg --runtime=1m 2>&1 | tee out8.log`

I expect fio to fail with data verification errors as I have 8 different processes executing 4k writes to a 32k disk space. If I set bs=8k instead of bs=4k then I do hit a data verification failures. Furthermore, if I use bssplit (bssplit=512/1:1024/1:1536/1:2048/1:2560/1:3072/1:3584/1:4k/1:8k/1:16k/1:32k/1:64k/1:128k/88) then I do not see data verify failures. 

Tested on different fio versions 3.6, 3.2, 3.21, 3.8, 2.1.10. Did not see any difference when using different fio versions. 

I am sure I am doing something wrong, but I can't figure out what :)

**Comment by vincentkfu** [comment]
I've yet to do a deep dive into the verify code but the evidence suggests that the data needed to verify a block is contained within that block. So if one fio job tries to verify data written by another one, it will pass because the checksum is still correct.

If you really want to trigger verify failures, have the first job use "0" for its write, the second job use "1" for its writes, etc using options like the following:

```
buffer_pattern="0"
verify_pattern="0"
verify=pattern
```

Also try running with `--debug=io,verify` to gain a little more insight into what is happening.
