### ISSUE TITLE
FIO crashes with Signal 11 (SIGSEGV) when trying to read_iolog using version 3

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#1567]
**Please acknowledge the following before creating a ticket**

- [X ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

**Environment**: 
$ cat /etc/redhat-release
Fedora release 34 (Thirty Four)

**fio version**: 
$ fio --version
fio-3.34

**Reproduction steps**
FIO crashes when trying to read_iolog using version 3. 
Steps: 
1) compile the latest FIO v3.34
2) run fio with the below input parameters 

$ cat test.fio
[read-test]
ioengine=sync
read_iolog=trace.log
replay_redirect=/dev/nvme0n1

$ cat trace.log
fio version 3 iolog
100 /dev/nvme0n1 read 1000 4096

$ fio test.fio
read-test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=sync, iodepth=1
fio-3.34
Starting 1 process
fio: pid=244252, got signal=11

**Comment by vincentkfu** [comment]
Fio should probably fail more gracefully but the iolog needs lines to add the file and open the file before the read command.

The trace file format v2 documentation says:

```
The filename is given as an absolute path, and has to have been added and opened before it can be used with this format.
```

https://fio.readthedocs.io/en/latest/fio_doc.html#trace-file-format
