### ISSUE TITLE
Reboot after configuring FIO leads to kernel corruption

### ISSUE THREAD

**Issue by priyama2** [axboe/fio#1569]
Please acknowledge the following before creating a ticket

    [X ] I have read the GitHub issues section of [REPORTING-BUGS](https://github.com/axboe/fio/blob/master/REPORTING-BUGS).

**Description of the bug:**
When partition is rebooted after ./configure of FIO setup, the kernel disk gets corrupted and does boot up properly.

**Environment**: 
arch: ppc64le
```
root@abcd52:~ cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
```

**fio version**: 
```
 fio --version
fio-3.34
```

**Reproduction steps**
- download fio
- compile the latest FIOv3.34
`./configure ; make; make install ; reboot`
- Boot image gets lost after fio setup

**Comment by axboe** [comment]
There's no way this is a fio issue.
