### ISSUE TITLE
​ refill_buffers option seems to be broken

### ISSUE THREAD

**Issue by andihit** [axboe/fio#157]
​It seems that the refill_buffers option is broken with fio 2.8.
I tried the same job file as in http://www.spinics.net/lists/fio/msg00878.html
```
[foo0]
rate=,200k
rw=write
refill_buffers=1
size=4m

[foo1]
rate=,200k
rw=write
refill_buffers=1
size=4m
```
and get the same outcome as in the cited bugreport (which should be fixed now according to the message) - the generates test files are identical.

Or did the meaning of the parameter change? Any hints?

Greetings,
Andreas

**Comment by axboe** [comment]
The option works in that it re-generates the buffer content every time. If you don't set randrepeat=0, then it will be seeded identically every time.

That said, we probably should seed them identically (but differently) by default. Should work with this commit:

http://git.kernel.dk/cgit/fio/commit/?id=87a0ea3b58ef3d126148cb0279e015177ef9c62f

**Comment by andihit** [comment]
thanks for the explanation
works as expected with your commit
