### ISSUE TITLE
Results JSON output is invalid JSON when using multiple job options

### ISSUE THREAD

**Issue by justas-** [axboe/fio#1571]
I am writing a parser for fio results JSON. The "job options" value is formatted incorrectly, making some parsers to reject JSON and others to silently overwrite values. In the below output, "job options" is a dict with 4 entries having identical key.

> {
>       "jobname" : "reads0_jobs1_iodepth128",
>       "groupid" : 0,
>       "error" : 0,
>       "eta" : 0,
>       "elapsed" : 4323,
>       "job options" : {
>         "filename" : "Nvme0n1",
>         "filename" : "Nvme1n1",
>         "filename" : "Nvme2n1",
>         "filename" : "Nvme3n1"
>       },
> }

"fio version" : "fio-3.34-38-g0739"

**Comment by vincentkfu** [comment]
You can avoid this by specifying `filename=nvme0n1:nvme1n1:nvme2n1:nvme3n1`

https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename
