### ISSUE TITLE
First IO errors not reported to stderr

### ISSUE THREAD

**Issue by Scafir** [axboe/fio#1572]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
In fio/ioengines.c, some errors are reported using `log_info`, and thus never printed to the user if --output is used.
I am specifically talking about: 
https://github.com/axboe/fio/blob/638689b15af35bd746f9114a3e8895e7a983ed83/ioengines.c#L410
and
https://github.com/axboe/fio/blob/638689b15af35bd746f9114a3e8895e7a983ed83/ioengines.c#L418

Both of these occurances should probably be changed to `log_err`.

**Environment**: Alma Linux 9

**fio version**: 3.27 (but issue currently present in master's source code)

**Reproduction steps**
Not too sure how to generate it on demand.. I got it while using direct=1 on an vfat mounted sd card that was forcibly removed.

**Comment by kcoms555** [comment]
@Scafir 
I am with you. When running block io test with multiple bs, I need to parse it to make a report.
