### ISSUE TITLE
opendir fails to parse

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#1573]
Hello, fio is failing to parse --opendir=d\:\f\\1 or opendir=d\:\f\1 in Windows with the same error 
**fio: file:filesetup.c:1976, func=opendir(d\:\\F\\1), error=Unknown error**
The directory  d:\f\1 has files created by FIO using --directory=d\:\f\1 and I would like to use those files to do the read tests, instead of FIO going and generating new files.

This is the command that is failing
fio --cpus_allowed_policy=split  --bs=32K --create_on_open=0 --create_serialize=1 --description="111" --direct=1  --disable_clat=0 --disable_slat=1 --do_verify=0 --exitall_on_error --fallocate=truncate --group_reporting=1 --io_size=500gb --iodepth=16 --ioengine=windowsaio --mem=mmap --lockmem=1 --name="Test" --nice=-5 --norandommap --nrfiles=1 --offset=0 --overwrite=0 --ramp_time=20 --random_generator=lfsr --randrepeat=0 --rw=randread --runtime=30 --scramble_buffers=1 --size=600gb --sync=sync --thinktime=0 --thread --time_based --unlink=0 --no_completion_thread=1 --name="1" --clocksource=cpu --opendir=d\:\\F\\1

fio: failed parsing opendir=d\:\\F\\1
POC3-Micro7450: (g=0): rw=randread, bs=(R) 32.0KiB-32.0KiB, (W) 32.0KiB-32.0KiB, (T) 32.0KiB-32.0KiB, ioengine=windowsaio, iodepth=16
fio: file:filesetup.c:1976, func=opendir(d\:\\F\\1), error=Unknown error

Any help would be appreciated.

**Comment by vincentkfu** [comment]
Please simplify your job file to the minimum required to produce the issue. I've tried `opendir` on both Linux and Windows and it seems to work.

Why do you have `--nrfiles=1`. If I have this along with `--opendir` the job doesn't run.

**Comment by Gt3pccb** [comment]
Because there are multiple files in the directory, as I am sweeping from 1-1000 files per job, and number of jobs from 1-200 in my file system test.
even if I remove the nrfiles the job fails with the same error.

**Comment by axboe** [comment]
I believe he already is. Usually the best way to get an issue fixed is to present a way to reproduce it. Your dir structure might look different than what Vincent tested with, hence it's not reproducing for him. If you provide a way to reproduce this from scratch (assuming no directories already), then it's usually an easy fix. It's also the best way to respect the time of others, as it puts as much of the work on the reporter as possible.

**Comment by vincentkfu** [comment]
I was able to run the following two jobs without issue:

`write.fio`
```
[global]
#bs=1024k
cpus_allowed_policy=split
direct=1
disable_clat=0
disable_slat=1
do_verify=0
exitall_on_error
fallocate=truncate
group_reporting=1
iodepth=16
ioengine=windowsaio
nice=-5
no_completion_thread=1
nrfiles=10000
offset=0
overwrite=0
readwrite=write
scramble_buffers=1
#filesize=800gb
filesize=4k
thinktime=0
thread
unlink=0

[Job-POC3--1]
filename_format=POC3--1.$filenum
directory=C\:\Users\vincent.fu\temp
#directory=D:\F\1:
```

`read.fio`
```
[global]
#bs=1024k
cpus_allowed_policy=split
direct=1
disable_clat=0
disable_slat=1
do_verify=0
exitall_on_error
fallocate=truncate
group_reporting=1
iodepth=16
ioengine=windowsaio
nice=-5
no_completion_thread=1
nrfiles=10000
offset=0
overwrite=0
readwrite=write
scramble_buffers=1
#filesize=800gb
filesize=4k
thinktime=0
thread
unlink=0

[Job-POC3--1]
filename_format=POC3--1.$filenum
opendir=C:\Users\vincent.fu\temp
readwrite=read
#directory=D:\F\1:
```

```
C:\cygwin64\home\vincent.fu\1573>fio write.fio
Job-POC3--1: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=16
fio-3.35
Starting 1 thread
Job-POC3--1: Laying out IO files (10000 files / total 39MiB)
Jobs: 1 (f=314): [f(1)][100.0%][eta 00m:00s]
Job-POC3--1: (groupid=0, jobs=1): err= 0: pid=7092: Wed May 24 09:00:13 2023
  write: IOPS=2476, BW=9906KiB/s (10.1MB/s)(39.1MiB/4038msec); 0 zone resets
    clat (usec): min=10, max=30341, avg=3027.51, stdev=3491.66
     lat (usec): min=143, max=31773, avg=3193.78, stdev=3507.29
    clat percentiles (usec):
     |  1.00th=[   12],  5.00th=[   13], 10.00th=[  269], 20.00th=[  766],
     | 30.00th=[ 1270], 40.00th=[ 1745], 50.00th=[ 2212], 60.00th=[ 2671],
     | 70.00th=[ 3130], 80.00th=[ 3589], 90.00th=[ 6259], 95.00th=[12387],
     | 99.00th=[16909], 99.50th=[17433], 99.90th=[18744], 99.95th=[18744],
     | 99.99th=[20055]
   bw (  KiB/s): min= 3321, max=16000, per=99.44%, avg=9850.25, stdev=6231.87, samples=8
   iops        : min=  830, max= 4000, avg=2462.50, stdev=1558.04, samples=8
  lat (usec)   : 20=6.17%, 50=0.07%, 100=0.01%, 250=1.16%, 500=6.07%
  lat (usec)   : 750=5.74%, 1000=3.79%
  lat (msec)   : 2=22.18%, 4=41.56%, 10=6.28%, 20=6.95%, 50=0.02%
  cpu          : usr=0.00%, sys=24.77%, ctx=0, majf=0, minf=0
  IO depths    : 1=6.2%, 2=12.5%, 4=25.0%, 8=50.0%, 16=6.2%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=94.1%, 8=0.0%, 16=5.9%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10000,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=9906KiB/s (10.1MB/s), 9906KiB/s-9906KiB/s (10.1MB/s-10.1MB/s), io=39.1MiB (41.0MB), run=4038-4038msec

C:\cygwin64\home\vincent.fu\1573>fio read.fio
fio: opendir added 10000 files
Job-POC3--1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=16
fio-3.35
Starting 1 thread
Jobs: 1 (f=7477)
Job-POC3--1: (groupid=0, jobs=1): err= 0: pid=4728: Wed May 24 09:00:34 2023
  read: IOPS=7412, BW=29.0MiB/s (30.4MB/s)(39.1MiB/1349msec)
    clat (usec): min=13, max=2698, avg=1087.29, stdev=585.70
     lat (usec): min=66, max=2735, avg=1109.03, stdev=585.88
    clat percentiles (usec):
     |  1.00th=[  137],  5.00th=[  151], 10.00th=[  277], 20.00th=[  506],
     | 30.00th=[  676], 40.00th=[  898], 50.00th=[ 1074], 60.00th=[ 1287],
     | 70.00th=[ 1483], 80.00th=[ 1680], 90.00th=[ 1893], 95.00th=[ 1991],
     | 99.00th=[ 2180], 99.50th=[ 2311], 99.90th=[ 2507], 99.95th=[ 2573],
     | 99.99th=[ 2704]
   bw (  KiB/s): min=29700, max=29992, per=100.00%, avg=29846.00, stdev=206.48, samples=2
   iops        : min= 7425, max= 7498, avg=7461.50, stdev=51.62, samples=2
  lat (usec)   : 20=0.01%, 100=0.01%, 250=6.71%, 500=13.11%, 750=12.91%
  lat (usec)   : 1000=12.54%
  lat (msec)   : 2=50.07%, 4=4.64%
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=0
  IO depths    : 1=0.1%, 2=13.3%, 4=26.7%, 8=53.3%, 16=6.7%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=93.7%, 8=0.0%, 16=6.3%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=10000,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=29.0MiB/s (30.4MB/s), 29.0MiB/s-29.0MiB/s (30.4MB/s-30.4MB/s), io=39.1MiB (41.0MB), run=1349-1349msec
```

I changed the filesize, blocksize, and paths used from the job files you provided.

1. Why do you have a trailing colon in `directory=D:\F\1:` for your write job? I also had to escape the colon for the drive letter to get it to work.
2. Why do you have a trailing colon in `D:\F\n:` for your read job? This will not work. Your initial bug report did not have a trailing colon.

**Comment by Gt3pccb** [comment]
Hello @vincentkfu, I guess I am confused because the directory naming in FIO is not consistent then.
For writes you have to escape the colon 
directory=D**\:**\F\1 

but for reads you don't
opendir=d:\F\1

**Comment by Gt3pccb** [comment]
I can't think of a way other than replacing the delimiter with another character because you have a single character `:` that  has 2 functions.

I see your reasoning, but I do not think that in Windows you can tell a job to use more than one directory at the time. 
If you run something like this
`[job1]
directory=e\:\FIO1:e\:\FIO2:e\:\FIO3:
nrfiles=10000
`
It is my experience that all the files will go to FIO1 and none to FIO2 and FIO3 and that If you want to write to different directories, you must use multiple jobs.

**Comment by Gt3pccb** [comment]
@vincentkfu maybe my English is getting on my way, the request would be that a job could write to multiple directories. 

RE: opendir. If the syntax can't be consistent then, I believe that it should be on the documentation.

**Comment by vincentkfu** [comment]
> @vincentkfu maybe my English is getting on my way, the request would be that a job could write to multiple directories.

With `--directory=/tmp/1:/tmp/2 --numjobs=2` and `--filename` omitted the first job clone will use `/tmp/1` and the second job clone with use `/tmp/2`. If `--filename` is supplied all job clones will use `/tmp/1` and the provided filename.
