### ISSUE TITLE
io_uring engine ignores --fdatasync when --hipri is used

### ISSUE THREAD

**Issue by anarazel** [axboe/fio#1577]
Hi,

Kernel version: 6.2.12
fio version: c99367f1

```
fio --ioengine io_uring --time_based=1 --runtime=5  --size=4GiB --name=bla --numjobs 1\
  --buffered=0  --bs=4096  --iodepth=1 --rw=write  --fdatasync=1
```
-> 893 iops

If I add `--hipri` -> 94.9k iops.

It doesn't look to be a kernel side issue. For one --hipri results in normal numbers when using the pvsync2 engine. More conclusively
```
perf record -e io_uring:io_uring_submit_sqe -a
```
shows that FSYNC is queued without --hipri, but not when using --hipri.

Regards,

Andres

**Comment by axboe** [comment]
Pushed a patch for this. The core doesn't notice fsync errors, which is kind of worrisome by itself. For polled io_uring, you cannot mix and match polled and non-polled IO. So io_uring will -EINVAL any fsync/sync_file_range/etc. Which does mean that the job itself doesn't make sense, but fio should of course notice the error.

**Comment by anarazel** [comment]
Commit hasn't shown up on github, but after pulling from your kernel.dk repo, I can confirm that now an error is raised.

Thanks!

**Comment by axboe** [comment]
> Commit hasn't shown up on github

Commits go to git.kernel.dk, but they sync to github in 5-10 min generally.
