### ISSUE TITLE
latency_target is not preserved across multiple jobs

### ISSUE THREAD

**Issue by jaroslawr** [axboe/fio#1582]
**Please acknowledge the following before creating a ticket**

- [ X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

If you combine latency_target with numjobs the correct latency_target is applied only to first job and the remaning ones have their latency_target 1000x higher. E.g. run:

```
fio --name=test --numjobs=4 --latency_target=1s --directory=fio --size=1mb
```

In the output report you can see:

```
fio-3.35-32-g8ce9c4
Starting 4 processes
test: Laying out IO file (1 file / 1MiB)
test: Laying out IO file (1 file / 1MiB)
test: Laying out IO file (1 file / 1MiB)
test: Laying out IO file (1 file / 1MiB)

test: (groupid=0, jobs=1): err= 0: pid=164675: Tue Jun 20 18:53:39 2023
     [...]
     latency   : target=1000000000, window=0, percentile=100.00%, depth=1
test: (groupid=0, jobs=1): err= 0: pid=164676: Tue Jun 20 18:53:39 2023
     [...]
     latency   : target=1000000000000, window=0, percentile=100.00%, depth=1
test: (groupid=0, jobs=1): err= 0: pid=164677: Tue Jun 20 18:53:39 2023
     [...]
     latency   : target=1000000000000, window=0, percentile=100.00%, depth=1
test: (groupid=0, jobs=1): err= 0: pid=164678: Tue Jun 20 18:53:39 2023
     [...]
     latency   : target=1000000000000, window=0, percentile=100.00%, depth=1
```

This is because fixup_options function does this:

```
	o->latency_target *= 1000ULL;
```

fixup_options is called once for the first job, the job is then copied, and then fixup_options is called again for each copy of the job, so that the replicas end up with a 1000x higher value.

**Environment**:

Not relevant I think

**fio version**:

Current master (8ce9c4)

**Reproduction steps**

Run:
```
fio --name=test --numjobs=4 --latency_target=1s --directory=fio --size=1mb
```

**Comment by vincentkfu** [comment]
Thanks for reporting and finding the right place to fix. Please try the 1582 branch here:

https://github.com/vincentkfu/fio/tree/1582
