### ISSUE TITLE
Fio io_timeout value is not using the io_timeout from "/sys/module/nvme_core/parameter/io_timeout"

### ISSUE THREAD

**Issue by Nitheesh1609** [axboe/fio#1586]
Please acknowledge the following before creating a ticket

 I have read the GitHub issues section of [REPORTING-BUGS](https://github.com/axboe/fio/blob/master/REPORTING-BUGS).
I am using fio to test a workload on a SSD. When I change the io_timeout value in the “/sys/module/nvme_core/parameter/io_timeout”, it is not reflected in the output of fio. Even when the latency is higher than the io_timeout value, it does not produce any io_timeout. Only when I specify the “—max_latency”, I am able to see io_timeout in the terminal but it is not getting registered on the dmesg. Does fio use the io_timeout from “/sys/module/nvme_core/parameter/io_timeout” and does fio convey the timout to nvme?

[Not able to email the mailinglist]

**Comment by vincentkfu** [comment]
Fio is a userspace application that uses ioengines to submit requests to many different types of devices and files. `io_timeout` is a module parameter associated with the Linux nvme driver. I would expect to see an I/O error reported by the nvme driver and propagated to fio through the ioengine if an I/O request submitted by fio exceeded the timeout. However, fio has no ioengine that directly inspects or uses the nvme driver's `io_timeout` parameter.
For the `--max_latency` option fio keeps tracks of the submission and completion times for each I/O. If the latency for an I/O exceeds the specified threshold then fio will stop the job. There is no direct connection between fio's `--max_latency` parameter and the NVMe driver's `io_timeout` parameter.
