### ISSUE TITLE
fio: rdma_create_event_channel fail

### ISSUE THREAD

**Issue by rldleblanc** [axboe/fio#159]
When trying to use the RDMA engine and the example job for the server with the port set to an arbitrary value I get:

# /home/rleblanc/fio/fio /home/rleblanc/fio/examples/rdmaio-server.fio 
receiver: (g=0): rw=read, bs=1M-1M/1M-1M/1M-1M, ioengine=rdma, iodepth=16
fio-2.8-14-g23a8
Starting 1 process
fio: rdma_create_event_channel fail
fio: io engine init failed. Perhaps try reducing io depth?
fio: pid=18588, err=1/

Setting I/O depth=1 only removed the corresponding message from the output.
# uname -r
4.1.15.bs.ufd

# rpm -qa | grep -E "ibverbs|rdmacm"
libibverbs-devel-1.1.8-8.el7.x86_64
librdmacm-1.0.21-1.el7.x86_64
libibverbs-1.1.8-8.el7.x86_64
librdmacm-devel-1.0.21-1.el7.x86_64

I'm not sure what is wrong as this is the first time I've tried using the RDMA engine.

**Comment by axboe** [comment]
Send this to the fio mailing list, so that more people will see it. I'm not that familiar with how the rdma stuff works.

**Comment by rldleblanc** [comment]
Didn't have the proper user-land libraries installed.
