### ISSUE TITLE
Cannot read input file for "--buffer_pattern"

### ISSUE THREAD

**Issue by anandvishes** [axboe/fio#1595]
Hi,

I am trying to pass a text file to --buffer_pattern,
fio --name=mytest --rw=randwrite --ioengine=libaio --bs=4k --size=1G --buffer_pattern='random_hexcode.txt' --filename=/pool1/fs1/test.dat

I am getting the below error.
fio: failed parsing buffer_pattern=random_hexcode.txt

Contents of the file:
[root@ixa00396852_023 temp]# cat random_hexcode.txt
0xabcde.

The above command works if I pass 0xabcde directly to --buffer_pattern 

TIA

**Comment by vincentkfu** [comment]
Is your shell stripping out the single quotes? In a job file `buffer_pattern='random_hexcode.txt'` works but if you're using single quotes on the command line try something like `"--buffer_pattern='random_hexcode.txt'"`
