### ISSUE TITLE
fio double free detected, never terminates, uses 100% CPU and impossible to kill even with kill -9

### ISSUE THREAD

**Issue by 1f604** [axboe/fio#1598]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

I ran fio with `--hipri=1` and it was taking so long (without `hipri=1` it only takes 3 seconds, now it was taking minutes) so I tried to kill it with Ctrl-C, didn't work, so I opened another terminal and tried to kill it with `kill -9` and that didn't work either. 

At the end it "finished" running with the message:

      free(): double free detected in tcache 2
      Aborted

But it actually didn't finish running! `top` reports that it's still running and using 100% CPU. And it is impossible for me to kill it!

I've attached my full terminal output at the end.

**Environment**: 

Debian 12 - literally just the default install with the most minimal options. No disk encryption.

**fio version**:

This bug occurred on both 3.33 and 3.35 (the latest version).

**Reproduction steps**

`fio --name TEST --eta-newline=5s --filename=temp.file --rw=read --size=2g --io_size=10g --blocksize=1024k --ioengine=io_uring --fsync=10000 --iodepth=64 --direct=1 --numjobs=1 --runtime=60 --group_reporting --hipri=1`

**Full terminal output**

Here is my terminal output showing the exact command I used:

```
$ fio --name TEST --eta-newline=5s --filename=temp.file --rw=read --size=2g --io_size=10g --blocksize=1024k --ioengine=io_uring --fsync=10000 --iodepth=64 --direct=1 --numjobs=1 --runtime=60 --group_reporting --hipri=1
TEST: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=io_uring, iodepth=64
fio-3.35
Starting 1 process
Jobs: 1 (f=1): [R(1)][11.7%][eta 00m:53s]
Jobs: 1 (f=1): [R(1)][20.0%][eta 00m:48s] 
Jobs: 1 (f=1): [R(1)][28.3%][eta 00m:43s] 
Jobs: 1 (f=1): [R(1)][36.7%][eta 00m:38s] 
Jobs: 1 (f=1): [R(1)][45.0%][eta 00m:33s] 
Jobs: 1 (f=1): [R(1)][53.3%][eta 00m:28s] 
Jobs: 1 (f=1): [R(1)][61.7%][eta 00m:23s] 
Jobs: 1 (f=1): [R(1)][70.0%][eta 00m:18s] 
Jobs: 1 (f=1): [R(1)][78.3%][eta 00m:13s] 
Jobs: 1 (f=1): [R(1)][86.7%][eta 00m:08s] 
Jobs: 1 (f=1): [R(1)][95.0%][eta 00m:03s] 
Jobs: 1 (f=1): [R(1)][50.8%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][52.8%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][54.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][56.2%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][57.7%][eta 01m:00s] 
^Cbs: 1 (f=1): [R(1)][58.0%][eta 01m:00s] 
fio: terminating on signal 2
Jobs: 1 (f=1): [R(1)][59.2%][eta 01m:00s]
Jobs: 1 (f=1): [R(1)][60.5%][eta 01m:00s] 
^Cbs: 1 (f=1): [R(1)][60.5%][eta 01m:00s] 
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][61.0%][eta 01m:00s]
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][61.5%][eta 01m:00s]
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][61.5%][eta 01m:00s]
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][61.5%][eta 01m:00s]
fio: terminating on signal 2
Jobs: 1 (f=1): [R(1)][61.8%][eta 01m:00s]
^Cbs: 1 (f=1): [R(1)][61.8%][eta 01m:00s]
fio: terminating on signal 2
Jobs: 1 (f=1): [R(1)][63.0%][eta 01m:00s] 
^Cbs: 1 (f=1): [R(1)][63.2%][eta 01m:00s] 
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][63.4%][eta 01m:00s]
fio: terminating on signal 2
^C
fio: terminating on signal 2
^C
fio: terminating on signal 2
^C
fio: terminating on signal 2
^C
fio: terminating on signal 2
^C
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][63.4%][eta 01m:00s]
fio: terminating on signal 2
^C
fio: terminating on signal 2
Jobs: 1 (f=1): [R(1)][64.1%][eta 01m:00s]
Jobs: 1 (f=1): [R(1)][65.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][66.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][67.0%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][67.9%][eta 01m:00s] 
^Cbs: 1 (f=1): [R(1)][68.4%][eta 01m:00s] 
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][68.4%][eta 01m:00s]
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][68.4%][eta 01m:00s]
fio: terminating on signal 2
^C
fio: terminating on signal 2
^Cbs: 1 (f=1): [R(1)][68.4%][eta 01m:00s]
fio: terminating on signal 2
Jobs: 1 (f=1): [R(1)][68.8%][eta 01m:00s]
Jobs: 1 (f=1): [R(1)][69.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][70.3%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][71.0%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][71.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][72.4%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][73.0%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][73.6%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][74.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][74.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][75.2%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][75.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][76.2%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][76.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][77.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][77.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][77.9%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][78.3%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][78.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][79.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][79.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][79.8%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][80.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][80.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][80.8%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][81.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][81.4%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][81.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][81.9%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][82.2%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][82.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][82.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][83.0%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][83.2%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][83.4%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][83.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][83.9%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][84.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][84.3%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][84.5%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][84.7%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][84.9%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.3%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.4%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.6%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.8%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][85.9%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][86.1%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][86.3%][eta 01m:00s] 
Jobs: 1 (f=1): [R(1)][86.4%][eta 01m:00s] 
fio: job 'TEST' (state=5) hasn't exited in 300 seconds, it appears to be stuck. Doing forceful exit of this job.

TEST: (groupid=0, jobs=1): err= 0: pid=3469: Mon Jul 17 16:05:48 2023
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=0
  IO depths    : 1=1.6%, 2=3.1%, 4=6.2%, 8=12.5%, 16=25.0%, 32=50.0%, >=64=1.6%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=64,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):

Disk stats (read/write):
  nvme0n1: ios=10/258, merge=0/114, ticks=2/83, in_queue=86, util=0.02%
free(): double free detected in tcache 2
Aborted
```

**Comment by dpronin** [comment]
with `--hipri=1` everything seems to be stuck within the kernel in `io_uring.c` compilation unit. Syscall seems to never return to userspace and occupies one CPU for 100% time

**Comment by axboe** [comment]
@dpronin going to need a lot more details than that. What are you running, what kernel, what storage device, pill queues configured, etc.

**Comment by dpronin** [comment]
I have looked into the issue and found out that `fio_ioring_getevents()` never returns because it requires minimum events completed as 1 but actually always got 0 within its context in `do {...} while (events < min)` loop

**Comment by axboe** [comment]
@dpronin See my previous comment, we need a lot more details here.

**Comment by dpronin** [comment]
@1f604 may you check it out if there is `double free()` left on the latest master. Pull the master branch, build and check it out one more time. Be aware, that stuck with `--hipri=1` set has not been fixed, only `double free()` has to vanish

**Comment by atintas** [comment]
I believe I am hitting a similar issue. 
I have encountered this with versions 3.34 and 3.35
My workload is a single threaded 1M Random Write QD1 with io_uring and hipri
Using "mpstat -P ALL 5" I can see my workload starting on the CPU core I specified, but there is a second core also spawning. Both cores are pinned at ~100% and no matter how you try to kill the workload process, nothing works. Even a ptrace doesn't seem to function properly with the PID. I have been having to reboot the server each time. 
This has been reproducible every single time.

**My system configuration:**
RHEL 9.2 
Kernel 6.1.35
FIO 3.35
Solidigm P5520 SSD
Poll queues = 4

**My workload parameters:**
ioengine=io_uring
hipri
log_hist_msec=1000
log_hist_coarseness=0
direct=1
thread=1
buffered=0
allow_mounted_write=0
randrepeat=0
time_based
norandommap
group_reporting
exitall
percentile_list=1.0:25.0:50.0:75.0:90.0:95.0:99.0:99.9:99.99:99.999:99.9999:99.99999:99.999999:100.0
cpus_allowed_policy=split
size=100%
bs=1m
iodepth=1
numjobs=1
rw=randwrite
runtime=60

**Comment by atintas** [comment]
@dpronin @axboe I compiled different kernels on my RHEL9 server to check which kernel is affected and can confirm I was able to reproduce the io_uring+hipri "stuck at 100% process" on all of the 6.x + kernels. When I moved back down to 5.15, I was not reproduce this issue.  
Just checking, is this is on the radar? 
If I need to open a ticket else where to get traction on this, please let me know. :-)

**Comment by axboe** [comment]
Write down exactly what your configuration is and how you're reproducing it and I'll take a look.

**Comment by atintas** [comment]
@axboe My previous comment has my server configuration and workload parameters. 
Do you need additional information that I have missed?

**Comment by axboe** [comment]
@atintas nope that should be all of it, sorry missed that! Just to be clear, spinning 100% is normal, this is how polling works. Not making progress and spinning is certainly not. Does it still do the latter if you use a smaller block size? A 1MB request will only be partially polled as it's split into multiple submissions. Maybe this is where the issue lies, I'll take a closer look tomorrow.

**Comment by atintas** [comment]
@axboe Yes, correct 100% cpu is normal with polling enabled. What is happening though is that a secondary zombie process is spawning at the same time and the FIO process can not be killed. Even a ptrace isn't successful since it's telling me the resource is busy and denying me access. I have to reboot to get my system back. The workload never completes and instead the time actually increases. As @dpronin had mentioned in his comment, it seems like something is stuck in the kernel. He mentioned io_uring.c specifically.

**Comment by axboe** [comment]
Yep, that definitely sounds like a bug.

**Comment by axboe** [comment]
See question on block size, too.

**Comment by atintas** [comment]
I have done a sweep of all my blocksizes from 512B all the way up to 8M and the one that consistently hit this issue was 1M. I have a 95% success rate reproducing it with 1M.

**Comment by dpronin** [comment]
I think that we are supposed to check td->terminated in the loop when getting events in io_uring.c ioengine. If it is true then exit a child thread/process

**Comment by axboe** [comment]
@atintas Can you post your full job file and invocation, rather than just an excerpt from it?

**Comment by axboe** [comment]
This should fix it:

https://git.kernel.dk/cgit/linux/commit/?h=block-6.5&id=50bd4aa84442442c87e669d72d1a6d0b01c332a8

**Comment by atintas** [comment]
@axboe I see you were able to fix it without my job file, but for good measure I will add it here anyway. 
[wr_rnd_qd_1_1m_1w.txt](https://github.com/axboe/fio/files/12295213/wr_rnd_qd_1_1m_1w.txt)
fio wr_rnd_qd_1_1m_1w.ini --output-format=json+ --output Debug_Stuck_FIO_Process_summary.log

Thanks for the fix. I will try it today and report back.
