### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by dpronin** [axboe/fio#1608]
Currently I am working on supporting cmake generator in the project

My local fork of the project has a [branch](https://github.com/dpronin/fio/tree/feature/cmake) reflecting this work

I am curious if it could be useful in the future for fio and could it be adopted in the mainline

Changes are supposed to contain only CMakeLists.txt and config-host.h.in template as new files. No other files could be touched and affected

**Comment by axboe** [comment]
Whenever people ask me about cmake/meson/etc for projects, the answer is mostly the same - who's going to maintain that build system? Are we now using two builds systems?

**Comment by dpronin** [comment]
I could support, but whenever I have faced `configure` script + bunch of Makefiles I have been asking the same question _when does this end_? Never if we do nothing

You will be always stuck at the question about two build systems if someone suggests you should consider another one, it would be obviously endless

I am not insisting on a new build system, you're maintainer and you decide, and I'm just a contributor to offer. But we should remember that some time ago people did program on Cobol, Ada, ancient Fortran, and nobody does today. Even some code in these languages left and companies are forced to find a grandfather, if it still hopefully lives, to support their legacy code base

cmake/meson/etc. would help you get rid of disgusting bash scripts and ugly Unix Makefiles and convert your project even in Microsoft Visual Studio solution, not only Unix Makefiles. cmake here is just an option. 

How long time ago have you opened configure and handcrafted makefiles in fio? It is absolutely unsupportable, everyone just adds what they want without any generic idea, as the result the script `configure` and Makefiles decay. I have been really struggling writing up CMakeLists.txt by trying to translate these `configure` and Makefiles for 3 days, let it alone that many code branches in `configure` have not already conformed and have been a result of wrong copy&paste

One more consideration. If more and more people ask you about that then maybe the time has come? Or we should wait up until you die (long live @axboe, of course) and then elect a new maintainer that would be younger and interested in modern approaches?

**Comment by axboe** [comment]
> I could support, but whenever I have faced configure script + bunch of Makefiles I have been asking the same question when does this end? Never if we do nothing

It basically requires zero maintenance, and I suspect the only things you'll find for it has been whenever people have added something new that needs checking for. So as far as I'm concerned, it's zero maintenance for me and switching to something new will undoubtedly leave me with a bunch of fallout for various things until it settles down. Given that I don't really have much time to devote to fio in the first place, that seems like a bad tradeoff on my end. 

The only potentially sane argument is that it would work as-is for visual studio, I can see how people would find that handy and useful.

I'm going to ignore your last paragraph, as I think it's really distasteful and you should consider seriously consider your phrasing.
