### ISSUE TITLE
FIO test for SSD multi-port

### ISSUE THREAD

**Issue by ningqingqing** [axboe/fio#1611]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<Does fio evenly distribute IO commands when running multiple fio wklds in one fio file?>

**Environment**: <Linux, CentOS>

**fio version**: <fio-3.29>

**Reproduction steps**
<<We create four namespaces on one SSD: nvme0n1, nvme1n2, nvme2n3, and nvme3n4, and run fio on these four namespaces in two ways.
Option 1, we create one fio file and run four WKLDS in the fio file to test nvme0n1, nvme1n2, nvme2n3, and nvme3n4, see the fio_nvme_total.txt file: [fio_nvme_total.txt](https://github.com/axboe/fio/files/12309149/fio_nvme_total.txt)

Option 2, we create four fio files to test nvme0n1, nvme1n2, nvme2n3, and nvme3n4 and run them in four command Windows, see the fio_nvme0n1.txt, fio_nvme1n2.txt, fio_nvme2n3.txt, fio_nvme3n4.txt
[fio_nvme0n1.txt](https://github.com/axboe/fio/files/12309137/fio_nvme0n1.txt)
[fio_nvme1n2.txt](https://github.com/axboe/fio/files/12309142/fio_nvme1n2.txt)
[fio_nvme2n3.txt](https://github.com/axboe/fio/files/12309145/fio_nvme2n3.txt)
[fio_nvme3n4.txt](https://github.com/axboe/fio/files/12309146/fio_nvme3n4.txt)

When testing with option 1, does fio evenly distribute I/O commands?>>

**Comment by vincentkfu** [comment]
```
[global]
per_job_logs=1
max_latency=8s
percentile_list=1:5:10:20:30:40:50:60:70:80:90:95:99:99.9:99.99:99.999:99.9999:99.99999:99.999999
group_reporting=1
log_avg_msec=1000
log_hist_msec=1000
disk_util=1
randrepeat=1
refill_buffers=0
direct=1
size=100%
ioengine=libaio

[wrkldseq_write_128k_QD128_1]
stonewall
readwrite=write
numjobs=1
iodepth=128
bs=128k
ba=128k
time_based
ramp_time=300
runtime=300
filename=/dev/nvme0n1

[wrkldseq_write_128k_QD128_2]
stonewall
readwrite=write
numjobs=1
iodepth=128
bs=128k
ba=128k
time_based
ramp_time=300
runtime=300
filename=/dev/nvme1n2

[wrkldseq_write_128k_QD128_3]
stonewall
readwrite=write
numjobs=1
iodepth=128
bs=128k
ba=128k
time_based
ramp_time=300
runtime=300
filename=/dev/nvme2n3

[wrkldseq_write_128k_QD128_3]
stonewall
readwrite=write
numjobs=1
iodepth=128
bs=128k
ba=128k
time_based
ramp_time=300
runtime=300
filename=/dev/nvme3n4
```

With the above job file, fio will not evenly distribute I/O. You have the `stonewall` directive at the top of each job. So your jobs will run one after the other. Fio will submit as much I/O as it can to the first device until the first job is complete. Then it will submit as much I/O as it can to the second device until the second job is complete, and so on.

If you want all the jobs to run simultaneously, remove the `stonewall` directive. If you want fio to evenly distribute I/O then use something like: `filename=/dev/nvme0n1:/dev/nvme1n2:/dev/nvme2n3:/dev/nvme3n4`

See the documentation for the filename and file_service_type options:
https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename
https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-file-service-type

**Comment by ningqingqing** [comment]
Hi, @vincentkfu , I'm sorry, I forget to remove stonewall before upload fio files.
I don't want fio to evenly distribute I/O. So currently I am testing with option#2. 

I want to confirm whether fio will evenly distribute I/O commands if I testing with option#1 (removed stonewall directive)? And what's the difference between option#1 and option#2 in I/O allocation?

**Comment by vincentkfu** [comment]
Running `fio_nvme_total.txt` without `stonewall` should be essentially identical to running your four separate job files simultaneously. With a single job file defining multiple jobs you can take advantage of options like `group_reporting` or `flow` but the results should otherwise be comparable to four separate invocations of fio. When multiple jobs are defined, fio will spawn separate processes for each job and they will run independently of each other (unless otherwise directed by an option like `flow`).

**Comment by ningqingqing** [comment]
Thank you @vincentkfu
