### ISSUE TITLE
The profile report verify: bad magic header 4dbe, wanted acca at file /testfs1/file-1 offset 32768, length 8192

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1616]
Hi, 
I am using the following profile to send IO to 3 filesystem with 2 files in each, the profile likes in below , the purpose is to divide the file system into half, with the 1st half write data and 2nd half read the data, but the file read is failed instantly with following following errors

bad magic header 4dbe, wanted acca at file /testfs1/file-1 offset 32768, length 8192

`
[global]
ioengine=libaio
exitall_on_error=1
iodepth=32
bs=8k
direct=1 ; Set to 1 if doing RAW device IO, i.e. /dev/*
group_reporting ; jobs are clumped into single report line
verify=crc32c
do_verify=1 ; Enable data verification after write
error_dump=1
write_bw_log=fio_bw_log
write_lat_log=fio_lat_log
write_iops_log=fio_iops_log

[testfs-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs/file-0
size=31249012k
rw=write

[testfs-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs/file-1
size=31249012k
rw=read

[testfs1-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs1/file-0
size=31249012k
rw=write

[testfs1-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs1/file-1
size=31249012k
rw=read

[testfs2-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs2/file-0
size=31249012k
rw=write

[testfs2-Direct_Rand100pct_8K_100W_32Depth]
filename=/testfs2/file-1
size=31249012k
rw=read
`

[debugio.log](https://github.com/axboe/fio/files/12429538/debugio.log)

**Comment by axboe** [comment]
You're asking the file-1 workload to verify already written data, but you have not written it as it's a read workload. This will of course fail. Just remove the do_verify and it'll do what you want, verify after the write, but the reads will just be normal reads and not incur any verification.

**Comment by wangyihanlarry** [comment]
one more follow up question, if I only want do_verify take effects for file-0, how should I do? and if I removed the do_verify from the global section, will the verify still take effect for the file-0?

and what's the difference between do_verify and experimental_verify? when should I use experimentnal_verify?

**Comment by axboe** [comment]
It's on by default when you have verify enabled and doing a write workload. Re-read my previous reply.
