### ISSUE TITLE
MD5 checksum error if Read blocksize is different from Write blocksize

### ISSUE THREAD

**Issue by deepaktawri** [axboe/fio#162]
I get MD5 checksum error with following fio command. Thing to note here is Read block size is 4K and Write block size 64K. Is it valid ? I thought that MD5 checksum will be written for 64K blocks and verified for the same size. Reads of 4K might go on  in parallel to that write/verify process. Please guide

FIO command :
fio --ioengine=libaio --rw=randrw --direct=1 --runtime=30 --time_based --iodepth=16 --verify=md5 --group_reporting  --blocksize=4K,64K  --name=job1 --filename=/dev/nvme1n1  --name=job2 --filename=/dev/nvme2n1  --name=job3 --filename=/dev/nvme3n1  --name=job4 --filename=/dev/nvme4n1

Error :
', output:verify: bad magic header ac77, wanted acca at file /dev/nvme2n1 offset 43169349632, length 65536
verify: bad magic header f0d6, wanted acca at file /dev/nvme2n1 offset 15033303040, length 65536
verify: bad magic header d945, wanted acca at file /dev/nvme3n1 offset 14236254208, length 65536

**Comment by axboe** [comment]
Having a read size of 4k and write of 64k is valid, and the workload does do what you suspect - 64k writes happen with the 4k reads, and then the verify reads are 64k in size. So your job should work just fine. What version are you using? I just tested it with current -git, and it worked fine for me.

**Comment by deepaktawri** [comment]
Thank you for the light speed response!

fio version on my system shows fio-2.2.8.

I will  try with latest git and get back with my finding. Thanks again!

**Comment by deepaktawri** [comment]
I tried with latest git (fio version fio-2.8-18-g639a) and this problem is not seen with it. Thank you!
