### ISSUE TITLE
Docs should indicate that client/server mode only supports defining jobs via job files, not command line arguments

### ISSUE THREAD

**Issue by aggieNick02** [axboe/fio#1629]
- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Fio documentation needs updating to clarify that when running in client/server mode, job parameters must be passed via a job file, not via the command line. I'm happy to put up a PR with doc changes making this clear.

We just need verification that this is intended and not a bug - based on my looking at the code, I'm pretty confident, but if Jens could confirm, that would be great.

**Environment**: Applies to all

**fio version**: Latest

**Reproduction steps**
After playing a bit and exploring the code, I'm pretty certain that, when running in client/server mode, any job parameters passed on the client command line are discarded. The only way to convey job configuration to the server is via job files.

Code exploration details:
To be sent to the server as a command-line option, the option must be marked with `FIO_CLIENT_FLAG` - see the beginning of `parse_cmd_line` in `init.c` . Job-specific command line options are not marked as such, and they are thus parsed on the client in `parse_cmd_line` in `init.c` in the `FIO_GETOPT_JOB` case.

So the only way job-specific command line options could be sent to the client is by sending the populated thread options struct from the client to the server, as far as I can tell. On the server side when the options are received, `convert_thread_options_to_cpu` must be called, and the only caller of that function is` handle_update_job_cmd` in `server.c`. The only sender to the server of that net command (`FIO_NET_CMD_UPDATE_JOB`) is `fio_client_update_options` called from `goptions.c`, which I think is a graphical interface fio can have?

**Comment by aggieNick02** [comment]
Vincent (@vincentkfu) I looked at the code a bit after mentioning this in my last PR - I think this is intended behavior and not a bug and just needs a doc update. Jens (@axboe) can you confirm? Thanks!

**Comment by vincentkfu** [comment]
I agree with your analysis. It seems like the intended way to communicate job options from a client to a server is via `fio_client_send_ini()` in `client.c`. The client either sends the contents of a local job file or sends the filename of a remote file.

Feel free to open a PR to make this clearer in the documentation.

**Comment by aggieNick02** [comment]
Thanks for taking a look with me. Just put a PR up.
