### ISSUE TITLE
fio: failed reading verity state in windows

### ISSUE THREAD

**Issue by yahahawork** [axboe/fio#1631]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

enable verify_state_save option, after write do read verify, same options in ubuntu20.04 and windows. In windows, fio can not reading verity state.

**Environment**: Windows 10 19044.2604

**fio version**: 3.35

**Reproduction steps**

write

```
;-start job file-
[Example1]
rw=randwrite
bs=32k
size=1g
iodepth=1
direct=1
ioengine=libaio (windowsaio)
log_avg_msec=1000
filename=/dev/sda (\\.\PHYSICALDRIVE0)
verify=pattern
verify_pattern=0x8a
do_verify=0
verify_state_save=1
thread
;-end job file-
```

read

```
;-start job file-
[Example1]
rw=randread
bs=32k
size=1g
iodepth=1
direct=1
ioengine=libaio (windowsaio)
log_avg_msec=1000
filename=/dev/sda (\\.\PHYSICALDRIVE0)
verify=pattern
verify_pattern=0x8a
do_verify=1
verify_only=1
verify_state_load=1
thread
;-end job file-
```

![image](https://github.com/axboe/fio/assets/104351842/12c29d7a-d39a-4206-aac1-38ab54b4420d)

![image](https://github.com/axboe/fio/assets/104351842/50a4460c-7902-480c-a41f-ad1aee3a757d)

![image](https://github.com/axboe/fio/assets/104351842/2c5f9a10-05b7-4401-9089-426408354b81)

**Comment by vincentkfu** [comment]
Thanks for reporting this issue and finding the source of the error message. It seems as if the state file was opened in text mode on Windows. Opening it in binary mode seems to fix the issue. Please give it a try and report back. You can find an installer with the fix here:

https://github.com/vincentkfu/fio/actions/runs/6191747239

**Comment by vincentkfu** [comment]
Pretty sure this is the right fix, so I've pushed the patch upstream. Reopen the ticket if you still see this issue.
