### ISSUE TITLE
Why is there not a predefined sane defaults test or tests?

### ISSUE THREAD

**Issue by DoTheEvo** [axboe/fio#1633]
What did I do to you?

What did any of us?

Why are you demanding sacrifice of our time and effort to get usable results from this program?

You must know ins and outs of this, there must be few sane tests to run that output few numbers that tell people difference between hdd, hdd raid, sata ssd, nvme ssd and usb key,...    so why not put them under some flag `--default-test1`, maybe have several...

Most of us really just want few usable results and aspects of the drive, and those who want more have all that 30k words documentation.

**Comment by axboe** [comment]
If you're too lazy to search a bit and figure it out, use something else.

**Comment by DoTheEvo** [comment]
This is obviously your childish ego being hurt talking...   but is there any actual reason?  Any actual drawback?

Why punish people who want to use the software?
Why making them jump through hoops? Each and every one of them?
Is there some difficulty in deciding what would default look like?
Why not even offering the sane default on the github readme page or in the documentation?

Feels weird. But hey your repo.. you do you.

**Comment by axboe** [comment]
Only one being immature here is you, most people figure out how to properly communicate. Or do just the tiniest bit of research before posting nonsense. If you think you can start a productive discussion about job files FOR FREE SOFTWARE by playing a victim, you are sadly mistaken. Locking this issue, go somewhere else. We do not want you as a user.
