### ISSUE TITLE
refuse to write to device with partition table or filesystem without force option

### ISSUE THREAD

**Issue by curu** [axboe/fio#1637]
even we warned users, there are still people keep destroying their  data with fio ...

we find that if mkfs detected that there are partition table or filesystem on a block device, they will emit a warn and quit
user's can still do dangerous mkfs with --force option.
```
[root@cvmlab-oc8 fio-fio-3.35]# mkfs.xfs /dev/vdb
mkfs.xfs: /dev/vdb appears to contain a partition table (dos).
mkfs.xfs: Use the -f option to force overwrite.
[root@cvmlab-oc8 fio-fio-3.35]# mkfs.xfs /dev/vdb1 
mkfs.xfs: /dev/vdb1 appears to contain an existing filesystem (ext4).
mkfs.xfs: Use the -f option to force overwrite.
```

can we do something to save those people like mkfs? that is, if user don't provide a -f|--force option, we refuse to write to  block device with partition or filesystem on it.

**Comment by vincentkfu** [comment]
This would break all automated users of fio that currently don't run with the --force option. Moreover, what will prevent your users from just blindly using the `--force` option all the time? The only solution I can think of is user education. I have two suggestions:

1) don't let users log in as root--then they will have to use `sudo`
2) maintain your own fork where the default for the `readonly`  parameter is 1

**Comment by axboe** [comment]
Like Vincent said, this can't be done without breaking the majority of automated setups out there, which is something we'd get to hear about potentially years from now. So no, this will not be added.

**Comment by curu** [comment]
> Like Vincent said, this can't be done without breaking the majority of automated setups out there, which is something we'd get to hear about potentially years from now. So no, this will not be added.

get it.  but I am wondering if there will be a new major version of fio that can make this breaking change?

**Comment by axboe** [comment]
We don't break compatibility even between major versions.
