### ISSUE TITLE
Unix epoch timestamp is wrong

### ISSUE THREAD

**Issue by it800** [axboe/fio#1638]
**Please acknowledge the following before creating a ticket**

- [X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
If fio runs on a windows host and log_unix_epoch parameter set true, then the result files contain timestamps which do not correlate with Unix timestamp and cannot get decoded clearly because apparently they do not belong to Unix epoch and their real date reference seems to be 16.08.2023. 

**Environment**: Windows 10 Pro 22H2 Build 

**fio version**: 3.35

**Reproduction steps**
1. In the configuration file set log_unix_epoch=1
2. Run fio in any scenario
3. Wait until it stops or terminate by ctrl-c
4. Check the log files for the timestamps
[config_and_result_examples.zip](https://github.com/axboe/fio/files/12717062/config_and_result_examples.zip)

**Comment by vincentkfu** [comment]
On Windows I see:

```
vincent.fu@windows ~/fio-canonical
$ ./fio --name=test --ioengine=null --filesize=1T --time_based --runtime=3s --write_bw_log=test --log_avg_msec=1000 --log_unix_epoch=1
fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.35-129-g996a
...
vincent.fu@windows ~/fio-canonical
$ cat test_bw.1.log
3534489116, 15684483, 0, 0, 0
3534490116, 15346212, 0, 0, 0
```

The time stamp corresponds to a time in the yer 2082.

On Linux I see:
```
root@localhost:~# fio --name=test --ioengine=null --filesize=1T --time_based --runtime=3s --write_bw_log=test --log_avg_msec=1000 --log_unix_epoch=1
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.35-126-ge2c5f
...
root@localhost:~# cat test_bw.1.log
1695751914637, 18840952, 0, 0, 0
1695751915637, 18902814, 0, 0, 0
```

The Linux time stamp seems right. So it looks like this is a Windows issue.

**Comment by it800** [comment]
Since 3534489116 is the number of milliseconds, I'd assume the reference time is somewhere in the year 1982. But that doesn't matter, the problem is still that the timestamp doesn't match the unix epoch. Don't you consider the possibility that the root of the problem is not in Windows, but in incorrect operation of the clock_gettime function in Windows environment? After all, it is already obvious that there is a problem and it is reproduced on different PCs. So maybe the fio code in this part should be corrected to take this situation into account?

**Comment by vincentkfu** [comment]
What I meant was that this is a Windows fio issue. It works on Linux but not on Windows. So fio must not be handling something right with `clock_gettime` on Windows.

**Comment by it800** [comment]
I am looking at this situation from the user's point of view. FIO generates an incorrect timestamp, and in my opinion, it is logical enough that the problem should be fixed. Obviously, there is no way to influence Windows in any way, so there is no point in expecting any fixes from Microsoft. 
Let's suppose that there are problems in Windows that prevent FIO from running, then by your logic there would be nothing to fix in FIO either. And it would just be the software that doesn't work. Then what would be the point of porting it to this platform? The same approach is true with timestamp, as it seems to me. Thank you

**Comment by axboe** [comment]
@it800 Please actually read what Vincent wrote, nobody is saying that Windows itself is buggy, and that hence it needs to get fixed there.

If you care deeply about getting this fixed, one solution is to dig into it yourself and figure it out. The source is right there for you to look at, unlike the Microsoft side. If you're not willing or able to dig in yourself, then I suggest you stay patient and wait until someone on our side has time to look at it.

**Comment by it800** [comment]
@axboe
I apologize, I had no intention of offending anyone. I am not a programmer (well, I used to be a long time ago), so I don't think I have any chance to figure out and fix the problem myself. I just wanted to outline the problem and make sure I wasn't misjudging the situation.
Thank you, for your feedback.

**Comment by vincentkfu** [comment]
Thanks for reporting this issue. It should be fixed now.
When the test run is done you can obtain Windows installers with the fix from the artifacts listed at https://github.com/axboe/fio/actions/runs/6381625910
