### ISSUE TITLE
Failed parsing verify_pattern=0xff%oabcd-12 when given in command line. Works in job file

### ISSUE THREAD

**Issue by deepaktawri** [axboe/fio#164]
I wonder why I get parsing error with verify_pattern in below command =>

fio --iodepth=16 --bs=4k --direct=1 --ioengine=sync --exitall_on_error=1 --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --clat_percentiles=0 --fill_device=1 --rw=write --verify_pattern=0xff%oabcd-12 --do_verify=0 --output=write1.output --name=job1 --filename=/dev/nvme2n1 --name=job2 --filename=/dev/nvme1n1
fio: failed parsing verify_pattern=0xff%oabcd-12

The problem is not seen if all the parameters are given  in a job file.

**Comment by axboe** [comment]
You have to escape your citations. It's not a fio thing, it's the shell.

`--verify-pattern=0xff%o"abcd"-12`

**Comment by deepaktawri** [comment]
My bad! while moving parameters from job file to command line in shell script, I didn't escape the substring in pattern. Apology for the false alarm.

 FIO_WRITE1_PARAMS="--fill_device=1 --rw=write --verify_pattern=0xff%o"abcd"-12 --do_verify=0 --output=write1.output"

Thank you.
