### ISSUE TITLE
fio may core when run timeout

### ISSUE THREAD

**Issue by zqs-Oppenauer** [axboe/fio#1642]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Hi, i'm trying to upgrade fio from 3.13 to 3.35, and test with the custom I/O engine. In certain cases, fio may core, and below is the stack trace information for the coredump
<img width="1664" alt="截屏2023-10-10 15 41 01" src="https://github.com/axboe/fio/assets/147482571/0edac6a2-2467-4395-80ad-0e47571b4d64">
I read the code of fio and find fio will check whether the ddir is READ, WRITE or TRIM when call `rate_ddir`, and here the ddir is DDIR_INVAL
![image](https://github.com/axboe/fio/assets/147482571/8eaae0d6-d90d-4ff6-9d14-765a8a4acfb3)

`rate_ddir` will return DDIR_INVAL as below and the td->rwmix_ddir will be set DDIR_INVAL when fio timeout.
![image](https://github.com/axboe/fio/assets/147482571/3d720a9f-8fb1-4487-b479-e31943bcf612)

because `rate_ddir` returns  DDIR_INVAL, `set_io_u_file` will loop to get next file for current io_u and call `rate_ddir` again, which causes `assert(ddir_rw(ddir))` failed.

**Environment**: Debian GNU/Linux 10

**fio version**: fio-3.35

**Reproduction steps**
To reproduce this bug, multiple conditions need to be met
1. set rate option and rate is triggered.
2. open multi files.
3. set runtime option and fio exactly timeout during call `set_io_u_file` 
because the third condition is difficult to meet every time, i modify the function `runtime_exceeded`, and make return value always false, which guarantees the third condition and the `assert(ddir_rw(ddir))` fails again.

i don't know whether it's a bug, and want know wether there are any methods to avoid core in this case, thank you very much.

**Comment by zqs-Oppenauer** [comment]
@vincentkfu @sitsofe   hi, if it's convenient, could you please give me some advice? i find this issue https://github.com/axboe/fio/issues/1039 introduces the relevant code changes, thank you very much. 🙏

**Comment by weyllor** [comment]
Ping
@vincentkfu

**Comment by weyllor** [comment]
@axboe Please take a look.

**Comment by weyllor** [comment]
any update?

**Comment by zqs-Oppenauer** [comment]
@axboe @vincentkfu hi，whether the current problem description is not quite accurate and requires additional clarification？this is very important for us, please take a look, thanks very much.🙏

**Comment by axboe** [comment]
People, stop pinging on this issue. If it's that important to you, either take a closer look yourself or pay someone to do it. This is a volunteer effort, and we'll get to it when we have time to do so.

**Comment by zqs-Oppenauer** [comment]
sorry very much, I apologize for disturbing you. I read the relevant code causing the issue and identified the reason for the core dump. If I submit a patch for the fix, would you be able to review it when you have time?

**Comment by axboe** [comment]
Always happy to review patches.

**Comment by vincentkfu** [comment]
Should be fixed by https://github.com/axboe/fio/pull/1648
