### ISSUE TITLE
Delete single whitespace from FIO output for read line

### ISSUE THREAD

**Issue by ksingh7** [axboe/fio#165]
Hi
Requesting for a minor change , see the fio output lines for read and write. You will notice a extra whitespace between read and ':'  

Could you please delete that, its sometime a problem while extracting strings with grep ;)

```
  read : io=65474MB, bw=214088KB/s, iops=26760, runt=313167msec

  <Output Truncated for clarity>

  write: io=28018MB, bw=91612KB/s, iops=11451, runt=313167msec
```

**Comment by axboe** [comment]
It's to make them line up, making it look a bit prettier. I have a feeling you're asking because you are parsing it. Is that true? If so, I would strongly recommend you look at using the json output format instead.

**Comment by ksingh7** [comment]
@axboe yes i am using grep to parse FIO normal output.

BTW which one is great format for parsing JSON or TERSE ? :)

**Comment by axboe** [comment]
I'd recommend json. It's humanly readable, and easily parseable.
