### ISSUE TITLE
max_latency option not working

### ISSUE THREAD

**Issue by gfrees** [axboe/fio#166]
I am trying to use the max_latency option as a means to stop FIO when I encounter a cmd with a large latency (stopping FIO when I encounter the large latency event will allow me to trace the event with a bus trace and device trace and determine the root cause of the long cmd).  However, when I add the max_latency option to my FIO script the job will not run.  I get the following error message from FIO:

Bad option <max_latency=45000>
fio: job global dropped

My FIO script is the following:

[global]
runtime=129600
ioengine=sync
time_based=1
norandommap=1
bwavgtime=5000
direct=1
thread=1
do_verify=0
numjobs=1
continue_on_error=io
ramp_time=10

filename=/dev/sdb

# Random Read Workload
# 100% Reads @1024k
[random_read_1024k]
stonewall
rw=randread
bs=1048576

max_latency=45000
write_lat_log=1MB_RandRead_APK_M05_36hrs

I am running FIO version 2.0.10 on SuSE Linux.  The FIO script works as intended without the max_latency option.  It is unclear to me if this is a bug or if it is just user error of some sort.

**Comment by axboe** [comment]
Can you try with 2.9? It's the latest release, the one you are running is ancient.

**Comment by gfrees** [comment]
Thank you.  Version 2.9 solved the problem.  The max_latency parameter now works as intended.
