### ISSUE TITLE
Provide option to run concurrent file writes in round-robin fashion

### ISSUE THREAD

**Issue by gargnitingoogle** [axboe/fio#1672]
**Description of the new feature**

I am testing writes on a network-mounted file-system which has a limit on number of write-operations per file per unit time. I currently have a [job](https://github.com/GoogleCloudPlatform/gcsfuse/blob/2f2fc25311df6f03a32af31e62babd86c91ef787/perfmetrics/scripts/job_files/seq_rand_read_write.fio#L45) which does multiple writes to 40 files simultaneously. Now, instead of writing to those 40 files in round-robin fashion, it seems to be going all writes for one file
at a time before moving on to the next file and so on. This is hitting the write-limit on the file-system.

I saw `roundrobin` in [file_service_type](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-file-service-type), but that is supposed to be enabled by default, and won't help.

**Is it possible to somehow configure fio to go through all the concurrent files writes in a round-robin fashion? If not, could you please provide an option to do so ?**

**Comment by vincentkfu** [comment]
You need something like `nrfiles=40` in order for a single job to write to multiple files in round robin fashion. Your job file has `numjobs=40` which directs fio to spawn 40 separate jobs each writing to a different file.

Start with a very simple job file, take a close look at what is happening, carry out experiments to understand what the options do, and slowly build up from there.

**Comment by gargnitingoogle** [comment]
thanks @vincentkfu . Will try out nrfiles, and if it doesn't work, will update here.
