### ISSUE TITLE
Reading a file randomly via multiple threads

### ISSUE THREAD

**Issue by raj-prince** [axboe/fio#1693]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Hi Team,

I am looking for a fio config, using which we can read a single file by multiple threads parallely.

I tried with the below fio config:
```
[global]
ioengine=libaio
direct=1
fadvise_hint=0
iodepth=64
invalidate=1
nrfiles=1
thread=1
openfiles=1
group_reporting=1
create_serialize=0
allrandrepeat=1
numjobs=10
filename_format=single_file

[Workload]
directory=/gcs
bs=1M
filesize=20M
rw=randomread
size=20M
```

Observation:
1. All the read calls are coming via same file-handle. So, there are two possibilities - (a) read is happening with only one thread. (b) Same file handle is shared b/w all the threads.
2. We get the sequential read block request of 1 MB. Next read block call only comes after the previous read request is responded. This is also the explanation of (1) point.

I am looking for something reading a single file via multiple threads with different fileHandle.

**Environment**:
Ubuntu 20

**fio version**:
Latest fio built from source code.

**Reproduction steps**

**Comment by vincentkfu** [comment]
You have identified a corner case that fio is not handling well. 

Just change

`filename_format=single_file` to `filename=single_file`

`filename_format` does not handle well the case where parsing its value results in the same filename for multiple jobs.

**Comment by raj-prince** [comment]
Thanks a lot @vincentkfu, that worked!!

One more query (sort of follow up) if you could answer:
Is it possible to create a fio config, using which we can read a single file with different handles by multiple threads. With an extra ask file should be read only once, and read block is distributed equally among threads.

For example, we would to read a 5 MiB file with 1 MiB block size with 5 threads.

5 Requests will be generated - [0, 1MiB), [1MiB, 2MiB), [2MiB, 3MiB), [3MiB, 4MiB) and [4MiB, 5MiB).
Now, I would like to distributed all those 5 block read among threads.

Thank you!!

**Comment by vincentkfu** [comment]
Try the `offset_increment` option.

The following will have each job read half the file:

`fio --name=test --filesize=16k --numjobs=2 --offset_increment=50% --filename=test `

Run with `--debug=io,file` to see details.

**Comment by raj-prince** [comment]
Thanks a lot @vincentkfu!! It worked.
