### ISSUE TITLE
Invalid argument error

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#171]
I was trying to execute a sequential reverse pattern with 128K block size, the script was intended to start from the mid drive and read backward for about 500gb. 

FIO version: 2.8
OS: Cent OS 7.2

After about 60% of the workload i get io_u error with invalid arguement as error description. 

Below is the command line:
./fio --name=reverse --filename=/dev/nvme0n1 --ioengine=libaio --iodepth=16 --bs=128K --numjobs=1 --buffered=0 --offset=1030792150 --rw=read:-256k --io-size=527765581331b --runtime=3600 --time_based=1

Am i missing something? I have run reverse pattern in the past, but never encountered this error.

**Comment by axboe** [comment]
Should be fixed by this:

http://git.kernel.dk/cgit/fio/commit/?id=c465cd14ca958dfdb87bb1998add722d62ae3691

The issue is that your offset setting isn't properly aligned, so when fio resets, it will attempt to issue IO at a bad offset.

**Comment by shivapahwa** [comment]
I ran the fio scripts again by compiling the latest fio source code. I am not able to see the issue any more. Thanks for fix. Appriciate your support.

**Comment by axboe** [comment]
Just a heads up that I reverted that commit - the use case is arguably invalid, since the offset isn't a multiple of a valid offset (should be block size aligned).
