### ISSUE TITLE
Windows IoRing support

### ISSUE THREAD

**Issue by poly000** [axboe/fio#1710]
[`libwinring`](https://github.com/CarterLi/libwinring) provides liburing-like API based on IoRing

[ioringapi](https://learn.microsoft.com/en-us/windows/win32/api/ioringapi/)

**Comment by axboe** [comment]
Not sure what the purpose of opening this issue is? It is pretty nifty that you could write code using io_uring on Linux and I/O Rings on Windows basically in the same way, and the underlying reason is mostly that Microsoft basically just copied the io_uring API with I/O Rings.

Anyway, closing this one.

**Comment by poly000** [comment]
> Not sure what the purpose of opening this issue is? It is pretty nifty that you could write code using io_uring on Linux and I/O Rings on Windows basically in the same way, and the underlying reason is mostly that Microsoft basically just copied the io_uring API with I/O Rings.
> 
> Anyway, closing this one.

b/c `io_uring` ioengine is not avaliable on windows

**Comment by poly000** [comment]
> Hah, I totally missed that this was posted on the fio github, not the liburing one. Yes, fio could indeed add support for this, but it would probably be easier to just use the I/O Rings api natively as a separate windows io engine rather than try and make the io_uring engine compatible with Windows via usage of that library.

yep... so should I remove reference to that lib and reopen this issue?

**Comment by axboe** [comment]
> yep... so should I remove reference to that lib and reopen this issue?

I mean you can open it as a feature request, but I personally don't even have a windows box, nor do I have time to develop the engine. If you mark it as a feature request/enhancement, then maybe someone will get motivated to do it. But please include a description of it, just dumping a random link isn't very useful.

**Comment by poly000** [comment]
> > yep... so should I remove reference to that lib and reopen this issue?
> 
> I mean you can open it as a feature request, but I personally don't even have a windows box, nor do I have time to develop the engine. If you mark it as a feature request/enhancement, then maybe someone will get motivated to do it. But please include a description of it, just dumping a random link isn't very useful.

thanks! I will do this when I am avaliable
