### ISSUE TITLE
Specify F_FULLFSYNC when calling fsync on MacOS OR add as an option at the end of run, close of file

### ISSUE THREAD

**Issue by kimono-koans** [axboe/fio#1713]
**Description of the new feature**

MacOS has unusual behavior re: [fsync](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html) call and probably re: it's drive firmware:

> "Note that while `fsync()` will flush all data from the host to the drive (i.e. the "permanent storage device"), the drive itself may not physically write the data to the platters for quite some time and it may be written in an out-of-order sequence.
> 
> Specifically, if the drive loses power or the OS crashes, the application may find that only some or none of their data was written.  The disk drive may also re-order the data so that later writes may be present, while earlier writes are not.
> 
> This is not a theoretical edge case.  This scenario is easily reproduced with real world workloads and drive power failures."

This means there is currently no way for `fio` to generate an apples to apples comparisons across systems and perhaps even across filesystems on MacOS (I've heard of instances where ZFS on MacOS will continue to sync to disk).  However, man page explains there is a way to mitigate:

> "For applications that require tighter guarantees about the integrity of their data, Mac OS X provides the F_FULLFSYNC fcntl."

I would suggest that the `fsync` behavior of MacOS is not what the user expects when benchmarking and either `--end_fsync=1` or `--fsync_on_close=1` are set.  However, even if this behavior is consistent with other Unixes, and "correct", I would suggest adding a feature such that one can call F_FULLFSYNC  when either `--end_fsync=1` or `--fsync_on_close=1` are set on MacOS.

**Comment by axboe** [comment]
Fio is using ```fcntl(io_u->file->fd, F_FULLFSYNC);``` already on OSX for this very reason. At least that's the case with any of the sync IO engines, which I believe are the only ones available on OSX anyway.
