### ISSUE TITLE
Fio behavior with buffer_compress_percentage=50, buffer_pattern="abcd", scramble_buffer=true and refill_buffers

### ISSUE THREAD

**Issue by karthick2966** [axboe/fio#173]
Hi Folks,

I have couple of questions on fio behaviour with flags buffer_compress_percentage=50, buffer_pattern="abcd", scramble_buffer=true and refill_buffers.

1. With this flags, will fio repeat 50% of block with "abcd" and since scramble_buffers=1, will buffer pattern be "acdb" (scramble example) for subsequent block?

2. Is there a way to pass file (pattern from file) as buffer_pattern.

Thank you.

**Comment by axboe** [comment]
There's currently no way to pass in a file to be used to fill a buffer pattern. I'll take patches for that, though, if you want to work on it.
