### ISSUE TITLE
`fio: io_u error on file /tmp/mounts3/1-job-30-write.0.0: Bad file descriptor: write offset=0, buflen=131072`

### ISSUE THREAD

**Issue by bas-kirill** [axboe/fio#1732]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
I installed `mount-s3` and mounted it as `/tmp/mounts3` using command `mount-s3 kirill.bas /tmp/mounts3`. 

Also wrote config for benchmark:
```bash
[global]
direct=1
ioengine=libaio
iodepth=16
bs=128k

[1-job-30-write]
name=1-job-30-write
numjobs=1
directory=/tmp/mounts3
rw=rw
rwmixwrite=30
rwmixread=70
size=1m
``` 

After execution fio ./mounts3.fio > report.txt got an error: 
```bash
fio: io_u error on file /tmp/mounts3/1-job-30-write.0.0: Bad file descriptor: write offset=0, buflen=131072
fio: io_u error on file /tmp/mounts3/1-job-30-write.0.0: Bad file descriptor: write offset=131072, buflen=131072
```

**Environment**: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20240207.1

**fio version**: fio-3.28

**Reproduction steps**

1. Install mount-s3:
```
sudo apt update -y
sudo apt install fio -y
wget -P /home/ubuntu https://s3.amazonaws.com/mountpoint-s3-release/latest/arm64/mount-s3.deb
sudo apt-get install /home/ubuntu/mount-s3.deb -y
```

2. Create mount directory: `mkdir /tmp/mounts3`

3. `mount-s3 <bucket-name> /tmp/mount3 --allow-delete`

4. Create fio configuration:

```
cat <<EOF > /home/ubuntu/mounts3.fio
[global]
direct=1
ioengine=libaio
iodepth=16
bs=128k

[1-job-30-write]
name=1-job-30-write
numjobs=1
directory=/tmp/mounts3
rw=rw
rwmixwrite=30
rwmixread=70
size=1m
```

5. Start benchmark: `fio /home/ubuntu/mounts3.fio > report.txt`

Expected Result: got report in .txt

Actual Result: error: `fio: io_u error on file /tmp/mounts3/1-job-30-write.0.0: Bad file descriptor: write offset=0, buflen=131072`

**Comment by vincentkfu** [comment]
Closing due to lack of response from reporter.

**Comment by MynaITLabs** [comment]
FYI, I made the error disappear when I removed the 'direct=1' option on a mSATA KingDian M200 60GB .
