### ISSUE TITLE
FIO 2.8 filename=/dev/nvme0n1:/dev/nvme1n1 generates uneven iodepths on the interface when checked via iostat

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#175]
Below mentioned file generates uneven iodepths for the two targets when recording with iostats 
###FILE START####
[global]
name= Test
ioengine=libaio
direct=1
buffered=0
size=100%
randrepeat=0
time_based
norandommap
refill_buffers
log_avg_msec=1000
group_reporting
filename=/dev/nvme0n1:/dev/nvme1n1

[rd_rnd_qd_128_4k_4w]
stonewall
bs=4k
iodepth=32
numjobs=4
rw=randread
runtime=3600
###FILE END####

**This way generates correct iodepth expected as per the parameters.** (i.e. even IODEPTH reported with iostats for both the nvme drives) 
###FILE START####
[global]
name= Test
ioengine=libaio
direct=1
buffered=0
size=100%
randrepeat=0
time_based
norandommap
refill_buffers
log_avg_msec=1000
group_reporting
bs=4k
iodepth=32
numjobs=4
rw=randread
runtime=3600

[drive1] 
stonewall
filename=/dev/nvme0n1
[drive2]
filename=/dev/nvme1n1

###FILE END####

**Comment by axboe** [comment]
That's very odd. I've verified that fio does strict roundrobin with your exact job file, but I also see one device running basically 2/3rd the queue depth, according to iostat. But if you terminate fio, you can see it's issued pretty much exactly the same amount of IO to each device:

  nvme1n1: ios=1138634/0, merge=0/0, ticks=59490/0, in_queue=59500, util=98.28%
  nvme0n1: ios=1138644/0, merge=0/0, ticks=30280/0, in_queue=30320, util=97.54%

and one of them just has more ticks and time in_queue. Not sure this is a fio issue, but I'll take a deeper look and figure out what is going on here.

**Comment by axboe** [comment]
Are your two devices the same? If one is faster than the other, then that would explain it. If I rerun the test again, with a bigger difference in device speeds, then it's more apparent:

  nvme1n1: ios=2031724/0, merge=0/0, ticks=94950/0, in_queue=94690, util=98.83%
  nvme2n1: ios=2031735/0, merge=0/0, ticks=17840/0, in_queue=17680, util=97.10%

Observed depth is ~1.8 for nvme2n1 (which is a DRAM based nvme device), and ~6.8 for a slower Intel P3700 nvme device.

So I don't think there's anything out of the ordinary here. Fio will roundrobin your devices strictly, and issue 1 IO to one of them, then 1 to the next, repeat. If one finishes IO quicker than the other, then the observed queue depth through iostat will be different.

**Comment by akoundal** [comment]
Hi,
Yes the Device are the same its actually P3608 (which is x8). I expected it
to be same when doing the filename=device1:device2 but at a given time it
doesn;t maintain the same iodepth, i ran for quite some time it keeps on
changing as per the serviced.

On Tue, May 17, 2016 at 2:53 PM, Jens Axboe <notifications@github.com>
wrote:

> Are your two devices the same? If one is faster than the other, then that
> would explain it. If I rerun the test again, with a bigger difference in
> device speeds, then it's more apparent:
>
> nvme1n1: ios=2031724/0, merge=0/0, ticks=94950/0, in_queue=94690,
> util=98.83%
> nvme2n1: ios=2031735/0, merge=0/0, ticks=17840/0, in_queue=17680,
> util=97.10%
>
> Observed depth is ~1.8 for nvme2n1 (which is a DRAM based nvme device),
> and ~6.8 for a slower Intel P3700 nvme device.
>
> So I don't think there's anything out of the ordinary here. Fio will
> roundrobin your devices strictly, and issue 1 IO to one of them, then 1 to
> the next, repeat. If one finishes IO quicker than the other, then the
> observed queue depth through iostat will be different.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/axboe/fio/issues/175#issuecomment-219865851>
>



-- 
Life is too short for silly things so invest your time in some productive
outputs!!

**Comment by akoundal** [comment]
To my understanding may be that is not clear:
when giving the filename=device1:device2 , shouldn't it send the generate
threads in parallel and issue to both targets at same time rather then
round-robin? I was not sure that it will do the round-robin for this also.

On Tue, May 17, 2016 at 6:55 PM, abhishek koundal <akoundal@gmail.com>
wrote:

> Hi,
> Yes the Device are the same its actually P3608 (which is x8). I expected
> it to be same when doing the filename=device1:device2 but at a given time
> it doesn;t maintain the same iodepth, i ran for quite some time it keeps on
> changing as per the serviced.
>
> On Tue, May 17, 2016 at 2:53 PM, Jens Axboe <notifications@github.com>
> wrote:
>
>> Are your two devices the same? If one is faster than the other, then that
>> would explain it. If I rerun the test again, with a bigger difference in
>> device speeds, then it's more apparent:
>>
>> nvme1n1: ios=2031724/0, merge=0/0, ticks=94950/0, in_queue=94690,
>> util=98.83%
>> nvme2n1: ios=2031735/0, merge=0/0, ticks=17840/0, in_queue=17680,
>> util=97.10%
>>
>> Observed depth is ~1.8 for nvme2n1 (which is a DRAM based nvme device),
>> and ~6.8 for a slower Intel P3700 nvme device.
>>
>> So I don't think there's anything out of the ordinary here. Fio will
>> roundrobin your devices strictly, and issue 1 IO to one of them, then 1 to
>> the next, repeat. If one finishes IO quicker than the other, then the
>> observed queue depth through iostat will be different.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/axboe/fio/issues/175#issuecomment-219865851>
>>
>
>
>
> --
> Life is too short for silly things so invest your time in some productive
> outputs!!
>



-- 
Life is too short for silly things so invest your time in some productive
outputs!!

**Comment by axboe** [comment]
You have one IO thread in your first example, and this thread will roundrobin between issuing IO to the two files. This means they share the in-kernel aio context, and everything else. But fio will issue fairly between the two.

That's how you defined the job file. In fio, each job is a separate thread (or process, in your case). Your other example, that one is using a thread per file. So it really all comes down to what kind of behavior you want to model.

**Comment by akoundal** [comment]
Yes your explanation makes sense. i thought first job file will also spawn
two threads.
Appreciate your follow up and explanation.I am clear now.

-May the force be with You
