### ISSUE TITLE
fio fails to run more than 4 rbd jobs at once

### ISSUE THREAD

**Issue by adippl** [axboe/fio#1778]
**Please acknowledge the following before creating a ticket**

- [ x ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
fio fails to benchmark more than 4 RBD image jobs at once. 
There is no IO on ceph cluster and fio never finishes the benchmark

**Environment**: 
OS: ubuntu 22.04
librbd 18.2.2

**fio version**: 3.34 3.36. 3.37

**Reproduction steps**
Example of my config file.
Fio fails when running it.
Commenting out one of the jobs and running with only 4 jobs makes fio run correctly.
Moving ioengine= , clientname= or pool= makes no difference.
```
[global]
rw=randwrite
bs=4k
iodepth=16
group_reporting
time_based
ramp_time=30
runtime=60

[node00_image00]
ioengine=rbd
rbdname=node00_image00
clientname=benchmark
pool=benchmark_ssd

[node00_image01]
ioengine=rbd
rbdname=node00_image01
clientname=benchmark
pool=benchmark_ssd

[node00_image02]
ioengine=rbd
rbdname=node00_image02
clientname=benchmark
pool=benchmark_ssd

[node00_image03]
ioengine=rbd
rbdname=node00_image03
clientname=benchmark
pool=benchmark_ssd

[node00_image04]
ioengine=rbd
rbdname=node00_image04
clientname=benchmark
pool=benchmark_ssd
```

I've saved output of fio with --debug=all 
It's very long. I've uploaded it as a gist. https://gist.github.com/adippl/776dc4eda30e117688e2807d2e025e5e

**Comment by vincentkfu** [comment]
What happens if you run two instances of fio, one with two rbd and the other with three rbd jobs? Or five instances of fio simultaneously each with a single job?

**Comment by adippl** [comment]
Running 2 separate fio each with 4 RBD jobs at one works normally.

Adding job/rbd image to one of fio has the same effect. Fio running with 5 images doesn't generate traffic and never finishes and has to be killed with kill -9.

**Comment by vincentkfu** [comment]
It looks like the ioengine is trying to reap completions but none are returned by librbd, so it gets stuck endlessly looking for completions.

Near the end of your debug log is this:

```
io       69936 fill: io_u 0x55e592d10540: off=0x5974a000,len=0x1000,ddir=1,file=node00_image02.0.0
io       69936 prep: io_u 0x55e592d10540: off=0x5974a000,len=0x1000,ddir=1,file=node00_image02.0.0
io       69936 queue: io_u 0x55e592d10540: off=0x5974a000,len=0x1000,ddir=1,file=node00_image02.0.0
io       69936 calling ->commit(), depth 16
io       69936 io_u_queued_complete: min=1
diskutil 69843 update io ticks
helperthread 69843 next_log: 500, msec_to_next_event: 250
```

The remaining debug prints are from the helper thread and diskutil, with no more messages from the IO threads. Processes 69934, 69935, and 69937 seem to finish up without issue but 69936 gets stuck looking for completions that never arrive.

The `io_u_queued_complete: min=1` debug print comes from `io_u_queued_complete()` which calls `td_io_getevents()` which calls the ioengine's `fio_rbd_getevents()`:

```
static int fio_rbd_getevents(struct thread_data *td, unsigned int min,
			     unsigned int max, const struct timespec *t)
{
	unsigned int this_events, events = 0;
	struct rbd_options *o = td->eo;
	int wait = 0;

	do {
		this_events = rbd_iter_events(td, &events, min, wait);

		if (events >= min)
			break;
		if (this_events)
			continue;

		if (!o->busy_poll)
			wait = 1;
		else
			nop;
	} while (1);

	return events;
}
```

Fio thinks there are 16 I/Os outstanding (`calling ->commit(), depth 16`) but librbd returns no completions.

This is as far as I am able to go. Perhaps something knowledgeable about rbd can chime in. Consider trying different versions of librbd.

**Comment by vincentkfu** [comment]
Closing due to lack of follow up.

**Comment by xin3liang** [comment]
In my case, I can't run fio test more than 10 rbds, otherwise it will get stuck and no any fio test is running.
Test fio version: `3.29, 3.35 and master`. 
Test OS: `openEuler24.03(linux 6.6.x), CentOS stream-9(linux 5.14.0-547.el9)`
Howerver, I can run more than 10 RBDs in a container. `podman run -it --pids-limit 4096 --name bdevtest centos-stream9`
