### ISSUE TITLE
Size parameter in % results in Invalid argument error 

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#178]
FIO version: 2.9
OS: Cent OS 7.1 (4.3.3 kernel) 

nvme drive capacity = 2TB 

While testing the LBA span size using the size parameter the run got hit with Invalid argument error. 
FILE: 
[global]
name= Size
ioengine=libaio
direct=1
buffered=0
size=40%
randrepeat=0
time_based
norandommap
refill_buffers
log_avg_msec=1000
group_reporting
filename=/dev/nvme0n1

[wr_qd_128_64k_1w]
stonewall
bs=64k
iodepth=128
numjobs=1
rw=write
runtime=7200

When size parameter is changed to use **800G** it works fine w/o any failures. 
[global]
name= Size
ioengine=libaio
direct=1
buffered=0
size=**800G**
randrepeat=0
time_based
norandommap
refill_buffers
log_avg_msec=1000
group_reporting
filename=/dev/nvme0n1

[wr_qd_128_64k_1w]
stonewall
bs=64k
iodepth=128
numjobs=1
rw=write
runtime=7200

This is something reported in this issue which is reported fix: 
https://github.com/axboe/fio/issues/171

Do let me know if I am doing something wrong in my input file.

**Comment by axboe** [comment]
Issue 171 was due to offset being badly aligned. I'm guessing this is io_size being badly aligned, can you try with the attached patch?

[align-percent.txt](https://github.com/axboe/fio/files/271390/align-percent.txt)

**Comment by axboe** [comment]
Oops, try this version, the previous one had some extra stuff in it...
[align-percent.txt](https://github.com/axboe/fio/files/271395/align-percent.txt)

**Comment by akoundal** [comment]
sure, will update once i have tested out with the new patch.

**Comment by akoundal** [comment]
Failure seen in ~25minutes without patch 

**No failure** seen with 2hr of WL execution. Looks like good to go. cheers.

**Comment by axboe** [comment]
Great, thanks for reporting and testing. Fix has been committed.
