### ISSUE TITLE
FIO's json+ output is either incorrect, or the built-in parsers have bugs, or both.  See details below.

### ISSUE THREAD

**Issue by russfellows** [axboe/fio#1781]
**Please acknowledge the following before creating a ticket**

- [ x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
The builtin parsers, that are installed with fio to parse the json output do not work correctly.  This occurs when attempting to parse a json+ file created from fio of the same version.  

**Environment**:  Ubuntu 24.04 LTS

**fio version**: 3.37

**Reproduction steps**

root@localhost:/#  fio_jsonplus_clat2csv --debug ./fio-32file-256k_run3.json ./fio-32file-256k_run3.csv
ddir_lat_list:  ['read_slat_ns', 'read_clat_ns', 'read_lat_ns', 'write_slat_ns', 'write_clat_ns', 'write_lat_ns', 'trim_slat_ns', 'trim_clat_ns', 'trim_lat_ns']
col_labels:  nsec, read_slat_ns_count, read_slat_ns_cumulative, read_slat_ns_percentile, read_clat_ns_count, read_clat_ns_cumulative, read_clat_ns_percentile, read_lat_ns_count, read_lat_ns_cumulative, read_lat_ns_percentile, write_slat_ns_count, write_slat_ns_cumulative, write_slat_ns_percentile, write_clat_ns_count, write_clat_ns_cumulative, write_clat_ns_percentile, write_lat_ns_count, write_lat_ns_cumulative, write_lat_ns_percentile, trim_slat_ns_count, trim_slat_ns_cumulative, trim_slat_ns_percentile, trim_clat_ns_count, trim_clat_ns_cumulative, trim_clat_ns_percentile, trim_lat_ns_count, trim_lat_ns_cumulative, trim_lat_ns_percentile,
Traceback (most recent call last):
  File "/usr/local/bin/fio_jsonplus_clat2csv", line 332, in <module>
    main()
  File "/usr/local/bin/fio_jsonplus_clat2csv", line 273, in main
    for jobnum in range(0, len(jsondata['jobs'])):
                               ~~~~~~~~^^^^^^^^
KeyError: 'jobs'

**Comment by vincentkfu** [comment]
It's certainly possible that there is a bug but you're going to have to provide more details for there to be any hope for me to help you.

What job did you run? What are the contents of your JSON file? Has this worked for you in the past?
