### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lb23333** [axboe/fio#1795]
$ make
    CC crc/crc32c-arm64.o
In file included from crc/../os/os.h:38,
                 from crc/crc32c-arm64.c:2:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:345: crc/crc32c-arm64.o] Error 1                                      
fio-3.9, gcc-11,linux-5.15

**Comment by axboe** [comment]
When you file an issue, it includes information on what should be in that issue. You didn't read that. 

Update your fio version, it's too old.
