### ISSUE TITLE
sqthread_poll =1

### ISSUE THREAD

**Issue by zx104972** [axboe/fio#1796]
我开启 sqthread_poll=1 后 为什么  usr cpu  会升高，sys  cpu 会降低呢，正常不应该反着吗
seq_read: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=64
fio-3.37-80-g4017-dirty
Starting 1 process
Jobs: 1 (f=4): [R(1)][100.0%][r=222MiB/s][r=56.9k IOPS][eta 00m:00s]
seq_read: (groupid=0, jobs=1): err= 0: pid=21890: Thu Aug  1 14:17:02 2024
  read: IOPS=57.3k, BW=224MiB/s (235MB/s)(13.1GiB/60002msec)
    clat (usec): min=73, max=17242, avg=1117.22, stdev=383.30
     lat (usec): min=73, max=17242, avg=1117.31, stdev=383.30
    clat percentiles (usec):
     |  1.00th=[  330],  5.00th=[  515], 10.00th=[  644], 20.00th=[  799],
     | 30.00th=[  914], 40.00th=[ 1012], 50.00th=[ 1106], 60.00th=[ 1205],
     | 70.00th=[ 1287], 80.00th=[ 1401], 90.00th=[ 1582], 95.00th=[ 1762],
     | 99.00th=[ 2147], 99.50th=[ 2311], 99.90th=[ 2966], 99.95th=[ 3326],
     | 99.99th=[ 4621]
   bw (  KiB/s): min=211313, max=275320, per=100.00%, avg=229321.48, stdev=9408.20, samples=119
   iops        : min=52828, max=68830, avg=57330.36, stdev=2352.03, samples=119
  lat (usec)   : 100=0.01%, 250=0.33%, 500=4.22%, 750=11.85%, 1000=21.99%
  lat (msec)   : 2=59.76%, 4=1.84%, 10=0.02%, 20=0.01%
  cpu          : usr=86.01%, sys=0.00%, ctx=361, majf=0, minf=3
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=3436078,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

**Comment by vincentkfu** [comment]
Please pose your question in English.

**Comment by vincentkfu** [comment]
Closing due to lack of follow up.
