### ISSUE TITLE
Improve http_host- and filename-related documentation

### ISSUE THREAD

**Issue by scaleoutsean** [axboe/fio#1797]
**Description of the new feature**

Improve http_s3_* related documentation. 

**Please acknowledge the following before creating a ticket**

- [v] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**

- Online help for `http_host` contains the word bucket which is confusing. The docs say this "could" contain "the bucket hostname", but it's unclear when this would be a choice (for S3 users it usually isn't as S3 is configured in certain way).
- [Examples](https://github.com/axboe/fio/blob/9213e16d98b0e9d2f8d4f7e760ed0fd45c8960f6/examples/http-s3.fio#L16) has a vHost type example (s3.eu-central-1.amazonaws.com (no bucket name, which implies Path-style addressing without referring to it as such. There's no problem with that, but it's considered a legacy method and it probably should be called out using common AWS terminology.

**Environment**: Ubuntu 22.04 (Linux Mint 21.3)

**fio version**: fio-3.37-80-g4017

**Reproduction steps**

```sh
$ fio --enghelp=http | grep bucket
http_host               : Hostname (S3 bucket)
```

**Comments:**

- `Hostname (S3 bucket)` may be clearer as `S3 API FQDN`, so that Path-style endpoint.org is also valid (no bucket in it). The docs say `Hostname to connect to. For S3, this could be the bucket hostname. Default is localhost`, but *could* is ambiguous. If vHost-style buckets are used, by now everyone knows they need to prefix API endpoint with bucket name.
- The other challenge is`filename`, which is not included in `--enghelp=http` output, but maybe it should be. Currently there's nothing on S3 in [filename param docs](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename), so it's unclear how to specify that value. The way it seems to work with v3.37 and Path-style S3 is you need to specify `/` + `bucket` + `/` + `key` in filename (`filename=/bucket/obj.ect`), while for new-style vPath it's just `/` + `key`). 
- Instead of `bucket hostname`, virtual-hosted-style (or Host-style or vHost-style) and path-style could be used for easier search, [standardization and disambiguation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html), and the terms `bucket` and `key` could be used to describe how `filename` should be specified with HTTP engine in vHost- (`/k/e.y`) and Path-style (`/` + `bucket` + `/` + `k/e.y`) scenarios. Maybe omitting the first forward slash also works, but I haven't tried that.
- Separately, but related to the docs for the same engine, `http_host` has nothing on port numbers (whether or not they may or must be specified), which requires trial & error and I'm not even sure how people whose object storage runs on non-standard ports manage this. Currently it seems `https` acts as an undocumented 80/443 "switch". A bit of additional detail on this behavior wouldn't hurt.

Quick reference (from the AWS link above, but there are exceptions, see the link for all details):

- Modern AWS vHost-style: `https://bucket-name.s3.region-code.amazonaws.com/key-name`
- AWS Path-style: `https://s3.region-code.amazonaws.com/bucket-name/key-name`

**Comment by vincentkfu** [comment]
Feel free to submit a PR addressing the issues you have identified. Also reasonable would be to add comments to the http ioengine examples documenting your findings.

**Comment by scaleoutsean** [comment]
I think this was addressed in the PR, so I think this issue can be closed.

**Comment by lvjing421** [comment]
> Feel free to submit a PR addressing the issues you have identified. Also reasonable would be to add comments to the http ioengine examples documenting your findings.
> 
> Documentation changes require updates to both the HOWTO and man page fio.1.

Hi, I tried with man fio, but it does not display fio.1's content.

**Comment by sitsofe** [comment]
Hello @lvjing421:
I'm afraid I don't understand. Are you saying the **latest** https://github.com/axboe/fio/blob/master/fio.1 (and I guess https://github.com/axboe/fio/blob/master/HOWTO.rst ) do not address scaleoutsean's comment or do you mean something else? If the former then can you clarify further, if "something else" I strongly suggest filing a different issue (if it's a bug then file and issue, if it's a "How do I?" then a discussion) rather than jumping on a closed thread.

**Comment by lvjing421** [comment]
> Hello [@lvjing421](https://github.com/lvjing421): I'm afraid I don't understand. Are you saying the **latest** https://github.com/axboe/fio/blob/master/fio.1 (and I guess https://github.com/axboe/fio/blob/master/HOWTO.rst ) do not address scaleoutsean's comment or do you mean something else? If the former then can you clarify further, if "something else" I strongly suggest filing a different issue (if it's a bug then file and issue, if it's a "How do I?" then a discussion) rather than jumping on a closed thread.

Sorry for the confusion, it is about fio man usage in general - man fio does not work.

**Comment by sitsofe** [comment]
@lvjing421:

> [...] it is about fio man usage in general - man fio does not work.

Please create a new discussion ticket (FWIW I've just done `man ./fio.1` here and it worked for me).

**Comment by lvjing421** [comment]
> [@lvjing421](https://github.com/lvjing421):
> 
> > [...] it is about fio man usage in general - man fio does not work.
> 
> Please create a new discussion ticket (FWIW I've just done `man ./fio.1` here and it worked for me).

I just did not get the correct usage, thanks.
