### ISSUE TITLE
generic_open_file() error lost

### ISSUE THREAD

**Issue by andreas-gruenbacher** [axboe/fio#18]
With the following job description, when I run ```fio --section=verify test.fio``` as a regular user, I get a permission denied error but fio still exits with status 0:

    ; fio job description for writing a defined pattern to disk and later
    ; verifying the pattern.
    ;
    ; Usage:
    ;  fio --section=write write-verify.fio
    ;  fio --section=verify write-verify.fio

    [global]
    thread=1
    bs=4k
    buffered=1
    ioengine=sync
    verify=meta
    verify_interval=4k
    filename=/dev/vda

    [write]
    rw=write
    fill_device=1
    do_verify=0

    [verify]
    stonewall
    create_serialize=0
    rw=read
    do_verify=1

--

    $ gdb --args fio --section=verify test.fio 
    [...]
    (gdb) b filesetup.c:611
    Breakpoint 1 at 0x420608: file filesetup.c, line 611.
    (gdb) r
    Starting program: /usr/local/bin/fio --section=verify test.fio
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    verify: (g=0): rw=read, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=1
    fio-2.1.10-54-gb736
    [New Thread 0x7fffeedfe700 (LWP 6844)]
    Starting 1 thread
    [New Thread 0x7fffee5fd700 (LWP 6845)]
    [Switching to Thread 0x7fffee5fd700 (LWP 6845)]
    
    Breakpoint 1, generic_open_file (td=0x7fffeedff000, f=0x7ffff66dc210) at filesetup.c:611
    611			td_verror(td, __e, buf);
    (gdb) n
    614s: 1 (f=0): [if (!from_hash && f->fd != -1) {s] [0/0/0 iops] [eta 00m:00s]
    (gdb) p td->error
    $1 = 13
    (gdb) bt
    #0  generic_open_file (td=0x7fffeedff000, f=0x7ffff66dc210) at filesetup.c:614
    #1  0x000000000041fbea in bdev_size (td=0x7fffeedff000, f=0x7ffff66dc210) at filesetup.c:297
    #2  0x000000000041fdb6 in get_file_size (td=0x7fffeedff000, f=0x7ffff66dc210) at filesetup.c:367
    #3  0x0000000000420721 in generic_get_file_size (td=0x7fffeedff000, f=0x7ffff66dc210) at filesetup.c:644
    #4  0x00000000004207b3 in get_file_sizes (td=0x7fffeedff000) at filesetup.c:660
    #5  0x0000000000420c72 in setup_files (td=0x7fffeedff000) at filesetup.c:791
    #6  0x000000000044a51e in thread_main (data=0x7fffeedff000) at backend.c:1430
    #7  0x00007ffff74a8d15 in start_thread () from /lib64/libpthread.so.0
    #8  0x00007ffff6fd748d in clone () from /lib64/libc.so.6
    (gdb) c
    Continuing.
    file:filesetup.c:611, func=open(/dev/vda), error=Permission deniedta 00m:00s]
    [Thread 0x7fffee5fd700 (LWP 6845) exited]
    
    
    Run status group 0 (all jobs):
    
    Disk stats (read/write):
      vda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
    [Thread 0x7fffeedfe700 (LWP 6844) exited]
    [Inferior 1 (process 6840) exited normally]

**Comment by axboe** [comment]
Fixed
