### ISSUE TITLE
FIO Metadata

### ISSUE THREAD

**Issue by ningqingqing** [axboe/fio#1821]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<We are testing performance on a 4160B(4K+64B) SSD, we want to know how fio deal with the 64B metadata if we set blocksize=130k or blocksize=4160B, and do we need to use pi_act and md_per_io_size parameters？What effect do these two parameters have on FIO? We try to analyze fio PCIe trace, but can't find metadata. >

**Environment**: <Linux, CentOS>

**fio version**: <3.37>

**Reproduction steps**
<[seqwrite.txt](https://github.com/user-attachments/files/17161943/seqwrite.txt)
sequential write test with blocksize=130k, pi_act=0 and md_per_io_size=2k
[randwrite.txt](https://github.com/user-attachments/files/17161944/randwrite.txt)
random write test with blocksize=4160, pi_act=0 and md_per_io_size=64>

**Comment by vincentkfu** [comment]
This depends on how your device is formatted. @ankit-sam and I wrote two blog posts on fio's PI support. You should be able to find the answers to your question there:

https://github.com/vincentkfu/fio-blog/wiki/Fio-end-to-end-data-protection-part-1-background
https://github.com/vincentkfu/fio-blog/wiki/Fio-end-to-end-data-protection-part-2-fio-support

If your device is formatted in extended LBA mode then you do not need to set {{md_per_io_size}}. If you do have a 4160B SSD then there will not be a separate metadata buffer. Fio will use a single 4160B buffer with the first 4096 bytes containing logical block data and the final 64 bytes containing metadata.

**Comment by ningqingqing** [comment]
Thank you @vincentkfu . Sorry for the late reply. I'm on vacation last week.
