### ISSUE TITLE
On pNFSv4, FIO attempts to access the file after it's closed

### ISSUE THREAD

**Issue by qtcwt** [axboe/fio#1823]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
When testing pNFS4.2, fio sometimes does LAYOUTGET after a CLOSE on the same file. According to [NFS spec 18.2.4](https://www.rfc-editor.org/rfc/rfc5661#section-18.2.4), single CLOSE should shut down all OPENs for the same file and the single open-owner.

More context: 
I notice that fio opens the same file twice and closes it twice. Between the two closes, it also attempts to do LAYOUTGET. Both that LAYOUTGET and the last CLOSE will not be able to find the open state, as the first CLOSE should already close it, not matter how many times the file was opened by the same client.
Since fio is running upon my Linux's built-in NFS client, I further read the spec of open/close manual. Under section `Multithreaded processes and close()` in [man close()](https://man7.org/linux/man-pages/man2/close.2.html), it says concurrent close while another thread is doing IO can cause unintended effect, depending on how the system is implemented. 
With that, I guess the bug was because fio tries to open, access, and close the same files on different threads without synchronization.

**Environment**: kernel-4.18.0-305.el8.x86_64 (Red Hat Enterprise Linux)

**fio version**: fio-3.35-129-g996a. Also reproduced at master HEAD (commit: 980fb7f).

**Reproduction steps**
```bash
# Set mount_point to where pNFS is mounted
fio --name=f --numjobs=2 --rw=write --create_on_open=1 --bs=4k  --directory=${mount_point} --filename='f0:f1' --filesize=4k
```

**Comment by vincentkfu** [comment]
You have two separate jobs both trying to `create_on_open` the same files `f0` and `f1`. The configuration is not well defined. Try allowing fio to use unique filenames by replacing `--filename=f0:f1` with `--nrfiles=2`.

**Comment by qtcwt** [comment]
I think I figured out the problem. It is actually not in fio. Thanks for the response, Vincent. Closing.
