### ISSUE TITLE
writefua and readfua may not work with the engine of io_uring 

### ISSUE THREAD

**Issue by 18888024924** [axboe/fio#1834]
**Please acknowledge the following before creating a ticket**

- [Y ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<
Dear engineer
   when I use run the command as below, the parameter that writefua and readfua seem not work. There is no fuaflag 0x4000 sent to NVMe SSD . I have some trobule with the usage of fio‘s fua fuction。
fio3.37 --ioengine=io_uring --thread --size=100% --direct=1 --group_reporting --name=test --numjobs=1 --bs=4k --iodepth=1 --writefua=1 --readfua=1 --filename=/dev/nvme0n1 --rw=randwrite --time_based --do_verify=1 -verify_dump=1 --verify_backlog=1 --runtime=21600 --output=a.txt>

**Environment**: <ubuntu22.04>

**fio version**: <fio3.37>

**Reproduction steps**
<fio3.37 --ioengine=io_uring --thread --size=100% --direct=1 --group_reporting --name=test --numjobs=1 --bs=4k --iodepth=1 --writefua=1 --readfua=1 --filename=/dev/nvme0n1 --rw=randwrite --time_based --do_verify=1 -verify_dump=1 --verify_backlog=1 --runtime=21600 --output=a.txt>

**Comment by sitsofe** [comment]
The [`readfua` and `writefua`  options are documented](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-readfua) as being engine specific parameters for the the [sg ioengine](https://fio.readthedocs.io/en/latest/fio_doc.html#i-o-engine). Notice how the commands you are referencing are in the [I/O engine specific parameters section](https://fio.readthedocs.io/en/latest/fio_doc.html#i-o-engine-specific-parameters) and the ioengines that support a given command are inside the square brackets. As such, it is not a bug that they don't work with the io_uring engine.

**Comment by 18888024924** [comment]
Dear engineer
what I am referring to is [1761](https://github.com/axboe/fio/pull/1761) Compile Fio using Master's package
It is mentioned here that 'write fua' and 'read fua' were added to the io_uring. 
My understanding is that the fua_flag of 0x4000 will be passed in the nvme_read and nvme_write command's cdw12. 
In fact, when writefua and readfua are set to 1, fua_flag passed down is 0.
So I'm a bit confused, not sure if this feature has not been fully implemented yet.

**Comment by axboe** [comment]
You need to use passthrough with io_uring for that, it won't work with normal file system access. Fio should probably warn about that...

**Comment by vincentkfu** [comment]
You will also need to use fio 3.38 for those options.
