### ISSUE TITLE
fio dying with "fio seems to be stuck grabbing stat_sem, forcibly exiting"

### ISSUE THREAD

**Issue by tjodork** [axboe/fio#1846]
**Please acknowledge the following before creating a ticket**

- [x] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<!
running the following jobfile

[global]
bs=4k
direct=1
buffered=0
iodepth=1
numjobs=1
group_reporting=1
rw=randwrite
percentage_random=90
rwmixread=0
rwmixwrite=0
ioengine=libaio
runtime=3300
time_based=1
norandommap
randrepeat=0
ramp_time=60
random_generator=tausworthe64
nice=19 
prio=0 
prioclass=1 
unified_rw_reporting=1
size=100%
[job1]
filename=/dev/dm-53
new_group
[job2]
filename=/dev/dm-54
new_group
[job3]
filename=/dev/dm-65
new_group
[job4]
filename=/dev/dm-76
new_group
[job5]
filename=/dev/dm-85
new_group
[job6]
filename=/dev/dm-86
new_group
[job7]
filename=/dev/dm-87
new_group
[job8]
filename=/dev/dm-88
new_group
[job9]
filename=/dev/dm-89
new_group
[job10]
filename=/dev/dm-90
new_group
[job11]
filename=/dev/dm-55
new_group
[job12]
filename=/dev/dm-56
new_group
[job13]
filename=/dev/dm-57
new_group
[job14]
filename=/dev/dm-58
new_group
[job15]
filename=/dev/dm-59
new_group
[job16]
filename=/dev/dm-60
new_group
[job17]
filename=/dev/dm-61
new_group
[job18]
filename=/dev/dm-62
new_group
[job19]
filename=/dev/dm-63
new_group
[job20]
filename=/dev/dm-64
new_group
[job21]
filename=/dev/dm-66
new_group
[job22]
filename=/dev/dm-67
new_group
[job23]
filename=/dev/dm-68
new_group
[job24]
filename=/dev/dm-69
new_group
[job25]
filename=/dev/dm-70
new_group
[job26]
filename=/dev/dm-71
new_group
[job27]
filename=/dev/dm-72
new_group
[job28]
filename=/dev/dm-73
new_group
[job29]
filename=/dev/dm-74
new_group
[job30]
filename=/dev/dm-75
new_group
[job31]
filename=/dev/dm-35
new_group
[job32]
filename=/dev/dm-77
new_group
[job33]
filename=/dev/dm-78
new_group
[job34]
filename=/dev/dm-79
new_group
[job35]
filename=/dev/dm-80
new_group
[job36]
filename=/dev/dm-81
new_group
[job37]
filename=/dev/dm-82
new_group
[job38]
filename=/dev/dm-83
new_group
[job39]
filename=/dev/dm-84
new_group
[job40]
filename=/dev/dm-36
new_group
[job41]
filename=/dev/dm-45
new_group
[job42]
filename=/dev/dm-46
new_group
[job43]
filename=/dev/dm-47
new_group
[job44]
filename=/dev/dm-48
new_group
[job45]
filename=/dev/dm-49
new_group
[job46]
filename=/dev/dm-50
new_group
[job47]
filename=/dev/dm-51
new_group
[job48]
filename=/dev/dm-52
new_group
[job49]
filename=/dev/dm-37
new_group
[job50]
filename=/dev/dm-38
new_group
[job51]
filename=/dev/dm-39
new_group
[job52]
filename=/dev/dm-40
new_group
[job53]
filename=/dev/dm-41
new_group
[job54]
filename=/dev/dm-42
new_group
[job55]
filename=/dev/dm-43
new_group
[job56]
filename=/dev/dm-44
new_group
[job57]
filename=/dev/dm-0
new_group
[job58]
filename=/dev/dm-1
new_group
[job59]
filename=/dev/dm-12
new_group
[job60]
filename=/dev/dm-23
new_group
[job61]
filename=/dev/dm-29
new_group
[job62]
filename=/dev/dm-30
new_group
[job63]
filename=/dev/dm-31
new_group
[job64]
filename=/dev/dm-32
new_group
[job65]
filename=/dev/dm-33
new_group
[job66]
filename=/dev/dm-34
new_group
[job67]
filename=/dev/dm-2
new_group
[job68]
filename=/dev/dm-3
new_group
[job69]
filename=/dev/dm-4
new_group
[job70]
filename=/dev/dm-5
new_group
[job71]
filename=/dev/dm-6
new_group
[job72]
filename=/dev/dm-7
new_group
[job73]
filename=/dev/dm-8
new_group
[job74]
filename=/dev/dm-9
new_group
[job75]
filename=/dev/dm-10
new_group
[job76]
filename=/dev/dm-11
new_group
[job77]
filename=/dev/dm-13
new_group
[job78]
filename=/dev/dm-14
new_group
[job79]
filename=/dev/dm-15
new_group
[job80]
filename=/dev/dm-16
new_group
[job81]
filename=/dev/dm-17
new_group
[job82]
filename=/dev/dm-18
new_group
[job83]
filename=/dev/dm-19
new_group
[job84]
filename=/dev/dm-20
new_group
[job85]
filename=/dev/dm-21
new_group
[job86]
filename=/dev/dm-22
new_group
[job87]
filename=/dev/dm-24
new_group
[job88]
filename=/dev/dm-25
new_group
[job89]
filename=/dev/dm-26
new_group
[job90]
filename=/dev/dm-27
new_group
[job91]
filename=/dev/dm-28
new_group
[job92]
filename=/dev/dm-153
new_group
[job93]
filename=/dev/dm-154
new_group
[job94]
filename=/dev/dm-165
new_group
[job95]
filename=/dev/dm-176
new_group
[job96]
filename=/dev/dm-187
new_group
[job97]
filename=/dev/dm-188
new_group
[job98]
filename=/dev/dm-189
new_group
[job99]
filename=/dev/dm-190
new_group
[job100]
filename=/dev/dm-191
new_group
[job101]
filename=/dev/dm-192
new_group
[job102]
filename=/dev/dm-155
new_group
[job103]
filename=/dev/dm-156
new_group
[job104]
filename=/dev/dm-157
new_group
[job105]
filename=/dev/dm-158
new_group
[job106]
filename=/dev/dm-159
new_group
[job107]
filename=/dev/dm-160
new_group
[job108]
filename=/dev/dm-161
new_group
[job109]
filename=/dev/dm-162
new_group
[job110]
filename=/dev/dm-163
new_group
[job111]
filename=/dev/dm-164
new_group
[job112]
filename=/dev/dm-166
new_group
[job113]
filename=/dev/dm-167
new_group
[job114]
filename=/dev/dm-168
new_group
[job115]
filename=/dev/dm-169
new_group
[job116]
filename=/dev/dm-170
new_group
[job117]
filename=/dev/dm-171
new_group
[job118]
filename=/dev/dm-172
new_group
[job119]
filename=/dev/dm-173
new_group
[job120]
filename=/dev/dm-174
new_group
[job121]
filename=/dev/dm-175
new_group
[job122]
filename=/dev/dm-177
new_group
[job123]
filename=/dev/dm-178
new_group
[job124]
filename=/dev/dm-179
new_group
[job125]
filename=/dev/dm-180
new_group
[job126]
filename=/dev/dm-181
new_group
[job127]
filename=/dev/dm-182
new_group
[job128]
filename=/dev/dm-183
new_group
[job129]
filename=/dev/dm-184
new_group
[job130]
filename=/dev/dm-185
new_group
[job131]
filename=/dev/dm-186
new_group
[job132]
filename=/dev/dm-137
new_group
[job133]
filename=/dev/dm-138
new_group
[job134]
filename=/dev/dm-145
new_group
[job135]
filename=/dev/dm-146
new_group
[job136]
filename=/dev/dm-147
new_group
[job137]
filename=/dev/dm-148
new_group
[job138]
filename=/dev/dm-149
new_group
[job139]
filename=/dev/dm-150
new_group
[job140]
filename=/dev/dm-151
new_group
[job141]
filename=/dev/dm-152
new_group
[job142]
filename=/dev/dm-139
new_group
[job143]
filename=/dev/dm-140
new_group
[job144]
filename=/dev/dm-141
new_group
[job145]
filename=/dev/dm-142
new_group
[job146]
filename=/dev/dm-143
new_group
[job147]
filename=/dev/dm-144
new_group
[job148]
filename=/dev/dm-97
new_group
[job149]
filename=/dev/dm-98
new_group
[job150]
filename=/dev/dm-109
new_group
[job151]
filename=/dev/dm-120
new_group
[job152]
filename=/dev/dm-131
new_group
[job153]
filename=/dev/dm-132
new_group
[job154]
filename=/dev/dm-133
new_group
[job155]
filename=/dev/dm-134
new_group
[job156]
filename=/dev/dm-135
new_group
[job157]
filename=/dev/dm-136
new_group
[job158]
filename=/dev/dm-99
new_group
[job159]
filename=/dev/dm-100
new_group
[job160]
filename=/dev/dm-101
new_group
[job161]
filename=/dev/dm-102
new_group
[job162]
filename=/dev/dm-103
new_group
[job163]
filename=/dev/dm-104
new_group
[job164]
filename=/dev/dm-105
new_group
[job165]
filename=/dev/dm-106
new_group
[job166]
filename=/dev/dm-107
new_group
[job167]
filename=/dev/dm-108
new_group
[job168]
filename=/dev/dm-110
new_group
[job169]
filename=/dev/dm-111
new_group
[job170]
filename=/dev/dm-112
new_group
[job171]
filename=/dev/dm-113
new_group
[job172]
filename=/dev/dm-114
new_group
[job173]
filename=/dev/dm-115
new_group
[job174]
filename=/dev/dm-116
new_group
[job175]
filename=/dev/dm-117
new_group
[job176]
filename=/dev/dm-118
new_group
[job177]
filename=/dev/dm-119
new_group
[job178]
filename=/dev/dm-121
new_group
[job179]
filename=/dev/dm-122
new_group
[job180]
filename=/dev/dm-123
new_group
[job181]
filename=/dev/dm-124
new_group
[job182]
filename=/dev/dm-125
new_group
[job183]
filename=/dev/dm-126
new_group
[job184]
filename=/dev/dm-127
new_group
[job185]
filename=/dev/dm-91
new_group
[job186]
filename=/dev/dm-92
new_group
[job187]
filename=/dev/dm-93
new_group
[job188]
filename=/dev/dm-94
new_group
[job189]
filename=/dev/dm-95
new_group
[job190]
filename=/dev/dm-96
new_group
[job191]
filename=/dev/dm-128
new_group
[job192]
filename=/dev/dm-129
new_group
[job193]
filename=/dev/dm-130
new_group

and then  Signalling for fio to report results with command kill -USR1 xxxxxx    (the psid)

normally it returns the data correctly as shown here

Signalling for fio to resport results with command kill -USR1 3051666     --------------------------------------------
Here is response 
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.6%][r=4893MiB/s][r=1253k IOPS][eta 05m:08s]
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.7%][r=4902MiB/s][r=1255k IOPS][eta 05m:06s]
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.7%][r=4934MiB/s][r=1263k IOPS][eta 05m:05s]
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.7%][r=4941MiB/s][r=1265k IOPS][eta 05m:04s]
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.7%][r=4916MiB/s][r=1258k IOPS][eta 05m:03s]
Jobs: 192 (f=192): [M(46),X(1),M(146)][93.8%][r=4911MiB/s][r=1257k IOPS][eta 05m:02s]
There was 36317 lines in datafile /tmp/bgresults
12-04-2024_11.17.43 - Line 430 : dm-53  iops=6599.00  bw= 27.02 MB/s  rt=2424.23 ms
dm-54  iops=6630.57  bw= 27.16 MB/s  rt=2412.71 ms
dm-65  iops=6611.58  bw= 27.08 MB/s  rt=2419.62 ms
dm-76  iops=6627.34  bw= 27.15 MB/s  rt=2413.86 ms

*****************************************************
but when it fails it returns multiple lines of below (and kills my test)
*****************************************************
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
fio seems to be stuck grabbing stat_sem, forcibly exiting
>

**Environment**: <!
Linux bidooftos 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 18 14:35:40 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
 Static hostname: bidooftos
       Icon name: computer-server
         Chassis: server ?
      Machine ID: fc26c6078c234b21935fd6c5d89ca764
         Boot ID: c14e7a7d86fe4a5e983f335ee10f5a3d
Operating System: Red Hat Enterprise Linux 9.5 (Plow)     
     CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
          Kernel: Linux 5.14.0-427.42.1.el9_4.x86_64
    Architecture: x86-64
Firmware Version: 0.97
>

**fio version**: <!fio-3.35>

**Reproduction steps**

**Comment by vincentkfu** [comment]
There have been a few changes in the helper thread code implicated here since fio 3.35 (although nothing seems like an obvious fix). Can you try fio 3.38 or the tip of master?

If you still see the issue, can you provide an easier way to reproduce the issue?

**Comment by tjodork** [comment]
wow, THAT fixed it!  thx for the amazing support

**Comment by vincentkfu** [comment]
This might be the patch that fixed it but I don't know for sure:

```
commit 864742594519946b0bcf9f5f351676b01772b601
Author: Shai Levy <58184723+shailevi23@users.noreply.github.com>
Date:   Mon Oct 16 14:29:04 2023 +0300

    helper_thread: fix pthread_sigmask typo.

    Signed-off-by: Shai Levy <shailevy23@gmail.com>.

diff --git a/helper_thread.c b/helper_thread.c
index 53dea44b..2a9dabf5 100644
--- a/helper_thread.c
+++ b/helper_thread.c
@@ -106,13 +106,14 @@ static int read_from_pipe(int fd, void *buf, size_t len)

 static void block_signals(void)
 {
-#ifdef HAVE_PTHREAD_SIGMASK
+#ifdef CONFIG_PTHREAD_SIGMASK
        sigset_t sigmask;

+       int ret;
+
        ret = pthread_sigmask(SIG_UNBLOCK, NULL, &sigmask);
        assert(ret == 0);
        ret = pthread_sigmask(SIG_BLOCK, &sigmask, NULL);
-       assert(ret == 0);
 #endif
 }
```
