### ISSUE TITLE
Multiple jobs miscompare issue

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#185]
Hi,

I hit a miscompare while doing raw ios using multiple jobs, I want to be able to increase the load on the device and check for data integrity at the same time. 

I see a waring that states "Multiple writers may overwrite blocks that belong to other jobs". 
 
Command line parameters:
fio --name=test --filename=/dev/nvme0n1 --rw=randrw --ioengine=sync --iodepth=16 --bs=128k --numjobs=2 --verify_pattern=0x1ea5fbda --do_verify=1 --verify_fatal=1 --verify_dump=1 --verify_backlog=1000 --buffered=0 --runtime=3600 --time_based=1 --offset=0 --io_size=1759218604441B --verify=pattern

How else can i increase the load and do data verification at the same time?

Regards,
Shiva Pahwa

**Comment by shivapahwa** [comment]
I also see a lot of messages:
err=84/file:io_u.c:1900, func=io_u_sync_complete, error=Invalid or incomplete multiple or wide character

**Comment by axboe** [comment]
Like fio warns you, you can't have multiple threads all writing to the same space and expect verification to work. You are currently running sync (QD=1) IO. One way to ramp up the load would be to set ioengine=libaio and direct=1, then your iodepth=16 would actually mean something. Right now it's forced at iodepth=1, since you have ioengine=sync.

**Comment by shivapahwa** [comment]
Thanks for the information, I was trying to do raw IOs on the device and the data pattern is the same for both jobs. Even if one job steps over the other job the verification should not fail.

Please correct me if my understanding is wrong. 

If i use libaio, do you recomment me using  a single thread and high queue depth for data verification?

**Comment by shivapahwa** [comment]
I was going through the open issues and came across the following one:
https://github.com/axboe/fio/issues/163

There is a mention about data verification. As long as the pattern is the same file verification should not fail, does this not apply to raw write verifies to block devices?

Should we just increase QD and keep numjobs to 1(in the same address space), if we want to do verify?

**Comment by axboe** [comment]
Using multiple jobs that keeps writing on top of each other is a bad idea. Either partition the device and run each of them on separate partitions, or drive a higher load with a higher queue depth.

Depending on what kind of verification is used, multiple jobs may or may not verify correctly. You'd need to seed them identically too, so they are producing the same random content as well. And then you'd get identical offsets too, so...

**Comment by shivapahwa** [comment]
To work around the miscompare issue, I have created N threads and assigned each thread a region:

The below test does random/sequential read-write on both t1 and t2 each have a starting offset and size. I hope this approach is good enough for avoiding threads writing over each other. Please advice if my understanding is incorrect.

sudo ./fio  --name=global --filename=/dev/nvme0n1 --rw=randrw --ioengine=sync --iodepth=16 --bs=128K --verify_pattern=0x1f4266d --do_verify=1 --verify_fatal=1 --verify_dump=1 --verify_backlog=4086 --verify_state_save=1 --buffered=0 --runtime=2 --time_based=1 --verify=pattern --name=t1 --offset=0 --size=862016985104B --name=t2 --offset=1717986918 --size=879609171148B

Using a similar approach in case of reverse sequential/random read-writes.

sudo ./fio  --name=global --filename=/dev/nvme0n1 --rw=write:-256K --ioengine=libaio --iodepth=1 --bs=128K --numjobs=128 --do_verify=1 --verify_fatal=1 --verify_dump=1 --verify_backlog=1000 --runtime=2 --time_based=1 --verify=pattern --verify_pattern=0x2eb46c1c --name=t1 --offset=206158430 --size=105552985194B --name=t2 --offset=412316860 --size=105552985194B --name=t3 --offset=618475290 --size=105552985194B --name=t4 --offset=824633720 --size=105552985194B --name=t5 --offset=1030792150 --size=105552985194B --name=t6 --offset=1236950580 --size=105552985194B --name=t7 --offset=1443109011 --size=105552985194B --name=t8 --offset=1717986918 --size=105552985194B
