### ISSUE TITLE
libaio (and posixaio) and direct=1 error 

### ISSUE THREAD

**Issue by nitinmathur5** [axboe/fio#186]
I am facing the following error on centos platform.

Test environment
CentOS 6.5
Linux kernel: 3.8.8, 64 bit
FIO version: fio-2.11

I run the following command

`./fio --name=test_workld --ioengine=libaio --direct=1 --rw=randrw --norandommap --randrepeat=0 --rwmixread=40 --rwmixwrite=60 --iodepth=256 --size=100% --numjobs=4 --bssplit=512/4:64k/96 --random_distribution=zoned:50/5:50/95 --overwrite=1 --output=test_op --filename=/dev/nvme0n1 --group_reporting --runtime=1m --time_based
`
This means, I'm using libaio (or posixaio), with a queue depth of 256, and fio is utilizing asynchronous IO engines. But this command results into an error "Invalid argument". If i change the parameter --direct=0, I'm able to issue the command successfully.

Can you help me to understand, why with direct=1, the fio command results in an error  ?

**Comment by axboe** [comment]
You're using a blocksize in fio that is less than the hardware block size. I suspect your nvme device is using 4k sectors, hence you can't use unbuffered accesses in sizes/alignments less than that.
