### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [axboe/fio#189]
I would like to point out that identifiers like "[`__FIO_FSERVICE_NONUNIFORM`](https://github.com/axboe/fio/blob/8c07860de982fabaaf41d44c22aa86aba2539b58/file.h#L41)" and "[`__fio_mutex_init`](https://github.com/axboe/fio/blob/34febb23fa9c7b9b0d54c324effff1a808a8fe6e/mutex.h#L28)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by axboe** [comment]
Fio is written in C, not C++.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by axboe** [comment]
Come on, this is silly. The standard can mandate whatever naming practice it likes, history dictates that lots of programs are written like this. Undefined behavior is nonsense. It implies that the program may work, or it may not. In reality, if we did have a conflict, the compile would error out.

If you'll note, I prefix those names with fio or FIO. Risk of conflict? Practically zero.

If you want to send in patches to make this cleaner, I'll take a look at them on an individual basis.

**Comment by elfring** [comment]
How do you [think about](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") to [achieve improvements in the affected software application domain](https://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/ "GCC Undefined Behavior Sanitizer")?

**Comment by axboe** [comment]
I'll repeat what I wrote before - send in actual patches if you feel there are issues that should be resolved. I don't deal in hypotheticals.
