### ISSUE TITLE
Numa Options Failing

### ISSUE THREAD

**Issue by sheridp** [axboe/fio#190]
fio-2.11-15-g6a89b  (also occurs on fio-2.11-4-g34feb)

Receviing the following error messages:
Bad option \<numa_cpu_nodes=0\>
Bad option \<numa_mem_policy=bind:0\>

Even when trying to run on fio/examples/numa.fio

**Comment by axboe** [comment]
You probably didn't have the numa development libraries installed, when you configured and built fio. If you don't, then fio doesn't have libnuma support and doesn't support those options. Check with:

$ ./fio --cmdhelp | grep numa
numa_cpu_nodes          : NUMA CPU nodes bind
numa_mem_policy         : NUMA memory policy setup

Check if you have libnuma-dev or libnuma-devel installed, depending on your distro.

**Comment by sheridp** [comment]
That was it; thanks!  On Centos 6.7 it's numactl-devel.
