### ISSUE TITLE
Unable to set iodepth_batch_submit to 0

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#191]
I was wanting to set the flag iodepth_batch_submit to curent QD. 
FIO fails with error, min value out of range: 0 (1 min).

FIO version: 2.9
OS: Cent 7.2

Documentation:
iodepth_batch_submit=int
iodepth_batch=int This defines how many pieces of IO to submit at once.
		It defaults to 1 which means that we submit each IO
		as soon as it is available, but can be raised to submit
		bigger batches of IO at the time. If it is set to 0 the iodepth
		value will be used.

**Comment by axboe** [comment]
This is fixed in the 2.12 release.
