### ISSUE TITLE
FIO hangs when you set io_submit_more to offload

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#192]
FIO stalls with out doing any IO operations if we set the io_submit_mode to offload. I am using a low runtime, this is just to test my parameters are correctly set.
I have disabled all the latency mesurements.

Fio version: 2.9
OS: Cent 7.2

rw=randrw
ioengine=libaio
iodepth=512
numjobs=2
bs=128K
iodepth_batchsubmit=512
iodepth_batch_complete=0
io_submit_mode=offload
verify=pattern
verify_pattern=0xABAB
do_verify=1
verify_fatal=1
verify_dump=1
verify_backlog=100
runtime=10
time_based=1

Let me know if you need any other information information

**Comment by axboe** [comment]
I'll take a look at this, when I get back from vacation.

**Comment by axboe** [comment]
Can you send the complete job file that you used? Also, please reproduce with the latest release first, there has been fixes to the offload mechanism since the 2.9 release.

**Comment by shivapahwa** [comment]
FIO verions: 2.12
OS: Cent 7.2 x86_64
Parameters:
--filename=/dev/XXX --rw=randrw --ioengine=libaio --iodepth=512 --io_submit_mode=offload --iodepth_batch_submit=1024 --iodepth_batch_complete=0 --bs=128K --numjobs=2 --verify_pattern=0xAA --do_verify=1 --verify_fatal=1 --verify_dump=1 --verify_backlog=16344 --runtime=60 --time_based=1 --disable_lat-1 --diable_slat=1 --disable_clat=1 --disable_bw=1 --clat_percentiles=0 --verify=pattern --randseed=1234

**Comment by axboe** [comment]
You do realize that this will spawn up to 2x512, 1024 threads doing IO? It should not hang, of course, but it'll be really slow unless you have thousands of CPUs in your box as well.

**Comment by axboe** [comment]
I can reproduce it. Seems to be tied to the verification, for some reason. I'll debug it.

**Comment by shivapahwa** [comment]
Yes, i understand that, wanted to increase the CPU utilization while doing IOS.

**Comment by sitsofe** [comment]
@shivapahwa can you still reproduce this issue with a recent fio?

**Comment by shivapahwa** [comment]
@sitsofe I dont have access to the systems to try to reproduce this issue. Will update you soon with the findings.

**Comment by shivapahwa** [comment]
Cannot reproduce the hang, fio handles the overflow condition by displaying the posix_fallocate error.
