### ISSUE TITLE
FIO Not Closing Processes?

### ISSUE THREAD

**Issue by rspotoaz** [axboe/fio#198]
Hello.  I know this is from an older version of fio, however we're using this version because (as of a few months ago) the committed current version exhibited this behavior in greater frequency.  We're seeing a high number of cases where the process does not complete normally.  As if one of the forked processes gets "hung".  This is an intermittent issue.  The server in question actually contains four nodes, and the other three nodes completed the process just fine.  Don't know if there was actually just some kind of failure that wasn't caught by the parent or it just didn't clean up properly.

Are you able to glance at the attached log and provide some thoughts?

[log.txt](https://github.com/axboe/fio/files/342300/log.txt)

One of the disks is a 1TB SSD, the rest are 2TB HDDs.

Note that I shortened the attached log, as the last line(s) is repeated ad-nausea until the processes are killed.

**Comment by axboe** [comment]
Can you try and reproduce on the latest release, 2.12? I don't mind looking into this, but I need it reproduced on the latest version first.

**Comment by rspotoaz** [comment]
I will work on that, thank you!

**Comment by sitsofe** [comment]
@rspotoaz Any luck reproducing this with the latest fio release?

**Comment by rspotoaz** [comment]
I'm so sorry, I thought I responded to this.  I was not able to reproduce the issue as of version 2.1.2.  Thank you!
