### ISSUE TITLE
Can FIO generate the same IOPS table for latency distribution like IOMETER

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#199]
When running iometer, it tells you roughly how many IOPS are landing in latency bucket in table format so it can be plotted based on the granularity. 
![image](https://cloud.githubusercontent.com/assets/19417434/16529387/74ba997a-3f77-11e6-94a0-0f66ac77f396.png)

I know the FIO summary tells you the QoS percentile which can be reverse engineered to do the maths and get that information but still the break down will really help in analyzing the generating the latency profiles. 
Looking for support and comments here..

**Comment by axboe** [comment]
Fio dumps something similar to that:

    lat (usec) : 20=0.01%, 50=1.57%, 100=52.73%, 250=40.58%, 500=3.51%
    lat (usec) : 750=1.32%, 1000=0.23%
    lat (msec) : 2=0.04%, 4=0.02%

just in percentages, instead of absolute numbers. This isn't configurable, the buckets are fixed, but it ranges from 2 usec to >= 2 seconds.

**Comment by akoundal** [comment]
There is some confusion with respect to the different latencies the tool reports:  
cLAT -> this is the main one which all customer report or look for the data. Also which generates the QoS percentile.
lat = > (clat +slat) never matches so not sure what it represents. ?? 
slat(submission) 
Appreciate your time  here :).

**Comment by sitsofe** [comment]
@akoundal I'm not sure I understand the question. Are you asking why lat never matches (clat + slat) or are you asking something else?

**Comment by akoundal** [comment]
@sitsofe yes i am clear on the lat/slat...thanks for the follow up though ....
thx for the support ...:).
