### ISSUE TITLE
cpuio not recognized as a input  parameter

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#202]
Is cpuio a depricated option?

FIO: 2.12
OS: Cent 7.2

**Comment by axboe** [comment]
No. You'll need to be more specific. What are you running, how does it fail, what were your expectations?

**Comment by shivapahwa** [comment]
My Bad, i used the options incorrectly. I was using cpuio as a regular FIO option. Corrected the job file by spcifying the ioengine as cpuio and it seems to work just fine.
