### ISSUE TITLE
Feature request - customizable bandwidth unit?

### ISSUE THREAD

**Issue by fangchin** [axboe/fio#204]
Up to the most recent fio (2.12 as of this post), the bandwidth has always been output in units of KB/s.  We are using SSDs, especially NVMe SSDs exclusively, and such a usage is becoming more and more common, especially once NVMe over Fabrics gets into the main stream.  So, perhaps it's time to make the bandwidth unit customizable in  Gbps, Mbps etc? 

Also, fio seems to treat GB, MB. KB and GiB, MiB, KiB etc exactly the opposite of the common practice in the industry.  As far as I can tell, using M as an example

1. In Linux, M bytes means 1024 x 1024 = 2 ** 10 bytes
2. In the storage industry, MB = 1,000,000 bytes = 10 **6 bytes
3. In computing, MiB = 1024 x 1024 = 2 * 10 bytes

See [https://en.wikipedia.org/wiki/Mebibyte](url)

**Comment by sitsofe** [comment]
This request is an amalgamation of issue #103 and issue #62 .

**Comment by fangchin** [comment]
You are correct.  Should have double-checked the earlier issues first. Thanks!
