### ISSUE TITLE
Flash Memory loop test sample

### ISSUE THREAD

**Issue by zhingket** [axboe/fio#205]
Hi, sorry i'm noob to this, and i'm trying to find an example on how to loop 5 files to write each one and read them until depletion or error on the flash memory, hope you can help

**Comment by axboe** [comment]
Assuming you want to verify the actual contents, you could do something ala:

    [loop-write-verify]
    rw=write
    verify=crc32c
    nrfiles=5
    size=128m
    bs=4k
    direct=1
    runtime=365d
    time_based=1

which would run for 1 year, repeatedly writing those files, then reading them back and verifying the contents.

**Comment by axboe** [comment]
Change `nr_files` and `size=128m` for a different number of files, or different total size of the file set, of course.

**Comment by zhingket** [comment]
Thanks jens, here is my scenario, i have 5 set of file size (1kb, 5kb, 900kb, 1MB & 72MB) to be written and read 600k times on an 8gb sd card then give the summary/report. Can you help me on this?! Thanks in advance

**Comment by axboe** [comment]
Just do a separate section for each, set the `size=` appropriately, and set `loops=` to the number of iterations.

**Comment by zhingket** [comment]
Thanks Jens for the quick response, I tried this one, it ran, but I am not sure if I wrote it correctly

[1kb_file]
rw=write
verify=crc32c
size=1kb
bs=4k
direct=1

[5kb_file]
rw=write
verify=crc32c
size=5kb
bs=4k
direct=1

[900kb_file]
rw=write
verify=crc32c
size=900kb
bs=4k
direct=1

[1Mb_file]
rw=write
verify=crc32c
size=1mb
bs=4k
direct=1

[72Mb_file]
rw=write
verify=crc32c
size=72m
bs=4k
direct=1

loops=10

**Comment by axboe** [comment]
Put the shared parts in a [global] section:

    [global]
    rw=write
    verify=crc32c
    direct=1
    loops=10

and have the job sections be just what they need. Additionally, for the two small jobs, you can't use a block size that doesn't align to the full size, at least not if  you want all the IO to be done. So I'd use bs=1k for the 1k/5k sections.

**Comment by zhingket** [comment]
something like this?

[global]
rw=write
verify=crc32c
direct=1
loops=10

[1kb_file]
size=1kb
bs=1k

[5kb_file]
size=5kb
bs=1k

[900kb_file]
size=900kb
bs=4k


[1Mb_file]
size=1mb
bs=4k

[72Mb_file]
size=72m
bs=4k

**Comment by axboe** [comment]
Yes, that should work. Then just bump loops to 600k or whatever you want, and you should be good to go.

**Comment by axboe** [comment]
But you probably want all jobs to continue for a long time. Even 600k loops of the 1k write/read will be over pretty soon. Why not just time limit it? Remove `loops=` and do `runtime=100d` (for 100 days, for instance) and `time_based=1` to force all jobs to continue running for 100 days. Set `exitall_on_error` in the global section, to force them all to terminate if one of the sees an error.

**Comment by zhingket** [comment]
Thank you very much jens!
