### ISSUE TITLE
Linux AIO support  

### ISSUE THREAD

**Issue by johnzzhao** [axboe/fio#206]
I run ../configure, and got output with Linux AIO support   no.  

However, when I did yum list, it shows:
Loaded plugins: langpacks, product-id, rhui-lb, search-disabled-repos
Installed Packages
libaio.x86_64                                                                     0.3.109-13.el7                

Any idea what I need to do?

Thansk, 

John

**Comment by johnzzhao** [comment]
I am installing fio-2.12 on Redhat 7.1.

**Comment by xjtuwjp** [comment]
You need install development libaio header package, eg:
libaio-devel? I don't know the exactly name of that package on RHEL, but
should be similar.

2016-07-15 3:30 GMT+02:00 johnzzhao <notifications@github.com>:

**Comment by sitsofe** [comment]
@johnzzhao - is there an issue here with libaio-devel installed?

**Comment by axboe** [comment]
Closing, as others have mentioned, you need the devel version of the library as well, when you are building from source. I do believe that libaio-devel is the right name, on apt based systems it's usually libaio-dev.
