### ISSUE TITLE
fio2gnuplot shows some odd lines in both IOPS and BW plots

### ISSUE THREAD

**Issue by fangchin** [axboe/fio#207]
I have been testing a few Intel DC P3700 U.2 1.6TB NVMe SSDs using `fio-2.12`, mainly focusing on 4K random writes. Following SNIA's PTS [http://www.snia.org/sites/default/files/SSS_PTS_Enterprise_v1.1.pdf](url), I did the following:

1. **Remove all the data on the drive**: using Intel's `isdct delete` comand
1. **Workload-independent preconditioning**:  using fio to sequentially fill the entire device _twice_ in raw, with `bs=128K`
1. **Workdload dependent preconditioning**: using fio to do 4K random writes to fill the entire device _once_.  The results are logged for plotting IOPS and BW. The following is a typical job file for this part:

```
[4K-random-write]
description=4K random write
filename=/dev/nvme4n1
ioengine=libaio
direct=1
bs=4k
rw=randwrite
iodepth=10
thread=1
numjobs=12
buffered=0
runtime=3600
randrepeat=0
norandommap
refill_buffers
log_avg_msec=1000
group_reporting=1
per_job_logs=0
write_bw_log=nvme4n1_4krw
write_iops_log=nvme4n1_4krw 
```
The run results looked reasonable and consistent with the 4K random write performance that Intel has published in this family's spec: [http://www.intel.com/content/www/us/en/solid-state-drives/ssd-dc-p3700-spec.html](url)

But, when I tried to use `fio2gnuplot` to plot the log files, I always see some odd looking lines in the plots, both for IOPS and BW:

![nvme4n1_4krw_iops-2draw](https://cloud.githubusercontent.com/assets/1431544/16897598/229e591a-4b6b-11e6-8a80-6611d5856a4e.png)
![nvme4n1_4krw_bw-2draw](https://cloud.githubusercontent.com/assets/1431544/16897600/266ff0d0-4b6b-11e6-9693-c92b30c04723.png)

I tried several drives, and different logging resolutions via the `log_avg_msec`, and got the same results.  Would appreciate a hint why this is so and whether there is a way to rid of these lines.  The log files for the above example drive are also attached.  The way I generated the plots are:
```
[root@fs11 tmp]# fio2gnuplot -p nvme4n1_4krw_iops.log -g -d nvme4
1 files Selected with pattern 'nvme4n1_4krw_iops.log'
 |-> nvme4n1_4krw_iops.log

Running gnuplot Rendering

Rendering traces are available in nvme4/ directory
[root@fs11 tmp]# fio2gnuplot -p nvme4n1_4krw_bw.log -g -d nvme4
1 files Selected with pattern 'nvme4n1_4krw_bw.log'
 |-> nvme4n1_4krw_bw.log

Running gnuplot Rendering

Rendering traces are available in nvme4/ directory
```

BTW, the corresponding 
nvme4n1_4krw_bw-2Dsmooth.png and 
nvme4n1_4krw_iops-2Dsmooth.png
are free of these odd looking straight lines.

[nvme4n1_4krw_iops.zip](https://github.com/axboe/fio/files/367580/nvme4n1_4krw_iops.zip)
[nvme4n1_4krw_bw.zip](https://github.com/axboe/fio/files/367581/nvme4n1_4krw_bw.zip)

**Comment by cronburg** [comment]
@fangchin : `fio2gnuplot` expects the bandwidth logs for different threads to be in different log files, i.e. without `per_job_logs` disabled. Those lines you're seeing are from the end of one thread's bandwidth data to the beginning of the next thread's data.

If you're looking for an average (or total) bandwidth across your 12 threads, take a look at `fiologparser.py` with either `-a` or `-s` option, i.e.:

    $ fiologparser.py -a ../nvme4n1_4krw.* > out.log # 12 different nvme4n2_4krw files here
    $ ipython --pylab
    In [1]: data = loadtxt("out.log", delimiter=',')
    In [2]: t, bw = transpose(data)
    In [3]: plot(t / 1000.0, bw, '-o', markersize=2)

Resulting in a similar graph to the one you already have, but averaged across the threads:

![averaged across threads](http://cronburg.com/fio/bw_sum.png)

**Comment by fangchin** [comment]
@cronburg.  Excellent!  Thanks for the pointer.
