### ISSUE TITLE
Is there a way to keep randomly generated data unique between each threads?

### ISSUE THREAD

**Issue by 7rui** [axboe/fio#209]
For example, I use dedupe=0, numjobs=4 writing to one file, and I got a file with duplication rate of 75%.
How can fio generate a file with 0% dup rate when dedupe=0 is set?

**Comment by sitsofe** [comment]
@7rui: Did you use `refill_buffers` (https://github.com/axboe/fio/blob/fio-2.12/HOWTO#L607 ) buffers too?

**Comment by 7rui** [comment]
I found I can set randseed to solve this.
