### ISSUE TITLE
Unrealistic random write performance when running a single job

### ISSUE THREAD

**Issue by sheridp** [axboe/fio#210]
Using the following command:

`./fio --bs=4k --ioengine=libaio --direct=1 --numjobs=1 --norandommap --time_based --runtime=5m --ramp_time=5m  --filename=/dev/nvme0n1 --iopsavgtime=10000 --name=4KRW --rw=randwrite --iodepth=64`

I will get IOPS numbers that bounce all over  and are way too high for this drive  (in the per second stdout and overall averages).  If, however, I add `--numjobs=8` and change `--iodepth=8`, the numbers stabilize and are more in line with what I expect from the drive.

Using latest commit (eec97b935abb714bf498c96a8f18ec1104c75fd4); also see this problem in tags 2.3 and 2.11.

**Comment by sitsofe** [comment]
Do the IOPs look strange without `iopsavgtime` and `norandommap` too?

**Comment by sheridp** [comment]
Yes; I removed those two options and still see the problem.

 It's very strange:  If I fire up a vdbench instance while fio is running, let it go for a few minutes, and then kill it, fio will go back to reporting normal numbers for a short while. It will then return to numbers that are approximately  3X - 5X too high.

Given this, and the fact that problem disappears when numjobs is higher, it must have something to do with the rate calculations and an actual queue depth that is too low (ie. with only one job, maybe fio cannot keep the queue depth at 64).  When I have time, I will dig into the source to see if/how set QD is used in the IOPS calculation.

**Comment by sitsofe** [comment]
Does iostat give a sensible numbers while this is happening? Is it possible to tell if something similar happens when you use the nullblk device (as that would make it easier for others to reproduce the problem too but you would need to know the "true" throughput it could do)...

**Comment by sheridp** [comment]
iostat is also giving unusually high numbers, so it's hard to know whom to trust.

But it is very strange that --numjobs=1, --iodepth=64  would give drastically different numbers from --numjobs=64, --iodepth=1 (the latter of which matches vdbench performance).  In both cases, mpstat is showing all processors mostly idle and iowait %  = 0.

**Comment by sheridp** [comment]
I think the problem was with --randrepeat.  It defaults to on, but once I set it off,  I get the numbers I expect with --numjobs=1.  So I must have been running into some sort of drive caching / higher speed when writing a repeated pattern (which I did not think would be an issue for 10m runs, but I guess it is).
