### ISSUE TITLE
Offset does not work

### ISSUE THREAD

**Issue by shaoweei** [axboe/fio#218]
Offset parameter is not valid at fio 2.12 and fio 2.13, but 2.2.13 is work right.
please check it, thank you :).

**Comment by axboe** [comment]
Please provide more details than this. A basic bug report includes:

1) What you ran and how
2) Your expectations of the outcome
3) How the actual outcome differs.

Thanks.

**Comment by axboe** [comment]
Try with current -git, and it should work again.

**Comment by shaoweei** [comment]
It works, thank you :+1:
