### ISSUE TITLE
Data size always 64 percent when use fio produce data on the nfs storage

### ISSUE THREAD

**Issue by MyCoXiao** [axboe/fio#22]
Hi,
    There is a problem need your help,  I wrote something by FIO but in certain point something weird happens. Fio version is 2.1.13.
    My command as below:
    fio --directory=./ --direct=1 --rw=randwrite --refill_buffers --norandommap --randrepeat=0 --ioengine=libaio --bs=4k --rwmixread=100 --iodepth=1 --numjobs=1  --group_reporting --name=4ktestwrite --size=100M
    If the directory is local disk, the data actual size(use du -h) is 100M, but if the directory is the nfs share storage the data actual size is 64M. Could you please help to solve this?

This is nfs storage.
Perofrmance-Node ~ # mount
10.121.190.9:/root/lvm on /root/centOS type nfs (rw,vers=4,addr=10.121.190.9,clientaddr=10.121.147.10)
Perofrmance-Node ~ # cd -
/root/centOS
Perofrmance-Node centOS # pwd
/root/centOS
Perofrmance-Node centOS # du -h
16K     ./lost+found
64M     .
Perofrmance-Node centOS # ls -lh
total 64M
-rw-r--r-- 1 nobody nogroup 100M Oct 20 12:02 4ktestwrite.0.0
drwx------ 2 nobody nogroup  16K Aug 13 16:25 lost+found

This is local disk
Perofrmance-Node test # pwd
/mnt/disk/test
Perofrmance-Node test # du -h
101M    .
Perofrmance-Node test # ls -lh
total 101M
-rw-r--r-- 1 root root 100M Oct 17 03:38 4ktestwrite.0.0

   Any assistance will be greatly appreciated!

Thanks

**Comment by sitsofe** [comment]
@MyCoXiao You asked fio to make a 100MByte file and then potentially didn't write to all of it (`--norandommap`) so areas of the file could still be sparse.

On a local filesystem like ext4 fio will be able to issue a `fallocate` operation at layout time to tell the filesystem it needs to preallocate all of the blocks of the file. When fio is writing to your NFS mount the `fallocate` call will fail so the blocks aren't allocated up front - only when written to by the job. Subsequently, parts of the file remain sparse after fio has finished leading to du vs ls returning different file sizes (size of the file in terms of blocks that had to be allocated vs size the file would like to be).

If you want to observe the same sparse file behaviour on the local filesystem try adding `--fallocate=none` to your options.
