### ISSUE TITLE
Exit if files do not exist

### ISSUE THREAD

**Issue by davidhedlund** [axboe/fio#225]
"If the the files do not exist, size must be given" - man fio

I must set --size on a empty USB device
* sudo fio --name=randwrite --rw=randwrite --bs=4k --filename=/dev/sdb --size=256M

I cannot use "shutdown now" when I run it without --size
* sudo fio --name=randwrite --rw=randwrite --bs=4k --filename=/dev/sdb

So prevent system fail, should not fio send a message ("size must be given") and exit when it is evoked without --size?

**Comment by axboe** [comment]
Not sure I really understand what you are saying here. For your case, /dev/sdb should exist, and fio will query the size of it and use that as the size, if none other is given. That's the same behavior as if a regular file is used, fio just uses different methods to determine the size of the file (or device).

Fio needs a size to run. If the file does not exist, it doesn't know what size to use. Hence if a specific existing file isn't given and size is NOT given, fio will error out.

I don't know what your system fail refers to.

**Comment by davidhedlund** [comment]
@axboe All I'm saying is that I cannot use fio without the --size flag even if /dev/sdb exist. It never finish and it is not possible to kill fio in this state either.

**Comment by axboe** [comment]
That sounds very odd. If size isn't given, the full device size is used. If sdb is 2TB, fio will randomly write 2TB of data all over the disk. If it's not possible to kill, then it sounds like it hit a kernel bug. ps aux output would be handy, dmesg output, and probably "echo w > /proc/sysrq-trigger" as well.

**Comment by axboe** [comment]
Or if not a kernel bug, then just stalled IO to the device. So a device problem. With the info given here, I can't say which one it is.

**Comment by davidhedlund** [comment]
@axboe You are right, the device is 16GB and takes forever to do random write test on. However, the problem is that I cannot kill fio I want too. How do I do that?

**Comment by axboe** [comment]
If it just takes forever, fio might just be waiting for sync of the dirty buffers. You are doing a buffered random write, not a direct one. It should eventually exit, but it's waiting on the in-kernel sync, and you can't kill it at that point. Check /proc/meminfo, in particular the Dirty entry. That's probably big, and slowing shrinking at the reclaim rate of the device. Is this a USB stick?

**Comment by davidhedlund** [comment]
@axboe Yes it is a USB stick.

**Comment by davidhedlund** [comment]
https://github.com/axboe/fio/issues/226

**Comment by axboe** [comment]
I thought it might be. So what is happening is that fio will very quickly dirty a lot of memory on the device. When you then tell fio to exit, it'll wait for all that dirty memory to be cleaned. As your device is very slow, that will take forever. This isn't really a fio or Linux issue. If you want it to exit quicker, use --direct=1 to write unbuffered.
