### ISSUE TITLE
Off-topic: h-node.org help for random read, and random write on USB sticks

### ISSUE THREAD

**Issue by davidhedlund** [axboe/fio#226]
I volunteer for h-node.org. For the moment I'm evaluating USB flash drives that are suitable for GNU/Linux live booting.

What is the best fio command to evaluate random read, and random write on USB sticks?

**Comment by axboe** [comment]
I'd write them, and read them back verifying the contents. Something ala:

```fio --name=write_and_verify --rw=randwrite --bs=4k --direct=1 --ioengine=libaio --iodepth=16 --verify=crc32c --filename=/dev/XXX```

**Comment by davidhedlund** [comment]
@axboe Thank you once again.

**Comment by davidhedlund** [comment]
@axboe I didn't find any examples in man fio. Is your USB stick example stated somewhere else?

**Comment by axboe** [comment]
Fio ships with some examples in the examples/ directory. But this basic write/read-and-verify isn't in there. I'll put it in there, it's the most basic form of data verification you can do.

**Comment by davidhedlund** [comment]
@axboe Great.

**Comment by davidhedlund** [comment]
@axboe Any idea how long it will take to perform your command above on a 16 GB USB stick with slow random write performance?

**Comment by axboe** [comment]
Depends on how slow... For this test case, fio will randomly write 16G of data in 4K chunks, then randomly read 16G of data in 4K chunks. Perhaps you can speed it up by doing rw=write for sequential writes, instead of random ones.

**Comment by davidhedlund** [comment]
@axboe I must random write because that is what will happen on a GNU/Linux live USB stick.

**Comment by davidhedlund** [comment]
@axboe What would you recommend to add to the command to evaluate them on a feasible time?

**Comment by axboe** [comment]
Write larger chunks, perhaps? Use bs=128K or something like that. Outside of that, your only options are not writing/verifying the whole thing. But that seems unsafe.

**Comment by davidhedlund** [comment]
@axboe I will perform the random write, and random read test, for a bunch of USB sticks. The first thing I need to do is to set up a reliable test case so I can publish the results on h-node.org.

With that said, any improvement for the fio evaluation command are welcome. I am very happy with your help this far.

**Comment by davidhedlund** [comment]
So please add a example for this in the example/ directory.

**Comment by axboe** [comment]
Outside of a bigger IO write size and/or using sequential instead of random writes, there's nothing you can do. I don't have any magic to speed up slow USB disks :-)

Example has already been added.

**Comment by davidhedlund** [comment]
@axboe Can you please point me to the example here at github?

**Comment by axboe** [comment]
https://github.com/axboe/fio/blob/master/examples/basic-verify.fio

**Comment by davidhedlund** [comment]
@axboe I'll use that as reference. I'm impressed with fio. Good work.

**Comment by davidhedlund** [comment]
@axboe Should bs=128K be commented to https://github.com/axboe/fio/blob/master/examples/basic-verify.fio too?

**Comment by axboe** [comment]
Thanks.

There are many variations you can do, 4k is a good basic test. If you went bs=128k instead, then another thing you could do is set verify_interval lower. It'll default to one block, so every 4k for a 4k test, and 128k for a 128k test. If you set that at 4k and set bs=128k, you'd write larger chunks, but still have 4k granularity in verifying where things went wrong, if they did.

But the point of adding the job file is to have a basic example that people can expand upon if they want to, it's better than not having a simple starting point. To that effect, I think the 4k is a good default.

**Comment by davidhedlund** [comment]
@axboe I'm impatient. Is this the fastest way to quick verify:

sudo fio --name=write_and_verify --rw=randwrite --bs=4k --direct=1 --ioengine=libaio --iodepth=16 --verify=crc32c --filename=/dev/sdb --size=128MB

**Comment by axboe** [comment]
You're only verify 128MB of the device, which is less than 1% of your device. So up to you if that is enough, I can't call that.

**Comment by davidhedlund** [comment]
@axboe Wow, this will take weeks. I better of run this on a dedicated computer.

**Comment by axboe** [comment]
Even a shitty USB stick should be able to write a few MB/sec with that. At that rate, it should finish in 2-3h for the write, and probably quicker for the read. So not sure what you are running on if it takes weeks?

**Comment by davidhedlund** [comment]
I meant for all full devices.

**Comment by davidhedlund** [comment]
@axboe Is everything on /dev/sdb left intact when I perform write test with fio or will it over write by default?

**Comment by axboe** [comment]
Not sure about that full comment, fio doesn't care what's on the device. And since it's a writeable test, it destroys what's currently on the device.

**Comment by davidhedlund** [comment]
Ok.

**Comment by davidhedlund** [comment]
@axboe I see https://github.com/axboe/fio/blob/master/examples/ssd-test.fio so what I suggested was that you add https://github.com/axboe/fio/blob/master/examples/usb-stick-test.fio What do you think about it?

**Comment by axboe** [comment]
There's nothing USB stick specific about this test, which is why I added it as a basic verification test instead. You could just as well use it on a file in your file system, or on HDD/SSD, it doesn't matter. The fact that you are using it on a USB stick is orthogonal to the issue, it's a skeleton job file for data verification that can be expanded as the user sees fit.

**Comment by axboe** [comment]
As I said, I already added the basic verification file. See further up in the comments here.

**Comment by davidhedlund** [comment]
@axboe Yes, but what about adding a specific USB stick test?

**Comment by axboe** [comment]
For what purpose? The basic test does the same, and it's not specific to USB sticks in any way.

**Comment by davidhedlund** [comment]
@axboe Sorry, I thought a sort of USB test was missing when I saw https://github.com/axboe/fio/blob/master/examples/ssd-test.fio

**Comment by davidhedlund** [comment]
@axboe Why do have you set "--ioengine=libaio" and  "--iodepth=16" in the example?

**Comment by davidhedlund** [comment]
I understand that --verify=crc32c is verification for file systems including ext4.

**Comment by axboe** [comment]
It usually goes faster with async IO, hence libaio and iodepth=16. crc32c is a good default checksum, as most CPUs have hardware support for it.

**Comment by davidhedlund** [comment]
@axboe Why is it bad if the test run faster?

**Comment by axboe** [comment]
It's not bad, that was the point...

**Comment by davidhedlund** [comment]
@axboe Oh, libaio = async IO.

**Comment by davidhedlund** [comment]
@axboe Why is it not default then?

**Comment by axboe** [comment]
Because fio is a generic workload modeler, and because it depends on direct=1 to be set to be async.

**Comment by davidhedlund** [comment]
@axboe Thanks.

**Comment by davidhedlund** [comment]
@axboe Where do I read the random read and random write results here?:

<pre>
Run status group 0 (all jobs):
   READ: io=71680KB, aggrb=6820KB/s, minb=974KB/s, maxb=1039KB/s, mint=9855msec, maxt=10510msec
  WRITE: io=77628KB, aggrb=988KB/s, minb=75KB/s, maxb=130KB/s, mint=78511msec, maxt=78522msec

Disk stats (read/write):
  sdb: ios=14825/17145, merge=2454/1783, ticks=945081/7561965, in_queue=8550478, util=100.00%
</pre>

**Comment by davidhedlund** [comment]
Read 6820KB, write 988KB/s I assume. I don't know what merge means though.

**Comment by axboe** [comment]
Please see the fio man page or the HOWTO document, it's all explained in there.

**Comment by davidhedlund** [comment]
@axboe Yes.
