### ISSUE TITLE
fio --filename=/dev/

### ISSUE THREAD

**Issue by davidhedlund** [axboe/fio#232]
What happens when fio write to /dev/?

> fio --name=write rw=write --bs=4k --filename=/dev/$block_device

I didn't set $block_device by misstake and run that command multiple times.

**Comment by axboe** [comment]
You must have runs something else, unless $block_device contains something, fio would error out with "is a directory". And whatever $block_device contains must have already existed, or fio would have errored out saying you need to set `size`.

**Comment by davidhedlund** [comment]
@axboe I did set size too.

**Comment by axboe** [comment]
Well, then $block_device must have had something in it. `ls -lSr /dev` would likely show you the file that was created.

**Comment by davidhedlund** [comment]
@axboe Thank you. I see loop0, loop1... loop7. What is the name of the files created by fio?

**Comment by axboe** [comment]
Whatever $block_device contained... I'll repeat - if that variable was empty, fio would error out:

`fio: pid=26412, err=21/file:filesetup.c:623, func=open(/dev/), error=Is a directory`

So if it didn't, then it wrote whatever filename you had in there, be it a block device or a normal file.

**Comment by davidhedlund** [comment]
@axboe Ok, thank you for explaining this for me. I was worried that I might destroyed some files on my GNU/Linux system distribution.
