### ISSUE TITLE
numjobs missing

### ISSUE THREAD

**Issue by sheridp** [axboe/fio#237]
numjobs is missing in the 'global options' section of the output when using output-format=json+ and group_reporting.  This is important to determine the actual queue depth.

**Comment by joe-harlan** [comment]
I second this notion.  It is also missing from json without the '+'.  Any chance this could be added in the next release???

**Comment by brycepg** [comment]
@axboe Can you provide some context for https://github.com/axboe/fio/commit/876e10015bc3191a71512c3ae57482bf1add4e0e#diff-db536a6e586c0739e8e679f910add4b9R1106
I'd like to have numjobs in global options

I changed https://github.com/axboe/fio/blob/master/stat.c#L1881 `json_add_job_opts` numjobs parameter to `true`, and it seems to work fine.

**Comment by brycepg** [comment]
A workaround for this issue (without changing the source code) is to specify numjobs for each job instead of in global options.

**Comment by axboe** [comment]
The idea is that it should be easy to collate the global and job options into one file, and run the same thing again. If you include ```numjobs``` in the out, then that isn't true. As an example, let's say you run something ala:

```
[test]
filename=xxx
size=1g
numjobs=8
```

then you end up with 8 job outputs in the json file. If each of these included the ```numjobs``` option, then it would look like you ran 8x8 of those jobs.

**Comment by brycepg** [comment]
What you said definitely makes sense when not using group_reporting, and `numjobs` is properly included in the `job` itself if `group_reporting=1` and `numjobs` is specified in the job.

Example:

    [test]
    filename=xxx
    numjobs=8
    group_reporting=1

Will give

     'job options': {
      'group_reporting': '1',
      'numjobs': '8',
      'filename': 'xxx'
    }

However:

    [global]
    numjobs=8
    group_reporting=1
    [test]
    filename=xxx

Gives

    'global options': {
      'group_reporting': '1'
    }
    ...
    'job options': {
      'filename': 'xxx'
    }

Putting numjobs in `global options` will not display numjobs anywhere in the json output at the same time while having only one job displayed in the json, leaving the impression that only one job was run instead of 8

**Comment by axboe** [comment]
Yeah, it's not perfect, I agree that part should be fixed up.

**Comment by axboe** [comment]
Pushed out a fix to just always include it, since what we have now isn't perfect anyway. Would be nice to get that rectified, so that it always directly reflected what was run. Until that happens, it's better not to special case it, as we're potentially losing information right now.
