### ISSUE TITLE
Segfault on global rate_iops option

### ISSUE THREAD

**Issue by dmonakhov** [axboe/fio#242]
$ cat test.fio 
[global]
rate_iops=1
[test]
size=4k

$./fio --showcmd test.fio  > dev/
fio --rate_iops=1 --name=test --size=4k 
Segmentation fault (core dumped)

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=5e333ada464c885d2a33a30e98812bfb666e6052

This should fix it, thanks for reporting.
