### ISSUE TITLE
FIO_2.13: exiting with return code 0, though the command errors out.

### ISSUE THREAD

**Issue by vrbagalkote** [axboe/fio#244]
[root@powerio-blue-lp3 fio-2.13]# date; fio /dev/mapper/mpatha --name=xyz --ioengine=libaio --iodepth=1 --rw=randwrite --bs=4k --direct=0 --size=512M --numjobs=8 --runtime=900 --group_reporting; date
Mon Sep 12 02:50:36 EDT 2016
xyz: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
...
fio: option <�> outside of [] job section
Mon Sep 12 02:50:36 EDT 2016
[root@powerio-blue-lp3 fio-2.13]# echo $?
0
[root@powerio-blue-lp3 fio-2.13]#

**Comment by axboe** [comment]
You run `date` after fio, so you are looking at the return value of that command, not fio. Fio will error with exit value 1 for that error.
