### ISSUE TITLE
Pause in-between one test to another within a job file

### ISSUE THREAD

**Issue by prabhugce** [axboe/fio#248]
Can fio pause between one test to another test in a job file, which has got multiple tests, so that some other external operation like capturing a serial data can happen for a while(10 minutes) and then resume fio? I used ramp_time thinking that it would not do any operation in that time, but it doesn't behave in the desired way.

[global]
ioengine=libaio                 # Default engine for CentOS
clat_percentiles=1              # report QOS data, on by default
percentile_list=95.0:99.0:99.5:99.9:99.99:99.999:99.9999    # defines percentile buckets in mS
disable_slat=1                  # disables Submission Latency recording
disable_lat=1                   # disables Total Latency recording
thread                          # fork threads rather than jobs (windows can only fork threads)
cpus_allowed=0-7
cpus_allowed_policy=split
direct=1                        # Uses direct IO's, bypass OS buffer
size=25%

[seq1]
stonewall
offset=0
rw=write
name=seq1
bs=128k
iodepth=32
bwavgtime=1000
write_bw_log=128k_seq1

[break1]
stonewall
ramp_time=10m
name=break1
write_bw_log=break1

[seq2]
stonewall
offset=25%
rw=write
name=seq2
bs=128k
iodepth=32
bwavgtime=1000
write_bw_log=128k_seq2

[break2]
stonewall
ramp_time=10m
name=break2
write_bw_log=break2

[seq3]
stonewall
offset=25%
rw=write
name=seq3
bs=128k
iodepth=32
bwavgtime=1000
write_bw_log=128k_seq3

[break3]
stonewall
ramp_time=10m
name=break3
write_bw_log=break3

[seq4]
stonewall
offset=25%
rw=write
name=seq4
bs=128k
iodepth=32
bwavgtime=1000
write_bw_log=128k_seq4

Appreciate, if someone can tell me, what I am thinking is possible in fio or not.

Thanks,
Prabhu

**Comment by axboe** [comment]
Have you looked at startdelay?

**Comment by prabhugce** [comment]
Great!! startdelay is exactly what I need. 
offset accepts storage space as input. How to dynamically move lba space irrespective of total capacity, so that along with size, which accepts percentage as input

**Comment by prabhugce** [comment]
Great!! startdelay is exactly what I need. 
offset accepts storage space as input. How to dynamically move lba space irrespective of total capacity? I am able to fill x% of a drive by specifying size=x%, but couldn't move lba space dynamically

**Comment by sitsofe** [comment]
@prabhugce You will be better off using the fio mailing list if you're asking support questions rather than using the github issue tracker...

I might be misunderstanding your last question but it sounds like you need the combination of `offset` (which moves the starting lba) and `io_limit` (but you will have to ensure this is less than or equal to the amount of space left after doing the offset otherwise the I/O will wrap around to the start).

**Comment by sitsofe** [comment]
@prabhugce 
> How to dynamically move lba space irrespective of total capacity? 

In fact, it's probably a combination of [`offset`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-offset) and [`size`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size) that you are after.

Given that the original problem (pausing between jobs) can be done, could you close this issue?
