### ISSUE TITLE
Fio spitting out a lot of log errors during exit

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#249]
Fio version: fio-2.13
OS: Cent OS Linux 7.2.1511 
Processor: x86_64
No of CPU cores: 8

Off late i have been noticing a lot of errors during fio cleanup. Two instances of my recent test runs below.

fio  --name=fio_test --filename=/dev/nvme0n1 --rw=rw --ioengine=libaio --iodepth=1024 --iodepth_batch=0 --iodepth_batch_complete=0 --bs=1M --numjobs=32 --buffered=0 --runtime=10 --time_based=3600 --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --clat_percentiles=0 --disable_bw=1 --offset=0 --size=1031006768332B

fio: pid=1205, got signal=9
fio: pid=1201, got signal=9
fio: pid=1202, got signal=9
fio: pid=1216, got signal=9
fio: pid=1213, got signal=9
fio: pid=1204, got signal=9
fio: pid=1230, got signal=9
fio: pid=1214, got signal=9
fio: pid=1226, got signal=9
fio: pid=1200, got signal=9
fio: pid=1227, got signal=9
fio: pid=1221, got signal=9
fio: pid=1207, got signal=9
fio: pid=1228, got signal=9
fio: pid=1211, got signal=9
fio: pid=1223, got signal=9
fio: pid=1219, got signal=9
fio: pid=1206, got signal=9
fio: file hash not empty on exit

fio  --name=fio_test --filename=/dev/nvme0n1 --rw=write --ioengine=libaio --iodepth=1024 --iodepth_batch=0 --iodepth_batch_complete=0 --bs=1M --numjobs=32 --buffered=0 --runtime=3600 --time_based=1 --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --clat_percentiles=0 --disable_bw=1 --offset=0 --size=1031006768332B

fio: pid=30937, got signal=9
fio: pid=30932, got signal=9
fio: pid=30935, got signal=9
fio: pid=30934, got signal=9
fio: pid=30933, got signal=9
fio: pid=30940, got signal=9
fio: pid=30947, got signal=9
fio: pid=30951, got signal=9
fio: pid=30962, got signal=9
fio: pid=30961, got signal=9
fio: pid=30950, got signal=9
fio: pid=30954, got signal=9
fio: pid=30960, got signal=9
fio: pid=30958, got signal=9
fio: pid=30936, got signal=9
fio: pid=30939, got signal=9
fio: pid=30946, got signal=9
fio: pid=30949, got signal=9

**Comment by sitsofe** [comment]
@shivapahwa do you have 32GBytes or more of RAM in your machine? If you look at dmesg do you see anything there?

**Comment by axboe** [comment]
That's a good question. For the job that you are trying to run, you are using 1M*1024 = 1G of RAM for each process. And you are starting 32 of them. You are probably getting killed by the OOM killer in the kernel, since you are forcing the machine into an out-of-memory condition. This isn't a fio issue, it's a problem with oversubscribing the OS.

**Comment by shivapahwa** [comment]
I agree with you guys. It did not occur to me that it could be the OS.
