### ISSUE TITLE
fio "Segmentation fault (core dumped)" since 1b2a83d

### ISSUE THREAD

**Issue by yide1728** [axboe/fio#250]
Hello 
I found Segmentation fault with latest fio, finally found it was introduced from 1b2a83d.
Here is the execution log:

#fio -filename=/dev/md0 -iodepth=1 -thread -rw=randread -ioengine=psync  --runtime=10 -name=mytest -numjobs=6
Segmentation fault (core dumped)
# dmesg
[ 3960.881374] fio[4169]: segfault at 0 ip 00000000004146a2 sp 00007ffefea66b90 error 4 in fio[400000+98000]

commit 1b2a83dcda752f411156f7967c0d4f80e7eb61ef
Author: Jens Axboe <axboe@fb.com>
Date:   Sun Sep 25 13:57:32 2016 -0600

    file: add bloom filter to avoid quadratic lookup behavior
    
    If we have a lot of jobs, with a lot of subjobs, and they each
    have a lot of files, we get pathetic startup performance
    because each file add will check all the previously added
    files.
    
    Fixes: bcbfeefa7bce ("fio: add multi directory support")
    Signed-off-by: Jens Axboe <axboe@fb.com>

**Comment by axboe** [comment]
My bad, I've fixed it up in current -git. If you git pull again, it should work.

**Comment by yide1728** [comment]
Thanks, it works now.
