### ISSUE TITLE
something happened when directI/O=1

### ISSUE THREAD

**Issue by pahome** [axboe/fio#253]
Mine machine is Ubuntu 4.4.0-38 x86_64
fio_version = 2.14
Below is my config file
```
[global]
ioengine=libaio
**direct=1**
time_based
runtime=60
ramp_time=30
size=64g
group_reporting

[S_100RW_1M_R]
rw=read
numjobs=1
iodepth=32
bs=1m
stonewall

[S_100RW_1M_W]
rw=write
numjobs=1
iodepth=32
bs=1m
stonewall
```
when I execute :` sudo fio fio.cfg` and it done
it shows the result of seq. read without seq. write.
it shows below:
`fio: io_u error on file xxxxx : Invalid argument: write offset=0, buflen=1048576`

I tried every times and the results are the same even I changed the tested device.

how come it happened?

thanks a lot

**Comment by axboe** [comment]
Looks like your filesystem doesn't support O_DIRECT. What file system is being used with the job file?

**Comment by pahome** [comment]
I mount a **ext4(hdd)** in ~/a, a **sshfs** in ~/b.And I use **mergerfs** to mount them in ~/mnt
The job file is originally belonged to ~/a/jobfile, so I will see it in ~/mnt/jobfile.
And I test the ~/mnt/jobfile by the config above.

thanks for help

**Comment by axboe** [comment]
sshfs/mergefs don't support O_DIRECT, then, which is why the job fails.
