### ISSUE TITLE
How to fill data into the big size disk as fast as possible

### ISSUE THREAD

**Issue by dllhlx** [axboe/fio#255]
As mentioned in the title, when I run fio in the os with 16 * 6T sata mechanical  hard disk, the dump data process before test become very slow, sometime need 6+ hours. So do you have any idea to speed up this process so I can finish dump data into disk quickly. Thanks a lot.

**Comment by axboe** [comment]
Well, you are writing 96TB of data to rotating storage, it will take a long time. Use a big block size (bs=1M) and use direct=1 and ioengine=libaio iodepth=16, and have a thread for each job writing sequentially. That's going to be roughly as fast as it's going to get.

**Comment by dllhlx** [comment]
@axboe  thanks !

**Comment by matschaffer** [comment]
Closed ticket, yes. Just incase someone happens across this again, I ended up using this to fill all the SSDs on an AWS i3.8xl (raided)

```
fio \
  --filename=/dev/md0 \
  --direct=1 \
  --size=100% \
  --log_avg_msec=10000 \
  --filename=fio_test_file \
  --ioengine=libaio \
  --name disk_fill \
  --rw=write \
  --bs=256k \
  --iodepth=8
```

So far it's had the lowest ETA (35m) to fill roughly 7TB. Haven't seen any noticeable improvement in disk throughput (by bytes) from more workers, larger block sizes or iodepth.

**Comment by sitsofe** [comment]
@matschaffer There might be some tiny benefit from using --gtod_reduce=1 if you're CPU bound but your block size wasn't tiny tiny so you might be going as fast as you can already. Other tricks include letting fio reap more completed I/Os in one go (e.g. [iodepth_batch_complete_max](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-iodepth-batch-complete-max)=32) but again this will only really help if you're CPU bound.

Very occasionally you can also get better performance by lowering fio's block size to whatever the disk considers to be optimal (especially if the kernel is splitting I/Os up for some reason) but you'd have to experiment and check what iostat -x 1 was outputting during a run.

**Comment by matschaffer** [comment]
Nice! Yeah, plenty of CPU to spare on the i3.8xl with the above settings. I'd been just watching the graphs from https://github.com/netflix/vector and `iotop`, but I'll check `iostat -x 1` as well to see how it compares.
