### ISSUE TITLE
Assertion `data->fail_ok' failed

### ISSUE THREAD

**Issue by kimianowski** [axboe/fio#256]
I'm using fio to simulate disk stress for a given time. However I get an error:

`fio: lib/axmap.c:230: axmap_set_fn: Assertion `data->fail_ok' failed.`

And then fio stops. I run fio with command as follows:

`fio --name=diskStressJob --rw=randrw --size=16m --runtime=5m --time_based`

removing `--rw=randrw` or both `runtime` and `time_based` removes the issue, but I need to use these options. Attached you will find stderr and stdout from running the command with `--debug=all` option. Also when I first run fio with `--create-only=1` and `size=17m`, the problem also disappears. My fio version is 2.0.13. 

[err.txt](https://github.com/axboe/fio/files/526716/err.txt)
[out.txt](https://github.com/axboe/fio/files/526715/out.txt)

**Comment by axboe** [comment]
That bug has long since been fixed, you are running a version that is almost 4 years old... Upgrade to the newest, and it should work for you.

**Comment by kimianowski** [comment]
In which version exactly was it fixed? The version 2.0.13 is officially available on RedHat 6, so may be still commonly used.

**Comment by axboe** [comment]
It's fixed in 2.0.15 and newer. You should tell RH to update their fio package, it's ancient.

**Comment by pstrzelczak** [comment]
I agree that the version in RHEL6 in ancient. However, IMHO fio maintainers not users are the ones that should care their latest package in RHEL6 (still widely used in enterprise) is not outdated.
