### ISSUE TITLE
Option to place log files in a different location

### ISSUE THREAD

**Issue by dcharnley** [axboe/fio#265]
Is there a cli option to have the log files put into a different directory other than ./. I have tried directory and output and neither appear to work

**Comment by sitsofe** [comment]
@dcharnley just put a full path including the filename you want to use e.g.
--write_bw_log=/tmp/bwlog

**Comment by sitsofe** [comment]
@dcharnley - did putting the full path change the location of the log?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by prashant-pokhriyal** [comment]
@sitsofe in doc it has written that if I do not give any str to write_bw_log, it will automatically creates the log file, but it is not creating it.

> write_bw_log=str
> If given, write a bandwidth log for this job. Can be used to store data of the bandwidth of the jobs in their lifetime.
> 
> **If no str argument is given, the default filename of jobname_type.x.log is used.**

**Comment by sitsofe** [comment]
@prashant-pokhriyal please don't hijack existing issues with new issues - file a new issue with the new information!

FWIW: What you describe is actually a subtle bug when specifying --write_bw_log on the command line. If you were to use it in a job file like that you would find it matches the described behaviour but it's still a bug. Care to open a new issue for it (see https://github.com/axboe/fio/blob/master/REPORTING-BUGS for info we require)?
