### ISSUE TITLE
JSON output bw_* fields got zero values 

### ISSUE THREAD

**Issue by dawn110110** [axboe/fio#272]
fio 2.15 build from source on CentOS 6.8 Final x86_64 machine

when output as json bw_* fields are zero (except for "bw")

here are cmds and outputs

1. as json:

```
[root@data03 bin]# ./fio --rw=readwrite --size=5000m --name=t2 --bs=512k --runtime=180 --output-format=json --filename=/data/fio_test/f1
{
  "fio version" : "fio-2.15",
  "timestamp" : 1479710051,
  "timestamp_ms" : 1479710051096,
  "time" : "Mon Nov 21 14:34:11 2016",
  "global options" : {
    "rw" : "readwrite",
    "size" : "5000m"
  },
  "jobs" : [
    {
      "jobname" : "t2",
      "groupid" : 0,
      "error" : 0,
      "eta" : 0,
      "elapsed" : 17,
      "job options" : {
        "name" : "t2",
        "bs" : "512k",
        "runtime" : "180",
        "filename" : "/data/fio_test/f1"
      },
      "read" : {
        "io_bytes" : 2552320,
        "bw" : 153412,
        "iops" : 299.633362,
        "runtime" : 16637,
        "total_ios" : 4985,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 54,
          "max" : 135676,
          "mean" : 2892.544678,
          "stddev" : 11199.579102,
          "percentile" : {
            "1.000000" : 56,
            "5.000000" : 58,
            "10.000000" : 61,
            "20.000000" : 66,
            "30.000000" : 72,
            "40.000000" : 80,
            "50.000000" : 86,
            "60.000000" : 111,
            "70.000000" : 1048,
            "80.000000" : 1208,
            "90.000000" : 2736,
            "95.000000" : 3760,
            "99.000000" : 52992,
            "99.500000" : 66048,
            "99.900000" : 100864,
            "99.950000" : 107008,
            "99.990000" : 136192,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 54,
          "max" : 135676,
          "mean" : 2892.896973,
          "stddev" : 11199.629883
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000
      },
      "write" : {
        "io_bytes" : 2567680,
        "bw" : 154335,
        "iops" : 301.436554,
        "runtime" : 16637,
        "total_ios" : 5015,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 139,
          "max" : 106832,
          "mean" : 416.128998,
          "stddev" : 3193.881836,
          "percentile" : {
            "1.000000" : 149,
            "5.000000" : 165,
            "10.000000" : 185,
            "20.000000" : 217,
            "30.000000" : 239,
            "40.000000" : 245,
            "50.000000" : 251,
            "60.000000" : 258,
            "70.000000" : 266,
            "80.000000" : 286,
            "90.000000" : 322,
            "95.000000" : 370,
            "99.000000" : 644,
            "99.500000" : 1112,
            "99.900000" : 50432,
            "99.950000" : 92672,
            "99.990000" : 107008,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 154,
          "max" : 106855,
          "mean" : 436.012177,
          "stddev" : 3194.754883
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000
      },
      "trim" : {
        "io_bytes" : 0,
        "bw" : 0,
        "iops" : 0.000000,
        "runtime" : 0,
        "total_ios" : 0,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000,
          "percentile" : {
            "1.000000" : 0,
            "5.000000" : 0,
            "10.000000" : 0,
            "20.000000" : 0,
            "30.000000" : 0,
            "40.000000" : 0,
            "50.000000" : 0,
            "60.000000" : 0,
            "70.000000" : 0,
            "80.000000" : 0,
            "90.000000" : 0,
            "95.000000" : 0,
            "99.000000" : 0,
            "99.500000" : 0,
            "99.900000" : 0,
            "99.950000" : 0,
            "99.990000" : 0,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000
      },
      "usr_cpu" : 0.583073,
      "sys_cpu" : 11.481125,
      "ctx" : 5810,
      "majf" : 0,
      "minf" : 37,
      "iodepth_level" : {
        "1" : 100.000000,
        "2" : 0.000000,
        "4" : 0.000000,
        "8" : 0.000000,
        "16" : 0.000000,
        "32" : 0.000000,
        ">=64" : 0.000000
      },
      "latency_us" : {
        "2" : 0.000000,
        "4" : 0.000000,
        "10" : 0.000000,
        "20" : 0.000000,
        "50" : 0.000000,
        "100" : 28.750000,
        "250" : 26.370001,
        "500" : 25.520000,
        "750" : 0.280000,
        "1000" : 2.770000
      },
      "latency_ms" : {
        "2" : 8.980000,
        "4" : 5.050000,
        "10" : 0.050000,
        "20" : 0.040000,
        "50" : 0.480000,
        "100" : 1.640000,
        "250" : 0.070000,
        "500" : 0.000000,
        "750" : 0.000000,
        "1000" : 0.000000,
        "2000" : 0.000000,
        ">=2000" : 0.000000
      },
      "latency_depth" : 1,
      "latency_target" : 0,
      "latency_percentile" : 100.000000,
      "latency_window" : 0
    }
  ],
  "disk_util" : [
    {
      "name" : "xvdf",
      "read_ios" : 7564,
      "write_ios" : 12807,
      "read_merges" : 0,
      "write_merges" : 389100,
      "read_ticks" : 51312,
      "write_ticks" : 1744941,
      "in_queue" : 1807002,
      "util" : 92.627625
    }
  ]
}
```

2. as normal:

```
[root@data03 bin]# ./fio --rw=readwrite --size=5000m --name=t2 --bs=512k --runtime=180  --filename=/data/fio_test/f1
t2: (g=0): rw=rw, bs=512K-512K/512K-512K/512K-512K, ioengine=psync, iodepth=1
fio-2.15
Starting 1 process
Jobs: 1 (f=1): [M(1)] [100.0% done] [396.5MB/402.5MB/0KB /s] [792/804/0 iops] [eta 00m:00s]
t2: (groupid=0, jobs=1): err= 0: pid=7783: Mon Nov 21 14:57:12 2016
  read : io=2492.6MB, bw=467458KB/s, iops=913, runt=  5460msec
    clat (usec): min=70, max=18565, avg=785.52, stdev=1052.85
     lat (usec): min=71, max=18565, avg=785.83, stdev=1052.89
    clat percentiles (usec):
     |  1.00th=[   72],  5.00th=[   74], 10.00th=[   76], 20.00th=[   80],
     | 30.00th=[   86], 40.00th=[   92], 50.00th=[   97], 60.00th=[  113],
     | 70.00th=[ 1416], 80.00th=[ 1816], 90.00th=[ 2096], 95.00th=[ 2384],
     | 99.00th=[ 3984], 99.50th=[ 4448], 99.90th=[ 7008], 99.95th=[ 9920],
     | 99.99th=[18560]
  write: io=2507.6MB, bw=470271KB/s, iops=918, runt=  5460msec
    clat (usec): min=149, max=2732, avg=222.54, stdev=93.45
     lat (usec): min=168, max=2751, avg=241.63, stdev=93.60
    clat percentiles (usec):
     |  1.00th=[  157],  5.00th=[  165], 10.00th=[  173], 20.00th=[  185],
     | 30.00th=[  205], 40.00th=[  213], 50.00th=[  219], 60.00th=[  225],
     | 70.00th=[  231], 80.00th=[  239], 90.00th=[  253], 95.00th=[  270],
     | 99.00th=[  370], 99.50th=[  644], 99.90th=[ 1656], 99.95th=[ 1832],
     | 99.99th=[ 2736]
    lat (usec) : 100=26.28%, 250=49.30%, 500=5.43%, 750=0.11%, 1000=0.76%
    lat (msec) : 2=11.64%, 4=5.99%, 10=0.47%, 20=0.02%
  cpu          : usr=1.89%, sys=37.63%, ctx=5867, majf=0, minf=34
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=4985/w=5015/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=2492.6MB, aggrb=467457KB/s, minb=467457KB/s, maxb=467457KB/s, mint=5460msec, maxt=5460msec
  WRITE: io=2507.6MB, aggrb=470271KB/s, minb=470271KB/s, maxb=470271KB/s, mint=5460msec, maxt=5460msec

Disk stats (read/write):
  xvdf: ios=7564/59, merge=0/189, ticks=13329/66, in_queue=13390, util=71.31%
```

**Comment by dawn110110** [comment]
found similar case by googling:
http://www.spinics.net/lists/fio/msg02843.html

**Comment by sitsofe** [comment]
@dawn110110 I think this was fixed by https://github.com/axboe/fio/commit/371817093568b7404b47d94a1ef10077f1695264 which arrived in fio-2.20. Can you try the latest fio and see if this problem is still here and if not can you close this issue?

**Comment by sitsofe** [comment]
@dawn110110 any update on this?

**Comment by dawn110110** [comment]
tried fio-3.1
problem fixed

sorry for reply so late.

same command
here's output

`{
  "fio version" : "fio-3.1",
  "timestamp" : 1509619773,
  "timestamp_ms" : 1509619773511,
  "time" : "Thu Nov  2 18:49:33 2017",
  "global options" : {
    "rw" : "readwrite",
    "size" : "5000m"
  },
  "jobs" : [
    {
      "jobname" : "t2",
      "groupid" : 0,
      "error" : 0,
      "eta" : 0,
      "elapsed" : 11,
      "job options" : {
        "name" : "t2",
        "bs" : "512k",
        "runtime" : "180",
        "filename" : "/data/fio_test/f1"
      },
      "read" : {
        "io_bytes" : 2605711360,
        "io_kbytes" : 2544640,
        "bw" : 241106,
        "iops" : 470.911503,
        "runtime" : 10554,
        "total_ios" : 4970,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat_ns" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat_ns" : {
          "min" : 56676,
          "max" : 457898789,
          "mean" : 369215.756942,
          "stddev" : 7157777.297474,
          "percentile" : {
            "1.000000" : 69120,
            "5.000000" : 110080,
            "10.000000" : 116224,
            "20.000000" : 120320,
            "30.000000" : 123392,
            "40.000000" : 127488,
            "50.000000" : 130560,
            "60.000000" : 134144,
            "70.000000" : 140288,
            "80.000000" : 144384,
            "90.000000" : 158720,
            "95.000000" : 173056,
            "99.000000" : 1236992,
            "99.500000" : 1875968,
            "99.900000" : 57933824,
            "99.950000" : 102236160,
            "99.990000" : 459276288,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat_ns" : {
          "min" : 56959,
          "max" : 457899758,
          "mean" : 369528.301408,
          "stddev" : 7157796.642569
        },
        "bw_min" : 53248,
        "bw_max" : 1067008,
        "bw_agg" : 100.000000,
        "bw_mean" : 253849.600000,
        "bw_dev" : 287687.491286,
        "bw_samples" : 20,
        "iops_min" : 104,
        "iops_max" : 2084,
        "iops_mean" : 495.800000,
        "iops_stddev" : 561.889631,
        "iops_samples" : 20
      },
      "write" : {
        "io_bytes" : 2637168640,
        "io_kbytes" : 2575360,
        "bw" : 244017,
        "iops" : 476.596551,
        "runtime" : 10554,
        "total_ios" : 5030,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat_ns" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat_ns" : {
          "min" : 147341,
          "max" : 542560714,
          "mean" : 1703911.685089,
          "stddev" : 13317452.251611,
          "percentile" : {
            "1.000000" : 242688,
            "5.000000" : 254976,
            "10.000000" : 259072,
            "20.000000" : 268288,
            "30.000000" : 272384,
            "40.000000" : 280576,
            "50.000000" : 288768,
            "60.000000" : 296960,
            "70.000000" : 305152,
            "80.000000" : 321536,
            "90.000000" : 346112,
            "95.000000" : 387072,
            "99.000000" : 54263808,
            "99.500000" : 63176704,
            "99.900000" : 147849216,
            "99.950000" : 227540992,
            "99.990000" : 541065216,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat_ns" : {
          "min" : 179029,
          "max" : 542595792,
          "mean" : 1729093.788668,
          "stddev" : 13317683.098424
        },
        "bw_min" : 1024,
        "bw_max" : 1116160,
        "bw_agg" : 100.000000,
        "bw_mean" : 244443.428571,
        "bw_dev" : 300745.007107,
        "bw_samples" : 21,
        "iops_min" : 2,
        "iops_max" : 2180,
        "iops_mean" : 477.428571,
        "iops_stddev" : 587.392592,
        "iops_samples" : 21
      },
      "trim" : {
        "io_bytes" : 0,
        "io_kbytes" : 0,
        "bw" : 0,
        "iops" : 0.000000,
        "runtime" : 0,
        "total_ios" : 0,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat_ns" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat_ns" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000,
          "percentile" : {
            "1.000000" : 0,
            "5.000000" : 0,
            "10.000000" : 0,
            "20.000000" : 0,
            "30.000000" : 0,
            "40.000000" : 0,
            "50.000000" : 0,
            "60.000000" : 0,
            "70.000000" : 0,
            "80.000000" : 0,
            "90.000000" : 0,
            "95.000000" : 0,
            "99.000000" : 0,
            "99.500000" : 0,
            "99.900000" : 0,
            "99.950000" : 0,
            "99.990000" : 0,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat_ns" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000,
        "bw_samples" : 0,
        "iops_min" : 0,
        "iops_max" : 0,
        "iops_mean" : 0.000000,
        "iops_stddev" : 0.000000,
        "iops_samples" : 0
      },
      "usr_cpu" : 1.449825,
      "sys_cpu" : 20.221738,
      "ctx" : 1922,
      "majf" : 0,
      "minf" : 35,
      "iodepth_level" : {
        "1" : 100.000000,
        "2" : 0.000000,
        "4" : 0.000000,
        "8" : 0.000000,
        "16" : 0.000000,
        "32" : 0.000000,
        ">=64" : 0.000000
      },
      "latency_ns" : {
        "2" : 0.000000,
        "4" : 0.000000,
        "10" : 0.000000,
        "20" : 0.000000,
        "50" : 0.000000,
        "100" : 0.000000,
        "250" : 0.000000,
        "500" : 0.000000,
        "750" : 0.000000,
        "1000" : 0.000000
      },
      "latency_us" : {
        "2" : 0.000000,
        "4" : 0.000000,
        "10" : 0.000000,
        "20" : 0.000000,
        "50" : 0.000000,
        "100" : 1.190000,
        "250" : 49.020000,
        "500" : 47.450000,
        "750" : 0.190000,
        "1000" : 0.050000
      },
      "latency_ms" : {
        "2" : 0.530000,
        "4" : 0.090000,
        "10" : 0.160000,
        "20" : 0.320000,
        "50" : 0.390000,
        "100" : 0.360000,
        "250" : 0.230000,
        "500" : 0.010000,
        "750" : 0.010000,
        "1000" : 0.000000,
        "2000" : 0.000000,
        ">=2000" : 0.000000
      },
      "latency_depth" : 1,
      "latency_target" : 0,
      "latency_percentile" : 100.000000,
      "latency_window" : 0
    }
  ],
  "disk_util" : [
    {
      "name" : "vdb",
      "read_ios" : 122,
      "write_ios" : 2662,
      "read_merges" : 0,
      "write_merges" : 331824,
      "read_ticks" : 244,
      "write_ticks" : 1394333,
      "in_queue" : 1431751,
      "util" : 92.863859
    }
  ]
}`

**Comment by sitsofe** [comment]
JSON always prints sections for read, write and trim even if your job doesn't use them. See https://github.com/axboe/fio/issues/430 for where someone else mentioned this...
