### ISSUE TITLE
fio --client not reliably retrieving histogram logs

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#274]
About 6 months ago, fio added a feature known as histogram logging, and support was added in fio --client to retrieve histogram logs from the remote workload generators.  Subsequently, when running large tests with 512 VMs generating workload to a Ceph cluster, I and co-workers ran into problems where we'd get errors from fio --client such as [those in this log file](https://s3.amazonaws.com/ben.england/fio--client/512-vms/20161111-0100_pbfio-randwrite-512i-128Kbs-95m_noDscrub-gettime.log),   These errors occur repeatably but only with histogram logging enabled - with regular latency and bandwidth logging they do not occur.  It appears that the test driver fio process and workload generator fio process get out of sync on a TCP socket, resulting in "matching tag" errors.  It's still not clear to me if "inflate error" precedes or follows the matching tag error.   This error doesn't occur for any but the longest tests, when the size of the histogram file is way larger than the other logs.  But whatever the cause, I had to workaround the problem with a short patch to **finish_log()**:

    #if 0
            if (td->client_type == FIO_CLIENT_TYPE_GUI || is_backend)
                    fio_send_iolog(td, log, log->filename);
            else
                    flush_log(log, !td->o.per_job_logs);
    #else
            flush_log(log, !td->o.per_job_logs);
    #endif

And I copy the files back from the remote workload generator hosts using **rpdcp** (part of **pdsh** package).  This has worked perfectly so far.

questions: 

- why reimplement **rsync -z** functionality inside fio?   Was it for portability to different operating systems such as Windows?
- should I just stop doing compression to make it simpler to get it working?  I suspect that there is some bug in the way compression is implemented in **__fio_append_iolog_gz_hist()**
- why does **deflate()** call use **Z_BLOCK** but **inflate()** call on other end uses **Z_NO_FLUSH**?

**Comment by cronburg** [comment]
Possible relation to the 'matching tags' errors back in July when excessive ETA packets was breaking the transmission protocol used in the client-server: http://www.spinics.net/lists/fio/msg04999.html

My best guess is that this particular workload is sending a decent number of large (gzipped) histogram packets thus breaking the protocol in a similar manner. The client recovers / keeps running after losing track of some of the histogram reply tags, but in doing so loses chunks of the gzipped histograms which in this workload most likely span multiple packets.

Possible (unsatisfactory, really) solution: purposely slow down the calls to `write_clat_hist_log()` in the while loop inside `iolog.c:td_write_logs()` so as not to overwhelm the client.

Other possible solution: force gzipping of histograms to not cross packet boundaries. This way if packets are lost we only lose some of the data, but are able to retain the data we received properly.

@bengland2: what do the histogram logs look like? Are they completely empty? Do they get cut off?

@axboe: Am I right in assuming that if we see an `unable to find matching tag` error, that some packets will be missing when we try to decompress?

**Comment by bengland2** [comment]
@cronburg - In response to Karl's question above, the histogram logs are typically either present or not present.  I don't see half-written ones.  I did see a few  where there were no log entries for 300 seconds even though log_hist_msec=100, that seems like something unrelated to fio.

I tried Karl's suggestion to slow down the return of the logs to the test driver as a workaround, using 
                sleep(td->thread_number/4);
Right before the call to **fio_send_iolog()** in iolog.c and this seems to work well, even though I get tons of ETA timeouts and "failed to find matching tag" errors.   Even when I generated 23-MB histogram logs from 512 VMs, they all got returned.  Since I'm running tests that have durations measured in hours right now, that's ok for me for now, but it's not ok as a general solution because it takes minutes to return all 512 VMs' logs, and with compression I would expect it to take much less time.

**Comment by bengland2** [comment]
While retrying a small test case with fio-3.2-24-gf273 , I found that the problem still exists (segfault) but can be worked around by disabling compiler -O3 optimization flag!    Ughh.  [See this post about fio](https://github.com/distributed-system-analysis/pbench/issues/734#issuecomment-351419247) for details.

**Comment by axboe** [comment]
What job file are you running to reproduce this?

**Comment by sitsofe** [comment]
@axboe there's a job file mentioned over in https://github.com/distributed-system-analysis/pbench/issues/734#issuecomment-351400593 that might be the one...

**Comment by sitsofe** [comment]
What looks a bit strange is the job name is listed twice - once on the command line and again in the job file itself but I'd be surprised if that's a problem...

**Comment by axboe** [comment]
Because I have a crystal ball, I do some code checking earlier today. Can you check if you can reproduce with current -git? Should have this:

```
commit c20c361255683ee138f0c239e48b315e25725f7e
Author: Jens Axboe <axboe@kernel.dk>
Date:   Wed Dec 13 08:44:34 2017 -0700

    server: initialize first iolog header properly
```

I just ran the test job, and it segfaults without, and works with that commit.

**Comment by bengland2** [comment]
I just pulled upstream fio and compiled without any modification and it runs my job file just fine now where before it segfaulted.  Thanks to your crystal ball.  Precog s/w development I guess.  Leave this open until people in the fio --client user community can test a bit more with it at larger scale, but it seems promising.  I modified jobfile with numjobs=60 log_hist_msec=500 runtime=60 so it would generate a ton of histogram data and it worked perfectly AFAICT.  So maybe this is it.

**Comment by axboe** [comment]
The problem was that log->log_offset ends up containing stack garbage. It's not uncommon for compiler optimizations etc to impact what ends up happening for that. If you get a 0, you'd be fine... So the patch just clears the whole pdu, could have been turned into:

```
      struct cmd_iolog_pdu pdu = {
              .nr_samples             = cpu_to_le64(iolog_nr_samples(log)),
              .thread_number          = cpu_to_le32(td->thread_number),
              .log_type               = cpu_to_le32(log->log_type),
              .log_hist_coarseness    = cpu_to_le32(log->hist_coarseness),
};
```

instead, which probably would be been cleaner / more efficient.

In other words, I'm pretty sure this is the correct fix, so we should be fine to close this bug. Just a shame it was sitting for that long, considering that it took 5 min to fix...

**Comment by bengland2** [comment]
you're right, this particularly issue is closed.  That last part made me more confident, thx.

**Comment by axboe** [comment]
Sorry, should have made it clear in the original reply that I had figured out what the issue was and fixed it.
