### ISSUE TITLE
Different IOPS at random operations at several SSDs testing

### ISSUE THREAD

**Issue by iznam** [axboe/fio#278]
Performance of any SSD drives is different if I test them at the same time by this config:

` 
[global]
bs=4k
iodepth=32
direct=1
ioengine=libaio
time_based
runtime=1800
buffered=0
rw=randread
norandommap

[sdc]
filename=/dev/sdc

[sdd]
filename=/dev/sdd

[sde]
filename=/dev/sde

[sdf]
filename=/dev/sdf
 `

Result is like this:
Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00 68505.00    0.00   267.60     0.00     8.00    31.41    0.46    0.46    0.00   0.01 100.00
sdd               0.00     0.00 66005.00    0.00   257.83     0.00     8.00    31.12    0.47    0.47    0.00   0.02 100.00
sde               0.00     0.00 82208.00    0.00   321.12     0.00     8.00    30.70    0.37    0.37    0.00   0.01 100.00
sdf               0.00     0.00 41171.00    0.00   160.83     0.00     8.00    13.32    0.32    0.32    0.00   0.02  99.60

All drives are the same model, with the same firmware and condition. If I test single drive (for example 
"sdf" from list above) then the drive show normal performance, 68 kIOPs, for example. Each iteration the random drive is "slow". The same result (different performance) if I run single-drive configs for each drive in parallel, like:

`sudo fio sdc.fio & sudo fio sdd.fio & sudo fio sde.fio & sudo fio sdf.fio`

Probably my configuration is wrong. I need to test multiple SSD drives (according to SATA ports) at the same time without performance drop. 

fio-2.15
4.4.0-47-generic
Ubuntu 16.04.1 LTS
MB: Supermicro X10DDW-i

**Comment by sitsofe** [comment]
I can't really say why you got the results you did but here are some suggestions:

Are you secure erasing your SSDs between runs to recondition them? Things like garbage collection could mean the performance of a "fresh" SSD is different to that of an "aged" SSD. See http://www.seagate.com/gb/en/tech-insights/lies-damn-lies-and-ssd-benchmark-master-ti/ for some good information on SSD benchmarking (including the suggestion of multi hour runs).

Also be aware that running all the tests at once may mean you get interference (e.g. if CPU saturation leads to one disk being starved more than others). A quick tip - using `stonewall=1` in the `[global]` section makes fio jobs run sequentially (although you do mention that in your comment).

You might want to set at least the same random seed (see `randseed` in the HOWTO) so the exact same sequence (both data and I/O pattern) is replayed - as you have `norandommap` you may find one SSD is receiving different amounts of overwrites compared to another etc.

One additional thought do you get the same result just reusing the exact same SSD when changing all the above? If not you may be suffering interference from something else on your system (e.g. some periodic action that uses disk or CPU).

**Comment by iznam** [comment]
Hi,
Thank you for the quick reply.

All SSDs are in sustained condition, that means that I did twice "full capacity write" before testing. 
The `stonewall=1` option is suitable for this particular test, because I need to test the case when all drives are loaded (to check each SATA port reliability and throughput when all drives operate).

I'm going to check your last suggestion. But what is really confusing me is that in this problem the QD on random SSD is less than it set in FIO config file (you can check in iostat output in initial message above). I also will check OS settings in `sysfs` for each drive — any suggestions here are appreciated.

Also I see this behavior with different SSDs (Intel, Micron, SanDisk), what can tell us that the problem is not in the drives.

**Comment by iznam** [comment]
Just have repeated the test and noticed again that one (random) drive has actual QD two less than it set up in config. 
For example. In configuration I set `iodepth=32` in global. Right after starting FIO and till its end, I see that one drive uses QD=16 or less, while others three use QD=32. If I `iodepth=16`, then again one drive uses QD=8 or less, others three — QD=16. That one drive every time is different. 
The strange thing is that if I run only three drives at the same time, then all three use QD=32. And does not matter which three I take (it means all drives are in the same condition).

![fio_issue](https://cloud.githubusercontent.com/assets/4847958/21054779/6b36a7f4-be48-11e6-835d-dbb4060cf28e.png)

**Comment by axboe** [comment]
This isn't a fio problem, it's OS behavior. Fio is running the job as listed, and lots of factors will impact how that performs. You have 4 independent processes running IO, which should be fine.Tuning your system for the best performance across a host of drives is really beyond what we can help you with. SATA isn't ideal for the best isolation. Check the IRQ affinity. I'm closing this issue.
