### ISSUE TITLE
FIO segfault when using option --daemonize

### ISSUE THREAD

**Issue by chamarthy** [axboe/fio#286]
FIO seems to be segfaulting when using with daemonize option on coreos7
Following is the jobfile and stacktrace

# fio --daemonize=fio.pid fio_profile.fio
Segmentation fault (core dumped)

# cat fio_profile.fio
[global]
ioengine=libaio
invalidate=1
direct=1
refill_buffers=1
time_based
runtime=864000
file_service_type=random
fsync=1000
fsync_on_close=1
create_on_open=1
do_verify=1
verify=crc32c
iodepth_batch_submit=2
iodepth_low=4
iodepth=16

[job1-file-job-fio-dir1]
directory=/tmp/fio-job1
size=600m
rw=randrw
nrfiles=100
openfiles=10
bs=218k
buffer_compress_percentage=16
buffer_compress_chunk=3k
buffer_pattern=0x22c52a

[job2-file-job-fio-dir2]
directory=/tmp/fio-job2
size=600m
rw=randrw
nrfiles=100
openfiles=10
bs=154k
buffer_compress_percentage=18
buffer_compress_chunk=3k
buffer_pattern=0x4889aa

# gdb /usr/bin/fio core.13633
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/fio...Reading symbols from /usr/lib/debug/usr/bin/fio.debug...done.
done.
[New LWP 13633]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `fio --daemonize=fio.pid fio_profile.fio'.
Program terminated with signal 11, Segmentation fault.
#0  __parse_jobs_ini (td=0x0, is_buf=0, type=1, nested=0, name=0x0, popts=0x0, aopts=0x0, nopts=0x0, stonewall_flag=0, file=0x0) at init.c:1694
1694                    if (!strcmp(file, "-"))
Missing separate debuginfos, use: debuginfo-install boost-system-1.53.0-26.el7.x86_64 boost-thread-1.53.0-26.el7.x86_64 glibc-2.17-157.el7_3.1.x86_64 libaio-0.3.109-13.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libibverbs-1.2.1-1.el7.x86_64 libnl3-3.2.28-2.el7.x86_64 librados2-0.94.5-1.el7.x86_64 librbd1-0.94.5-1.el7.x86_64 librdmacm-1.1.0-2.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libuuid-2.23.2-33.el7.x86_64 nspr-4.11.0-1.el7_2.x86_64 nss-3.21.3-2.el7_3.x86_64 nss-util-3.21.3-1.1.el7_3.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  __parse_jobs_ini (td=0x0, is_buf=0, type=1, nested=0, name=0x0, popts=0x0, aopts=0x0, nopts=0x0, stonewall_flag=0, file=0x0) at init.c:1694
#1  parse_jobs_ini (is_buf=0, type=1, stonewall_flag=0, file=0x0) at init.c:1940
#2  parse_options (argc=argc@entry=3, argv=argv@entry=0x7fffbe7e7aa8) at init.c:2765
#3  0x000000000040e854 in main (argc=3, argv=0x7fffbe7e7aa8, envp=<optimized out>) at fio.c:47

# fio --version
fio-2.17

**Comment by axboe** [comment]
Fixed in current -git:

http://git.kernel.dk/cgit/fio/commit/?id=54441e7b5f44d3786ee12b3fede90c4bb2c2c260

**Comment by chamarthy** [comment]
segfault is fixed now. Thanks,
