### ISSUE TITLE
PID file not generated with --daemonize option.

### ISSUE THREAD

**Issue by chamarthy** [axboe/fio#287]
With #286 segfault is fixed. But now i see that the PID file is not getting generated with --daemonize option.

/usr/bin/fio --output=/tmp/01-18-2017_10-53-53.fio.log --output-format=normal --daemonize=/var/run/fio.pid --status-interval=60 /tmp/01-18-2017_10-53-53.fio

ls -l /var/run/fio.pid
ls: cannot access /var/run/fio.pid: No such file or directory

fio --version
fio-2.17-1-g5444

Thanks for your support.

**Comment by axboe** [comment]
It's only meant to be used when fio is invoked as a backend server, through --server. It's not supposed to do anything for a normal job run.

**Comment by chamarthy** [comment]
Thanks for the clarification Jen's.
