### ISSUE TITLE
FIO file jobs erroring out with invalid_argument

### ISSUE THREAD

**Issue by chamarthy** [axboe/fio#293]
I have a fio job that does randrw to 10 directories with each directory of 100 files with randomly selected bsrange. When i execute the job, its constantly failing with the following error:

From my initial throughts, i feel that at random when bsrange is specified, buflen for the read/write offset seems to be unaligned as in the error message below.

Or am i missing something here.

```
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.35: Invalid argument: read offset=4792320, buflen=30932
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.40: Invalid argument: read offset=4374528, buflen=126407
```

```
# fio 01-25-2017_01-00-37.fio
job1-file-job-fio-dir1: (g=0): rw=randrw, bs=24.0KiB-80.0KiB,24.0KiB-80.0KiB,24.0KiB-80.0KiB, ioengine=libaio, iodepth=16
job2-file-job-fio-dir2: (g=0): rw=randrw, bs=32.0KiB-170KiB,32.0KiB-170KiB,32.0KiB-170KiB, ioengine=libaio, iodepth=16
job3-file-job-fio-dir3: (g=0): rw=randrw, bs=32.0KiB-186KiB,32.0KiB-186KiB,32.0KiB-186KiB, ioengine=libaio, iodepth=16
job4-file-job-fio-dir4: (g=0): rw=randrw, bs=8192B-234KiB,8192B-234KiB,8192B-234KiB, ioengine=libaio, iodepth=16
job5-file-job-fio-dir5: (g=0): rw=randrw, bs=16.0KiB-112KiB,16.0KiB-112KiB,16.0KiB-112KiB, ioengine=libaio, iodepth=16
job6-file-job-fio-dir6: (g=0): rw=randrw, bs=24.0KiB-250KiB,24.0KiB-250KiB,24.0KiB-250KiB, ioengine=libaio, iodepth=16
job7-file-job-fio-dir7: (g=0): rw=randrw, bs=24.0KiB-56.0KiB,24.0KiB-56.0KiB,24.0KiB-56.0KiB, ioengine=libaio, iodepth=16
job8-file-job-fio-dir8: (g=0): rw=randrw, bs=24.0KiB-128KiB,24.0KiB-128KiB,24.0KiB-128KiB, ioengine=libaio, iodepth=16
job9-file-job-fio-dir9: (g=0): rw=randrw, bs=24.0KiB-104KiB,24.0KiB-104KiB,24.0KiB-104KiB, ioengine=libaio, iodepth=16
job10-file-job-fio-dir10: (g=0): rw=randrw, bs=24.0KiB-24.0KiB,24.0KiB-24.0KiB,24.0KiB-24.0KiB, ioengine=libaio, iodepth=16
fio-2.17-1-g5444
Starting 10 processes
job1-file-job-fio-dir1: Laying out IO file(s) (100 file(s) / 600MiB)
job9-file-job-fio-dir9: Laying out IO file(s) (100 file(s) / 600MiB)
job2-file-job-fio-dir2: Laying out IO file(s) (100 file(s) / 600MiB)
job5-file-job-fio-dir5: Laying out IO file(s) (100 file(s) / 600MiB)
job3-file-job-fio-dir3: Laying out IO file(s) (100 file(s) / 600MiB)
job7-file-job-fio-dir7: Laying out IO file(s) (100 file(s) / 600MiB)
job4-file-job-fio-dir4: Laying out IO file(s) (100 file(s) / 600MiB)
job6-file-job-fio-dir6: Laying out IO file(s) (100 file(s) / 600MiB)
job8-file-job-fio-dir8: Laying out IO file(s) (100 file(s) / 600MiB)
job10-file-job-fio-dir10: Laying out IO file(s) (100 file(s) / 600MiB)
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.35: Invalid argument: read offset=4792320, buflen=30932
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.40: Invalid argument: read offset=4374528, buflen=126407
fio: pid=11829, err=22/file:io_u.c:1708, func=io_u error, error=Invalid argument
Jobs: 6 (f=0): [f(1),I(1),f(3),X(1),f(2),I(2)][0.0%][r=193KiB/s,w=0KiB/s][r=4,w=0 IOPS][eta 10d:00h:00m:00s]
job5-file-job-fio-dir5: (groupid=0, jobs=1): err= 0: pid=11828: Wed Jan 25 02:46:58 2017
  mixed: IOPS=486, BW=18.7MiB/s (19.6MB/s)(2080KiB/109msec)
    slat (usec): min=10, max=681, avg=84.36, stdev=132.77
    clat (msec): min=1, max=41, avg=18.91, stdev=12.45
     lat (msec): min=1, max=41, avg=18.99, stdev=12.45
    clat percentiles (usec):
     |  1.00th=[ 1944],  5.00th=[ 4320], 10.00th=[ 4448], 20.00th=[ 5536],
     | 30.00th=[ 5984], 40.00th=[14400], 50.00th=[20352], 60.00th=[22400],
     | 70.00th=[26496], 80.00th=[32640], 90.00th=[36096], 95.00th=[38144],
     | 99.00th=[41216], 99.50th=[41216], 99.90th=[41216], 99.95th=[41216],
     | 99.99th=[41216]
    lat (msec) : 2=1.89%, 4=1.89%, 10=33.96%, 20=3.77%, 50=58.49%
  cpu          : usr=2.78%, sys=8.33%, ctx=20, majf=0, minf=37
  IO depths    : 1=0.0%, 2=3.8%, 4=26.4%, 8=64.2%, 16=3.8%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=53,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16
job6-file-job-fio-dir6: (groupid=0, jobs=1): err=22 (file:io_u.c:1708, func=io_u error, error=Invalid argument): pid=11829: Wed Jan 25 02:46:58 2017
  cpu          : usr=5.26%, sys=0.00%, ctx=2, majf=0, minf=33
  IO depths    : 1=0.0%, 2=12.5%, 4=25.0%, 8=50.0%, 16=12.5%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=16,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  MIXED: bw=18.7MiB/s (19.6MB/s), 18.7MiB/s-18.7MiB/s (19.6MB/s-19.6MB/s), io=2080KiB (2130kB), run=109-109msec

Disk stats (read/write):
  sda: ios=0/11913, merge=0/970, ticks=0/472625, in_queue=472951, util=97.03%
```

Job File:
```
# cat 01-25-2017_01-00-37.fio
[global]
ioengine=libaio
unified_rw_reporting=1
exitall_on_error=1
invalidate=1
direct=1
refill_buffers=1
time_based
runtime=864000
file_service_type=random
fsync=1000
fsync_on_close=1
create_on_open=0
create_serialize=0
do_verify=1
verify=crc32c
iodepth_batch_submit=2
iodepth_low=4
iodepth=16

[job1-file-job-fio-dir1]
directory=/tmp/fio-job1
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-80k
buffer_compress_percentage=12
buffer_compress_chunk=2k
buffer_pattern=0x4409bb

[job2-file-job-fio-dir2]
directory=/tmp/fio-job2
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=32k-170k
buffer_compress_percentage=20
buffer_compress_chunk=2k
buffer_pattern=0x205cda

[job3-file-job-fio-dir3]
directory=/tmp/fio-job3
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=32k-186k
buffer_compress_percentage=24
buffer_compress_chunk=4k
buffer_pattern=0x967a27

[job4-file-job-fio-dir4]
directory=/tmp/fio-job4
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=8k-234k
buffer_compress_percentage=19
buffer_compress_chunk=2k
buffer_pattern=0x55d88d

[job5-file-job-fio-dir5]
directory=/tmp/fio-job5
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=16k-112k
buffer_compress_percentage=14
buffer_compress_chunk=1k
buffer_pattern=0xd635ed

[job6-file-job-fio-dir6]
directory=/tmp/fio-job6
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-250k
buffer_compress_percentage=16
buffer_compress_chunk=3k
buffer_pattern=0x2791d3

[job7-file-job-fio-dir7]
directory=/tmp/fio-job7
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-56k
buffer_compress_percentage=27
buffer_compress_chunk=2k
buffer_pattern=0x27e142

[job8-file-job-fio-dir8]
directory=/tmp/fio-job8
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-128k
buffer_compress_percentage=28
buffer_compress_chunk=2k
buffer_pattern=0x88e16a

[job9-file-job-fio-dir9]
directory=/tmp/fio-job9
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-104k
buffer_compress_percentage=17
buffer_compress_chunk=2k
buffer_pattern=0xd43ab0

[job10-file-job-fio-dir10]
directory=/tmp/fio-job10
size=600m
rw=randrw
nrfiles=100
openfiles=20
bsrange=24k-24k
buffer_compress_percentage=14
buffer_compress_chunk=3k
buffer_pattern=0x836795
```
# fio --version
fio-2.17-1-g5444

On CentOS 7.3

**Comment by chamarthy** [comment]
Problem seems to be with bsrange. If i change the param to bs=8k everything seems to work fine.

**Comment by sitsofe** [comment]
```
[...]
direct=1
[...]
rw=randrw
[...]
bsrange=24k-250k
```

You are asking for direct I/O so you **have** to use I/O sizes that are multiple of whatever the device/filesystem minimum block size is and that I/O must also be well aligned. If my filesystem's minimum block size is 4Kbytes then a block of size 250Kbytes violates that. Further, a maximum bsrange size that is not a multiple of the minimum bsrange size could force non-multiple minimum sized holes to be made (as fio is trying to make sure every area is written once) which would then cause more non well aligned I/O to take place when an attempt is made to fill the hole in...

**Comment by chamarthy** [comment]
Thanks for the clarification Jens. I was auto generating the profile with randomization and something went wrong. I will correct my script. Thanks for the support.

**Comment by sitsofe** [comment]
Actually re-reading the HOWTO for bsrange (http://fio.readthedocs.io/en/sphinx-doc/fio_man.html#cmdoption-arg-bsrange ) says this:

"The issued I/O unit will always be a multiple of the minimum size, unless blocksize_unaligned is set."

So that rule out 250Kbytes ever being submitted down and all spaces should be at least 24Kbytes in size... And yet:

```
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.35: Invalid argument: read offset=4792320, buflen=30932
fio: io_u error on file /tmp/fio-job6/job6-file-job-fio-dir6.0.40: Invalid argument: read offset=4374528, buflen=126407
```

job6 has the following:
```
bsrange=24k-250k
```

30932 is not a multiple of 24k.

@axboe do you know where "issued I/O unit will always be a multiple of the minimum size unless blocksize_unaligned is set" rule is enforced? The closest I can find is https://github.com/axboe/fio/blob/9258468e828cfe1c31b977635994003fe388398e/io_u.c#L579 ...

**Comment by sitsofe** [comment]
(The code in __get_next_buflen will only round to minimum blocksize if minimum blocksize is a power of 2 and 24k is not a power of 2)

**Comment by axboe** [comment]
Maybe set blockalign=4k?

**Comment by sitsofe** [comment]
Jens - I'm wondering if the current documentation needs amending: "issued I/O unit will always be a multiple of the minimum size unless blocksize_unaligned is set" .

Perhaps it would be better for fio just bomb out with an error like "max block size needs to be a multiple of min blocksize unless blockalign/blocksize_unaligned are set"? Then fio doesn't have to apply a correction...

**Comment by sitsofe** [comment]
It looks like this is fixed by commit 17a6b702f221372c919459d7f3fd3a111673403f ...

**Comment by sitsofe** [comment]
@chamarthy is this problem resolved in fio 2.19 or newer and if so could you close this issue?

**Comment by chamarthy** [comment]
Fixed in latest FIO: The same profile as above worked without any issue

**Comment by chamarthy** [comment]
Verified in
# fio --version
fio-2.19-12-gb94d

# fio fio_test
job1-file-job-fio-dir1: (g=0): rw=randrw, bs=(R) 24.0KiB-80.0KiB, (W) 24.0KiB-80.0KiB, (T) 24.0KiB-80.0KiB, ioengine=libaio, iodepth=16
job2-file-job-fio-dir2: (g=0): rw=randrw, bs=(R) 32.0KiB-170KiB, (W) 32.0KiB-170KiB, (T) 32.0KiB-170KiB, ioengine=libaio, iodepth=16
job3-file-job-fio-dir3: (g=0): rw=randrw, bs=(R) 32.0KiB-186KiB, (W) 32.0KiB-186KiB, (T) 32.0KiB-186KiB, ioengine=libaio, iodepth=16
job4-file-job-fio-dir4: (g=0): rw=randrw, bs=(R) 8192B-234KiB, (W) 8192B-234KiB, (T) 8192B-234KiB, ioengine=libaio, iodepth=16
job5-file-job-fio-dir5: (g=0): rw=randrw, bs=(R) 16.0KiB-112KiB, (W) 16.0KiB-112KiB, (T) 16.0KiB-112KiB, ioengine=libaio, iodepth=16
job6-file-job-fio-dir6: (g=0): rw=randrw, bs=(R) 24.0KiB-250KiB, (W) 24.0KiB-250KiB, (T) 24.0KiB-250KiB, ioengine=libaio, iodepth=16
job7-file-job-fio-dir7: (g=0): rw=randrw, bs=(R) 24.0KiB-56.0KiB, (W) 24.0KiB-56.0KiB, (T) 24.0KiB-56.0KiB, ioengine=libaio, iodepth=16
job8-file-job-fio-dir8: (g=0): rw=randrw, bs=(R) 24.0KiB-128KiB, (W) 24.0KiB-128KiB, (T) 24.0KiB-128KiB, ioengine=libaio, iodepth=16
job9-file-job-fio-dir9: (g=0): rw=randrw, bs=(R) 24.0KiB-104KiB, (W) 24.0KiB-104KiB, (T) 24.0KiB-104KiB, ioengine=libaio, iodepth=16
job10-file-job-fio-dir10: (g=0): rw=randrw, bs=(R) 24.0KiB-24.0KiB, (W) 24.0KiB-24.0KiB, (T) 24.0KiB-24.0KiB, ioengine=libaio, iodepth=16
fio-2.19-12-gb94d
Starting 10 processes
job10-file-job-fio-dir10: Laying out IO files (100 files / total 600MiB)
job7-file-job-fio-dir7: Laying out IO files (100 files / total 600MiB)
job1-file-job-fio-dir1: Laying out IO files (100 files / total 600MiB)
job9-file-job-fio-dir9: Laying out IO files (100 files / total 600MiB)
job5-file-job-fio-dir5: Laying out IO files (100 files / total 600MiB)
job3-file-job-fio-dir3: Laying out IO files (100 files / total 600MiB)
job6-file-job-fio-dir6: Laying out IO files (100 files / total 600MiB)
job2-file-job-fio-dir2: Laying out IO files (100 files / total 600MiB)
job4-file-job-fio-dir4: Laying out IO files (100 files / total 600MiB)
job8-file-job-fio-dir8: Laying out IO files (100 files / total 600MiB)
^Cbs: 10 (f=200): [m(10)][0.0%][r=1679MiB/s,w=0KiB/s][r=34.3k,w=0 IOPS][eta 09d:23h:59m:26s]

**Comment by sitsofe** [comment]
Thanks @chamarthy !
