### ISSUE TITLE
testing a specific portion of file / device

### ISSUE THREAD

**Issue by celesteking** [axboe/fio#298]
It would be wonderful to have an option to specify the range of testing. Right now, I have to resort to DM in order to carve the blockdev into segments. 

`--size` works only for 0..$size, and it seems it's impossible to specify start offset.

**Comment by axboe** [comment]
There's an --offset option too.

**Comment by celesteking** [comment]
Yes, my bad, it indeed exists. Haven't read the manual -- it's way too long :)

**Comment by axboe** [comment]
If only there existed a mechanism by which someone, who's reading a document, could search for specific phrases or words. Then you might have found it :-)

**Comment by celesteking** [comment]
I actually did that, I searched for "range" and "portion". I stumbled upon `size`, and kept looking for more. It might worth adding a note to `size` option with reference to `offset` and vice versa.

**Comment by axboe** [comment]
I'm mostly kidding, you used the phrase 'offset' in your issue here and that would have found it. I'm perfectly happy to apply patches to improve the documentation, so please do send that in.
