### ISSUE TITLE
fio verification fails with blocksize_range when used with blocksize_unaligned=1

### ISSUE THREAD

**Issue by devadigayatish** [axboe/fio#299]
I was trying to run fio on a nvme device. 
When tried with **blocksize=4K**, rw=randread and blocksize_unaligned=1, we don't see any errors.
But when we use **blocksize_range=4K-1024K**, rw=randread and blocksize_unaligned=1, we get CRC errors for verification.
**Is it not supposed to work with blocksize_range?**

The fio version used was : fio-2.17-29-gf0ac1

Here are the commands that i executed.

**While writing to device :**

fio --ioengine=sync --iodepth=16 --runtime=60 --time_based --verify=md5 --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --rw=randwrite --do_verify=0 --verify_state_save=1  --blocksize_range=4K-1024K  --blocksize_unaligned=1 --name=job1 --filename=/dev/nvme0n1

job1: (g=0): rw=randwrite, bs=4096B-1024KiB,4096B-1024KiB,4096B-1024KiB, ioengine=sync, iodepth=16
fio-2.17-29-gf0ac1
Starting 1 process
Jobs: 1 (f=1): [f(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]    
job1: (groupid=0, jobs=1): err= 0: pid=3912: Tue Jan 31 04:47:25 2017
  write: IOPS=676, BW=334MiB/s (351MB/s)(19.7GiB/60002msec)
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    0],
     | 99.00th=[    0], 99.50th=[    0], 99.90th=[    0], 99.95th=[    0],
     | 99.99th=[    0]
  cpu          : usr=68.28%, sys=12.44%, ctx=40231, majf=0, minf=3053
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,40604,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=334MiB/s (351MB/s), 334MiB/s-334MiB/s (351MB/s-351MB/s), io=19.7GiB (21.4GB), run=60002-60002msec

Disk stats (read/write):
  nvme0n1: ios=39909/3574553, merge=0/0, ticks=10946/9637934, in_queue=9650213, util=29.45%

**While reading from the device :** 

job1: (g=0): rw=randread, bs=4096B-1024KiB,4096B-1024KiB,4096B-1024KiB, ioengine=sync, iodepth=16
fio-2.17-29-gf0ac1
Starting 1 process
md5: verify failed at file /dev/nvme0n1 offset 48260788224, length 4096
       **Expected CRC: 5483b6f95212ce7cbeedfce11aa8a750**
       **Received CRC: 7feb2265b25f2083c539750dcec933ef**
       received data dumped as nvme0n1.48260788224.received
       expected data dumped as nvme0n1.48260788224.expected
fio: pid=3969, err=84/file:io_u.c:1940, func=io_u_sync_complete, error=**Invalid or incomplete multibyte or wide character**

job1: (groupid=0, jobs=1): err=84 (file:io_u.c:1940, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=3969: Tue Jan 31
 04:47:25 2017
   read: IOPS=142, BW=20.3MiB/s (21.3MB/s)(145KiB/7msec)
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    0],
     | 99.00th=[    0], 99.50th=[    0], 99.90th=[    0], 99.95th=[    0],
     | 99.99th=[    0]
  cpu          : usr=83.33%, sys=16.67%, ctx=44, majf=0, minf=125
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=1,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=20.3MiB/s (21.3MB/s), 20.3MiB/s-20.3MiB/s (21.3MB/s-21.3MB/s), io=145KiB (149kB), run=7-7msec

Disk stats (read/write):
  nvme0n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Comment by sitsofe** [comment]
@devadigayatish It's a bit unusual that you don't have direct=1 (which requires you to have alignment) with your job so you know you're bypassing Linux's page cache but perhaps this is intentional?

Anyway, I'd need to see the read job that you used to verify that particular write job to say anything useful...

**Comment by sitsofe** [comment]
@devadigayatish Could you add the command-line / jobfile that you used to perform the verification?

**Comment by sitsofe** [comment]
This might be related to https://github.com/axboe/fio/issues/335 but I can't tell without @devadigayatish help...

**Comment by sitsofe** [comment]
@devadigayatish can you pull the latest git fio and use if these problems are solved with already or when you use the `serialize_overlap=1` option? If so can you close this issue. Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Comment by devadigayatish** [comment]
Tried with fio version 3.12. The issue is still seen. 
But if we use the parameter "serialize_overlap=1" during writes, we don't see the issue. Hence, not reopening the issue.

**Read operation without using serialize_overlap during writes :** 

sudo /usr/local/bin/fio --ioengine=sync --iodepth=16 --verify=md5 --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --rw=randread --do_verify=1 --verify_state_load=1 --blocksize_range=4K-1024K --blocksize_unaligned=1 --name=job1 --filename=/dev/nvme1n1
job1: (g=0): rw=randread, bs=(R) 4096B-1024KiB, (W) 4096B-1024KiB, (T) 4096B-1024KiB, ioengine=sync, iodepth=16
fio-3.12
Starting 1 process
**verify: bad magic header 6f64, wanted acca at file /dev/nvme1n1 offset 1173372928, length 664005**
fio: pid=8324, err=84/file:io_u.c:2029, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character
job1: (groupid=0, jobs=1): err=84 (file:io_u.c:2029, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=8324: Fri Dec 
14 03:44:12 2018
  read: IOPS=265, BW=128MiB/s (134MB/s)(2086MiB/16328msec)
   bw (  KiB/s): min=126244, max=145013, per=99.98%, avg=130785.62, stdev=3798.70, samples=32
   iops        : min=  224, max=  292, avg=265.75, stdev=15.50, samples=32
  cpu          : usr=54.26%, sys=9.21%, ctx=18952, majf=0, minf=1271
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=4343,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=128MiB/s (134MB/s), 128MiB/s-128MiB/s (134MB/s-134MB/s), io=2086MiB (2187MB), run=16328-16328msec

**Read operation after using serialize_overlap during writes :** 

sudo /usr/local/bin/fio --ioengine=sync --iodepth=16 --verify=md5 --group_reporting --disable_lat=1 --disable_clat=1 --disable_slat=1 --disable_bw_measurement=1 --rw=randread --do_verify=1 --verify_state_load=1 --blocksize_range=4K-1024K --blocksize_unaligned=1 --name=job1 --filename
=/dev/nvme1n1
job1: (g=0): rw=randread, bs=(R) 4096B-1024KiB, (W) 4096B-1024KiB, (T) 4096B-1024KiB, ioengine=sync, iodepth=16
fio-3.12
Starting 1 process
Jobs: 1 (f=1): [V(1)][80.0%][r=35.7MiB/s][r=137 IOPS][eta 00m:30s]
job1: (groupid=0, jobs=1): err= 0: pid=18408: Fri Dec 14 03:59:19 2018
  read: IOPS=343, BW=128MiB/s (134MB/s)(14.9GiB/119151msec)
   bw (  KiB/s): min=38778, max=147401, per=99.70%, avg=130597.46, stdev=7402.85, samples=239
   iops        : min=  158, max=  488, avg=342.54, stdev=58.95, samples=239
  cpu          : usr=53.48%, sys=10.42%, ctx=143390, majf=0, minf=3304
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=40939,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=128MiB/s (134MB/s), 128MiB/s-128MiB/s (134MB/s-134MB/s), io=14.9GiB (15.0GB), run=119151-119151msec
