### ISSUE TITLE
failed to load engine libhdfs

### ISSUE THREAD

**Issue by ankitpateledu** [axboe/fio#301]
Hi All 
I am trying to launch fio via hdfs; i want to measure bandwidth and latency through hdfs on my setup 
i was able to install FIO on my Centos7 machines; but run into issue as below.

>  ./fio --name=random-writers --ioengine=libhdfs --iodepth=4 --rw=randwrite --bs=32k --direct=0 --size=64m --numjobs=4
fio: engine libhdfs not loadable
fio: failed to load engine libhdfs
fio: file:ioengines.c:91, func=dlopen, error=libhdfs: cannot open shared object file: No such file or directory

can you help me figuring out what is missing?

**Comment by sitsofe** [comment]
Did ./configure enable hdfs? If it says no you will have to investigate why the configure process can't find the libraries it is looking for...

**Comment by ankitpateledu** [comment]
while doing ./configure  idont see libhdfs or hdfs mention.
am i looking at right place to address your question?

> Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no
Static build                  no
Wordsize                      64
zlib                          no
Linux AIO support             no
POSIX AIO support             yes
POSIX AIO support needs -lrt  yes
POSIX AIO fsync               yes
Solaris AIO support           no
__sync_fetch_and_add          yes
libverbs                      no
rdmacm                        no
Linux fallocate               yes
POSIX fadvise                 yes
POSIX fallocate               yes
sched_setaffinity(3 arg)      yes
sched_setaffinity(2 arg)      no
clock_gettime                 yes
CLOCK_MONOTONIC               yes
CLOCK_MONOTONIC_RAW           yes
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     yes
sync_file_range               yes
EXT4 move extent              yes
Linux splice(2)               yes
GUASI                         no
Fusion-io atomic engine       no
libnuma                       no
strsep                        yes
strcasestr                    yes
strlcat                       no
getopt_long_only()            yes
inet_aton                     yes
socklen_t                     yes
__thread                      yes
RUSAGE_THREAD                 yes
SCHED_IDLE                    yes
TCP_NODELAY                   yes
Net engine window_size        yes
TCP_MAXSEG                    yes
RLIMIT_MEMLOCK                yes
pwritev/preadv                yes
pwritev2/preadv2              no
IPv6 helpers                  yes
Rados Block Device engine     no
rbd blkin tracing             no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           yes
libpmem                       no
libpmemblk                    no
NVML pmemblk engine           no
NVML dev-dax engine           no
lex/yacc for arithmetic       no
getmntent                     yes
getmntinfo                    no
Static Assert                 yes
bool                          yes
march_armv8_a_crc_crypto      no
Consider installing zlib-dev (zlib-devel), some fio features depend on it.

**Comment by sitsofe** [comment]
> s390_z196_facilities no
> **HDFS engine no**
> MTD yes

Isn't that saying it can't find the hdfs dependencies? If so I don't think this is an "issue" and is rather is a "how do I?" question that would be better aimed at the mailing list (https://github.com/axboe/fio/blob/fio-2.17/README#L77 ).

**Comment by ankitpateledu** [comment]
Oops, sorry i did quick search for "hdfs" rather than "HDFS" i will transfer this question to mailing list 
thanks for quick response

**Comment by sitsofe** [comment]
@ankitpateledu  Assuming you solved your problem can you close this issue?

**Comment by ankitpateledu** [comment]
for now I am closing the issue and I am taking conversation to mailing list as you have proposed
is it OK to re-open the issue in case i dont get any lead there?
thank you

**Comment by ankitpateledu** [comment]
my messages to fio@vger.kernel.org are going undelivered with this message 


![image](https://cloud.githubusercontent.com/assets/25492444/22570810/c039fd30-e951-11e6-848c-a84f1c34376b.png)

**Comment by axboe** [comment]
The answer to the problem is in the error - your message contains HTML, which is explicitly rejected by the fio reflector.

**Comment by ankitpateledu** [comment]
sorry but this is out of my understanding;? how can i remove HTML portion? from my email?

**Comment by axboe** [comment]
What email client are you using? Usually there are options to compose messages in either html, plain text, or an email that has both parts. The error sounds like it's the latter, that your email has both a text/plain and text/html part. You want to ensure that you don't send with any HTML, or it will be rejected.
