### ISSUE TITLE
Runtime failure on macOS 10.11 when built using Xcode 8

### ISSUE THREAD

**Issue by JCount** [axboe/fio#305]
Building on macOS 10.11 using Xcode 8 completes without error, however there is a runtime error of:
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/fio/2.17/bin/fio
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/fio/2.17/bin/fio
  Expected in: /usr/lib/libSystem.B.dylib
```
This occurs because the Xcode 8 SDK declares clock_gettime for both 10.11 and 10.12, even though it is only actually implemented on 10.12. This means that a simple test to see if the symbol is declared is not sufficient when building for macOS 10.11.

Currently, when building with/for this platform, one way to work around this problem seems to be to modify the configure script to ensure that the clock_gettime probe will fail.

I am happy to try and provide any other information you may need.

**Comment by sitsofe** [comment]
@JCount Ugh, not sure I like what Apple introduced here. Looking around many projects are going to suffer this and homebrew seems to workaround it by using the -no_weak_imports linker flag (https://github.com/Homebrew/homebrew-core/issues/3727 ). I would suggest that you change the formula to modify the configure script to add this flag. Does that workaround the problem?

**Comment by ilovezfs** [comment]
Nope, we don't and can't use that flag as a solution since it breaks Xcode 7.

**Comment by sitsofe** [comment]
@ilovezfs  In https://github.com/Homebrew/brew/pull/721 it isonly set whe targeting Xcode 8 and it's injected via LDFLAGS. Perhaps the best thing is to teach the Makefile to inject existing LDFLAGS in the Makefile for the Darwin platform: https://github.com/axboe/fio/blob/master/Makefile#L178 (see what the BSDs do above).

**Comment by ilovezfs** [comment]
@sitsofe that was subsequently reverted. Trust me. I've been the one doing most of the clock_gettime PRs for Homebrew.

**Comment by ilovezfs** [comment]
@sitsofe these are what proper solutions look like:

https://github.com/pyca/cryptography/pull/3354
https://github.com/jsquyres/libfabric/commit/469779935f9995b88a6f486fe3c4c4496989af36
https://github.com/jemalloc/jemalloc/commit/eb29d7ec0e2c4994e10ec40d42265a86e569500c
https://github.com/tarantool/tarantool/commit/d36ba2796839db0edd3c62e9048cd41b1ee08d1e

**Comment by sitsofe** [comment]
@ilovezfs Thanks for the links - I was just going through the giant list on https://github.com/Homebrew/homebrew-core/issues?utf8=%E2%9C%93&q=label%3Aclock_gettime%20 . This Apple change is disappointing because it doesn't cause the existing test to fail at compilation time, only at runtime. My Mac doesn't have Xcode 8 so could you let me know what happens with the following:

```
#include <stdio.h>
#include <time.h>
int main(int argc, char **argv)
{
#ifdef __APPLE__
#include <AvailabilityMacros.h>
#if MAC_OS_X_VERSION_MIN_REQUIRED < 101200
# error "Target OSX version too old to support clock_gettime"
#endif
#endif
  return clock_gettime(0, NULL);
}
```

**Comment by ilovezfs** [comment]
Yes, that does the trick. On 10.11:
```
iMac-TMP:1011 joe$ export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
iMac-TMP:1011 joe$ export MACOSX_DEPLOYMENT_TARGET=10.11
iMac-TMP:1011 joe$ clang foo.c
foo.c:8:3: error: "Target OSX version too old to support clock_gettime"
# error "Target OSX version too old to support clock_gettime"
  ^
1 error generated.
iMac-TMP:1011 joe$ export MACOSX_DEPLOYMENT_TARGET=10.12
iMac-TMP:1011 joe$ clang foo.c
iMac-TMP:1011 joe$ ./a.out 
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/joe/1011/./a.out (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/joe/1011/./a.out (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
iMac-TMP:1011 joe$
```
In the long-run `-no_weak_imports` should make life a bit easier once Xcode 7 and version 7 CLT is totally out of the picture. That said, there is almost no one happy with their current unitary SDK approach, but such is life.

**Comment by sitsofe** [comment]
@ilovezfs Do you know if the above is the wrong thing due to platforms like iOS?

@ilovezfs, @axboe if the explicit OSX version check above is no good I guess the alternative is a manual `--disable-clock_gettime` flag:
```patch
diff --git a/configure b/configure
index d0c2173..ae33bd4 100755
--- a/configure
+++ b/configure
@@ -184,6 +184,8 @@ for opt do
   ;;
   --disable-pmem) disable_pmem="yes"
   ;;
+  --disable-clock_gettime) disable_gettime="no"
+  ;;
   --help)
     show_help="yes"
     ;;
@@ -211,6 +213,7 @@ if test "$show_help" = "yes" ; then
   echo "--enable-lex           Enable use of lex/yacc for math"
   echo "--disable-shm          Disable SHM support"
   echo "--disable-optimizations Don't enable compiler optimizations"
+  echo "--disable-clock_gettime Disable use of clock_gettime"
   exit $exit_val
 fi
 
@@ -749,9 +752,9 @@ int main(int argc, char **argv)
   return clock_gettime(0, NULL);
 }
 EOF
-if compile_prog "" "" "clock_gettime"; then
+if test "$disable_gettime" != "yes"  && compile_prog "" "" "clock_gettime"; then
     clock_gettime="yes"
-elif compile_prog "" "-lrt" "clock_gettime"; then
+elif test "$disable_gettime" != "yes" && compile_prog "" "-lrt" "clock_gettime"; then
     clock_gettime="yes"
     LIBS="-lrt $LIBS"
 fi
```

**Comment by ilovezfs** [comment]
No, I'm saying the fix is good!

**Comment by ilovezfs** [comment]
The fancier way to do this by the way is to use weak linking and declare
```
extern int clock_gettime() __attribute__((weak_import));
```
and then
```
#ifdef CLOCK_REALTIME
if(clock_gettime) {

    struct timespec start, stop;
    double accum;

    if( clock_gettime( CLOCK_REALTIME, &start) == -1 ) {
      perror( "clock gettime" );
      exit( EXIT_FAILURE );
    }
```
and pass -weak_library to the linker.

**Comment by sitsofe** [comment]
@ilovezfs weak_library is definitely fancier but more OSX specific.

I was just speculating that while my first attempt worked it was a bit nasty to hardcode info in the test itself and that there might be other Apple platforms out there (iOS -is that even likely for something like fio?) that the test would spuriously fail on...

**Comment by ilovezfs** [comment]
I wouldn't worry about it. You're in good company with the AvailabilityMacros.h +  MAC_OS_X_VERSION_MIN_REQUIRED approach. If you're concerned about platform too I think you can `#include <TargetConditionals.h>` and check for `TARGET_OS_MAC`.

**Comment by sitsofe** [comment]
@ilovezfs OK thanks for the hint. So it's either the "automatic hardcoded check at configure time":
```c
#include <time.h>
int main(int argc, char **argv)
{
#ifdef __APPLE__
# include <AvailabilityMacros.h>
# include <TargetConditionals.h>
# if TARGET_OS_MAC && MAC_OS_X_VERSION_MIN_REQUIRED < 101200
#  error "Target OSX version too old to support clock_gettime"
# endif
#endif
  return clock_gettime(0, NULL);
}
```

Or the "manual disable clock_gettime override" of https://github.com/axboe/fio/issues/305#issuecomment-277509502 .

Jens: Any thoughts on what you'd prefer?

**Comment by ilovezfs** [comment]
FWIW: I'd highly recommend the "automatic hardcoded check at configure time" over requiring the explicit configure CLI option.

**Comment by ilovezfs** [comment]
Note that you may want to automatically set MACOSX_DEPLOYMENT_TARGET to be the same as the host unless the user has already set MACOSX_DEPLOYMENT_TARGET in the environment. For Homebrew we always set `MACOSX_DEPLOYMENT_TARGET=#{MacOS.version}` so it's not an issue for us, but if it's not set it's going to be `MAC_OS_X_VERSION_MIN_REQUIRED 101200` by default on 10.11 when SDKROOT is the Xcode 8 SDK.

**Comment by sitsofe** [comment]
@ilovezfs So if I'm on 10.11 and do a build with, say, the command line tools of Xcode 8 in a stock environment then I get MAC_OS_X_VERSION_MIN_REQUIRED 101200 and I'm back to square one?

Can you confirm a few things:
1. `clock_gettime()` was introduced in 10.12 but doesn't exist on older versions of OSX.
2. If you don't set an explicit target you can target a platform later than the platform you're building on if Xcode knows of one.
3. Xcode 8 only exists on 10.11 and 10.12.
4. Xcode 8 lets the linker find the `clock_gettime()` symbol at compile time even if you're targeting an older version of OSX because of weak symbols.
5. Using the -no_weak_imports linker flag only works in Xcode 8 and causes breakage on Xcode 7 because it's not supported there.
6. Explicit target `#define` checks can create binaries that won't run on the (10.11) host platform because of 2 and 4.

Sigh, there's no escape :-) I guess I feel bad for people on 10.11 who are using a "compiler with SDKs from the future" but I also feel this is Apple's fault for enabling weak symbols by default and not allowing them to be turned off in a manner that won't cause older compilers to scream. If I wind up using an "SDK from the future" I can only hope someone warns me to make sure I am targeting my host platform if I plan to run binaries there (or better yet that should be the default as homebrew has done)...

**Comment by ilovezfs** [comment]
The "version 8 command line tools" are distinct from the command line tools in the Xcode.app SDK. The former is usually referred to as "the CLT" and the latter referred to as "Xcode" or "the Xcode SDK." You will have 101100 by default with the former, and 101200 by default with the latter. Note that the CLT is a totally separate download from Xcode.app and that most users will not have it.

1. clock_gettime() was introduced in 10.12 but doesn't exist on older versions of OSX.
correct

10.11:
```
iMac-TMP:~ joe$ nm /usr/lib/system/libsystem_c.dylib |grep clock
0000000000006209 T __init_clock_port
0000000000025ec2 T _clock
                 U _clock_get_time
0000000000092004 D _clock_port
0000000000092000 D _clock_sem
0000000000095f18 b _get_clock.adjustment
0000000000095f30 b _get_clock.clock_seq
0000000000095f20 b _get_clock.last
                 U _host_get_clock_service
```
10.12:
```
Josephs-Mac:~ joe$ nm /usr/lib/system/libsystem_c.dylib |grep clock
00000000000874f1 S $ld$weak$os10.11$_clock_getres
00000000000874f2 S $ld$weak$os10.11$_clock_gettime
00000000000874f3 S $ld$weak$os10.11$_clock_settime
00000000000077f5 T __init_clock_port
000000000002698d T _clock
                 U _clock_get_time
00000000000023b8 T _clock_getres
00000000000021e9 T _clock_gettime
0000000000001ff0 T _clock_gettime_nsec_np
0000000000091004 D _clock_port
0000000000091000 D _clock_sem
0000000000002439 T _clock_settime
0000000000094d8c b _get_clock.adjustment
0000000000094da0 b _get_clock.clock_seq
0000000000094d90 b _get_clock.last
                 U _host_get_clock_service
Josephs-Mac:~ joe$
```
2. correct
3. correct (and I believe 8.3 will be 10.12 only)
4. correct
5. correct. And it is possible to have the version 7 CLT and version 8 Xcode.app installed simultaneously as a valid configuration. (a version 8 CLT for 10.11 only very recently became available)
6. correct

**Comment by sitsofe** [comment]
After a certain amount of pain I've come up with https://github.com/sitsofe/fio/tree/test_gettime which uses `-no_weak_imports`. @ilovezfs could you see if it resolves the issue where using the 10.12 SDK to target OSX 10.11 or older results in a binary that doesn't work? It won't automatically set  `MACOSX_DEPLOYMENT_TARGET` to your host platform if unset but I feel that should be for Apple to do rather than forcing it on every individual project and hopefully the number of people using a later SDK than their platform is small and only happens for a short period of time...

**Comment by JCount** [comment]
@sitsofe Good work and thank you. I was able to successfully build and run `fio 2.17` on OS X 10.11 using the Xcode 8 SDK (10.12) after applying the commit from your tree as a patch.

I am attaching some output, I can provide more if you would like.

```
==> Patching
==> Applying fa75374416c643c8f8d5e0c1331e8472844919ef.diff
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/fio--patch-20170212-33492-1aelco2/fa75374416c643c8f8d5e0c1331e8472844919ef.diff
patching file configure
==> ./configure
Disabling weak symbols
Operating system              Darwin
CPU                           x86_64
Big endian                    no
Compiler                      clang
Cross compile                 no

Static build                  no
Wordsize                      64
zlib                          yes
Linux AIO support             no
POSIX AIO support             yes
POSIX AIO support needs -lrt  no
POSIX AIO fsync               yes
Solaris AIO support           no
__sync_fetch_and_add          yes
libverbs                      no
rdmacm                        no
Linux fallocate               no
POSIX fadvise                 no
POSIX fallocate               no
sched_setaffinity(3 arg)      no
sched_setaffinity(2 arg)      no
clock_gettime                 no
CLOCK_MONOTONIC               no
CLOCK_MONOTONIC_RAW           no
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     yes
sync_file_range               no
EXT4 move extent              no
Linux splice(2)               no
GUASI                         no
Fusion-io atomic engine       no
libnuma                       no
strsep                        yes
strcasestr                    yes
strlcat                       yes
getopt_long_only()            yes
inet_aton                     yes
socklen_t                     yes
__thread                      yes
RUSAGE_THREAD                 no
SCHED_IDLE                    no
TCP_NODELAY                   yes
Net engine window_size        yes
TCP_MAXSEG                    yes
RLIMIT_MEMLOCK                yes
pwritev/preadv                no
pwritev2/preadv2              no
IPv6 helpers                  yes
Rados Block Device engine     no
rbd blkin tracing             no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           no
libpmem                       no
libpmemblk                    no
NVML pmemblk engine           no
NVML dev-dax engine           no
lex/yacc for arithmetic       yes
getmntent                     no
getmntinfo                    yes
Static Assert                 no
bool                          yes
march_armv8_a_crc_crypto      no
```
```
nm /usr/local/bin/fio | grep clock
00000001000098e2 T _fio_clock_init
0000000100059380 D _fio_clock_source
0000000100028bda t _fio_clock_source_cb
0000000100059384 d _fio_clock_source_inited
00000001000faacc S _fio_clock_source_set
00000001000098dc T _fio_local_clock_init
0000000100009c55 T _fio_monotonic_clocktest
```

**Comment by sitsofe** [comment]
@JCount @ilovezfs hopefully this is fixed by https://github.com/axboe/fio/pull/309 .

**Comment by sitsofe** [comment]
@JCount thanks for checking and @ilovezfs thanks for the detailed explanations (there's no way I would have known you needed to export `MACOSX_DEPLOYMENT_TARGET` **and** `SDKROOT` on 10.11 to get the problem to show).

Is there any chance you could update https://github.com/Homebrew/homebrew-core/pull/9644 to have the clock_gettime label? It might help someone else to eventually find this issue and give them another reference to how people approached this problem.

**Comment by JCount** [comment]
@sitsofe I would be happy to add the label. Thank you again for doing the work to develop a proper fix. We as a downstream really appreciate it, especially since this mean we no longer have to be hacking the configure script.

**Comment by sitsofe** [comment]
@JCount - did the patch fix the problem for you and if so could you close this issue? Thanks!

**Comment by JCount** [comment]
The patch fixes the problem. Sorry, I meant to close the issue but lost track of doing it. Once again, thanks.
