### ISSUE TITLE
New version fio can not prepare test file when --rw=read

### ISSUE THREAD

**Issue by hm-yang** [axboe/fio#311]
Hi,

I update my fio today and try to do some io testing.
I try to create some read and write simulation, but when I define read I/O, fio will response
"fio: pid=12791, err=2/file:filesetup.c:622, func=open(/tmp/test1), error=No such file or directory"

1) A description of what you think the bug is
I try to test read and write operation, this bug just happen when --rw=read/randread.
Seems like fio will not prepare test file first.

2) Environment (Linux distro version, kernel version). This is mostly needed if it's a build bug.

```
root@hmvm01:~/fio# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
root@hmvm01:~/fio# git rev-parse HEAD
b3e7e59290577696dc76c08651cce1e121cff64a
root@hmvm01:~/fio# ./fio --version
fio-2.17-58-gb3e7e
```

3) The output from fio --version.
fio-2.17-58-gb3e7e

4) How to reproduce. Please include a full list of the parameters passed to fio and the job file used (if any).
Just run read test first without create target file. For example,

```
root@hmvm01:~/fio# ./fio --ioengine=libaio --rw=randread --numjobs=1 --iodepth=256 --bs=1M --size=10G --direct=1 --filename=/tmp/test100 --name=test
test: (g=0): rw=randread, bs=1024KiB-1024KiB,1024KiB-1024KiB,1024KiB-1024KiB, ioengine=libaio, iodepth=256
fio-2.17-58-gb3e7e
Starting 1 process
fio: pid=12888, err=2/file:filesetup.c:622, func=open(/tmp/test100), error=No such file or directory


Run status group 0 (all jobs):

Disk stats (read/write):
    dm-0: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
```

Thanks,

**Comment by sitsofe** [comment]
Pre-layout still happens correctly for rw=write jobs but not rw=read ones. A git bisect has narrowed it down to this:

```
34c9f82301a584899a9e65e4b9f56d98c38a52e7 is the first bad commit
commit 34c9f82301a584899a9e65e4b9f56d98c38a52e7
Author: Tomohiro Kusumi <tkusumi@tuxera.com>
Date:   Tue Feb 14 17:19:45 2017 +0200

    Always set ->real_file_size to -1 when failed to get file size
    
    In some cases it's set to -1, but on others it's not,
    while the existing code (e.g. get_fs_free_counts(), setup_files(), etc)
    seem to expect ->real_file_size to be -1 in case of any error.
    
    Signed-off-by: Tomohiro Kusumi <tkusumi@tuxera.com>
    Signed-off-by: Jens Axboe <axboe@fb.com>
```

Any ideas @kusumi ?

**Comment by axboe** [comment]
Thanks for your report! I've found the recent regression that introduced this and reverted it. If you git pull and get an updated copy, it should work fine for you again.

**Comment by axboe** [comment]
I wish I had read the full report first, since Sitsofe had already done the bisect. Oh well, it was a 5 minute thing.

**Comment by kusumi** [comment]
Sorry about the regression.
I failed to catch that because the files have been there already.
Yes, get_file_size() returning with non-zero isn't necessarily an error as a whole.

**Comment by hm-yang** [comment]
It is a good news, thank you very much :)
