### ISSUE TITLE
(request) Is there a way currently to have mix distribution for sequential writes and random reads

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#315]
I am trying to do this type of workload and was wondering if this can be done on a raw drive with current fio parameters :
Workload requested by host: 
1)Sequential writes (60%)
2)Random reads (40%)

i am not sure which parameter to use so that it generates a mix workload of sequential writes and random reads, below parameters should confirm that at given point of time it should try to have 40% read and those 40% to be random.
rwmixread= 40  <this confirms 30% is read> 
percentage random =40, 0 , 0 <this confirms that 30% is random reads>

**Comment by sitsofe** [comment]
To do what you're describing I'd look at using one job to do the sequential writes and another job to do the random reads and then use the [flow](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-flow) parameter to control the amount of I/O each job does relative to the other.

This sort of "how do I?" question might be better asked on the [mailing list](https://github.com/axboe/fio/blob/fio-2.17/README#L77) though...

**Comment by akoundal** [comment]
@sitsofe  thanks for letting me know the mailing list ...point very well taken. 
Appreciate your support ...cheers!!
