### ISSUE TITLE
fio --client ETA messages limit scalability

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#317]
The polling of ETA messages once a second to every fio subprocess limits scalability.  An ideal solution would be to make ETA polling rate be adjustable, with default still as it is today.  For large-scale tests with hundreds or thousands of fio processes (example use case: distributed storage), a ETA poll rate of 10 seconds would be adequate, for example.   This is becoming particularly important as we start to try to use fio --client to generate workload from inside containers backed by distributed storage, for example.  Do people agree with the problem statement?

**Comment by axboe** [comment]
Making that configurable is perfectly reasonable, as long as it applies to both net client and normal runs. For instance, both of them have "1s +/- slack":

client.c:			if (mtime_since(&eta_tv, &tv) >= 900) {
eta.c:	if (!force && disp_time < 900)

I think we should just add an option for this, and have a within_slack() something function that says if we're close (+/- 10%?).

**Comment by bengland2** [comment]
--eta=never doesn't seem to work :-(    I expected that a command like
```
./fio --client=localhost --eta=never --name=randread ../../pbench-fio-2.14-2/bentest.job
```
would result in no ETA messages but I still see the same display of IOPS etc every second, so ETA messages must still be happening right?   I still would prefer control of the ETA rate described in initial post above, but --eta=never would at least be a workaround for scaling fio to large process counts.  Also, what do --eta=always and --eta=auto mean?

and --status-interval=10 did not do what I expected either.  Same every-second status update.

**Comment by axboe** [comment]
They are local options. It's a little deceptive with fio, since you can use them interchangeably, but they are not per-job options and as such they don't get passed to the backend. Does it work if you use --eta=never on the server side?

I can try and play with it here.

**Comment by axboe** [comment]
OK, that one was just a bug, I think. Try current -git.

**Comment by bengland2** [comment]
so that fixed --eta=never, thx.   Will see if we need adjustable ETA poll rate suggested in original post.  I need to experiment a bit at scale.

**Comment by axboe** [comment]
http://git.kernel.dk/cgit/fio/commit/?id=db37d89074ed204c9c2bd010e72f63dcf4725715

should take care of it.

**Comment by sitsofe** [comment]
@bengland2 were things any better and if so could you close this issue (and if not please report back)? Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
