### ISSUE TITLE
json output include other string while using rbd.

### ISSUE THREAD

**Issue by hwchiu** [axboe/fio#325]
Hi.

I use the current version fio (2017/03/13) to test rbd(ceph) and I use the following command
`./fio test.info --output-format=json --output=output.json`
you can see the test.info [here](https://gist.github.com/hwchiu/ab515d9a7358ce936cc7550006db6825)
and the output file **output.json** contains some non-json data, such as rbd version.
the output file is [here](https://gist.github.com/hwchiu/5b67e27686564807f6f5b6ff522eb08e).

I want to use the json parse to parse the output format but it fails.
Do I have any other parameters to help me remove those non-json data in output ?

Thanks.

**Comment by axboe** [comment]
I fixed that up now and pushed it out. The rbd engine should not print version info, I just removed it.
