### ISSUE TITLE
fio does not pump any IOs after it reaches size, if runtime specified

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#329]
IOs stop after size has been reached with runtime is specified. 

Fio Version: 2.17
OS: Cent 7.2 

Sctipt:
./fio --filename=/dev/nvme0n1 --name=T1 --size=1G --time_based --runtime=10000 

I was expecting FIO to continuously do IOs till the specified time has been reached in 1G range. But fio stops pumping IOs after issuing IOs of total size 1G. Does fio treat "size" as "io_size"?

If my understanding is right, this should be the behavior if io_size it used.

I am taking a deeper look into the issue, but thought of logging it for the records. 

Thanks,
Shiva Pahwa

**Comment by sitsofe** [comment]
I can't reproduce this problem here:

```
./fio --ioengine=null --name=T1 --size=1G --time_based --runtime=10s
T1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-2.18-51-g9486-dirty
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=6993MiB/s,w=0KiB/s][r=1790k,w=0 IOPS][eta 00m:00s]
T1: (groupid=0, jobs=1): err= 0: pid=43533: Fri Mar 31 11:36:20 2017
   read: IOPS=1910k, BW=7460MiB/s (7823MB/s)(72.9GiB/10000msec)
    clat (usec): min=0, max=1343, avg= 0.08, stdev= 0.50
     lat (usec): min=0, max=1343, avg= 0.14, stdev= 0.55
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    1],
     | 99.00th=[    1], 99.50th=[    1], 99.90th=[    1], 99.95th=[    1],
     | 99.99th=[    1]
    lat (usec) : 2=99.99%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
    lat (usec) : 250=0.01%
    lat (msec) : 2=0.01%
  cpu          : usr=99.12%, sys=0.72%, ctx=185, majf=0, minf=23
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=19098502,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=7460MiB/s (7823MB/s), 7460MiB/s-7460MiB/s (7823MB/s-7823MB/s), io=72.9GiB (78.3GB), run=10000-10000msec
```

What you are describing is as if `--time_based` is not being set. Can you make this problem happen on 2.18 too? Can you show the output of the job when it finishes?

**Comment by axboe** [comment]
I can't reproduce it in 2.17 either. As Sitsofe says, please paste the full output of the run, including how it was invoked.

**Comment by shivapahwa** [comment]
Command line:
./fio --filename=/dev/nvme0n1 --name=T1 --size=1G --time_based --runtime=1m --ioengine=libaio

If you look at the FIO output it would appear that FIO is doing IOs. But when you look at the output of iotop/ blktrace you will notice after 1G data is transferred FIO stops sending IO commands to the device.

Please find the output from blktrace and fio below:
 
Command: blktrace -d /dev/nvme1n1 -o - | blkparse -i - 
Output:
CPU4 (259,0):
 Reads Queued:       2,176,  417,792KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:    2,176,  278,528KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:    2,176,  278,528KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:         1,088        	 Timer unplugs:           0
CPU5 (259,0):
 Reads Queued:         726,  139,392KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:      726,   92,928KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:      726,   92,928KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:           363        	 Timer unplugs:           0
CPU6 (259,0):
 Reads Queued:       1,378,  264,576KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:    1,378,  176,384KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:    1,378,  176,384KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:           689        	 Timer unplugs:           0
CPU7 (259,0):
 Reads Queued:       3,336,  640,512KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:    3,336,  427,008KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:    3,336,  427,008KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:         1,668        	 Timer unplugs:           0
CPU9 (259,0):
 Reads Queued:         374,   71,280KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:      374,   47,600KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:      374,   47,600KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:           187        	 Timer unplugs:           2
CPU11 (259,0):
 Reads Queued:         194,   37,248KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:      194,   24,832KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:      194,   24,832KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:            97        	 Timer unplugs:           0
CPU12 (259,0):
 Reads Queued:          14,    2,688KiB	 Writes Queued:           0,        0KiB
 Read Dispatches:       14,    1,792KiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:       14,    1,792KiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 Read depth:             2        	 Write depth:             0
 IO unplugs:             7        	 Timer unplugs:           0

Total (259,0):
 Reads Queued:       8,198,    1,573MiB	 Writes Queued:           0,        0KiB
 Read Dispatches:    8,198,    1,049MiB	 Write Dispatches:        0,        0KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:    8,198,    1,049MiB	 Writes Completed:        0,        0KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 IO unplugs:         4,099        	 Timer unplugs:           2

Throughput (R/W): 81,741KiB/s / 0KiB/s
Events (259,0): 45,091 entries
Skips: 0 forward (0 -   0.0%)

FIO output:
./fio --filename=/dev/nvme1n1 --name=T1 --size=1G --time_based  --runtime=1m --ioengine=libaio
T1: (g=0): rw=read, bs=4096B-4096B,4096B-4096B,4096B-4096B, ioengine=libaio, iodepth=1
fio-2.17
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=3881MiB/s,w=0KiB/s][r=994k,w=0 IOPS][eta 00m:00s]
T1: (groupid=0, jobs=1): err= 0: pid=21918: Mon Apr  3 09:16:48 2017
   read: IOPS=972k, BW=3795MiB/s (3979MB/s)(222GiB/60001msec)
    slat (usec): min=0, max=1093, avg= 0.69, stdev= 1.28
    clat (usec): min=0, max=426, avg= 0.21, stdev= 0.43
     lat (usec): min=0, max=1099, avg= 0.90, stdev= 1.26
    clat percentiles (usec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    1], 90.00th=[    1], 95.00th=[    1],
     | 99.00th=[    1], 99.50th=[    1], 99.90th=[    1], 99.95th=[    1],
     | 99.99th=[    2]
    lat (usec) : 2=99.98%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
    lat (usec) : 500=0.01%
  cpu          : usr=29.55%, sys=69.91%, ctx=3372, majf=0, minf=9
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=58292742,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=3795MiB/s (3979MB/s), 3795MiB/s-3795MiB/s (3979MB/s-3979MB/s), io=222GiB (239GB), run=60001-60001msec

Disk stats (read/write):
  nvme1n1: ios=8198/0, merge=0/0, ticks=2437/0, in_queue=2436, util=1.75%

**Comment by sitsofe** [comment]
There's no `--direct=1` and you're doing reads on that fio command. If you have enough RAM that 1GByte of data is going to be cached and the kernel will be able to serve it out of cache...

**Comment by sitsofe** [comment]
(PS: a warning sign that this might be happening is that some of your lowest total latency is 0:
```
lat (usec): min=0, max=1099, avg= 0.90, stdev= 1.26
```
)

**Comment by shivapahwa** [comment]
You are right!  It never appeared to me that directIO by default is set to false. Thanks for the quick response. I dont think this is a bug with the tool. Closing this issue.
