### ISSUE TITLE
FS_cached_4k_random_reads fails on gluster v3.6.1

### ISSUE THREAD

**Issue by kiranfractal** [axboe/fio#33]
Hi, 

I am running fio latest from master branch with below configuration on gluster v3.6.1 CentOS v6.6 and it is failing.

# fio $args --output=4k_caranred_gz.log --section=FS_cached_4k_random_reads  --ioengine=gfapi --volume=vol1 --brick=192.168.1.246  fsmb.fio

fio: failed to lseek pre-read file[0KB/0KB/0KB /s] [0/0/0 iops] [eta 1158050440d:23h:16m:01s]

# fio $args --output=4k_caranredmt_gz.log --section=FS_multi-threaded_cached_4k_random_reads  --ioengine=gfapi --volume=vol1 --brick=192.168.1.246  fsmb.fio

fio: failed to lseek pre-read file[0KB/0KB/0KB /s] [0/0/0 iops] [eta 1158050440d:23h:12m:37s]
fio: failed to lseek pre-read fileone] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 1158050440d:23h:12m:33s]
fio: failed to lseek pre-read fileone] [4KB/0KB/0KB /s] [1/0/0 iops] [eta 1158050440d:23h:12m:32s]
fio: failed to lseek pre-read file
## fsmb.fio configuration file is below:

[global]

[FS_128k_streaming_writes]
name=seqwrite
rw=write
bs=128k
size=5g
# end_fsync=1

loops=1

[FS_cached_4k_random_reads]
name=randread
rw=randread
pre_read=1
norandommap
bs=4k
size=256m
runtime=30
loops=1

[FS_multi-threaded_cached_4k_random_reads]
name=randread
numjobs=4
rw=randread
pre_read=1
norandommap
bs=4k
size=256m/4
runtime=30
loops=1

Thanks.

**Comment by sitsofe** [comment]
@kiranfractal Is this still an issue with the latest version (at the time of writing 2.19) of fio?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
