### ISSUE TITLE
“rate_process=poisson” do not handle IOPS independently for reads and writes

### ISSUE THREAD

**Issue by gvkovai** [axboe/fio#332]
Turns out that “rate_process=poisson” is the culprit in the following example that when read:write mix is not 50:50, the each I/O direction do not look like poisson applied independently causing read:write ratio and #IOPS are not taken into account correctly. 

By commenting out "rate_process=poisson", IOPS are in line with the expectation.

===============================
In the following example, I would like 90 read ops and 10 write ops. Regardless of the values in "bssplit" or "bs" and "rwmixread/rwmixwrite" values, not able to see FIO doing 90:10 read:writes and total ops turns out to be ~20+~20 = ~40 IOPS instead of 100.

Am I missing something here?

Thanks
+GV

=============================================
$ ./fio-2.19 --version (compiled with: ./configure --build-static; make on CentOS release 6.7/3.10.0-229)
fio-2.19

==========================
$ cat output/fio/bssplit_rwmix.fio
[global]
ioengine=libaio
direct=1
time_based
norandommap
group_reporting
disk_util=0
continue_on_error=all
rate_process=poisson

[db-oltp-w]
bssplit=8k/90:16k/10
size=128G
filename=/dev/sdg
rw=randrw
iodepth=8
rwmixread=90
rwmixwrite=10
rate_iops=90,10,0

==========================
$ iostat -x 2 sdg
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.13    0.88    0.00   99.00
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdg               0.00     0.00   17.50   17.50   288.00   312.00    17.14     0.03    0.93    0.31    1.54   0.93   3.25

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.00    0.12    1.00    0.00   98.75
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdg               0.00     0.00   20.00   19.50   352.00   336.00    17.42     0.04    1.03    0.45    1.62   0.92   3.65

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.00    1.00    0.00   99.00
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdg               0.00     0.00   22.00   21.00   400.00   352.00    17.49     0.05    1.12    0.48    1.79   1.06   4.55

==========================
$ sudo ./fio-2.19 --runtime 120 --eta-newline=30 output/fio/bssplit_rwmix.fio
db-oltp-w: (g=0): rw=randrw, bs=(R) 8192B-16.0KiB, (W) 8192B-16.0KiB, (T) 8192B-16.0KiB, ioengine=libaio, iodepth=8
fio-2.19
Starting 1 process
Jobs: 1 (f=1), 0-100 IOPS: [m(1)][26.4%][r=200KiB/s,w=176KiB/s][r=22,w=21 IOPS][eta 01m:29s]
Jobs: 1 (f=1), 0-100 IOPS: [m(1)][51.2%][r=176KiB/s,w=168KiB/s][r=20,w=20 IOPS][eta 00m:59s]
Jobs: 1 (f=1), 0-100 IOPS: [m(1)][76.0%][r=128KiB/s,w=128KiB/s][r=16,w=16 IOPS][eta 00m:29s]
Jobs: 1 (f=1), 0-100 IOPS: [m(1)][100.0%][r=144KiB/s,w=112KiB/s][r=15,w=14 IOPS][eta 00m:00s]
db-oltp-w: (groupid=0, jobs=1): err= 0: pid=1663: Wed Apr  5 16:15:29 2017
   read: IOPS=18, BW=164KiB/s (168kB/s)(19.3MiB/120160msec)
    slat (usec): min=5, max=72, avg=32.59, stdev=10.66
    clat (usec): min=195, max=6884, avg=520.15, stdev=342.01
     lat (usec): min=211, max=6915, avg=552.73, stdev=341.11
    clat percentiles (usec):
     |  1.00th=[  235],  5.00th=[  294], 10.00th=[  342], 20.00th=[  398],
     | 30.00th=[  430], 40.00th=[  454], 50.00th=[  482], 60.00th=[  516],
     | 70.00th=[  548], 80.00th=[  596], 90.00th=[  668], 95.00th=[  756],
     | 99.00th=[  972], 99.50th=[ 3120], 99.90th=[ 5280], 99.95th=[ 6304],
     | 99.99th=[ 6880]
  write: IOPS=18, BW=161KiB/s (165kB/s)(18.9MiB/120160msec)
    slat (usec): min=8, max=101, avg=40.08, stdev= 9.08
    clat (usec): min=817, max=12413, avg=1720.19, stdev=692.15
     lat (usec): min=853, max=12449, avg=1760.27, stdev=692.64
    clat percentiles (usec):
     |  1.00th=[ 1032],  5.00th=[ 1176], 10.00th=[ 1256], 20.00th=[ 1384],
     | 30.00th=[ 1480], 40.00th=[ 1576], 50.00th=[ 1640], 60.00th=[ 1704],
     | 70.00th=[ 1800], 80.00th=[ 1896], 90.00th=[ 2040], 95.00th=[ 2192],
     | 99.00th=[ 5408], 99.50th=[ 6496], 99.90th=[ 8512], 99.95th=[ 9920],
     | 99.99th=[12352]
    lat (usec) : 250=0.86%, 500=26.90%, 750=19.85%, 1000=2.40%
    lat (msec) : 2=43.75%, 4=5.22%, 10=1.00%, 20=0.02%
  cpu          : usr=0.08%, sys=0.17%, ctx=8407, majf=0, minf=34
  IO depths    : 1=91.7%, 2=8.1%, 4=0.1%, 8=0.1%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=2213,2196,0, short=0,0,0, dropped=0,0,0
     errors    : total=0, first_error=0/<Success>
     latency   : target=0, window=0, percentile=100.00%, depth=8

Run status group 0 (all jobs):
   READ: bw=164KiB/s (168kB/s), 164KiB/s-164KiB/s (168kB/s-168kB/s), io=19.3MiB (20.2MB), run=120160-120160msec
  WRITE: bw=161KiB/s (165kB/s), 161KiB/s-161KiB/s (165kB/s-165kB/s), io=18.9MiB (19.8MB), run=120160-120160msec
==========================--

**Comment by axboe** [comment]
Can you try and add [this patch](http://kernel.dk/poisson-indep.patch) and see if it helps?

**Comment by axboe** [comment]
Gah, that missed the last_usec part. How about [this one](http://kernel.dk/poisson-indep-v2.patch)?

**Comment by gvkovai** [comment]
Thanks for the quick turnaround.

With the patch, I get ~180 read ops and ~20 write ops. It's about 2x of what specified "rate_iops=90,10,".

===================
$ cat output/fio/bssplit_rwmix.fio
[global]
ioengine=libaio
direct=1
time_based
norandommap
group_reporting
disk_util=0
continue_on_error=all
rate_process=poisson

[db-oltp-w]
bssplit=8k/90:16k/10
;bs=8k
size=128G
filename=/dev/sdg
rw=randrw
iodepth=8
rwmixread=90
rwmixwrite=10
rate_iops=90,10,

==========

$ sudo ./fio-2.19-dirty --runtime 120 --eta-newline=30 output/fio/bssplit_rwmix.fio
db-oltp-w: (g=0): rw=randrw, bs=(R) 8192B-16.0KiB, (W) 8192B-16.0KiB, (T) 8192B-16.0KiB, ioengine=libaio, iodepth=8
fio-2.19-dirty
Starting 1 process
Jobs: 1 (f=1), 0-100 IOPS: [m(1)][26.4%][r=1376KiB/s,w=168KiB/s][r=161,w=19 IOPS][eta 01m:29s]
^Cbs: 1 (f=1), 0-100 IOPS: [m(1)][47.1%][r=1648KiB/s,w=144KiB/s][r=189,w=17 IOPS][eta 01m:04s]
fio: terminating on signal 2

db-oltp-w: (groupid=0, jobs=1): err= 0: pid=4537: Fri Apr  7 21:50:29 2017
   read: IOPS=178, BW=1574KiB/s (1611kB/s)(87.3MiB/56792msec)
    slat (usec): min=4, max=1246, avg=27.95, stdev=23.62
    clat (usec): min=213, max=123955, avg=2323.13, stdev=3697.93
     lat (usec): min=223, max=123992, avg=2351.08, stdev=3697.48
    clat percentiles (usec):
     |  1.00th=[  572],  5.00th=[ 1080], 10.00th=[ 1144], 20.00th=[ 1224],
     | 30.00th=[ 1288], 40.00th=[ 1384], 50.00th=[ 1656], 60.00th=[ 1976],
     | 70.00th=[ 2192], 80.00th=[ 2896], 90.00th=[ 3760], 95.00th=[ 4512],
     | 99.00th=[11968], 99.50th=[19072], 99.90th=[49408], 99.95th=[63232],
     | 99.99th=[123392]
  write: IOPS=19, BW=168KiB/s (173kB/s)(9568KiB/56792msec)
    slat (usec): min=7, max=205, avg=31.88, stdev=19.16
    clat (usec): min=559, max=53113, avg=971.08, stdev=2319.00
     lat (usec): min=573, max=53135, avg=1002.96, stdev=2318.09
    clat percentiles (usec):
     |  1.00th=[  588],  5.00th=[  620], 10.00th=[  652], 20.00th=[  684],
     | 30.00th=[  716], 40.00th=[  748], 50.00th=[  772], 60.00th=[  804],
     | 70.00th=[  844], 80.00th=[  884], 90.00th=[ 1012], 95.00th=[ 1176],
     | 99.00th=[ 4512], 99.50th=[ 6944], 99.90th=[52992], 99.95th=[52992],
     | 99.99th=[52992]
    lat (usec) : 250=0.02%, 500=0.23%, 750=6.41%, 1000=5.12%
    lat (msec) : 2=53.08%, 4=28.01%, 10=6.02%, 20=0.69%, 50=0.33%
    lat (msec) : 100=0.07%, 250=0.04%
  cpu          : usr=0.41%, sys=0.65%, ctx=18343, majf=0, minf=37
  IO depths    : 1=70.4%, 2=26.9%, 4=1.9%, 8=0.8%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=10134,1084,0, short=0,0,0, dropped=0,0,0
     errors    : total=0, first_error=0/<Success>
     latency   : target=0, window=0, percentile=100.00%, depth=8

Run status group 0 (all jobs):
   READ: bw=1574KiB/s (1611kB/s), 1574KiB/s-1574KiB/s (1611kB/s-1611kB/s), io=87.3MiB (91.6MB), run=56792-56792msec
  WRITE: bw=168KiB/s (173kB/s), 168KiB/s-168KiB/s (173kB/s-173kB/s), io=9568KiB (9798kB), run=56792-56792msec

=================

**Comment by axboe** [comment]
Right, but you opened a separate issue for that. The point here is that it's appropriately split.

**Comment by gvkovai** [comment]
Another issue I came across. Not sure I would need to follow up with a new issue #.

I expected the following combination to yield 90 read ops and 10 write ops. But I did see 200 read ops and 200 write ops (like #333 but rwmixread/rwmixwrite params are ineffective)  . 

rwmixread=90
rwmixwrite=10
rate_iops=100

**Comment by sitsofe** [comment]
@gvkovai The latter issue you describe occurs because what you've written is shorthand for this:

```
rwmixread=90
rwmixwrite=10
rate_iops=100,100,100
```

(see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-blocksize for description of how the value given to [`rate_iops`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-rate-iops) is expanded)

So when you only have one direction (e.g. `rw=read`) by itself you will attempt a max total speed of 100 IOPS. However because you're using something like `rw=randrw `, you're asking for two directions (reads AND writes). Since each direction *independently* has a `rate_iops` of 100 when you have two directions you get a max total of 100 * 2 = 200 IOPS. For example:

```
$ ./fio --ioengine=null --rate_iops=100 --rw=rw --name=go --time_based --runtime=10s --size=100M
go: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-2.18-64-g7071-dirty
Starting 1 process
Jobs: 1 (f=1), 0-200 IOPS: [M(1)][30.0%][r=400KiB/s,w=400KiB/s][r=100,w=100 IOPS][eta 00m:07s]
```

In my example output there was a clue in the status line:
> Jobs: 1 (f=1), **0-200** IOPS: [M(1)][30.0%][r=400KiB/s,w=400KiB/s][**r=100,w=100** IOPS]

**Comment by sitsofe** [comment]
@axboe in your latest patch should the `dprint` output mention the `ddir` too?

```
diff --git a/backend.c b/backend.c
index 38ef3482f851..86e689f838a0 100644
--- a/backend.c
+++ b/backend.c
@@ -811,13 +811,13 @@ static long long usec_for_io(struct thread_data *td, enum fio_ddir ddir)
 		uint64_t val;
 		iops = bps / td->o.bs[ddir];
 		val = (int64_t) (1000000 / iops) *
-				-logf(__rand_0_1(&td->poisson_state));
+				-logf(__rand_0_1(&td->poisson_state[ddir]));
 		if (val) {
 			dprint(FD_RATE, "poisson rate iops=%llu\n",
 					(unsigned long long) 1000000 / val);
```

**Comment by sitsofe** [comment]
@gvkovai If your original request ("rate=poisson doesn't handle read/write rates independently") and your question ("Why does rate_iops=100 deliver 200 IOPS when using rw=randrw") have been fixed/answered could you close this issue?

**Comment by gvkovai** [comment]
This issue is fixed. verified with the patch. Thanks for the quick turnaround.
