### ISSUE TITLE
Question on this command parameters

### ISSUE THREAD

**Issue by samirdesai1000** [axboe/fio#334]
We are getting verification error with this command line. Is there an issue with this?

fio --name=DI_Stress_EMC --ioengine=libaio --direct=1 --rw=randwrite --norandommap --randrepeat=0 --iodepth=8 --size=100% --numjobs=1 --bs=2048k --overwrite=1 --filename=/dev/nvme0n1 --group_reporting --output=DI_Stress_EMC --verify=crc32c-intel --verify_fatal=1 --verify_dump=1 --verify_backlog=32768 --loops=1

**Comment by axboe** [comment]
You can't use norandommap, you'll potentially overwrite blocks. Does it work without that? Also, in the future, remember to include the output from fio in case of errors.

**Comment by sitsofe** [comment]
@axboe I thought fio could keep track of when a block was "damaged" by a later write and skip the earlier verification? I suppose you could get into trouble if two (or more) of the 8 write I/Os you were submitting down simultaneously covered the same LBA range and completed together though (you'd never know who "won")...

**Comment by axboe** [comment]
@sitsofe Right, but that's what norandommap turns off.

**Comment by sitsofe** [comment]
@samirdesai1000 Could you include the output that axboe (and REPORTING-BUGS) was asking for  and does removing norandommap resolve the problem?

**Comment by sitsofe** [comment]
@samirdesai1000 if you build the latest fio from git and use `serialize_overlap=1` (http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-serialize-overlap ) is the problem resolved? If so can you close this issue?
