### ISSUE TITLE
randwrite verify issue

### ISSUE THREAD

**Issue by abner-ma** [axboe/fio#335]
When I use fio to do the random write verify case, sometimes,there was a strange result,it makes me confused.
**I want to know is fio supposed to work with "-bsrange=512-2M -rw=randwrite -verify_backlog=1" very well?**
The fio version used was : fio-2.15
Here is what I do:
 1. "dd if=/dev/zero of=./ebstestX bs=1M count=1024 ",X represents 0-9,I create 10 files,size from 1G to 10G.
2.I use command "losetup" to make this 10 files to be 10 loop device.
3.start a shell script which contains 
`for n in $DISKS
do
        nn=`echo "${n}" | sed "s/\//_/g"`
        id=${n}
        DEVDISK=/dev/loop${n}

        char=`echo "obase=16;${id}"|bc|wc -L`
        bytes=$(((char-1)/2+1))
        idfix=${id}
        while [ $bytes -lt 8 ]; do
                idfix="${idfix}0x00"
                let bytes=$bytes+1
        done
        magicheader="EBSCRC##"
        #build a msg of lenth 256, so format this to 256-8-8-8=232
        info=`printf "%-232s" "Volume: ${n}, id ${id}"`
        # 8bytes magic + 16bytes volid + 16bytes offset + readable info

        fio -ioengine=libaio -direct=1 -iodepth=32 -numjobs=1 -thread -group_reporting -verify=pattern -verify_dump=1 -verify_fatal=1 -size=$SIZE -bsrange=512-2M -rw=randwrite -verify_backlog=1 -filename=${DEVDISK}  -verify_pattern="\"${magicheader}\"${idfix}%o\"${info}\""  -name=$NAME -output=${HOST}_blk${nn}.txt &

done
`
4.One of these was error,i use "od -c " to see the result,it shows:
loop4.1177413120.expected:
0000000   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0000020  \0 346   -   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0000040   4   ,       i   d       4
0000060
*
0000400   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0000420  \0 346   -   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0000440   4   ,       i   d       4
0000460*
0001000   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0001020  \0 346   -   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0001040   4   ,       i   d       4
0001060

loop4.1177413120.received:
0000000   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0000020  \0 236   &   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0000040   4   ,       i   d       4
0000060
*
0000400   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0000420  \0 236   &   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0000440   4   ,       i   d       4
0000460
*
0001000   E   B   S   C   R   C   #   # 004  \0  \0  \0  \0  \0  \0  \0
0001020  \0 346   -   F  \0  \0  \0  \0   V   o   l   u   m   e   :
0001040   4   ,       i   d       4
0001060

Only the offset in previous part is different,so i want to know is fio supposed to work with "-bsrange=512-2M -rw=randwrite -verify_backlog=1" very well in my case?

**Comment by sitsofe** [comment]
Something strange does appear to be going on as I see problems with this over in OSX land:

```
$ rm /tmp/tmp.fio; ~/git/fio/fio --ioengine=posixaio --direct=1 --iodepth=32 --verify=pattern --verify_dump=1 --verify_fatal=1 --size=100M --bsrange=512-4k --rw=randwrite --verify_backlog=1 --filename=tmp.fio --verify_pattern="%o" --name=go 
fio: 1
go: (g=0): rw=randwrite, bs=(R) 512B-4096B, (W) 512B-4096B, (T) 512B-4096B, ioengine=posixaio, iodepth=32
fio-2.18-64-g7071-dirty
Starting 1 process
go: Laying out IO file (1 file / 100MiB)
fio: got pattern '40', wanted '42'. Bad bits 1B/s][r=96,w=113 IOPS][eta 09m:34s]
fio: bad pattern block offset 1
pattern: verify failed at file tmp.fio offset 56771072, length 0
       received data dumped as tmp.fio.56771072.received
       expected data dumped as tmp.fio.56771072.expected
fio: verify type mismatch (866 media, 18 given)
fio: pid=67720, err=92/file:io_u.c:1982, func=io_u_queued_complete, error=Illegal byte sequence
fio(67720,0x7fff7a33d310) malloc: *** error for object 0x7ff6426034c0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
fio: pid=67720, got signal=6][r=125KiB/s,w=95KiB/s][r=74,w=59 IOPS][eta 00m:00s]

go: (groupid=0, jobs=1): err=92 (file:io_u.c:1982, func=io_u_queued_complete, error=Illegal byte sequence): pid=67720: Sun Apr  9 15:39:04 2017
  write: IOPS=105, BW=186KiB/s (190kB/s)(668KiB/3591msec)
    slat (usec): min=0, max=91, avg= 3.66, stdev= 6.36
    clat (usec): min=456, max=212714, avg=65392.73, stdev=46007.86
     lat (usec): min=457, max=212716, avg=65396.40, stdev=46007.13
    clat percentiles (usec):
     |  1.00th=[  516],  5.00th=[ 1004], 10.00th=[ 1768], 20.00th=[24448],
     | 30.00th=[37632], 40.00th=[43776], 50.00th=[60160], 60.00th=[74240],
     | 70.00th=[89600], 80.00th=[101888], 90.00th=[125440], 95.00th=[152576],
     | 99.00th=[189440], 99.50th=[203776], 99.90th=[211968], 99.95th=[211968],
     | 99.99th=[211968]
    lat (usec) : 500=0.14%, 750=1.93%, 1000=0.97%
    lat (msec) : 2=4.28%, 4=0.14%, 10=0.83%, 20=4.14%, 50=21.13%
    lat (msec) : 100=33.43%, 250=32.60%
  cpu          : usr=0.42%, sys=0.56%, ctx=608, majf=0, minf=61
  IO depths    : 1=0.1%, 2=0.3%, 4=0.6%, 8=47.4%, 16=51.7%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=98.4%, 8=1.6%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=345,379,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
  WRITE: bw=186KiB/s (190kB/s), 186KiB/s-186KiB/s (190kB/s-190kB/s), io=668KiB (684kB), run=3591-3591msec
```

**Comment by sitsofe** [comment]
A little bit more poking and added debugging has turned up the following:
```
$ grep -C 5 '56771072\|56770560' debug
io       31735 fill_io_u: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e800)=0
io       31735 queue: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 10
io       31735 get_next_block: p=0x7f34c401e540 offset=56771072
io       31735 fill_io_u: io_u 0x7f34c401e500: off=56771072/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401e500: off=56771072/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e500)=0
io       31735 queue: io_u 0x7f34c401e500: off=56771072/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 11
io       31735 get_next_block: p=0x7f34c401e280 offset=24595968
io       31735 fill_io_u: io_u 0x7f34c401e240: off=24595968/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401e240: off=24595968/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e240)=0
--
io       31735 fill_io_u: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401dc80)=0
io       31735 queue: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 14
io       31735 get_next_block: p=0x7f34c401d9c0 offset=56770560
io       31735 fill_io_u: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401d980)=0
io       31735 queue: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=1io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 15
io       31735 get_next_block: p=0x7f34c401d700 offset=17328128
io       31735 fill_io_u: io_u 0x7f34c401d6c0: off=17328128/len=2560/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401d6c0: off=17328128/len=2560/ddir=1io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401d6c0)=0
--
io       31735 io complete: io_u 0x7f34c401cb40: off=4692992/len=2560/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401ce00: off=96440832/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401d100: off=68902912/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401d3c0: off=18680320/len=1536/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401d6c0: off=17328128/len=2560/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401df40: off=98221568/len=3072/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401e240: off=24595968/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401e500: off=56771072/len=512/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401eac0: off=41968640/len=1536/ddir=1io       31735 /tmp.fioio       31735 
io       31735 io complete: io_u 0x7f34c401edc0: off=49715712/len=3072/ddir=1io       31735 /tmp.fioio       31735 
io       31735 prep: io_u 0x7f34c401edc0: off=49715712/len=3072/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401edc0)=0
--
io       31735 calling ->commit(), depth 9
io       31735 prep: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e800)=0
io       31735 queue: io_u 0x7f34c401e800: off=77857280/len=3584/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 10
io       31735 prep: io_u 0x7f34c401e500: off=56771072/len=512/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e500)=0
io       31735 queue: io_u 0x7f34c401e500: off=56771072/len=512/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 11
io       31735 prep: io_u 0x7f34c401e240: off=24595968/len=3584/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401e240)=0
io       31735 queue: io_u 0x7f34c401e240: off=24595968/len=3584/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 12
--
io       31735 calling ->commit(), depth 13
io       31735 prep: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401dc80)=0
io       31735 queue: io_u 0x7f34c401dc80: off=98162176/len=512/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 14
io       31735 prep: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401d980)=0
io       31735 queue: io_u 0x7f34c401d980: off=56770560/len=1024/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 15
io       31735 prep: io_u 0x7f34c401d6c0: off=17328128/len=2560/ddir=0io       31735 /tmp.fioio       31735 
io       31735 ->prep(0x7f34c401d6c0)=0
io       31735 queue: io_u 0x7f34c401d6c0: off=17328128/len=2560/ddir=0io       31735 /tmp.fioio       31735 
io       31735 calling ->commit(), depth 16
--
```

So it looks like a 512 byte write is done but then is destroyed by an overlapping 1024 byte write which was 512 bytes earlier only for an attempt to be made to verify the original 512 byte block.

**Comment by abner-ma** [comment]
@sitsofe Thank you for your answer.
Does that mean I'd better not to use fio with  "-bsrange=512-2M -rw=randwrite -verify_backlog=1"?

**Comment by sitsofe** [comment]
@abner-ma I think you've hit unexpected behaviour so until it is fixed I'd avoid using those options together. Perhaps using `bsrange` with any sort of verification needs one or more of the following:
* Avoid generation overlapping writes in the same pass (unless you are using `norandommap` etc).
* Remember the latter write damages the earlier write and avoid verifying the earlier write.
* Put up a warning that verification may fail because of random write I/O + `bsrange`.

**Comment by sitsofe** [comment]
@abner-ma Can you see if adding `serialize_overlap=1` after building the serialize_overlap branch from  https://github.com/sitsofe/fio/commits/serialize_overlap resolves the problem you are seeing?

**Comment by abner-ma** [comment]
@sitsofe Thank you for your help.I had try several times,and do not see it again when I use fio to randwrite on loop device.
But I still see the problem when I use the device which is provided by a software(like ceph and is developed by our organization).Thus I want to know,whether write slowly(I had test many times,it takes less time to write in loop device.When I  run 10 fio to randwrite at a time,5 or 6 will be verify error,not all of them) or any other reason can cause this.Can you help me to analyze what is the reason,besides our organuzation's software has bug?

**Comment by sitsofe** [comment]
I think I've found the problem. Can you try setting overwrite=1 and seeing if you still see the problem?

**Comment by sitsofe** [comment]
@axboe do you know why we check for !overwrite over in https://github.com/axboe/fio/blob/9bae252254d0ce37a144cb4c8d2cb4222d539a9e/iolog.c#L242:

```c
	if (((!td->o.verifysort) || !td_random(td) || !td->o.overwrite) &&
	      (file_randommap(td, ipo->file) || td->o.verify == VERIFY_NONE)) {
		INIT_FLIST_HEAD(&ipo->list);
		flist_add_tail(&ipo->list, &td->io_hist_list);
		ipo->flags |= IP_F_ONLIST;
		td->io_hist_len++;
		return;
	}
```

I know there's a comment saying "Random writes that lay out the file as it goes along" but are you saying that said random writes are going be faster because they are actually sequentially next to each other from a layout perspective?

**Comment by abner-ma** [comment]
@sitsofe Thank you ,I don't see the problem now.
