### ISSUE TITLE
fio 'write_iops_log' creates file with wrong axis parameters

### ISSUE THREAD

**Issue by dthpulse** [axboe/fio#337]
fio 'write_iops_log' creates file with wrong axis parameters so graphs created for example by plot  are useless. Bellow I added examples from old fio version (fio-2.8-1.34.x86_64) where it works and new fio version (fio-2.13-2.26.x86_64) where it is wrong.
Command used:

`/usr/bin/fio --ioengine=rbd --clientname=admin --pool=cbt-librbdfio --rbdname=cbt-librbdfio-`hostname -s`-0 --invalidate=0 --rw=randwrite --runtime=300 --ramp_time=None --numjobs=1 --direct=1 --bs=1048576B --iodepth=64 --end_fsync=0 --write_iops_log=/tmp/cbt/00000000/LibrbdFio/osd_ra-00004096/op_size-01048576/concurrent_procs-004/iodepth-064/randwrite/output.0 --write_bw_log=/tmp/cbt/00000000/LibrbdFio/osd_ra-00004096/op_size-01048576/concurrent_procs-004/iodepth-064/randwrite/output.0 --write_lat_log=/tmp/cbt/00000000/LibrbdFio/osd_ra-00004096/op_size-01048576/concurrent_procs-004/iodepth-064/randwrite/output.0 --name=librbdfio-`hostname -s`-0  > /tmp/cbt/00000000/LibrbdFio/osd_ra-00004096/op_size-01048576/concurrent_procs-004/iodepth-064/randwrite/output.0`

**fio-2.8-1.34.x86_64:**

> 622, 1, 0, 1048576
1374, 130, 0, 1048576
2132, 149, 0, 1048576
2800, 62, 0, 1048576
3328, 121, 0, 1048576
4056, 163, 0, 1048576
4606, 152, 0, 1048576
5173, 137, 0, 1048576
5900, 105, 0, 1048576
6704, 106, 0, 1048576
7628, 173, 0, 1048576
8402, 120, 0, 1048576
8951, 94, 0, 1048576
9656, 163, 0, 1048576
11116, 56, 0, 1048576
11769, 174, 0, 1048576
12457, 132, 0, 1048576
13151, 129, 0, 1048576
13943, 125, 0, 1048576
14516, 171, 0, 1048576
15041, 66, 0, 1048576
15853, 136, 0, 1048576
16606, 147, 0, 1048576
17493, 136, 0, 1048576
18189, 135, 0, 1048576
18750, 160, 0, 1048576
19527, 114, 0, 1048576
20058, 92, 0, 1048576
20814, 140, 0, 1048576
21332, 71, 0, 1048576
21837, 186, 0, 1048576
22678, 105, 0, 1048576
23453, 134, 0, 1048576

**fio-2.13-2.26.x86_64:**

> 399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576
399, 1, 0, 1048576

**Comment by sitsofe** [comment]
@dthpulse I'm afraid I don't completely follow this issue. Here's how I'm interpreting what you're saying:

fio-2.8 by default outputs the following in the write_iops_log log:
```
time (which increases by around 500ms each time), iops (which was typically greater than 1), data direction (0 = read), offset
```

fio-2.13 by default outputs the following in the write_iops_log log:
```
time (which does not necessarily increase at all), iops (which is always 1), data direction (0 = read), offset
```
In the 2.13 case it looks like IOs are collected together then averaged over some period - is this correct? In the second case it looks like you are getting per I/O information (hence IOPS would always be one you can have multiple results in the same millisecond etc).

The problems are the following:
- The 2.13 information is difficult/impossible to plot. My question here is what is the plot supposed to show (both along the x-axis and up the y-axis)?
- You desire the 2.8 like behaviour.

Is this a correct interpretation of your request? If so does setting [`log_avg_msec`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-avg-msec) appropriately (e.g. to 500ms) help?

**Comment by sitsofe** [comment]
(PS: ramp_time is actually an integer with a suffix so 0 is probably a better value to use at this point)

**Comment by sitsofe** [comment]
Closer inspection shows that the change in behaviour is actually alluded to in the documentation for [`iopsavgtime`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-iopsavgtime) (note that `log_avg_msec` defaults to 0):

> If the job also does IOPS logging through write_iops_log, then the minimum of this option and log_avg_msec will be used

**Comment by dthpulse** [comment]
So my understanding is that iopsavgtime default value is 500ms. If it is its default value, do I need to specify it anyway?

**Comment by dthpulse** [comment]
OK, so my understanding is tha in new fio version I have to specify parameter log_avg_msec to create desired results. Is it right?

**Comment by sitsofe** [comment]
That's my recommendation - can you post back if that has the desired effect?

**Comment by dthpulse** [comment]
Yes, the result is as expected now.
THX

**Comment by sitsofe** [comment]
@dthpulse Excellent! Since the problem was down to a change in default behaviour (I'm guessing the change was introduced in 2.10) which is reversible, could you close this issue?
