### ISSUE TITLE
Not meeting "rate_iops_min" does not cause job to exit

### ISSUE THREAD

**Issue by chunghenry** [axboe/fio#340]
Per manual definition, it states:
.. option:: rate_iops_min=int[,int][,int]

	**If fio doesn't meet this rate of I/O, it will cause the job to exit.**
	Comma-separated values may be specified for reads, writes, and trims as
	described in :option:`blocksize`.

However, in my case, it only states "_min iops rate ... not met, got ..._" and it continues the job. Is there any parameter that I'm missing? Or is this a bug?

Thanks in advance.

**Comment by axboe** [comment]
Please include your full job file or command line, and the output. It's hard to guess what is going on without all the info. Just checked -tip here:

./fio --name=sdc --filename=/dev/sdc --rw=randread --direct=1 --bs=4k --rate_iops_min=100
sdc: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-2.19-13-gd7658
Starting 1 process
sdc: rate_iops_min=100 not met, got 75 IOPS00KiB/s,w=0KiB/s][r=75,w=0 IOPS][eta 327d:16h:21m:27s]
fio: pid=38320, err=5/file:backend.c:1015, func=check_min_rate, error=Input/output error

sdc: (groupid=0, jobs=1): err= 5 (file:backend.c:1015, func=check_min_rate, error=Input/output err

and it seems to work fine for me, it exits when we fail to meet the 100 iops asked for.

**Comment by axboe** [comment]
Maybe you are running more than one job and need to set **exitall** to ensure that all jobs exit?

**Comment by chunghenry** [comment]
The commandline is the following:

fo --name =4k_RW --rw=ranwrite --bs=4k --ioengine=libaio --iodepth=256 --direct=1 --filename/dev/nvme0n1 --norandommap --ranrepeat=0 --rate_iops=3750 --rate_iops_min=3600 --numjobs=32 --group_reporting --runtime=60 --output=4k_RW.txt

I tried adding --exitall and it gave the same message. 

Using fio 2.2.8 for Centos 7.2

**Comment by axboe** [comment]
Please don't file bug reports against fio versions that are two years old. Reproduce with the latest version first, which is 2.19 right now. Reopen this bug if the problem persists there.

**Comment by chunghenry** [comment]
I'll double check with the latest and if it occurs again, I'll file another bug. Thanks Jens!

**Comment by chunghenry** [comment]
Just double checked with newer fio and it works like a charm. Sorry for the inconvenience earlier. Thanks!
