### ISSUE TITLE
Verification errors when using percentage_random=x and rw=randwrite

### ISSUE THREAD

**Issue by natachu** [axboe/fio#344]
Hi,

With both fio version 2.2.8 and the latest version (2.19) I get header verification errors when using the --percentage_random parameter.  

I was trying against a block device I was testing, and then finally just made a text file to run against and got the same error at the same offset as the block device, so I believe it is an fio problem, not a problem with my block device.  The error is:

verify: bad header numberio 49126, wanted 42 at file test2.txt offset 418398208, length 4096
       hdr_fail data dumped as test2.txt.418398208.hdr_fail

With 2.19, I created a test2.txt file of size 565182464 bytes, and then running these parameters from the command line:

sudo fio -name=cmdline-job --buffered=0 --filename=test2.txt --readwrite=randwrite --blocksize=4096 --percentage_random=1 --size=565182464 --iodepth=1 --verify=crc32c-intel --verify_fatal=1 --verify_dump=1

I get a numberio verification failure if I use any percentage_random except 0 or 100, and I don't get it if I use --verify_backlog=1, so my guess is that when using the percentage_random feature, fio performs some overwrite of a block but doesn't take that into account when moving to the verify stage.  Does that sound plausible?

**Comment by sitsofe** [comment]
Do you still see the problem if you set `--overwrite=1` ?

**Comment by natachu** [comment]
No, the problem goes away if I set --overwrite=1.  Documentation says this option "setup the file first", what does that mean?  Does it write the whole file sequentially first, then do the random write?

**Comment by sitsofe** [comment]
Overwrite is described over on http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-overwrite . The actual problem stems from around https://github.com/axboe/fio/blob/master/iolog.c#L228 and you can see even though a job is random if overwrite is 0 then you skip the verify sort work which and because it's not done you can end up with this issue (because nothing will check for overlaps).

You're basically seeing a varient of https://github.com/axboe/fio/issues/335 . I made a fix for that issue (https://github.com/sitsofe/fio/commit/ddc475a0ed482717c3b39f579dbdea532c5833c0 ) but it won't cover this case so I'm wondering if the overwrite detection in that code is worthwhile...

**Comment by natachu** [comment]
Ok.  I can run with overwrite=1, since I am testing against a block device it looks like it does not do anything before starting the test.  Thanks for the tip, I wonder if it would be worth it to make the sort happen when using the percentage_random feature, but I'm unblocked now.

**Comment by sitsofe** [comment]
@natachu Re always sort on `percentage_random` - that's a fair point. The problem I'm having is that there seem to be a growing number of  "enabling option X results in random write I/O performing overlaps" which are being mishandled.

An entirely unrelated question: has your company recently started using fio for verification tests? I've noticed a recent influx of problems found by new GitHub users being reported related to it and I'm just curious if you're all different engineers finding different problems but working for the same umbrella organisation :-)

@axboe Is the ` || !td->o.overwrite` optimisation worth the pain of having to create exceptions for all these options that can create overlaps and if so, is code like:

```
 -	if (((!td->o.verifysort) || !td_random(td) || !td->o.overwrite) &&
 -	      (file_randommap(td, ipo->file) || td->o.verify == VERIFY_NONE)) {
 +	if (((!td->o.verifysort) || !td_random(td) || (!td->o.overwrite &&
 +	     td->o.min_bs[io_u->ddir] == td->o.max_bs[io_u->ddir])) &&
 +	    (file_randommap(td, ipo->file) || td->o.verify == VERIFY_NONE)) {
```

the correct way of addressing them?

**Comment by natachu** [comment]
@sitsofe Yes, we started using fio recently at my company, I think in the last month or two, but afaik I'm the only one from my company that has asked a question on github.   We appreciate the tool and your support.

**Comment by sitsofe** [comment]
@natachu if you pull the latest git fio (which has https://github.com/axboe/fio/commit/8d4564e9884cbc6082b798cd828eb43da1bb35ff inside) this should be fixed. Can you close this issue this resolves the issue or comment again if it is a problem after that fix? Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
