### ISSUE TITLE
Compiling for Android using ndk-r15

### ISSUE THREAD

**Issue by omor1** [axboe/fio#346]
#### Description
ndk-r15 has a change in the libc header `<sys/ipc.h>` that adds the following (see [commit](https://android.googlesource.com/platform/bionic/+/a29821bb455e6c23b2c9fe13bf1436610c4eb412%5E%21/#F0)):
```C
#if defined(__USE_GNU)
#define __key key
#define __seq seq
#endif
```

This interferes with the definition of shmget in os-android.h:
```C
static inline int shmget (key_t __key, size_t __size, int __shmflg)
{
    int fd,ret;
    char key[11];

    /* code */
}
```
resulting in a compile error: `./os/os-android.h:87:7: error: redefinition of 'key' with a different type: 'char [11]' vs 'key_t' (aka 'int')`

A solution is to rename `key` to `keybuf` or something similar.

#### Environment
Targeting Android API level 21 for arm-linux-androideabi with a standalone toolchain from ndk-r14 with a patched `<sys/ipc.h>` (backported from  ndk-r15), using clang
fio version 2.19 (latest)
Note that I later found that I need to target Android API level 23 at a minimum so that `posix_madvise()` is available.

#### Reproduction
Compile for Android using ndk-r15 or higher (or at least a patched `<sys/ipc.h>`)

**Comment by sitsofe** [comment]
@omor1 your suggestion looks sensible - would you like to submit it as a pull request?

**Comment by omor1** [comment]
@sitsofe sure, I can do that. Is there a particular name that would be best to use? I'm currently using `keybuf`, but I don't know if you want to keep that.

There's another Android compilation bug I found, but I'll open a separate issue (and pull request) for that. It might require more discussion as I'm not sure if it's a problem with unified headers or not.

**Comment by sitsofe** [comment]
@omor1 I'd say `keybuf` is good - it's the shmget `key` being used but when `ashmem` is usually called in that context in the source of other programs the variable is typically called `buf` so: `key + buf = keybuf`.
