### ISSUE TITLE
fio_swapN on Android

### ISSUE THREAD

**Issue by omor1** [axboe/fio#348]
#### Description
`os/os-android.h` defines `fio_swapN` as `__bswap_N` (where `N` is 16, 32 or 64). However, there is no such function defined in the Android libc. There _is_ `bswap_N` (sans double underscore) defined in `<byteswap.h>`. This naturally causes compilation to fail, as it can't link properly.

`os/os-android.h` includes `<asm/byteorder.h>`, which in turn includes `<linux/byteorder/little_endian.h>` (at least for arm). This does define various byte swapping facilities, but does _not_ define `__bswap_N`. I wonder whether it used to define such functions, but at some point (perhaps with the change to unified headers) it removed them. Is the header being included for some other purpose, or can it be safely removed from the list of `#include`s?

#### Environment
Targeting Android API level 23 for arm-linux-androideabi with a standalone toolchain from ndk-r14, using clang, trying to compile fio 2.19.

#### Reproduction
Compile for Android using clang with unified headers.

#### Possible Solution

`os/os-linux.h` uses `__builtin_bswapN` if it's available, else it uses `__bswap_N`, which _is_ defined in glibc (but technically it is also supposed to be used as `bswap_N`, as per the `#define`s in the glibc `<byteswap.h>`).

`__builtin_bswapN` should be available for Android as well as a compiler intrinsic (I believe that clang implements most of the GCC builtins), so similar logic could be used in `os/os-android.h`, preferring the compiler builtin and dropping to the libc function if it's not available.

`__bswap_N` in `os/os-linux.h` should probably be changed to `bswap_N` as well (though the functions aren't usually used, as the builtins should be selected instead).

**Comment by sitsofe** [comment]
@omor1 Here's the approach boost take: https://github.com/boostorg/endian/blob/boost-1.64.0/include/boost/endian/detail/intrinsic.hpp#L32 (no mention of __bswap_N there).

Mentioning @xaaronc for comment on fio's `#include <asm/byteorder.h>` in `os/os-android.h` .

**Comment by sitsofe** [comment]
I have to admit I'm a bit suspicious of using #defined to check for intrinsics. I thought the inability to detect intrinsics was why clang invented the non-portable `__has_builtin` - https://clang.llvm.org/docs/LanguageExtensions.html#feature-checking-macros ...

**Comment by omor1** [comment]
@sitsofe I hadn't realized that the `os/os-linux.h` code was doing that—that definitely looks wrong, and most likely always returns false (so it actually _does_ use `__bswap_N`).

We could go the really thorough route (à la boost), or care a bit less and assume GCC implements the builtins correctly (GCC 4.3 was released in 2008, nearly 10 years ago, while GCC 4.8 was released 4 years ago). A decently modern version of GCC will work right.

**Comment by sitsofe** [comment]
@omor1 I'd be sorely tempted to just document somewhere that fio only compiles with non-ancient compilers on at least Linux-based platforms out of fear that everything will degenerate to `#ifdefs` all over, but Jens may feel otherwise. I think there are other platforms that stuck with old GCCs (OpenBSD still ships GCC 4.2 in it's base I think) but that's an aside and if such platforms care about fio they could carry a patch set of their own...

**Comment by omor1** [comment]
@sitsofe it looks like OpenBSD _does_ ship the ancient version of GCC (last under GPLv2), but it also ships a modern version LLVM/Clang, so I think it should be fine. Caring about ancient and non-standard platforms too much truly becomes a hassle (see: autotools checking everything under the sun because there was a version of some system 20 years ago that had a broken header).

**Comment by omor1** [comment]
`<asm/byteorder.h>` is necessary because `__cpu_to_le32()`, `__cpu_to_le64()`, `__le32_to_cpu()`, and `__le64_to_cpu()` are used in `cconv.c`.
