### ISSUE TITLE
Android and shared memory

### ISSUE THREAD

**Issue by omor1** [axboe/fio#352]
#### Description
`os/os-android.h` currently does not import `<sys/shm.h>`, which _does_ however exist in recent versions of the ndk/Bionic.

Without compiling with `--disable-shm`, there is a compile error: libc does not provide `struct shmid_ds`, but rather `struct shmid64_ds` and simply has `#define shmid_ds shmid64_ds` in `<sys/shm.h>`. Thus the header is in fact necessary to use shared memory facilities (though standard `shmat()`, `shmctl()`, `shmdt()`, and `shmget()` are still not provided).

#### Environment
Targeting Android API level 23 for arm-linux-androideabi with a standalone toolchain with unified headers from ndk-r14, using Clang, compiling fio git master (and 2.19).

#### Reproduction
Compile for Android using ndk-r14 using unified headers (may work with older versions of the NDK).

#### Solution
The entire POSIX shared memory compatibility section in `os/os-android.h` should be surrounded with `#ifndef CONFIG_NO_SHM` and also have `#include <sys/shm.h>` instead of `<linux/shm.h>` (or in addition to, but the former `#include`s the latter).
I'll submit a pull.

**Comment by enh** [comment]
that's not quite right. to build with NDK r14/r15 with unified headers targeting API level 26 or above, you need something more like this:

```
--- /tmp/fio-2.20/os/os-android.h	2017-05-19 07:25:27.000000000 -0700
+++ os/os-android.h	2017-05-19 18:52:04.447953599 -0700
@@ -63,7 +63,18 @@
  * necessary stuff here.
  */
 
+#if __ANDROID_API__ >= 26
+#define shmat bionic_shmat
+#define shmctl bionic_shmctl
+#define shmdt bionic_shmdt
+#define shmget bionic_shmget
+#endif
 #include <sys/shm.h>
+#undef shmat
+#undef shmctl
+#undef shmdt
+#undef shmget
+
 #define SHM_HUGETLB    04000
 
 #include <stdio.h>
```

otherwise you'll hit errors about the static redefinitions of shm* conflicting with the non-static declarations in sys/shm.h...

**Comment by enh** [comment]
(if you're thinking it's a wee bit early for any sane person to be targeting O or above, https://android-review.googlesource.com/400614 is me upgrading AOSP's copy of fio to 2.20 :-) )

**Comment by omor1** [comment]
@enh I'm currently using NDK-r14 and deploying on a Nexus 5 (targeting API level 23), so I haven't been able to look at the changes in Android O/API level 26. I'll be testing out r15 beta 2 soon—I want to see if it (magically) fixes #356, which is currently a showstopper for me. I'll see about Android O at the same time—it seems like it (finally) implements POSIX shared memory?

Since you seem familiar with using fio on Android, would you have any input on what's going on with #356?

**Comment by enh** [comment]
you won't be happy with the <sys/shm.h> implementation in O: SELinux will prevent you from successfully using any of it. (and Android common kernels have all the SYSV IPC stuff compiled out anyway.) it's really only useful to folks using bionic on non-Android (such as the host or -- more usually -- during early bringup). that's the point of this patch: move aside the "real" SYSV IPC that will fail at runtime so you can still use your "workaround" ashmem-based code.

**Comment by omor1** [comment]
The only reason we really need `<sys/shm.h>` is for the `shmid_ds` definition, since the kernel headers use `shmid64_ds`. Does it make more sense to just define it ourselves? Most of what we need is in `<linux/shm.h>`.
