### ISSUE TITLE
buffer_pattern won't work without setting iodepth

### ISSUE THREAD

**Issue by panxiao2014** [axboe/fio#355]
FIO: fio-2.19-51-gd418
OS: Red Hat Enterprise Linux Server release 7.2 (Maipo)

Running IO on attached stroage LUNs.  First running by using following setting:
ioengine=libaio
direct=1
time_based
runtime=240h
readwrite=readwrite
bs=4k
size=100g
buffer_pattern=0xbeef

By examing output from storage, the buffer pattern did not take effect. And then adding the following parameter:
iodepth=2

Then it worked fine. By doing some test we found that buffer_pattern only take effect when setting iodepth parameter in profile.

**Comment by sitsofe** [comment]
I can't reproduce the problem here with
```
$ ./fio --name=issue355 --ioengine=libaio --direct=1 --rw=readwrite --bs=4k --size=100M --buffer_pattern=0xbeef --filename=/tmp/tmp.fio
[...]
$ hexdump -C /tmp/tmp.fio -n 16K
00000000  be ef be ef be ef be ef  be ef be ef be ef be ef  |................|
00000010
```

However your job is readwrite so 50% of your I/Os are going to be reads? If so wouldn't you expect some areas of the file not to have the 0xbeef pattern in them?

**Comment by sitsofe** [comment]
I take that back. Something strange does appear to be happening with `--rw=readwrite` (as opposed to `--rw=write`) when the file is already laid out...

**Comment by axboe** [comment]
I think it's because you don't have refill_buffers=1 set. When you have mixed read and write, and the file is initially zero filled, your buffers will be cleared for the read. So even if we initially set the write pattern, once we've done a read, it'll be zeroed.

We should probably just force refill_buffers on in case that a pattern has been set.

**Comment by axboe** [comment]
In other words, this has nothing to do with the depth. It just so happens to change the symptoms, since now we have more buffers to read into.

**Comment by axboe** [comment]
Try current git, I added this patch:

http://git.kernel.dk/cgit/fio/commit/?id=c55fae03f7d5c0981e55241fc9003d762f7a5fd9

**Comment by panxiao2014** [comment]
Thanks! It works fine now.
