### ISSUE TITLE
Interrupting a benchmark with mount discard causes the file system to hang

### ISSUE THREAD

**Issue by roman-io** [axboe/fio#361]
How to reproduce the issue:
An AWS i3 instance with NVMe SSD, Ubuntu 14.04 or 16.04
Format the SSD with ext4 or xfs filesystem
`mount -o discard /dev/nvme0n1 /media/disk1`
`fio --name fio_test_file --direct=1 --rw=randwrite --bs=4k --size=5G --numjobs=8  --group_reporting`
Interrupt with `Ctrl+C`
Try to remove test files with `rm -rf fio_test_file.*`
Filesystem hangs forever, error in dmseg `task rm:2301 blocked for more than 120 seconds.`

The same setup with nodiscard - works fine:
`mount -o nodiscard /dev/nvme0n1 /media/disk1`

**Comment by axboe** [comment]
If the kernel hangs, then that's a kernel bug. You should report that issue to your distribution vendor, or through other appropriate channels. This isn't a fio issue.
