### ISSUE TITLE
output JSON file deviates from JSON  specifications

### ISSUE THREAD

**Issue by YukiKita** [axboe/fio#364]
If _fio_ accesses files which have long names, the ending double quote of _filename_ value in the output JSON file disappears. 

command
` fio -name=test -rw=read -bs=4k -filename=test_files/111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111.txt:test_files/222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222.txt:test_files/333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333.txt:test_files/444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444.txt:test_files/555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555.txt --output-format=json`
=>
part of ouptut JSON file 
`    {
      "jobname" : "test",
      "groupid" : 0,
      "error" : 0,
      "eta" : 0,
      "elapsed" : 3,
      "job options" : {
        "name" : "test",
        "rw" : "read",
        "bs" : "4k",
        "filename" : "test_files/111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111.txt:test_files/222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222.txt:test_files/333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333.txt:test_files/444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444.txt:test_files/55555555555555555555555555555555555
      },
`

**Comment by axboe** [comment]
Your original fix meant that we would crash fio running in client/server mode, see this issue:

https://github.com/axboe/fio/issues/375

I took a look at this, and reverted your fix. The real issue here is that the logging functions didn't handle > 1024 byte output correctly. See the fix I committed for that here:

http://git.kernel.dk/cgit/fio/commit/?id=7d64aa48fcfc03a93ea1623338a760e66406b132
