### ISSUE TITLE
Wrong data corruption error report on NVMe drive ? (verify: bad magic header)

### ISSUE THREAD

**Issue by Awele** [axboe/fio#366]
Error Message:
> verify: bad magic header 5487, wanted acca at file /dev/nvme0n1 offset 40129331200, length 32768
> hdr_fail data dumped as nvme0n1.40129331200.hdr_fail

Dump of the data read: (does not match the 0xacca magic header)
```
$ hexdump nvme0n1.40129331200.hdr_fail | head
0000000 5487 b241 11b2 0eb1 aa90 ac04 c915 12ed
0000010 9552 6038 e320 03c2 12aa c15e 2c47 17a6
0000020 ....
```

Dump of the data read after the error occured: (match expected 0xacca magic header)
```
$ sudo nvme read /dev/nvme0n1 -s 0x04ABF280 -z 32768 -d read_0x04ABF280.bin
$ hexdump read_0x04ABF280.bin | head
0000000 acca 0002 8000 0000 2f54 7db2 724e 0b78
0000010 0000 bf28 004a 0000 0c25 0000 2c1e 000e
0000020 ....
```

Command history order:
* Assumption: LBA 0x04abf280 (data magic header: 0x5487)
* Write command submission on 0x04abf280 (data magic header 0xacca)
* Read command submission on 0x04abf280
* Write completion on 0x04abf280
* Read completion on 0x04abf280 which return data magic number 0x5487
* Reread  0x04abf280 which return data 0xacca

NVMe 1.2a specification
> 6.3 Command Ordering Requirements
> (snip)
> Specifically, the controller is not responsible for checking the LBA of a Read or Write command to ensure any type of ordering between commands. **For example, if a Read is submitted for LBA x and there is a Write also submitted for LBA x, there is no guarantee of the order of completion for those commands (the Read may finish first or the Write may finish first)**. If there are ordering requirements between these commands, host software or the associated application is required to enforce that ordering above the level of the controller.

Which mean that in our previous scenario, read command can return either 0x5487 and 0xacca

Detail of failure where the above problem have been noticed:
* Fio version: fio-2.16-1-g3ab9 (Windows 10) / 2.9 (Fedora) / 2.16 (CentoOS)
* Fio command used for the linux test:
  * `fio sample.fio --runtime=172800 --verify_dump=1`
  * sample.fio
```
[job0]
size=100%
filename=/dev/nvme0n1
time_based=1
description=Random IO
iodepth=16
bs=32k
rw=randrw:2
rwmixread=53
random_distribution=random:7
loops=1
thread=1
direct=1
ioengine=libaio
random_generator=tausworthe
lockfile=readwrite
verify=md5
do_verify=1
verify_fatal=1
verify_backlog=1
invalidate=0
loops=1
```

Question:
Does FIO respect NVMe command ordering specification ? If it does not, this should be fixed since the verify option can not be safely when do_verify is set to 1.

**Comment by sitsofe** [comment]
The fio libiscsi engine isn't going to have any awareness of whether your I/O ultimately goes to an NVMe device, a SCSI RAID device, a SATA device etc. - it just talks to (appropriate) Linux devices and that information is abstracted by the kernel. Having said that 

There are two potential things that may help:
* Working around overlap detection not being on in some circumstances. If setting `overwrite=1` makes your problem go away you're seeing https://github.com/axboe/fio/issues/344 / https://github.com/axboe/fio/issues/345 .
* If setting `iodepth=1` makes it go away you're likely seeing the "device may reorder in-flight I/Os" problem (you can start using `--debug=all` and checking the output manually to try and prove this). It's not just NVMe device that do can have this behaviour but nor is it the case that ALL devices behave this way. Beyond setting iodepth to 1 you might be able to work around this issue by building an fio with the patch from https://github.com/axboe/fio/pull/343 and using the `serialize_overlap` option.

**Comment by sitsofe** [comment]
@Awele Do either of the above two suggestions change the result you're seeing?

**Comment by Awele** [comment]
Sorry for the late answer but I do not work during the week-end.
Let me resume what I understood of from your post and plesae check if my interpretation is correct.

###  Point1
Just for clarification, to answer the original question in this issue:
Current FIO design do not properly handle do_verify option when read and write command are overlapping. It does not respect the NVMe specification where overlapping command execution order is not guaranty.
**!!! If this is not correct, please correct !!!**

###  Point 2:
You are saying that setting overwrite=1 should make the problem go away. I do not really understand why? I have a lack of understanding about FIO when do_verify=1 and overwrite=1 option are set.

> If true, writes to a file will always overwrite existing data. If the file doesn’t already exist, it will be created before the write phase begins. If the file exists and is large enough for the specified write phase, nothing will be done.

My interpretation/question:
* Does it mean that the test make sure that the data was at least written once in the drive before reading it.
* Even after written it once to the file, if the overlapping command can still occur afterward, in this case why would FIO not report error (does it write the same data ? or does FIO dont care if the drive is returning older data or new data when command are overlapping)

Anyway, I am trying to reproduce it with the option overwrite=1 option. I will keep you inform of the result.

###  Point 3:
Setting iodetph=1 mean that we have no more overlapping command since only 1 command is run at a time. This may work but that wont solve the intent which is to check data corruption when queue depth is more than 1.

###  Point 4:
The intent of the serialize_overlap option (#343), is to avoid command overlapping. It mean that it should resolve all problem related to command execution order when command are overlapping. I like it and I hope it will be released in the next version.

**Comment by sitsofe** [comment]
Point 1 - it's hard to say which issues you're hitting. There is a bug in fio where it doesn't discard old overwritten because overlap detection has a bug when overwrite=0. Others have been hitting that issue but it could be that you are indeed seeing the case you're theorising about (an inflight read and a write racing each other). I can't say for sure.

Point 2 - I'm saying it *might* go away with `overwrite=1`. It's not because overwrite=1 is the right thing to do but because it stops the bug triggering (see the previously linked https://github.com/axboe/fio/issues/344#issuecomment-297852987 for details) . It's an easy thing for you to check though.

Point 3 - it's more to check to see if the problem goes away. If it doesn't go away and iodepth is 1 you're definitely in the point 1 case.

Point 4 - It sounds like it's unlikely to go in within its current form but if you want it sooner you can always pull the patch into your own fio builds :-)

**Comment by Awele** [comment]
Hi @sitsofe ,
Thank you for the time you take to help me, I really appreciate that.
I have reproduced the bug when the overwrite=1 option is set. So I guess this issue is not linked to #344 bug. I did not check if command on LBA 0x04ABF280 this time but I strongly suspect that read and write command are overlapping. (if it is needed, I can analyze it)

We can also notice that the verification failure occur on the exact same offset so I will put more detail about the whole script I am using (and not just the script which is failing)

At work, we decided not to use this script so it is not anymore a critical issue on our side. But I will try to work on this issue since it would be a nice if verification did work in the future.

### FIO script
overwrite=1 option set on is the only change compare to last time.

```
fio --ioengine=libaio \
    --name=fio_preconditioning \
    --output=XXXX_Precondition.log \
    --filename=/dev/nvme0n1 \
    --iodepth=32 \
    --rw=write \
    --bs=128k \
    --direct=1 \
    --numjobs=1 \
    --size=100% \
    --stonewall \
    --group_reporting \
    --refill_buffers \
    --loop=1

fio sample.fio --output=XXXX.log --runtime=172800 --verify_dump=1 --overwrite=1
```

 sample.fio 
```
[job0]
size=100%
filename=/dev/nvme0n1
time_based=1
description=Random IO
iodepth=16
bs=32k
rw=randrw:2
rwmixread=53
random_distribution=random:7
loops=1
thread=1
direct=1
ioengine=libaio
random_generator=tausworthe
lockfile=readwrite
verify=md5
do_verify=1
verify_fatal=1
verify_backlog=1
invalidate=0
loops=1
```

### Execution output
```
$ fio -v
fio-2.9

Script execution error:
verify: bad magic header 5487, wanted acca at file /dev/nvme0n1 offset 40129331200, length 32768
       hdr_fail data dumped as nvme0n1.40129331200.hdr_fail

$ hexdump nvme0n1.40129331200.hdr_fail | head
0000000 5487 b241 11b2 0eb1 aa90 ac04 c915 12ed
0000010 9552 6038 e320 03c2 12aa c15e 2c47 17a6

faulty sector number: 40129331200 / 512 = 0x04ABF280

$ sudo nvme read /dev/nvme0n1 -s 0x04ABF280 -z 32768 -d read_0x04ABF280.bin
read: Success
$ hexdump read_0x04ABF280.bin | head
0000000 acca 0002 8000 0000 b900 a2a6 0d5a 286d
0000010 0000 bf28 004a 0000 0c07 0000 a926 0001
```

**Comment by sitsofe** [comment]
I'll start off by noting your fio is very old. I'd recommend building 2.20 because so much has been fixed since the versions you run.

The header you got back clearly shows data that has not yet been written to by this fio run so it's not a case where you were overwriting a place that was previously written.

You should be able to confirm your theory by adding --debug=io on the fio command line and before the job. This will produce a large amount of output but what you will be at the end.

It's a bit curious that you turn cache invalidation off but I can't see how it would change the result in your particular case.

I guess a workaround is to verify_backlog at least equal to the iodepth? With the previously mentioned patch your iodepth would effectively be forced to 1 because the queue would be flushed after every I/O...

**Comment by sitsofe** [comment]
Something that might be interesting is if you simplify your verify job and see if the problem still happens. If your theory is correct then even a plain sequential write workload being verified with a backlog of 1 should trigger this, no?

**Comment by sitsofe** [comment]
@Awele `serialize_overlap` (http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-serialize-overlap ) has gone into the git tree of fio. Can you build an fio with it in, enable it and see if that resolves what you've been seeing? If so can you close this issue?

**Comment by Awele** [comment]
@sitsofe, thank you for the follow.

Unfortunately I do not have the environment to test the new feature. So I cannot verify if the new feature fix the problem I had. Logically it should fix the issue I had so I think we can close this ticket (Please reopen if you have problem with this policy).

Thank you for all the support. I really appreciate it.

**Comment by sitsofe** [comment]
@Awele OK thanks for following up.

We'll consider this issue closed and if you see this exact problem again in fio-3.0 (or later) when you've used `serialize_overlap=1` please reopen it.
