### ISSUE TITLE
output-format=json when running client/server causes a segfault

### ISSUE THREAD

**Issue by mledgington** [axboe/fio#375]
Commit 002e57665ed7eebe920de6f1729ef2e403b7c6cc to json.c (lines 345-347) now calls buf_output_add directly instead of using log_buf, which checks to see if the output buf is NULL (which client.c does for server/client using JSON output).

**Comment by axboe** [comment]
Oops yes, that's no good... I'll see if I can wrangle up a fix.

**Comment by axboe** [comment]
Reverted the problematic fix.
