### ISSUE TITLE
Non-zero offset and non-zero size skew disk working set size

### ISSUE THREAD

**Issue by cbwest3** [axboe/fio#377]
When an fio job uses a non-zero offset value and a non-zero size parameter, the working set size on disk is skewed.  For a 64k file, the job provided touches the following blocks:

`fio --stonewall --rw=read --name=firstquarter --size=25% --offset=0% --name=secondquarter --size=25% --offset=25% --name=thirdquarter --size=25% --offset=50%`

    |1111111111111111|222222222222----|33333333--------|----------------|
    0                16k              32k              48k              64k

    1=written by firstquarter, 2=written by secondquarter, 3=written by thirdquarter

**Comment by sitsofe** [comment]
To cope with this we'd need offset % (and possibly size %) to round downwards to the nearest block (rather than upwards) so they are more likely to touch...

**Comment by cbwest3** [comment]
I think this is related to the size parameter.  This can be reproduced using fixed-size offsets.  It seems the expected vs. actual math on working set size is (size_param_percent * size_of_file) vs. (size_param_percent * (size_of_file - offset)).

**Comment by sitsofe** [comment]
OK it seems that `io_size` is supposed to be reduced if offset means you can't do a full size amount of I/O. How about this patch?
```patch
diff --git a/filesetup.c b/filesetup.c
index 612e794..057636b 100644
--- a/filesetup.c
+++ b/filesetup.c
@@ -986,7 +986,13 @@ int setup_files(struct thread_data *td)
 			total_size = -1ULL;
 		else {
                         if (o->size_percent) {
-				f->io_size = (f->io_size * o->size_percent) / 100;
+				uint64_t file_size;
+
+				file_size = f->io_size + f->file_offset;
+				f->io_size = (file_size *
+					      o->size_percent) / 100;
+				if ((f->file_offset + f->io_size) > file_size)
+					f->io_size = file_size - f->file_offset;
 				f->io_size -= (f->io_size % td_min_bs(td));
 			}
 			total_size += f->io_size;
```

I checked this by doing
```
dd if=/dev/zero of=/tmp/fiofile bs=64k count=1
./fio --bs=2k --buffer_pattern=0xaa --filename /tmp/fiofile --stonewall --rw=write --name=firstquarter --size=25% --offset=0 --name=secondquarter --size=25% --offset=16k --name=last --offset=52k
```
