### ISSUE TITLE
io_bytes reported in JSON output is off by factor of 1024

### ISSUE THREAD

**Issue by cbwest3** [axboe/fio#378]
Sending a single 1M op to disk results in io_bytes=1024, per JSON output. This issue was mentioned in #233, among other things.  Reproducing the issue is simple, as shown below.

    $ sudo fio --name=test --filename=/dev/sdb --bs=1m --size=1m --output-format=json
    {
      "fio version" : "fio-2.19-66-gd44a",
      "timestamp" : 1496428095,
      "timestamp_ms" : 1496428095820,
      "time" : "Fri Jun  2 14:28:15 2017",
      "jobs" : [
        {
          "jobname" : "test",
          "groupid" : 0,
          "error" : 0,
          "eta" : 2147483647,
          "elapsed" : 1,
          "job options" : {
            "name" : "test",
            "filename" : "/dev/sdb",
            "bs" : "1m",
            "size" : "1m"
          },
          "read" : {
            "io_bytes" : 1024,
            "bw" : 256000,
            "iops" : 250.000000,
            "runtime" : 4,
            "total_ios" : 1,
            "short_ios" : 0,
            "drop_ios" : 0,
            "slat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000
            },
            "clat" : {
              "min" : 3495,
              "max" : 3495,
              "mean" : 3495.000000,
              "stddev" : 0.000000,
              "percentile" : {
                "1.000000" : 3504,
                "5.000000" : 3504,
                "10.000000" : 3504,
                "20.000000" : 3504,
                "30.000000" : 3504,
                "40.000000" : 3504,
                "50.000000" : 3504,
                "60.000000" : 3504,
                "70.000000" : 3504,
                "80.000000" : 3504,
                "90.000000" : 3504,
                "95.000000" : 3504,
                "99.000000" : 3504,
                "99.500000" : 3504,
                "99.900000" : 3504,
                "99.950000" : 3504,
                "99.990000" : 3504,
                "0.00" : 0,
                "0.00" : 0,
                "0.00" : 0
              }
            },
            "lat" : {
              "min" : 3496,
              "max" : 3496,
              "mean" : 3496.000000,
              "stddev" : 0.000000
            },
            "bw_min" : 0,
            "bw_max" : 0,
            "bw_agg" : 0.000000,
            "bw_mean" : 0.000000,
            "bw_dev" : 0.000000
          },
          "write" : {
            "io_bytes" : 0,
            "bw" : 0,
            "iops" : 0.000000,
            "runtime" : 0,
            "total_ios" : 0,
            "short_ios" : 0,
            "drop_ios" : 0,
            "slat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000
            },
            "clat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000,
              "percentile" : {
                "1.000000" : 0,
                "5.000000" : 0,
                "10.000000" : 0,
                "20.000000" : 0,
                "30.000000" : 0,
                "40.000000" : 0,
                "50.000000" : 0,
                "60.000000" : 0,
                "70.000000" : 0,
                "80.000000" : 0,
                "90.000000" : 0,
                "95.000000" : 0,
                "99.000000" : 0,
                "99.500000" : 0,
                "99.900000" : 0,
                "99.950000" : 0,
                "99.990000" : 0,
                "0.00" : 0,
                "0.00" : 0,
                "0.00" : 0
              }
            },
            "lat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000
            },
            "bw_min" : 0,
            "bw_max" : 0,
            "bw_agg" : 0.000000,
            "bw_mean" : 0.000000,
            "bw_dev" : 0.000000
          },
          "trim" : {
            "io_bytes" : 0,
            "bw" : 0,
            "iops" : 0.000000,
            "runtime" : 0,
            "total_ios" : 0,
            "short_ios" : 0,
            "drop_ios" : 0,
            "slat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000
            },
            "clat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000,
              "percentile" : {
                "1.000000" : 0,
                "5.000000" : 0,
                "10.000000" : 0,
                "20.000000" : 0,
                "30.000000" : 0,
                "40.000000" : 0,
                "50.000000" : 0,
                "60.000000" : 0,
                "70.000000" : 0,
                "80.000000" : 0,
                "90.000000" : 0,
                "95.000000" : 0,
                "99.000000" : 0,
                "99.500000" : 0,
                "99.900000" : 0,
                "99.950000" : 0,
                "99.990000" : 0,
                "0.00" : 0,
                "0.00" : 0,
                "0.00" : 0
              }
            },
            "lat" : {
              "min" : 0,
              "max" : 0,
              "mean" : 0.000000,
              "stddev" : 0.000000
            },
            "bw_min" : 0,
            "bw_max" : 0,
            "bw_agg" : 0.000000,
            "bw_mean" : 0.000000,
            "bw_dev" : 0.000000
          },
          "usr_cpu" : 0.000000,
          "sys_cpu" : 0.000000,
          "ctx" : 3,
          "majf" : 0,
          "minf" : 266,
          "iodepth_level" : {
            "1" : 100.000000,
            "2" : 0.000000,
            "4" : 0.000000,
            "8" : 0.000000,
            "16" : 0.000000,
            "32" : 0.000000,
            ">=64" : 0.000000
          },
          "latency_us" : {
            "2" : 0.000000,
            "4" : 0.000000,
            "10" : 0.000000,
            "20" : 0.000000,
            "50" : 0.000000,
            "100" : 0.000000,
            "250" : 0.000000,
            "500" : 0.000000,
            "750" : 0.000000,
            "1000" : 0.000000
          },
          "latency_ms" : {
            "2" : 0.000000,
            "4" : 100.000000,
            "10" : 0.000000,
            "20" : 0.000000,
            "50" : 0.000000,
            "100" : 0.000000,
            "250" : 0.000000,
            "500" : 0.000000,
            "750" : 0.000000,
            "1000" : 0.000000,
            "2000" : 0.000000,
            ">=2000" : 0.000000
          },
          "latency_depth" : 1,
          "latency_target" : 0,
          "latency_percentile" : 100.000000,
          "latency_window" : 0
        }
      ],
      "disk_util" : [
        {
          "name" : "sdb",
          "read_ios" : 0,
          "write_ios" : 0,
          "read_merges" : 0,
          "write_merges" : 0,
          "read_ticks" : 0,
          "write_ticks" : 0,
          "in_queue" : 0,
          "util" : 0.000000
        }
      ]
    }

**Comment by sitsofe** [comment]
I'm not sure what to do about this one. This came in with the dawn of json in fio (see https://github.com/axboe/fio/commit/cc372b17f2827e89da79241f1bbaca1e7c650611#diff-db536a6e586c0739e8e679f910add4b9R709 ) and I suspect it was to mimic the output of terse-output but sadly it was given a misleading json key. Perhaps fio should add a `io_kbytes` and one day add a `--json-old` mode to keep creating the `io_bytes` key. Care will have to be taken to do the right thing with `io_kbytes` if the user sets `kb_base=1000` too...

**Comment by cbwest3** [comment]
@sitsofe Since the discrepancy is large (factor of 1024), I would think anyone using the `io_bytes` property is aware of the issue and performing some sort of fix-up calculation (I currently am via Jupyter notebook).  I would suggest keeping the `io_bytes` property, fixing the reported value, and allowing users to perform whatever unit conversions they deem necessary (kB, KB, KiB, etc).

**Comment by sitsofe** [comment]
I'm not sure I follow. Changing `io_bytes` to really output bytes would be a vicious change to inflict by default but are you suggesting we make it a command line option to control whether this change takes place?

**Comment by axboe** [comment]
I'm guessing that most people don't actually use this key, or they would have spotted the error. Most of the QA/benchmarks automation I know of use the time, iops/speed, system overhead, etc.

So while it's a big ugly, my vote would be to just fix it up. The change is big enough that if you are using io_bytes, then you will surely notice that your math is now off by 1024. I'd be more worried if it was off by 1.024 or something like that.

**Comment by axboe** [comment]
Pushed a fix for this. There's now also an 'io_kbytes' key that shows the old output, and the 'io_bytes' has been corrected to actually be bytes.

**Comment by sitsofe** [comment]
@axboe given this change do we want to change bw to be in bytes too?

**Comment by cbwest3** [comment]
Yikes, I didn't notice the `bw` number was reported in KB too.  Since there is no unit label (e.g. bw_KBps), I had assumed it was in bytes per second.  I suggest either appending units to the property name (such as KBps) or keeping the label `bw` and reporting bytes per second.  My preference is the latter. :)

I'm happy to open a new issue if needed.

**Comment by axboe** [comment]
Ugh, Sitsofe, you are right. You know, given both of those, I'm going to revert the previous commit. That's a much bigger deal, imho.

**Comment by cbwest3** [comment]
@axboe Is it possible to keep the fix for `io_bytes`?  I think the logic was sound for that change and that `bw` is a different beast.  `io_bytes` claimed to report a number of bytes, which was clearly not the case.  The `bw` property does not claim a unit, either in its name nor in the documentation.

In the interest of not breaking current users and enabling fio use in a programmatic manner, can we:

1) Leave the current `bw` calculation as is and document it as KBps.
2) Create a new `bw_bytes_per_sec`, and document it as bytes per second?  Like `io_bytes`, this would allow users to perform their own unit conversion (base 10 or base 2), and eliminates (possible) undesired rounding and reduced precision.

Thank you for your consideration!

**Comment by axboe** [comment]
Yeah, thinking more about it, I still like the original change. So let's retain that behavior for io_bytes, and add the new key.
