### ISSUE TITLE
Compilation only Rados Block Device engine = no

### ISSUE THREAD

**Issue by 74cmonty** [axboe/fio#381]
Hello!
I want to compile fio with "Rados Block Device engine = yes", but when I run make on Ceph Monitor Node, this option is always no.

How can I ensure that Rados Block Device engine is enabled?

THX

**Comment by axboe** [comment]
Install the rbd development files/libaries. On debian, it's librbd-dev, on a RH based distro it's probably librbd-devel or something like that.
