### ISSUE TITLE
Weird bandwidth results when writing files smaller than 5-10GiB?

### ISSUE THREAD

**Issue by bknowles** [axboe/fio#383]
Folks,

I'm at a bit of a loss on how to go about debugging this.  I'm using fio-2.20 as installed with `brew` on macOS Sierra 10.12.5, and on my MacBook Pro (Retina, 15-inch, Mid 2014) with 16GB of RAM and testing with files in the 5-10GiB range, I see what I believe to be unfeasibly fast results on sequential and random reads.  I get bandwidth results of ~5GB/s on every loop with the 5GiB files, and on the 10GiB files I get more reasonable results the first couple of times through the loop but then the speeds ramp up to the ~5GB/s range.

I'm thinking that this problem might be a result of the fact that the only foreground app I've got open during these tests is the Terminal, and the test files are considerably smaller than the amount of RAM in the machine.  It might also be an issue with the way that `brew` compiles and installs this version, since libaio is not available to me as an ioengine.

When I run the same tests on an older laptop with only 8GB of RAM but also on the same version of macOS, I get more reasonable results out-of-the-box with 5GiB test files, but of course the hardware is older and slower, too.

If you can give me some pointers on how I can help debug this problem, I'd be glad to provide whatever assistance I can.

I'm attaching the configuration I'm testing with (see below), and here's a sample run with this file:

```
$ fio ssd-test.txt --section seq-read
seq-read: (g=0): rw=read, bs=(R) 32.0KiB-32.0KiB, (W) 32.0KiB-32.0KiB, (T) 32.0KiB-32.0KiB, ioengine=psync, iodepth=4
fio-2.20
Starting 1 process
Jobs: 1 (f=1)
seq-read: (groupid=0, jobs=1): err= 0: pid=7336: Fri Jun  9 01:22:33 2017
   read: IOPS=169k, BW=5295MiB/s (5552MB/s)(5120MiB/967msec)
    clat (usec): min=4, max=114, avg= 5.57, stdev= 1.27
     lat (usec): min=4, max=114, avg= 5.62, stdev= 1.29
    clat percentiles (usec):
     |  1.00th=[    5],  5.00th=[    5], 10.00th=[    5], 20.00th=[    5],
     | 30.00th=[    5], 40.00th=[    5], 50.00th=[    5], 60.00th=[    6],
     | 70.00th=[    6], 80.00th=[    6], 90.00th=[    6], 95.00th=[    7],
     | 99.00th=[    9], 99.50th=[   14], 99.90th=[   17], 99.95th=[   20],
     | 99.99th=[   42]
   bw (  MiB/s): min= 5256, max= 5256, per=0.10%, avg=5256.32, stdev= 0.00
    lat (usec) : 10=99.03%, 20=0.92%, 50=0.05%, 100=0.01%, 250=0.01%
  cpu          : usr=9.01%, sys=90.89%, ctx=61, majf=0, minf=33
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=163840,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
   READ: bw=5295MiB/s (5552MB/s), 5295MiB/s-5295MiB/s (5552MB/s-5552MB/s), io=5120MiB (5369MB), run=967-967msec
```

[EDIT]

If I boost the file size to 10GiB, and do some runs, they start off looking like this:

```
$ fio ssd-test.txt --section seq-read
seq-read: (g=0): rw=read, bs=(R) 32.0KiB-32.0KiB, (W) 32.0KiB-32.0KiB, (T) 32.0KiB-32.0KiB, ioengine=psync, iodepth=4
fio-2.20
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=1100MiB/s,w=0KiB/s][r=35.2k,w=0 IOPS][eta 00m:00s]
seq-read: (groupid=0, jobs=1): err= 0: pid=7400: Fri Jun  9 01:39:40 2017
   read: IOPS=34.1k, BW=1065MiB/s (1116MB/s)(10.0GiB/9618msec)
    clat (usec): min=3, max=6352, avg=28.89, stdev=112.04
     lat (usec): min=3, max=6352, avg=28.95, stdev=112.04
    clat percentiles (usec):
     |  1.00th=[    3],  5.00th=[    3], 10.00th=[    3], 20.00th=[    3],
     | 30.00th=[    4], 40.00th=[    4], 50.00th=[    4], 60.00th=[    4],
     | 70.00th=[    4], 80.00th=[    5], 90.00th=[    9], 95.00th=[  262],
     | 99.00th=[  502], 99.50th=[  612], 99.90th=[ 1032], 99.95th=[ 1512],
     | 99.99th=[ 2704]
   bw (  MiB/s): min=  992, max= 1126, per=0.10%, avg=1064.93, stdev=45.05
    lat (usec) : 4=21.16%, 10=68.96%, 20=2.08%, 50=1.02%, 100=0.50%
    lat (usec) : 250=1.13%, 500=4.13%, 750=0.72%, 1000=0.18%
    lat (msec) : 2=0.08%, 4=0.03%, 10=0.01%
  cpu          : usr=2.40%, sys=40.76%, ctx=63518, majf=0, minf=33
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=327680,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
   READ: bw=1065MiB/s (1116MB/s), 1065MiB/s-1065MiB/s (1116MB/s-1116MB/s), io=10.0GiB (10.7GB), run=9618-9618msec
```

But occasionally, I'll see a run boost to 1200-1300MiB/s.  But after a few more runs, they start going up to 2GiB/s, 3GiB/s, or even higher.  With a 10GiB test file, I've seen runs as high as ~5GiB/s.

I'm about to start doing a bunch of runs with a 20GiB test file, and we'll see how that goes.

[ssd-test.txt](https://github.com/axboe/fio/files/1063148/ssd-test.txt)

**Comment by sitsofe** [comment]
```
[...]
direct=0
```

You are saying you are happy for I/O to be satisfied by your operating system's cache. As such writes can be buffered in RAM and returned as done straight away even though they haven't been flushed to disk yet / reads for data that happen to already be in RAM can be satisfied immediately from there. Is this what you want?

**Comment by bknowles** [comment]
Ahh.  Okay, I was not aware that was the implication of that setting.

I guess I was just cargo-culting what I had seen somewhere else that said you needed to do that if you were going to be doing testing on SSDs.  Sigh....

Let me try it the other way, and I'll let you know if I continue to have problems.

Thanks!

**Comment by bknowles** [comment]
Indeed, using `direct=1` does seem to provide results that are more consistent and more plausible.

Sorry for the noise.

**Comment by sitsofe** [comment]
PS: libaio is only available on Linux. You can try posixaio on MacOS  - http://fio.readthedocs.io/en/latest/fio_doc.html#i-o-engine .
