### ISSUE TITLE
IOPS logs shows only 1

### ISSUE THREAD

**Issue by tungvs1486** [axboe/fio#385]
FIO version 2.20

This is the config file:
```
[global]
name=fio_cpg01
ioengine=libaio
iodepth=4
size=1g
direct=1
runtime=30
directory=/apps/fio-zone
filename=fio.test.out
write_bw_log=fio_cpg01_8k
write_lat_log=fio_cpg01_8k
write_iops_log=fio_cpg01_8k

[rand-rw-8k]
rw=randrw
rwmixread=70
bs=8k
stonewall
```

The IOPS log only shows IOPS = 1 all the time

```
[tungvs@tungvs-apps fio-test]$ less fio_cpg01_8k_iops.1.log 
1, 1, 1, 8192
1, 1, 1, 8192
51, 1, 0, 8192
52, 1, 1, 8192
75, 1, 0, 8192
91, 1, 0, 8192
92, 1, 1, 8192
93, 1, 1, 8192
94, 1, 1, 8192
94, 1, 0, 8192
95, 1, 1, 8192
172, 1, 0, 8192
176, 1, 0, 8192
181, 1, 0, 8192
210, 1, 0, 8192
236, 1, 0, 8192
248, 1, 0, 8192
249, 1, 1, 8192
250, 1, 1, 8192
251, 1, 1, 8192
251, 1, 1, 8192
261, 1, 0, 8192
```

Meanwhile, the bandwidth log seems to be normal

```
[tungvs@tungvs-apps fio-test]$ less fio_cpg01_8k_bw.1.log 
1, 10666, 1, 8192
1, 9298, 1, 8192
51, 162, 0, 8192
52, 12064, 1, 8192
75, 110, 0, 8192
91, 90, 0, 8192
92, 11457, 1, 8192
93, 10597, 1, 8192
94, 10240, 1, 8192
94, 87, 0, 8192
95, 12154, 1, 8192
172, 84, 0, 8192
176, 66, 0, 8192
181, 93, 0, 8192
210, 71, 0, 8192
236, 127, 0, 8192
248, 122, 0, 8192
249, 13407, 1, 8192
250, 11505, 1, 8192
251, 11175, 1, 8192
251, 10113, 1, 8192
```

**Comment by sitsofe** [comment]
Fio *defaults* to logging every I/O not averaging them out over a period. See the [Log File Formats section of the HOWTO](http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats) for further details. You can use [log_avg_msec](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-avg-msec) to change this behaviour. 

@tungvs1486 you don't happen to work for SUSE do you? This has recently come up over on https://github.com/axboe/fio/issues/337 and http://www.spinics.net/lists/fio/msg05916.html so this question rapidly turning into a FAQ...

**Comment by tungvs1486** [comment]
Thanks @sitsofe ,
That's correct. I've used the previous version of Fio (2.1.10) up until now and just upgraded it to 2.20 since yesterday.
Thanks for your time.
Also, I don't work for SUSE (at least for now)

**Comment by sitsofe** [comment]
@tungvs1486 Just checking... ;-)
