### ISSUE TITLE
Android: libc doesn't have rpmatch()

### ISSUE THREAD

**Issue by omor1** [axboe/fio#390]
Android libc (Bionic) doesn't, as far as I can tell have the `rpmatch()` function (can @enh confirm?).

This needs a workaround, much like is currently done for earlier versions of uClibc. This can either go in `oslib/libmtd_common.h` like is done for uClibc, or in `os/os-android.h` like is done for some of the other Android wrapper functions.

Currently, this results in a warning when compiling (implicit function declaration), but somehow everything links. Presumably there would be problems if one would try to use the MTD I/O engine.

**Comment by axboe** [comment]
What a mess that is. I'd say just have mtd include it's own mtd_rpmatch() and kill that silly check for uclibc and versions. I can do it, if no one else wants to.

**Comment by axboe** [comment]
Done

**Comment by omor1** [comment]
I think that `rpmatch()` is supposed to support internationalization (according to the man page) as well as always accepting `^[Yy]` and `^[Nn]` as affirmative and negative, respectively. But I don't think that it matters all that much in practice :).

**Comment by axboe** [comment]
We can deal with that once fio is internationalized. Right now it's only in English :-)

**Comment by enh** [comment]
yeah, thanks for the heads up, but `rpmatch` doesn't sound like something we'd ever want to implement! half-baked libc i18n rarely ends well :-)

**Comment by axboe** [comment]
Nobody is implementing a full anything of rpmatch. However, if the choice is between a two-liner y/n check or another mess of ifdef and versioning, then I'm picking the former.

But in any case, the code isn't even USED. Fio doesn't prompt for anything once, everything is driven by the job file or command line options. It either loads or fails, no in between or followup questions.

**Comment by omor1** [comment]
f25f4ef6d123173d7669553ec712419f95c1a3ea gets rid of that code in any case :). What methods are there to detect similar dead code?

**Comment by axboe** [comment]
I actually don't know what people tend to use for this. The code in question was static inline, and those are by definition never warned about by gcc. So it's not like the dead code does any harm, and especially for libmtd, I don't want to embark on a cleanup adventure, since keeping it closer to upstream is better. But dead code in fio proper should definitely be pruned, if it exists.
