### ISSUE TITLE
BLKTRACE* macros redefined

### ISSUE THREAD

**Issue by omor1** [axboe/fio#391]
The `BLKTRACE*` macros are defined in both `<linux/fs.h>` and in `blktrace_api.h`. This results in multiple compile-time warning for redefined macros.

This definitely occurs when compiling for Android, but probably occurs for desktop Linux with glibc as well; its `<linux/fs.h>` defines the macros too.

Since these are block device ioctls, I really doubt fio needs to define them itself and they can be removed from `blktrace_api.h`. If it does, then they can be put in `#ifndef`s to avoid the redefinitions.

**Comment by axboe** [comment]
I've just killed them, fio doesn't use the ioctls at all.
