### ISSUE TITLE
fio 2.1.7 and 2.1.10 run 100% random wirte, after the written data extend then physical drive or VD capacity, the IOPS will increase about 30% and jitter also increase

### ISSUE THREAD

**Issue by zuiko7** [axboe/fio#392]
Hi Guys 

I used fio 2.1.7 and 2.1.10 for SSD IOPS testing, test both of JBOD mode and Raid 10, run 100% random write test case. the problem is when the written data exceed then physical drive or VD capacity, then IOPS will increase about 30% and jitter will also increase.
But I have tried the latest version 2.17, it does not have the same situation, the IOPS is very smooth

Did anyone see the same situation

Thank you very much

**Comment by axboe** [comment]
Both of those versions are absolutely ancient. Does it reproduce in the current version, fio-2.21?

**Comment by zuiko7** [comment]
I tried 2.17, it published this year, and it cannot reproduce that situaion, I did not try 2.21

Thank you

**Comment by axboe** [comment]
If a newer version fixes it, I'm not sure what you want me to do with this report. I can't travel back in time and fix that regression in 2.1.10 :-)

**Comment by zuiko7** [comment]
Hi axboe
Thank you for your help, I want to understand, why the old version has this situation
THank you

**Comment by axboe** [comment]
Without knowing all the details of what is happening, I can't say. You could try a git bisect between the newest bad version and the oldest new version. You know 2.1.10 is broken and that 2.17 is not. You could then do a git bisect to find the commit that fixed the issue. Once you have that, then you can probably tell what the exact fix is.
