### ISSUE TITLE
Trimming 0GiB shouldn't take any time at all 

### ISSUE THREAD

**Issue by SamTheDev** [axboe/fio#396]
I was experimenting with trim on an Nvme lately, i was changing the amount of space trimmed in the disk, then measure the performance afterwards, what caught my attention was that trimming a size of 0G took, abnormally, too much time.

Here is my job file:
`[global]
ioengine=libaio
iodepth=256
size=0G
direct=1
do_verify=1
verify=crc32c-intel
continue_on_error=verify
filename=/dev/nvme0n1
[trim-job]
rw=trim
bs=512k
stonewall`

>Time needed: 770 seconds
>Time needed to trim: 74G is 27 seconds !

**Comment by sitsofe** [comment]
@SamTheDev are you sure setting a size of 0G does what you think it does or does it means something else - http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size ?

**Comment by SamTheDev** [comment]
I missed that !
Yes indeed, setting the size to 0G will simply run the Job on the entire disk size.
Thank you @sitsofe

**Comment by sitsofe** [comment]
You're welcome @SamTheDev .
