### ISSUE TITLE
No writes on a logical volume

### ISSUE THREAD

**Issue by painbird7** [axboe/fio#398]
Noticed FIO does not perform any writes on my secondary drive which has been configured with a software RAID1 in Windows. Based on the Disk Monitor tool, it seems that the write workloads are being ignored or skipped. Am I doing something wrong? Or FIO doesn’t support such actions on a formatted volume? 

•	OS: Windows 2012 R2 x64, version 6.3.9600
•	FIO Version: 2.6
•	How to reproduce:
    1. Create a software RAID5 volume in Windows and assign a letter E.
    2. Run FIO in command line with the following args: --output-format=json –filename=\\.\E\: --
    runtime=10 test2.fio

**Comment by axboe** [comment]
As usual for bug reports, please include how you are invoking fio, what you expected, what happened, etc. It's impossible to help you with such a vague report. Also see the REPORTING-BUGS file that fio comes with, it has all the details you need:

http://git.kernel.dk/cgit/fio/tree/REPORTING-BUGS

**Comment by painbird7** [comment]
Thank you axboe. Emailed the question.

**Comment by sitsofe** [comment]
I don't think you can access physical drives as letters - letters are for volumes/file systems. See the HOWTO filename section - http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-filename . Note it's hard to tell if this is your issue without the REPORTING-BUGS information...

**Comment by sitsofe** [comment]
@painbird7 I stand corrected - you can do I/O to raw "volumes" so long as you obey the rules mentioned in the filename section of the HOWTO (i.e. you **have** to escape the path correctly, there must be no filesystem on top etc). In my test the path **before** escaping looked like `\\.\E:` for the volume `E:`.

**Comment by painbird7** [comment]
Thank you! Got it to work as I needed by using the --directory switch instead of filename after creating a folder in the volume.

**Comment by sitsofe** [comment]
@painbird7 good to hear you solved your problem. Can you close this issue please?

**Comment by sitsofe** [comment]
@painbird7 - if your issue has been solved could you close this issue? Thanks.

**Comment by sitsofe** [comment]
@painbird7 / Jay - are you there?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
