### ISSUE TITLE
rw=trimwrite and `bssplit=` combination

### ISSUE THREAD

**Issue by wyysoft** [axboe/fio#399]
My fio script:

`[global]
ioengine=libaio
filename=/dev/nvme0n1
thread
direct=1
time_based
runtime=5

[trimwrite]
bssplit=4k/60:8k/10:16k/5:32k/5:64k/20
rw=trimwrite
iodepth=1
write_iolog=trimwritelog.txt
`

The iolog shows that there is only one TRIM command, and others are all write command, which is not what I expected. 
However, if I set 'bs=8k' instead of 'bssplit=' parameter, the result is what I expect.

Is there anything to be noted while using 'bssplit=' + 'rw=trimwrite' together? Thanks~

My FIO version is v2.21 formal, and OS is Ubuntu 16.04.2 formal release.

**Comment by axboe** [comment]
That's definitely a bug, I'll take a look.

**Comment by axboe** [comment]
OK, so this is what is happening. trimwrite is special in that it's meant to trim a block, then write it. That depends on the block sizes being used being identical. When you set bssplit, even if the settings are the same (which they are in your case), we pick the next block size randomly. Hence things will no longer line up, and we won't alternate between the trim and the write. For the case of trimwrite, we just need to sequence them identically.

**Comment by axboe** [comment]
Pushed a fix, please re-test with current -git.
