### ISSUE TITLE
"verify: bad magic header" when running random trims and random writes in parallel jobs

### ISSUE THREAD

**Issue by SamTheDev** [axboe/fio#400]
I am not sure what i am looking at here, when i run two jobs, one that do random writes and the other do random trims using different block sizes and using the `crc32c-intel` verification, I am getting tons of bad magic header on different offsets.
Here is my fio file:
```[global]
ioengine=libaio
iodepth=256
size=745G
direct=1
do_verify=1
verify=crc32c-intel
continue_on_error=verify
filename=/dev/nvme0n1
[rand-write]
rw=randwrite
bs=128k
stonewall
[rand-trim]
rw=randtrim
bs=8k
```
And here a sample of the errors i am getting:

> verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 74384015360, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 229102190592, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 738719563776, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 517141430272, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 770493775872, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 658903269376, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 154457997312, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 179346472960, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 147415236608, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 104724430848, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 78316306432, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 422666043392, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 355708436480, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 783581184000, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 355939647488, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 581093687296, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 487317438464, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 329462579200, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 590256930816, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 291887644672, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 316852404224, length 131072
verify: bad magic header 0, wanted acca at file /dev/nvme0n1 offset 205704658944, length 131072

The same bad magic header errors occur with 4k,8k,16k,32k randtrim's block size. 
How do i interpret this, am i doing something wrong, or something isn't right with fio?

**Comment by sitsofe** [comment]
@SamTheDev Are all the errors arriving after the rand-trim job starts? Do you still get the errors with much smaller size parameters (e.g. size=1G, size=128M)?

**Comment by SamTheDev** [comment]
@sitsofe No, the jobs start with no error at first, but after running for a while those errors start popping out.
The benchmark is still running using bigger blocks, i will report back if the same behavior occurs for bigger randtrims block sizes.

**Comment by sitsofe** [comment]
@SamTheDev I'm a bit suspicious that the jobs aren't running sequentially - could you move the stonewall to before the first job?

**Comment by sitsofe** [comment]
PS: If you're wondering why I'm asking to experiment with moving the stonewall into the global section, take a look at the opening sentence explanation (and the alternative name) in the HOWTO for stonewall: http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-stonewall  ...

**Comment by SamTheDev** [comment]
@sitsofe Ok, i will try that out, i will report back when i will get the results.

>  I'm a bit suspicious that the jobs aren't running sequentially 

The whole point behind this is to run the rand writes and rand trims in parallel!, isn't this the right way to do it?

**Comment by sitsofe** [comment]
@SamTheDev Perhaps I can give a small example:

[global]
filename=/tmp/fiofile
verify=crc32c
direct=1
[job1]
rw=write
bs=8k
[job2]
rw=randwrite
bs=4k

Imagine job1 finishes first and starts doing its verify while job2 (which is running in parallel) is continuing to do its writes. job2 will have changed data that job1 does not know about, therefore when job1 is doing a verify and finds data that doesn't match what it (job1) wrote it will complain about corrupted/mismatching data. Is that clearer?

**Comment by SamTheDev** [comment]
@sitsofe pretty clear thx :))

**Comment by sitsofe** [comment]
@SamTheDev To go back to your original example, you could have had the stonewall on just the `rand-trim` job but by moving it to the global section you guarantee it is being set on every job. Are you happy that you understand why fio was complaining about bad headers? If so could you close this issue and if not could you continue asking questions...

**Comment by SamTheDev** [comment]
@sitsofe Makes perfect sense, thank you again :))

**Comment by ramesh416** [comment]
Is there a way i can use fio to load data first as one job and run verify on the same dir as part of another job. Use case i have is - 

1. load data, 
2. do some failures on my filesystem
3. Verify data which i loaded in step 1

**Comment by axboe** [comment]
Sure, just have your write part contain do_verify=0 and then create an identical job but with do_verify=1 and write patterns turned to reads. For instance, if you originally had rw=randwrite, then do rw=randread. Ditto for rw=write, rw=read instead. If you do that, you can verify at any later time.

**Comment by axboe** [comment]
See examples/surface-scan.fio for an example of a single job file that splits it up.
