### ISSUE TITLE
Fio 2.21 doesn't let run --profile=act failing for device-names

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#402]
I was trying to see the use the aerospike  profile with FIO 2.21 but it gives the below error. Looks like the issue with the --device-names option. 
![image](https://user-images.githubusercontent.com/19417434/28141882-64feb376-6713-11e7-8c60-4be492adeb51.png)

System: CentOS 7.2 , kernel 4.12 
FIO version : 2.21 
Command used : 
fio --profile=act --device-names=/dev/nvme0n1

**Comment by axboe** [comment]
Can you try current -git? Should be fixed there.

**Comment by akoundal** [comment]
Yes works now :).  thanks for a quick fix.

**Comment by axboe** [comment]
Thanks for reporting!
