### ISSUE TITLE
Trying to generate log files for job

### ISSUE THREAD

**Issue by eelife** [axboe/fio#404]
Hello I am new to fio, and I am trying to learn how to use the fio2gnuplot tool. I am trying to run the simple commands of:
```
write_bw_log=first-fio
write_iops_log=first-fio
```

But I cannot seem to get any file to appear. Here is an example of a run i have:
```
[global]
rw=randwrite
iodepth=4
ioengine=sync
directory=/data/local/tmp
filename=emmc.test.file

[randwrite]
fsync=1
direct=0
```

What mistake am I making?

**Comment by sitsofe** [comment]
@eelife Hi. fio2gnuplot is probably expecting the logs to have been created with [log_avg_msec](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-avg-msec)  - are you doing so?

**Comment by eelife** [comment]
I am not, what procedure should I go about to create logs?

**Comment by sitsofe** [comment]
@eelife did you follow the link in previous comment?

**Comment by eelife** [comment]
Oh didn't realize it was a link, woops. Okay, so I have to set that value in order to specify what period of time the logs should be specified for?

**Comment by sitsofe** [comment]
@eelife nearly - it specifies the window of time that each row in a log is averaged over . Also see [Log File Formats](http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats) for a slightly different phrasing of what it does.

**Comment by eelife** [comment]
Okay, I see that now. So I have to first create logs using log_avg_msec command? How do I go about doing that?

**Comment by eelife** [comment]
Okay I generated the log files. But 1 more issue, I am getting a no datablock named $1 issue when trying to graph the log files. Do you know what causes this error?

**Comment by sitsofe** [comment]
@eelife I stand corrected. I've just run
```
./fio --ioengine null --size=1000M --rate=5M --rate_process=poisson --write_bw_log=bb --name go --time_based --runtime=5s --bs=512
fio2gnuplot -g -p 'bb*.log'
xdg-open bb_bw.1-2Dsmooth.png
```

Can you include the information requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ? Further, after fio finishes running fio is it producing the appropriate *.log files?

**Comment by eelife** [comment]
Yes the appropriate log files are being generated, but I can only plot the latency (clat and lat, not slat oddly enough) graphs. The iops and bandwidth graphs are giving me the following errors. I ran the command below.

`fio2gnuplot -g -p '*iops.log' > iops_error_log.txt`
`fio2gnuplot -g -p '*bw.log' > bw_error_log.txt`


[iops_error_log.txt](https://github.com/axboe/fio/files/1153416/iops_error_log.txt)
[bw_error_log.txt](https://github.com/axboe/fio/files/1153418/bw_error_log.txt)

**Comment by sitsofe** [comment]
I'm afraid your version of fio is so old I can't comment much further. Any chance you can reproduce the problem with fio-2.99 / a git version of fio? If so can you give the full command line you ran fio with along with any job files?

**Comment by eelife** [comment]
Can i just clone the git repo and it replaces my current version?

**Comment by sitsofe** [comment]
Not quite. You will have to git clone, cd inside, make and then the easiest initial thing is to run fio from the current working directory.

**Comment by sitsofe** [comment]
You may also need to edit tools/plot/fio2gnuplot so gpm_dir points to the correct location (inside the clone) and then you can run the clone version of that too.

**Comment by eelife** [comment]
Hmm, I  downloaded the repo and "made" it, but my version of fio has still not changed.

**Comment by sitsofe** [comment]
Yes. cd inside then ./fio etc.

**Comment by eelife** [comment]
Okay, I ran the script from the pwd and generated more log files then transferred them to the directory with the fio2gnuplot script, but still the same errors appear.

"/usr/share/fio//graph2D.gpm line 25: no datablock named $1
`"/usr/share/fio//math.gpm line 25: no datablock named $1`

**Comment by sitsofe** [comment]
I've just run this:

```
./fio --ioengine null --size=1000M --rate_process=poisson --write_bw_log=bb --name go --time_based --runtime=5s --bs=512 --write_iops_log=bb --rate=1000M --log_avg_msec=50 --ramp_time=5s
tools/plot/fio2gnuplot -g -p 'bb*.log'
eog bb_iops.1-2Draw.png 
```

without issue. Did you edit `./fio2gnuplot` and change `gpm_dir ` in https://github.com/axboe/fio/blob/fio-2.99/tools/plot/fio2gnuplot#L388 and make it point to `~/Documents/fio-master/tools/plot` ?

**Comment by eelife** [comment]
Where do I change that in the script. I am sorry, I cant seem to find it.

**Comment by sitsofe** [comment]
@eelife - did you see the link I included to indicate the line to change in fio2gnuplot?

**Comment by eelife** [comment]
Hmm now I am getting another error after changing gpm_dir in lines 389 and 405 from (/usr/share/fio/ and /usr/logcal/share/fio/) respectively. 

The error is telling me that I have not installed fio correctly, which is confusing but I see where in the code it would be saying that. Does that mean I do not have the correct directory. I am using ~/Documents/fio-master/tools/plot for both gpm_dir . 

I really appreciate all of this help. Thank you.

**Comment by sitsofe** [comment]
@eelife I made a mistake - you won't be able to use `~` you'll have to use the full path.

**Comment by eelife** [comment]
Sweet success, finally. Thank you so much!

**Comment by sitsofe** [comment]
@eelife So you still have to tell us all - are you still seeing an issue? If the issue is gone could you close this issue please? Thanks!

**Comment by eelife** [comment]
No more issues, but titles are saying Blocksize = 0K for some reason?

**Comment by sitsofe** [comment]
@eelife because in the last example I gave you `bs` is less than 1KByte and the title is rounding down to the nearest KByte (i.e. `bs=4K` will look right). I think that's all I've got...

**Comment by sitsofe** [comment]
OK the other explanation is that the logs will just have an blocksize of zero if "windowed logging is enabled" as described at the end of http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats .

**Comment by eelife** [comment]
That fixed it. Once again, thanks alot!
