### ISSUE TITLE
smalloc failure with large numbers of files

### ISSUE THREAD

**Issue by dc-zachstanke** [axboe/fio#405]
When bench-marking using the opendir option on a directory with ~150,000 files within fio version 2.99 crashes with the following error message.

`fio: filesetup.c:1489: alloc_new_file: Assertion '0' failed.`

After diving into the source code and looking into it by changing smalloc.c:29 from 

`#define INITIAL_SIZE	16*1024*1024`

to 

`#define INITIAL_SIZE	16*1024*1024*16`

fio will continue to run, however the execution is very slow.

In this case fio is being run on ubuntu 16.04LTS on a system with 256GB of memory and two 8 core CPUs.

contents of my job file used.
```

[global]
time_based
ramp_time=30
runtime=900
iodepth=16
numjobs=8
refill_buffers
norandommap
group_reporting
rw=randrw
opendir=/NETWORK_DIRECTORY_HERE

[1:100]
bs=1024k
rwmixread=100
```

invoked using the command below

`fio --client=SERVER_IP test.fio`

on  the server side

`fio --server`

UPDATE:

Some more testing verifies that the issue is present when called locally using an appropriately modified version of the test file and the command 

`fio test.fio`

**Comment by sitsofe** [comment]
@dc-zachstanke How much can you remove from the job file that still shows the problem?

**Comment by dc-zachstanke** [comment]
After striping the job-file down to just 

```
[global]
opendir=/DIRECTORY_HERE

[1:100]
```

The problem still occurs both when running on a server and locally from an NVMe SSD.

The local output is as follows

```
fio: opendir added 173694 files
fio: smalloc OOM
fio: filesetup.c:1307: alloc_new_file: Assertion `0' failed.
Aborted (core dumped)
```

The server output is as below

```
fio: server listening on 0.0.0.0,8765
fio: filesetup.c:1489: alloc_new_file: Assertion `0' failed.

```

Server client

```
hostname=HOSTNAME, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-2.99, flags=1
client: host=IPADDR disconnected
```

**Comment by sitsofe** [comment]
I'm not surprised the assertion is hit given the sheer number of files but what about the slowness? Can you get further by using the [--alloc-size](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-alloc-size) (previous word links to the HOWTO) option?

**Comment by dc-zachstanke** [comment]
--alloc-size does not seem to help. I used as much as the full system memory available on the server (256GB).

**Comment by dc-zachstanke** [comment]
Just an update, it would appear the slowness when increasing the INITIAL_SIZE attribute is related to the metadata server being asked to get information about that many files one at a time.  When running locally the test takes only a few seconds to initialize however run identically on the server it takes ~3 minutes to add all the files, then ~30 minutes for the worker threads to begin generating a workload.  Is it possible to increase the queue depth fio uses during the setup?  The MDS server has additional performance available, it appears to be the latency of the 40Gb network that is limiting the speed of the setup.

**Comment by dc-zachstanke** [comment]
Going to close this issue because tweaking the initial size attribute fixed it.  It may be desirable to find a way to fix smalloc to scale correctly but is not a major issue.
