### ISSUE TITLE
why bandwidth exceeded SSD's max bandwidth when use libaio >= 4 io depth

### ISSUE THREAD

**Issue by dublio** [axboe/fio#406]
Hello,

I have a SSD, it's spec show seq-read: 2600MB/s, but when I use libaio with io depth >=4 , it almost get 3000MiB/s, I don't know why exceed it spec?

http://ark.intel.com/products/80995/Intel-SSD-DC-P3600-Series-2_0TB-2_5in-PCIe-3_0-20nm-MLC

my test parameter, as following:

#io_depth = 1 ,2, 4, 8, 16,  , ,128

fio \
--output=test.log \
-group_reporting=1 \
-ioengine=libaio \
-name=read \
-rw=read \
-filename=/dev/nvme0n1 \
-size=153G \
-direct=1 \
-bs=512k \
-numjobs=1 \
-iodepth=$io_depth \
-runtime=60

io_depth | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128

Bandwidth(MiB/s) | 1563 | 2477 | 2948 | 3012 | 3004 | 2983 | 2987 | 3015

**Comment by sitsofe** [comment]
@dublio This is more of a support question than a bug but do you know what block size the vendor was using when they stated 2600MB? Your block size is big at 512k...

**Comment by dublio** [comment]
@sitsofe when use libaio with io queue=1, and run more than 8 threads(8,12,14,18,22,,,40), it's bandwidth not exceed 2600MB/s. it also use 512K bs, seems meeting spec. So I want know why libaio with >=4 io depth reach 3000MB/s.

fio parameter:
#threads range from 1,2,4,8,12,16, ,,, 40

fio 
--output=test.log 
-group_reporting=1 
-ioengine=libaio 
-name=read 
-rw=read 
-filename=/dev/nvme0n1 
-size=153G 
-direct=1 
-bs=512k 
-numjobs=$threads
-iodepth=1
-runtime=60

test result:

thread | 1 | 2 | 4 | 8 | 12 | 16 | 20 | 24 | 28 | 32 | 36 | 40

Bandwidth(MiB/s) | 1564 | 1749 | 2434 | 2608 | 2606 | 2605 | 2601 | 2614 | 2606 | 2598 | 2596 | 2595

**Comment by dublio** [comment]
@sitsofe I have got bs and q-depth , I will sent it to maillist if I have more questions, thanks a lot.

**Comment by sitsofe** [comment]
@dublio you may also find this mailing list post useful: http://www.spinics.net/lists/fio/msg05201.html .
