### ISSUE TITLE
Random writes' bandwidth evolves differently for different disk's portion

### ISSUE THREAD

**Issue by SamTheDev** [axboe/fio#407]
I've tried to measure the evolution of the bandwidth in an NVMe disk when i write only a portion of the disk, so i wrote a simple script that basically do that:

> For write portion in {10,20...,100} %  
> |- Write the entire disk with 1s; 
> |- Write a portion% of the disk randomly using 128k bs;  #using fio
> |- Log the bandwidth each 50s
> End for 

My fio file looks like this:

```
[global]
ioengine=libaio
iodepth=256
size=X%
direct=1
do_verify=0
continue_on_error=all
filename=/dev/nvme0n1
randseed=1
[write-job]
rw=randwrite
bs=128k 
```

Logically the bandwidth should start from the best bandwidth (for 128k block size), which is around 1.3 GiB/s for my NVMe, then gets down till the written portion is met.
But this is not the case, the randwrites for 80%, 90% and 100% of the disk size start at a different bandwidth than the others!

![image](https://user-images.githubusercontent.com/2827220/28362904-97f53fdc-6c7e-11e7-80cd-df36ebbe748e.png)

If we have 10 identical cars with different fuel amount, shouldn't they all start at the same speed until the fuel is done !
Does fio take into consideration how much he will write and limit the bandwidth?!
Is this a normal fio functioning? Or am i missing something about how fio handles portion random writes?
Thank you.

**Comment by sitsofe** [comment]
@SamTheDev You're dealing with an SSD and as such the past has a great influence over the future and a smaller region increases the chances of I/O being closer to sequential. For example, are you doing a secure erase between each test? If not how do you know you're not suffering interference from the SSD having to do erases on later tests?

Unfortunately a GitHub issue is not a good place to discuss the ins and outs of SSD benchmarking. May I suggest you close this issue and try the mailing list (no guarantees but it's a wider readership)?

**Comment by SamTheDev** [comment]
@sitsofe Sorry about that, i will move the question to the mailing list. If you don't mind, i am also interested in your thoughts on the subject, i don't see how smaller region increases the chances of I/O being closer to sequential ! doesn't setting the size using a percentage (without using the offset ) means that fio will send commands **on the whole addressable disk space** using bs till that size is for filled  ?

**Comment by sitsofe** [comment]
@SamTheDev since you've been kind enough to close the issue here please ensure that your mailing list email also contains your latest question. When I see it arrive I'll try and post at least one reply.

**Comment by sitsofe** [comment]
(Conversation was continued over on http://www.spinics.net/lists/fio/msg06073.html ("Random writes' bandwidth evolves differently for different disk's portion").)

**Comment by SamTheDev** [comment]
@sitsofe , hello and sorry for showing up here again, this literally my last resort.

I have a simple question that I promise won’t take much of your time ( the mailing list doesn’t look like the right place for such questions :/), hoping for your kind help.

I want to test how a couple of Intel devices perform with a specific workload that contains mainly random 128k writes, but the random offsets must be generated using a **Fisher and Yates shuffle** algorithm (basically to make sure that there are zero collisions between requested offsets ).

So, i added an implementation to that random generator to fio, and added a “`get_next_Fisher_and_Yates_offset`” function to retrieve the next offset each time.

To quickly test that, i replaced the default **TAUSWORTHE** random offset function call, more precisely I’ve changed the[ `__get_next_rand_offset ` function](https://github.com/axboe/fio/blob/63463983ce10e9678c5ad309608630eea873b4df/io_u.c#L89)  from the **io_u.c** file to something like that:

```
//…
static int __get_next_rand_offset(struct thread_data *td, struct fio_file *f,
				  enum fio_ddir ddir, uint64_t *b,
				  uint64_t lastb)
{
	uint64_t r;

	if (td->o.random_generator == FIO_RAND_GEN_TAUSWORTHE ||
	    td->o.random_generator == FIO_RAND_GEN_TAUSWORTHE64) {

		r = __rand(&td->random_state);

		dprint(FD_RANDOM, "off rand %llu\n", (unsigned long long) r);

		//*b = lastb * (r / (rand_max(&td->random_state) + 1.0));   
                  b = get_next_Fisher_and_Yates_offset (…)                           // update
	} else {
		uint64_t off = 0;

 //….
```


Is that enough to replace the default random generator (for a quick test)??

PS: the reason i am asking is that after doing that, i am getting top performances each run, even on limited fully written device range. this doesn’t look right! :/

Here a sample of my test fio file:

> [global]
> ioengine=libaio
> iodepth=256
> io_size=256G
> size=1117G
> direct=1
> do_verify=0
> continue_on_error=all
> filename=/dev/nvme0n1
> randseed=29
> sync=1
> [write-job]
> rw=randwrite
> bs=128k
> 

I really appreciate your help, 🙇 
Thank you in advance.
Sam.

**Comment by axboe** [comment]
Fisher-yates is insanely inefficient for this purpose. See the lfsr option if you want a pseudo random cyclic generation, that doesn't include hitting the same block twice.

**Comment by SamTheDev** [comment]
@axboe thank you, i will check that out, and does that mean that tausworthe include hitting the same block twice ?

**Comment by axboe** [comment]
Tausworthe is just a normal random generator, it doesn't give you any guarantees on hitting every block exactly once in a range of 0..N. The random map tracks that for it. LFSR will give you that guarantee.

**Comment by sitsofe** [comment]
Second conversation was continued over on http://www.spinics.net/lists/fio/msg06230.html and http://www.spinics.net/lists/fio/msg06233.html .
