### ISSUE TITLE
about IOPS calculating

### ISSUE THREAD

**Issue by hasonhai** [axboe/fio#41]
Hi,
I run a test on my virtual machine with the latest release, the result looks normal for the throughput (58MBs) but IOPS is very high. The bandwidth is normal, because max bandwidth of my hard drive is around 115MB/s (from some benchmark website). As I know, my hard drive has 7200rpm, __it should have the maximum IOPS around 190 but Fio reported 20k__. Is this a bug from Fio?  

Here is the config file:
============================
ubuntu@vm1:~$ cat sequential-read.fio 
    ; sequence read of 4gb of data

    [sequence-read]
    rw=read
    size=4gb
    directory=/home/ubuntu/fiodata
    ioengine=libaio
    direct=1
    iodepth=16 

And here is the result:
================
ubuntu@vm1:~$ fio sequential-read.fio
    
    sequence-read: (g=0): rw=read, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
    fio-2.2.3
    Starting 1 process
    sequence-read: Laying out IO file(s) (1 file(s) / 4096MB)
    Jobs: 1 (f=1): [R(1)] [100.0% done] [80506KB/0KB/0KB /s] [20.2K/0/0 iops] [eta 00m:00s]
        sequence-read: (groupid=0, jobs=1): err= 0: pid=20158: Thu Jan  1 10:16:33 2015
        read : io=4096.0MB, bw=57875KB/s, iops=14468, runt= 72472msec
        slat (usec): min=6, max=8049, avg=13.45, stdev=51.91
        clat (usec): min=91, max=925638, avg=1087.67, stdev=3674.23
        lat (usec): min=121, max=925669, avg=1102.28, stdev=3674.53
        clat percentiles (usec):
         |  1.00th=[  322],  5.00th=[  852], 10.00th=[  956], 20.00th=[  996],
         | 30.00th=[ 1012], 40.00th=[ 1032], 50.00th=[ 1048], 60.00th=[ 1064],
         | 70.00th=[ 1080], 80.00th=[ 1144], 90.00th=[ 1272], 95.00th=[ 1320],
         | 99.00th=[ 1528], 99.50th=[ 2736], 99.90th=[ 7840], 99.95th=[ 9280],
         | 99.99th=[17536]
        bw (KB  /s): min=    4, max=81120, per=100.00%, avg=58117.17, stdev=6324.94
        lat (usec) : 100=0.01%, 250=0.11%, 500=4.45%, 750=0.19%, 1000=18.37%
        lat (msec) : 2=76.17%, 4=0.38%, 10=0.29%, 20=0.03%, 50=0.01%
        lat (msec) : 100=0.01%, 250=0.01%, 1000=0.01%
      cpu          : usr=8.42%, sys=20.69%, ctx=65164, majf=0, minf=43
      IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
         submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
         complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
         issued    : total=r=1048576/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
         latency   : target=0, window=0, percentile=100.00%, depth=16
    
    Run status group 0 (all jobs):
       READ: io=4096.0MB, aggrb=57874KB/s, minb=57874KB/s, maxb=57874KB/s, mint=72472msec, maxt=72472msec

    Disk stats (read/write):
       vda: ios=1048572/4, merge=0/1, ticks=962356/0, in_queue=962044, util=100.00%

I also have here several articles on calculating max IOPS for hard drive, if you want to take a look. 
* http://vmtoday.com/2009/12/storage-basics-part-i-intro/
* http://vmtoday.com/2009/12/storage-basics-part-ii-iops/
* http://don.blogs.smugmug.com/2007/10/08/hdd-iops-limiting-factor-seek-or-rpm/
*http://blog.aarondelp.com/2009/10/its-now-all-about-iops.html

Thank you very much!

**Comment by axboe** [comment]
You are doing sequential reads, which means that one 4kb issued IO by fio may be coalesced into more. For IOPS testing, random reads are normally what you would use. Additionally, I would guess there's some caching going on at the host end of that vda.

**Comment by hasonhai** [comment]
Hi,
I set direct to 1. Does it means that no buffer is used on the host? How can be any caching there? is there any other possible corner that reveals the caching? I know this is a stupid question, but i'm new to disk performance so I don't know where to dig into to understand the IOPS number. Thanks for your help!

**Comment by axboe** [comment]
There is no caching on the vda side (or driver or kernel), since it's O_DIRECT. But there could be on the other end of it. I'd start with making this a randread test and see if it's still that fast. If it is, the effect is definitely down to caching.
