### ISSUE TITLE
Averaged IOps Log File write results appear shifted compared to the reads

### ISSUE THREAD

**Issue by shimrot** [axboe/fio#410]
We noticed that when performing mixed read/write I/O, the averaged IOps log file results do not accurately reflect the average I/O rates compared to results from bus traces (other logs might be the same, but didn't verify).
The cause appears to be that the "write" sample results are shifted respect to the read results.

That is, given an example job:  
```
[global]
bs=4KB
direct=1
filename=/dev/sdb
ioengine=libaio
log_avg_msec=1000
norandommap=1
ramp_time=5s
randrepeat=0
runtime=10s

[RW-Job]
rw=randrw
write_iops_log=RW-Job
write_lat_log=RW-Job
```

The IOPs log is supposed to show the IOPs average over 1 second intervals. The IOPs log file produced: 
```
1000, 5089, 0, 0
2000, 5305, 0, 0
2000, 5182, 1, 0
3000, 5249, 0, 0
3000, 5255, 1, 0
4000, 5324, 0, 0
4000, 5218, 1, 0
5000, 5181, 0, 0
5000, 5180, 1, 0
6001, 5285, 0, 0
6001, 4938, 1, 0
7000, 5221, 0, 0
7000, 5273, 1, 0
8000, 5382, 0, 0
8000, 5397, 1, 0
9000, 5051, 0, 0
9000, 5261, 1, 0
10028, 5144, 1, 0
```

The write entries appear to be shifted, thus entry "2000, 5182, 1, 0" belongs at timestamp 1000 rather than 2000, and so on.

We discovered the issue during some product testing, comparing some IOMeter 1 second samples to the fio average IOps samples.  IOMeter shows a much larger peak and valley swing than the FIO log file results, when looking at the sum of the read and write per interval.

Below is a chart showing the issue.  The IOPs log (sum of read and write at each time value) at 1 second is smoother (green line) than when taking results from a bus trace and counting the number of ops which occur each second (orange line).   If we have fio record every op, and count the ops over 1 second intervals (blue line), the data matches our bus trace.
![image](https://user-images.githubusercontent.com/8331559/28440892-db13ed82-6d6d-11e7-8afa-837cf6fd8ce3.png)

The standard deviation for the bus trace and fio every op 1 sec averaged results is 42.1 and 41.5 respectively.  But the stddev for the fio average IOPs results (sum of read and write) is 24.0.  If we shift the writes up a slot, then the stddev for the fio average results ends up at 41.2.  Thus, it's a good bet that the write samples are truely shifted.

The 1 second average smoothing apparently occurs because the peaks and valleys for both reads and writes actually occur at the same time, but since the writes are shifted, the sum of the two result in smaller swings.

We experimented with FIO 2.15, 2.18 and 2.21 - all with same results.

So, I'm looking for help determining what is causing the write sample to receive a shifted time.  I tried looking at code (particularly calc_log_samples in stat.c - guessing that's the right place to look), but nothing clear to me.  

Thanks  
Kris

**Comment by sitsofe** [comment]
@shimrot apologies for not getting back sooner. This does sound strange and I suspect this will be tricky to track down but we know it is `log_avg_msec` related.

If you simplify your job as far as possible do you still see the offset problem? For example if you eliminate ramp_time, randrepeat and norandommap does the problem stay the same?

**Comment by shimrot** [comment]
@sitsofe - sorry I was not available for a while.  Without doing the extensive analysis, I ran the simple test without the parms as you suggested (with FIO 3.0):

```
[global]
bs=4KB
direct=1
filename=/dev/sdb
ioengine=libaio
log_avg_msec=1000
runtime=10s

[RW-Job]
rw=randrw
write_iops_log=RW-Job
write_lat_log=RW-Job
```

The log output is still the same - two reads at the beginning, two writes at the end.  Thus it still appears be an issue: 

**RW-Job_iops.1.log:**
```
1000, 5036, 0, 0
2000, 5300, 0, 0
2000, 5090, 1, 0
3000, 5285, 0, 0
3000, 5249, 1, 0
4000, 5211, 0, 0
4000, 5248, 1, 0
5000, 5058, 0, 0
5000, 5251, 1, 0
6000, 5252, 0, 0
6000, 5012, 1, 0
7000, 5076, 0, 0
7000, 5311, 1, 0
8000, 4882, 0, 0
8000, 5115, 1, 0
9000, 5096, 0, 0
9000, 4715, 1, 0
10030, 4951, 1, 0
```

Note that the latency log doesn't show the same read/write entry shift: 

**RW-Job_lat.1.log:**
```
1000, 129447, 0, 0
1000, 55913, 1, 0
2000, 130476, 0, 0
2000, 55659, 1, 0
3000, 131096, 0, 0
3000, 55608, 1, 0
4000, 131341, 0, 0
4000, 56751, 1, 0
5000, 135026, 0, 0
5000, 59195, 1, 0
6000, 130810, 0, 0
6000, 56057, 1, 0
7000, 137391, 0, 0
7000, 56290, 1, 0
8000, 143155, 0, 0
8000, 60151, 1, 0
9000, 138419, 0, 0
9000, 56358, 1, 0
10000, 138417, 0, 0
10000, 56425, 1, 0
```

Thanks

**Comment by shimrot** [comment]
Sorry - didn't mean to close

**Comment by sitsofe** [comment]
Thanks for the update and the simplification. Your example shows that the HOWTO has a mistake in it when referencing the data direction among other things.

The job below like yours demonstrates the same problem

```
[global]
bs=4KB
direct=1
ioengine=libaio
filename=/dev/nullb0
log_avg_msec=1000
runtime=5s
iodepth=1

[consecoffsetlog]
rw=randrw
write_iops_log=consecoffsetlog
write_bw_log=consecoffsetlog
write_lat_log=consecoffsetlog
```

As root the following were done:
```
modprobe -r null_blk 
modprobe null_blk completion_nsec=100000000 irqmode=2
./fio consecoffsetlog.fio
```

With  `log_avg_msec` this would give the following:
```
cat consecoffsetlog_iops.1.log
1000, 5, 0, 0
2000, 6, 0, 0
2000, 4, 1, 0
3000, 3, 0, 0
3000, 4, 1, 0
4000, 5, 0, 0
4000, 7, 1, 0
5000, 4, 0, 0
5000, 5, 1, 0
5040, 6, 1, 0
```

Without it you see results like this:
```
head -15 consecoffsetlog_iops.1.log
100, 1, 0, 4096
201, 1, 0, 4096
301, 1, 0, 4096
401, 1, 1, 4096
501, 1, 0, 4096
601, 1, 0, 4096
701, 1, 1, 4096
801, 1, 1, 4096
901, 1, 1, 4096
1001, 1, 0, 4096
1102, 1, 1, 4096
1202, 1, 0, 4096
1302, 1, 1, 4096
1402, 1, 0, 4096
1502, 1, 0, 4096
tail -15 consecoffsetlog_iops.1.log
3604, 1, 1, 4096
3704, 1, 1, 4096
3805, 1, 0, 4096
3905, 1, 0, 4096
4005, 1, 1, 4096
4105, 1, 1, 4096
4205, 1, 0, 4096
4305, 1, 1, 4096
4405, 1, 0, 4096
4505, 1, 0, 4096
4605, 1, 1, 4096
4706, 1, 1, 4096
4806, 1, 0, 4096
4906, 1, 1, 4096
5006, 1, 1, 4096
```

It is as the original values in one of the directions are being initially "forgotten" but are percolating through to the end...

**Comment by sitsofe** [comment]
@shimrot does https://github.com/sitsofe/fio/tree/shifted_logging resolve the problem?

**Comment by shimrot** [comment]
@sitsofe 
Thanks - sure looks promising.  My original quick simple job at the job gives the following log file, which shows paired reads and writes: 
```
1000, 5168, 0, 0
1000, 5173, 1, 0
2000, 5215, 0, 0
2000, 5076, 1, 0
3000, 5029, 0, 0
3000, 5156, 1, 0
3999, 5093, 0, 0
3999, 5163, 1, 0
5000, 5177, 0, 0
5000, 4975, 1, 0
6000, 4947, 0, 0
6000, 5077, 1, 0
7000, 5012, 0, 0
7000, 5032, 1, 0
7999, 4894, 0, 0
7999, 4932, 1, 0
8999, 5195, 0, 0
8999, 5142, 1, 0
10000, 5033, 0, 0
10000, 4998, 1, 0
```

Next week I'll should be able to repeat the complete test with a bus trace and compare results.
Thanks again.
Kris

**Comment by sitsofe** [comment]
@shimrot is it OK if I submit a pull request with the proposed fix?

**Comment by sitsofe** [comment]
I ended up submitting this one as https://github.com/axboe/fio/pull/443 after Jens OK'd it. My hesitation was because it took a large amount of concerted effort to diagnose and debug it (which is extra annoying given how small the suggested fix is) and I was unsure if it was correct.

There may be a few areas which can be "improved" (e.g. the Log File Formats section of the HOWTO needs updating and there are a couple of questions in https://github.com/axboe/fio/pull/443#issue-254759628 ) but this should be a good start.

@shimrot Regardless of when the patch goes mainline I'd still be interested to know your bus trace comparison result...

**Comment by shimrot** [comment]
I was able to verify that the "non-shifted" time periods for mixed loads now average together and represent the actual average of ops sent to the drive from a windows build of the latest 3.0+ main level clone.    Thank you @sitsofe - well done!

**Comment by sitsofe** [comment]
@shimrot You're welcome and thanks for the detailed (but well targeted) investigation.
