### ISSUE TITLE
Where can i get the Json+ format for FIO result?

### ISSUE THREAD

**Issue by Cnexlabzhengwang** [axboe/fio#413]
hi alex,
I am runing with FIO2.99 for json+ output_format, but i want to know the meanings of "Bins", where can i get the detail info for json/Json+ format for fio output?
See the attachment, please help.
[TestRand_w30_bs4096_threads1_iodepth1_nvme0n1.zip](https://github.com/axboe/fio/files/1175667/TestRand_w30_bs4096_threads1_iodepth1_nvme0n1.zip)

**Comment by vincentkfu** [comment]
In fio 2.99, the bins objects contains key, value pairs where the key is a latency duration and the value is the count of the number of IOs that required that latency for completion.

From your example::
`          "bins" : {
            "87552" : 1,
            "89600" : 1,
            "94720" : 1,
            "96768" : 1,
            "97792" : 1,
            "99840" : 1,
            "100864" : 2,
            "103936" : 6,
            "104960" : 534,
            "105984" : 5995,
            "107008" : 7529,
...
}
   `

One IO required 87552 ns to complete, 2 IOs required 100864ns to complete, 7529 IOs required 107008ns to complete.

The latency duration keys actually represent the midpoint of a variable width latency bin.  Full documentation is in stat.h

**Comment by sitsofe** [comment]
@Cnexlabzhengwang who is Alex?

At any rate @vincentkfu has added brief documentation to http://fio.readthedocs.io/en/latest/fio_doc.html#json-output and has also added a note that full documentation can be read inside `stat.h`. @Cnexlabzhengwang given this, would you agree this issue is resolved and if so can you close this issue? Thanks!

**Comment by Cnexlabzhengwang** [comment]
Hi wheeler,
Sorry, I means Axboe…

发件人: Sitsofe Wheeler [mailto:notifications@github.com]
发送时间: 2017年8月14日 15:37
收件人: axboe/fio <fio@noreply.github.com>
抄送: Zheng Wang <zwang@cnexlabs.com>; Mention <mention@noreply.github.com>
主题: Re: [axboe/fio] Where can i get the Json+ format for FIO result? (#413)


@Cnexlabzhengwang<https://github.com/cnexlabzhengwang> who is Alex?

At any rate @vincentkfu<https://github.com/vincentkfu> has added brief documentation to http://fio.readthedocs.io/en/latest/fio_doc.html#json-output and has also added a note that full documentation can be read inside stat.h. @Cnexlabzhengwang<https://github.com/cnexlabzhengwang> given this, would you agree this issue is resolved and if so can you close this issue? Thanks!

**Comment by Cnexlabzhengwang** [comment]
hi all,
Thank you all, i think this issue had been resolved.
