### ISSUE TITLE
Can 'io_size=' also accept a percentage value as input parameter?

### ISSUE THREAD

**Issue by wyysoft** [axboe/fio#419]
Since 'size=' and 'offset=' both accept a percentage value, what about 'io_size='?
It will be very helpful when trying to write 2X user capacity data without the effort to get and set real size.

**Comment by sitsofe** [comment]
@wyysoft wouldn't it be easier to use loops in that case?

**Comment by wyysoft** [comment]
@sitsofe 
Thanks for your reply and suggestion. But what if I need to write data of 1.2X or 1.5X disk size?
I can get disk size through command line and do some math to get desired io_size. So this thread is just about a tiny function request.

**Comment by Thanehood** [comment]
I too would like to see this option implemented.  For random testing where I need 100% LBA but only want to perform IO for a given percentage of the device to condition the device, --io_size=x% would come in handy.

**Comment by travisdowns** [comment]
It seems like `io_size` does accept % on current versions, but only up to 100%?

**Comment by vincentkfu** [comment]
This was added via https://github.com/axboe/fio/commit/8b38f40138047975ea7a59b9ce06681ffdd2c31d

The commit message includes a note regarding why it was capped at 100%. I will close this issue since it has been resolved but feel free to open another issue regarding the 100% limit.
