### ISSUE TITLE
Fio 2.2.3 parallel jobs of random read/write never finish if numjobs > 2

### ISSUE THREAD

**Issue by hasonhai** [axboe/fio#42]
Hi,
I have a config file like this:

    ; random read of 170mb of data
    [randomread]
    rw=randread
    size=170m
    directory=/home/ubuntu/fiodata
    ioengine=libaio
    direct=1
    iodepth=16 
    numjobs=3

When I ran the jobs, one of the jobs finished very quickly with high bandwidth. But others got very low bandwidth even after the high one already finished. When the job group reached nearly 100%, one or two last jobs run forever with bandwidth of 0KB. It only happen for random read and random write and when the number of parallel job larger than 2. I only test it with numjobs = 3,4,5. For larger value, I haven't tested them.
With the older version of fio, I also got similar phenomena:
*  one job got high throughput, others got low throughput even the high one had finished.
* last job took very long time (but still finish, not like this version, running forever)  
Thanks

**Comment by axboe** [comment]
I don't think this is a fio bug. The order in which they finish is out of fio's hands, that's down to the operating system and below. If some jobs are stuck and don't finish, you would have to investigate on the system side where they are stuck

**Comment by axboe** [comment]
axboe@lenny:/home/axboe/git/fio $ fio x
randomread: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
...
fio-2.1.14-33-gf8b8f
Starting 3 processes
Jobs: 3 (f=3)
randomread: (groupid=0, jobs=1): err= 0: pid=23241: Fri Jan  2 10:05:46 2015
  read : io=174080KB, bw=151374KB/s, iops=37843, runt=  1150msec
    slat (usec): min=3, max=9744, avg=25.47, stdev=62.78
    clat (usec): min=124, max=10147, avg=396.86, stdev=204.34
     lat (usec): min=128, max=10156, avg=422.41, stdev=210.69
    clat percentiles (usec):
     |  1.00th=[  209],  5.00th=[  255], 10.00th=[  282], 20.00th=[  314],
     | 30.00th=[  338], 40.00th=[  362], 50.00th=[  386], 60.00th=[  410],
     | 70.00th=[  434], 80.00th=[  466], 90.00th=[  516], 95.00th=[  564],
     | 99.00th=[  660], 99.50th=[  700], 99.90th=[  876], 99.95th=[ 1960],
     | 99.99th=[10048]
    bw (KB  /s): min=151984, max=153056, per=33.59%, avg=152520.00, stdev=758.02
    lat (usec) : 250=4.23%, 500=83.03%, 750=12.48%, 1000=0.19%
    lat (msec) : 2=0.03%, 4=0.01%, 10=0.02%, 20=0.02%
  cpu          : usr=3.48%, sys=29.57%, ctx=9536, majf=0, minf=25
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=43520/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=16
randomread: (groupid=0, jobs=1): err= 0: pid=23242: Fri Jan  2 10:05:46 2015
  read : io=174080KB, bw=153510KB/s, iops=38377, runt=  1134msec
    slat (usec): min=3, max=594, avg=25.10, stdev=41.36
    clat (usec): min=108, max=1653, avg=391.27, stdev=95.17
     lat (usec): min=125, max=1664, avg=416.45, stdev=97.30
    clat percentiles (usec):
     |  1.00th=[  205],  5.00th=[  258], 10.00th=[  282], 20.00th=[  314],
     | 30.00th=[  338], 40.00th=[  362], 50.00th=[  382], 60.00th=[  406],
     | 70.00th=[  430], 80.00th=[  462], 90.00th=[  510], 95.00th=[  556],
     | 99.00th=[  652], 99.50th=[  684], 99.90th=[  812], 99.95th=[  884],
     | 99.99th=[ 1640]
    bw (KB  /s): min=152688, max=157016, per=34.10%, avg=154852.00, stdev=3060.36
    lat (usec) : 250=4.24%, 500=84.01%, 750=11.57%, 1000=0.14%
    lat (msec) : 2=0.04%
  cpu          : usr=4.41%, sys=28.22%, ctx=9467, majf=0, minf=25
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=43520/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=16
randomread: (groupid=0, jobs=1): err= 0: pid=23243: Fri Jan  2 10:05:46 2015
  read : io=174080KB, bw=151770KB/s, iops=37942, runt=  1147msec
    slat (usec): min=3, max=1470, avg=25.29, stdev=42.05
    clat (usec): min=119, max=1666, avg=395.81, stdev=95.15
     lat (usec): min=133, max=1672, avg=421.19, stdev=97.69
    clat percentiles (usec):
     |  1.00th=[  211],  5.00th=[  258], 10.00th=[  286], 20.00th=[  318],
     | 30.00th=[  342], 40.00th=[  366], 50.00th=[  390], 60.00th=[  410],
     | 70.00th=[  438], 80.00th=[  470], 90.00th=[  516], 95.00th=[  556],
     | 99.00th=[  652], 99.50th=[  684], 99.90th=[  772], 99.95th=[  892],
     | 99.99th=[ 1640]
    bw (KB  /s): min=150752, max=156240, per=33.80%, avg=153496.00, stdev=3880.60
    lat (usec) : 250=3.98%, 500=83.30%, 750=12.56%, 1000=0.11%
    lat (msec) : 2=0.05%
  cpu          : usr=1.74%, sys=31.39%, ctx=9550, majf=0, minf=23
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=43520/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: io=522240KB, aggrb=454121KB/s, minb=151373KB/s, maxb=153509KB/s, mint=1134msec, maxt=1150msec

That's running your job here.

**Comment by hasonhai** [comment]
Thank you very much for your quick response. I will investigate more on the system side.

**Comment by axboe** [comment]
Please try 2.2.4 as well, it could actually be a fio bug that is fixed in 2.2.4.

**Comment by hasonhai** [comment]
I'm testing it now. Look likes it fixed the problem. My test ran very smooth. Thanks a lot!
