### ISSUE TITLE
FIO 2.18 and 2.21 reports wrong IOPS values in json+ per second format 

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#421]
Currently running random read workload I am seeing that JSON log file is showing unexpected IOPS/BW numbers. 
I am running it on Linux CentOS 7.3 kernel 4.8.6

Parameters used: 
[global]
name= Test file
ioengine=sync
direct=1
buffered=0
size=100%
randrepeat=0
time_based
ramp_time=120
norandommap
refill_buffers
group_reporting
filename=/dev/nvme0n1

[rd_rnd_qd_1_4k_1w]
stonewall
bs=4k
iodepth=1
numjobs=1
rw=randread
runtime=780

One of the ouput from the log file is showing this data which is not possible 
![image](https://user-images.githubusercontent.com/19417434/29099357-d27c879c-7c59-11e7-8aca-7f8beb11fbd7.png)

this is causing the wrong calculations for the data. Any support will be appreciated.

**Comment by sitsofe** [comment]
Do you still see the problem with the latest fio? Possibly linked to https://github.com/axboe/fio/issues/378 et al.

**Comment by akoundal** [comment]
I will be running it with the 2.99 today and share the data.

**Comment by akoundal** [comment]
@sitsofe  the first run came out fine i.e. no crazy values, i am doing a weekend run and update the status on Monday.

**Comment by sitsofe** [comment]
@akoundal note that the units that `io_bytes` was in was kbytes for older versions of fio (although it has now been switched to byte). Also note that presently `bw` is in kbytes (although this may change too - keep an eye on #422)

**Comment by akoundal** [comment]
@sitsofe  thanks for the headsup will keep an eye and share the status Monday (cheers)

**Comment by akoundal** [comment]
@sitsofe my back to back with fio 2.99 has shown promising results and 3 days of resting has not shown any crazy outliers in the run. I am running couple for last checks and then may be keep fingers crossed and close this request...

**Comment by akoundal** [comment]
current testing  has not shown any issues so  I am closing this for the time being @sitsofe
