### ISSUE TITLE
FIO IOPS Log and BW Log Issue

### ISSUE THREAD

**Issue by jrgruher** [axboe/fio#426]
Hi, I'm using FIO 3.0 on Ubuntu 16.10 with 4.12.7 kernel.  I'm running a 4KB random IO pattern against an Intel P3700 400GB NVMe SSD.  I'm trying to view the IOPS/BW over time using the write_bw_log and write_iops_log parameters.  FIO is writing the logs but the values in the logs don't align with the summary for the run.

Here is my INI:
[global]
bs=4k
rw=randread
numjobs=4
iodepth=32
thread=1
ioengine=libaio
direct=1
time_based=0
group_reporting=1
write_bw_log=joe
write_iops_log=joe
write_lat_log=joe
log_avg_msec=25000
[job00]
filename=/dev/nvme0n1

Some general data:

nvmf@nvmfjt01:~/jrg9/chandler$ lsblk|grep nvm
nvme0n1              259:0    0 372.6G  0 disk

nvmf@nvmfjt01:~/jrg9/chandler$ fio --version
fio-3.0

nvmf@nvmfjt01:~/jrg9/chandler$ uname -a
Linux nvmfjt01 4.12.7-041207-generic #201708160856 SMP Wed Aug 16 12:59:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I let this workload run until FIO stopped after about 18m15s.  Looked like a normal completion, no errors.

FIO reported 358,733 IOPS for the run, which is a bit below the drive spec but not unreasonable.  However, when I look at the four IOPS log output files, they report an average of about 60K IOPS over the run (that's total for all four - each individual log reports an average around 15K IOPS).  The first value in each log looks good, then all the remaining values seem way too low.  BW log shows similar behavior.

I also tried this in FIO 2.10 and had a variation of the same problem - the first value in each IOPS/BW log looked reasonable, and then all remaining IOPS/BW values in the logs were zero, despite lots of IO running through the whole run.

FIO result:
3;fio-3.0;job00;0;0;1562845536;1434935;358733;1089140;0;1013;1.381831;0.648783;21;5496;354.399721;187.404269;1.000000%=77;5.000000%=90;10.000000%=101;20.000000%=129;30.000000%=203;40.000000%=350;50.000000%=395;60.000000%=423;70.000000%=456;80.000000%=493;90.000000%=561;95.000000%=634;99.000000%=790;99.500000%=864;99.900000%=1089;99.950000%=1368;99.990000%=2736;0%=0;0%=0;0%=0;35;5497;355.901387;187.421156;34962;465113;3.600047%;51658.333609;25079.185236;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;12.897066%;15.847556%;200777107;0;639894;0.1%;0.1%;0.1%;0.1%;0.1%;100.0%;0.0%;0.00%;0.00%;0.00%;0.00%;0.01%;9.29%;23.25%;48.34%;17.59%;1.35%;0.14%;0.03%;0.01%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;nvme0n1;390692768;0;0;0;137555724;0;140813472;100.00%

Example IOPS log:
nvmf@nvmfjt01:~/jrg9/chandler$ cat joe_iops.1.log
24998, 115735, 0, 0
53199, 15963, 0, 0
77872, 15549, 0, 0
102552, 15221, 0, 0
127228, 14918, 0, 0
151904, 14644, 0, 0
176581, 14405, 0, 0
201256, 14143, 0, 0
225933, 13909, 0, 0
250608, 13731, 0, 0
275285, 13507, 0, 0
303486, 13314, 0, 0
328163, 13133, 0, 0
352838, 12957, 0, 0
377514, 12818, 0, 0
402191, 12689, 0, 0
426867, 12553, 0, 0
451543, 12424, 0, 0
476219, 12329, 0, 0
500895, 12253, 0, 0
525571, 11903, 0, 0
550247, 11810, 0, 0
578448, 11806, 0, 0
603125, 12142, 0, 0
627801, 12657, 0, 0
652477, 13081, 0, 0
677154, 13737, 0, 0
701832, 14671, 0, 0
726506, 16034, 0, 0
751182, 15229, 0, 0
775858, 13769, 0, 0
800534, 12680, 0, 0
825210, 11795, 0, 0
853411, 11012, 0, 0
878088, 10600, 0, 0
902764, 10203, 0, 0
927440, 9886, 0, 0
952116, 9631, 0, 0
976792, 9439, 0, 0
1001469, 9300, 0, 0
1026145, 8953, 0, 0
1050820, 8845, 0, 0
1075497, 8809, 0, 0
1089193, 8745, 0, 0

**Comment by jrgruher** [comment]
Here's one more example - tried to simplify the parameters in my INI, but no improvement.  You can see the overall IOPS reported by FIO and the over-time IOPS in the IOPS log file are way disconnected.


root@nvmfjt01:/home/nvmf/jrg9/chandler# cat 4k-rr-01.ini
[global]
bs=4k
rw=randread
numjobs=1
iodepth=128
ioengine=libaio
direct=1
runtime=30
write_iops_log=joe2
log_avg_msec=5000
[job00]
filename=/dev/nvme0n1


root@nvmfjt01:/home/nvmf/jrg9/chandler# fio 4k-rr-01.ini
job00: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-3.0
Starting 1 process
Jobs: 1 (f=1): [r(1)][100.0%][r=1595MiB/s,w=0KiB/s][r=408k,w=0 IOPS][eta 00m:00s]
job00: (groupid=0, jobs=1): err= 0: pid=2767: Thu Aug 17 10:34:09 2017
   read: IOPS=398k, BW=1555MiB/s (1630MB/s)(45.6GiB/30001msec)
    slat (nsec): min=824, max=117534, avg=1682.36, stdev=1290.45
    clat (usec): min=96, max=2899, avg=319.29, stdev=69.36
     lat (usec): min=97, max=2900, avg=321.08, stdev=69.39
    clat percentiles (usec):
     |  1.00th=[  221],  5.00th=[  243], 10.00th=[  255], 20.00th=[  269],
     | 30.00th=[  281], 40.00th=[  289], 50.00th=[  302], 60.00th=[  318],
     | 70.00th=[  334], 80.00th=[  363], 90.00th=[  412], 95.00th=[  453],
     | 99.00th=[  562], 99.50th=[  611], 99.90th=[  725], 99.95th=[  775],
     | 99.99th=[  906]
   bw (  MiB/s): min= 1081, max= 1594, per=99.96%, avg=1554.11, stdev=68.33, samples=59
   iops        : min=56293, max=383046, avg=65603.75, stdev=54419.77, samples=36
  lat (usec)   : 100=0.01%, 250=7.73%, 500=89.82%, 750=2.38%, 1000=0.07%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=32.51%, sys=67.50%, ctx=105, majf=0, minf=153
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=11941208,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=1555MiB/s (1630MB/s), 1555MiB/s-1555MiB/s (1630MB/s-1630MB/s), io=45.6GiB (48.9GB), run=30001-30001msec

Disk stats (read/write):
  nvme0n1: ios=11890654/0, merge=0/0, ticks=1923076/0, in_queue=1925204, util=99.69%


root@nvmfjt01:/home/nvmf/jrg9/chandler# cat joe2_iops.1.log
5000, 383046, 0, 0
10640, 56412, 0, 0
15576, 56410, 0, 0
20511, 56425, 0, 0
25446, 56394, 0, 0
30040, 57131, 0, 0


root@nvmfjt01:/home/nvmf/jrg9/chandler# fio --version
fio-3.0


root@nvmfjt01:/home/nvmf/jrg9/chandler# uname -a
Linux nvmfjt01 4.12.7-041207-generic #201708160856 SMP Wed Aug 16 12:59:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jrgruher** [comment]
Same behavior observed with default 4.8.0-59 kernel for Ubuntu 16.10.

**Comment by sitsofe** [comment]
(I suspect this isn't going to be easy to solve but all credit to you @jrgruher - this is a well written bug report!)

**Comment by jrgruher** [comment]
This feature seems to work in FIO 2.15:

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio 4k-rr-01-01-128.ini
job00: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=128
fio-2.15
Starting 1 thread
Jobs: 1 (f=1): [r(1)] [78.8% done] [1804MB/0KB/0KB /s] [462K/0/0 iops] [eta 00m:58s]
job00: (groupid=0, jobs=1): err= 0: pid=5341: Thu Aug 17 16:57:40 2017
  read : io=277967MB, bw=1789.6MB/s, iops=457984, runt=155375msec
    slat (usec): min=0, max=95, avg= 1.44, stdev= 0.91
    clat (usec): min=61, max=5168, avg=277.60, stdev=118.64
     lat (usec): min=62, max=5170, avg=279.12, stdev=118.63
    clat percentiles (usec):
     |  1.00th=[  129],  5.00th=[  155], 10.00th=[  173], 20.00th=[  197],
     | 30.00th=[  215], 40.00th=[  235], 50.00th=[  255], 60.00th=[  278],
     | 70.00th=[  306], 80.00th=[  342], 90.00th=[  406], 95.00th=[  470],
     | 99.00th=[  636], 99.50th=[  716], 99.90th=[ 1176], 99.95th=[ 2096],
     | 99.99th=[ 2896]
    lat (usec) : 100=0.12%, 250=47.54%, 500=48.64%, 750=3.31%, 1000=0.26%
    lat (msec) : 2=0.08%, 4=0.05%, 10=0.01%
  cpu          : usr=28.43%, sys=68.46%, ctx=736888, majf=0, minf=816
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=137.3%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued    : total=r=71159403/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=128
Run status group 0 (all jobs):
   READ: io=277967MB, aggrb=1789.6MB/s, minb=1789.6MB/s, maxb=1789.6MB/s, mint=155375msec, maxt=155375msec
Disk stats (read/write):
  nvme0n1: ios=97645100/0, merge=0/0, ticks=24504996/0, in_queue=24519280, util=99.95%

root@nvmfjt01:/home/nvmf/jrg9/chandler# cat joe1x128_iops.1.log
20001, 438712, 0, 0
39999, 455544, 0, 0
59999, 457418, 0, 0
79999, 462500, 0, 0
99999, 462728, 0, 0
119999, 462893, 0, 0
139999, 462508, 0, 0

root@nvmfjt01:/home/nvmf/jrg9/chandler# cat 4k-rr-01-01-128.ini
[global]
bs=4k
rw=randread
numjobs=1
iodepth=128
thread=1
ioengine=libaio
direct=1
ramp_time=60
norandommap=1
group_reporting=1
write_iops_log=joe1x128
log_avg_msec=20000
[job00]
filename=/dev/nvme0n1

root@nvmfjt01:/home/nvmf/jrg9/chandler# uname -a
Linux nvmfjt01 4.12.7-041207-generic #201708160856 SMP Wed Aug 16 12:59:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio --version
fio-2.15

**Comment by sitsofe** [comment]
@jrgruher OK that's a good start. If you're in a position to can you use git bisect (e.g.
```
git bisect start fio-3.0 fio-2.15
```
then test the commit it picks and then mark commit as good or bad see https://git-scm.com/docs/git-bisect ) to narrow down where the problem was introduced?

**Comment by jrgruher** [comment]
Pulling down different releases and testing, this feature works in FIO 2.15 through 2.20.  

Version 2.21 I can't seem to get a healthy build, every time I build it I get a segfault when I run it:
root@nvmfjt01:/home/nvmf/fio-fio-2.21# fio --version
Segmentation fault (core dumped)

Version 2.99 the feature is broken.  First data point looks reasonable and rest are always way too low.  I would assume there's a lot of changes from 2.20 to 2.99 due to the jump in version number?  I'll see if I can use the suggested tool to narrow it down further but that will be a new one for me.

Example workload on 2.20 and 2.99 shown below.

[global]
bs=4k
rw=randread
numjobs=1
iodepth=128
thread=1
ioengine=libaio
direct=1
runtime=20
time_based=1
norandommap=1
write_iops_log=joe1x128map
log_avg_msec=5000
[job00]
filename=/dev/nvme0n1

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio --version
fio-2.20

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio 4k-rr-01-01-128.ini
job00: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-2.20
Starting 1 thread
Jobs: 1 (f=1): [r(1)][100.0%][r=1324MiB/s,w=0KiB/s][r=339k,w=0 IOPS][eta 00m:00s]
job00: (groupid=0, jobs=1): err= 0: pid=14014: Fri Aug 18 13:25:06 2017
   read: IOPS=341k, BW=1332MiB/s (1396MB/s)(26.0GiB/20001msec)
    slat (usec): min=1, max=122, avg= 1.92, stdev= 1.22
    clat (usec): min=150, max=3245, avg=372.93, stdev=55.86
     lat (usec): min=151, max=3247, avg=374.94, stdev=55.95
    clat percentiles (usec):
     |  1.00th=[  302],  5.00th=[  314], 10.00th=[  322], 20.00th=[  334],
     | 30.00th=[  342], 40.00th=[  350], 50.00th=[  358], 60.00th=[  370],
     | 70.00th=[  382], 80.00th=[  402], 90.00th=[  442], 95.00th=[  486],
     | 99.00th=[  564], 99.50th=[  604], 99.90th=[  772], 99.95th=[  852],
     | 99.99th=[  964]
   bw (  MiB/s): min=  912, max= 1388, per=0.10%, avg=1332.06, stdev=79.08
    lat (usec) : 250=0.01%, 500=96.31%, 750=3.57%, 1000=0.11%
    lat (msec) : 2=0.01%, 4=0.01%
  cpu          : usr=29.74%, sys=70.22%, ctx=60, majf=0, minf=781
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=6818743,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128
Run status group 0 (all jobs):
   READ: bw=1332MiB/s (1396MB/s), 1332MiB/s-1332MiB/s (1396MB/s-1396MB/s), io=26.0GiB (27.9GB), run=20001-20001msec
Disk stats (read/write):
  nvme0n1: ios=6784098/0, merge=0/0, ticks=891048/0, in_queue=892632, util=99.54%

root@nvmfjt01:/home/nvmf/jrg9/chandler# cat joe1x128map_iops.1.log
5000, 336087, 0, 0
10000, 347660, 0, 0
15000, 340327, 0, 0

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio --version
fio-2.99

root@nvmfjt01:/home/nvmf/jrg9/chandler# fio 4k-rr-01-01-128.ini
job00: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-2.99
Starting 1 thread
Jobs: 1 (f=1): [r(1)][100.0%][r=1626MiB/s,w=0KiB/s][r=416k,w=0 IOPS][eta 00m:00s]
job00: (groupid=0, jobs=1): err= 0: pid=5141: Fri Aug 18 14:42:43 2017
   read: IOPS=420k, BW=1640MiB/s (1720MB/s)(32.0GiB/20001msec)
    slat (nsec): min=793, max=146660, avg=1649.16, stdev=1271.80
    clat (usec): min=107, max=1457, avg=302.72, stdev=76.60
     lat (usec): min=108, max=1458, avg=304.48, stdev=76.64
    clat percentiles (usec):
     |  1.00th=[  192],  5.00th=[  217], 10.00th=[  229], 20.00th=[  245],
     | 30.00th=[  258], 40.00th=[  273], 50.00th=[  285], 60.00th=[  302],
     | 70.00th=[  322], 80.00th=[  355], 90.00th=[  404], 95.00th=[  449],
     | 99.00th=[  570], 99.50th=[  619], 99.90th=[  734], 99.95th=[  775],
     | 99.99th=[  898]
   bw (  MiB/s): min= 1146, max= 1671, per=100.00%, avg=1640.54, stdev=89.13, samples=39
   iops        : min=58578, max=406300, avg=75604.09, stdev=73864.11, samples=22
    lat (usec) : 250=24.11%, 500=73.44%, 750=2.38%, 1000=0.07%
    lat (msec) : 2=0.01%
  cpu          : usr=29.64%, sys=70.36%, ctx=114, majf=0, minf=781
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=8397009,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128
Run status group 0 (all jobs):
   READ: bw=1640MiB/s (1720MB/s), 1640MiB/s-1640MiB/s (1720MB/s-1720MB/s), io=32.0GiB (34.4GB), run=20001-20001msec
Disk stats (read/write):
  nvme0n1: ios=8349113/0, merge=0/0, ticks=1521120/0, in_queue=1522948, util=99.57%

root@nvmfjt01:/home/nvmf/jrg9/chandler# cat joe1x128map_iops.1.log
5000, 406300, 0, 0
10635, 60051, 0, 0
15575, 60251, 0, 0
20047, 59138, 0, 0

**Comment by jrgruher** [comment]
This patch from the FIO mailing list fixes the issue:

diff --git a/time.c b/time.c
index edfe779..5e38aad 100644
--- a/time.c
+++ b/time.c
@@ -8,7 +8,7 @@ static unsigned long ns_granularity;

 void timespec_add_msec(struct timespec *ts, unsigned int msec)  {
-       unsigned long adj_nsec = 1000000 * msec;
+       unsigned long adj_nsec = 1000000UL * msec;

        ts->tv_nsec += adj_nsec;
        if (adj_nsec >= 1000000000) {

**Comment by sitsofe** [comment]
Because the suggested patch hasn't been added to mainline fio it's a bit premature to close this issue (but I don't have privileges to reopen this issue). I'll try and whip up a pull request...

**Comment by sitsofe** [comment]
@jrgruher OK I've made the https://github.com/sitsofe/fio/tree/timespec_add_msec_overflow branch as a proposed fix for this. Can you let me know if it works (and perhaps reopen this issue in the until something lands on mainline)?

**Comment by jrgruher** [comment]
Reopen until fixed in mainline.

**Comment by jrgruher** [comment]
Pulled down https://github.com/sitsofe/fio/archive/timespec_add_msec_overflow.zip and tested.  Result looks good, fix works.  Test output below.  Reopen until fixed in mainline.

nvmf@nvmfjt01:~/jrg9/chandler$ cat 4k-rr-01-01-128.ini
[global]
bs=4k
rw=randread
#rwmixread=100
numjobs=1
iodepth=128
thread=1
ioengine=libaio
direct=1
ramp_time=10
#runtime=20
time_based=0
#size=400G
norandommap=1
#exitall=1
#unified_rw_reporting=1
#group_reporting=1
#write_bw_log=joe1x128
write_iops_log=joe1x128map
#write_lat_log=joe1x128
log_avg_msec=25000
[job00]
filename=/dev/nvme0n1

nvmf@nvmfjt01:~/jrg9/chandler$ sudo fio 4k-rr-01-01-128.ini
job00: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=128
fio-3.0
Starting 1 thread
job00: No I/O performed by libaio, perhaps try --debug=io option for details?0s]
job00: (groupid=0, jobs=1): err= 0: pid=15664: Tue Aug 22 08:40:06 2017
   read: IOPS=408k, BW=1593MiB/s (1670MB/s)(358GiB/229948msec)
    slat (nsec): min=861, max=67374, avg=1694.83, stdev=1150.90
    clat (usec): min=53, max=5503, avg=311.71, stdev=99.32
     lat (usec): min=54, max=5505, avg=313.50, stdev=99.34
    clat percentiles (usec):
     |  1.00th=[  190],  5.00th=[  231], 10.00th=[  243], 20.00th=[  258],
     | 30.00th=[  269], 40.00th=[  281], 50.00th=[  293], 60.00th=[  306],
     | 70.00th=[  326], 80.00th=[  351], 90.00th=[  400], 95.00th=[  449],
     | 99.00th=[  578], 99.50th=[  652], 99.90th=[ 1467], 99.95th=[ 2278],
     | 99.99th=[ 2900]
   bw (  MiB/s): min= 1003, max= 1704, per=100.00%, avg=1600.24, stdev=60.40, samples=459
   iops        : min=388919, max=421094, avg=407531.11, stdev=13443.54, samples=9
  lat (usec)   : 100=0.16%, 250=14.21%, 500=83.11%, 750=2.24%, 1000=0.14%
  lat (msec)   : 2=0.08%, 4=0.07%, 10=0.01%
  cpu          : usr=30.49%, sys=69.04%, ctx=200391, majf=0, minf=1306
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=104.2%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=93760941,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128
Run status group 0 (all jobs):
   READ: bw=1593MiB/s (1670MB/s), 1593MiB/s-1593MiB/s (1670MB/s-1670MB/s), io=358GiB (384GB), run=229948-229948msec
Disk stats (read/write):
  nvme0n1: ios=97587634/0, merge=0/0, ticks=16756164/0, in_queue=16789516, util=100.00%


nvmf@nvmfjt01:~/jrg9/chandler$ cat joe1x128map_iops.1.log
24998, 396176, 0, 0
49996, 390242, 0, 0
74994, 388919, 0, 0
99992, 401202, 0, 0
125000, 411593, 0, 0
150000, 419488, 0, 0
175000, 421094, 0, 0
200000, 419559, 0, 0
225000, 419507, 0, 0

**Comment by sitsofe** [comment]
I added a Reported-by and Tested-by to this one and added a Reviewed-by for @vincentkfu so hopefully it's clear solving this one was a group effort :-)
