### ISSUE TITLE
IOPS and Bandwidth very high at the end

### ISSUE THREAD

**Issue by C4rst3n** [axboe/fio#427]
Hi, i ran a few tests on my raid systems and the bandwidth and iops climb very high at the end.

Here is my config file
>[global]
>ioengine=sync
>direct=1
>#sync=1
>rw=randrw
>size=2g
>refill_buffers=1
>[HDD_performance]
>write_bw_log=HDD_ohne_page
>write_iops_log=HDD_ohne_page
>write_lat_log=HDD_ohne_page
>filename=/mnt/HDD/testdatei
>[SSD_performance]
>stonewall
>write_bw_log=SSD_ohne_page
>write_iops_log=SSD_ohne_page
>write_lat_log=SSD_ohne_page
>filename=/mnt/SSD/testdatei

and here is an example output:
![compare-hdd-_bw-2draw](https://user-images.githubusercontent.com/31128367/29453360-a93e60e6-8409-11e7-98c0-56915de870a8.png)

As you can see the bandwidth is exploding at the end. Do you have an explanation for that? Or is it a bug in the measurement??

**Comment by akoundal** [comment]
check this : #421

**Comment by C4rst3n** [comment]
Well i need to miss that when i browsed the known issus. I just saw that i'm on 2.2.10. Is the latest version available via apt?? Or do i need to build on my own??

**Comment by sitsofe** [comment]
@C4rst3n you'll have to build it yourself. For reference we're up to fio-3.0 (see https://github.com/axboe/fio/releases for the different versions).

**Comment by C4rst3n** [comment]
thank you both @akoundal @sitsofe. It was really easy to compile fio.
There are just a few things going bad now.
i get an warning on iops rendering 
`Warning: empty y range [0:0], adjusting to [0:1]`
and the render plot is just a line.

And the other thing is that the letters (from the labels) after an _ are subscripted  HDD_rand_bw.log now.

And in the graph of the latency the y-value is called unknown. 

Pretty sure it's a kind of operator error.

Just wanted to show you some example images, but when i wanted to rerun my test it is instant finished and the log files have just one entry -.-

my test file:
>[global]
>ioengine=sync
>direct=1
>rw=randrw
>size=2g
>runtime=300
>refill_buffers=1
>[HDD_randrw_2g_5m]
>write_bw_log=HDD_rand
>write_iops_log=HDD_rand
>write_lat_log=HDD_rand
>filename=/mnt/HDD/fiofile
>[SSD_randrw_2g_5m]
>stonewall
>write_bw_log=SSD_rand
>write_iops_log=SSD_rand
>write_lat_log=SSD_rand
>filename=/mnt/SSD/fiofile

**Comment by sitsofe** [comment]
@C4rst3n - I'm going to guess your previous fio was older than 2.10 and since upgrading you've hit https://github.com/axboe/fio/issues/385 . See http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-avg-msec and the final paragraph of http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats .

**Comment by C4rst3n** [comment]
@sitsofe you were absolutely right :D Is there a pre defined pattern for latency? Because the y-axis is called unknown for latency while iops and bw are named correctly.

Finally i'd like you to have a look at my script here:
with the old fio it took around 30-60 to finish this, so i limited it to 5 minutes (=300seconds)
At first i did not use time_based=1 and for some reason the SSD had less values then the HDD although the SSDs needed more then 5 minutes previously with the old build of fio.
So i added time_based=1 to make sure that the test runs 5 minutes and has the same amount of values.
But now the script finished directly (even faster then ls) without doing anything. The log files have only one value in it. Do you know the problem about that??

>[global]
>ioengine=sync
>direct=1
>rw=randrw
>size=2g
>runtime=300
>time_based=1
>refill_buffers=1
>log_avg_msec=1000
>[HDD_randrw_2g_5m]
>write_bw_log=HDD_rand
>write_iops_log=HDD_rand
>write_lat_log=HDD_rand
>filename=/mnt/HDD/randrw
>[SSD_randrw_2g_5m]
>stonewall
>write_bw_log=SSD_rand
>write_iops_log=SSD_rand
>write_lat_log=SSD_rand
>filename=/mnt/SSD/randrw

**Comment by sitsofe** [comment]
@C4rst3n I've got no useful ideas this time I'm afraid. As always, it's good to include the information requested in https://github.com/axboe/fio/blob/fio-3.0/REPORTING-BUGS (e.g. version) and whether you're running with particular command line parameters in addition to your job file. Something also worth doing is seeing whether fio continues to finish far too quickly with just one job, then start removing as many options as possible such that the problem continues to happen but so you end up with the minimum number of options to make it happen.

**Comment by C4rst3n** [comment]
All right, so i'll figure out what option causes this bug and report it in an own issue with an title that fits more to the problem.

**Comment by vogelfreiheit** [comment]
#742 here, same issue in 3.8. Not sure what is the cause.
