### ISSUE TITLE
fio in json format provide no unit information compared to plain text

### ISSUE THREAD

**Issue by saurabhbpl** [axboe/fio#430]
Below are the two outputs from a single job. The json format outputted differs from simple text in following ways:-

1). There is no unit specified for "lat" and "bw" as against simple text which clearly specifies unit
2). The output dumps status for Trim, Read, Write even one operation is performed as against the simple text which output only data for specified operation.

Test: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=psync, iodepth=1
fio-2.20
Starting 1 process
{
  "fio version" : "fio-2.20",
  "timestamp" : 1502919927,
  "timestamp_ms" : 1502919927580,
  "time" : "Wed Aug 16 14:45:27 2017",
  "global options" : {
    "direct" : "1"
  },
  "jobs" : [
    {
      "jobname" : "Test",
      "groupid" : 0,
      "error" : 0,
      "eta" : 0,
      "elapsed" : 21,
      "job options" : {
        "name" : "Test",
        "rw" : "read",
        "bs" : "128k",
        "runtime" : "20s",
        "filename" : "/dev/sdak"
      },
      "read" : {
        "io_bytes" : 4995968,
        "bw" : 249785,
        "iops" : 1951.452427,
        "runtime" : 20001,
        "total_ios" : 39031,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 249,
          "max" : 25925,
          "mean" : 510.818350,
          "stddev" : 239.257488,
          "percentile" : {
            "1.000000" : 426,
            "5.000000" : 454,
            "10.000000" : 462,
            "20.000000" : 474,
            "30.000000" : 478,
            "40.000000" : 482,
            "50.000000" : 490,
            "60.000000" : 494,
            "70.000000" : 498,
            "80.000000" : 506,
            "90.000000" : 532,
            "95.000000" : 820,
            "99.000000" : 868,
            "99.500000" : 876,
            "99.900000" : 908,
            "99.950000" : 924,
            "99.990000" : 9152,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 249,
          "max" : 25925,
          "mean" : 511.019087,
          "stddev" : 239.253282
        },
        "bw_min" : 233984,
        "bw_max" : 257536,
        "bw_agg" : 0.097664,
        "bw_mean" : 249804.850000,
        "bw_dev" : 5690.008497
      },
      "write" : {
"io_bytes" : 0,
        "bw" : 0,
        "iops" : 0.000000,
        "runtime" : 0,
        "total_ios" : 0,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000,
          "percentile" : {
            "1.000000" : 0,
            "5.000000" : 0,
            "10.000000" : 0,
            "20.000000" : 0,
            "30.000000" : 0,
            "40.000000" : 0,
            "50.000000" : 0,
            "60.000000" : 0,
            "70.000000" : 0,
            "80.000000" : 0,
            "90.000000" : 0,
            "95.000000" : 0,
            "99.000000" : 0,
            "99.500000" : 0,
            "99.900000" : 0,
            "99.950000" : 0,
            "99.990000" : 0,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000
      },
      "trim" : {
        "io_bytes" : 0,
        "bw" : 0,
        "iops" : 0.000000,
        "runtime" : 0,
        "total_ios" : 0,
        "short_ios" : 0,
        "drop_ios" : 0,
        "slat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "clat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000,
          "percentile" : {
            "1.000000" : 0,
            "5.000000" : 0,
            "10.000000" : 0,
            "20.000000" : 0,
           "30.000000" : 0,
            "40.000000" : 0,
            "50.000000" : 0,
            "60.000000" : 0,
            "70.000000" : 0,
            "80.000000" : 0,
            "90.000000" : 0,
            "95.000000" : 0,
            "99.000000" : 0,
            "99.500000" : 0,
            "99.900000" : 0,
            "99.950000" : 0,
            "99.990000" : 0,
            "0.00" : 0,
            "0.00" : 0,
            "0.00" : 0
          }
        },
        "lat" : {
          "min" : 0,
          "max" : 0,
          "mean" : 0.000000,
          "stddev" : 0.000000
        },
        "bw_min" : 0,
        "bw_max" : 0,
        "bw_agg" : 0.000000,
        "bw_mean" : 0.000000,
        "bw_dev" : 0.000000
      },
      "usr_cpu" : 0.465000,
      "sys_cpu" : 3.915000,
      "ctx" : 39035,
      "majf" : 0,
      "minf" : 41,
      "iodepth_level" : {
        "1" : 100.000000,
        "2" : 0.000000,
        "4" : 0.000000,
        "8" : 0.000000,
        "16" : 0.000000,
        "32" : 0.000000,
        ">=64" : 0.000000
      },
      "latency_us" : {
        "2" : 0.000000,
        "4" : 0.000000,
        "10" : 0.000000,
        "20" : 0.000000,
        "50" : 0.000000,
        "100" : 0.000000,
        "250" : 0.010000,
        "500" : 72.752428,
        "750" : 21.698137,
        "1000" : 5.518690
      },
      "latency_ms" : {
        "2" : 0.000000,
        "4" : 0.010000,
        "10" : 0.015372,
        "20" : 0.010000,
        "50" : 0.010000,
        "100" : 0.000000,
        "250" : 0.000000,
        "500" : 0.000000,
        "750" : 0.000000,
        "1000" : 0.000000,
        "2000" : 0.000000,
        ">=2000" : 0.000000
      },
      "latency_depth" : 1,
      "latency_target" : 0,
      "latency_percentile" : 100.000000,
      "latency_window" : 0
    }
  ],
  "disk_util" : [
{
      "name" : "sdak",
      "read_ios" : 38803,
      "write_ios" : 0,
      "read_merges" : 0,
      "write_merges" : 0,
      "read_ticks" : 19045,
      "write_ticks" : 0,
      "in_queue" : 19036,
      "util" : 95.280044
    }
  ]
}

Test: (groupid=0, jobs=1): err= 0: pid=2218367: Wed Aug 16 14:45:27 2017
   read: IOPS=1951, BW=244MiB/s (256MB/s)(4879MiB/20001msec)
    clat (usec): min=249, max=25925, avg=510.82, stdev=239.26
     lat (usec): min=249, max=25925, avg=511.02, stdev=239.25
    clat percentiles (usec):
     |  1.00th=[  426],  5.00th=[  454], 10.00th=[  462], 20.00th=[  474],
     | 30.00th=[  478], 40.00th=[  482], 50.00th=[  490], 60.00th=[  494],
     | 70.00th=[  498], 80.00th=[  506], 90.00th=[  532], 95.00th=[  820],
     | 99.00th=[  868], 99.50th=[  876], 99.90th=[  908], 99.95th=[  924],
     | 99.99th=[ 9152]
   bw (  KiB/s): min=233984, max=257536, per=0.10%, avg=249804.85, stdev=5690.01
    lat (usec) : 250=0.01%, 500=72.75%, 750=21.70%, 1000=5.52%
    lat (msec) : 4=0.01%, 10=0.02%, 20=0.01%, 50=0.01%
  cpu          : usr=0.47%, sys=3.92%, ctx=39035, majf=0, minf=41
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=39031,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=244MiB/s (256MB/s), 244MiB/s-244MiB/s (256MB/s-256MB/s), io=4879MiB (5116MB), run=20001-20001msec

Disk stats (read/write):
  sdak: ios=38803/0, merge=0/0, ticks=19045/0, in_queue=19036, util=95.28%

**Comment by sitsofe** [comment]
1. It's kind of too late for lat to change without introducing a new field name but perhaps it could be documented in the HOWTO (any thoughts @vincentkfu?). bw is tricky, see https://github.com/axboe/fio/issues/422 - perhaps bw_bytes should be added...
2. Showing every direction even when they are not being used sounds minor...

**Comment by vincentkfu** [comment]
@sitsofe, sure, I can submit a patch with some barebones documentation for the json output.

**Comment by sitsofe** [comment]
@vincentkfu sounds like a plan.

**Comment by vincentkfu** [comment]
Current fio in fact provides unit information (nsec) for latency measurements in the json output.

**Comment by saurabhbpl** [comment]
@vincentkfu DO you mean the default unit is "nsec".?
If you look at the fio output pasted above the latency in simple text is displayed in usec and the value is same as deplayed by json output.

>> lat (usec): min=249, max=25925, avg=511.02, stdev=239.25
>>"lat" : {
"min" : 249,
"max" : 25925,
"mean" : 511.019087,
"stddev" : 239.253282
},

**Comment by vincentkfu** [comment]
@saurabhbpl your output is from fio-2.20. Output from fio-3.00 has units for the latency values in the json output.

**Comment by saurabhbpl** [comment]
Thanks @vincentkfu . I closed this bug.
