### ISSUE TITLE
fio intermittently fails to perform IO when --trigger-timeout, --trigger is specified

### ISSUE THREAD

**Issue by saurabhbpl** [axboe/fio#431]
We have observed that fio intermittently fails to perform IO when --trigger-timeout, --trigger is specified. It works fine when these options are removed.
[saurabha@devvm ~/temp/fio-fio-3.0] ./fio --client=ip6:client ~/temp/data_integrity.fio --verify_state_save=1 --verify_state_load=1 --verify=crc32c  --rw="write"
hostname=<hostname>, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.0, flags=1
<hostname> job0: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=128
<hostname> Starting 1 process
job0: (groupid=0, jobs=1): err= 0: pid=3009069: Fri Aug 18 17:25:04 2017
   read: IOPS=329, BW=342MiB/s (359MB/s)(3454MiB/10092msec)
    slat (usec): min=61, max=41362, avg=3004.19, stdev=1839.61
    clat (msec): min=91, max=546, avg=378.15, stdev=37.44
     lat (msec): min=95, max=549, avg=381.15, stdev=37.53
    clat percentiles (msec):
     |  1.00th=[  194],  5.00th=[  321], 10.00th=[  363], 20.00th=[  380],
     | 30.00th=[  380], 40.00th=[  380], 50.00th=[  384], 60.00th=[  384],
     | 70.00th=[  384], 80.00th=[  384], 90.00th=[  393], 95.00th=[  422],
     | 99.00th=[  472], 99.50th=[  502], 99.90th=[  531], 99.95th=[  542],
     | 99.99th=[  550]
   bw (  KiB/s): min=313344, max=374784, per=97.25%, avg=340823.60, stdev=13581.11, samples=20
   iops        : min=  306, max=  366, avg=332.60, stdev=13.19, samples=20
  lat (msec)   : 100=0.09%, 250=1.62%, 500=101.56%, 750=0.54%
  cpu          : usr=0.09%, sys=2.57%, ctx=3159, majf=0, minf=2
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.2%, 16=0.5%, 32=1.0%, >=64=238.1%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=3326,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=342MiB/s (359MB/s), 342MiB/s-342MiB/s (359MB/s-359MB/s), io=3454MiB (3622MB), run=10092-10092msec

Disk stats (read/write):
  nvme0n1: ios=63597/0, merge=0/0, ticks=5277006/0, in_queue=5289060, util=99.54%

[saurabha@devvm ~/temp/fio-fio-3.0] ./fio --trigger-timeout=5s --trigger=hostname --client=ip6:client ~/temp/data_integrity.fio --verify_state_save=1 --verify_state_load=1 --verify=crc32c  --rw="write"
hostname=hostname be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.0, flags=1
<hostname> job0: (g=0): rw=read, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=libaio, iodepth=128
<hostname> Starting 1 process
devvm26373 r=0k,w=0k][r=0,w=0 IOPS][eta 00m:17s]
<hostname> job0: No I/O performed by libaio, perhaps try --debug=io option for details?
devvm26373
client: host=hostname disconnected

**Comment by sitsofe** [comment]
@saurabhbpl does the https://github.com/sitsofe/fio/tree/verify_trigger branch resolve the issues you are seeing?

**Comment by saurabhbpl** [comment]
I will build fio from this specified branch and confirm the result as soon as I have some spare cycles.

**Comment by sitsofe** [comment]
@saurabhbpl any follow up on this one (I appreciate it's hard to find the time though)?

**Comment by sitsofe** [comment]
@saurabhbpl I've sent a pull request for the proposed fix but even if this issue is closed can you still post whether it resolves the problem you saw?

**Comment by saurabhbpl** [comment]
@sitsofe WIll check and let you know

**Comment by saurabhbpl** [comment]
The issue is fixed. Thanks for the fix @sitsofe

**Comment by saurabhbpl** [comment]
Any approximation when will be the next stable fio release I can expect the fixes.? I see fio-3.0 release last month.

**Comment by sitsofe** [comment]
@saurabhbpl fio-3.1 was released yesterday (see https://github.com/axboe/fio/releases ) but in general that sort of question is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.1/README#L58) .
