### ISSUE TITLE
About  "If a sample's MSB is greater than 23, it will be counted as 23"

### ISSUE THREAD

**Issue by football1222** [axboe/fio#433]
I'm confused with the setting in the title. As explained in stat.h:107 ** If a sample's MSB is greater than 23, it will be counted as 23, anything >8838608 will be count in the last group 18, which corresponds to [8838608,+inf] . 
However, I don't see any if-statement to ensure that. In **plat_val_to_idx()**,  if the "val"(nsec) is big enough, it will be mapped to group 19,20,21,... . This results goes into **add_clat_percentile_sample()**. Then there is check if IDX <= FIO_IO_U_PLAT_NR, which is 29X64, but not 18X64.
If 29 is the choice, then there's potential risk that in **plat_idx_to_val()**, "base" could exceed unsigned int.
So is there anything to ensure that which I didn't notice or something else? Thank you!

**Comment by vincentkfu** [comment]
The maximum return value of plat_val_to_idx() is (FIO_IO_U_PLAT_NR - 1). So any extremely large values will always be put in the final bucket: https://github.com/axboe/fio/blob/master/stat.c#L91

**Comment by vincentkfu** [comment]
FIO_IO_U_PLAT_GROUP_NR was originally 19 but this was increased to 29 when the unit was changed from usec to nsec:

https://github.com/axboe/fio/commit/d6bb626ef37d3905221ade2887b422717a07af09#diff-b1ee69fb5e2f7a77b82e6adfb0aa6492L111

**Comment by football1222** [comment]
If 29 is the new case, then I think there are two issues:
1. [](https://github.com/axboe/fio/blob/master/stat.h#L102) should be modified.
2. in **plat_idx_to_val()**, base was defined as unsigned int, but 
[](https://github.com/axboe/fio/blob/master/stat.c#L112)
/* Find the group and compute the minimum value of that group */
	error_bits = (idx >> FIO_IO_U_PLAT_BITS) - 1;
	base = 1 << (error_bits + FIO_IO_U_PLAT_BITS);
base would easily exceed 32bits when error_bits reaches 26(when Group Id >= 27), and it should be.
'cause Group 27 should cover [4294967296, 8589934591] if I'm not getting this wrong.
So in my opinion, base should be unsigned long long. 
Am I right about this? Thank you.
