### ISSUE TITLE
IOPS appears to be incorrectly represented in output

### ISSUE THREAD

**Issue by szaydel** [axboe/fio#448]
This has got to be something I am doing wrong. I noticed today that the `iops` line appears rather perplexing: `iops        : min=    1, max=    1, avg= 1.00, stdev= 0.00, samples=68653` .

I suppose it is possible that I am hitting some rare condition. So I figured it is worth raising an issue about this.

```
Jobs: 1 (f=8): [m(1)][100.0%][r=131MiB/s,w=302MiB/s][r=2930,w=6591 IOPS][eta 00m:00s]
r=gauss-70%-write: (groupid=0, jobs=1): err= 0: pid=27: Mon Sep  4 14:57:49 2017
   read: IOPS=4477, BW=201MiB/s (211MB/s)(3087MiB/15334msec)
    slat (nsec): min=535, max=846640, avg=3212.50, stdev=8611.98
    clat (nsec): min=1002, max=9001.3k, avg=233226.16, stdev=398236.09
     lat (usec): min=6, max=9002, avg=236.44, stdev=398.08
    clat percentiles (usec):
     |  1.00th=[    7],  5.00th=[   11], 10.00th=[   23], 20.00th=[   68],
     | 30.00th=[  101], 40.00th=[  126], 50.00th=[  155], 60.00th=[  186],
     | 70.00th=[  225], 80.00th=[  281], 90.00th=[  392], 95.00th=[  627],
     | 99.00th=[ 1942], 99.50th=[ 2868], 99.90th=[ 5080], 99.95th=[ 6456],
     | 99.99th=[ 7898]
   bw (  KiB/s): min=  529, max=56839549, per=100.00%, avg=512615.25, stdev=856649.51, samples=68653
   iops        : min=    1, max=    1, avg= 1.00, stdev= 0.00, samples=68653
  write: IOPS=10.4k, BW=466MiB/s (489MB/s)(7153MiB/15334msec)
    slat (nsec): min=431, max=440581, avg=3278.19, stdev=7092.23
    clat (usec): min=8, max=22789, avg=1429.59, stdev=1603.80
     lat (usec): min=14, max=22790, avg=1432.86, stdev=1603.24
    clat percentiles (usec):
     |  1.00th=[  100],  5.00th=[  149], 10.00th=[  182], 20.00th=[  247],
     | 30.00th=[  367], 40.00th=[  586], 50.00th=[  898], 60.00th=[ 1385],
     | 70.00th=[ 1778], 80.00th=[ 2057], 90.00th=[ 3490], 95.00th=[ 4359],
     | 99.00th=[ 8094], 99.50th=[ 9241], 99.90th=[11863], 99.95th=[13173],
     | 99.99th=[16450]
   bw (  KiB/s): min=  317, max=3644128, per=16.28%, avg=77782.68, stdev=112711.03, samples=158883
   iops        : min=    1, max=    1, avg= 1.00, stdev= 0.00, samples=158883
  lat (usec)   : 2=0.01%, 4=0.01%, 10=1.45%, 20=1.42%, 50=2.02%
  lat (usec)   : 100=4.66%, 250=27.40%, 500=16.78%, 750=7.07%, 1000=5.14%
  lat (msec)   : 2=19.24%, 4=10.31%, 10=4.30%, 20=0.20%, 50=0.01%
  cpu          : usr=103.44%, sys=210.24%, ctx=532902, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=99.9%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=68653,158883,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=201MiB/s (211MB/s), 201MiB/s-201MiB/s (211MB/s-211MB/s), io=3087MiB (3237MB), run=15334-15334msec
  WRITE: bw=466MiB/s (489MB/s), 466MiB/s-466MiB/s (489MB/s-489MB/s), io=7153MiB (7500MB), run=15334-15334msec
```

This is what I am running with, only difference here is stripped out comments for brevity.
```
[global]
ioengine=solarisaio
rw=randrw
direct=0
fallocate=none
numjobs=${NUMJOBS}
nrfiles=8
filename_format=data$filenum
directory=/storage/${POOL}/fio
thread
per_job_logs=0
write_bw_log=gauss10-rand70
write_iops_log=gauss10-rand70
group_reporting

[r=gauss-70%-write]
rwmixread=30 ; read % of mixed workload, where write = 100 - rwmixread
random_distribution=normal:10
percentage_random=70
bssplit=4k/10:8k/10:16k/20:32k/30:64k/10:128k/20
buffer_pattern=0x0638f227
io_size=10G
iodepth=16
```

**Comment by sitsofe** [comment]
@szaydel Which version of fio?

**Comment by sitsofe** [comment]
@szaydel another thing that will help is if you can cut the job down to the minimum options that still show the problem (e.g. remove group_reporting etc).

**Comment by sitsofe** [comment]
Hang on, have you seen the last paragraph of http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats ?

**Comment by szaydel** [comment]
That last one has got to be it. I am going to test this theory first and if not, then will strip the job down. But sounds like you hit the nail on the head.

**Comment by szaydel** [comment]
Yep, that was it alright. Reading is fundamental as they say. Thanks @sitsofe!

This did make me think about the label iops though. Since, if the value is aggregated on a number that is not necessarily 1000ms, technically, this is not really iops at least by the definition of an IOPS where the PS implies per-second. I should have a look at the source to make sure I fully grok how they are computed though before speaking.

At any rate, I think this one is resolved! Thank you @sitsofe.

**Comment by sitsofe** [comment]
@szaydel You're welcome. For anyone stumbling across this issue in the future here's the text that we're referring to and that @szaydel was testing:

> Fio defaults to logging every individual I/O. When IOPS are logged for individual I/Os the value entry will always be 1. 

@szaydel you're not the first one to be caught by this but people usually only notice it within the IOPS log itself rather than in the summary that fio prints (which threw me off initially too). I'm starting to wonder if the change I was thinking of making in https://github.com/sitsofe/fio/commit/ada4bafffb67c3f64f6a09d3a4ebc36e58ea286e where the text about "IOPS recorded as 1" is moved to the `write_iops_log` section is going to make this less prominent. What are your thoughts on that commit? 

FWIW, I'd argue that it's not unusual for IOPS to be calculated using I/Os collected over "non-second" periods. For example, people to count total I/Os done across some task's lifetime and then divide by the number of seconds in that lifetime and report that as IOPS  - it's a form of average after all.

Finally if you feel your issue is resolved could you close this issue? Thanks!

**Comment by szaydel** [comment]
I think that text is actually a significant improvement. This is a out of sight out of mind situation and passing this knowledge in one place likely would have reduced the chance that I experienced this and started to wonder. So, def. +1.
