### ISSUE TITLE
zone_size > zone_range leads to incorrect zoning

### ISSUE THREAD

**Issue by gvkovai** [axboe/fio#450]
Tried to do 3x amount of IO per zone and hence had the following config. Expectation was 9M worth of IO done in each 3M size of the zone. I.e., each zone would be read thrice before moving to next zone. The actual result shown in pic. See pic attached. IO continues (increments offset) until end of zone_size instead of zone_range. zone_skip=1M became ineffective as skipped area also read.

> $ ./fio --version
fio-3.0

> [global]
ioengine=libaio
direct=1
time_based
disk_util=0
continue_on_error=all
rate_process=poisson
write_iolog=offsetlog
[db-dss1]
bs=8K
filesize=524288M
zonesize=9M
zonerange=3M
zoneskip=1M
filename=/dev/sdb
rw=read
iodepth=1
rate_iops=100

> sudo ./fio --runtime 120 --debug=file,io,blktrace --write_iops_log=/tmp/IOPS --write_lat_log=/tmp/LAT --status-interval=10 --output=/tmp/fio.out --output-format=json <above.fio>

Y Axis = Nth IO

![image](https://user-images.githubusercontent.com/27024474/30082842-3293e3bc-925a-11e7-9df5-5d1bccbffe57.png)

![image](https://user-images.githubusercontent.com/27024474/30082890-69c6b008-925a-11e7-9ad8-7ec6adf6b022.png)

Affecting code is in io_u.c: static int get_next_seq_offset...
It's using io_size instead of zone_range.

**Comment by sitsofe** [comment]
I admit I've never known the difference between zonesize and zonerange. The HOWTO says this

> zonesize=int
> Divide a file into zones of the specified size. See zoneskip.
>
> zonerange=int
> Give size of an I/O zone. See zoneskip.
>
> zoneskip=int
> Skip the specified number of bytes when zonesize data has been read. The two zone options can  be used to only do I/O on zones of a file.

It seems weird how only zonerange and zoneskip refer to each other. However digging down on zonerange gets to https://github.com/axboe/fio/commit/ed33585509a97c4a65e46967cb49419b6a4f8870 whose commit message says:

> This also adds a 'zonerange' configuration option which may be too ambiguous
and is subject to potential renaming in the future.
>
> When doing random I/O, it is beneficial to be able to specify how large the
addressible space is in the zone, while specifying a different metric for
how much data to read from that zone (i.e., how many samples to take from each
zone). When 'zonerange' is not specified, it defaults to be equal to the
'zonesize' option. When both are specified, 'zonerange' indicates the
size of the zone while 'zonesize' indicates the quantity of data to read from
each zone.

This text matches the issue's expectation so this problem sounds genuine.

**Comment by gvkovai** [comment]
Made a patch to fix this issue:
[fio_450.patch.gz](https://github.com/axboe/fio/files/1282773/fio_450.patch.gz)

Same test was run and this fixes seq-io. Let me know if there are comments.

![image](https://user-images.githubusercontent.com/27024474/30135839-8882270e-932a-11e7-958f-15c805e5c3c6.png)

![image](https://user-images.githubusercontent.com/27024474/30135869-a81f2620-932a-11e7-80b9-4851be9e8903.png)

**Comment by sitsofe** [comment]
@gvkovai hey that's great! A few comments:

Could you use the PRIu64 macros for print uint64_t values (see https://github.com/axboe/fio/blob/a1d5a6b8a67dfc0f45d353c05d7a5abad3767976/engines/glusterfs.c#L168 for such an example)

You've got some trailing whitespace after one of the comment lines.

I also can't help wondering if you need more guards to not trigger these checks when zoning isn't been used. Does this also handle random I/O within the zone (do I have to fill the zone uniformly three times over)?

**Comment by sitsofe** [comment]
@gvkovai PS: you may want to use a Github gist (https://github.com/axboe/fio/issues/356#issuecomment-309346987 ) for patches that you want to refer to in github comments where you don't have a repo)

**Comment by gvkovai** [comment]
random has an issue with the suggested fix (without the fix also, it has an issue):

Exact same config with rw=randread and 'norandommap' is not set.

![image](https://user-images.githubusercontent.com/27024474/30216359-c3da43a2-9480-11e7-873e-8e1ac00ccc33.png)

![image](https://user-images.githubusercontent.com/27024474/30216421-f238593c-9480-11e7-89fb-73c91ee7be0e.png)

When 'norandommap' is set, it works as expected.

![image](https://user-images.githubusercontent.com/27024474/30216537-542e6582-9481-11e7-95d4-5e6f22ac503e.png)

![image](https://user-images.githubusercontent.com/27024474/30216643-a520b670-9481-11e7-8532-8e69440f9932.png)

**Comment by gvkovai** [comment]
Fix zoning issue with seq-io and randommap issue

    The case of zonerange < zonesize scenario was not handled
    correctly earlier. When zonesize > zonerange, IO must continue
    in the same zonerange of the size zonesize for seq-io.

    For random io, zonesize > zonerange leads to sequential io
    after first zonerange size of io is done when 'norandommap'
    is not set. In this case, map needs to be reset for every
    zonerange size of IO on a zone.

Please let me know if there are any comments:
[https://gist.github.com/gvkovai/2a71a38fb5be92f4072c5edf106817d9](url)

I have got this fixed for both random and seq. Verified with both 'norandommap' set as well as not set.

The following are with the above fix and 'norandommap' not set.

![image](https://user-images.githubusercontent.com/27024474/30219201-552a944e-9489-11e7-86b3-9a4e7aa67669.png)

![image](https://user-images.githubusercontent.com/27024474/30219237-72a8f394-9489-11e7-9fc8-6dd2195abf7b.png)

**Comment by sitsofe** [comment]
Wow!

**Comment by sitsofe** [comment]
Unfortunately the gist link is 404...

**Comment by sitsofe** [comment]
Ok text of the link is different to the link it goes to. Hopefully https://gist.github.com/gvkovai/2a71a38fb5be92f4072c5edf106817d9 works.

**Comment by sitsofe** [comment]
@gvkovai regarding getting your patch into mainline fio: which of the following would you like to do?
1. Submit a git style patch to Jens/the fio mailing list (possibly via email but I suspect if you updated the gist to include the full git patch headers that could be made to work)?
2. Submit a patch to Jens via a pull request from a cloned and updated fio repo on Github?
3. Create a git style patch but have me submit it?
4. Something else?
