### ISSUE TITLE
Low FIO measurements compared to other benchmark tool btest

### ISSUE THREAD

**Issue by Bennamer** [axboe/fio#456]
Hi, I running FIO benchmark on Multiple NVMe SSDs, I get lower performance than running the same workload with Btest. Top shows that both applications are running on ~the same amount of cores but Btest utilizes the cores much higher. 
In FIO I get 1.773M IOps but running btest I get 2.39M IOps
Do you have any idea what is the different btw the two tools, why and how to configure fio in order to show higher performance? this was the same problem with SAS drives not only NVMe.

Btest output:
[root@compute2 FIO]# btest -T 32 -t 3600 -r 1 -w 16 -b 4k -a 4k -D R 100 /dev/nvme105n1 /dev/nvme106n1
Diff report interval 1 sec
AIO implies direct IO
Use AsyncIO with window size of 16 requests per thread
IO Block size is 4096
IO alignment size is 4096
Use async IO mode
Use pure random IO
Generate 100% reads, the rest will be writes
32 threads are ready, starting test at Tue Sep 12 06:12:09 2017
Total: 11.617 seconds, 2394777.500 iops, avg latency 427 usec, bandwidth 9578496 KB/s, errors 0, total ops 27820001
Total: 11.617 seconds, 51326 max_latency, hiccups levels: <1ms: 27375927 1ms: 201753 2-10ms: 199797 11-50ms: 42522 51-100ms: 2 >100ms: 0

FIO param:
[global]
name=4k RdRnd IOdepth16 job32
filename=/dev/nvme14n1;/dev/nvme15n1
ioengine=libaio
direct=1
bs=4k
rw=randrw
rwmixread=100
iodepth=16
numjobs=32
size=100%
loops=2
group_reporting
[job1]

Running fio with the above param I get: 1.773M IOps
[root@compute2 FIO]#fio global_fio2
job1: (g=0): rw=randrw, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
...
fio-2.2.10
Starting 32 processes
^Cbs: 32 (f=32): [r(32)] [2.2% done] [6926MB/0KB/0KB /s] [1773K/0/0 iops] [eta 07m:58s]
fio: terminating on signal 2

job1: (groupid=0, jobs=32): err= 0: pid=11726: Tue Sep 12 06:12:41 2017
  read : io=68659MB, bw=6908.6MB/s, iops=1768.5K, runt=  9939msec
    slat (usec): min=1, max=3644, avg= 3.48, stdev= 4.19
    clat (usec): min=19, max=10395, avg=284.85, stdev=194.21
     lat (usec): min=57, max=10400, avg=288.41, stdev=194.27
    clat percentiles (usec):
     |  1.00th=[  115],  5.00th=[  131], 10.00th=[  145], 20.00th=[  165],
     | 30.00th=[  187], 40.00th=[  209], 50.00th=[  233], 60.00th=[  262],
     | 70.00th=[  298], 80.00th=[  354], 90.00th=[  466], 95.00th=[  612],
     | 99.00th=[ 1096], 99.50th=[ 1336], 99.90th=[ 1960], 99.95th=[ 2256],
     | 99.99th=[ 3120]
    bw (KB  /s): min=201832, max=237608, per=3.13%, avg=221106.75, stdev=4450.47
    lat (usec) : 20=0.01%, 50=0.01%, 100=0.06%, 250=56.12%, 500=35.47%
    lat (usec) : 750=5.44%, 1000=1.60%
    lat (msec) : 2=1.22%, 4=0.09%, 10=0.01%, 20=0.01%
  cpu          : usr=8.57%, sys=30.54%, ctx=9923423, majf=0, minf=29995
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=17576749/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: io=68659MB, aggrb=6908.6MB/s, minb=6908.6MB/s, maxb=6908.6MB/s, mint=9939msec, maxt=9939msec

Disk stats (read/write):
  nvme14n1: ios=17351582/0, merge=0/0, ticks=4864526/0, in_queue=5171474, util=100.00%

Many thanks in advance
Eli

**Comment by axboe** [comment]
You start 16 jobs/threads, and each job is reading from both devices. That's not optimal. This would be better:

```
[global]
name=4k RdRnd IOdepth16 job32
ioengine=libaio
direct=1
bs=4k
rw=randrw
rwmixread=100
iodepth=16
numjobs=32
size=100%
loops=2
group_reporting

[job1]
filename=/dev/nvme14n1

[job2]
filename=/dev/nvme15n1
```

and/or change the numjobs to 16 as well, if you want to retain the same number of jobs.

**Comment by axboe** [comment]
That's a start. There are various other ways you can reduce the overhead as well. You could use norandommap and/or random_generator=lfsr. Fio also captures more detailed latency information by default.

**Comment by Bennamer** [comment]
Great!!! That was quick, thanks for the answer, a very good start, indeed, 
splitting to 4 jobs on 4 different volumes I get 4KBs 2.35M IOps and running on 1K BS I get 4.3M Iops,

many thanks,  :)
Eli

**Comment by sitsofe** [comment]
@Bennamer Sounds like good news. If your issue is resolved can you close this issue?
