### ISSUE TITLE
No I/O performed by libaio error with --io_submit_mode=offload set

### ISSUE THREAD

**Issue by brschwartz** [axboe/fio#458]
Running the following job file with --io_submit_mode=offload set will
give a 'No I/O performed by libaio' error

Using the latest FIO version (fio-3.0-52-gc6fa)

sudo fio --name=test --filename=/dev/sda --rw=randread --size=1M --bs=128k,64k --ioengine=libaio --io_submit_mode=offload

With debug=io set, FIO is trying to submit a zero-length read request:

io       29653 io complete: io_u 0x55b3e49ed140: off=393216/len=131072/ddir=0io       29653 //dev/sdaio       29653
io       29653 fill_io_u: io_u 0x55b3e49ed140: off=393216/len=0/ddir=0io       29653 //dev/sdaio       29653
io       29653 get_io_u: zero buflen on 0x55b3e49ed140
io       29653 get_io_u failed
io       29653 io_u 0x55b3e49ed140, setting file failed
io       29653 get_io_u failed
io       29653 close ioengine libaio
io       29653 free ioengine libaio
io       29653 close ioengine libaio
io       29653 free ioengine libaio

**Comment by axboe** [comment]
Interesting test case. I pushed a fix for this, please try current -git and report back.

**Comment by brschwartz** [comment]
Everything looks good on my end.  Thanks!
