### ISSUE TITLE
Combining --ramp_time and --io_submit_mode=offload causes clat stats to be set to 0's

### ISSUE THREAD

**Issue by brschwartz** [axboe/fio#459]
Using the latest FIO (fio-3.0-53-g956e), combining --ramp_time and --io_submit_mode=offload will result in all completion latency stats to be set to 0

Example job file:
sudo fio --name=test --filename=/dev/sdb --rw=randread --runtime=5s --bs=128k --io_submit_mode=offload --ramp_time=1s

fio-3.0-53-g956e
Starting 1 process
Jobs: 1 (f=1): [r(1)][100.0%][r=7680KiB/s,w=0KiB/s][r=60,w=0 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=1548: Tue Sep 12 22:34:41 2017
   read: IOPS=56, BW=7294KiB/s (7469kB/s)(35.8MiB/5019msec)
    clat percentiles (nsec):
     |  1.00th=[    0],  5.00th=[    0], 10.00th=[    0], 20.00th=[    0],
     | 30.00th=[    0], 40.00th=[    0], 50.00th=[    0], 60.00th=[    0],
     | 70.00th=[    0], 80.00th=[    0], 90.00th=[    0], 95.00th=[    0],
     | 99.00th=[    0], 99.50th=[    0], 99.90th=[    0], 99.95th=[    0],
     | 99.99th=[    0]

**Comment by axboe** [comment]
Can you retry with current -git? There was a bug in how we propagate and set when the ramp time is over for when you are using IO offload.

**Comment by brschwartz** [comment]
Looks good to me, thanks!
