### ISSUE TITLE
shmget failing on OSX Mavericks (Darwin Kernel Version 13.4.0)

### ISSUE THREAD

**Issue by szaydel** [axboe/fio#466]
I will preface this with saying that this may be a problem with the fact that I am running Mavericks as a VM on top of Sierra with Fusion. As such, this may well be a problem solely caused by this fact. Nonetheless, I figured I should log this.

I am observing this error: `error: failed to setup shm segment`, and after a bit of research I see the following:

```
$ sudo dtrace -qn 'syscall::shmget:return {printf("Error: %d Return: %d\n", errno, arg0);}' -c '/tmp/fio ./input'
Password:
error: failed to setup shm segment
Error: 22 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
Error: 12 Return: -1
```
I am guessing this may have to do with this being a VM. This is what happens in the VM.
```
shmget(0x0, 0x7D2C04, 0x380)		 = -1 Err#22
shmget(0x0, 0x3E9604, 0x380)		 = -1 Err#12
shmget(0x0, 0x1F4B04, 0x380)		 = -1 Err#12
shmget(0x0, 0xFA584, 0x380)		 = -1 Err#12
shmget(0x0, 0x7D2C4, 0x380)		 = -1 Err#12
shmget(0x0, 0x3E964, 0x380)		 = -1 Err#12
shmget(0x0, 0x1F4B4, 0x380)		 = -1 Err#12
shmget(0x0, 0xFA5C, 0x380)		 = -1 Err#12
```
This is what happens on a normal physical machine.

```
shmget(0x0, 0x7D2404, 0x380)		 = -1 Err#22
shmget(0x0, 0x3E9204, 0x380)		 = 196608 0
```

It may not be worth investing time into this, and if you all feel this way, feel free to close this.

**Comment by sitsofe** [comment]
This normally starts happening when fio has crashed (as opposed to shutting down cleanly) and left behind shared memory segments. On other platforms such as Linux we can arrange for the OS to throw the segments away but this isn't possible on macOS/OSX. You can use

```
$ ipcs
IPC status from <running system> as of Mon Sep 25 16:10:02 BST 2017
T     ID     KEY        MODE       OWNER    GROUP
Message Queues:

T     ID     KEY        MODE       OWNER    GROUP
Shared Memory:
m 46006273 0x00000000 --rw------- anon    staff

T     ID     KEY        MODE       OWNER    GROUP
Semaphores:
```

To view them under Shared Memory and you can use something like

```
$ ipcrm -m 46006273
```

to remove them.

**Comment by sitsofe** [comment]
(Obviously some care is needed. It's key you destroy only segments that belonged to fio and not other processes)

**Comment by szaydel** [comment]
Yep, can confirm that's in fact what is happening. I removed two segments and was able to get ahead. Good to know this, thanks @sitsofe.
