### ISSUE TITLE
fio does not start the job

### ISSUE THREAD

**Issue by C4rst3n** [axboe/fio#470]
hey,
it's the same problem as #429 but now when i do not use direct write

```
[randomwrite]
ioengine=sync
rw=randwrite
refill_buffers=1
log_avg_msec=1000
size=1g
bs=128k
filename=/mnt/HDD/rH128k
```

**Comment by sitsofe** [comment]
@C4rst3n are you on a recent version of fio (3.1 or later)? Which version of fio are you running?

**Comment by sitsofe** [comment]
I can't reproduce a problem here with the following job:
```
[randomwrite]
ioengine=sync
rw=randwrite
refill_buffers=1
log_avg_msec=1000
size=1m
bs=128k
filename=/tmp/fio.tmp
```

We really also need to see the output of the failed fio run (does the `/mnt/HDD/` directory already exist? Is the current working directory writable?) . Also can you ensure you include the information asked for in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ? Thanks.

**Comment by C4rst3n** [comment]
i removed the ioengine line and the log_avg_msec, too. But same problem.
On a 2nd run it works.

system info:
```
raid@raid-PowerEdge-T630:~$ fio --version
fio-3.0-19-ga4bef
raid@raid-PowerEdge-T630:~$ cat /proc/version
Linux version 4.10.0-33-generic (buildd@lgw01-22) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
```
output:
```
randomwrite: (g=0): rw=randwrite, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=sync, iodepth=1
fio-3.0-19-ga4bef
Starting 1 process
randomwrite: Laying out IO file (1 file / 1024MiB)

randomwrite: (groupid=0, jobs=1): err= 0: pid=15674: Tue Oct  3 17:17:27 2017
  write: IOPS=2938, BW=1469MiB/s (1541MB/s)(1024MiB/697msec)
    clat (usec): min=216, max=557, avg=253.84, stdev=56.93
     lat (usec): min=216, max=558, avg=253.94, stdev=56.96
    clat percentiles (usec):
     |  1.00th=[  219],  5.00th=[  223], 10.00th=[  223], 20.00th=[  225],
     | 30.00th=[  227], 40.00th=[  229], 50.00th=[  229], 60.00th=[  231],
     | 70.00th=[  241], 80.00th=[  269], 90.00th=[  330], 95.00th=[  396],
     | 99.00th=[  486], 99.50th=[  506], 99.90th=[  523], 99.95th=[  529],
     | 99.99th=[  562]
   bw (  MiB/s): min= 1395, max= 1395, per=94.95%, avg=1395.00, stdev= 0.00, samples=1
   iops        : min= 2790, max= 2790, avg=2790.00, stdev= 0.00, samples=1
  lat (usec)   : 250=74.85%, 500=24.51%, 750=0.63%
  cpu          : usr=24.71%, sys=75.29%, ctx=2, majf=0, minf=8
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,2048,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=1469MiB/s (1541MB/s), 1469MiB/s-1469MiB/s (1541MB/s-1541MB/s), io=1024MiB (1074MB), run=697-697msec

Disk stats (read/write):
    md1: ios=0/2, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=1/9, aggrmerge=47/62, aggrticks=2/155, aggrin_queue=157, aggrutil=34.27%
  sdj: ios=0/11, merge=0/125, ticks=0/128, in_queue=128, util=11.75%
  sdi: ios=2/8, merge=94/0, ticks=4/84, in_queue=88, util=7.83%
  sdh: ios=2/9, merge=94/31, ticks=4/96, in_queue=100, util=8.81%
  sdb: ios=0/10, merge=0/94, ticks=0/312, in_queue=312, util=34.27%
```

**Comment by C4rst3n** [comment]
just noticed that it worked for my SSD random writing. But not for SSD sequentiel and not for HDD

**Comment by sitsofe** [comment]
Your latest output makes it looks like it worked... Nonetheless can you upgrade to the most recent git version of fio or fio-3.1 and see if you can still reproduce the problem? If so, can you include the fio output of a failing run?

**Comment by C4rst3n** [comment]
gonna try it.

**Comment by sitsofe** [comment]
Yes you can pull the latest and install over the old one.

**Comment by sitsofe** [comment]
(or you can skip the install and just put the full path to your new fio when you want to run it)

**Comment by C4rst3n** [comment]
new version:
```
raid@raid-PowerEdge-T630:~$ fio --version
fio-3.1-10-ge465
```

it is still instant finished, when the file does not already exist:

```
raid@raid-PowerEdge-T630:~/git/fioDrop$ runpagefiotest md5
randomwrite: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=sync, iodepth=1
fio-3.1-10-ge465
Starting 1 process
randomwrite: Laying out IO file (1 file / 1024MiB)
Jobs: 1 (f=1)
randomwrite: (groupid=0, jobs=1): err= 0: pid=22321: Tue Oct  3 19:15:53 2017
  write: IOPS=393k, BW=767MiB/s (804MB/s)(1024MiB/1335msec)
    clat (nsec): min=624, max=68464, avg=1895.48, stdev=918.31
     lat (nsec): min=649, max=68488, avg=1919.51, stdev=922.50
    clat percentiles (nsec):
     |  1.00th=[  724],  5.00th=[  772], 10.00th=[ 1208], 20.00th=[ 1240],
     | 30.00th=[ 1288], 40.00th=[ 1320], 50.00th=[ 1944], 60.00th=[ 2128],
     | 70.00th=[ 2192], 80.00th=[ 2288], 90.00th=[ 2672], 95.00th=[ 3536],
     | 99.00th=[ 5408], 99.50th=[ 5792], 99.90th=[ 7840], 99.95th=[ 8896],
     | 99.99th=[14016]
   bw (  KiB/s): min=611392, max=845208, per=92.72%, avg=728300.00, stdev=165332.88, samples=2
   iops        : min=305698, max=422604, avg=364151.00, stdev=82665.03, samples=2
  lat (nsec)   : 750=3.23%, 1000=3.13%
  lat (usec)   : 2=44.32%, 4=46.13%, 10=3.16%, 20=0.04%, 50=0.01%
  lat (usec)   : 100=0.01%
  cpu          : usr=25.79%, sys=74.06%, ctx=1, majf=0, minf=29
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,524288,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=767MiB/s (804MB/s), 767MiB/s-767MiB/s (804MB/s-804MB/s), io=1024MiB (1074MB), run=1335-1335msec

Disk stats (read/write):
    md1: ios=0/6, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=1/16, aggrmerge=62/187, aggrticks=22/137, aggrin_queue=159, aggrutil=11.84%
  sdj: ios=3/15, merge=125/125, ticks=40/144, in_queue=184, util=11.01%
  sdi: ios=0/17, merge=0/219, ticks=0/136, in_queue=136, util=9.36%
  sdh: ios=0/21, merge=0/375, ticks=0/132, in_queue=132, util=9.08%
  sdb: ios=3/13, merge=125/31, ticks=48/136, in_queue=184, util=11.84%
3
```

runpagefiotest:
i just run the first for the moment
```
# HDD random
/usr/bin/time --output=HDD_rfio_$1.txt --append executeFio rH2k.fio
#/usr/bin/time --output=HDD_rfio_$1.txt --append executeFio rH8k.fio
#/usr/bin/time --output=HDD_rfio_$1.txt --append executeFio rH32k.fio
#/usr/bin/time --output=HDD_rfio_$1.txt --append executeFio rH128k.fio
#/usr/bin/time --output=HDD_rfio_$1.txt --append executeFio rH512k.fio

# HDD sequentiell
#/usr/bin/time --output=HDD_sfio_$1.txt --append executeFio sH2k.fio
#/usr/bin/time --output=HDD_sfio_$1.txt --append executeFio sH8k.fio
#/usr/bin/time --output=HDD_sfio_$1.txt --append executeFio sH32k.fio
#/usr/bin/time --output=HDD_sfio_$1.txt --append executeFio sH128k.fio
#/usr/bin/time --output=HDD_sfio_$1.txt --append executeFio sH512k.fio

# SSD random
#/usr/bin/time --output=SSD_rfio_$1.txt --append executeFio rS2k.fio
#/usr/bin/time --output=SSD_rfio_$1.txt --append executeFio rS8k.fio
#/usr/bin/time --output=SSD_rfio_$1.txt --append executeFio rS32k.fio
#/usr/bin/time --output=SSD_rfio_$1.txt --append executeFio rS128k.fio
#/usr/bin/time --output=SSD_rfio_$1.txt --append executeFio rS512k.fio

# SSD sequentiell
#/usr/bin/time --output=SSD_sfio_$1.txt --append executeFio sS2k.fio
#/usr/bin/time --output=SSD_sfio_$1.txt --append executeFio sS8k.fio
#/usr/bin/time --output=SSD_sfio_$1.txt --append executeFio sS32k.fio
#/usr/bin/time --output=SSD_sfio_$1.txt --append executeFio sS128k.fio
#/usr/bin/time --output=SSD_sfio_$1.txt --append executeFio sS512k.fio
```

executeFio 
```
raid@raid-PowerEdge-T630:~/scripts$ cat executeFio
#!/bin/bash
fio ~/git/fioJobFiles/$1
sync
sudo echo 3 | sudo tee /proc/sys/vm/drop_caches
```

and finally the jobfile:
```
[randomwrite]
ioengine=sync
rw=randwrite
refill_buffers=1
size=1g
bs=2k
filename=/mnt/HDD/rH2k
```

the others are similar but with different block sizes, and with seq write instead of random. Some do work. But idk what test, yet

**Comment by C4rst3n** [comment]
ok, HDD random write does not work. HDD sequential only the first test with blocksize 2k, SSD random write works fine and SSD sequential only the first test with blocksize 2k

Does that help??
The jobfiles just differ in the blocksize and the output filename. where i just noticed that the random and sequentiell test both use the same file

**Comment by sitsofe** [comment]
OK this sounds like buffering. I'm guessing your server has dramatically more than 1GByte of RAM? If so it can easily hold 1GByte of writes in memory regardless of whether they are sequential or random. Basically the kernel says "got the writes!" right away and only later does it actually send them to the disk in the background. You may be better able to test this effect by using
```
sudo echo 3 | sudo tee /proc/sys/vm/drop_caches
```

Then
```
watch grep -C5 Dirt /proc/meminfo 
```

Try using end_fsync or direct=1 and see if that changes things.

**Comment by sitsofe** [comment]
PS: The usual hint that you're hitting kernel buffering is that the speeds are outrageously fast (in your case one job is reporting 1469MiB/s) compared to what you know the disk can really do and the minimum total latency is extremely low (Latency of 649 nanoseconds is speed of memory fast! - https://people.eecs.berkeley.edu/~rcs/research/interactive_latency.html ).

@C4rst3n does the above explain what you're seeing?

**Comment by sitsofe** [comment]
PPS: The other way to defeat buffering is to make sure you are writing/reading dramatically more data than can be kept in the buffer. For example if you machine has 4GBytes of RAM you ensure you do 12GBytes of I/O over at least a 12GByte region (that way two thirds of the I/O can't have possibly been cached).

**Comment by C4rst3n** [comment]
yeah the server has 64 GB RAM.
But the test doesn't even start. When i rerun it, it starts writing. For example the first test take about 50 minutes. Others are about 10 seconds. But the timer is displayed. If you take a look at the execute script i first run fio and then do a drop cache. So if i understand you correctly the end_fsync=1 will use the pagecache, but before it finishes the jobs it makes sure that everything is written to the disk, right??
In that case i'll try that. Because i want to compare "idle system" (with page cache) vs "busy system" (without page cache.)

**Comment by sitsofe** [comment]
> end_fsync=1 will [flush] the pagecache [] before it finishes the jobs it makes sure that everything is written to the disk, right??

Yes. Note latencies will still be extremely low but a write job shouldn't finish until the data has actually hit the disk. Bear in mind that the flushing is only happening at the end of the job - search for fsync in the HOWTO to see other points at which (write) flushing can be forced and bear in mind that if it can fio will invalidate caches automatically on Linux (see http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-invalidate ).

**Comment by C4rst3n** [comment]
i tried the end_fsync.
The runtimes for HDD random write:
8 | 5 | 5 | 4 | 4
HDD seq write:
5 | 4 | 4 | 4 | 4
SSD random:
3 | 2 | 2 | 2 | 2
SSD seq:
2 | 2 | 2 | 2 | 2
All values are seconds.

Now, after the output files already exist:
HDD random:
1611,07 | 4,38 | 4,49 | 4,35 | 4,28
HDD seq:
22,21 | 4,5 | 4,36 | 4,42 | 4,26
SSD random:
32,99 | 2,9 | 2,62 | 2,86 | 2,57
SSD seq:
11,13 | 2,4 | 2,75 | 2,7 | 2,68

As you can see the values for blocksize >8k are about the same as for the first test. But for 2k the test took much longer. Do you have an idea why? Furthermore a value of 2,4 secons and 2,75 seconds makes more sense to me then always 2 seconds (ssd seq.)

**Comment by sitsofe** [comment]
@C4rst3n When the output files already exist you are in the position where there may already be cached data that you have to flush out. Smaller blocks tend are more work to flush out than larger blocks. (Small) sequential blocks can be merged together to form larger blocks before they are sent to the disk so the worst case tends to be seen with small random blocks.

**Comment by C4rst3n** [comment]
yeah i see about the smaller and bigger blocks and the random vs sequential.

But i don't understand why the 2nd run takes so much longer. Yeah the file already exist. But fio generates new random data, doesn't it?
So no matter what is already cached it has to write something else. Furthermore the cached things are flushed after every run using the end_fsync, right? So there shouldn't be anything cached.

**Comment by sitsofe** [comment]
Fair point. Do the times change when you use invalidate=0 ?

**Comment by C4rst3n** [comment]
actually yes. A second run of the test is now as fast as the first run.
But what does this mean??

**Comment by sitsofe** [comment]
@C4rst3n A good question. This is a wild guess but I think it means you're also timing how long it takes to do cache invalidation. I noticed you were telling me how long the **fio process** was taking to run not how long the **individual job** took. If you take a look at http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-invalidate you will notice that fio's pre I/O cache invalidation defaults to true (on platforms where fio supports it such as Linux). My theory goes that when there's no file there's nothing cached to invalidate but when there is a recently written file there probably is. What if dropping even a clean cache takes time (have you ever noticed `echo 3 > /proc/sys/vm/drop_caches` can take seconds even after a recent sync if the amount of system cached data is large)? This could be because loads of data structures (e.g. within the filesystem and block layers) have to be found and freed when you drop the data...

At any rate this doesn't sound like a bug in fio. To find out more you'll need to talk to a linux kernel filesystem and or block layer expert to find out the proper explanation. Given this, could you close the issue here?

**Comment by C4rst3n** [comment]
oh yeah. I think you are right. Actually i take the time how long fio runs and not how long the job runs.
So it's more a kind of bug in my test implementation. 

Thank you for your help

**Comment by sitsofe** [comment]
@C4rst3n You're welcome - sorry I can't given you a definite explanation!
