### ISSUE TITLE
pointer to garbage

### ISSUE THREAD

**Issue by TaliShiva** [axboe/fio#471]
What to do if function "getevents" transmitted pointer (const struct timespec *t) which indicated garbage?
I want to paused my ioengine on some msec(sec,nsec) when ioengine wants get answer about recording of write. I don't understand how can get time for waiting if time pointer indicated garbage. Why does he pass the pointer to the garbage? (sorry for my english)

**Comment by sitsofe** [comment]
Hi @TaliShiva . I think this type of question is better asked over on the mailing list as it's not really an "issue". Could you close the issue here and use the instructions over in https://github.com/axboe/fio/blob/fio-3.1/README#L58 to send this to the mailing list? Thanks.
