### ISSUE TITLE
Some questions about ioengine

### ISSUE THREAD

**Issue by TaliShiva** [axboe/fio#472]
1) What is the call queue function of ioengine? Can you write minimal viable call chain? (init->open->queue->commit->getevents->cleanup)
 
2) Are the function of ioengine can be called in several threads without indicated numjobs? 

3) Why in null-ioengine when iodepth=1 we indicate this flag: "td->io_ops->flags |= FIO_SYNCIO;"

**Comment by sitsofe** [comment]
Hi @TaliShiva . I think this type of question is better asked over on the mailing list as it's not really an "issue". Could you close the issue here and use the instructions over in https://github.com/axboe/fio/blob/fio-3.1/README#L58 to send this to the mailing list? Thanks.
