### ISSUE TITLE
Request a means for setting a fixed unit type for BW and Latency values

### ISSUE THREAD

**Issue by excelero-joe** [axboe/fio#473]
Request a change to introduce a command-line option to allow a user to set a fixed unit type when outputting to files.

e.g. Using a script to run a series of tests and capture output into CSV or JSON(+) and ensure the output for latency and bandwidth are in fixed units like microseconds and KiBps; respectively.

**Comment by sitsofe** [comment]
Hang on - aren't the units already fixed when you use an output of json or minimal/csv (as opposed to being variable when you use normal outout)? This sounds suspiciously like https://github.com/axboe/fio/issues/451 - are you trying to parse the "normal" output which is not stable and not designed for machines?

**Comment by sitsofe** [comment]
@excelero-joe can you tell if using the json or terse output formats shows fixed units? If so can this issue be resolved. Thanks!

**Comment by excelero-joe** [comment]
Total mistake on my part.  We were reading the output wrong.  The values are in fact in fixed units with JSON output.  Closing the issue.
