### ISSUE TITLE
fio json+ summary incorrect for concurrent jobs

### ISSUE THREAD

**Issue by ejlee7** [axboe/fio#480]
The json+ output file does not include the information for both jobs when 2 jobs are run concurrently. 
The clat_hist log files that fio outputs appear to be accurate and present from both jobs, but when the ini file is run on the two drives, both jobs do not appear in the json+ summary.log file. The job name belongs to the first job and the job options appear to belong to the second job. This appears to be an issue across the following fio versions -- 2.19 - 3.1 (tested on 2.19, 3.0, 3.1)
![image](https://user-images.githubusercontent.com/1852258/31747133-f2be0d98-b41f-11e7-9733-216531a9188a.png)

[rd_rnd_qd_1_4k_70Rd_1w.txt](https://github.com/axboe/fio/files/1396581/rd_rnd_qd_1_4k_70Rd_1w.txt)
[rd_rnd_qd_1_4k_70Rd_1w_summary.log](https://github.com/axboe/fio/files/1396570/rd_rnd_qd_1_4k_70Rd_1w_summary.log)

**Comment by sitsofe** [comment]
@ejlee7 

```
[global]
name=rd_rnd_qd_1_4k_70Rd_1w
[rd_rnd_qd_1_4k_70Rd_1w_job1]
filename=/dev/nvme0n1
[rd_rnd_qd_1_4k_70Rd_1w_job2]
filename=/dev/nvme1n2
```

Is the same as saying this:
```
[rd_rnd_qd_1_4k_70Rd_1w_job1]
name=rd_rnd_qd_1_4k_70Rd_1w
filename=/dev/nvme0n1
[rd_rnd_qd_1_4k_70Rd_1w_job2]
name=rd_rnd_qd_1_4k_70Rd_1w
filename=/dev/nvme1n2
```

Notice how the first job is forcing the name of each  job globally using the `name` option - was this your intent?

**Comment by ejlee7** [comment]
The global specification of the ```name``` was to indicate that both jobs are running the same workload. From what I could tell in the documentation, the ```name``` parameter is used to specify the name that will be printed to the console while the test is running.

The issue with the json+ output file is that the "job name" specifies job1 while the "job options" are specific to job2. There is a mismatch between the "job name" and the nested "job options" in the output of the json+ file. This makes it unclear whether the data that follows belongs to job1 or job2.

**Comment by sitsofe** [comment]
If you don't set the global name are things better?

**Comment by ejlee7** [comment]
If I remove the global ```name``` parameter, there is still the same mismatch between the job number in "job name" and the job number in "job options"

**Comment by sitsofe** [comment]
@ejlee7 OK, let's rule out `name`. Next up - doesn't [`group_reporting`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-group-reporting) merge statistics? If you remove that are both reported?

**Comment by ejlee7** [comment]
```group reporting``` is what I want to use because I need the data for each job aggregated. However, looking at the documentation again, it looks like I need to also use ```new_group``` with the jobs in order to get the data aggregated in the desired manner.

**Comment by sitsofe** [comment]
@ejlee7 Yes it does sound like `new_group` would be needed. If you add that does it resolve your problem and if so could you close this issue? Thanks!

**Comment by sitsofe** [comment]
(PS: `buffered` is just an antonym of [`direct`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-direct) - you don't need to set both)
