### ISSUE TITLE
clock setaffinity failed on Oracle Linux 6.7 using fio 3.1

### ISSUE THREAD

**Issue by k2000ghm** [axboe/fio#481]
it return clock setaffinity failed: Invalid argument 4 times when run a script like:

[global]
ioengine=libaio
direct=1
group_reporting
directory=/xxx
filename=xxx
size=8g

[Squence-Write-1M]
rw=write
bs=1M
iodepth=4
runtime=60
time_based
stonewall

it can run test but get some error, when the test is finished, it start another test which i have never define like:

Jobs: 7 (f=7): [W(4), _(1), W(3)][0.1%][r=0KiB/s, w=0KiB/s][r=0, w=0 IOPS] [eta 03d:06h:41m:10s]

then I can't stop it using “Ctrl + C” but kill -9 with PID

**Comment by sitsofe** [comment]
@k2000ghm are you running fio in a container or inside a cpu cgroup?

**Comment by sitsofe** [comment]
Could you also post the full output with the error inside? Thanks!

**Comment by k2000ghm** [comment]
@sitsofe Oh，i didn't save the output, I'll try to run it again It's a Physical x86 BladeServer  on the Huawei FusionCube Platform

**Comment by sitsofe** [comment]
@k2000ghm I'm afraid without more information it's unlikely this can be taken further. Could you close this issue for now and if you're in a position to debug it could you reopen it and post more information? Thanks!

**Comment by k2000ghm** [comment]
@sitsofe OK，thank a lot
