### ISSUE TITLE
trim seems to ignore queue depth value

### ISSUE THREAD

**Issue by Thanehood** [axboe/fio#483]
When running a randtrim job, I get the same throughput using queue depth 1 and 32.  I would think I would get better throughput with higher QD, am I mistaken?
Using FIO v3.0 on Linux on SSD

**Comment by axboe** [comment]
Trim isn't a queueable command (from the application/kernel API point of view), so that's to be expected. The only way to get more than one in flight at the time is to add more jobs/threads each doing trim.
