### ISSUE TITLE
bug when kill -9 fio

### ISSUE THREAD

**Issue by john0576** [axboe/fio#486]
when use kill -9 to kill fio，linux panic and abrt report a bug：
[root@localhost ~]# abrt-cli list --since 1509473256
id 0ee3cf4d8832eae2dbee430b1b800c31e8652745
reason:         BUG: unable to handle kernel NULL pointer dereference at 0000000000000200
time:           Tue 31 Oct 2017 07:12:42 PM CET
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/vmcore-127.0.0.1-2017-10-31-14:10:52

**Comment by axboe** [comment]
That's a Linux bug, not a fio bug. You should report it there. You need the full trace, btw, the single line isn't going to help anyone...

**Comment by john0576** [comment]
3q,how to get the full trace?

**Comment by sitsofe** [comment]
@john0576 At this stage, you need to get in contact with your distro/kernel vendor (Red Hat?) about kernel debugging as they will be able to guide you as to how you take the next steps.
