### ISSUE TITLE
Terse format should generate header line and reduce metadata in output

### ISSUE THREAD

**Issue by szaydel** [axboe/fio#49]
At the moment, as wonderful as it is to get "raw-ish" output, I think there are a few issues with it. First, it would be ideal for pairs like `1.00%=6112` to instead be just `6112`, but in a column identified by a descriptive column heading. Really, the `1.00%=<value>` is a metadata+data pairing, i.e. field is described in-line so to speak. From the standpoint of rapid data processing this is less than ideal.

It may not be necessary to force column header to print, but having it be an option would be great. So, if format was fixed, and each field was just a value with a well-defined meaning, these mappings would be unnecessary, and at same time each field in each row would have a firm description.

Ideally, I would love to be able to toggle writing of header row, even if output is just one long line. This would make life much easier for me and others who use statistical tools, like R for example. Even with Python, AWK and other tools processing would be simplified.

**Comment by axboe** [comment]
Generally I've recommended people use the json output instead, as it is less fragile and is readable (easily) by both humans and machines. But I do agree, it'd be great to modify the terse format (v4 it would then be...) to do what you describe for value outputs, and add a header as the first line. I take patches!
