### ISSUE TITLE
Duplicate status described in manual page (OUTPUT)

### ISSUE THREAD

**Issue by sjvudp** [axboe/fio#491]
The man page says in **`OUTPUT`** about **`current status of each thread`**:
`P      Thread setup, but not started.`
[...]
`P      Thread running pre-reading file(s).`
Is that intentional, or is it a bug?

**Comment by sitsofe** [comment]
@sjvudp If you look at http://fio.readthedocs.io/en/latest/fio_doc.html#interpreting-the-output you will see one is capital P and the other is little p. It could be the man page has them using the same case and if so that would be a bug...

**Comment by sitsofe** [comment]
OK looking at https://github.com/axboe/fio/blob/fio-3.2/fio.1#L2724 (I'm not at a computer presently) shows they have the same case so that confirms it's a bug.

**Comment by axboe** [comment]
Indeed, I have fixed that up. Thanks for reporting!
