### ISSUE TITLE
Does the status-interval parameter work well with usec?

### ISSUE THREAD

**Issue by babx88** [axboe/fio#495]
I tried 'status-interval' parameter to 1 usec. but it didn't work.
If I change the do_usleep function in the backend.c file to 
```
static void do_usleep(unsigned int usecs)
{
	check_for_running_stats();
	check_trigger_file();
	usleep(usecs / 1000);
}
```
and check_for_running_stats(void) function in stat.c file to
```
void check_for_running_stats(void)
{
	if (status_interval) {
		if (!status_interval_init) {
			fio_gettime(&status_time, NULL);
			status_interval_init = true;
		} else if (utime_since_now(&status_time) >= status_interval) {
			show_running_run_stats();
			fio_gettime(&status_time, NULL);
			return;
		}
	}
	if (check_status_file()) {
		show_running_run_stats();
		return;
	}
}
```
finally int parse_cmd_line(int argc, char *argv[], int client_type) function in init.c to
```
case 'L': {
			long long val;

			if (check_str_time(optarg, &val, 1)) {
				log_err("fio: failed parsing time %s\n", optarg);
				do_exit++;
				exit_val = 1;
				break;
			}
			status_interval = val;
			break;
			}

```does it work?
It seems to work well, but I can not trust the results.
Help me.

**Comment by axboe** [comment]
There's nothing preventing that from working, but I'm curious why you'd want microsecond resolution on that parameter? Doing 1 million status dumps per second will severely impact the run. Why not just do some appropriate logging?

**Comment by babx88** [comment]
Thank you for answer. I tried to use it for precision testing. So Is there no way?
And Also There is one question. 
From the original code '--status-interval=1ms' parameter is worked like 10ms.

**Comment by axboe** [comment]
It's an extremely heavy handed way, especially if you want precision testing. There are logging options that are much more appropriate for your use case.

```From the original code '--status-interval=1ms' parameter is worked like 10ms.```

Not sure what that means? The time parsing looks correct, 1ms yields a value of 1, which is correct since the internal value is in miliseconds.

**Comment by sitsofe** [comment]
@babx88 were you able to use one of the other logging options mentioned over on http://fio.readthedocs.io/en/latest/fio_doc.html#log-file-formats to get the precision you were after? If so can this issue be closed?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
