### ISSUE TITLE
Performing Rate with Thinktime_blocks

### ISSUE THREAD

**Issue by shimrot** [axboe/fio#497]
I'm trying to create a load which performs regular operations at a given rate (whether BW or IOps) but with a gap between a number of blocks.  For example:   100KB reads at 8 IOps, but insert a 500ms gap every 8 blocks.   

If I try rate_iops=8, thinktime=500ms, thinktime_blocks=8, rather than a regular op rate outside of the delay, what I see is a 4 block burst after the thinktime, followed by 4 evenly spaced ops.  In other words, it seem the the op rate is steady, but and ops which occur during the thinktime period are queued up, and then released after the think period (though still at a iodepth=1 in this case)
(I'm trying this with version 3.2)

I'm wondering if this really is the way the thinktime was intended to work? If so, is there any way I can still produce a regular (linear) arrival time with gaps, which don't end up with a burst of I/Os?

Thanks much.
Kris

**Comment by axboe** [comment]
Added rate_ignore_thinktime to handle this issue. If you set that to 1, then it'll handle thinktime like you wanted.

**Comment by shimrot** [comment]
Wow - that was fast.  Thanks.
However, when testing I did run into new issues. If I run the following, after the delay period (500ms), then next operation is delayed 1.75 seconds, and then subsequent operations occur at the expected rate, and of course it repeats after the next delay period.
```
fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1501 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=500ms --thinktime_blocks=8 --rate_ignore_thinktime=1 --rate_iops=8 
```

Trace (look at InterCmdTime field):
```
Time (sec)	End Time (sec)	ID	End ID	Cmd	InterCmdTime (ms)	Start LBA	LBA Count
10.212301	10.2140344	    30	30	    R	500.06347	        166840520	200
11.9607099	11.9624288   	    31	31	    R	1746.67548	        166922640	200
12.0857169	12.0874176	    32	32	    R	123.28809	        167004760	200
12.2107246	12.2124348	    33	33	    R	123.30706	        167086880	200
12.3357325	12.3374746	    34	34	    R	123.29776	        167169000	200
12.4607409	12.4624364	    35	35	    R	123.26625	        167251120	200
12.5857473	12.5874129	    36	36	    R	123.31088	        167333240	200
12.7107549	12.7124957	    37	37	    R	123.34201	        167415360	200
13.2125557	13.2142468	    38	38	    R	500.06004	        167497480	200
14.9608998	14.9626791	    39	39	    R	1746.65301	        167579600	200
```

Thinking that the rate_cycle (1000ms) might not be right for this scenario, I tried setting the --rate_cycle=4000, 500, and 300, but none of these made any difference.

I also tried several other combinations of thinktime, blocks and rates, but they all had a varying long gap for the first op after the delay.

I'm not sure whether this issue can be reopened, or create a new issue.
Thanks again
Kris

**Comment by axboe** [comment]
Can you open a new issue for that? I'll take a look at it.

**Comment by axboe** [comment]
Nevermind, I think I fixed it. Please git pull and ensure you have this:

```commit 1aa39b0ce447f228460e6d0af601fee88fd5f4b4
Author: Jens Axboe <axboe@kernel.dk>
Date:   Thu Dec 7 09:06:04 2017 -0700

    rate: ensure IO issue restarts right after sleep
```

commit, and retest with that and report back. Thanks!

**Comment by shimrot** [comment]
The "Ensure Issue" fix doesn't seem to have resolved the issue.  I did double check that I'm truely running with the fix since
there wasn't a lot of change. The thing to note is that the 1st command after the thinktime does appear right away, and it did before.
I think I described it wrong before, sorry.  It's the 2nd command after the thinktime that is delayed.

```
fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1501 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=500ms --thinktime_blocks=8 --rate_ignore_thinktime=1 --rate_iops=8 
```

Trace: (See InterCmdTime).  id 35 is the end of the prior thinktime_blocks=8 cluster, then a 500ms think time and a command immediately,  Then the next command is delayed for 1.6s, followed by the final 6 commands in the thinktime_blocks=8 at the expected rate.
```
Time (sec)	End Time (sec)	ID	End ID	Cmd	InterCmdTime (ms)	Start LBA	LBA Count
11.8930237	11.8947615	    35	35	    R	123.29863	        528306728	200
12.3948282	12.3965725	    36	36	    R	500.06674	        528388848	200
14.0181806	14.0198703	    37	37	    R	1621.60811	        527239168	200
14.1431852	14.1449261	    38	38	    R	123.31486	        527321288	200
14.2681933	14.2699364	    39	39	    R	123.26714	        527403408	200
14.3932015	14.3948547	    40	40	    R	123.26514	        527485528	200
14.5182137	14.5199074	    41	41	    R	123.35893	        527567648	200
14.6432202	14.6449134	    42	42	    R	123.31286	        527649768	200
14.7682282	14.7710239	    43	43	    R	123.31478	        527731888	200
15.2710885	15.272756	    44	44	    R	500.06456	        527814008	200
16.893386	16.8951685	    45	45	    R	1620.63	            527896128	200

```

Thanks again, 
Kris

**Comment by axboe** [comment]
Yeah, I was out-of-office most of the day, but did notice some cases that didn't really work still. I'll see if I can make it work properly tomorrow.

**Comment by axboe** [comment]
Can you try current -git again? Thanks!

**Comment by shimrot** [comment]
Sorry,

My test machines are tied up for a few days.  I should be able to try again
Tuesday.

Thanks much.
Kris

**Comment by shimrot** [comment]
The latest change is better, though there is still a slightly greater time for the 2nd op after the delay.  Should I also tune the rate_cycle in some way?
Here are the results (different drive which now has 4K physical blocks, rather than 512B, but I did verify that this new drive with the prior fix still sees the 1.6s delay during the 2nd operation)

```
Time (sec)	End Time (sec)	ID	End ID	Cmd	InterCmdTime (ms)	Start LBA	LBA Count
48.45173	48.45205	   269	269	    R	500.177	            123771436	25
48.63877	48.63906	   270	270	    R	186.720	            123781701	25
48.76378	48.76409	   271	271	    R	124.723	            123791966	25
48.88879	48.88910	   272	272 	    R	124.695	            123615488	25
49.01379	49.01411	   273	273	    R	124.689	            123625753	25
49.13880	49.13911	   274	274	    R	124.694	            123636018	25
49.26381	49.26413	   275	275	    R	124.694	            123646283	25
49.38883	49.38914	   276	276	    R	124.697	            123656548	25
49.88933	49.88964	   277	277	    R	500.186	            123666813	25
```
Thanks again

**Comment by shimrot** [comment]
To check if the rate_cycle would have made a difference (because I was delaying after only a seconds worth of transfers), I increased the thinktime_blocks=24 (3 seconds of transfers).  But, the timing of 2nd op after the thinktime delay didn't change (just the number of operations between think times).

**Comment by shimrot** [comment]
Sorry, its the same one I was using previously: 
```
 fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1251 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=500ms --thinktime_blocks=8 --rate_ignore_thinktime=1 --rate_iops=8
```

With more operations between thinktime (significant thinktime and rate options at end of command): 
```
 fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1251 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=500ms --thinktime_blocks=24 --rate_ignore_thinktime=1 --rate_iops=8
```

Thanks

**Comment by shimrot** [comment]
axebo:  I opened a new issue to address the continued concerns, but it seems to have disappeared.  I'm not sure what happened.  

Anyway, I did some further debug and think I mostly understand the issue.

May I suggest a tweak to the backend.c::handle_thinktime calculation of "over"?  That is, adjust based on the rate per byte similar to what you've done.  That is, if thinktime is greater than one op worth of bytes, then subtract one op worth of bytes.  But, if think time is greater than one ops worth, instead add the missing the number of bytes a full op would have exceeded the think time.  Thus: 

```
	/*
	 * If we're ignoring thinktime for the rate, add the number of bytes
	 * we would have done while sleeping, minus one block to ensure the
	 * 2nd op after the sleep is not delayed further.
	 */
	if (total && td->rate_bps[ddir] && td->o.rate_ign_think) {
		uint64_t missed = (td->rate_bps[ddir] * total) / 1000000ULL;

		uint64_t over;
		uint64_t bps = td->rate_bps[ddir];
		uint64_t bs = td->o.min_bs[ddir];
		uint64_t usperop = bs * 1000000ULL / bps;
		if (usperop <= total)
			over = bs;
		else
			over = (usperop - total) / usperop * -bs;

		/*
		if (total >= 1000000)
			over = td->o.min_bs[ddir];
		else
			over = (td->o.min_bs[ddir] * total) / 1000000ULL;
		*/

		td->rate_io_issue_bytes[ddir] += (missed - over);
	}
```
 
Trying this with the original case (thinktime=500ms, and rate_iops=8)

```
fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1000 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=500ms --thinktime_blocks=8 --rate_iops=8 --rate_ignore_thinktime=1
```

a trace indicates a much better arrival consistency (though the 2nd op after the thinktime still shows a 400-500us difference (I'm unsure why, missing some factor, though it's not much of an issue with an op rate this slow).
```
Time (sec)	End Time (sec)	ID	End ID	Cmd	InterCmdTime (ms)	Start LBA	LBA Count
8.5439175	8.544215	    51	51	    R	500.19116	141338930	25
8.6684527	8.6687638	    52	52	    R	124.23768	141349195	25
8.7934697	8.7937809	    53	53	    R	124.70588	141359460	25
8.9184537	8.9187512	    54	54	    R	124.67274	141369725	25
9.0434823	9.0438114	    55	55	    R	124.73107	141379990	25
9.1684735	9.1688444	    56	56	    R	124.66202	141390255	25
9.2935054	9.2938308	    57	57	    R	124.66102	141400520	25
9.4184926	9.4188231	    58	58	    R	124.66183	141410785	25
9.9190114	9.9193336	    59	59	    R	500.18836	141421050	25
10.0435657	10.0438812	    60	60	    R	124.23216	141431315	25
10.1685745	10.1688906	    61	61	    R	124.69327	141441580	25
10.293563	10.293886	    62	62	    R	124.67239	141451845	25
10.4185723	10.4188761	    63	63	    R	124.68628	141462110	25
10.543584	10.5438865	    64	64	    R	124.70799	141318400	25
10.6685936	10.6688693	    65	65	    R	124.70717	141328665	25
10.7936035	10.7938594	    66	66	    R	124.73423	141338930	25
```



Performing a case where the thinktime is shorter than the than the rate (thinktime=100ms, rate_iops=4)
``` 
fio --output="debug.out" --allow_mounted_write=1 --direct=1 --directory="/media/stream" --filename_format=files.\$filenum --filesize=600MB --ioengine=libaio --norandommap=1 --nrfiles=1000 --numa_cpu_nodes=1 --numa_mem_policy="bind:1" --overwrite=1  --ramp_time=10s --randrepeat=0 --runtime=300s --time_based=1 --name="stream" --bs=100KB  --file_service_type="random:1850" --numjobs=1 --rw=read:40MB --thinktime=100ms --thinktime_blocks=8 --rate_iops=4 --rate_ignore_thinktime=1
``` 

The trace shows the thinktime increase between ops, but otherwise the rate is consistent (and as expected):
```
Time (sec)	End Time (sec)	ID	End ID	Cmd	InterCmdTime (ms)	Start LBA	LBA Count
11.5363729	11.5366835	    45	45	    R	349.71223	64661885	25
11.786397	11.7867078	    46	46	    R	249.71354	64672150	25
12.0364219	12.0367311	    47	47	    R	249.71405	64682415	25
12.2864485	12.2867483	    48	48	    R	249.71741	64692680	25
12.5364738	12.5367865	    49	49	    R	249.72548	64702945	25
12.7864986	12.7868118	    50	50	    R	249.71204	64713210	25
13.0365238	13.0368511	    51	51	    R	249.71202	64723475	25
13.2865494	13.2868481	    52	52	    R	249.69831	64733740	25
13.636601	13.6369294	    53	53	    R	349.75288	64744005	25
13.8866099	13.8869454	    54	54	    R	249.68049	64754270	25
```

What do you think?
Kris

**Comment by axboe** [comment]
That looks good to me! I'll get that committed.

**Comment by axboe** [comment]
Done:

http://git.kernel.dk/cgit/fio/commit/?id=62b858f646ad4fce971fbde21ff4859ec84bc281
