### ISSUE TITLE
Strong evidence suggesting there is a memory leak while using the --verify parameter.

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#50]
While comparing the memory consumption of the following command on a stock RHEL 6.5 machine over time to the equivalent without the --verify parameter, there is a considerable difference in memory consumption over time. Attempting different verification methods did not seem to  change the rate of memory leakage. crc32c crc64 md5 sha1... etc all had the same effect. while lowering the iodepth slowed the effect which also lowered the maximum number of iops being processed.
<pre><code>
./fio --ioengine=libaio --direct=1 --rw=randrw --iodepth=256 --time_based --bs=4k --runtime 24h --verify md5 --verify_fatal=1 --name=output0 --filename=/dev/mapper/mpathdof --name=output1 --filename=/dev/mapper/mpathdog --name=output2 --filename=/dev/mapper/mpathdoh --name=output3 --filename=/dev/mapper/mpathdod --name=output4 --filename=/dev/mapper/mpathdoe --name=output5 --filename=/dev/mapper/mpathdoa --name=output6 --filename=/dev/mapper/mpathdoc --name=output7 --filename=/dev/mapper/mpathdnw --name=output8 --filename=/dev/mapper/mpathdob --name=output9 --filename=/dev/mapper/mpathdnz --name=output10 --filename=/dev/mapper/mpathdny --name=output11 --filename=/dev/mapper/mpathdnx --name=output12 --filename=/dev/mapper/mpathdnv --name=output13 --filename=/dev/mapper/mpathdnt --name=output14 --filename=/dev/mapper/mpathdnu --name=output15 --filename=/dev/mapper/mpathdnq --name=output16 --filename=/dev/mapper/mpathdns --name=output17 --filename=/dev/mapper/mpathdnr --name=output18 --filename=/dev/mapper/mpathdnp --name=output19 --filename=/dev/mapper/mpathdno --name=output20 --filename=/dev/mapper/mpathdnk --name=output21 --filename=/dev/mapper/mpathdnl --name=output22 --filename=/dev/mapper/mpathdnn --name=output23 --filename=/dev/mapper/mpathdnm --name=output24 --filename=/dev/mapper/mpathdnj --name=output25 --filename=/dev/mapper/mpathdnf --name=output26 --filename=/dev/mapper/mpathdne --name=output27 --filename=/dev/mapper/mpathdni --name=output28 --filename=/dev/mapper/mpathdnh --name=output29 --filename=/dev/mapper/mpathdnd --name=output30 --filename=/dev/mapper/mpathdnc --name=output31 --filename=/dev/mapper/mpathdng
</code></pre>

After only 5 minutes of running with the --verify parameter, a considerable amount of memory has been used.  

<pre><code>top - 18:49:11 up 45 min,  2 users,  load average: 36.92, 33.17, 20.32
Tasks: 454 total,  19 running, 435 sleeping,   0 stopped,   0 zombie
Cpu(s): 22.9%us, 32.8%sy,  0.0%ni,  0.2%id, 28.0%wa,  0.0%hi, 16.1%si,  0.0%st
Mem:  24599096k total, 12130100k used, 12468996k free,   162512k buffers
Swap: 12369912k total,        0k used, 12369912k free,   922372k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
25540 root      20   0  753m 334m  552 D 21.6  1.4   2:13.45 fio
25555 root      20   0  751m 333m  552 R 21.2  1.4   2:13.75 fio
25535 root      20   0  751m 333m  552 D 21.2  1.4   2:12.22 fio
25537 root      20   0  751m 333m  548 R 20.9  1.4   2:13.57 fio
25559 root      20   0  751m 333m  552 D 20.9  1.4   2:13.15 fio
25557 root      20   0  751m 333m  548 D 21.6  1.4   2:13.48 fio
25552 root      20   0  751m 332m  552 D 21.6  1.4   2:13.43 fio
25538 root      20   0  751m 332m  544 D 21.2  1.4   2:12.90 fio
25545 root      20   0  750m 332m  552 R 21.9  1.4   2:12.86 fio
25520 root      20   0  750m 332m  552 R 20.6  1.4   2:11.30 fio
25539 root      20   0  749m 331m  552 R 21.2  1.4   2:12.60 fio
25546 root      20   0  748m 330m  544 D 21.9  1.4   2:12.76 fio
25550 root      20   0  748m 330m  548 D 21.6  1.4   2:11.86 fio
25548 root      20   0  742m 324m  552 D 21.6  1.4   2:09.51 fio
25541 root      20   0  740m 322m  548 D 22.2  1.3   2:09.55 fio
25554 root      20   0  740m 322m  544 D 21.6  1.3   2:08.30 fio
25549 root      20   0  740m 321m  544 D 21.2  1.3   2:07.98 fio
25556 root      20   0  739m 321m  548 R 21.2  1.3   2:07.79 fio
25532 root      20   0  739m 321m  552 D 20.2  1.3   2:07.09 fio
25543 root      20   0  739m 321m  556 R 20.9  1.3   2:08.99 fio
25544 root      20   0  739m 320m  552 D 20.6  1.3   2:08.26 fio
25558 root      20   0  738m 320m  544 D 21.6  1.3   2:08.07 fio
25534 root      20   0  737m 319m  548 R 20.9  1.3   2:06.16 fio
25562 root      20   0  737m 319m  548 D 21.9  1.3   2:07.70 fio
25547 root      20   0  722m 303m  560 D 19.6  1.3   2:00.81 fio
25560 root      20   0  721m 303m  548 D 19.9  1.3   1:59.64 fio
25553 root      20   0  718m 300m  548 D 19.2  1.3   1:58.87 fio
25533 root      20   0  711m 293m  544 D 19.6  1.2   1:54.97 fio
25561 root      20   0  711m 293m  548 D 19.2  1.2   1:56.98 fio
25536 root      20   0  711m 292m  552 D 19.6  1.2   1:55.96 fio
25551 root      20   0  710m 292m  556 D 18.9  1.2   1:56.46 fio
25542 root      20   0  708m 290m  548 R 18.9  1.2   1:55.94 fio
24307 root      20   0  377m 172m 171m S  0.7  0.7   0:04.95 fio</code></pre>   If left unchecked, the memory leak will consume all of the system's ram until the kernel starts killing the fio job because there is no memory left on the system.

**Comment by axboe** [comment]
That's not a leak, it's fio storing meta data related to the IO. And yes, that can consume quite a lot of memory. There are two things you can try:

1) There's an experimental option for verify, experimental_verify, that will make do without this meta data and just re-wind the playback when it needs to. That doesn't log meta data, so will consume  lot less.

2) You can split the verify into a separate phase. If you add do_verify=0 to your job, it will only write the verification bits. Then you can later re-run the same job with do_verify=1 and verify_only=1 to just do the verification.

#1 should work with your runtime settings, it'll just do all the needed writes, then switch to verify, repeat. It's experimental though, but I would love to hear if it works for you. #2 might not fit what you really want with the verify job.

**Comment by rustyscottweber** [comment]
The goal is for real time long term performance data verification.  Only writing the verification bits and then checking them at the end doesn't help if an intermediate write was bad.  example... block gets written correctly, gets overwritten incorrectly, then overwritten again correctly.  How would I ever know that data was being written incorrectly if verification of the data only happens at the end of writing traffic for a couple of days.  I'll give it a go with the experimental verification since that seems more promising, but I would like to know if there is a cap on the amount of meta data that get's collected (maybe I just need more memory for my system)?  How would I compute the minimum amount of ram needed to account for the maximum amount of memory that fio would use?  What meta data is it collecting?  Isn't the verification hash being written onto the block in test?

Also, for data verification.  While at a former company I worked for, we had a tool that would check writes by a predetermined random seed.  We kept the number of times a block had been written in memory and, based of of how many times the block had been written, we knew exactly what data had been written to the block because we knew the random seed that was being used to generate the data.  In stead of storing a verification section on each block, and then keeping that in memory, why not keep an array of random seeds with which one can reverse engineer what the exact bits should be on the block that was written?

**Comment by rustyscottweber** [comment]
PS.  all of the above mentioned solutions do not seem to reduce the amount of memory needed.

did I do something wrong?
<pre><code>
fio --ioengine=libaio --direct=1 --rw=randrw --iodepth=512 --time_based --bs=4k --runtime 12h --verify=crc32 --verify_fatal=1 --do_verify=0  --verify_dump=1 --write_bw_log randrw4k --write_iops_log randrw4k --write_lat_log randrw4k --name=output0 --filename=/dev/mapper/mpathdop --name=output1 --filename=/dev/mapper/mpathdot --name=output2 --filename=/dev/mapper/mpathdoq --name=output3 --filename=/dev/mapper/mpathdoo --name=output4 --filename=/dev/mapper/mpathdon --name=output5 --filename=/dev/mapper/mpathdom --name=output6 --filename=/dev/mapper/mpathdoi --name=output7 --filename=/dev/mapper/mpathdou --name=output8 --filename=/dev/mapper/mpathdos --name=output9 --filename=/dev/mapper/mpathdol --name=output10 --filename=/dev/mapper/mpathdov --name=output11 --filename=/dev/mapper/mpathdow --name=output12 --filename=/dev/mapper/mpathdor --name=output13 --filename=/dev/mapper/mpathdox --name=output14 --filename=/dev/mapper/mpathdok --name=output15 --filename=/dev/mapper/mpathdoj
</code></pre>
