### ISSUE TITLE
RHEL and Centos RPM's seem very dated.

### ISSUE THREAD

**Issue by rustyscottweber** [axboe/fio#503]
Looking at some of the latest RHEL and Centos built RPM's, I noticed that the rpm installed versions are at about 1.5.  Given that FIO is at 3.4 or higher at this point, it might make sense to get the updates out to those who install fio through yum.

How do I get an RPM build kicked?

**Comment by sandeen** [comment]
For RHEL5 and RHEL6, fio is only available through the EPEL repo which is essentially Fedora packages built for RHEL.  This was true for RHEL7 as well though RHEL7.4.
RHEL5 is old enough that I'm not really interested in working out build dependencies etc, but I'll see about pushing something newer for RHEL6.

**Comment by sandeen** [comment]
In the end, though, this is an EPEL distro issue, not a fio issue to bug Jens about - he doesn't control how distros ship his utility.

**Comment by dirtyharrycallahan** [comment]
The short answer is to contact the package maintainer or become a co-maintainer.

```
[root@localhost ]# rpm -q --changelog fio | head -n10
* Mon Dec 21 2015 Eric Sandeen <sandeen@redhat.com> 2.2.8-2
- Enable RDMA support

* Thu May 07 2015 Eric Sandeen <sandeen@redhat.com> 2.2.8-1
- New upstream version

* Wed Apr 15 2015 Eric Sandeen <sandeen@redhat.com> 2.2.7-1
- New upstream version
- Add librbd ioengine support

**Comment by rustyscottweber** [comment]
Thank you.  Will follow up with the EPEL library.

**Comment by sandeen** [comment]
No need, I am pushing v3.1 to EPEL6 and EPEL7 now.  (Yes, I know 3.3 is out, but there are RHEL-specific constraints I'm dealing with for now).

**Comment by sitsofe** [comment]
A quick word if caution - there are result facing differences between fio 1.5 and 3.1. It's not such a problem for humans doing one off runs but may require tweaks to scripts to cope with the new behaviour.

**Comment by sandeen** [comment]
I'm not sure how v1.5 came into the discussion - EPEL5 and EPEL6 were at v2.0.13, EPEL7 was at v2.2.8.

**Comment by rustyscottweber** [comment]
A college of mine installed fio version 1.5 from RHEL 6.8 using yum.
Thank you!
If that's the case, then maybe I should investigate where he is getting his RPM's from.
