### ISSUE TITLE
Output invalid json when --rw is either randwrite or randread

### ISSUE THREAD

**Issue by mir07** [axboe/fio#511]
Hi,
Invalid json is outputted when randon in any form or shape is chosen for rw.
Test case: sudo /usr/bin/fio --size 100m --ioengine=libaio --direct=1 --output-format=json --filename /ae1ff9ecf08682eed79b9f053490c7e9fb5137a0441b2694bafaac1cce4a2721 --name=4KQ8T8Read --bs=4k --rw=randread --numjobs=8
Example part below with this error: SyntaxError: Duplicate key '0.00' on line 63
{
	"fio version": "fio-3.1",
	"timestamp": 1515270450,
	"timestamp_ms": 1515270450512,
	"time": "Sat Jan  6 21:27:30 2018",
	"global options": {
		"size": "100m",
		"ioengine": "libaio",
		"direct": "1",
		"filename": "/ae1ff9ecf08682eed79b9f053490c7e9fb5137a0441b2694bafaac1cce4a2721"
	},
	"jobs": [{
			"jobname": "4KQ8T8Read",
			"groupid": 0,
			"error": 0,
			"eta": 0,
			"elapsed": 10,
			"job options": {
				"name": "4KQ8T8Read",
				"bs": "4k",
				"rw": "randread",
				"numjobs": "8"
			},
			"read": {
				"io_bytes": 104857600,
				"io_kbytes": 102400,
				"bw": 11155,
				"iops": 2788.974834,
				"runtime": 9179,
				"total_ios": 25600,
				"short_ios": 0,
				"drop_ios": 0,
				"slat_ns": {
					"min": 7222,
					"max": 685527,
					"mean": 39562.223086,
					"stddev": 21935.896454
				},
				"clat_ns": {
					"min": 1481,
					"max": 6828734,
					"mean": 311390.134141,
					"stddev": 133107.857838,
					"percentile": {
						"1.000000": 164864,
						"5.000000": 189440,
						"10.000000": 201728,
						"20.000000": 224256,
						"30.000000": 244736,
						"40.000000": 261120,
						"50.000000": 280576,
						"60.000000": 305152,
						"70.000000": 337920,
						"80.000000": 378880,
						"90.000000": 464896,
						"95.000000": 536576,
						"99.000000": 651264,
						"99.500000": 700416,
						"99.900000": 1105920,
						"99.950000": 1613824,
						"99.990000": 5406720,
						"0.00": 0,
						"0.00": 0,
...... Above is line 63

**Comment by mir07** [comment]
The bug is reproducible on latest git version (fio-3.3-21-g57a61)

**Comment by axboe** [comment]
It doesn't have anything to do with rand or not rand, it'll happen for any workload. In fact, this bug has been there since the json output was added.
