### ISSUE TITLE
fio --client JSON output duplicates global options

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#516]
in fio v3.2 and earlier versions, if you run *fio --client --output-format=json* , you will see in the "global options" section that global options are repeated once per host.  This is harmless but annoying, particularly when large numbers of hosts are used in a test (think VMs or containers).

**Comment by sitsofe** [comment]
Sounds similar to https://github.com/axboe/fio/issues/273 ...

**Comment by bengland2** [comment]
oops... closing, but I'll note that it's still not fixed in fio 3.2 there, thx
