### ISSUE TITLE
feature request: option to disable madvise for mmap ioengine

### ISSUE THREAD

**Issue by avg-I** [axboe/fio#528]
From the behaviors I observe and from reading the code it seems that mmap ioengine always issues either `POSIX_MADV_SEQUENTIAL` or `POSIX_MADV_RANDOM` depending on the I/O pattern.
That makes sense, but it is a bit limiting as it does not allow to test the default / normal behavior.
As an example, `rw=randread:8` is a mix of sequential and random behavior.
So, it would be nice to either extend the automatic choice of the advice to detect the mixed patterns or to provide a way to specify the advice explicitly.

What do you think?
Thank you!

**Comment by axboe** [comment]
Pushed a fix for this, so it depends on fadvise_hint like the non-mmap engines.

**Comment by avg-I** [comment]
Wow, this was lightning fast!
Thank you very much.

**Comment by avg-I** [comment]
Wow, this was lightning fast!
Thank you very much.

**Comment by avg-I** [comment]
Although, I am not 100% sure if `POSIX_MADV_DONTNEED` and `FIO_MADV_FREE` should play by the same rules as `POSIX_MADV_SEQUENTIAL` and `POSIX_MADV_RANDOM`.

**Comment by axboe** [comment]
Yeah, probably better to leave them as-is. They should be behind some invalidation check, however.
