### ISSUE TITLE
HOWTO doesn't have description for *_dev, *_agg, *_mean fields in JSON output

### ISSUE THREAD

**Issue by Ramzec** [axboe/fio#538]
```
        "bw_agg": 3.991935,
        "bw_mean": 23340.681401,
        "bw_dev": 6138.991438,
        "iops_mean": 1458.276897,
        "iops_stddev": 383.680035,
```
Could someone explain what do they mean?

**Comment by sitsofe** [comment]
@Ramzec Aggregate bandwidth, bandwidth average, bandwidth standard deviation, I/Os Per Second average, , I/Os Per Second standard deviation. Could you close this issue if that resolves your question? Thanks!

**Comment by Ramzec** [comment]
That helps. Thank you.

**Comment by sitsofe** [comment]
@Ramzec You're welcome.
