### ISSUE TITLE
zlib not found when building statically

### ISSUE THREAD

**Issue by brycepg** [axboe/fio#542]
Reproduction:

    git checkout fio-3.5
    make clean
    yum install -y zlib-devel
    ./configure --build-static

Configure notes that zlib isn't available:

    bguinta  ➜  fio git:(cd174b90) ✗ ./configure --build-static | grep zlib
    zlib                          no
    Consider installing zlib-dev (zlib-devel), some fio features depend on it.

But without --build-static this works fine:

    bguinta  ➜  fio git:(cd174b90) ✗ ./configure | grep zlib       
    zlib                          yes

**Comment by axboe** [comment]
Works for me, are you sure your zlib-devel includes a static version of libz?

**Comment by axboe** [comment]
```
$ ./configure --build-static | grep zlib
zlib                          yes
```

**Comment by brycepg** [comment]
I'm only seeing a shared object in the devel package

**Comment by brycepg** [comment]
Looks like there is a separate `zlib-static` package that I needed to have installed
