### ISSUE TITLE
Overflow of latency counters during long NVMe test running

### ISSUE THREAD

**Issue by ifke** [axboe/fio#545]
The fio utility uses uint32_t arrays for individual latency counters and uint64_t for total ones. In stat.h:
```
    uint32_t io_u_map[FIO_IO_U_MAP_NR];
    uint32_t io_u_submit[FIO_IO_U_MAP_NR];
    uint32_t io_u_complete[FIO_IO_U_MAP_NR];
    uint32_t io_u_lat_n[FIO_IO_U_LAT_N_NR];
    uint32_t io_u_lat_u[FIO_IO_U_LAT_U_NR];
    uint32_t io_u_lat_m[FIO_IO_U_LAT_M_NR];
    uint32_t io_u_plat[DDIR_RWDIR_CNT][FIO_IO_U_PLAT_NR];
    uint32_t io_u_sync_plat[FIO_IO_U_PLAT_NR];
    uint32_t pad;

    uint64_t total_io_u[DDIR_RWDIR_SYNC_CNT];
    uint64_t short_io_u[DDIR_RWDIR_CNT];
    uint64_t drop_io_u[DDIR_RWDIR_CNT];
    uint64_t total_submit;
    uint64_t total_complete;
```

We got an issue after eight hours NVMe testing with the libaio engine. Total iops value was 6323529453, and most of iops had latency 250 us. So there was overflow of corresponding io_u_lat_u counter and we saw incorrect latency distribution: the sum of values of fields latency_ns, latency_us, latency_ms was significantly less than 100 percent. The fio output in json format is here.
[fio-3.5.eighthours.txt](https://github.com/axboe/fio/files/1766154/fio-3.5.eighthours.txt)

Is it possible to change latency counters to uint64_t type and maybe do so for other counters incremented on each IO operation?

**Comment by sitsofe** [comment]
@ifke This would make sense and was suggested by Jens over in https://www.spinics.net/lists/fio/msg06407.html . Would you like to whip up a patch for this?

**Comment by ifke** [comment]
I can try. I have already patched fio of version 2.2-10 used in our company. I saw new uint32_t counters clat_percentiles and lat_percentiles in version 3.5. I'm not sure whether I have to update them too.

**Comment by sitsofe** [comment]
Yes, I think they would need updating too. Basically anything that is storing total counts of I/Os in 32 bits would need bumping to 64 bits. It's probably worth giving the patched fio's null ioengine a spin using the the sanitizer's `-fsanitize=integer` flag...

**Comment by ifke** [comment]
Fixed
