### ISSUE TITLE
Using fio to continuously send IO to the NFS share and got the “Input/output error” occasionally

### ISSUE THREAD

**Issue by justinwubo** [axboe/fio#551]
The script I'm using is below:

`for n in {1..70}; do
    fio --name=randrw$( printf %09d "$n" ) --ioengine=libaio --iodepth=128 --rw=randrw --bs=128k --direct=1 --size=50M --numjobs=300 --runtime=2400 --time_based --group_reporting >> ./fio.log
done
 `

And the error is like below and it happened almost a hundred times to different files or the same file multiple times. I googled similar issues, but most of them just happened right after they ran the fio command, but not my case. My error happened in the middle of some time.

`fio: io_u error on file randrw000000042.234.0: Input/output error
     write offset=41549824, buflen=131072
fio: io_u error on file randrw000000042.108.0: Input/output error
     write offset=11927552, buflen=131072
fio: io_u error on file randrw000000042.108.0: Input/output error
     write offset=34865152, buflen=131072`

I talked with the NFS server side and they found that the server was busy that time and the write didn't success, so the server returned "write size = 0". Seems like fio didn't handle this return or it's actually a NFS server bug?

BTW, the fio version is fio-2.1.3.

Thanks!

**Comment by sitsofe** [comment]
An NFS server is well within its rights to return short writes (i.e. telling the client that less than was asked for was written) but it looks like the Linux in-kernel NFS client interprets a zero length write as a sign that no progress was made and thus turns it into an EIO failure - https://github.com/torvalds/linux/blob/v4.15/fs/nfs/write.c#L1587-L1598 . If you check dmesg and see a message like

> NFS: Server wrote zero bytes [...]

then this is the scenario you're in. Most programs will give up if their writes I/Os return an EIO return code.

Regarding fio and the libaio ioengine, from what I can tell it will actually record that an I/O was short and retry it so long as it wasn't a zero length I/O:
* https://github.com/axboe/fio/blob/fio-3.5/engines/libaio.c#L97 shows where the length of the I/O is returned by the libaio ioengine.
* https://github.com/axboe/fio/blob/fio-3.5/backend.c#L475-L505 shows that if an I/Os length is less than what was requested then the I/O is recorded as being short and not zero the request is requeued. However if the I/O done was returned as zero this is interpreted as an error and turned into an EIO.

You might be able to force fio to carry on by using the [continue_on_error](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-continue-on-error).

PS: You will probably want to capture stdout too. Also do you know about [--output](http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-output) ?
PPS: Your version of fio is ancient! Take a look at what version we're up to now: https://github.com/axboe/fio/releases .

If the above answers your question can you close this issue? Thanks!

**Comment by justinwubo** [comment]
Hi, 

Thanks for your quick and detail reply!

I'm upgrading fio by cloning this one.

From what you said, can I understand it like this: if the reserver responses the write 0, then FIO gets it and FIO would quit the IO to the file?

By the way, I didn't find any log, like "NFS: Server wrote zero bytes [...]" on my Ubuntu client.

`grep "NFS" /var/log/*.*
/var/log/kern.log.1:Feb 22 15:30:22 iZbp1elwh9e38447rhpxonZ kernel: [ 4072.875948] RPC: Registered tcp NFSv4.1 backchannel transport module.
/var/log/kern.log.1:Feb 22 15:45:21 iZbp1elwh9e38447rhpxonZ kernel: [ 4971.612134] NFS: Registering the id_resolver key type
`

**Comment by sitsofe** [comment]
@justinwubo 

> From what you said, can I understand it like this: if the reserver responses the write 0, then FIO gets it and FIO would quit the IO to the file?

More or less yes. If fio is told by the kernel that a short zero write occurred then fio will turn the condition into an EIO error and by default fio quits when it sees an error. 

> By the way, I didn't find any log, like "NFS: Server wrote zero bytes [...]" on my Ubuntu client.

Looking again I've realised you would only see that message if you were doing buffered (non-direct) I/O as the function doing that checking in the kernel is called `nfs_writeback_result`.

Regarding your job I'm not surprised your NFS server is getting overloaded: you are trying to achieve an iodepth of 38400 (128 * 300). Your system (both client and server) will have to be well spec'd to keep up with that...

**Comment by justinwubo** [comment]
So server response is correct and FIO response is also correct, right? What happened to the file exactly? If the specific file block is 1 after the random layout and FIO this time should write it to 0, but the server responded "write size = 0", so the block kept 1? 

But if the fio quited the operations to the file that returned the error, why I saw fio continuously operating the same file within different areas. It should skip the file to others, right?

fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=9437184, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=26214400, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=16777216, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=38404096, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=655360, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=50593792, buflen=131072
fio: io_u error on file randrw000000067.51.0: Input/output error
     write offset=44171264, buflen=131072

**Comment by sitsofe** [comment]
@justinwubo

> So server response is correct and FIO response is also correct, right? What happened to the file exactly?

If I send 10 bytes and the server says it only wrote 5 then all the program knows is that the first 5 bytes are there but it can't say anything about the last 5 - they might be old data, they might be new data, they might be a mix of old and new, they might be random etc. All the program can deduce is that those last 5 bytes are indeterminate. Since we're getting back 0 length all we know is that everything we tried to write is indeterminate...

> why I saw fio continuously operating the same file within different areas.

You're doing random I/O and each in flight I/O has to finish as well so you may see up to 128 errors before the job in cancelled since you set `iodepth=128`.

**Comment by sitsofe** [comment]
@justinwubo 

> So server response is correct and FIO response is also correct, right?

I should note on fio's end it looks like a design decision to treat I/Os that return a zero length as an error. You could change the code so it tried retrying them but then I suppose the question would become how long do you retry them before you turn the condition into an error? 

However, as this topic has become more of a discussion I suggest we close the issue here and move further discussion to the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.5/README#L58) ...

**Comment by justinwubo** [comment]
Thanks man！

**Comment by sitsofe** [comment]
@justinwubo you're welcome!
