### ISSUE TITLE
trying to control rates and thinktime to work together

### ISSUE THREAD

**Issue by scramm** [axboe/fio#556]
Hi,
What we are trying to emulate is a rather bursty amount of writes an app does where it shoves anywhere from 2-8GBs at a crack, with some amount of time between them (maybe 1-3s). In the real world, out of the client it tops out around 500MB/s (writes), so I've been trying to use the rate=,500m to no luck. Then started factoring in some thinktimes but something seems wonky. On the NAS side I am seeing bursts of writes ~1GB/s and think times which appear to be 5s or more and regardless of what I set for the "rate=,myrate" or thinktime, it just doesn't seem to honor it.
Running the 3.1-1.2.el6.x86_64 version.
Example line "/usr/local/bin/fio --name=random-writes --ioengine=libaio --iodepth=4 --rw=randrw --rwmixwrite=95 --bs=128k --direct=0 --size=50g --numjobs=1 --buffer_compress_percentage=41 --thread --randrepeat=1 --thinktime=1ms --thinktime_blocks=50000 --rate=,400m  --directory /mnt/A/junk"
Am I missing something with those options? I don't care about limiting reads and if my math is right, 50K 128KB blocks at a burst should be about 6GB, correct? Anyhow, the rate actually coming into the other end is peaking at the max inbound (10Gb) line rate, not the limits I'm hoping for.
thanks

**Comment by sitsofe** [comment]
@scramm 
Your line looks broadly right although I would imagine your reads will be slowed down by your writes as you've tied them together (just over 9 reads can be done for every write that goes through). Also doesn't thinktime affect all blocks (reads and writes)?

There's also a small possibility that a fix has gone in since 3.1 that would help you. Any chance you try fio from git master (especially since you already seem to be using a local version of fio)?

**Comment by scramm** [comment]
Using the 3.5-1.2.el6.x86_64 version now, same sort of symptoms. The thinktime params, at least those I noted above, do not seem to allow the creation of burst loads like intended. I'm trying to push a couple GBs of "not-large" IOs with sleeps in between these burts of some seconds. I can't seem to get it to respond. I may be missing something Mr Obvious would catch.

**Comment by sitsofe** [comment]
@scramm if you want burstiness have you seen the `rate_process` option https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-rate-process ?

Also looking at that fio command line I see you explicitly use buffering. Did you see the warning in the documentation about libaio buffering behaviour (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-ioengine / https://github.com/axboe/fio/issues/512#issuecomment-356604533 )?

**Comment by sitsofe** [comment]
Closing because we need more information from the reporter to take this further.

@scramm - please re-open this issue if/when you're able to do more supply the requested information. Thank you!
