### ISSUE TITLE
windowsaio prints latency logs in nanoseconds, linux prints in microseconds

### ISSUE THREAD

**Issue by hiryu14** [axboe/fio#566]

**Comment by hiryu14** [comment]
not really an issue but I noticed that windows prints latency in nanoseconds while linux latency prints in microseconds, is this expected?

**Comment by sitsofe** [comment]
@hiryu14 Don't know there's much we can do without any description. I've got a feel this is going to be a question - are you sure you're not better off asking this over on the fio mailing list?

**Comment by sitsofe** [comment]
@hiryu14 If you mean the summary output fio changes the units to try and fit the values displayed (see slat in the Interpreting the output section
http://fio.readthedocs.io/en/latest/fio_doc.html#interpreting-the-output )

**Comment by sitsofe** [comment]
@hiryu14 To answer this question well we would really need the fio versions your comparing and a brief example of the output you're comparing.

**Comment by hiryu14** [comment]
Sorry, accidentally hit enter on the original submission. Thank you for taking the time to look into this. From that page, the description for latency output says:

**_Latency log
    Value is latency in nsecs_**

Mine seems to be printing in usec, or microseconds on linux. I am on version 2.2.10-1ubuntu1.

I have uploaded 3 files. 1_lat.1.log is the latency output and it looks like it is in usec.
The linux.txt is the json output from my latest test. 
The "direct_write_seq_256k_20G_8QD.txt" file is actually the .fio filed tested. 

[1_lat.1.log](https://github.com/axboe/fio/files/1841522/1_lat.1.log)
[linux.txt](https://github.com/axboe/fio/files/1841524/linux.txt)
[direct_write_seq_256k_20G_8QD.txt](https://github.com/axboe/fio/files/1841526/direct_write_seq_256k_20G_8QD.txt)

Let me know if you need anymore info.

**Comment by sitsofe** [comment]
@hiryu14 and your fio version on Windows (I'm guessing it's 2.99 or greater)?

**Comment by hiryu14** [comment]
I believe so, although I cannot tell. It was installed March 5th this year, FWIW.

**Comment by sitsofe** [comment]
@hiryu14 if you look in the JSON or normal output you will see fio always tell you its version...

**Comment by hiryu14** [comment]
Oh, Duh
"fio version" : "fio-3.5", for windows.
I attached two files windows.txt (json output) and another 1_lat.1.log 
these are from windows.

[_lat.1.log](https://github.com/axboe/fio/files/1841567/_lat.1.log)
[windows.txt](https://github.com/axboe/fio/files/1841568/windows.txt)

**Comment by sitsofe** [comment]
Your Linux fio is old (it's version 2.2.10, see https://github.com/axboe/fio/releases for what we're on now) and as such predates the nanosecond work introduced around fio-3.0 (see nanosecond in http://brick.kernel.dk/snaps/fio-3.0.shortlog.txt ) whereas your Windows fio (version 3.5) is new enough to contain it. If your Linux fio version matched that of your Windows fio I suspect they would have the same units. In general if you're doing cross platform comparisons it is wise to use a similarly versioned fio on all platforms to reduce the differences. If this answers your question could you close this issue? Thanks!

**Comment by sitsofe** [comment]
@hiryu14 did the previous comment explain what you were seeing?

**Comment by hiryu14** [comment]
Yup just tested it and it is printing in nanoseconds on linux.
I incorrectly assumed that apt-get install fio would grab the latest!

**Comment by sitsofe** [comment]
@hiryu14 Many stable/non-rolling Linux distros don't like changing the versions of software once that version of the distro ships so as the distro ages you can find you end up with very old software compared to what's upstream. Like many things this can be a double edged sword...
