### ISSUE TITLE
Allow io_limit to use a percentage

### ISSUE THREAD

**Issue by brycepg** [axboe/fio#568]
I'd like to do multiple 'drive writes' to a storage device without having to calculate the needed bytes.
For example, I'd like to see something like
```
io_limit=200%
```
Which would mean 'stop when `2*<file size>` worth of throughput has occurred'

The `size` parameter allows for percentages up to `100%` but silently stops operation at `100%` throughput if given a value greater than the size of the file.

My current workaround is to have code to calculate `drive_writes * filesize_bytes` and set the result of that value in `io_limit`. The problem with this is the jobfiles become much less generic and can be generated only when the size of the drive is known.

**Comment by sitsofe** [comment]
@brycepg if you're using as exact multiple why not use loops ? Nonetheless this request sounds like a duplicate of https://github.com/axboe/fio/issues/419 .

**Comment by brycepg** [comment]
You're right, didn't find that one.

I have the same issue as the other OP.

For `2.5` drive writes with 2 numjobs I  would need to do:
```
numjobs=2
loops=2
size=75%
```

But I want to cover the whole LBA space, not just 75% of it. If loops accepted a floating point value I'd be happier. (or if io_limit accepted a percentage)
