### ISSUE TITLE
fio acting like my drive is in read only mode when I issue write commands so unable to perform write measurements

### ISSUE THREAD

**Issue by nbyrne** [axboe/fio#57]
Hi
The issue occurs during random 4K  or sequential 128K writes, fio complains file system  I am testing is read only.
The drives are in a new server just installed Windows 2008 R2 and the LSI HBA does in fact recognize the drives.
The drive with errors does show in Device Manager so the Windows driver is recognizing it.
But any attempt to issue write commands I see this:
![writeissue](https://cloud.githubusercontent.com/assets/8560859/7151151/04ece432-e2e3-11e4-92f2-648323227df0.png)

Anyone got any ideas?

**Comment by axboe** [comment]
See this note from the HOWTO:

Note: Windows and
FreeBSD prevent write access to areas of the disk containing    
in-use data (e.g. filesystems).

I suspect that is your issue.

**Comment by nbyrne** [comment]
Thanks for getting back I will investigate some more. I have not seen this before on this firmware version and in other test systems I tested so hopefully it is in fact some thing simple like that. (the devices would not typically have any in use data. They are always freshly secure erased so never used to store any user data when we test performance).

**Comment by axboe** [comment]
It has to be something like that. Fio is getting a clear read-only error back, so the problem is somewhere below fio. Having a mounted (or whatever the windows nomenclature is there) file system on the drive would be the most likely explanation. But I'm really not a Windows expert, by any stretch of the imagination...

**Comment by nbyrne** [comment]
Probably because our firmware unstable. Not necessarily issue with fio but I will keep banging on it.

**Comment by nbyrne** [comment]
The problem was in this specific system Windows 2008 R2 Enterprise, the OS does not take drive online automatically when inserted into server. Instead it remains Offline so fio can't write to it.
![offline](https://cloud.githubusercontent.com/assets/8560859/7164906/dfbfd434-e360-11e4-9747-d80d421305dd.PNG)
Now with Windows 2008 Standard edition I don't have this issue. The drive is taken online by Disk Management automatically. So you can write to it immediately.
Once you enable drive to be online fio can now write data to it but I had enable this manually.
Annoying issue but this was the resolution.
