### ISSUE TITLE
FIO 2.20 version results interpretation

### ISSUE THREAD

**Issue by slattann** [axboe/fio#576]
Hi, 

I am new to both github  &  fio.
Can someone please help me understand how do I get git clone to version 2.20 ?

Other question:
How do interpret these results?
Run status group 0 (all jobs):
   READ: bw=384MiB/s (403MB/s), 12.0MiB/s-12.0MiB/s (12.6MB/s-12.6MB/s), io=32.0GiB (34.4GB), run=85224-85313msec

Disk stats (read/write):
    dm-2: ios=8373091/53, merge=0/0, ticks=2674007/7022, in_queue=2683890, util=100.00%, aggrios=8388658/48, aggrmerge=278/8, aggrticks=2633391/6772, aggrin_queue=2639060, aggrutil=100.00%
  sda: ios=8388658/48, merge=278/8, ticks=2633391/6772, in_queue=2639060, util=100.00%

This result I got with the command used: 
echo 3 > /proc/sys/vm/drop_caches
fio --name=Seq_read --rw=read --size=1024m  --bs=32768k --direct=1 --iodepth=1 --ioengine=sync --directory=/data/local/tmp --numjobs=32 --output=/data/FIO_Seq_RD_Run1.txt

This will really help me understand fio basics. Thanks

-Sameer Lattannavar

**Comment by slattann** [comment]
Sure . Thanks

**Comment by sitsofe** [comment]
@slattann one more hint regarding "interpret these results": https://github.com/axboe/fio/blob/fio-2.20/HOWTO#L2939 .
