### ISSUE TITLE
What is latency_target latency_window latency_percentile used for?

### ISSUE THREAD

**Issue by losemyheaven** [axboe/fio#577]
Hi,
I referred to the docs and examples but I'm still hard to understand how to use latency_target, latency_window and latency_percentile.
Could any one help explain it in detail?
Thanks

**Comment by sitsofe** [comment]
@losemyheaven 

As this isn't so much an issue in fio and more of a "How do I/what does X do?" question this is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.5/README#L58). Can you repost your question there (it might be helpful to also explain particular points in the wording of http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-latency-target , http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-latency-percentile and http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-latency-window you're struggling with) and I'll close it here. Thanks!

**Comment by losemyheaven** [comment]
Sorry for posting in wrong place.
I'll post it on mailing list.
Thanks.

**Comment by sitsofe** [comment]
@losemyheaven no worries and good luck!
