### ISSUE TITLE
Cannot allocate memory error

### ISSUE THREAD

**Issue by agnii** [axboe/fio#578]
Hi
I run fio and do a failover of storage on server. failover causes IO to stop for some time ~20s. From debug and packet capture I see the outstanding IO completes successfully, but then fio immediately exits with 'Cannot Allocate memory". This is 100% seq. writes (1K and 4K), single file, iodepth 1, direct io. Same issue with reads.
This is a NFS 4.1 (pNFS) mount.
Tried with latest git repo also.

Cut paste the output, the offset it is complaining about seems to have completed successfully.

Would be grateful for any hints on how to debug the issue. From fio and libaio code I could not get from where the message is generated.

Thanks
-Aditya

io       14279 prep: io_u 0x7f9c68003cc0: ret=0
io       14279 queue: io_u 0x7f9c68003cc0: off=0x7f8000,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
io       14279 calling ->commit(), depth 1
io       14279 io_u_queued_complete: min=1
Jobs: 1 (f=1)Jobs: 1 (f=1): [W(1)][0.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 01h:59m:57s]
....
Jobs: 1 (f=1): [W(1)][0.2%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 01h:59m:45s]Jobs: 1 (f=1): [W(1)][0.2%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 01h:59m:44s]Jobs: 1 (f=1): [W(1)][0.2%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 01h:59m:43s]io       14279 getevents: 1
io       14279 complete: io_u 0x7f9c68003cc0: off=0x7f8000,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
io       14279 fill: io_u 0x7f9c68003cc0: off=0x7f9000,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
io       14279 prep: io_u 0x7f9c68003cc0: off=0x7f9000,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
io       14279 prep: io_u 0x7f9c68003cc0: ret=0
io       14279 queue: io_u 0x7f9c68003cc0: **off=0x7f9000**,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
io       14279 calling ->commit(), depth 1
io       14279 io_u_queued_complete: min=1
io       14279 getevents: 1
io       14279 complete: io_u 0x7f9c68003cc0: **off=0x7f9000**,len=0x1000,ddir=1,file=/adi/pnfst1/file1.0.0
fio: io_u error on file /adi/pnfst1/file1.0.0: Cannot allocate memory: write **offset=8359936**, buflen=4096
io       14279 io_u_queued_complete: min=0
io       14279 getevents: 0
fio: pid=14279, err=12/file:io_u.c:1820, func=io_u error, error=Cannot allocate memory
mem      14279 free malloc mem 0x7f9c68000c50
io       14279 close ioengine libaio
io       14279 free ioengine libaio

file1: (groupid=0, jobs=1): err=12 (file:io_u.c:1820, func=io_u error, error=Cannot allocate memory): pid=14279: Wed Apr 11 04:28:12 2018
  write: IOPS=116, BW=468KiB/s (479kB/s)(8164KiB/17456msec)
    slat (usec): min=28, max=900, avg=55.55, stdev=20.97

**Comment by axboe** [comment]
This is an NFS bug, you should report it to the proper list (linux-nfs@vger.kernel.org). Fio is just the messenger here.
