### ISSUE TITLE
Misleading error message for 'cpus_allowed' option

### ISSUE THREAD

**Issue by ksacilotto** [axboe/fio#58]
The error message displayed by the option parser for the 'cpus_allowed' parameter is misleading.

My system has 4 processors:

$ grep -c processor /proc/cpuinfo 
4

If I provide a high number for cpus_allowed, I get the error message:

$ fio --filename=/tmp/foo.fio --cpus_allowed=5 --name=job1
fio: CPU 5 too large (max=4)
fio: failed parsing cpus_allowed=5

If it says "(max=4)", I would expect it to accept the value "4" if I want to use the last CPU of the system (even though we know that the CPUs are generally numbered starting with 0), but that's not what happens:

$ fio --name=global --filename=/tmp/foo.fio --cpus_allowed=4 --name=job1
job1: (g=0): rw=read, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=1
fio-2.1.3
Starting 1 process
fio: pid=24942, err=22/file:backend.c:1192, func=cpu_set_affinity, error=Invalid argument

So for setting the affinity the CPU number really starts from 0, so 3 would be the right value in this case and the following command works as expected:

$ fio --name=global --filename=/tmp/foo.fio --cpus_allowed=3 --name=job1

More details:
fio version: fio-2.2.7-11-g1d6d
OS version: Linux kleberpc 3.13.0-49-generic #81-Ubuntu SMP Tue Mar 24 19:29:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by axboe** [comment]
Hi,

I fixed this up now, so it should be consistent if you try master. Do note that cpus_allowed takes a list of CPUs. If you do cpus_allowed=3, then it can only run on CPU 3. If you want it to run on all of them, youd' do cpus_allowed=0-3, or if you wanted it to run on 0 and 2, you could do cpus_allowed=0,2

**Comment by ksacilotto** [comment]
Hi,

It seems that commit b84113993b3a (Fix off-by-one in cpu mask index handling) fixes the issue only for the 'cpumask' option, to fix it also for 'cpus_allowed' I think we would need also something like this:

diff --git a/options.c b/options.c
index b5195c35c7e4..5fbad317e47a 100644
--- a/options.c
+++ b/options.c
@@ -503,9 +503,9 @@ static int set_cpus_allowed(struct thread_data *td, os_cpu_mask_t *mask,
 				ret = 1;
 				break;
 			}
-			if (icpu > max_cpu) {
+			if (icpu >= max_cpu) {
 				log_err("fio: CPU %d too large (max=%ld)\n",
-							icpu, max_cpu);
+							icpu, max_cpu - 1);
 				ret = 1;
 				break;
 			}

**Comment by ksacilotto** [comment]
Hi,

It seems that commit b84113993b3a (Fix off-by-one in cpu mask index handling) fixes the issue only for the 'cpumask' option, to fix it also for 'cpus_allowed' I think we would need also something like this:

https://gist.github.com/ksacilotto/98824f457b4b59eda51d#file-axboe_fio_issues_58_patch

**Comment by axboe** [comment]
Oops yes, it handled only one of them. Fixed up.
