### ISSUE TITLE
Sequential Writes and Random Reads

### ISSUE THREAD

**Issue by phoenixdigital** [axboe/fio#591]
I've been writing a few tests for fio for a Splunk environment and can see you can mix reads and write for either random or sequential.

# Random Read Writes (25% reads 75% writes)
"C:\Temp\fio.exe" --runtime=60 --thread --randrepeat=1 --ioengine=windowsaio --direct=1 --gtod_reduce=1 --name=random_rw_25_75 --filename=C\:/fio-test.dat --create_on_open=0 --bs=4k --iodepth=64 --size=1G --readwrite=randrw --rwmixread=25 --disable_lat=0 --disable_clat=0 --disable_slat=0 --output-format=json+ --output=C\:random_rw_25_75.json

# Sequential Read Writes (25% reads 75% writes)
"C:\Temp\fio.exe" --runtime=60 --thread --randrepeat=1 --ioengine=windowsaio --direct=1 --gtod_reduce=1 --name=seqential_rw_25_75 --filename=C\:/fio-test.dat --create_on_open=0 --bs=4k --iodepth=64 --size=1G --readwrite=rw --rwmixread=25 --disable_lat=0 --disable_clat=0 --disable_slat=0 --output-format=json+ --output=C\:seqential_rw_25_75.json

However I was wondering if there was an option to do sequential write and random reads in the same test?

**Comment by axboe** [comment]
Sure, see ```percentage_random``` in the man page. You just set the read direction to 100, and the write direction to 0.

**Comment by phoenixdigital** [comment]
Thankyou that is perfect!
