### ISSUE TITLE
IOPS log output seems wrong...

### ISSUE THREAD

**Issue by mikkelbisgaard** [axboe/fio#594]
We've just fetched the latest version (3.6..) and it seems that if you make a fio-book with write_iops_log=path the log file is created, but the amount of IOPS is just constant at 1 ... 

example of a read output:
100, 1, 0, 4096
104, 1, 0, 4096
107, 1, 0, 4096
112, 1, 0, 4096
120, 1, 0, 4096
128, 1, 0, 4096
133, 1, 0, 4096
139, 1, 0, 4096
144, 1, 0, 4096
150, 1, 0, 4096
155, 1, 0, 4096
171, 1, 0, 4096
180, 1, 0, 4096

Same goes for the write output.

However the write_bw seems to work as intended.

**Comment by mikkelbisgaard** [comment]
Sorry - misread the documention. 
Log_avg_msec saved the day.

**Comment by sitsofe** [comment]
@mikkelbisgaard I'm glad the documentation helped :-)
