### ISSUE TITLE
Probs with ramp_time and rate_ignore_thinktime when rate_process is poisson

### ISSUE THREAD

**Issue by shimrot** [axboe/fio#596]
When rate_process=poisson, the operations stop for about "ramp_time" after ramp_time has expired, and rate_ignore_thinktime has no effect (operations still burst after think_time expires).

Fixes seem very simple.  If ok, I can generate a pull request, but simple patch at bottom.

Attached are bus trace histogram pics showing the effect:
Master: rate_process=poisson with ramp_time (no operations during measurements after ramp)
$ fio --filename=/dev/sdb --bs=64KB --direct=1 --rw=read --ramp_time=15s --runtime=25s --name=poisson --rate_process=poisson --rate_iops=6
![master-poisson-ramptime](https://user-images.githubusercontent.com/8331559/40932174-132fabea-67f3-11e8-9556-a7562e5cc2ac.PNG)

Master: rate_process=poisson with ignore_think_time (operations burst after think_time - overall rate still correct though)
$ fio --filename=/dev/sdb --bs=64KB --direct=1 --rw=read --runtime=25s --name=poisson --rate_process=poisson --rate_iops=6 --rate_ignore_thinktime=1 --thinktime=4s --thinktime_blocks=30
![master-poisson-ignorethinktime](https://user-images.githubusercontent.com/8331559/40932175-1347d24c-67f3-11e8-9f92-115010589bbf.PNG)

Fix: rate_process=poisson with ramp_time (need to add "last_usec" (used by poisson process) to reset
$ fio --filename=/dev/sdb --bs=64KB --direct=1 --rw=read --ramp_time=15s --runtime=25s --name=poisson --rate_process=poisson --rate_iops=6
![fix-poisson-ramptime](https://user-images.githubusercontent.com/8331559/40932185-1cac176c-67f3-11e8-9678-494d248df5fa.PNG)

Fix: rate_process=poission with ramp_time and ignore think time (adjust last_usec by think_time)
$ fio --filename=/dev/sdb --bs=64KB --direct=1 --rw=read --ramp_time=15s --runtime=25s --name=poisson --rate_process=poisson --rate_iops=6 --rate_ignore_thinktime=1 --thinktime=4s --thinktime_blocks=30
![fix-poisson-ignorethinktime](https://user-images.githubusercontent.com/8331559/40932186-1cc1c04e-67f3-11e8-8aff-0462c9eef8f0.PNG)

## Patch: 
```
diff --git a/backend.c b/backend.c
index 033d5a7..55bcb4e 100644
--- a/backend.c
+++ b/backend.c
@@ -892,6 +892,7 @@
 			over = (usperop - total) / usperop * -bs;
 
 		td->rate_io_issue_bytes[ddir] += (missed - over);
+		td->last_usec[ddir] += total;   // adjust for rate_process=poisson
 	}
 }
 
diff --git a/libfio.c b/libfio.c
index 6faf32a..674bc1d 100644
--- a/libfio.c
+++ b/libfio.c
@@ -92,6 +92,7 @@
 			td->bytes_done[ddir] = 0;
 			td->rate_io_issue_bytes[ddir] = 0;
 			td->rate_next_io_time[ddir] = 0;
+			td->last_usec[ddir] = 0;
 		}
 	}
```

**Comment by axboe** [comment]
Thanks, looks good to me.
