### ISSUE TITLE
Max_latency check doesn't stop all threads for multi-thread WL

### ISSUE THREAD

**Issue by akoundal** [axboe/fio#597]
fio version : 3.7 
While testing the max_latency check, its been seen that single thread will exit out with no issues but if there are multiple threads it will just fail for 1 thread and keep on going for the other threads. 
I tried the below file with and w/o thread=1 and result is same. 
In my failing case i gave 200 as arbitrary number. Thread 1 failed with the 
**Only single job fails**
![image](https://user-images.githubusercontent.com/19417434/40946059-7f571804-6810-11e8-82d2-b8ad29e32965.png)

**other jobs has higher then 2ms latency still passed**
![image](https://user-images.githubusercontent.com/19417434/40946080-95685158-6810-11e8-97f1-5d9a531177a1.png)

**FAILING CASE**
[global]
name= max latency
ioengine=libaio
direct=1
buffered=0
size=100%
randrepeat=0
time_based=1
runtime=10
norandommap
allow_mounted_write=1
max_latency=200
refill_buffers
log_avg_msec=1000
filename=/dev/nvme0n1

[job1]
stonewall
bs=128k
iodepth=128
numjobs=4
rw=write

**PASS CASE**
[global]
name= max latency
ioengine=libaio
direct=1
buffered=0
size=100%
randrepeat=0
time_based=1
runtime=10
norandommap
allow_mounted_write=1
max_latency=200
refill_buffers
log_avg_msec=1000
filename=/dev/nvme0n1

[job1]
stonewall
bs=128k
iodepth=128
numjobs=1
rw=write

**Comment by sitsofe** [comment]
@akoundal Do you know about the [`exitall`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-exitall) and does it help you here?

(BTW: As this isn't so much an issue in fio and more of a "how do I?" question it would have been better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58))

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
