### ISSUE TITLE
Files read/write to a a different device via network.

### ISSUE THREAD

**Issue by mushishi12** [axboe/fio#60]
Hi,

I'm trying to to create a CIFS like test in order to test a couple of things.

I have 2 Linux devices connected to a L2 network. I'm controlling both via console.
I want to create files in device 1 and transfer them to device 2 simultaneously using all the thread available. 
I can create the files but is there a way to transfer them to the other device using the fio tool?

Can anyone help with me with this?

**Comment by axboe** [comment]
Send email to fio@vger.kernel.org with your questions.
