### ISSUE TITLE
loop in multiple jobs in a job file 

### ISSUE THREAD

**Issue by shashank9003** [axboe/fio#603]
hello,
I want to loop back this string of jobs 1000 times, kindly help !

......code ......

[job1]
.......
stonewall
[job2]
.........
stonewall
[job3]
.........
stonewall

**Comment by sitsofe** [comment]
As this isn't so much an issue in fio and more of a "How do I?" question I'm going to close this here because it's better for you to post this to the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.7/README#L58). Thanks!
