### ISSUE TITLE
How to write random files using fio

### ISSUE THREAD

**Issue by jo-ale35** [axboe/fio#611]
I want to write random files in tmpfs(/mnt/tmp1,/mnt/tmp2...).
I tried with randseed,random_generator,randrepeat etc. in the profile file but each time I run the profile file and get the checksum the values they are the same.
I am using ioengine=sync and direct =0

**Comment by axboe** [comment]
refill_buffers=1 will ensure that write buffers get refilled before every IO. Then you can combine that with randseed etc.
