### ISSUE TITLE
How to assign a test range of the whole disk

### ISSUE THREAD

**Issue by wangzhengdera** [axboe/fio#612]
For example, the totoal disk is 100G,
I want to do the r/w at the first 1G, then the second 1G. until the last 1G
 How to do it with the current FIO version?

**Comment by sitsofe** [comment]
@wangzhengdera I'd take a look at fio's zone commands - http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-zonesize . As this isn't so much an issue in fio and more of a "how do I?" question it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.7/README#L58 )...

**Comment by sitsofe** [comment]
(@wangzhengdera but if your question was how does fio just use all of a disk then I'll point out by default fio will work with the entire file/disk unless you override that behaviour by using size. See http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-size for details)

**Comment by sitsofe** [comment]
@wangzhengdera If this answers your question could you close this issue? Thanks!
