### ISSUE TITLE
verify + norandommap + async io  + randrw can cause data verifcation errors

### ISSUE THREAD

**Issue by larrystevenwise** [axboe/fio#616]
Hey, 

I was chasing a data corruption issue with fio over nvmef/rdma transports, and i've come to find it it was due to me using norandommap when doing async, randrw, with a deep ioqpdepth.  And I guess that makes sense: if you don't use use --norandmmap, each IO is to a random block and thus with async submissions, you could overwrite the block of a prior pending IO and thus cause a verification error.

Is my analysis correct?  

Should fio perhaps detect this and either fail the run as invalid, or at least warn the user?  Or is the user supposed to be smarter than I am. :)

Here is the type of command I run over nvmf rdma connected ram disks, with ext4 file systems,  mounted on /mnt/0 and /mnt/1:

fio --verify=crc32c --rw=randrw --name=random --norandommap --ioengine=libaio --size=800m --group_reporting --exitall --fsync_on_close=1 --invalidate=1 --direct=1 --filename_format=/mnt/\$jobnum/foo.\$jobnum --time_based --runtime=30 --iodepth=256 --numjobs=2 --unit_base=1 --bs=$((1024*1024)) --kb_base=1000

With --norandmmap included, it often, though, intermittently gets verification errors.  Without norandmmap it seems to work fine.

Thanks

Steve.

**Comment by axboe** [comment]
I was looking at the documentation since I was pretty sure this is documented, but I guess only vaguely. But yes, you either need to use random map, or use the lfsr random generator to guarantee that we hit a block once (and only once).

Can you check if --random_generator=lfsr also avoids the issue? It should.

**Comment by axboe** [comment]
And if all that works out, it'd be awesome if you could send a patch for the HOWTO and fio.1 man page.

**Comment by larrystevenwise** [comment]
using '--norandommap --random_generator=lfsr' also avoids the verifcation errors!    I'll do a patch to document this.  Thanks!

**Comment by larrystevenwise** [comment]
see #617

**Comment by sitsofe** [comment]
Another thing that can help is to use [serialize_overlap](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-serialize-overlap) ...

**Comment by larrystevenwise** [comment]
so many options... :)

**Comment by axboe** [comment]
Many options! It might make sense to make a section on data verification. Straight forward use cases are simple enough, but it quickly becomes complex.
