### ISSUE TITLE
ioengine- libpmem,dev-dax,pmemblk giving error

### ISSUE THREAD

**Issue by jo-ale35** [axboe/fio#618]
**Problem Statement:** Encountering error while using the following ioengines 
1. libpmem
2. dev-dax
3. pmemblk 
**The error is as follows:**
fio: engine libpmem not loadable
fio: failed to load engine
fio: file:ioengines.c:89, func=dlopen, error=libpmem: cannot open shared object file: No such file or directory

Same for dev-dax and pmemblk.

Am using the following **profile file**:
[global]
direct=1
ioengine=pmemblk
norandommap
randrepeat=0
bs=256k         # for bandwidth

iodepth=1
runtime=30
time_based=1
group_reporting
thread

gtod_reduce=1   # for IOPS and bandwidth
#zero_buffers
refill_buffers
numjobs=9       # for bandwidth
cpus_allowed_policy=split

rw=randwrite

[drive0]
filename=/dev/pmem0.0
cpus_allowed=0-31

[drive1]
filename=/dev/dax1.0
cpus_allowed=0-31

**Comment by axboe** [comment]
Your fio build doesn't have that engine enabled. Check the output of the configure script, you'll need the necessary headers and libraries to enable it.

**Comment by jo-ale35** [comment]
Will it be enabled in the new build?

**Comment by axboe** [comment]
If you aren't building it yourself, you need to contact whoever is providing your builds. We have nothing to do with that end of things.

**Comment by jo-ale35** [comment]
The write performed by fio are  parallel or serial? If serial how can we make it into parallel.

**Comment by axboe** [comment]
You are going way off topic here now. If you have general questions about how to use fio, please direct them at fio@vger.kernel.org
