### ISSUE TITLE
No info about version mismatch between client and server

### ISSUE THREAD

**Issue by mrnuke** [axboe/fio#620]
fio just quits when there is a mismatch between server and client versions.

	[dut] # fio --server

	[client] $ fio  --client=dut.lan --filename=/dev/nvme1n2 --name=whatever --ioengine=libaio --iodepth=32 --rw=randrw --continue_on_error=1 
	whatever: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=32

What just happened? Did we run the test? Did the test fail -- it seems to have run alright? No info, no insult, no nothing. If we run with ```--debug=all``` , hidden within the long snake output, we find a cryptic hint:

	fio: bad server cmd version 70

**Expected results:**

fio prints an insult informing the numbnut user of the version mismatch.

**Comment by axboe** [comment]
That looks unfortunate, definitely should have insulted the users intelligence. I'm on vacation right now, but if no one beats me to it, I'll take a look at this early next week. What version are you running?

**Comment by sitsofe** [comment]
@mrnuke did you see Jens' question?

**Comment by mrnuke** [comment]
I saw the comment, but totally missed the question. fio-3.3, and up to fio-3.7-66-gedfc exhibit this.

**Comment by kachini** [comment]
got the same problem. Any workaround for this issue?

**Comment by axboe** [comment]
Pushed a fix for this.
