### ISSUE TITLE
Crash with particular zoned distribution

### ISSUE THREAD

**Issue by aiyoh79** [axboe/fio#622]
When run with zoned distribution, Windows FIO crash just before the test end.

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: fio.exe
  Application Version:  0.0.0.0
  Application Timestamp:    5b479850
  Fault Module Name:    StackHash_358a
  Fault Module Version: 6.3.9600.18969
  Fault Module Timestamp:   5aa29ff0
  Exception Code:   c0000374
  Exception Offset: PCH_69_FROM_ntdll+0x0000000000090D0A
  OS Version:   6.3.9600.2.0.0.400.8
  Locale ID:    1033
  Additional Information 1: 358a
  Additional Information 2: 358aa8b6b63ef02850734a6246acca53
  Additional Information 3: db9c
  Additional Information 4: db9c0fd66291c38fc78429754aa260e8

FIO version: 3.7
Windows 2012

**Comment by sitsofe** [comment]
@aiyoh79 We're going to need the a reduced testcase to be able to solve this. That means we need:

* The fio job file / parameters that make this issue occur
* You need to reduce the options to the minimum number that make the issue occur...

**Comment by aiyoh79** [comment]
This is the fio file

; Random write
[global]
ioengine=windowsaio
rw=randwrite
bs=4k
size=1g
directory=C\:\fiotest
direct=1
iodepth=16
nrfiles=1
openfiles=1
numjobs=2
thread
group_reporting
ramp_time=15
runtime=15
random_distribution=zoned:95/5:5/95

[test]

I did another test with only 1 job and there is no error reported.

**Comment by sitsofe** [comment]
OK I see this too on macOS with fio 3.7 and the following slightly reduced job file:

```
[global]
rw=randwrite
size=128M
thread
iodepth=16
nrfiles=1
openfiles=1
numjobs=2
ramp_time=5
runtime=5
random_distribution=zoned:95/5:5/95
[crash]
```

which produces the following:

```
$ fio job.fio 
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=16
...
fio-3.7
Starting 2 threads
test: Laying out IO file (1 file / 128MiB)
test: Laying out IO file (1 file / 128MiB)
fio(4082,0x700007a9e000) malloc: *** error for object 0x8000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

So it does look like something suspicious is going on...

**Comment by sitsofe** [comment]
@aiyoh79 A fix for something similar has just gone into fio HEAD (see https://github.com/axboe/fio/issues/650 ). Can you retest and see if that solves your issue too?

**Comment by sitsofe** [comment]
Excellent! Thanks for checking so quickly - I'm going to close the issue now.
