### ISSUE TITLE
fio workload on existing files and close feature

### ISSUE THREAD

**Issue by kunallillaney** [axboe/fio#623]
I am attempting to use fio to run a random write workload on a test file-system. I am currently unable to do so because of two issues which are as follows:

1. Have fio run on an existing dataset? I have set of files (larger than 1GB) and would like to run a random write workload on this which is randomly distributed. Currently, my workaround is to run fio anyways and it works fine but this is not ideal. I can run fio for an arbitrary size but this distributed incorrectly with it being biased to the start of the file (my assumptions this a hack since fio assumes the file is of small size but does not entirely overwrite the existing file). Is there a parameter in fio to run on existing files? Ideally this would ensure that the random writes would equally distributed and the total amount of data written may not be equal to the size of the existing dataset.

2. fio keeps all files open during the entire workload period and closes it once the workload is finished. Can I tell fio to close files once it is done with them instead of keeping them open throughout the workload? The file system flushes data on file close and this would enable to run a workload which is larger than the size of cache. Using sync can solve this but that is not desired.

I did look through the man for fio and the examples provided in the repo. Am I missing some parameter which enables this? Thanks.

**Comment by axboe** [comment]
#1 - do you have any data on it being skewed towards the start of the file? That sounds very odd.
#2 - it should close them once they are completed, but not before that. You can manage how many files you keep open at any point in time separately, with ```openfiles```

**Comment by kunallillaney** [comment]
@axboe Thanks for the response. I have a follow up question:

The file-system I am trying to benchmark flushes on close  not during the write (where it caches the data). Similarly it pre-fetches on open and reads from cache during read. Does fio calculate that in the aggregate bandwidth or does it strictly only use the time for every write/read done. A more general question here would be, does fio take into account create and close timings? Will using fsync_on_close and create_on_open work here?

Thanks.

**Comment by sitsofe** [comment]
@kunallillaney you might have more luck asking questions like that over on the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58)...

**Comment by kunallillaney** [comment]
@sitsofe Thanks. Will do that.
