### ISSUE TITLE
rewrite of fiologparser_hist.py

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#624]
[fio-histo-log-pctiles.py](https://github.com/parallel-fs-utils/fio/blob/fio-histo-log-pctiles/tools/hist/fio-histo-log-pctiles.py) is a proposed rewrite of [tools/hist/fiologparser_hist.py](https://github.com/axboe/fio/blob/master/tools/hist/fiologparser_hist.py) which should be much faster and easier to use.  Let me know what you think, and if you want a PR for it.  An accompanying design document is attached:

[New latency percentile measurement method for fio.pdf](https://github.com/axboe/fio/files/2219366/New.latency.percentile.measurement.method.for.fio.pdf)

**Comment by axboe** [comment]
This looks good to me, nice improvement! Care to send as a patch or pull request?

**Comment by bengland2** [comment]
do you want PDF file to be in git?  If so I'll add to the PR, but I didn't see any PDF files in the git repo.

**Comment by axboe** [comment]
I don't see why not, just shove it in doc/. It's useful.

**Comment by sitsofe** [comment]
@bengland2 is it likely the PDF could be generated from restructuredtext?

**Comment by bengland2** [comment]
Probably, (sigh).  Next time I make a change to it, I'll look into this.

**Comment by bengland2** [comment]
So it turns out that fio is generating some histogram logs where there are 2 records at the end that have the same timestamp and direction.   This shouldn't happen and it causes the above histogram log postprocessing tool to throw a divide-by-zero exception.  I'm currently usnig this workaround to filter out duplicate timestamp records, but the real fix is to get fio to stop doing this. Just letting people know because the workaround might be adequate until the fix is found:


```
@@ -59,6 +59,8 @@
     with open(logfn, 'r') as f:
         records = [ l.strip() for l in f.readlines() ]
     intervals = []
+    last_time_ms = -1
+    last_direction = -1
     for k, r in enumerate(records):
         if r == '':
             continue
@@ -91,6 +93,15 @@
         if len(buckets) != buckets_per_interval:
             raise FioHistoLogExc('%d buckets per interval but %d expected in %s' % 
                     (len(buckets), buckets_per_interval, exception_suffix(k+1, logfn)))
+
+        # hack to filter out records with the same timestamp
+        # we should not have to do this if fio logs histogram records correctly
+
+        if time_ms == last_time_ms and direction == last_direction:
+            continue
+        last_time_ms = time_ms
+        last_direction = direction
+
         intervals.append((time_ms, direction, bsz, buckets))
     if len(intervals) == 0:
         raise FioHistoLogExc('no records in %s' % logfn)
```

**Comment by bengland2** [comment]
I also hit another problem with bogus histogram generated by fio, so far it seems to be the last record, I can work around this by filtering that out again, but ughh.  Here's [the histogram log](https://s3.amazonaws.com/ben.england/bad-fio-histogram/fio_clat_hist.1.log).  The last record looks like this:

```
8005, 1, 4096, 0, ... , 0, 12522707419136, 1026, 12522707464550, 12884902915, 12522707464820, 8589935620, 12522707465066, 8589935621, 12522707465191, 1030, 12522707465393, 128849029
19, 12522707465570
```

Looks like some sort of memory corruption problem.

However, both of these problems are not bugs in fio-histo-log-pctiles.py, but in fio histogram logging, so I'm closing this issue - the rewrite appears to be working, but has exposed some issues around its input data.

**Comment by bengland2** [comment]
@sitsofe We could replace the PDF in doc/ with a .md file which can be edited using github-native editor.    Is that ok?

**Comment by sitsofe** [comment]
@bengland2 Sounds way better to me but I suppose a .rst would be even more in keeping...

**Comment by bengland2** [comment]
@sitsofe what's an .rst?  Is [this](https://en.wikipedia.org/wiki/ReStructuredText) what it is?

**Comment by sitsofe** [comment]
@bengland2 Yup. A chunk of fio's documentation is actually written in reStructuredText which can be put through http://www.sphinx-doc.org/en/master/ . See the above https://github.com/axboe/fio/issues/624#issuecomment-408704150 for the old discussion.
