### ISSUE TITLE
fio compile problem with gfio option on freebsd 11

### ISSUE THREAD

**Issue by A2116** [axboe/fio#625]
Hello
I want to install fio in FreeBSD 11
it's no problem when I compile fio package using gmake without any option and even install it, it's work correctly
but when I use (--enable-gfio) option in configuration process to use the graphical environment it makes an error and does not compile successfully
my graphical environment is KDE

the error is:

In file included from gfio.c:25:
/usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
#error "<malloc.h> has been replaced by <stdlib.h>"
 ^
gfio.c:854:3: warning: implicit declaration of function 'basename' is invalid in C99 [-Wimplicit-function-declaration]
                basename(label);
                ^
gfio.c:855:49: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const gchar *' (aka 'const char *')
      [-Wint-conversion]
                gtk_label_set_text(GTK_LABEL(ge->page_label), basename(label));
                                                              ^~~~~~~~~~~~~~~
/usr/local/include/gtk-2.0/gtk/gtklabel.h:113:25: note: passing argument to parameter 'str' here
                                                   const gchar   *str);
                                                                  ^
2 warnings and 1 error generated.
gmake: *** [Makefile:409: gfio.o] Error 1

what should I do?

**Comment by axboe** [comment]
Pushed a fix for this:

http://git.kernel.dk/cgit/fio/commit/?id=cfe1ed39102ad9711728a86eeec69c4206745036

**Comment by A2116** [comment]
tanks
but the same changes should be done on these files:

graph.c
tickmarks.c
goptions.c
gerror.c
gclient.c

**Comment by axboe** [comment]
Good point, did those as well. Minor change, the main fix was getting the basename(3) include right for the previous errors.
