### ISSUE TITLE
FIO Size produces different IO Rates

### ISSUE THREAD

**Issue by jessejameslala** [axboe/fio#627]
Using the following:

fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=5GB

fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=10GB

fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=32GB

The resulting IO indicates lots of paging even though I am using direct=1 the 5GB file results in 4K IO/Sec while the 32GB size results in 1K IO/Sec

**Comment by jessejameslala** [comment]
[root@dr6300-7WVBR22 Qorestor]# fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=5GB
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=256
fio-3.1
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][r=0KiB/s,w=16.8MiB/s][r=0,w=4288 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=9795: Mon Jul 23 23:41:11 2018
  write: IOPS=4165, BW=16.3MiB/s (17.1MB/s)(980MiB/60160msec)
   bw (  KiB/s): min=13312, max=20992, per=100.00%, avg=16837.13, stdev=1243.46, samples=120
   iops        : min= 3328, max= 5248, avg=4208.92, stdev=310.84, samples=120
  cpu          : usr=0.58%, sys=3.53%, ctx=7862, majf=0, minf=340
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=113.5%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=0,250602,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=16.3MiB/s (17.1MB/s), 16.3MiB/s-16.3MiB/s (17.1MB/s-17.1MB/s), io=980MiB (1028MB), run=60160-60160msec

Disk stats (read/write):
    dm-3: ios=0/284347, merge=0/0, ticks=0/9186975, in_queue=9189893, util=99.98%, aggrios=0/284417, aggrmerge=0/0, aggrticks=0/9134489, aggrin_queue=9134548, aggrutil=99.96%
  sdb: ios=0/284417, merge=0/0, ticks=0/9134489, in_queue=9134548, util=99.96%
[root@dr6300-7WVBR22 Qorestor]# fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=10GB
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=256
fio-3.1
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][r=0KiB/s,w=9088KiB/s][r=0,w=2272 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=9856: Mon Jul 23 23:42:26 2018
  write: IOPS=2270, BW=9099KiB/s (9317kB/s)(536MiB/60335msec)
   bw (  KiB/s): min= 6656, max=11052, per=100.00%, avg=9194.79, stdev=754.39, samples=120
   iops        : min= 1664, max= 2763, avg=2298.31, stdev=188.51, samples=120
  cpu          : usr=0.31%, sys=1.88%, ctx=4341, majf=0, minf=4
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=117.2%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=0,136987,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=9099KiB/s (9317kB/s), 9099KiB/s-9099KiB/s (9317kB/s-9317kB/s), io=536MiB (562MB), run=60335-60335msec

Disk stats (read/write):
    dm-3: ios=0/160642, merge=0/0, ticks=0/9066214, in_queue=9066463, util=98.21%, aggrios=0/160642, aggrmerge=0/0, aggrticks=0/9004872, aggrin_queue=9004850, aggrutil=98.20%
  sdb: ios=0/160642, merge=0/0, ticks=0/9004872, in_queue=9004850, util=98.20%
[root@dr6300-7WVBR22 Qorestor]# fio --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=/Qorestor/io_test --bs=4k --iodepth=256 --readwrite=randwrite --ramp_time=4 --runtime=60 --randrepeat=1 --group_reporting --size=32GB
test: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=256
fio-3.1
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][r=0KiB/s,w=4864KiB/s][r=0,w=1216 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=9915: Mon Jul 23 23:43:41 2018
  write: IOPS=1425, BW=5718KiB/s (5855kB/s)(336MiB/60258msec)
   bw (  KiB/s): min= 3847, max=124384, per=100.00%, avg=5756.00, stdev=10928.56, samples=120
   iops        : min=  961, max=31096, avg=1438.62, stdev=2732.17, samples=120
  cpu          : usr=0.17%, sys=0.95%, ctx=2784, majf=0, minf=104
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.2%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=0,85886,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=5718KiB/s (5855kB/s), 5718KiB/s-5718KiB/s (5855kB/s-5855kB/s), io=336MiB (353MB), run=60258-60258msec

Disk stats (read/write):
    dm-3: ios=0/86146, merge=0/0, ticks=0/8671824, in_queue=8672076, util=92.12%, aggrios=0/86146, aggrmerge=0/0, aggrticks=0/8612500, aggrin_queue=8612490, aggrutil=92.10%
  sdb: ios=0/86146, merge=0/0, ticks=0/8612500, in_queue=8612490, util=92.10%

**Comment by axboe** [comment]
Are you memory constrained? Might help to add norandommap as an option.

**Comment by sitsofe** [comment]
@jessejameslala can you follow up on Jen's comment?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
