### ISSUE TITLE
Request to set 'cpu' as the default clocksource

### ISSUE THREAD

**Issue by adityagulavani** [axboe/fio#630]
I've been working with fio to check storage performance on virtualized environment vs. bare-metal performance. One thing I noticed in perf report was fio depended heavily on 'clock_gettime()' on the virtualized environment where I was getting **130K IOPS per thread** compared to **~240K IOPS** on bare-metal with same configuration. I collected a lot perf data (perf, ftrace, sysstat tools) to confirm it was fio and not the VM. 

Turns out, if I just set the clocksource to 'cpu' then the performance I get from fio is **~195K IOPS** on virtualized environment. That is a 1.56x improvement just by changing the clocksource. Is there  a reason there is no default value set for clocksource parameter?

I agree, it was a fault on my behalf for not reading through the HOWTO doc. Even that states fio heavily depends on clocksource and 'cpu' is the preferred one. For some reason, on the VM fio goes with 'clock_gettime()' whereas on bare-metal it goes with 'cpu' as the clocksource. If it is all the same with no conflicts reported with 'cpu' clocksource, can we have that as the default clocksource?

**Comment by axboe** [comment]
The VM probably doesn't report a stable and invariant TSC, or maybe it fails the test. If you run:

```fio --cpuclock-test```

on the vm, what does it output? Fio will default to the CPU clocksource, if it's working and stable. If it isn't, well then it won't...

**Comment by adityagulavani** [comment]
fio does not find a reliable TSC in the cpuclock_test on the VM. 

[fio_clocktest.log](https://github.com/axboe/fio/files/2236392/fio_clocktest.log)

Can you briefly explain the significance of a stable TSC in fio? Is the clock used anywhere else apart from accounting?

**Comment by axboe** [comment]
The cpuclock results look fine, but it doesn't report invariant tsc in the cpuid. This is what makes fio ignore the clock source, since it's deemed unreliable. CPUs without invariant TSC aren't synced across cores, which means it's hard/impossible to use them as a reliable clock source across CPUs. It's just used for accounting.

**Comment by adityagulavani** [comment]
Ah, got it. Thanks a lot. 

We can go ahead and close the issue.
