### ISSUE TITLE
fio benchmark on RAID device avoiding any caching

### ISSUE THREAD

**Issue by 74cmonty** [axboe/fio#641]
Hi,
can you recommend a fio setting for benchmarking a RAID device that is bypassing any caching effects in case RAID controller has cache enabled?

THX

**Comment by sitsofe** [comment]
As this isn't so much an issue in fio and more of a "how do I?" question (and one that isn't really about fio...) it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58).

**Comment by sitsofe** [comment]
(For others who might end up here this was answered on the mailing list over in https://www.spinics.net/lists/fio/msg07224.html )
