### ISSUE TITLE
randommap causes skew in distribution of disk addresses

### ISSUE THREAD

**Issue by kelleymh** [axboe/fio#658]
When running fio in a typical configuration of “randread” (or “randrw” or “randwrite”) with 4K block size and the default random number generator (Tausworthe), the sequence of generated disk addresses has a sizable skew in certain situations.  I tracked down the skew to the way the randommap works to prevent disk addresses from being used more than once.

The skew is observed when running against a RAID0 disk configuration with 4 disks and with 64K chunk size on Linux.  One would expect almost the same number of I/Os to be directed to each of the 4 disks in the RAID0 config, but actually disk 0 ends up with about 15% more I/Os than the other three when run for a hour against 800 Mbyte disks (total of 3.2 Tbyte).  While the overall disk addresses are random, the low order 6 bits of the addresses skew toward zero, resulting in disk 0 getting more traffic than the others.   If the RAID0 array is constructed with a chunk size of 256K or larger, the skew goes away because then the low order 6 bits of the address aren’t a factor in determining which disk to use.

When running with the --norandommap option, the skew also goes away and each of the 4 disks sees the same number of I/Os to within about 0.015%, which is great.  The skew also goes away when ‘lfsr’ is used as the random number generator because a randommap is not needed in that case.

Looking at axmap.c, the cause of the problem is evident.  The map is constructed of 64-bit words (on 64-bit hardware), where each bit represents 4K bytes (in my configuration doing 4K randreads).  If the random number generator produces a disk address with a bit in the map that is already set (i.e., the address has already been used), the randommap finds a “nearby” bit that is zero, and generates a new disk address based on that bit.  The skew occurs in the selection of the “nearby” bit.  The algorithm selects the current 64-bit word, and scans for a zero bit in that word, but always starting at bit zero of the word.  Particularly when the map is closer to empty than full, this produces disk addresses with low order 6 bits that tend toward zero.

I have coded a version of axmap_next_free() that takes a different approach.  When looking for a zero bit, it starts with the current bit that collides and only looks forward (i.e., larger values) for a zero bit, wrapping around the end of the map if necessary.   This approach avoids the skew, and experimentally produces very even usage across the 4 disks in the RAID0 config with 64K chunk size.  It is, however, a fairly extensive rewrite of axmap_next_free() and axmap_find_first_free().

I’m new to the fio community, and am looking for feedback on the issue and my proposed new approach.  I’ll submit pull requests if there is general agreement.

**Comment by axboe** [comment]
Thanks for the report. Please post the axmap patch so we can take a look. I like the described approach (start at current, only look forward and wrap if necessary).

**Comment by sitsofe** [comment]
@kelleymh was this fixed by https://github.com/axboe/fio/commit/b9304c5be4efabebdc4d8bf649d7239bf8af986e and if so could you close this issue? Thanks!

**Comment by kelleymh** [comment]
Yes, this was fixed by that commit.  Closing.
