### ISSUE TITLE
bssplit operation is not working as expected.

### ISSUE THREAD

**Issue by MohanrajBabu** [axboe/fio#662]
Hi,

**Description:**

Set the option bssplit=4k/10:64k/50:32k/40 and size=10M in a job file.
Expected Behavior:
The range of bs should be between 4k and 32k and block size should split based on the weightage.
Actual Behavior:
Observed range of bs is between 32k and 32k and so IO read operation performed with bs set as 32k.
Issued read is 320.
320*32k = 10M
    
**Linux distro and kernel version**
     Ubuntu 18.04
     4.15.0-29-generic

**fio version**
     fio-3.8-87-gc088
 
**Steps to reproduce:**
Job file:  
[read_bss]
rw=read
bssplit=4k/10:64k/50:32k/40
size=10M
filename=file1

output:
read_bss: (g=0): rw=read, bs=(R) 32.0KiB-32.0KiB, (W) 32.0KiB-32.0KiB,
(T) 32.0KiB-32.0KiB, ioengine=psync, iodepth=1
fio-3.8-87-gc088
Starting 1 process

read_bss: (groupid=0, jobs=1): err= 0: pid=15920: Thu Aug 23 18:44:49 2018
   read: IOPS=735, BW=22.0MiB/s (24.1MB/s)(10.0MiB/435msec)
    clat (usec): min=8, max=67364, avg=1352.33, stdev=7109.12
     lat (usec): min=8, max=67365, avg=1352.65, stdev=7109.09
    clat percentiles (usec):
     |  1.00th=[    9],  5.00th=[   11], 10.00th=[   13], 20.00th=[   15],
     | 30.00th=[   15], 40.00th=[   16], 50.00th=[   17], 60.00th=[   17],
     | 70.00th=[   20], 80.00th=[   24], 90.00th=[ 2540], 95.00th=[ 3130],
     | 99.00th=[45351], 99.50th=[65799], 99.90th=[67634], 99.95th=[67634],
     | 99.99th=[67634]
  lat (usec)   : 10=3.44%, 20=66.56%, 50=16.56%, 100=0.31%, 500=0.31%
  lat (usec)   : 1000=1.25%
  lat (msec)   : 2=0.94%, 4=6.88%, 10=0.62%, 20=1.25%, 50=0.94%
  lat (msec)   : 100=0.94%
  cpu          : usr=4.15%, sys=0.00%, ctx=42, majf=0, minf=20
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=320,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=22.0MiB/s (24.1MB/s), 22.0MiB/s-22.0MiB/s
(24.1MB/s-24.1MB/s), io=10.0MiB (10.5MB), run=435-435msec

Disk stats (read/write):
  sda: ios=36/0, merge=0/0, ticks=712/0, in_queue=776, util=79.03%

_Why fio not splitting the block size based on the weightage._

P.S: Tried to send this content to fio@vger.kernel.org. I have subscribed but the server rejecting my mails, need help on this also.

Thanks and Regards,
Mohan

**Comment by axboe** [comment]
Looks like a recent bug, introduced by the > 4GB block size support. I'll take a look at it.

The fio mailing list is very picky, you have to send plain text emails (no html, etc).

**Comment by axboe** [comment]
OK, pushed a fix:

http://git.kernel.dk/cgit/fio/commit/?id=e97163ad9c395e352028e200b781666d1a775449

should work fine again for you now.

**Comment by MohanrajBabu** [comment]
Thanks axboe, its working fine now.

**Comment by axboe** [comment]
Great, thanks for reporting, and subsequently testing the fix.
