### ISSUE TITLE
Install FIO RHEL

### ISSUE THREAD

**Issue by latincode** [axboe/fio#668]
I have already installed in testing and QA environment now on Production

This is how I proceed:

1.- Install REPEL

**_rpm -iv epel-release-7-11.noarch.rpm_**

This time it make this error:

_warning: epel-release-7-11.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY_
_Preparing packages for installation...
        file /etc/yum.repos.d/epel-testing.repo from install of epel-release-7-11.noarch conflicts with file from package epel-release-6-8.noarch
        file /etc/yum.repos.d/epel.repo from install of epel-release-7-11.noarch conflicts with file from package epel-release-6-8.noarch_

2.- Then I install FIO  tar -xf fio-2.1.10.tar

**_./configure_**

error message:
_compile error check config.log and/or the above output_

And cannot continue doing

3.- **_make_**

error:
_make: ***[conf.host.make] error1 fio_

4.- **_make install_**

Is this due to ./configure problem or epel?

**Comment by sitsofe** [comment]
As this isn't so much an issue in fio and more of a "how do I?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58). Further, we (upstream) don't support ancient versions of fio (you're trying to use `fio-2.1.10`, see https://github.com/axboe/fio/releases for which version we're up to....)
