### ISSUE TITLE
ramp_time issue

### ISSUE THREAD

**Issue by hertz1987** [axboe/fio#669]
I'm running a fio test with the following job file:
```
[global]
randrepeat=0
group_reporting=1
fadvise_hint=0
direct=1
runtime=10
ioengine=libaio
filename=/dev/asm-disks/DATA1
time_based=1

[small_random_write]
rw=randwrite
ramp_time=1
numjobs=50
bs=8k
```
when the job started i see there are only 42 processes opening the file and doing I/O operations:
```
Jobs: 50 (f=42): ....
```
and the remaining 8 processes won't open the file and do I/Os unless the 42 processes finish their run:
```
Jobs: 8 (f=8):.... [eta 07m:50s]
```
besides, the eta [eta 07m:50s] is way longer than runtime or ramp_time that i've specified in the job file

by running vmstat i can see while the 42 processes are running and waiting for I/O response,the other 8 process are waiting for run time:
```
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu-----
 8 42      0 53653048 128136 2624400    0    0     0 460680 108554 653863  1 11 34 55  0
 8 42      0 53651788 128144 2624396    0    0     0 442204 104978 656010  1 10 50 39  0
 8 42      0 53651656 128144 2624400    0    0     0 446312 106599 657230  1 10 53 35  0
 9 42      0 53651720 128144 2624400    0    0     0 427080 104135 638754  1 10 55 34  0
```
The problem disappears when ramp_time is not specified, even if i raise numjobs to a incredibly high value:
```
Jobs: 2500 (f=2500): [w(2500)][66.7%][r=0KiB/s,w=94.6MiB/s][r=0,w=12.1k IOPS][eta 00m:05s]   
```
So i have no idea why they did not run simultaneous with the previous 42 processes
any hint or suggestion is of great help to me ! thanks in advance!

**Comment by sitsofe** [comment]
@hertz1987 are you on the latest version of fio and if not does upgrading to it make a difference?

**Comment by hertz1987** [comment]
@sitsofe  I've tried both the latest version(3.8) and the stable version (2.0.12) for RHEL 6.9 on epel , and this problem occur in both releases.I'm sorry for delay of feedback in the next few hours, and I'll be checking on this issue tomorrow as soon as i can,thank you guys again for your precious time !

**Comment by axboe** [comment]
Works fine for me, just used an nvme device as the only change in the job file. Are you running out of RAM? If the device is huge and you're using randwrite, that can happen with that many jobs. You could try adding ```norandommap``` and see if that helps you.

**Comment by hertz1987** [comment]
I'll verify it with more variables,and see if changing memory size and read/write mode could help. I'll close the issue for now, if something valuable comes up i'll post my finding here. Thanks again your your time !

**Comment by hertz1987** [comment]
The machine I'm testing on has 32 cpu threads and 128GB memory, and it's OS is RHEL 6.9 .I've tried clearing /etc/sysctl.conf and /etc/security/limits.conf to avoid any misconfigured parameters. i've also tried the norandommap but all in vain. but after changing my test environment to another machine which has same cpu threads count and memory size but uses ubuntu 16.04.3(4.4.0-87) the  problem disappeared, and i got exactly 140 processes simultaneously running. I'lll give more feedback if anything comes up

**Comment by sitsofe** [comment]
@hertz1987 You can check `ipcs shm` to see if there are left over shared memory segments from crashed fio runs on the problem machine (but telling whether the segments came from fio can be tricky). If this is the issue then the problem is fixed on Linux with fio-2.18+.

**Comment by hertz1987** [comment]
@sitsofe I've tried the latest version of fio (3.8) but it didn't work.
I notice that:
- The number of process that did not run simultaneously with the others varied each time i tried to run the test
- From the following output while the test is running i can see that those processes are still in ramp period: 
  ``` Jobs: 140 (f=138): [r(41),/(1),r(44),/(1),r(53)][0.0%][r=365MiB/s,w=0KiB/s][r=46.7k,w=0 IOPS] ```
  Notice that 41+44+53 = 138 process are doing read I/O operations while the other 1+1=2 processes are in ramp period ( "/" means in ramp period ,according to OUTPUT section in fio man page )

I've tried various variables but still can't find out the reason,and i've decided to move on,but i'll be sure to post my findings soon as i crack this.Thank you guys!

**Comment by axboe** [comment]
You must be talking about a different job file now, can you please always post what you are running?
