### ISSUE TITLE
Fio write opetation write the file in each run?

### ISSUE THREAD

**Issue by jo-ale35** [axboe/fio#674]
While doing write/randwrite with FIO is it actually writing the whole file for every run?
 Or is it just writing a file during the first run only?

**Comment by szaydel** [comment]
Best answer is it depends on how the job is configured, but I think more commonly answer will not be entirely re-written files each time.

**Comment by sitsofe** [comment]
@jo-ale35 the answer that @szaydel gave is spot on - it depends. For example a job like this:

```
fio --name=example --rw=write --filename=fio.test --size=4M
```

is going to try and preallocate the fio.test file (see https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-fallocate ) if it doesn't exist, write to every 4k block of it once and then exit. You don't specify what a run is so I have made an assumption.

Note: This isn't so much an issue in fio and more of a "How do I/What does X do?" so it would be better to aim questions like this towards the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58). Thanks!
