### ISSUE TITLE
git.kernel.dk Git Smart HTTP Support

### ISSUE THREAD

**Issue by felixbuenemann** [axboe/fio#68]
While [updating the homebrew formula](https://github.com/Homebrew/homebrew/pull/39474) for Mac OS X, I noticed that checkout over http from the canonical repo is very slow, so I think [Git Smart HTTP](http://git-scm.com/docs/git-http-backend) is not configured on the server, which gives a big speed boost and enables progress reports in the git client.

```bash
git clone git://git.kernel.dk/fio.git  1,06s user 0,74s system 14% cpu 12,245 total
git clone http://git.kernel.dk/fio.git  2,00s user 3,32s system 5% cpu 1:40,52 total
```

As you are running GitWeb on Apache and probably only want read-only access, something like this should be appropriate:

```apache
SetEnv GIT_PROJECT_ROOT /var/www/git

AliasMatch ^/git/(.*/objects/[0-9a-f]{2}/[0-9a-f]{38})$          /var/www/git/$1
AliasMatch ^/git/(.*/objects/pack/pack-[0-9a-f]{40}.(pack|idx))$ /var/www/git/$1
ScriptAliasMatch \
	"(?x)^/git/(.*/(HEAD | \
			info/refs | \
			objects/info/[^/]+ | \
			git-upload-pack))$" \
	/usr/libexec/git-core/git-http-backend/$1
ScriptAlias /git/ /var/www/cgi-bin/gitweb.cgi/
```
The important change to the "Accelerated static Apache 2.x" example for read-only access is the removal of git-receive-pack in the ScriptAliasMatch directive.

Feel free to ignore or close as completely off-topic :smile:

**Comment by axboe** [comment]
This is very useful, I had no idea. I never use the http:// protocol myself for git. It should work now, but only if you use:

http://git.kernel.dk/data/git/fio.git

to clone. Should be possible to make it work without /data/git/ as well, but that currently screws up the gitweb interface if I do...

**Comment by axboe** [comment]
Should work now without /data/git/ - please test.

**Comment by felixbuenemann** [comment]
Works fine, thanks! I also checked that push is denied.
