### ISSUE TITLE
cannot run trace file

### ISSUE THREAD

**Issue by Umar895** [axboe/fio#681]
Hi,
I have tried to run my trace file via io_readlog option, but the recommended format for this option does not include timing. Can anyone please suggest any other option to run my trace file using fio. The format of the trace file is as follows [LBA, IO_SIZE, TIME].

Thank you,
Umar

**Comment by sitsofe** [comment]
As this isn't so much an issue in fio and more of a "how do I?" question it might be better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.8/README#L58). You may also need to clarify what you mean by "timing" (the current trace format is described over on https://fio.readthedocs.io/en/latest/fio_man.html#trace-file-format-v2 ).

**Comment by axboe** [comment]
You can do delays, the format is described in the link that Sitsofe provided. I'm going to close this one, as it's not an issue.
