### ISSUE TITLE
steady state detection function does not work

### ISSUE THREAD

**Issue by tyneliu** [axboe/fio#687]
All the three option ss_ramp, ss_dur and ss_ramp does not work. no matter how you change the three parameter it will not affect the fio steady state detection.
here is my fio options:
fio --ioengine=libaio --direct=1 --thread --norandommap --group_reporting --log_avg_msec=60000 --per_job_logs=0 --minimal --eta=always --name=RandRdPre --rw=randread --bs=4k --ss=iops_slope:0.1% --ss_dur=1800 --ss_ramp=3600 --write_iops_log=fioinst  --filename=/dev/sda --iodepth=32  --numjobs=1
and the fio instant log:
60000, 79617, 0, 0
120000, 79793, 0, 0
180000, 79661, 0, 0
240000, 79704, 0, 0
300000, 79483, 0, 0
360000, 79454, 0, 0
420001, 79556, 0, 0
480000, 79343, 0, 0
540000, 79049, 0, 0
600001, 78776, 0, 0
660000, 78029, 0, 0
720000, 78023, 0, 0
780001, 77554, 0, 0
840000, 77225, 0, 0
900000, 76945, 0, 0
960000, 67886, 0, 0
1020001, 65353, 0, 0
1080000, 64239, 0, 0
1140000, 62856, 0, 0
1200000, 61628, 0, 0
1260000, 60328, 0, 0
1320000, 58853, 0, 0
1380000, 72292, 0, 0
1440000, 79839, 0, 0
1500000, 79852, 0, 0
1560000, 79879, 0, 0
I set the ss_ramp to 3600s and fio should run 1 hour before start steady state detection but it only run 1560 seconds  including the steady state detection phase( I set the ss_dur as 1800s)

Here is another set of fio options
fio --ioengine=libaio --direct=1 --thread --norandommap --group_reporting --log_avg_msec=60000 --per_job_logs=0 --minimal --eta=always --name=RandRdPre --rw=randread --bs=4k --ss=iops:0.1% --ss_dur=3600 --ss_ramp=7200 --write_iops_log=fioinst  --filename=/dev/sda --iodepth=32  --numjobs=1
And the fio log:
60000, 81947, 0, 0
120000, 81955, 0, 0
180000, 81746, 0, 0
240000, 81715, 0, 0
300000, 81783, 0, 0
360000, 81891, 0, 0
420000, 81954, 0, 0
480000, 81855, 0, 0
540000, 81217, 0, 0
600000, 81226, 0, 0
660000, 81509, 0, 0
720000, 81776, 0, 0
780000, 81592, 0, 0
840000, 80596, 0, 0
900000, 80245, 0, 0
960000, 80146, 0, 0
1020000, 79937, 0, 0
1080000, 79660, 0, 0
1140000, 74609, 0, 0
1200000, 67226, 0, 0
1260000, 65964, 0, 0
1320000, 64709, 0, 0
1380000, 63455, 0, 0
1440000, 61814, 0, 0
1500000, 60604, 0, 0
I set the ss_ramp to 2 hours and ss_dur to 1 hour but the fio only run 1500s. I tried multiple sets of parameter on SSD from different vendors the result is exactly the same, no matter how you set the three parameter and which SSD you are testing fio will run only 1500s. if we graph the data we can see the steady state is not achieved...
![randrd_iops-2draw](https://user-images.githubusercontent.com/30696585/45661293-707e9100-bb2f-11e8-90ea-5c64e548e1f4.png)
I tested on fio-3.5 and fio-3.9 the result is also the same, can anybody help to fix this? Thanks.

**Comment by sitsofe** [comment]
Mentiong @vincentkfu in case he has ideas on this one...

**Comment by vincentkfu** [comment]
fio has most likely read an amount of data equal to the size of your device and ended the job before even considering whether steady state has been attained. Try adding the following options:

```
--time_based
--runtime=24h
```

fio will run 24h if steady state is never attained but will stop earlier if your steady state criterion is met.

**Comment by sitsofe** [comment]
@tyneliu did Vincent's comment help you?

**Comment by tyneliu** [comment]
I am still doing the data collection, will keep update.

**Comment by tyneliu** [comment]
Thanks  @vincentkfu and @sitsofe 
These two options works for me and I can get the steady state like this and it is achieved before the --run_time option. You can consider to add this explanation to the man page.
![randrd_iops-2draw](https://user-images.githubusercontent.com/30696585/45857437-3b6e7a80-bd8b-11e8-8ea0-60443a51e8e7.png)
another question for @vincentkfu , can I assign two --ss option at the same time? for example -ss=iops:2% --ss=iops_slope:1% . I want to monitor both the variation range and the trend.

**Comment by sitsofe** [comment]
@tyneliu Hang on a moment:
1. It's a bit sneaky to repurpose an issue for secondary or more different issues and is generally considered considered bad netiquette (it's generally one problem = one issue and further problems are expected to be new issues but see below).
2. Your latest query isn't so much an issue in fio and is more of a "How do I?" question. As such it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58).

Because your original problem has been solved I'm going to close this issue now and recommend you re-ask your latest question on the mailing list but if Vincent feels like replying here he will still be able to do so after this is closed.

**Comment by vincentkfu** [comment]
> can I assign two --ss option at the same time? for example -ss=iops:2% --ss=iops_slope:1% . I want to monitor both the variation range and the trend.

There is currently no way to use two criteria at the same time. However, with --output-format=json, you can see the per second measurements the steady state feature is using and check the second criterion after the fact.
