### ISSUE TITLE
FIO ignores "lat_percentiles=1" when the --output-format is json

### ISSUE THREAD

**Issue by xweichu** [axboe/fio#691]
FIO job:
file name: R0.5MB.fio
===========================

[global]
ioengine=libaio
iodepth=1
direct=1
size=50g
lat_percentiles=1

\[Read-0.5MB\]
rw=read
bs=512k
directory=/mnt/cephfs/FIO/0.5MB/

===========================
The plain text result show lat percentiles instead of clat percentile correctly if just run the command fio R0.5MB.fio. 

However, the json output is not correct when running fio with command fio R0.5MB.fio --output-format=json --output=test.json. Values of clat_percentiles are included instead of lat_percentiles.

FIO version: fio-3.10-15-ged060

**Comment by axboe** [comment]
Pushed a fix for this, please re-test. Thanks!
