### ISSUE TITLE
Low IOPS while running FIO against multiple NVMoF targets

### ISSUE THREAD

**Issue by jjpcat** [axboe/fio#694]
Host: i9-7940X (14c/28t); Ubuntu 17.10 (kernel 4.13.0-46). FIO: 2.16. 

The host has 1 100G NIC connected to a switch. 4 NVMoF targets (running RoCEv2, each has a 25G NIC) are also connected to the switch. Those 4 targets are identical (OS, CPU, NIC, SSD, etc.)

When I run FIO randread on the host against 1 target (iodepth=32, numjobs=4), I get 670K 4K IOPS. This is expected, as this is limited by 25G NIC. When I run FIO randread against 2 targets (--filename=/dev/nvme0n1:/dev/nvme1n1, iodepth=64, numjobs=8), I get 1330K 4K IOPS. This is still good. The problem is that, when the target count is increased to 3 or 4, IOPS barely moves. For example, with 4 targets, I am getting around 1500K IOPS. Here's the command I use:

sudo fio --name=dummy --runtime=60 --time_based=1 --filename=/dev/nvme0n1:/dev/nvme1n1:/dev/nvme2n1:/dev/nvme3n1 --ioengine=libaio --direct=1 --rw=randread -bs=4k --iodepth=64 --numjobs=14 --group_reporting

I tried iodepth=128 and/or numjobs=28. But IOPS stays the same. 

I used iperf to verify that the host, the switch and the NIC are able to run at full 100G speed. Also, "top" shows the CPU is only about 60% loaded when I test against 4 targets. 

So what adjustment can I make here so that I can see ~2600K IOPS when I test against 4 targets?

Thanks.

**Comment by axboe** [comment]
You want to have separate jobs drive single drives, if your goal is max performance. Do a separate job section for each drive, each with a job or two (experiment).

**Comment by jjpcat** [comment]
I tried it. But the aggregated IOPS is still stuck at 1500K. Here's my config file:

[global]
name=dummy
runtime=60
time_based=1
ioengine=libaio
direct=1
rw=randread
bs=4k

[job0]
filename=/dev/nvme0n1
iodepth=32
numjobs=4
group_reporting
[job1]
filename=/dev/nvme1n1
iodepth=32
numjobs=4
group_reporting
[job2]
filename=/dev/nvme2n1
iodepth=32
numjobs=3
group_reporting
[job3]
filename=/dev/nvme3n1
iodepth=32
numjobs=3
group_reporting

**Comment by axboe** [comment]
You're running out of steam somewhere. I can't say where since I don't have access to your system, but some resource is limiting the performance you are getting.

**Comment by axboe** [comment]
You also want to update your fio version, 2.16 is pretty old. Probably won't change much for you, however.

**Comment by sitsofe** [comment]
@jjpcat I notice you kinda sort of asked this question ("How do I make fio go faster?" aka "How do I add go faster stripes to fio?", "How do I improve my fio hero numbers?") before over in #579 . It's unclear how much you worked through those suggestions that were there (if you haven't I strongly recommend doing so) but at any rate I think there was a key piece of advice from that issue that you overlooked when you made this new question so I'll summarise it in here as it remains relevant to your latest posting:

> As this isn't so much an issue in fio and more of a "How do I?" question **your question is better sent to the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58)** (be aware that the mailing list only accepts plain text emails). I'll note there has been the occasional "What are go faster options for fio?" questions on the mailing list in the past (e.g. https://www.spinics.net/lists/fio/msg07221.html , https://www.spinics.net/lists/fio/msg05451.html ) and the issue tracker (https://github.com/axboe/fio/issues/579#issuecomment-382327888  ). Further, there are examples of the jobs people used to reach high IOPS in various places (e.g. https://marc.info/?l=linux-kernel&m=140313968523237&w=2 ).

Given the above, I'm going to close the issue here but you might get a more useful response if you were to repost it on the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.10/README#L58) (you never know until you try!)...
