### ISSUE TITLE
IO on CIFS mountpoint is failing

### ISSUE THREAD

**Issue by paraggit** [axboe/fio#707]
I have exported cifs share with rw,allow=all option from RHEL 7.5 server.
and mounted it over client using below command
#mount -t cifs //192.168.2.10/fs2 /mnt -o username=root,password=XYZ
after starting IO workload its giving error as mention below.
fio output

[root@galvin /]# /root/fio --direct=1 --ioengine=sync --numjobs=1 --status-interval=2 --rw=randrw --bssplit=4k --rwmixread=50 --group_reporting=1 --runtime=60 --size=100m --time_based --filename=/mnt/file1 -name=test
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=sync, iodepth=1
fio-3.11-6-gee6ce
Starting 1 process
test: Laying out IO file (1 file / 100MiB)
fio: pid=0, err=13/file:filesetup.c:138, func=unlink, error=Permission denied

Run status group 0 (all jobs):

I have tried every thing like setting file permission as 777 but its not working.

**Comment by szaydel** [comment]
I don't think I have ever done any testing with SMB mountpoint, but this certainly sounds like a file creation issue. What might be valuable here is pre-creating that file to see if `fio` can use it, or if same issue arises. I think `strace` (I am assuming client is linux) will be highly informative in this case.

**Comment by sitsofe** [comment]
Closing because we need more information from the reporter to take this further.

@paraggit  - please re-open this issue if/when you're able to do more supply the requested information. Thank you!
