### ISSUE TITLE
unit_base is not working as expected

### ISSUE THREAD

**Issue by MohanrajBabu** [axboe/fio#717]
Hi,

**Description**:
Set the option --unit_base=1 or --unit_base=8 while running a fio job.

Expected behavior:
Based on the value set stats should print as byte based or bit based.

Actual Behavior::
Throws value not allowed error.

**Linux distro and kernel version**
Ubuntu 18.04
4.15.0-29-generic

**fio version**
fio-3.12-17-g0fcbc0

**Steps to reproduce:**

[bash] fio --name=fio_job1 --unit_base=0 --size=10m
fio_job1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.12-17-g0fcbc0
Starting 1 process

fio_job1: (groupid=0, jobs=1): err= 0: pid=25851: Sat Nov 24 23:13:17 2018
  read: IOPS=37.1k, BW=145MiB/s (152MB/s)(10.0MiB/69msec)
    clat (nsec): min=921, max=18337k, avg=24470.59, stdev=472447.51
     lat (nsec): min=964, max=18337k, avg=24615.23, stdev=472447.44
    clat percentiles (nsec):
     |  1.00th=[     948],  5.00th=[     988], 10.00th=[    1012],
     | 20.00th=[    1048], 30.00th=[    1080], 40.00th=[    2896],
     | 50.00th=[    2992], 60.00th=[    3024], 70.00th=[    3056],
     | 80.00th=[    3120], 90.00th=[    3248], 95.00th=[    3664],
     | 99.00th=[  382976], 99.50th=[  505856], 99.90th=[ 9502720],
     | 99.95th=[11730944], 99.99th=[18219008]
  lat (nsec)   : 1000=6.25%
  lat (usec)   : 2=30.43%, 4=58.95%, 10=1.80%, 20=0.62%, 50=0.27%
  lat (usec)   : 250=0.08%, 500=1.05%, 750=0.43%
  lat (msec)   : 10=0.04%, 20=0.08%
  cpu          : usr=16.18%, sys=7.35%, ctx=42, majf=0, minf=10
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=2560,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=145MiB/s (152MB/s), 145MiB/s-145MiB/s (152MB/s-152MB/s), io=10.0MiB (10.5MB), run=69-69msec

Disk stats (read/write):
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

[bash] fio --name=fio_job1 --unit_base=8 --size=10m
fio: value 8 not allowed:
        valid values: 0          Auto-detect
                    : 8          Normal (byte based)
                    : 1          Bit based

fio: failed parsing unit_base=8

[bash] fio --name=fio_job1 --unit_base=1 --size=10m
fio: value 1 not allowed:
        valid values: 0          Auto-detect
                    : 8          Normal (byte based)
                    : 1          Bit based

fio: failed parsing unit_base=1

Thanks and Regards,
Mohan

**Comment by axboe** [comment]
Huh odd, thanks for reporting. I checked in a fix for it.
