### ISSUE TITLE
Weird bandwidth results with posixAIO working with single file and multi files

### ISSUE THREAD

**Issue by yijieZ** [axboe/fio#718]
As I learned one PosixAIO thread would service for one file descriptor,but I got a worse bandwidth with filename=multi files than filename=single file as other settings are the same.

`ioengine=posixaio
direct=1
rw=write
bs=1KB
size=16g
directory=./
iodepth=32
filename=./fio-16g.0.0`

**Comment by sitsofe** [comment]
@yijieZ Hi,

Could you clarify this a bit more? When filing new issues on fio we usually end up needing the information requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS to take an issue further. Could you at least show your original command line and the results then contrast this with another command line and the results that achieved and add which platform and which version of fio you are using. Then you can highlight exactly the differences.

Re POSIX AIO: your platform may have inherent limitations in its POSIX AIO implementation. For example: if your platform is Linux where it is typically glibc that *emulates* POSIX AIO via thread pool then you have to in-turn understand the limitations of the glibc AIO implementation. Here's a comment snippet from the glibc source code for its POSIX AIO implementation (https://github.com/bminor/glibc/blob/glibc-2.28/sysdeps/pthread/aio_misc.c#L359 ):

```
       /* The current file descriptor is worked on.  It makes no sense
	 to start another thread since this new thread would fight
	 with the running thread for the resources.  But we also cannot
```

Over in https://blog.linuxplumbersconf.org/2009/slides/Anthony-Liguori-qemu-block.pdf the QEMU folks note this this means [glibc's POSIX AIO]

> Cannot support multiple AIO requests in flight on a single file descriptor

Also note that Jens (fio's author) has little love for `posixaio` on Linux https://github.com/axboe/fio/issues/703#issuecomment-428714558 .

At any rate @yijieZ could you let us know more information and if this answers your question can you close this issue? Thanks!

**Comment by yijieZ** [comment]
Sorry for my unclear question!
I run fio-3.7-66-gedfc on 4.15.7 Linux Kernel.
 
Here is my fio code:
`[posixaio-write]
ioengine=posixaio
direct=1
buffered=0
rw=write
bs=4k
size=8g
directory=./
numjobs=1
iodepth=32
filename=./posixaio-write.0.0

time_based=1
runtime=20`
and the bandwidth of its result is 64.7MiB/s on my machine.

When I change the **filename=./posixaio-write.0.0** to **filename=./posixaio-write.0.0:./posixaio-write.0.1:./posixaio-write.0.2**, the bandwidth of this test go down to 10.4MiB/s.

According to 

>        /* The current file descriptor is worked on.  It makes no sense
	 to start another thread since this new thread would fight
	 with the running thread for the resources.  But we also cannot

 I think the test with multi files should get the higher bandwidth, but the results are opposite. 
It confused me.

**Comment by sitsofe** [comment]
@yijieZ not to worry - you're clarifying things now :-)

```
filename=./posixaio-write.0.0:./posixaio-write.0.1:./posixaio-write.0.2
```
The job you've specified doesn't use multiple files simultaneously (just specifying multiple files in the `filename` is not enough). It is currently saying you want to use the first file and then when that's done the second file and then when that's done the third file and then when that's done stop. Only one file will be open at any given time AND you'll be occasionally changing files (roughly every 2.7GBytes). See https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename and https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-file-service-type for details.

Is this clearer?

**Comment by sitsofe** [comment]
(PS: `direct=1` and `buffered=0` are synonyms of each other. A bit like the sentence I'm typing it's redundant to specify both in the same job  - specifying `direct=1` is enough)

**Comment by yijieZ** [comment]
Thanks for your reply!

And may I ask how to set up to use multiple files simultaneously?
I want to validate the posixaio characteristics with fio.

**Comment by sitsofe** [comment]
@yijieZ No problem. Hmm we're getting a bit off-topic for an issue so maybe we should close this and take it to the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails)? What do you think?

**Comment by yijieZ** [comment]
OK!
Appreciating your help!
