### ISSUE TITLE
Q: UT events

### ISSUE THREAD

**Issue by universalbodge** [axboe/fio#722]
I am getting UT events in the blktrace while running fio

259,1    4       10     0.000371656 15754 **UT**   N [fio] 1

According to the blkparse man

P -- plug
U -- unplug
T -- unplug due to timer

but there are no P events in the trace

Please, can somebody elaborate on this?

Thanks in advance

**Comment by sitsofe** [comment]
@universalbodge Hi!

As this isn't really an issue in `fio`, I think you would be better asking this to the the linux-btrace folks (mailing list over on http://vger.kernel.org/vger-lists.html#linux-btrace ) or the linux-block mailing list (http://vger.kernel.org/vger-lists.html#linux-block )...

**Comment by sitsofe** [comment]
@universalbodge As this isn't really a question about fio itself I think this question is better aimed at people who are actively working on the kernel block layer and thus are better placed to answer this. As such I'm closing this issue here. Thanks!
