### ISSUE TITLE
rw_sequencer=identical setting issue

### ISSUE THREAD

**Issue by TJ-X** [axboe/fio#725]
I have tried to design a random pattern. I used random read and want to it repeat at the offset for specified times and it got next offset to do the same thing. I used rw_sequencer and set it as identical to generate this pattern and I found out it will not repeat at the offset. I have also tried set the rw_sequencer  as sequential but it works, it get a random offset and than it continuously repeat the command and have sequential LBA. I checked the command, address and block size by using BusHound software.

I would like to know if there is any parameter I need to set for using rw_sequence=identical, or anything I should pay attention to?

Here is the platform information and script below:
* OS: Windows 7
* FIO version: 3.12-x64

**FIO script:**
[RandomWriteTest]
filename=\\.\physicaldrive3
filesize=4Mi
name=mytest
group_reporting
direct=1
buffered=0
thread=1
numjobs=1
iodepth=64
randrepeat=0

**readwrite=randread:8**   ;repeat 8 times and jump to next random offset
**rw_sequencer=identical**  ;start at the same address when repeating
blocksize=8k

**Comment by sitsofe** [comment]
@TJ-X While I think there might be some small misbehaviour here I don't think your main issue is a bug but rather a complex interaction due to your use of `iodepth`:

In the following I gather up the offsets that fio generates by scraping its debug output then I push that through `uniq` to work out how long the runs are:

```
$ rm fio.tmp; ./fio --iodepth=1 --debug=io --name=sameoffset --filesize=1M --direct=1 --randrepeat=0 --rw=randread:8 --rw_sequencer=identical --bs=8k --ioengine=libaio --filename=fio.tmp | awk -F '[,=]' '/complete.*off/ { print $2 }' | uniq -c
      7 0x0
      8 0xc8000
      8 0xf6000
      8 0xb6000
      8 0x7e000
      8 0xa6000
      8 0x50000
      8 0xca000
      8 0x92000
      8 0x80000
      8 0xda000
      8 0xb4000
      8 0x52000
      8 0x84000
      8 0x96000
      8 0xee000
      1 0x4e000
```

On the above run the `iodepth=1`. There does appear to be an issue with the number of offsets generated for the first I/O but I'm guessing that's not your main issue.

```
$ rm fio.tmp; ./fio --iodepth=64 --debug=io --name=sameoffset --filesize=1M --direct=1 --thread=1 --randrepeat=0 --rw=randread:8 --rw_sequencer=identical --bs=8k --ioengine=libaio --filename=fio.tmp | awk -F '[,=]' '/complete.*off/ { print $2 }' | uniq -c
      7 0x0
      8 0xdc000
      8 0x26000
      8 0x3c000
      8 0x62000
      8 0x6e000
      8 0xa8000
      3 0xec000
      8 0x2000
      4 0x54000
      1 0xa0000
      2 0x54000
      1 0xa0000
      2 0x54000
      6 0xa0000
      8 0xcc000
      8 0xb0000
      8 0x82000
      8 0x14000
      5 0x92000
      1 0x74000
      3 0x92000
      5 0xec000
```

On the above run `iodepth=64`. Now while fio can send down simultaneous I/Os there's no telling what order they will actually turn up to the disk in or that they will actually complete in because there's no guarantee all the I/Os will complete in the order they were submitted in.

Thoughts?

**Comment by TJ-X** [comment]
@sitsofe highly appreciate your feedback!

I think I find the root cause.
I rechecked my BusHound setting and I found out that I set the "merge Repeated Commands" and I ignored the merged commands. So after unchecking this setting, it showed correct command trace.

And I also tried different iodepth to check if it also effected the startLBA address, the result showed that there is sill in sequence by following commands. It seemed that iodepth would not effect the order.

Here is the BusHound log:

1. iodepth=64
readwrite=randread:8
rw_sequencer=identical

|iodepth=64 |WriteCMD   | StartLBA |    BlockSize|
|-------|---------------|---------------|--------|
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  00 00 00 00 | 10 00 |   
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  02 10 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 |  
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 
| CMD |  28 00 00 00 |  04 90 00 00 | 10 00 | 


2. iodepth=1
readwrite=randread:8
rw_sequencer=identical

|iodepth=1 |WriteCMD   | StartLBA |    BlockSize|
|--------|--------------|-------------|--------|
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |       
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |     
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |     
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |     
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |     
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |     
| CMD |   28 00 00 00|  00 00 00 00 | 10 00      |      
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |        
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  02 40 00 00 | 10 00      |    
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      |        
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 
| CMD |   28 00 00 00|  05 10 00 00 | 10 00      | 


3. iodepth=64
readwrite=randread:8
rw_sequencer=sequential

|iodepth=64 |WriteCMD   | StartLBA |    BlockSize|
|--------|--------------|-------------|--------|
   | CMD |   28 00 00 00 | 00 00 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 10 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 20 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 30 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 40 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 50 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 60 00 00 | 10 00|
  | CMD |   28 00 00 00 | 02 c0 00 00 | 10 00|
  | CMD |   28 00 00 00 | 02 d0 00 00 | 10 00|
  | CMD |   28 00 00 00 | 02 e0 00 00 | 10 00|
  | CMD |   28 00 00 00 | 02 f0 00 00 | 10 00|
  | CMD |   28 00 00 00 | 03 00 00 00 | 10 00|
  | CMD |   28 00 00 00 | 03 10 00 00 | 10 00|
  | CMD |   28 00 00 00 | 03 20 00 00 | 10 00|
  | CMD |   28 00 00 00 | 03 30 00 00 | 10 00|
  | CMD |   28 00 00 00 | 00 80 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 90 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 a0 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 b0 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 c0 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 d0 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 e0 00 00 | 10 00|           
  | CMD |   28 00 00 00 | 00 f0 00 00 | 10 00|  

3. iodepth=1
readwrite=randread:8
rw_sequencer=sequential

|iodepth=1 |WriteCMD   | StartLBA |    BlockSize|
|--------|--------------|-------------|--------|
| CMD  |  28 00 00 00 | 00 00 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 10 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 20 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 30 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 40 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 50 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 00 60 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 50 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 60 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 70 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 80 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 90 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 a0 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 b0 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 c0 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 30 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 40 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 50 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 60 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 70 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 80 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 90 00 00 | 10 00 | 
| CMD  |  28 00 00 00 | 05 a0 00 00 | 10 00 |

**Comment by sitsofe** [comment]
@TJ-X OK looks good. I was looking at completion arrivals so it could well be the case that the submission order was correct. Note that your trace shows the weird "initial 7" behaviour my debugging did so there's a mild issue there but hopefully no major issue and given that could you close this issue? Thanks!

**Comment by TJ-X** [comment]
Hi, @sitsofe 
Thanks to the reply!! 
I also noticed that there is an "initial 7", no matter sequential or identical sequencer is set, the first is always lack of one command. Is that special setting in FIO?

**Comment by sitsofe** [comment]
Oops I overlooked your question:

> I also noticed that there is an "initial 7", no matter sequential or identical sequencer is set, the first is always lack of one command. Is that special setting in FIO?

Not that I'm aware of - I'd say it's a mild bug.
