### ISSUE TITLE
FIO interleaving blocks when writing specific pattern with randrw

### ISSUE THREAD

**Issue by rxyjp2008** [axboe/fio#729]
The interleaving blocks issue appears again on a newer version of FIO: fio-3.12-24-ga031

The FIO job is shown below, it does a random read/write, with a fixed block size, it verifies as it writes, but the verification was successful. 

```
[global]
blocksize=8k
direct=1
numjobs=1
readwrite=randrw
verify_dump=1
iodepth=1
ioengine=libaio
thread=1
verify=pattern
do_verify=1
verify_pattern=0x11111111111852fb
create_on_open=1
verify_fatal=1
verify_backlog=10000


[job-/dev/mapper/mpathc]
name=job-/dev/mapper/mpathc
filename=/dev/mapper/mpathc
size=20g
offset=0


[job-/dev/mapper/mpathb]
name=job-/dev/mapper/mpathb
filename=/dev/mapper/mpathb
size=20g
offset=0


[job-/dev/mapper/mpatha]
name=job-/dev/mapper/mpatha
filename=/dev/mapper/mpatha
size=20g
offset=0


[job-/dev/mapper/mpathe]
name=job-/dev/mapper/mpathe
filename=/dev/mapper/mpathe
size=20g
offset=0

[job-/dev/mapper/mpathd]
name=job-/dev/mapper/mpathd
filename=/dev/mapper/mpathd
size=20g
offset=0
```

And it writes the block space the following pattern:

```
088fe000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
0890e000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
08910000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
08912000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
08914000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
08916000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
0891e000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
08922000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
08924000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
08926000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
08928000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
0892c000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

```
We tried this version before, and the pattern IO worked fine, but today I hit this issue again.

**Comment by sitsofe** [comment]
@rxyjp2008 Hi! It was always going to take longer to get a reply what with it being Christmas and all :-)

1. What were you expecting to happen and what did happen? You say:

    > it verifies as it writes, but the verification was successful

    Was verification meant to fail?

2. Can you make this issue happen with just one job (e.g. just the `mpathc` job by itself)?
3. Can you include the full fio output from when it fails?
4. What is the latest fio that doesn't manifest this issue?

**Comment by rxyjp2008** [comment]
Hi @sitsofe, thank you for the quick response during holiday season!
Here are the answers:
1. I did verification twice. In the first time the verification was done along with the write with option verify_backlog=1000, and it was successful; the second time the verification was done after the IO was over, so I started another job file with verify_only set to 1, but it was failed because it was expecting the pattern 11 11 11 11 11 18 52 fb but found 0000000 (the interleaving 0s). 

2. I can try that.

3. The IO job doesn't fail itself, just the written blocks don't look right (included in the original description). 
We expect the written data to be repeating pattern 11 11 11 11 11 18 52 fb, but in reality it is 11 11 11 11 11 18 52 fb ...**. 00 00 00 00 00 00 00 00 .**.. 11 11 11 11 11 18 52 fb

4. I am not sure if there is a version that definitely don't hit this issue. We tried version fio-3.12-24-ga031 mentioned above before and verified this issue did not occur, but then I found it happened again

**Comment by rxyjp2008** [comment]
Ran again with only one block device with version fio-3.12-32-g0527 , no error reported, the output is:
```
job-/dev/mapper/mpathc: (groupid=0, jobs=1): err= 0: pid=12713: Thu Dec 27 18:44:12 2018
  read: IOPS=744, BW=2980KiB/s (3051kB/s)(20.0GiB/7037923msec)
    slat (usec): min=5, max=2018, avg=16.51, stdev= 5.85
    clat (usec): min=191, max=31331, avg=915.31, stdev=1369.78
     lat (usec): min=201, max=31345, avg=932.13, stdev=1370.04
    clat percentiles (usec):
     |  1.00th=[  239],  5.00th=[  258], 10.00th=[  269], 20.00th=[  289],
     | 30.00th=[  334], 40.00th=[  375], 50.00th=[  396], 60.00th=[  424],
     | 70.00th=[  482], 80.00th=[  644], 90.00th=[ 2933], 95.00th=[ 4015],
     | 99.00th=[ 6128], 99.50th=[ 6783], 99.90th=[11863], 99.95th=[13042],
     | 99.99th=[15664]
   bw (  KiB/s): min=    8, max= 4616, per=65.88%, avg=1962.64, stdev=770.90, samples=10687
   iops        : min=    2, max= 1154, avg=490.64, stdev=192.72, samples=10687
  write: IOPS=372, BW=1489KiB/s (1525kB/s)(9.00GiB/7037707msec)
    slat (usec): min=7, max=3027, avg=18.80, stdev= 6.42
    clat (usec): min=443, max=37244, avg=788.45, stdev=857.87
     lat (usec): min=457, max=37263, avg=807.56, stdev=857.83
    clat percentiles (usec):
     |  1.00th=[  494],  5.00th=[  515], 10.00th=[  523], 20.00th=[  537],
     | 30.00th=[  545], 40.00th=[  553], 50.00th=[  570], 60.00th=[  578],
     | 70.00th=[  594], 80.00th=[  627], 90.00th=[  955], 95.00th=[ 2376],
     | 99.00th=[ 4113], 99.50th=[ 4424], 99.90th=[11731], 99.95th=[12649],
     | 99.99th=[15270]
   bw (  KiB/s): min=    8, max= 4328, per=100.00%, avg=1961.42, stdev=768.36, samples=10686
   iops        : min=    2, max= 1082, avg=490.33, stdev=192.09, samples=10686
  lat (usec)   : 250=1.97%, 500=47.54%, 750=33.67%, 1000=1.74%
  lat (msec)   : 2=3.94%, 4=7.20%, 10=3.78%, 20=0.16%, 50=0.01%
  cpu          : usr=0.82%, sys=2.12%, ctx=7863490, majf=0, minf=273
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=5242880,2620498,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=2980KiB/s (3051kB/s), 2980KiB/s-2980KiB/s (3051kB/s-3051kB/s), io=20.0GiB (21.5GB), run=7037923-7037923msec
  WRITE: bw=1489KiB/s (1525kB/s), 1489KiB/s-1489KiB/s (1525kB/s-1525kB/s), io=9.00GiB (10.7GB), run=7037707-7037707msec
```

But the written data still interleaves
```
13887000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
1388f000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
13892000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
13893000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
13895000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
13896000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
13897000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
13899000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
1389c000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
*
1389d000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
1389e000  11 11 11 11 11 18 52 fb  11 11 11 11 11 18 52 fb  |......R.......R.|
```

**Comment by sitsofe** [comment]
> The IO job doesn't fail itself, just the written blocks don't look right (included in the original description).

@rxyjp2008 Ah that's down to the fact you are running a `rw=randrw` job (the parts where the initial phase was only doing a read will be untouched). From https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-readwrite we can see `randrw` means:

> **randrw**
> Random mixed reads and writes.

By default (and without verification) that means that I/O will be done across the region (in your case 20GBytes from the start). Some blocks will be read and some blocks will be written but each block on has one of the types of I/O done to it e.g. imagine a sequence of alternating reads and writes.

When verification is turned on with` rw=readwrite`/`rw=randrw` jobs things get complicated. Verify jobs are often split into two parts: the initial layout part and the verification part. When a job is a "pure" write job this is easy - writes happen the those writes are verified. However:

* If you ask for a pure verifying `read`/`randread` job then the **data already on the disk will be verified** during the first stage (this catches out a lot of people e.g. https://www.spinics.net/lists/fio/msg07670.html ).
* If you ask for a verifying `readwrite`/`randrw` job then during the first phase if a read occurs the data read will only be verified IF that block was somehow already written by the same job earlier. When the second phase starts it will ONLY verify those blocks that were written.

You can see this being alluded to over in the [documentation for the `verify` option](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify):

> If the data direction given is a read or random read, fio will assume that it should verify a previously written file. If the data direction includes any form of write, the verify will be of the newly written data.

Do the gaps make sense now and if so can you close this issue? Thank!

**Comment by rxyjp2008** [comment]
@sitsofe Thank you for the clarification, this is very helpful! I'm closing the issue.
