### ISSUE TITLE
verify_only option fails with verify: bad header numberio 1, wanted 0

### ISSUE THREAD

**Issue by tomerg-lb** [axboe/fio#732]
**Created the following configuration file: write_to_file.fio**
[write_with_verify]
filename=/tmp/fiofile
direct=1
rw=write
bs=4096
verify=md5
size=128k
do_verify=1

**I then run:**
fio write_to_file.fio

**Result:**
write_with_verify: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.11
Starting 1 process

write_with_verify: (groupid=0, jobs=1): err= 0: pid=4205: Wed Jan  9 17:43:43 2019
   read: IOPS=6400, BW=25.0MiB/s (26.2MB/s)(128KiB/5msec)
    clat (usec): min=106, max=164, avg=113.44, stdev=11.66
     lat (usec): min=107, max=165, avg=113.96, stdev=11.68
    clat percentiles (usec):
     |  1.00th=[  108],  5.00th=[  108], 10.00th=[  108], 20.00th=[  109],
     | 30.00th=[  109], 40.00th=[  109], 50.00th=[  109], 60.00th=[  111],
     | 70.00th=[  113], 80.00th=[  114], 90.00th=[  127], 95.00th=[  135],
     | 99.00th=[  165], 99.50th=[  165], 99.90th=[  165], 99.95th=[  165],
     | 99.99th=[  165]
  write: IOPS=6400, BW=25.0MiB/s (26.2MB/s)(128KiB/5msec)
    clat (usec): min=108, max=415, avg=134.05, stdev=56.11
     lat (usec): min=119, max=442, avg=145.99, stdev=58.65
    clat percentiles (usec):
     |  1.00th=[  110],  5.00th=[  110], 10.00th=[  110], 20.00th=[  111],
     | 30.00th=[  111], 40.00th=[  115], 50.00th=[  118], 60.00th=[  122],
     | 70.00th=[  131], 80.00th=[  137], 90.00th=[  161], 95.00th=[  215],
     | 99.00th=[  416], 99.50th=[  416], 99.90th=[  416], 99.95th=[  416],
     | 99.99th=[  416]
  lat (usec)   : 250=98.44%, 500=1.56%
  cpu          : usr=25.00%, sys=0.00%, ctx=65, majf=0, minf=14
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=32,32,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=25.0MiB/s (26.2MB/s), 25.0MiB/s-25.0MiB/s (26.2MB/s-26.2MB/s), io=128KiB (131kB), run=5-5msec
  WRITE: bw=25.0MiB/s (26.2MB/s), 25.0MiB/s-25.0MiB/s (26.2MB/s-26.2MB/s), io=128KiB (131kB), run=5-5msec

Disk stats (read/write):
  vda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Now I added to the configuration file one line:**
verify_only=1
And got:
write_with_verify: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.11
Starting 1 process
verify: bad header numberio 1, wanted 0 at file /tmp/fiofile offset 4096, length 4096
write_with_verify: No I/O performed by psync, perhaps try --debug=io option for details?
fio: pid=4323, err=84/file:io_u.c:2029, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character

write_with_verify: (groupid=0, jobs=1): err=84 (file:io_u.c:2029, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=4323: Wed Jan  9 17:46:09 2019
   read: IOPS=2000, BW=8000KiB/s (8192kB/s)(8192B/1msec)
    clat (usec): min=173, max=424, avg=299.02, stdev=177.18
     lat (usec): min=174, max=425, avg=299.99, stdev=177.33
    clat percentiles (usec):
     |  1.00th=[  174],  5.00th=[  174], 10.00th=[  174], 20.00th=[  174],
     | 30.00th=[  174], 40.00th=[  174], 50.00th=[  174], 60.00th=[  424],
     | 70.00th=[  424], 80.00th=[  424], 90.00th=[  424], 95.00th=[  424],
     | 99.00th=[  424], 99.50th=[  424], 99.90th=[  424], 99.95th=[  424],
     | 99.99th=[  424]
  lat (usec)   : 250=2.94%, 500=2.94%
  cpu          : usr=0.00%, sys=0.00%, ctx=4, majf=0, minf=21
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=33.3%, 4=66.7%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=2,32,0,0 short=0,0,0,0 dropped=0,0,0,0

Run status group 0 (all jobs):
   READ: bw=8000KiB/s (8192kB/s), 8000KiB/s-8000KiB/s (8192kB/s-8192kB/s), io=8192B (8192B), run=1-1msec

Disk stats (read/write):
  vda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

What am I doing wrong?

**Comment by sitsofe** [comment]
@tomerg-lb Did you ensure the file you were verifying had been written by fio run that was writing verify headers to the file? If the file has been deleted between the runs (or written over with zeros) you would get an error such as the one you described?

**Comment by sitsofe** [comment]
This does look like a bug - I get errors with the following:
```
fio --randseed=1 --stonewall --direct=1 --rw=write --bs=4096 --verify=md5 --size=128k --filename=fiofile --name=write_verify --do_verify=1 --name=verify --verify_only=1
write_verify: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
verify: (g=1): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.12-20-g4cf3
Starting 2 processes
verify: bad header numberio 1, wanted 0 at file fiofile offset 4096, length 4096 (requested block: offset=4096, length=4096)
fio: pid=13666, err=84/file:io_u.c:2033, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character
```

Even explicitly loading a state file doesn't resolve the issue.

**Comment by sitsofe** [comment]
1. Most of those options came before the first `--name` so the second job contains 95% of the same options as the first (only `do_verify=1` would have been missing (which defaults to 1 anyway) and `--verify_only=1` was added).
2. Not really - I'm rather snowed under with regular work :-) and I can't speak for others like Jens (who seems on a roll with the io_urine^Wio_uring work :-) ). You could change the `write` to `read` in the second job and leave off `--verify_only` and it will likely do what you need though...

**Comment by tomerg-lb** [comment]
@sitsofe, any update on this?
We are using fio to test a complex storage system and I really need a way to verify that the data written to a certain LBA is still actually there.

**Comment by sitsofe** [comment]
@tomerg-lb I personally (and only speaking for myself) simply don't much free time (if anything I have even less free time than in January!) but if you're up to it have a go at an investigation of your own and see if you can create a patch to fix it (if you work in a company of other programmers you may also be able to call on them for help making the patch)! If you succeed please submit it here for inclusion/review! Another approach is to try reaching out via the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) for help investigating/coding a fix (there are no guarantees though)...

**Comment by Stan-He** [comment]
@sitsofe  I can reproduce the same issue in the latet version fio-3.13

```
//everthing ok
fio --filename=/dev/nvme0n1 --size=1M --rw=write --ioengine=libaio --direct=1 --verify=crc32 --verify_dump=1 --name=test --bs=512b 
//verify: bad header numberio
fio --filename=/dev/nvme0n1 --size=1M --rw=write --ioengine=libaio --direct=1 --verify=crc32 --verify_dump=1 --name=test --bs=512b -verify_only=1
```
Then I did some debugging, I found that when using verify_only=1，the io_u->numberio get from ipo->numberio is always zero which cause the verify fail.

if you know how the ipo(io_piece) works, please let me know,  I am trying to keep on debugging

```
verify.c  get_next_verify
...
    if (ipo) {
        td->io_hist_len--;

        io_u->offset = ipo->offset;
        io_u->buflen = ipo->len;
        io_u->numberio = ipo->numberio;
        io_u->file = ipo->file;
        io_u_set(td, io_u, IO_U_F_VER_LIST);
...

```

**Comment by sitsofe** [comment]
@Stan-He Hmm... I wonder if the code around https://github.com/axboe/fio/blob/46ff70e8795e91acb2ffc041e6c1fdb4e157dff4/verify.c#L853 is correct? It doesn't seem to matter that `loops=0` in this case - we don't seem to have bothered calculating and filling in `io_u->numberio` ...

**Comment by sitsofe** [comment]
@Stan-He Another thought: maybe `numberio` isn't being filled in because it's being skipped by https://github.com/axboe/fio/blob/2041bd343da1c1e955253f62374588718c64f0f3/backend.c#L1514 ?

**Comment by sitsofe** [comment]
@gwendalcr thanks for fixing this up!
