### ISSUE TITLE
buffer_pattern='filename' requires extra escaping

### ISSUE THREAD

**Issue by scaleoutsean** [axboe/fio#733]
Version: 3.1.2 on Ubuntu 16.04.

It seems either the docs or the code may need to be changed to handle `'filename'` or indicate that an [additional](https://github.com/axboe/fio/commit/a1554f6519e7c91b262a35486d100d757b3b5b8a#diff-80dbe7ba2d53fde5c781b0729271dc31R336) set of escapes are necessary for `buffer_pattern='filename'` to work.

This works, including in combination with other patterns, in zsh 5.1.1 and bash 4.3.48(1)-release: 

```
fio --buffer_pattern=\'libfio.c\' ...
```

**Comment by sitsofe** [comment]
@scaleoutsean Hi,
the docs are assuming you are typing things into a job file. If you are typing something into into a shell via a command line argument then don't you have to know and understand your shell's rules?

**Comment by scaleoutsean** [comment]
Ok, closing now.

I wasn't aware of the assumption.

**Comment by sitsofe** [comment]
@scaleoutsean Yeah it's a bit subtle but notice how the examples don't have leading double dashes in front of them.

Given the range of potential shells out there and the fact that you may just be using a job file adding a warning without confusing people gets complicated...
