### ISSUE TITLE
Avoid I/Os out of host system cache using ioengine libpmem devdax mmap

### ISSUE THREAD

**Issue by andresrubiop** [axboe/fio#734]
Hello, I would like to have a recommendation to avoid I/Os out of host system cache using ioengine= libpmem mmap or devdax. Before I did it in libaio with the direct parameter.

**Comment by sitsofe** [comment]
@andresrubiop did the above answer your question and if so can you close this issue? Thanks!

**Comment by andresrubiop** [comment]
Yeah it does actually. Thanks!!

**Comment by sitsofe** [comment]
@andresrubiop You're welcome!
