### ISSUE TITLE
fio client/server with different job files hang

### ISSUE THREAD

**Issue by aasraoui** [axboe/fio#737]
Not able to run fio with client/server using different job files, 

debugs are listed below:

fio --size=100 --client=intel01 jobfile-w-intel1.cfg --client=intel04 jobfile-w-intel4.cfg --client=amd1 jobfile-w-amd1.cfg --client=amd2 jobfile-w-amd2.cfg --output=/root/fio/scripts/RW_4KB_16NVMe.txt

<amd1> job: you need to specify size=
<amd1> fio: pid=0, err=22/file:filesetup.c:961, func=total_file_size, error=Invalid argument
<amd1> job: you need to specify size=
<amd1> fio: pid=0, err=22/file:filesetup.c:961, func=total_file_size, error=Invalid argument
<amd1> job: you need to specify size=
<amd1> fio: pid=0, err=22/file:filesetup.c:961, func=total_file_size, error=Invalid argument
<amd1> job: you need to specify size=

**Comment by sitsofe** [comment]
I think we would have to see the contents of the job files to understand this...

**Comment by sitsofe** [comment]
Closing because we need more information from the reporter to take this further.

@aasraoui  - please re-open this issue if/when you're able to do more supply the requested information. Thank you!
