### ISSUE TITLE
fio how to run mix workload all 4 patterns in one job file?

### ISSUE THREAD

**Issue by mallilinux1978** [axboe/fio#741]
Example: 60% randread, 20% randwrite, 10% seqread, 10% seqwrite

i tried a bit by reading fio guide but not getting it quite right so appreciated if anyone has done this already and share the job file please?

[sybase-like]	
bs=2k
rw=randrw
percentage_random=80
rwmixread=70
rwmixwrite=30

**Comment by sitsofe** [comment]
@mallilinux1978 Sadly this is going to be hard as you want to balance your workload more than two ways ([flow](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-flow) almost gets you there but not quite).

**Comment by szaydel** [comment]
@mallilinux1978, it is possible to just setup two or more independent configurations and run them all concurrently. Or are you looking for consolidated reporting?

**Comment by mallilinux1978** [comment]
yes all as one test or a job from FIO perspective. Basically we're trying to simulate OLTP workload where every transaction will do 4 patterns for example table space are random and logs are sequential. from a reporting perspective, these metrics are they key (IOPs, Latency & Throughput) in total as well as read/write ratio. 

Other synthetic tools like EMC IORATE and VDBENCH support 4 patterns in one test.

**Comment by sitsofe** [comment]
If VDBench is working for you you may want to stick with it in this particular case  ;-)

FWIW this a feature I've wanted to code up (I was going to abuse flow by adding another config item that would basically make it work with "shares" calculated from a total) but there's never the time...

**Comment by szaydel** [comment]
This may be an open and shut case for the moment as @sitsofe suggested, but I am just going to ask one last thing. Why not create separate job blocks without a barrier between them? @sitsofe, correct me if I am wrong, but that should not be impossible given these requirements, however, ordering may be something that you cannot realistically control.

**Comment by sitsofe** [comment]
@szaydel running four different workloads (randread, randwrite, seqread, seqwrite) is easy (you could just create seperate jobs for these in the jobfile and ensure you don't use stonewall as you said). Maintaining the ratios between all the jobs versus all the other jobs is what makes this hard. Balancing one against one or 2vs2 (two on one side, two on the other) could be done via `flow` etc. but all vs all when you have three or more jobs is where I think you'll struggle...

**Comment by mallilinux1980** [comment]
Any idea when this will be introduced?

**Comment by sitsofe** [comment]
@mallilinux1978 All I can say is that I'm not working on this feature at the moment (and I can't speak for other developers) but if someone submits a good diff/pull request...
