### ISSUE TITLE
fio: file hash not empty on exit

### ISSUE THREAD

**Issue by wvxvw** [axboe/fio#743]
FIO version is 3.1, this test ran on CentOS 7.

```
fio: io_u.c:1867: io_completed: Assertion `io_u->flags & IO_U_F_FLIGHT' failed.
fio: pid=52921, got signal=6
...
fio: file hash not empty on exit
```

Here's the job configuration:

```
[global]
ioengine=sg
loops=1
numjobs=1
log_avg_msec=1

[emulate-postgresql]
filename=/dev/sg3
iodepth=8
size=100G
runtime=10M
bs=4k
rw=randrw
rwmixread=70
fsync=16
end_fsync=1
write_lat_log=fsync
write_bw_log=fsync
write_iops_log=fsync
```

Is it possible I don't understand something about how `sg` engine should be used?  Anyhow, it seems like an error in FIO (even if my usage is wrong).

I saw similar problems, and I looked in `dmesg` -- nothing interesting there. `iscsid` service seems fine. I can write / read to the device, no problems there.

If I screwed something up in the job configuration: what I wanted to achieve is for the job to send `Synchronize Cache(10)` SCSI command after every 16 writes.

**Comment by sitsofe** [comment]
@wvxvw Hi!

Can you make the problem happen with the latest upstream fio (https://github.com/axboe/fio/releases )?

**Comment by wvxvw** [comment]
Yes, built version 3.13 and am seeing the same behavior.

**Comment by sitsofe** [comment]
@wvxvw Good to know. Next up can you whittle down the job file? Foe example does this need `fsync` enabled to occur? Can you remove `loops=1` and `runtime`? Can you turn off all the logging etc?

**Comment by sitsofe** [comment]
(Also mentioning @vincentkfu for comment)

**Comment by sitsofe** [comment]
@wvxvw you may want to uncomment https://github.com/axboe/fio/blob/66a8a1bf98d714e013ee329dc975f3b6b552de6d/engines/sg.c#L130 assuming you're willing to be overwhelmed by debug output...

**Comment by vincentkfu** [comment]
Consider running with --debug=io. It's possible that this is related to fsync, although I have not examined that code closely.

The FIO_SGIO_DEBUG flag only enables some asserts and debug prints related to trim/unmap commands. So uncommenting that line is unlikely to help.

**Comment by axboe** [comment]
It seems to happen off the exit path, when we do:

```
		if (td->o.io_submit_mode == IO_MODE_OFFLOAD) {
			workqueue_flush(&td->io_wq);
			i = 0;
		} else
			i = td->cur_depth;

		if (i) {
			ret = io_u_queued_complete(td, i);
			if (td->o.fill_device && td->error == ENOSPC)
				td->error = 0;
		}
```
when the job is done. You can trigger this pretty easily by just setting timeout=5s or something like that.

**Comment by axboe** [comment]
Maybe an accounting error? For me, it's returning that 7 commands are still in flight, and getevents() inside io_u_queued_complete() agrees that there are 7. But apparently some/all of those are NOT marked inflight, hence we crash.

**Comment by axboe** [comment]
Took a quick look, and I think the sync logic is just broken. For the synchronous sync logic, we write the command, then read back a completion. The broken part is that this completion could be for any command that was inflight, whereas the code assumes that it's the sync command we just issued.

**Comment by axboe** [comment]
Confirmed, if I insert:

```
                assert(hdr->usr_ptr == io_u);                                   
```

inside the

```
if (do_sync)
```

part in fio_sgio_rw_doio(), then it triggers pretty quickly.

**Comment by axboe** [comment]
Pushed out a fix.
