### ISSUE TITLE
Use Free Azure Pipelines to Build Binaries?

### ISSUE THREAD

**Issue by DarwinJS** [axboe/fio#745]
I maintain a chocolatey package for fio (mainly for helping inititialize Amazon EBS volumes: https://cloudywindows.io/post/fully-automated-on-demand-ebs-initialization-in-both-bash-for-linux-and-powershell-for-windows/)

I was wondering if there would be any interest in using the free, unlimited for open source Azure pipelines to build binaries? (https://channel9.msdn.com/Shows/DevOps-Lab/Using-Azure-Pipelines-for-your-Open-Source-Project)

I might have some time to do this if it is of interest.

**Comment by DarwinJS** [comment]
FYI Bluestop.org appears to be down and I can't figure how to pull binaries from appveyor.  Appveyor also seems to build every commit without distinguishing releases?  I could be reading it wrong.

**Comment by vincentkfu** [comment]
bluestop works when using https (but not http)

https://bluestop.org/fio/

**Comment by DarwinJS** [comment]
Thanks!  I can't find a way to ask the site owner to forward http to https - not sure if you know how to ask them?

**Comment by DarwinJS** [comment]
New version of the chocolatey package is in moderation and will be visible soon at https://chocolatey.org/packages/fio

**Comment by bcran** [comment]
@DarwinJS Sorry, I switched from http to https a few months ago and didn't put in a redirect. I'll see if I can fix it to redirect http://bluestop.org/fio to https://bluestop.org/fio .

**Comment by sitsofe** [comment]
@DarwinJS is there any chance you can include a few more pieces in that chocolatey package? It would be good to include at least MORAL-LICENSE , README and HOWTO. See https://src.fedoraproject.org/rpms/fio/blob/master/f/fio.spec for a list of files that Fedora package and https://repology.org/project/fio/packages for the list of fio packages in general!

**Comment by DarwinJS** [comment]
It turns out these files already make it to the system as part of the fact the chocolateypackage uses your zip file.  To enhance the visibility of this fact, I have added the following to the installer script output!

![image](https://user-images.githubusercontent.com/11597190/54027222-b62b2680-416e-11e9-8aed-9aee57efb4a2.png)

**Comment by DarwinJS** [comment]
Actually, I just realized if I duplicate the files into the package root - they will also show up on the chocolatey website as files that people can examine - giving them more visibility.  So I have done that in addition to the above message.  Version 3.13.0.20190308 is in moderation
