### ISSUE TITLE
How to r/w a 100g-200g address space in a disk

### ISSUE THREAD

**Issue by Rmrfy** [axboe/fio#750]
### My idea
I want to  r/w a 100g-200g address space in a disk.
### This is my configure file
```
[global]
ioengine=libaio
size=100G-200G
direct=1
iodepth=8
filename=/dev/sdd
numjobs=2
group_reporting

[rand-readwrite]
rw=randrw
rwmixread=70
bs=8k
```
`I want to know is this feasible?`

**Comment by Rmrfy** [comment]
@axboe

**Comment by sitsofe** [comment]
Hello @Rmrfy!

`size` itself does not take a range (see the fio help on https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size ). In fact, the documentation of `size` suggests you can use it with [`offset`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-offset) to achieve a range...

Please be aware that it is kinder to give others a chance to reply before you explicitly start mentioning individuals. Multiple people can (and do) reply to fio Github issues but also note that what you're asking isn't so much an issue in fio and is more of a "How do I/Why is?" question. As such you might find it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails) .

**Comment by Rmrfy** [comment]
@sitsofe Thank u for your replaying

**Comment by sitsofe** [comment]
@Rmrfy If the above answers your question could you close this issue? Thanks!

**Comment by Rmrfy** [comment]
This didn't solve my problem, but I will close this issue first.
