### ISSUE TITLE
wildly inflated IOPS result from fio on Ceph with NVM OSDs

### ISSUE THREAD

**Issue by bengland2** [axboe/fio#752]
Recently  Tim Wilkinson and I have been observing that fio v3.12 on RHEL7 3.10.0-957.el7.x86_64 is outputting iops results that are wildly inflated.  For example, in the test with this command:

/usr/local/bin/fio --client=/root/vms.list.5 --output-format=json [fio.job](https://github.com/axboe/fio/files/2992483/fio_job.txt)

We get [this result](https://github.com/axboe/fio/files/2992492/fio-result.txt)  of 1492073 IOPS (in "All clients" jobname, but iostat data collected in /dev/rbd devices used for fio files reports an order of magnitude less IOPS, 162,000, and this is consistent with network and /dev/nvme0n1 throughput.  We have tried removing all logging from fio and it still happens.  These are old and slow Xeon(R) CPU X5660  @ 2.80GHz so could that somehow be distorting things?

We'll try running same test without --client using ansible to spread the fio jobs out on the hosts, see if that gives same result or not.  I suspect --client isn't that heavily used so maybe there's a bug in it.  However, all of the 50 constituent fio jobs are ~30K so it is adding them together properly.

This does not seem to happen on the same cluster when tests are run with HDD devices (which are of course much slower).

Anyone else seeing this?  For now we're working around it by measuring IOPS using iostat -mdx on /dev/rbd* but we don't want to go on for long like this.

**Comment by sitsofe** [comment]
@bengland2 if it happens quickly could you turn logging on (I'd start with https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-write-bw-log and then if the problem really happens quickly you can start using https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-debug ) and see if there's a trend that allows the isolation of the problem?

**Comment by sitsofe** [comment]
Hang on I see this:
```
        "filename" : "/mnt0/ceph/file0:/mnt0/ceph/file1:/mnt0/ceph/file2:/mnt0/ceph/file3:/mnt0/ceph/file4:/mnt1/ceph/file0:/mnt1/ceph/file1:/mnt1/ce"
```

Can you let me know how do you know that `direct=1` is definitely going to bypass the cache with the filesystem in use (I'm not trying to be difficult - I'm genuinely curious!)? Do we know you're not hitting one of the warning cases with regard to the `O_DIRECT` warnings on https://stackoverflow.com/a/46377629/2732969 ?

**Comment by bengland2** [comment]
@sitsofe  thanks for your suggestion, we are trying using RBD partitions instead of files to see if this is the case.  At least this removes XFS from the discussion.  We are also experimenting with removing logs or increasing time between samples in the logs.  We are also experimenting with running fio jobs on multiple hosts using ansible -f N instead of fio --client, since fio --client option isn't used by most people AFAICT.  Once we have a handle on what causes it we'll report back.

**Comment by sitsofe** [comment]
(Hmm XFS is usually well behaved so that makes it less likely you're in the "filesystem fell back to buffered I/O" scenario but your results will prove that one way or the other)

**Comment by bengland2** [comment]
so far, testing with RBD partitions instead of XFS files on RBD seems to provide more accurate results, we're going with that for now.   We'll come back to this behavior later on but for now we need to do our day jobs ;-)

**Comment by sitsofe** [comment]
@bengland2 Understandable - do you want to close this issue for the meantime?

**Comment by bengland2** [comment]
ok, closed for now.
