### ISSUE TITLE
Cannot run on unformatted drive on Windows

### ISSUE THREAD

**Issue by protik77** [axboe/fio#754]
Hi, I am trying fio-3.13 to do some benchmarking on a unformatted hard drive on Windows. I compiled `fio` using Cygwin. But the test is failing. 

```
> fio --version
fio-3.13
```

My sample job file,

```
[global]
buffered=0
rw=read
bs=4k
size=6m
thread=1

[file1]
iodepth=1
```

The error shown is below:

```
> fio no_partition_read.fio --directory \\.\F\:\
file1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=1
fio-3.13
Starting 1 thread
windowsaio: failed to open file "\\.\F:\/file1.0.0"
fio: failed opening blockdev \\.\F:\/file1.0.0 for size check



Run status group 0 (all jobs):
```

I have tried the `\\.\PhysicalDrive0` notation as well. I have also tried `\\?\Volume{1277e70d-79a7-11e1-9fed-f04da2ef6fc9}\` notation mentioned in the mailing list. So far, no luck. Any help regarding this is really appreciated.

**Comment by sitsofe** [comment]
@protik77 Your path looks strange:
1. Do you want to write into a filesystem? If so you will need to use a path like the example in the "Each colon and backslash" paragraph of the help over on https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename ?
2. Do you want directly write onto a raw partition? If so you will need use `filename` with the `PhysicalDrive` syntax described in the link above.

Note: trying to use `--directory` (documentation is on https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-directory ) with something that isn't a path to a mounted filesystem doesn't make sense - how do you create a new file on something that isn't a filesystem?

If this answers your question could you close this issue? Thanks!

**Comment by protik77** [comment]
I wanted to run benchmarking into a raw partition, Adding the following to the job file resolved the issue,

```
filename=\\.\PhysicalDrive1
```

Earlier I was using `directory` which was the cause of the problem.
