### ISSUE TITLE
error=Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by gzhx106** [axboe/fio#759]
This error occurred while using script testing
fio -filename=/dev/nvme2n1 -direct=1 -ioengine=libaio -continue_on_error=none -random_generator=tausworthe64 -rw=randrw -bs=3388K -numjobs=1 -iodepth=256 -runtime=20000 -loops=$tc_hour -time_based -name=ssd_rw -do_verify=1 -verify_dump=1 -verify=md5

error info:
(g=0): rw=randrw, bs=(R) 3388KiB-3388KiB, (W) 3388KiB-3388KiB, (T) 3388KiB-3388KiB, ioengine=libaio, iodepth=256
fio-3.12
Starting 1 process
fio: pid=8610, err=84/file:io_u.c:2074, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

(groupid=0, jobs=1): err=84 (file:io_u.c:2074, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=8610:

Do not know if there is a issue with FIO ?

**Comment by gzhx106** [comment]
This error occurs on the 3.12 version, while version 2.99 does not appear

**Comment by gzhx106** [comment]
verify: bad header rand_seed 16005983017258152080, wanted 1053428439018799125 at file /dev/nvme0n1p2 offset 13002027008, length 1773568 (requested block: of        fset=13002027008, length=1773568)
       hdr_fail data dumped as nvme0n1p2.13002027008.hdr_fail
fio: pid=30624, err=84/file:io_u.c:2074, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

**Comment by sitsofe** [comment]
@gzhx106:

`rw=randrw`

When you are using that mode AND doing verification are you sure about what to expect?

(Note this may be another case of #746 , #740 etc.)

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
