### ISSUE TITLE
file size limit?

### ISSUE THREAD

**Issue by mallilinux1978** [axboe/fio#766]
is there limit on file size in fio v3.13? though i've mentioned 200GB in job file but created just 11GB.

am i missing anything here?
here is job file.

[global]
time_based
ioengine=libaio
direct=1
group_reporting
overwrite=1
thread
size=200G
filename=/fio1/fiotest:/fio2/fiotest:/fio3/fiotest:/fio4/fiotest:/fio5/fiotest:/fio6/fiotest:/fio7/fiotest:/fio8/fiotest:/fio9/fiotest:/fio10/fiotest:/fio11/fiotest:/fio12/fiotest:/fio13/fiotest:/fio14/fiotest:/fio15/fiotest:/fio16/fiotest:/fio17/fiotest:/fio18/fiotest:/fio19/fiotest:/fio20/fiotest
readwrite=randwrite
ramp_time=10s
runtime=3600s
numjobs=1
[2ktest]
blocksize=2k
iodepth=128

# df -hP | grep fio
/dev/mapper/testvg_srdfa-fio1     256G   11G  233G   5% /fio1
/dev/mapper/testvg_srdfa-fio2     256G   11G  233G   5% /fio2
/dev/mapper/testvg_srdfa-fio3     256G   11G  233G   5% /fio3
/dev/mapper/testvg_srdfa-fio4     256G   11G  233G   5% /fio4
/dev/mapper/testvg_srdfa-fio5     256G   11G  233G   5% /fio5
/dev/mapper/testvg_srdfa-fio6     256G   11G  233G   5% /fio6
/dev/mapper/testvg_srdfa-fio7     256G   11G  233G   5% /fio7
/dev/mapper/testvg_srdfa-fio8     256G   11G  233G   5% /fio8
/dev/mapper/testvg_srdfa-fio9     256G   11G  233G   5% /fio9
/dev/mapper/testvg_srdfa-fio10    256G   11G  233G   5% /fio10
/dev/mapper/testvg_srdfa-fio11    256G   11G  233G   5% /fio11
/dev/mapper/testvg_srdfa-fio12    256G   11G  233G   5% /fio12
/dev/mapper/testvg_srdfa-fio13    256G   11G  233G   5% /fio13
/dev/mapper/testvg_srdfa-fio14    256G   11G  233G   5% /fio14
/dev/mapper/testvg_srdfa-fio15    256G   11G  233G   5% /fio15
/dev/mapper/testvg_srdfa-fio16    256G   11G  233G   5% /fio16
/dev/mapper/testvg_srdfa-fio17    256G   11G  233G   5% /fio17
/dev/mapper/testvg_srdfa-fio18    256G   11G  233G   5% /fio18
/dev/mapper/testvg_srdfa-fio19    256G   11G  233G   5% /fio19
/dev/mapper/testvg_srdfa-fio20    256G   11G  233G   5% /fio20

**Comment by axboe** [comment]
You asked for a total size of 200G, and you're using 20 files. That's about 10G per file.

**Comment by sitsofe** [comment]
@mallilinux1978 given @axboe's reply is this a down to a misunderstanding of how `size` with multiple files in `filename` (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename ) works? If so can you close this issue. Thanks!

**Comment by mallilinux1978** [comment]
its working as per document. but how can i create individual files with same size as size parameter instead of dividing size/no of files?

**Comment by sitsofe** [comment]
@mallilinux1978 This is a bit offtopic for an issue here (and future questions are better sent to the [mailing list](https://github.com/axboe/fio/blob/fio-3.13/README#L58 )) but did you see the link to [`filesize`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-filesize) help that was mentioned in  [`filename`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename) documentation?
