### ISSUE TITLE
blktrace replay slower than original

### ISSUE THREAD

**Issue by shimrot** [axboe/fio#772]
When I do a replay of operations produced from constant rate load, the replay rate of operations is slower than the original (~2%).
That is, when I blktrace fio writes with an op rate of 250 IOps for 1 minute, the replay only produces about 246 IOps. Adding a ramp time doesn't seem to effect the results.

For example, with blktrace running as follows (start after starting fio): 
```
> blktrace -d /dev/nvme0n1
```

In order to blktrace without capturing initial and ending reads, run fio before starting blktrace and end blktrace before fio finishes.  The FIO command (fio built from the current master, but attempts from an earlier 3.12 image give same results)
```
>  fio --direct=1 --filename="/dev/nvme0n1" --ioengine=libaio --norandommap=1 --random_generator=tausworthe64 --randrepeat=0 --runtime=3m --time_based=1 --name="Measure_RW_256KB_QD1" --bs=256KB1 --rate=64000KB --rw=randwrite
Measure_RW_256KB_QD1: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=1
fio-3.13-27-gef32d
Starting 1 process
Jobs: 1 (f=1), 0B/s-0B/s: [w(1)][100.0%][w=62.5MiB/s][w=250 IOPS][eta 00m:00s]
Measure_RW_256KB_QD1: (groupid=0, jobs=1): err= 0: pid=46369: Thu Apr 18 14:59:49 2019
  write: IOPS=250, BW=62.5MiB/s (65.5MB/s)(10.0GiB/180001msec)
    slat (usec): min=15, max=123, avg=32.14, stdev= 7.74
    clat (usec): min=344, max=1552, avg=515.60, stdev=97.70
     lat (usec): min=399, max=1593, avg=548.21, stdev=98.03
    clat percentiles (usec):
     |  1.00th=[  396],  5.00th=[  412], 10.00th=[  424], 20.00th=[  449],
     | 30.00th=[  453], 40.00th=[  461], 50.00th=[  478], 60.00th=[  506],
     | 70.00th=[  537], 80.00th=[  586], 90.00th=[  660], 95.00th=[  717],
     | 99.00th=[  832], 99.50th=[  873], 99.90th=[  971], 99.95th=[ 1037],
     | 99.99th=[ 1270]
   bw (  KiB/s): min=63488, max=64512, per=99.99%, avg=63996.44, stdev=350.88, samples=360
   iops        : min=  248, max=  252, avg=249.97, stdev= 1.38, samples=360
  lat (usec)   : 500=57.53%, 750=39.22%, 1000=3.19%
  lat (msec)   : 2=0.07%
  cpu          : usr=0.64%, sys=1.57%, ctx=90008, majf=0, minf=182
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,45001,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=62.5MiB/s (65.5MB/s), 62.5MiB/s-62.5MiB/s (65.5MB/s-65.5MB/s), io=10.0GiB (11.8GB), run=180001-180001msec

Disk stats (read/write):
  nvme0n1: ios=43/44973, merge=0/0, ticks=6/22073, in_queue=22056, util=12.26%
```

I'm using --rate option rather than rate_iops, but it doesn't really matter.  The resulting op rate of 250 IOps is expected.  
And, using blkparse to get a text output, and then analyzing the timestamps of 'queue' actions, the average period between queue entries is about 4000 us, as expected.

Building trace bin file:
```
> blkparse nvme0n1 -o /dev/null -d nvme0n1.blkparse.bin
```

Then replay with or without a ramp period, write rate is 246 IOps (~2% slow):
```
> fio  --direct=1 --filename="/dev/nvme0n1" --replay_redirect="/dev/nvme0n1" --ioengine=libaio --randrepeat=0 --name="Replay" --ramp_time=0s --read_iolog=nvme0n1.blkparse.bin Replay: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.13-27-gef32d
Starting 1 process
Jobs: 1 (f=1): [W(1)][100.0%][w=61.6MiB/s][w=246 IOPS][eta 00m:00s]
Replay: (groupid=0, jobs=1): err= 0: pid=46629: Thu Apr 18 15:05:52 2019
  write: IOPS=245, BW=61.5MiB/s (64.5MB/s)(3848MiB/62584msec)
    slat (nsec): min=16676, max=79311, avg=28768.10, stdev=6408.39
    clat (usec): min=383, max=1208, avg=488.22, stdev=76.46
     lat (usec): min=408, max=1233, avg=517.47, stdev=76.64
    clat percentiles (usec):
     |  1.00th=[  392],  5.00th=[  404], 10.00th=[  416], 20.00th=[  445],
     | 30.00th=[  457], 40.00th=[  461], 50.00th=[  465], 60.00th=[  469],
     | 70.00th=[  490], 80.00th=[  523], 90.00th=[  586], 95.00th=[  652],
     | 99.00th=[  783], 99.50th=[  824], 99.90th=[  889], 99.95th=[  963],
     | 99.99th=[ 1172]
   bw (  KiB/s): min=62464, max=63488, per=100.00%, avg=62951.42, stdev=127.69, samples=125
   iops        : min=  244, max=  248, avg=245.90, stdev= 0.50, samples=125
  lat (usec)   : 500=73.57%, 750=24.93%, 1000=1.46%
  lat (msec)   : 2=0.04%
  cpu          : usr=0.83%, sys=1.36%, ctx=30789, majf=0, minf=208
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,15390,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=61.5MiB/s (64.5MB/s), 61.5MiB/s-61.5MiB/s (64.5MB/s-64.5MB/s), io=3848MiB (4034MB), run=62584-62584msec

Disk stats (read/write):
  nvme0n1: ios=0/15341, merge=0/0, ticks=0/7078, in_queue=7070, util=11.32%
```

I tried debugging, but couldn't find something to account for extra delay.  The op rate is not very high.  And adding the io debug output and some extra output makes it harder to account for delays.  The key logic appears to be in iolog.c::iolog_delay, but I can't seem to fault the logic - looks good as far as I can tell.

Any ideas?
Thanks

**Comment by sitsofe** [comment]
@shimrot Hmm,

Why is the amount of issued I/O (see `issued rwts`) different between the two jobs? Could it be that some of your I/Os have been merged going through the block layer thus changing the workload?

**Comment by sitsofe** [comment]
Closing because we need more information from the reporter to take this further.

@shimrot - please re-open this issue if/when you're able to do more supply the requested information. Thank you!

**Comment by shimrot** [comment]
Sitsofe, 

I kind of gave up on this blktrace approach to the test.   I never did understand why the write operations were being split – though they do appear to be reconsolidated before being sent to the drive. 

For what it’s worth, as part of debug, I did make the following patch to blktrace.c, which seemed to fix timings, but I couldn’t get past the split writes (I rebased with current before making this patch – but didn’t try retesting).

Thanks much
Kris


diff --git a/blktrace.c b/blktrace.c
index 64a610a..b916e15 100644
--- a/blktrace.c
+++ b/blktrace.c
@@ -202,7 +202,7 @@
 		ipo->offset = ipo->offset / td->o.replay_scale;
 	ipo_bytes_align(td->o.replay_align, ipo);
 	ipo->len = bytes;
-	ipo->delay = ttime / 1000;
+	ipo->delay = (ttime + 500) / 1000;
 	if (rw)
 		ipo->ddir = DDIR_WRITE;
 	else
@@ -215,7 +215,7 @@
 	queue_io_piece(td, ipo);
 }
 
-static void handle_trace_notify(struct blk_io_trace *t)
+static bool handle_trace_notify(struct blk_io_trace *t)
 {
 	switch (t->action) {
 	case BLK_TN_PROCESS:
@@ -232,9 +232,10 @@
 		dprint(FD_BLKTRACE, "unknown trace act %x\n", t->action);
 		break;
 	}
+	return false;
 }
 
-static void handle_trace_discard(struct thread_data *td,
+static bool handle_trace_discard(struct thread_data *td,
 				 struct blk_io_trace *t,
 				 unsigned long long ttime,
 				 unsigned long *ios, unsigned int *bs)
@@ -243,7 +244,7 @@
 	int fileno;
 
 	if (td->o.replay_skip & (1u << DDIR_TRIM))
-		return;
+		return false;
 
 	ipo = calloc(1, sizeof(*ipo));
 	init_ipo(ipo);
@@ -262,7 +263,7 @@
 		ipo->offset = ipo->offset / td->o.replay_scale;
 	ipo_bytes_align(td->o.replay_align, ipo);
 	ipo->len = t->bytes;
-	ipo->delay = ttime / 1000;
+	ipo->delay = (ttime + 500) / 1000;
 	ipo->ddir = DDIR_TRIM;
 	ipo->fileno = fileno;
 
@@ -270,6 +271,7 @@
 							ipo->offset, ipo->len,
 							ipo->delay);
 	queue_io_piece(td, ipo);
+	return true;
 }
 
 static void dump_trace(struct blk_io_trace *t)
@@ -277,7 +279,7 @@
 	log_err("blktrace: ignoring zero byte trace: action=%x\n", t->action);
 }
 
-static void handle_trace_fs(struct thread_data *td, struct blk_io_trace *t,
+static bool handle_trace_fs(struct thread_data *td, struct blk_io_trace *t,
 			    unsigned long long ttime, unsigned long *ios,
 			    unsigned int *bs)
 {
@@ -290,16 +292,16 @@
 
 	if (rw) {
 		if (td->o.replay_skip & (1u << DDIR_WRITE))
-			return;
+			return false;
 	} else {
 		if (td->o.replay_skip & (1u << DDIR_READ))
-			return;
+			return false;
 	}
 
 	if (!t->bytes) {
 		if (!fio_did_warn(FIO_WARN_BTRACE_ZERO))
 			dump_trace(t);
-		return;
+		return false;
 	}
 
 	if (t->bytes > bs[rw])
@@ -308,28 +310,30 @@
 	ios[rw]++;
 	td->o.size += t->bytes;
 	store_ipo(td, t->sector, t->bytes, rw, ttime, fileno);
+	return true;
 }
 
-static void handle_trace_flush(struct thread_data *td, struct blk_io_trace *t,
+static bool handle_trace_flush(struct thread_data *td, struct blk_io_trace *t,
 			       unsigned long long ttime, unsigned long *ios)
 {
 	struct io_piece *ipo;
 	int fileno;
 
 	if (td->o.replay_skip & (1u << DDIR_SYNC))
-		return;
+		return false;
 
 	ipo = calloc(1, sizeof(*ipo));
 	init_ipo(ipo);
 	fileno = trace_add_file(td, t->device);
 
-	ipo->delay = ttime / 1000;
+	ipo->delay = (ttime + 500) / 1000;
 	ipo->ddir = DDIR_SYNC;
 	ipo->fileno = fileno;
 
 	ios[DDIR_SYNC]++;
 	dprint(FD_BLKTRACE, "store flush delay=%lu\n", ipo->delay);
 	queue_io_piece(td, ipo);
+	return true;
 }
 
 /*
@@ -340,6 +344,7 @@
 			 unsigned long *ios, unsigned int *bs)
 {
 	static unsigned long long last_ttime;
+	unsigned long long queued_time = t->time;
 	unsigned long long delay = 0;
 
 	if ((t->action & 0xffff) != __BLK_TA_QUEUE)
@@ -349,28 +354,35 @@
 		if (!last_ttime || td->o.no_stall)
 			delay = 0;
 		else if (td->o.replay_time_scale == 100)
-			delay = t->time - last_ttime;
+			delay = queued_time - last_ttime;
 		else {
-			double tmp = t->time - last_ttime;
+			double tmp = queued_time - last_ttime;
 			double scale;
 
 			scale = (double) 100.0 / (double) td->o.replay_time_scale;
 			tmp *= scale;
 			delay = tmp;
 		}
-		last_ttime = t->time;
 	}
 
 	t_bytes_align(&td->o, t);
 
-	if (t->action & BLK_TC_ACT(BLK_TC_NOTIFY))
+	if (t->action & BLK_TC_ACT(BLK_TC_NOTIFY)) {
 		handle_trace_notify(t);
-	else if (t->action & BLK_TC_ACT(BLK_TC_DISCARD))
-		handle_trace_discard(td, t, delay, ios, bs);
-	else if (t->action & BLK_TC_ACT(BLK_TC_FLUSH))
-		handle_trace_flush(td, t, delay, ios);
-	else
-		handle_trace_fs(td, t, delay, ios, bs);
+	}
+	else if (t->action & BLK_TC_ACT(BLK_TC_DISCARD)) {
+		if (handle_trace_discard(td, t, delay, ios, bs))
+			last_ttime = t->time;
+	}
+	else if (t->action & BLK_TC_ACT(BLK_TC_FLUSH)) {
+		if (handle_trace_flush(td, t, delay, ios))
+			last_ttime = t->time;
+	}
+	else {
+		if (handle_trace_fs(td, t, delay, ios, bs))
+			last_ttime = t->time;
+	}
+
 }
 
 static void byteswap_trace(struct blk_io_trace *t)

Kris Davis
