### ISSUE TITLE
Last IOPS exceeds total Size specified

### ISSUE THREAD

**Issue by manukathir** [axboe/fio#773]
I'm trying to sequentially write from offset 0 to size 9120bytes with blocksize=4k. Looking at the debug io log, FIO is actually writing from 0 to ‭12288‬, since its align each write with 4k.

Is there a way in FIO to write 9120bytes of data with bs=4k ?

 fio --direct=1 --readwrite=write --offset=0 --size=9120 --filename=/dev/nvme0n1 --buffer_pattern=0xAABBCCDD --name=Testing_last_io --debug=io
fio: set debug option io
Testing_last_io: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.13
Starting 1 process
io       20414 drop page cache /dev/nvme0n1
io       20414 fill: io_u 0xb7f500: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 prep: io_u 0xb7f500: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 queue: io_u 0xb7f500: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 complete: io_u 0xb7f500: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 fill: io_u 0xb7f500: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 prep: io_u 0xb7f500: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 queue: io_u 0xb7f500: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 complete: io_u 0xb7f500: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 fill: io_u 0xb7f500: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 prep: io_u 0xb7f500: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 queue: io_u 0xb7f500: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       20414 complete: io_u 0xb7f500: **off=0x2000,len=0x1000**,ddir=1,file=/dev/nvme0n1
io       20414 close ioengine psync
io       20414 free ioengine psync

**Comment by sitsofe** [comment]
@manukathir Did you see `blocksize_unaligned` in the fio manual https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-blocksize-unaligned ?

If this answers your question could you close this issue? Thanks!

**Comment by manukathir** [comment]
@sitsofe blocksize_unaligned did not work for direct I/O or buffered I/O
```
Direct I/O
# fio --direct=1 --readwrite=write --offset=0 --size=9120 --filename=/dev/nvme0n1 --buffer_pattern=0xAABBCCDD --name=Testing_last_io --debug=io --blocksize_unaligned=1
fio: set debug option io
fio: bs_unaligned may not work with raw io
Testing_last_io: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.13
Starting 1 process
io       9742  drop page cache /dev/nvme0n1
io       9742  fill: io_u 0xaf45c0: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  prep: io_u 0xaf45c0: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  queue: io_u 0xaf45c0: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  complete: io_u 0xaf45c0: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  fill: io_u 0xaf45c0: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  prep: io_u 0xaf45c0: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  queue: io_u 0xaf45c0: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  complete: io_u 0xaf45c0: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  fill: io_u 0xaf45c0: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  prep: io_u 0xaf45c0: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  queue: io_u 0xaf45c0: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9742  complete: io_u 0xaf45c0: **off=0x2000,len=0x1000**,ddir=1,file=/dev/nvme0n1
io       9742  close ioengine psync
io       9742  free ioengine psync

```
```

Buffered I/O
# fio --direct=0 --readwrite=write --offset=0 --size=9120 --filename=/dev/nvme0n1 --buffer_pattern=0xAABBCCDD --name=Testing_last_io --debug=io --blocksize_unaligned=1 --buffered=1
fio: set debug option io
Testing_last_io: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.13
Starting 1 process
io       9988  drop page cache /dev/nvme0n1
io       9988  fill: io_u 0x175d640: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  prep: io_u 0x175d640: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  queue: io_u 0x175d640: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  complete: io_u 0x175d640: off=0x0,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  fill: io_u 0x175d640: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  prep: io_u 0x175d640: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  queue: io_u 0x175d640: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  complete: io_u 0x175d640: off=0x1000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  fill: io_u 0x175d640: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  prep: io_u 0x175d640: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  queue: io_u 0x175d640: off=0x2000,len=0x1000,ddir=1,file=/dev/nvme0n1
io       9988  complete: io_u 0x175d640: **off=0x2000,len=0x1000**,ddir=1,file=/dev/nvme0n1
io       9988  close ioengine psync
io       9988  free ioengine psync

```

**Comment by sitsofe** [comment]
@manukathir Apologies I didn't read your original command line closely enough. In short when you use direct I/O on Linux there are various constraints you have to fulfill and one of them is that you MUST align your I/O. From http://man7.org/linux/man-pages/man2/open.2.html#NOTES :

> The O_DIRECT flag may impose alignment restrictions on the length and
>       address of user-space buffers and the file offset of I/Os.

So to come back to your original question:

> Is there a way in FIO to write 9120bytes of data with bs=4k ?

On Linux, yes you can do unaligned I/O if you are not doing direct I/O (see the above option). If you are doing direct I/O the answer is no (and this constraints comes from the kernel) if the I/O is really going direct and bypassing caches.
