### ISSUE TITLE
Random Reads on ZBDs ignore conventional zones

### ISSUE THREAD

**Issue by trinof** [axboe/fio#774]
zbd_find_zone() currently ignores conventional zones because BLK_ZONE_COND_NOT_WP condition zones are initialized to have their write pointer set to their start LBA. This leads to a somewhat unexpected situation where a randread workload on a drive with only empty write pointer restricted zones will return immediately with no I/O performed. Similarly, any randrw workload that happens to start with a read will do the same thing. Unless there's some reason to set conventional zone write pointers to their start LBAs, it seems like it'd be easiest to set them to full so that zbd_find_zone() would not skip them.

**Comment by sitsofe** [comment]
Mentioning @damien-lemoal /@dmitry-fomichev for comment...

**Comment by damien-lemoal** [comment]
Indeed, this sounds like a reasonable fix. Do you have a patch or would you like me to send one ?

**Comment by trinof** [comment]
Here's a patch with the update that makes sense to me. This seemed the simplest way to fix the problem.
[zbd_random_reads.txt](https://github.com/axboe/fio/files/3103938/zbd_random_reads.txt)

**Comment by damien-lemoal** [comment]
Your patch looks OK to me. Have tested also with write workloads with -verify enabled ? And also have you run the t/zbd/test-zbd-support script ?

**Comment by trinof** [comment]
I did some brief testing with verify write workloads and everything seemed in order. Running t/zbd/test-zbd-support passes all 46 tests.

**Comment by damien-lemoal** [comment]
OK. Please send a proper patch or pull request ! I can also send a patch on your behalf too if you cannot do so yourself.

**Comment by trinof** [comment]
This is the first patch I've sent, so I tried to mimic what I've seen on the FIO mailing list before. Let me know if there's anything missing or wrong and thanks for your input.
