### ISSUE TITLE
Is it possible to use Linux `readahead` syscall to increase IO depth?

### ISSUE THREAD

**Issue by JimChengLin** [axboe/fio#780]
Under the current implementation of `psync` engine, `iodepth` parameter is actually useless. No matter what you set, the real IO Queue depth only depends on `numjobs`. If there are 48 threads(processes), the max IO Queue depth can only be 48.

However, we can definitely improve it by using `readahead` Linux syscall. `readahead` enables a thread submit more than one request to kernel just like what `libaio` does. 

From my own experiences, `readahead` is quite promising. What do you think? I would like to make a try if no one is doing similar stuff.

**Comment by axboe** [comment]
That's the nature of a sync engine, the IO system call doesn't return until the IO is actually complete. Hence more jobs are needed to perform IO.

The readahead system call can be useful in certain situations. But as it's not necessarily async, it's not particularly useful for most situations. Additionally, you still need to do the actual read, hence you're now doing two system calls per IO.

If the objective is actual performance, I'd recommend looking into io_uring instead. It provides buffered aio natively, instead of having to work around it with manual readahead.

**Comment by sitsofe** [comment]
@JimChengLin In fact the fio manual/help does warn you about iodepth and sync engines:

> Note that increasing iodepth beyond 1 will not affect synchronous ioengines

(from https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-iodepth ).

Wrt to a new `readahead` call - @axboe if someone were to provide a patch to add it (not me!) would we likely consider it? I think there would be tricky design decisions (but the implementor would have to solve those).

**Comment by axboe** [comment]
The readahead system call isn't new, we've had that for many years. I'm not against adding any feature per se, but I have a hard time seeing how readahead would be used. You would need future knowledge of what IO offsets fio would generate, or hold off on issuing until you have X pending, then issue readahead for them, then do the actual IO. Or something like that. You would at least need a few parameters to control the heuristics of it. Even if you did that, you're still burdened by the fact that you don't know if the calls will block. Hence the io queue on fio's side needs to be drained before doing any readahead calls, as not to get any false long latencies.

I just don't see a way to do this cleanly, without resorting to separate threads. And at that point you may as well just use more jobs. I have a hard time imagining anyone wanting to do it on the app side now that we have io_uring. It's a far better solution than readahead kludges that need offload anyway.

**Comment by sitsofe** [comment]
Based on the above, we can close this feature request for now (but if someone submits an intelligent patch that avoid the pitfalls mentioned above we can always review it).
