### ISSUE TITLE
Unable to append output to a file

### ISSUE THREAD

**Issue by ponasromas** [axboe/fio#783]
Hello,

I have .sh file with content:

```
#!/bin/bash

echo 'FIO random reads:' >> tst.log
./fio reads.ini --output-format=json >> tst.log
echo 'Done' >> tst.log
```

Results are:

> FIO random reads:
> Done

And a error in console:

> ./test.sh: line 4:  2335 Killed                  ./fio reads.ini --output-format=json >> tst.log

When running manually from console:

./fio reads.ini --output-format=json >> tst.log

Results are correctly saved in json format without any single error.

**Comment by ponasromas** [comment]
Found reason:

> debian kernel: Out of memory: Kill process 2352 (fio) score 274 or sacrifice child

The question now is:

Why manually executed program able to finish without producing "Out of memory" error.

**Comment by sitsofe** [comment]
@ponasromas We would really need to know what version of fio, how much memory you have on your machine and what the contents of `reads.ini` is (and any extra command line parameters) to even be able to make a start...

**Comment by ponasromas** [comment]
I have VPS with 256 MB RAM. read.ini:

```
[global]
randrepeat=1
ioengine=libaio
bs=4k
ba=4k
size=1G
direct=1
gtod_reduce=1
norandommap
iodepth=64
numjobs=1

[randomreads]
startdelay=0
filename=st-io-test
readwrite=randread
```
Command line option:

./fio reads.ini --output-format=json >> tst.log

In bash script it's the same.

**Comment by sitsofe** [comment]
@ponasromas Which version of fio? Can you include the full output of the OOM? If you now use the bash script does it go on to OOM? What's your current working directory? What's the current output reported by `free`?

**Comment by ponasromas** [comment]
FIO 3.14. 

Simple fix on my case:

```
#!/bin/bash
echo 'FIO random reads:' >> tst.log
./fio reads.ini --output-format=json >> tst.log &
wait
echo 'Done' >> tst.log
```
Yep, dropping fio to background resolves OOM error. Interesting, that running fio WITHOUT '--output-format=json' option:

```
#!/bin/bash
echo 'FIO random reads:' >> tst.log
./fio reads.ini >> tst.log
echo 'Done' >> tst.log
```
 I don't need to drop it to the background, it works fine.

OOM log: https://pastebin.com/7FWfBKfv

You may close this report as it is resolved(?).

**Comment by sitsofe** [comment]
@ponasromas Hmm... In all honesty your machine has very little memory and between those php processes and fio there's just very little of it left. If I had to guess I'd say that storing all the extra stats in JSON format just caused fio to allocate a bit more memory. As to your other workaround, I'm not sure why putting fio in the background would make less memory be taken up but if it works for you then ¯\\_(ツ)_/¯... 

PS: Do you know about [`--output`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-output) ?
