### ISSUE TITLE
Failed to create dir  on windows

### ISSUE THREAD

**Issue by YongxueHong** [axboe/fio#784]
Hi, 
Failed to create a directory when using fio-3.13 on windows.
e.g:

> C:\Windows\System32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
> "C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
> fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=4
> ...
> fio-3.13
> Starting 4 threads
> 
> 
> Run status group 0 (all jobs):
> fio: failed to create dir (C:\): 13

It is ok for fio-2.2.10.
The format of option "filename" is changed ?

**Comment by sitsofe** [comment]
@YongxueHong Well I can't say anything about fio 2.2.10 working because it's so ancient but wrt to fio 3.13 - have you read the documentation on `filename` (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename )? If you haven't read it yet could you do so and let us know if anything it mentions helps?

**Comment by YongxueHong** [comment]
@sitsofe Yeah, I have read the documents about the options "filename" then try it by any way which I could think, but still failed to work.

**Comment by sitsofe** [comment]
@YongxueHong,

```
--filename=C:\fio_system_disk_test
            ^^
```

From https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename :
>**Each colon and backslash** in the wanted path must be escaped with a \ character.

But on top of that I can't tell what your shell is so you might have to put that in quotes too.

(Additionally while you're trying to solve this particular issue I recommend removing as many of the other options as possible to make it easier to narrow down the cause of the problem)

**Comment by YongxueHong** [comment]
So sorry, My mistake.  
For the comment:

> Hi,
> Failed to create a directory when using fio-3.13 on windows.
> e.g:
> 
>     C:\Windows\System32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C:\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
>     "C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C:\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
>     fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=4
>     ...
>     fio-3.13
>     Starting 4 threads
> 
>     Run status group 0 (all jobs):
>     fio: failed to create dir (C:): 13
> 
> It is ok for fio-2.2.10.
> The format of option "filename" is changed ?

The command is "C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300.

**Comment by YongxueHong** [comment]
Actually, there is a \ character before ":" and "\", but after inserting a quote, it's disappeared.
sorry, my fault.

**Comment by sitsofe** [comment]
@YongxueHong Ah I think you've done what what I was about to say:

> @YongxueHong Ah - that's better, I see what you were saying now!
>
> OK - what happens when you put double quotes around `C\:\\fio_system_disk_test` ? Also just to > check - your "user" has permission to create files in "C:\"?

But are you saying it's all working now?

**Comment by YongxueHong** [comment]
@sitsofe, yes, my "user" has permission to create files in "C:".  it 's working with the following cmd:
```
C:\Windows\System32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=4
...
fio-3.13
Starting 4 threads


Run status group 0 (all jobs):
fio: failed to create dir (C:\): 13
```

**Comment by sitsofe** [comment]
Hmm... Can you see if this happens in fio 3.1 and fio 3.2 (https://bluestop.org/files/fio/releases/ )?

**Comment by YongxueHong** [comment]
@sitsofe  all right

**Comment by YongxueHong** [comment]
@sitsofe  I tried it with 3.1, it works.
```
C:\Windows\system32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300
fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=4
...
fio-3.1
Starting 4 threads
fiotest: Laying out IO file (1 file / 1024MiB)

fiotest: (groupid=0, jobs=4): err= 0: pid=1640: Fri May 31 15:23:57 2019
   read: IOPS=94, BW=378KiB/s (387kB/s)(111MiB/300136msec)
    slat (usec): min=19, max=89634, avg=84.87, stdev=531.71
    clat (usec): min=457, max=1940.2k, avg=139227.01, stdev=181766.53
     lat (usec): min=565, max=1940.2k, avg=139311.89, stdev=181771.49
    clat percentiles (msec):
     |  1.00th=[    7],  5.00th=[   15], 10.00th=[   26], 20.00th=[   42],
     | 30.00th=[   56], 40.00th=[   71], 50.00th=[   88], 60.00th=[  109],
     | 70.00th=[  138], 80.00th=[  184], 90.00th=[  284], 95.00th=[  435],
     | 99.00th=[ 1083], 99.50th=[ 1502], 99.90th=[ 1519], 99.95th=[ 1536],
     | 99.99th=[ 1754]
   bw (  KiB/s): min=    7, max=  248, per=24.26%, avg=91.71, stdev=32.88, samples=2394
   iops        : min=    1, max=   62, avg=22.67, stdev= 8.30, samples=2394
  write: IOPS=95, BW=383KiB/s (392kB/s)(112MiB/300136msec)
    slat (usec): min=18, max=1499, avg=86.91, stdev=19.74
    clat (usec): min=337, max=629645, avg=29273.59, stdev=54207.01
     lat (usec): min=426, max=629717, avg=29360.50, stdev=54205.96
    clat percentiles (usec):
     |  1.00th=[   457],  5.00th=[  1237], 10.00th=[  2057], 20.00th=[  4686],
     | 30.00th=[  7898], 40.00th=[ 11600], 50.00th=[ 17695], 60.00th=[ 28967],
     | 70.00th=[ 34866], 80.00th=[ 40633], 90.00th=[ 51119], 95.00th=[ 65274],
     | 99.00th=[417334], 99.50th=[476054], 99.90th=[557843], 99.95th=[583009],
     | 99.99th=[624952]
   bw (  KiB/s): min=    7, max=  287, per=24.48%, avg=93.52, stdev=40.50, samples=2376
   iops        : min=    1, max=   71, avg=23.07, stdev=10.18, samples=2376
  lat (usec)   : 500=0.87%, 750=0.43%, 1000=0.43%
  lat (msec)   : 2=3.15%, 4=4.14%, 10=10.47%, 20=10.55%, 50=28.05%
  lat (msec)   : 100=19.22%, 250=16.01%, 500=4.70%, 750=1.15%, 1000=0.26%
  lat (msec)   : 2000=0.56%
  cpu          : usr=0.00%, sys=0.33%, ctx=0, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.4%, 4=99.6%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=28391,28716,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
   READ: bw=378KiB/s (387kB/s), 378KiB/s-378KiB/s (387kB/s-387kB/s), io=111MiB (116MB), run=300136-300136msec
  WRITE: bw=383KiB/s (392kB/s), 383KiB/s-383KiB/s (392kB/s-392kB/s), io=112MiB (118MB), run=300136-300136msec

C:\Windows\system32>

```

**Comment by YongxueHong** [comment]
```C:\Windows\system32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --iodepth=4 --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --ioengine=windowsaio --thread --group_reporting --numjobs=4 --size=1G --runtime=300fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=4...fio-3.1Starting 4 threadsfiotest: Laying out IO file (1 file / 1024MiB)fiotest: (groupid=0, jobs=4): err= 0: pid=1640: Fri May 31 15:23:57 2019   read: IOPS=94, BW=378KiB/s (387kB/s)(111MiB/300136msec)    slat (usec): min=19, max=89634, avg=84.87, stdev=531.71    clat (usec): min=457, max=1940.2k, avg=139227.01, stdev=181766.53     lat (usec): min=565, max=1940.2k, avg=139311.89, stdev=181771.49    clat percentiles (msec):     |  1.00th=[    7],  5.00th=[   15], 10.00th=[   26], 20.00th=[   42],     | 30.00th=[   56], 40.00th=[   71], 50.00th=[   88], 60.00th=[  109],     | 70.00th=[  138], 80.00th=[  184], 90.00th=[  284], 95.00th=[  435],     | 99.00th=[ 1083], 99.50th=[ 1502], 99.90th=[ 1519], 99.95th=[ 1536],     | 99.99th=[ 1754]   bw (  KiB/s): min=    7, max=  248, per=24.26%, avg=91.71, stdev=32.88, samples=2394   iops        : min=    1, max=   62, avg=22.67, stdev= 8.30, samples=2394  write: IOPS=95, BW=383KiB/s (392kB/s)(112MiB/300136msec)    slat (usec): min=18, max=1499, avg=86.91, stdev=19.74    clat (usec): min=337, max=629645, avg=29273.59, stdev=54207.01     lat (usec): min=426, max=629717, avg=29360.50, stdev=54205.96    clat percentiles (usec):     |  1.00th=[   457],  5.00th=[  1237], 10.00th=[  2057], 20.00th=[  4686],     | 30.00th=[  7898], 40.00th=[ 11600], 50.00th=[ 17695], 60.00th=[ 28967],     | 70.00th=[ 34866], 80.00th=[ 40633], 90.00th=[ 51119], 95.00th=[ 65274],     | 99.00th=[417334], 99.50th=[476054], 99.90th=[557843], 99.95th=[583009],     | 99.99th=[624952]   bw (  KiB/s): min=    7, max=  287, per=24.48%, avg=93.52, stdev=40.50, samples=2376   iops        : min=    1, max=   71, avg=23.07, stdev=10.18, samples=2376  lat (usec)   : 500=0.87%, 750=0.43%, 1000=0.43%  lat (msec)   : 2=3.15%, 4=4.14%, 10=10.47%, 20=10.55%, 50=28.05%  lat (msec)   : 100=19.22%, 250=16.01%, 500=4.70%, 750=1.15%, 1000=0.26%  lat (msec)   : 2000=0.56%  cpu          : usr=0.00%, sys=0.33%, ctx=0, majf=0, minf=0  IO depths    : 1=0.1%, 2=0.4%, 4=99.6%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%     issued rwt: total=28391,28716,0, short=0,0,0, dropped=0,0,0     latency   : target=0, window=0, percentile=100.00%, depth=4Run status group 0 (all jobs):   READ: bw=378KiB/s (387kB/s), 378KiB/s-378KiB/s (387kB/s-387kB/s), io=111MiB (116MB), run=300136-300136msec  WRITE: bw=383KiB/s (392kB/s), 383KiB/s-383KiB/s (392kB/s-392kB/s), io=112MiB (118MB), run=300136-300136msecC:\Windows\system32>```

**Comment by sitsofe** [comment]
@YongxueHong: OK next up 3.2?

**Comment by YongxueHong** [comment]
@sitsofe  sorry, I didn't find the 3.2.

**Comment by sitsofe** [comment]
Ah true - how about 3.5?

**Comment by YongxueHong** [comment]
@sitsofe  it doesn't work with 3.5:
```
C:\Windows\system32>"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --size=1G --runtime=300
"C:\Program Files (x86)\fio\fio\fio.exe" --rw=randrw --bs=4k --direct=1 --filename=C\:\\fio_system_disk_test --name=fiotest --size=1G --runtime=300
fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=1
fio-3.5
Starting 1 thread


Run status group 0 (all jobs):
fio: failed to create dir (C:\): 13
fiotest: No I/O performed by windowsaio, perhaps try --debug=io option for details?

C:\Windows\system32>
```

**Comment by Gt3pccb** [comment]
the interesting thing is that 3.13 works and 3.16 fails in the same directory and Everyone has full access
fio-3.16
Starting 1 thread
fio: failed to create dir (c:): 22
it would be nice to know

**Comment by sitsofe** [comment]
@Gt3pccb OK that's odd. Can you test 3.14 and 3.15 too?

**Comment by Gt3pccb** [comment]
I only see 3.13 and 3.16 if you give me the the versions I can test

**Comment by sitsofe** [comment]
@Gt3pccb if you're quick:
- 3.14 - https://ci.appveyor.com/project/axboe/fio/builds/24739339/job/05hbubj00p7aa687/artifacts
- 3.15 - https://ci.appveyor.com/project/axboe/fio/builds/25941683/job/4gf8c7jstuy6ikr4/artifacts

**Comment by Gt3pccb** [comment]
@Sitsofe Sorry for the late response.
3.14, 3.15, 3.16 have the same issue
PS C:\> fio  --thread  --direct=1 --ioengine=windowsaio  --directory=v\:\ --filesize=2500GB --rw=write --iodepth=128 --bs=1MB --nrfiles=1 --name=XR2-4-Node --numjobs=12 --verify_async=40 --verify_dump=1 --scramble_buffers=1
XR2-4-Node: (g=0): rw=write, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=windowsaio, iodepth=128
...
fio-3.14
Starting 12 threads
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22
fio: failed to create dir (v:): 22

**Comment by sitsofe** [comment]
@Gt3pccb Thanks. So we know the issue was introduced between 3.13 and 3.14. I might put up some intermediary builds to narrow things further if I find time...

**Comment by sitsofe** [comment]
Hmm, could you try https://ci.appveyor.com/project/axboe/fio/builds/23973395/job/6m4dnuero7qqlc5h and report back?

**Comment by Gt3pccb** [comment]
No luck…

**Comment by Gt3pccb** [comment]
1 up vote for this.

**Comment by sitsofe** [comment]
So the short answer to this is: don't double the backslashes - only escape `:` with a backslash! i.e. `C:\Windows\Temp\fio.tmp` becomes `C\:\Windows\Temp\fio.tmp`. I'll keep looking as time permits.
