### ISSUE TITLE
Pinning fio to a cpu core

### ISSUE THREAD

**Issue by Anjali05** [axboe/fio#788]
I am using cpu_allowed flag to pin the fio process to a particular core but it does not seem to work. Will using taskset instead work the same way?

**Comment by sitsofe** [comment]
@Anjali05 Probably. However I'd say your question gives rise to the following set of questions:
- Which version of fio, which OS, what command line are you using?
- How do you know fio isn't being pinned to the core you're interested in?
- If you know the above, could you use the same technique to check if taskset worked?

**Comment by Anjali05** [comment]
I need to run fio in docker as well as my host. 
**My host info:**
Ubuntu 18.04
4.15.0-47-generic kernel
fio-3.1 is installed

On host, fio does not seem to work with cpu_allowed so I am using taskset.

**On docker:**
same kernel as my host 
fio-3.1 installed

There are two ways I can pin the fio process running inside the container:
1) By pinning the _docker run_ command to the core so that any process that runs inside it gets pinned to the same core. In this case, when I use --cpuset-cpus to pin docker, I get "clock setaffinity failed: Invalid argument" errro while running fio.
2) I can pin just the fio command using cpu_allowed flag but its not working. I have not still tried taskset with fio inside docker.

I would prefer pinning the docker container itself by using the --cpuset-cpus but I am not able to rectify the error. 

Any help would be appreciated. Thanks.

**Comment by axboe** [comment]
The cpus_allowed should work fine for native OS's, I'm not aware of any alternative way of needing to do that for docker, nor should there need to be.

Please read REPORTING-BUGS:

http://git.kernel.dk/cgit/fio/tree/REPORTING-BUGS

on how to write a proper bug report. Saying "it's not working" is not super helpful, as it's not clear how you are determining why it's not working, and what "it" even is.

**Comment by sitsofe** [comment]
@Anjali05 So I've just tried the following on docker running on an Ubuntu 18.04 host:

```
$ docker run -it ubuntu:18.04 /bin/bash
$ apt update
[...]
$ apt install fio
[...]
$ fio --eta=never --ioengine null --size=1T --time_based=1 --runtime=30s --name=go & sleep 3; for pid in $(pgrep fio); do taskset --all-tasks -cp ${pid}; done; pkill -9 fio; wait
[1] 1769
go: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.1
Starting 1 process
pid 1769's current affinity list: 0-39
pid 1811's current affinity list: 0-39
pid 1812's current affinity list: 0-39
[1]+  Killed                  fio --eta=never --ioengine null --size=1T --time_based=1 --runtime=30s --name=go
fio --cpus_allowed=0-19 --eta=never --ioengine null --size=1T --time_based=1 --runtime=30s --name=go & sleep 3; for pid in $(pgrep fio); do taskset --all-tasks -cp ${pid}; done; pkill -9 fio; wait
[1] 1817
go: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.1
Starting 1 process
pid 1817's current affinity list: 0-39
pid 1859's current affinity list: 0-39
pid 1860's current affinity list: 0-19
[1]+  Killed                  fio --cpus_allowed=0-19 --eta=never --ioengine null --size=1T --time_based=1 --runtime=30s --name=go
```

So in the above we clearly see the allowed CPUs parameter taking effect (in the second run the fio process actually doing the I/O set its affinity to CPUs 0 through to 19). If you can follow up on @axboe's request we might be able to explain the discrepancy.

**Comment by sitsofe** [comment]
@Anjali05 Please could you follow up the request for additional information (mentioned in https://github.com/axboe/fio/issues/788#issuecomment-501620904 ) or otherwise let us know if your issue is resolved? Thanks!

**Comment by Anjali05** [comment]
@sitsofe The issue has been resolved. Thanks!
