### ISSUE TITLE
Differences with dd, proper ioengine/baseline for native vs nfs comparisson

### ISSUE THREAD

**Issue by hanoii** [axboe/fio#789]
After trying several tools I landed here and so far I am liking it a lot. 

I am trying to benchmark NFS mounts IO performance between NFS mounts on linux on different virtualization platforms (Docker/VirtualBox/Vmware Fusion) vs Native OSX. I am looking to use the most real-world situation but it's hard for me (being a bit new to this) to choose/settle on some settings

Af first I started with `dd` (`dd if=/dev/zero of=testlocal.dat bs=8k count=125k`) and it  provided a good overall measure but wanted to take it a bit further and use fio. 

This is my current setting:
```
[global]
bs=8K
numjobs=1
time_based=1
runtime=30
size=1G
;direct=1
;ioengine=libaio

[test-write]
rw=write
```

direct and ioengine are commented as I wanted to see the defaults and tried different things with command line arguments.

On a docker mount nfs I am getting similar results with `fio` and  `dd`, on ox native, however, quite different. If I leave the default psync and direct, I get super fast writes, 2x that of the native with `dd`. If I set it to direct=1  then it drops to less than half than `dd`. So now I am confused what can I use to compare native vs nfs.

Any heper/suggestions are more than welcome

**Comment by sitsofe** [comment]
@hanoii 

This is really a general filesystem benchmarking question and is probably better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails). I'll briefly say that kernel caching is likely the reason for the huge discrepancy but if you want a more thorough explanation I can go into details by email on the list...

**Comment by sitsofe** [comment]
@hanoii just to check - are you planning on taking this one to the mailing list?

**Comment by hanoii** [comment]
@sitsofe appreciate the follow up. I subscribed and still planning to.. this was a bit of a side benchmarking project which I now puase it slightly (some preliminary conclusions already ruled what I was trying to benchmark out) but I want to understand more of the tool and I can use this to reliable benchmark this so yes, hopefully I can follow up better on this next week.

**Comment by sitsofe** [comment]
@hanoii OK, I'll close this issue for now...
