### ISSUE TITLE
In verify mode, if some blocks fail to fill header or pattern, will they be verified ? 

### ISSUE THREAD

**Issue by wedy542700927** [axboe/fio#791]
Hi, may I ask a question ?
When I used fio with verify flag, i found that some blocks failed to fill header or pattern but still be verified. 
So in verify mode, if some blocks fail to fill header or pattern, will they be verified ? 
Thank you.
```
-------------------------------------------------------------------------------
"verify   36299 get_verify: bad magic header 0, wanted acca at file /mnt/fs_nfsv4/fio-werk/1t_4k_rand_write_sha512.0.0 offset 218603520, length 4096"
-------------------------------------------------------------------------------
```

**Comment by sitsofe** [comment]
@wedy542700927 To diagnose an issue like this we need at least the information asked for in https://github.com/axboe/fio/blob/master/REPORTING-BUGS . Could you add that information in a follow up comment please/

**Comment by sitsofe** [comment]
@wedy542700927 Hi! What did the issue turn out to be in the end?
