### ISSUE TITLE
filename argument seems limited to ~4k characters

### ISSUE THREAD

**Issue by powernap** [axboe/fio#794]
In trying to work around issue #631 I discovered what seems like a ~4k character limit on the filename argument. I see this on fio 3.5 and 3.14 on FreeBSD 11.2 and on fio 3.12 on Ubuntu 19.04.

```
# ~/fio-3.14-11.2 filename_ok.fio 
create: (g=0): rw=write, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=posixaio, iodepth=128
fio-3.14
Starting 1 process

create: (groupid=0, jobs=1): err= 0: pid=64798: Mon Jul  1 11:17:28 2019
  write: IOPS=29.4k, BW=3678MiB/s (3857MB/s)(1207MiB/328msec)
    slat (nsec): min=662, max=473876, avg=2666.92, stdev=14338.17
    clat (usec): min=314, max=44140, avg=4001.28, stdev=2581.62
     lat (usec): min=318, max=44173, avg=4003.95, stdev=2581.59
    clat percentiles (usec):
     |  1.00th=[ 2573],  5.00th=[ 2868], 10.00th=[ 2999], 20.00th=[ 3130],
     | 30.00th=[ 3294], 40.00th=[ 3458], 50.00th=[ 3654], 60.00th=[ 3851],
     | 70.00th=[ 4047], 80.00th=[ 4293], 90.00th=[ 4883], 95.00th=[ 5342],
     | 99.00th=[10552], 99.50th=[26084], 99.90th=[40109], 99.95th=[42206],
     | 99.99th=[44303]
  lat (usec)   : 500=0.06%, 750=0.07%, 1000=0.07%
  lat (msec)   : 2=0.40%, 4=67.73%, 10=30.64%, 20=0.34%, 50=0.68%
  cpu          : usr=12.54%, sys=85.93%, ctx=137, majf=0, minf=2
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.2%, 16=0.3%, 32=0.7%, >=64=98.7%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=91.5%, 8=7.4%, 16=1.0%, 32=0.1%, 64=0.1%, >=64=0.1%
     issued rwts: total=0,9652,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
  WRITE: bw=3678MiB/s (3857MB/s), 3678MiB/s-3678MiB/s (3857MB/s-3857MB/s), io=1207MiB (1265MB), run=328-328msec
# ~/fio-3.14-11.2 filename_too_long.fio 
Bad option <foobr/perftest/ds.micro.127>
fio: job create dropped
# fio -v
fio-3.5
# ~/fio-3.14-11.2 -v
fio-3.14
```
Looking at length of filename argument:
```
# grep filename filename_too_long.fio |cut -d= -f2 | wc -c
4114
# grep filename filename_ok.fio |cut -d= -f2 | wc -c
4081
```
I've attached the two fio files I ran in the above examples:
[filename_ok.fio.txt](https://github.com/axboe/fio/files/3346326/filename_ok.fio.txt)
[filename_too_long.fio.txt](https://github.com/axboe/fio/files/3346327/filename_too_long.fio.txt)

**Comment by axboe** [comment]
PATH_MAX on most OS's is defined as 4096, so this isn't really a surprise (nor something fio can do anything about).

**Comment by powernap** [comment]
Understand the PATH_MAX limit, but each path in the filename list is quite short - I just have a lot of files in the filename argument, since I cannot auto-generate them with filename_format.

**Comment by powernap** [comment]
OK, finally had a chance to look at the code. Obvious workaround is to increase size allocated to string in init.c and increase OPT_LEN_MAX in parse.h - everything is fine when I bump these three instances of 4096 to 8192, for example.

**Comment by axboe** [comment]
Good point, on the per-option limit, not filename. I'll be fine with making that change.

**Comment by powernap** [comment]
One question I have is whether it makes sense to have the hard-coded malloc() and fgets() length for string in __parse_jobs_ini() in init.c instead set to OPT_LEN_MAX from parse.h? It seems they're quite related.

**Comment by axboe** [comment]
Yeah I think that'd make sense, even if they aren't totally the one and same thing.
