### ISSUE TITLE
http ioengine should have FIO_SYNCIO flag

### ISSUE THREAD

**Issue by vincentkfu** [axboe/fio#797]
I noticed that the http ioengine does not have the FIO_SYNCIO flag but it does appear to carry out synchronous operations. In its current state latencies are measured incorrectly. I created a branch with a patch to add the flag:

https://github.com/vincentkfu/fio/tree/http

However, I have no means to test the patch. Is there anyone who can test this? @l-mb? Or perhaps it's low risk enough to go in without testing?

**Comment by axboe** [comment]
Yes, it's definitely a sync engine, so the patch looks correct to me.

**Comment by vincentkfu** [comment]
I've sent the patch to the mailing list.
