### ISSUE TITLE
libaio library not found on ESXi

### ISSUE THREAD

**Issue by kennethburgener** [axboe/fio#80]
Ryan H. added support for ESXi, but libaio gets linked when found on a system.  ESXi doesn't have libaio available.

    $ ./configure --esx
    $ make
    $ scp fio root@esxhost:/scratch/

    esxhost # ./fiobin
    ./fiobin: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory

**Comment by rustyscottweber** [comment]
Sounds like the binary should be statically linked against lbaio instead of dynamically in the case of esxi.
