### ISSUE TITLE
Failed parsing random_distribution=zoned_abs

### ISSUE THREAD

**Issue by WOWSCpp** [axboe/fio#800]
I just followed the instruction here: https://fio.readthedocs.io/en/latest/fio_man.html
and my script is as follows:
```
fio_blocksize="4K"
size="500G"
iodepth="64"
rread=80
rwrite=20
numjob="1"
filename="/dev/bcache0"
fio --direct=1 --size=${size} --blocksize=${fio_blocksize} --ioengine=libaio -thread --rw=randwrite --random_distribution=zoned_abs=60/20G:30/100G:10/500g --iodepth=${iodepth} --numjob=${numjob} --group_reporting  --filename=${filename} --name=test  --output=../results/overall_iostat.txt
```
and I then got an error like this:
fio: failed parsing random_distribution=zoned_abs=60/20G:30/100G:10/500g

**Comment by axboe** [comment]
The man page says you need to use:

random_distribution=<type>:parameters

Hence a colon after the type, only one equal sign in there. So you'd want:

--random_distribution=zoned_abs:60/20G:30/100G:10/500g

**Comment by WOWSCpp** [comment]
> The man page says you need to use:
> 
> random_distribution=:parameters
> 
> Hence a colon after the type, only one equal sign in there. So you'd want:
> 
> --random_distribution=zoned_abs:60/20G:30/100G:10/500g

Actually I have tried the command you said, and I tried again with 
--random_distribution=zoned_abs:60/20G:30/100G:10/500g
it showed almost the same error: fio: failed parsing random_distribution=zoned_abs:60/20G:30/100G:10/500g

**Comment by sitsofe** [comment]
@WOWSCpp Is that little `g` at the end supported syntax (https://fio.readthedocs.io/en/latest/fio_doc.html#parameter-types )?

**Comment by axboe** [comment]
Not sure why it fails, just tried this locally:
```
fio --name=sde --rw=randread --direct=1 --random_distribution=zoned_abs:60/2g:30/5g:10/2g --filename=/dev/sde
```

and it parses and runs just fine. Cap or small 'g' should be fine. Maybe try --debug=parse at the start of the command line?

**Comment by sitsofe** [comment]
@WOWSCpp which version of fio are you using?

**Comment by WOWSCpp** [comment]
@sitsofe It's fio-3.1

**Comment by WOWSCpp** [comment]
@axboe Thanks! I'll try it later and then tell you if it works for me.

**Comment by axboe** [comment]
Just upgrade your fio version, it's old and this bug has been fixed. First line of defense against some issue you see is always to use the latest fio. Sometimes that'll fix the issue for you, and save you (and us) some time.

**Comment by WOWSCpp** [comment]
@axboe @sitsofe Thanks very much & really appreciate your time!
