### ISSUE TITLE
Latency graph

### ISSUE THREAD

**Issue by chinmayprabhudesai** [axboe/fio#803]
I am really new to this application and I'm helping a team member figure out how to use the `gfio` tool. I had some questions regarding that.

Is there a way to plot a latency graph?

I see [setup_iops_graph](https://github.com/axboe/fio/blob/master/gfio.c#L80) and [setup_bandwidth_graph](https://github.com/axboe/fio/blob/master/gfio.c#L99) but I don't see a latency graph function. I saw some latency related code in the `gclient.c` file not really sure how it relates to the graphs.

Is there a milestone to add it in the future ?

Any way latency can be obtained for a job using the `gfio` application ?

Hoped to find some information in the docs, but very little is mentioned about gfio.

**Comment by sitsofe** [comment]
@chinmayprabhudesai I can't help much as I don't build `gfio` but maybe @smcameron / @axboe know if plotting latency is in there.

I'm afraid If the functionality **isn't** already in `gfio` then I doubt anyone will be able tell you if (let alone when) it will ever be added as `fio` doesn't have a roadmap.

**Comment by smcameron** [comment]
It's been about 5 years since I've done anything related to storage, so my memory is pretty hazy on this.  I do see some things related to latency in gclient.c

https://github.com/axboe/fio/blob/master/gclient.c#L1338

It calls something called gfio_show_latency_buckets(), https://github.com/axboe/fio/blob/master/gclient.c#L931 which if I remember right, there's something like a bar graph of latency buckets, and there's a thing for drawing bar graphs in graph.c https://github.com/axboe/fio/blob/master/graph.c#L436 so I think there's at least some kind of graph related to latency there.

-- steve

**Comment by chinmayprabhudesai** [comment]
@sitsofe and @smcameron,

Thanks for your quick response to the issue!

@smcameron,

I noticed those lines in the `gclient.c` (as I mentioned in the original comment). I didn't follow the code to `graph.c`. I see there's a command-line script that generates plots (`.svg` files) from the log files, but nothing more. 

I checked the manpage for fio, all it say's is this:
> write_bw_log=str
If given, write a bandwidth log of the jobs in this job file. Can be used to store data of the bandwidth of the jobs in their lifetime. **The included fio_generate_plots script uses  gnuplot  to  turn  these  text files  into  nice  graphs.  See write_lat_log for behaviour of given filename.** For this option, the postfix is _bw.x.log, where x is the index of the job (1..N, where N is the number of jobs). If per_job_logs is false, then the filename will not include the job index.


Assuming that gfio is the only file that does actual GUI stuff, I don't see any graphs for latency. Perhaps none were implemented. 

Thanks for your help though!

Unless the maintainers are accepting any feature requests for gfio this ticket, it can be marked closed!

**Comment by sitsofe** [comment]
@chinmayprabhudesai - way to go anonymous team member!

FWIW: there are other tools that can post process various logs into graphs using other tools like gnuplot (see `tools/plot/fio2gnuplot` and `tools/fio_generate_plots`) but they are not interactive GUI tools.

**Comment by chinmayprabhudesai** [comment]
Thanks for pointing to additional resources!

Glad you caught it while it was visible :), realized that I should have verified the content of the snippet before uploading, so took it down.
