### ISSUE TITLE
Multiple TabError's when trying to run fio2gnuplot with Python 3

### ISSUE THREAD

**Issue by kapsh** [axboe/fio#804]
`tools/plot/fio2gnuplot` cannot be run with Python 3 because it mixes tabs with spaces which became SyntaxError in Python 3.
```
❯ python fio2gnuplot    
  File "fio2gnuplot", line 42
    fio_data_file.append(file)
                             ^
TabError: inconsistent use of tabs and spaces in indentation
```
There are more of them.

**Comment by kapsh** [comment]
I am willing to fix this. Just tell me please should I correct only broken places manually or make the whole file pep-8 compliant (indent with four spaces, etc.).

**Comment by sitsofe** [comment]
Hi @kapsh:

https://github.com/axboe/fio/blob/master/tools/plot/fio2gnuplot is the file that needs fixing up. Something like:
```
find . -exec file {} \; | grep Python
```

will tell you about which files in the fio repo are Python ones.

**Comment by kapsh** [comment]
@sitsofe sure, I already found and checked them. They are runnable except this one. Do you want me to take care about other files as well?

**Comment by sitsofe** [comment]
@kapsh If the others are fine we can just fix this file. Could you submit a pull request with your sign-off on it?

**Comment by kapsh** [comment]
Fine, I will try to touch as little as possible.
