### ISSUE TITLE
High number of threads result in file open errors

### ISSUE THREAD

**Issue by sm259** [axboe/fio#807]
When running a high number of threads ~~using the linux CFQ scheduler~~, there seems to be a problem opening the files during the workload. This issue was originally found in version 2.2.6, but is present at least up untill 3.9, however in version 3.9, it takes much longer to reproduce. With version 2.2.6 up to 3.8, I can reproduce with 10 second workloads about 50% of the time.

~~Also, this issue is not present when using the linux noop scheduler.~~ I am running on Ubuntu 16.04.10, kernel version 4.17.7.

I have 43 drives being tested, each with 16 jobs. If I reduce the number of drives to 36 (576 threads), the issue is not seen, but any number of drives higher than 36 causes it.

I am running using all command line parameters, which are:

--rw=randrw 
--thread=1 
--rwmixwrite=10 
--norandommap=1
--iomem=mmaphuge 
--numjobs=16 
--direct=1 
--hugepage-size=2m 
--iomem_align=2m 
--bs=2097152
--ioengine=sync
--output-format=json 
--eta=always

After the workload completes, I get this error on 2.2.6: 

`<fio: try reducing/setting openfiles (failed at 0 of 1)>`

On later versions (around 3.6 - 3.9):

`<fio: try reducing/setting openfiles (failed at 0 of 1)
*job_name*: No I/O performed by sync, perhaps try --debug=io option for details?>`

I set --debug=io, as well as --debug=all, but got no further information from fio.

This error message is from td_io_open_file() in ioengines.c, and as far as I can tell, the error gets logged after a call from get_next_file_rr() in io_u.c. So for some reason the round robin fails to get the next file ~~when the CFQ scheduler is being used~~.

EDIT: I actually can reproduce the issue using the noop scheduler.

**Comment by sm259** [comment]
Here is the code where I have tracked the issue to. The print statement I added only gets printed when the run fails. If it passes, I never see the print. So it's looking like the thread either never started, or failed to create the file that FIO is looking for, which matches the error shown in later versions: `No I/O performed by sync, perhaps try --debug=io option for details?`

Starting at line 1003 in version 2.2.6:
```c
static struct fio_file *get_next_file_rr(struct thread_data *td, int goodf,
					 int badf)
{
	unsigned int old_next_file = td->next_file;
	struct fio_file *f;

	do {
		int opened = 0;

		f = td->files[td->next_file];

		td->next_file++;
		if (td->next_file >= td->o.nr_files)
			td->next_file = 0;

		dprint(FD_FILE, "trying file %s %x\n", f->file_name, f->flags);
		if (fio_file_done(f)) {
			f = NULL;
			continue;
		}

		if (!fio_file_open(f)) {
			int err;

			if (td->nr_open_files >= td->o.open_files)
				return ERR_PTR(-EBUSY);
                        **printf("Entry from line 1030 in io_u.c\n");  // Added debug print**
			err = td_io_open_file(td, f);
			if (err) {
				dprint(FD_FILE, "error %d on open of %s\n",
					err, f->file_name);
				f = NULL;
				continue;
			}
			opened = 1;
		}

		dprint(FD_FILE, "goodf=%x, badf=%x, ff=%x\n", goodf, badf,
								f->flags);
		if ((!goodf || (f->flags & goodf)) && !(f->flags & badf))
			break;

		if (opened)
			td_io_close_file(td, f);

		f = NULL;
	} while (td->next_file != old_next_file);

	dprint(FD_FILE, "get_next_file_rr: %p\n", f);
	return f;
}
```

**Comment by axboe** [comment]
I don't think the scheduler has anything to do with it, outside of it altering timing so that you'll get more files open at the same time. What does ulimit -n say for you? You probably just want to bump the number of open files available to you.

**Comment by sm259** [comment]
ulimit -n was set to 1024 on this system. I adjusted it to 2048.

That does appear to be the problem! I had looked at the sysctl fs.file-max, which was obviously not the problem since it was set to over three million.

I was not aware of the ulimit, thank you @axboe !
