### ISSUE TITLE
got first direct IO errored when use -ioengine=splice

### ISSUE THREAD

**Issue by 2005songliwei** [axboe/fio#810]
Hi experts,
when I run fio test with following argument will got first IO error:
fio -filename=/dev/sda -direct=1 -iodepth 1 -thread -rw=rw -rwmixread=70 -ioengine=splice -bs=16k -size=64M -numjobs=15 -runtime=150 -group_reporting -name=mytest

the error only happened when ioengine is "splice"

the detail error information is: 
fio: looks like splice doesn't work on this file system
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.

The error will gone if specify direct=0,
but during test, the error exist from v3.13, and the newest version also exist the issue.
and I also found it is following commit which import the issue:

commit 08dc3bd5061269afa96e72d5e5985a11ea51ed01
Author: Jens Axboe <axboe@kernel.dk>
Date:   Tue Nov 20 19:42:19 2018 -0700

    backend: initialize io engine before io_u buffers
    
    Otherwise we call io_ops->io_u_init() before the IO scheduler is
    setup, which is somewhat backwards.
    
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

diff --git a/backend.c b/backend.c
index d64cc9922114..2f103b3abb15 100644
— a/backend.c
+++ b/backend.c
@@ -1698,6 +1698,9 @@ static void *thread_main(void *data)
        if (!init_iolog(td))
                goto err;
 
+       if (td_io_init(td))
+               goto err;
+
        if (init_io_u(td))
                goto err;
 
@@ -1728,9 +1731,6 @@ static void *thread_main(void *data)
        if (!o->create_serialize && setup_files(td))
                goto err;
 
-       if (td_io_init(td))
-               goto err;
-
        if (!init_random_map(td))
                goto err;

after revert this commit, the issue gone.
Could you help check if this is the real issue?

Thanks,
Liwei.

**Comment by sitsofe** [comment]
Hmm. I don't think the commit above is wrong but I think the code around https://github.com/axboe/fio/blob/9caaf02b06deecf0b0a13c16b6d59dddc64b8c35/engines/splice.c#L281 looks a bit suspicious:

```c
	/*
	 * And if vmsplice_to_user works, we definitely need aligned
	 * buffers. Just set ->odirect to force that.
	 */
	if (td_read(td))
		td->o.mem_align = 1;
```

@axboe I thought the value of `o.mem_align` was the number of bytes to align to so shouldn't it be set to the `page_size`?

**Comment by axboe** [comment]
@sitsofe I think you are right, that's definitely a bug. We align by default, so we don't need this code. I'm pretty sure it dates back to before that was the case. I'll kill the case.
