### ISSUE TITLE
Invalid job progress and race condition

### ISSUE THREAD

**Issue by Ryanfsdf** [axboe/fio#813]
When I run
 ```
fio --ioengine=libaio --bs=128K  --size=2G --readwrite=write --numjobs=1 --name=test --directory=.
```
it shows 
```
Jobs: 1 (f=1): [W(1)] [inf% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 1158050441d:07h:00m:12s]
```
and the test runs for a lot longer than expected. This occurs roughly half the time, so I believe it involves a race condition. 

This is on Ubuntu 16.04.3.

**Comment by axboe** [comment]
Could you do:

$ ps aux | grep fio

which should show you two jobs. The first is the task that's doing the management, the other one is the actual IO job. For the IO job, do:

$ gdb -p <pid of IO job>

and then do the 'bt' command to get a backtrace of it.

Also, what version of fio? If it's not new, please update to latest release first, thanks.

**Comment by sitsofe** [comment]
@Ryanfsdf which version of fio? I have a faint memory of problems in that area being resolved a few years back...

**Comment by Ryanfsdf** [comment]
Ahh, it was an archaic version (2.2.10) installed from the package manager. Closing this issue as the latest version doesn't exhibit this.
