### ISSUE TITLE
Bandwidth displayed during test is too low

### ISSUE THREAD

**Issue by llamafilm** [axboe/fio#815]
I'm fairly new to fio so I don't know enough to call this a bug, maybe it's a lack of understanding on my part.  Every time I run a sequential write test on a ZFS pool, the final bandwidth result is always significantly higher than the bandwidth displayed during the test.  Here is an example.  During the test, the bandwidth fluctuates between 600 - 720 MiB/s, but at the end it shows 734MiB/s.  I believe the 734 number is accurate based on the total time, so why is in-progress display low?

```
# fio --name=seqwrite --rw=write --bs=1M --numjobs=1 --size=30G --directory=/tank --direct=1
seqwrite: (g=0): rw=write, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=psync, iodepth=1
fio-3.1
Starting 1 process
seqwrite: Laying out IO file (1 file / 30720MiB)
fio: native_fallocate call failed: Operation not supported
Jobs: 1 (f=1): [W(1)][100.0%][r=0KiB/s,w=636MiB/s][r=0,w=636 IOPS][eta 00m:00s] 
seqwrite: (groupid=0, jobs=1): err= 0: pid=14175: Wed Sep 11 11:15:30 2019
  write: IOPS=734, BW=734MiB/s (770MB/s)(30.0GiB/41847msec)
    clat (usec): min=185, max=100354, avg=1333.63, stdev=1047.15
     lat (usec): min=206, max=100377, avg=1359.47, stdev=1048.58
    clat percentiles (usec):
     |  1.00th=[  231],  5.00th=[  302], 10.00th=[ 1205], 20.00th=[ 1303],
     | 30.00th=[ 1319], 40.00th=[ 1352], 50.00th=[ 1385], 60.00th=[ 1418],
     | 70.00th=[ 1450], 80.00th=[ 1500], 90.00th=[ 1565], 95.00th=[ 1631],
     | 99.00th=[ 1876], 99.50th=[ 2089], 99.90th=[ 3359], 99.95th=[ 4228],
     | 99.99th=[14877]
   bw (  KiB/s): min=563200, max=3178496, per=100.00%, avg=751992.75, stdev=307495.09, samples=83
   iops        : min=  550, max= 3104, avg=734.34, stdev=300.29, samples=83
  lat (usec)   : 250=3.12%, 500=5.62%, 750=0.46%, 1000=0.04%
  lat (msec)   : 2=90.14%, 4=0.57%, 10=0.03%, 20=0.01%, 100=0.01%
  lat (msec)   : 250=0.01%
  cpu          : usr=2.48%, sys=26.79%, ctx=232099, majf=0, minf=26
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,30720,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=734MiB/s (770MB/s), 734MiB/s-734MiB/s (770MB/s-770MB/s), io=30.0GiB (32.2GB), run=41847-41847msec
```

**Comment by sitsofe** [comment]
It looks like the I/O is fluctuating wildly:

```
   bw (  KiB/s): min=563200, max=3178496, per=100.00%, avg=751992.75, stdev=307495.09, samples=83
```

The difference between max and min is very large. I suspect part of this is down to ZFS not truly "doing" direct I/O (https://github.com/zfsonlinux/zfs/commit/a584ef26053065f486d46a7335bea222cb03eeea ) so there may be cache effects. @llamafilm do you see the same issue on ZFS/ext4 or raw block devices?

**Comment by llamafilm** [comment]
This pool was created using block devices.
I see the same problem if I run with `direct=0`.  Thanks for the link; It says ZoL doesn't support unbuffered writes.  Indeed I can see`iostat` shows disks still writing for a few seconds after `fio` returns, which means the number at the end result must be inflated due to the buffer.
I am trying to find the right way to test a sequential workload when the buffer is full, i.e. the actual disk speed.  Maybe the answer is to use `end_fsync` instead of `direct`.

**Comment by sitsofe** [comment]
@llamafilm while the pool is on raw devices your choice of filesystem doesn't "just pass" direct I/O down to the block device (as you've found) so I'll close this as it appears to not be an "issue" in `fio` itself.

It's true you can use `end_fsync=1` to force waiting until all data written is on non-volatile storage but bear in mind that guarantee is slight stricter than what mere direct I/O asks for (so if you're benchmarking against other filesystems make sure you use `end_fsync=1` on them too). The other thing you can do is just do so much non-overlapping I/O it can't possibly all be buffered. The more you do over your buffer size the more it will reflect what the underlying storage can do...
