### ISSUE TITLE
[Bug][FIO 3.9] fio verify bs size limit?

### ISSUE THREAD

**Issue by ufo2243** [axboe/fio#822]
fio -direct=0 -iodepth=1 -rw=write -ioengine=libaio -bs=44 -size=16M -numjobs=1 -runtime=1000 -group_reporting -name=test -filename=./test.1233213 -verify=crc64 -do_verify=1

Starting 1 process
fio: pid=6669, got signal=11

Run status group 0 (all jobs):

Disk stats (read/write):
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

bs must bigger then 44, otherwise fio verfify will fail. and change verify type won't help.  
I thought it might be caused by fio verfify info is bigger then 44 Byte.
fio version 3.9

**Comment by axboe** [comment]
Pushed out a fix for this.
