### ISSUE TITLE
Can I test a ram using fio?

### ISSUE THREAD

**Issue by CentUser** [axboe/fio#824]
Recently, I am experimenting on fio with all of its parameters and am trying to figure out what it means by specifying those options.

Hardware:
CPU:  Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
RAM: 128G
Dell 730xd

Here, I made up a ram loopback disk :
/dev/loop1: [64768]:262724 (/tmp/fio_test_ram_3g)

and formated with ext4. 

tested it using the following fio job file:
```
[global]
bs=4k
direct=1
buffered=0
group_reporting
new_group
numjobs=24
runtime=90
size=2G

ioengine=libaio
# rw=randread
rw=randwrite
iodepth_batch_submit=32
iodepth=1
[rr4k_ram_3g_sync]
filename=/home/test/work/loop_ram/3g/test_file
sync=1

stonewall

[rr4k_ram_3g_nosync]
sync=0
filename=/home/test/work/loop_ram/3g/test_file
```

Results:
```
rr4k_ram_3g_sync: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
rr4k_ram_3g_nosync: (g=1): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.1
Starting 48 processes
Jobs: 48 (f=48): [w(48)][0.1%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 19h:53m:31s]      
rr4k_ram_3g_sync: (groupid=0, jobs=24): err= 0: pid=26254: Sun Sep 29 17:45:36 2019
  write: IOPS=176, BW=707KiB/s (724kB/s)(64.2MiB/92963msec)
    slat (usec): min=3, max=20709, avg=213.13, stdev=1002.27
    clat (usec): min=86, max=4891.9k, avg=135615.92, stdev=429172.47
     lat (usec): min=106, max=4891.9k, avg=135829.40, stdev=429139.00
    clat percentiles (msec):
     |  1.00th=[    8],  5.00th=[   40], 10.00th=[   44], 20.00th=[   48],
     | 30.00th=[   52], 40.00th=[   55], 50.00th=[   58], 60.00th=[   62],
     | 70.00th=[   65], 80.00th=[   70], 90.00th=[   81], 95.00th=[   99],
     | 99.00th=[ 2802], 99.50th=[ 3037], 99.90th=[ 4866], 99.95th=[ 4866],
     | 99.99th=[ 4866]
   bw (  KiB/s): min=    8, max=  152, per=7.63%, avg=53.84, stdev=23.75, samples=2437
   iops        : min=    2, max=   38, avg=13.46, stdev= 5.94, samples=2437
  lat (usec)   : 100=0.01%, 250=0.06%, 500=0.01%, 1000=0.01%
  lat (msec)   : 10=0.99%, 20=0.25%, 50=22.76%, 100=71.17%, 250=0.80%
  lat (msec)   : 500=0.15%, 750=0.15%, 1000=0.58%, 2000=1.62%, >=2000=1.46%
  cpu          : usr=0.00%, sys=0.01%, ctx=27595, majf=0, minf=258
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,16425,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
rr4k_ram_3g_nosync: (groupid=1, jobs=24): err= 0: pid=26278: Sun Sep 29 17:45:36 2019
  write: IOPS=2908, BW=11.4MiB/s (11.9MB/s)(1056MiB/92955msec)
    slat (usec): min=3, max=20740, avg=38.03, stdev=439.01
    clat (usec): min=7, max=4849.4k, avg=8211.42, stdev=105190.89
     lat (usec): min=74, max=4849.4k, avg=8249.63, stdev=105191.07
    clat percentiles (usec):
     |  1.00th=[    101],  5.00th=[    104], 10.00th=[    105],
     | 20.00th=[    108], 30.00th=[    109], 40.00th=[    111],
     | 50.00th=[    114], 60.00th=[    116], 70.00th=[    124],
     | 80.00th=[   6783], 90.00th=[  15795], 95.00th=[  20317],
     | 99.00th=[  30016], 99.50th=[  35390], 99.90th=[1837106],
     | 99.95th=[2801796], 99.99th=[3338666]
   bw (  KiB/s): min=    8, max= 5044, per=7.53%, avg=876.07, stdev=976.27, samples=2472
   iops        : min=    2, max= 1261, avg=218.90, stdev=243.96, samples=2472
  lat (usec)   : 10=0.01%, 20=0.02%, 50=0.01%, 100=0.44%, 250=75.79%
  lat (usec)   : 500=0.06%, 750=0.02%, 1000=0.05%
  lat (msec)   : 2=0.63%, 4=0.71%, 10=6.18%, 20=10.64%, 50=5.18%
  lat (msec)   : 100=0.04%, 500=0.01%, 750=0.01%, 1000=0.04%, 2000=0.12%
  lat (msec)   : >=2000=0.08%
  cpu          : usr=0.03%, sys=0.10%, ctx=293297, majf=0, minf=286
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,270372,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=707KiB/s (724kB/s), 707KiB/s-707KiB/s (724kB/s-724kB/s), io=64.2MiB (67.3MB), run=92963-92963msec

Run status group 1 (all jobs):
  WRITE: bw=11.4MiB/s (11.9MB/s), 11.4MiB/s-11.4MiB/s (11.9MB/s-11.9MB/s), io=1056MiB (1107MB), run=92955-92955msec

Disk stats (read/write):
  loop1: ios=0/291702, merge=0/0, ticks=0/2801921, in_queue=2943768, util=99.90%
```

------------------------------------------------------

While I am wandering that why they differ in the speed of write to ram only because of sync.

**Comment by CentUser** [comment]
Same configure on my laptop with
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
RAM:8G DDR4 2133 MHz

--------------------------------------------------------------
rr4k_ram_3g_sync: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
rr4k_ram_3g_nosync: (g=1): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.1
Starting 48 processes
Jobs: 31 (f=31): [w(25),_(2),w(1),_(6),w(2),_(1),w(2),_(4),w(1),_(4)][14.3%][r=0KiB/s,w=1000MiB/s][r=0,w=256k IOPS][Jobs: 24 (f=24): [w(24),_(24)][15.5%][r=0KiB/s,w=683MiB/s][r=0,w=175k IOPS][eta 04m:28s]                            Jobs: 24 (f=24): [w(24),_(24)][62.5%][r=0KiB/s,w=585MiB/s][r=0,w=150k IOPS][eta 00m:54s]
rr4k_ram_3g_sync: (groupid=0, jobs=24): err= 0: pid=16671: Sun Sep 29 06:07:15 2019
  write: IOPS=89.9k, BW=351MiB/s (368MB/s)(30.9GiB/90001msec)
    slat (usec): min=2, max=23179, avg=17.85, stdev=180.40
    clat (nsec): min=775, max=53443k, avg=247966.29, stdev=626958.54
     lat (usec): min=10, max=53498, avg=265.91, stdev=657.74
    clat percentiles (usec):
     |  1.00th=[   78],  5.00th=[  117], 10.00th=[  128], 20.00th=[  139],
     | 30.00th=[  145], 40.00th=[  153], 50.00th=[  159], 60.00th=[  169],
     | 70.00th=[  184], 80.00th=[  235], 90.00th=[  334], 95.00th=[  457],
     | 99.00th=[ 1811], 99.50th=[ 3752], 99.90th=[ 9503], 99.95th=[12387],
     | 99.99th=[21103]
   bw (  KiB/s): min= 2887, max=21280, per=3.52%, avg=12668.67, stdev=6978.40, samples=4296
   iops        : min=  721, max= 5320, avg=3166.83, stdev=1744.57, samples=4296
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.03%, 50=0.22%
  lat (usec)   : 100=2.05%, 250=79.09%, 500=14.72%, 750=1.88%, 1000=0.37%
  lat (msec)   : 2=0.70%, 4=0.47%, 10=0.37%, 20=0.08%, 50=0.01%
  lat (msec)   : 100=0.01%
  cpu          : usr=0.92%, sys=2.58%, ctx=8679469, majf=0, minf=235
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,8087358,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
rr4k_ram_3g_nosync: (groupid=1, jobs=24): err= 0: pid=16695: Sun Sep 29 06:07:15 2019
  write: IOPS=259k, BW=1010MiB/s (1059MB/s)(48.0GiB/48661msec)
    slat (usec): min=2, max=30732, avg=25.00, stdev=233.41
    clat (nsec): min=511, max=48635k, avg=63638.27, stdev=175445.76
     lat (usec): min=5, max=48655, avg=88.81, stdev=294.86
    clat percentiles (usec):
     |  1.00th=[    7],  5.00th=[   10], 10.00th=[   13], 20.00th=[   18],
     | 30.00th=[   19], 40.00th=[   26], 50.00th=[   41], 60.00th=[   56],
     | 70.00th=[   78], 80.00th=[  105], 90.00th=[  128], 95.00th=[  145],
     | 99.00th=[  225], 99.50th=[  330], 99.90th=[ 1991], 99.95th=[ 3458],
     | 99.99th=[ 7701]
   bw (  KiB/s): min=27255, max=64169, per=4.30%, avg=44447.59, stdev=6047.31, samples=2267
   iops        : min= 6813, max=16042, avg=11111.53, stdev=1511.84, samples=2267
  lat (nsec)   : 750=0.09%, 1000=0.28%
  lat (usec)   : 2=0.20%, 4=0.06%, 10=4.56%, 20=31.45%, 50=20.88%
  lat (usec)   : 100=20.66%, 250=21.05%, 500=0.42%, 750=0.09%, 1000=0.06%
  lat (msec)   : 2=0.10%, 4=0.06%, 10=0.04%, 20=0.01%, 50=0.01%
  cpu          : usr=2.28%, sys=7.24%, ctx=14683617, majf=0, minf=234
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,12582912,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=351MiB/s (368MB/s), 351MiB/s-351MiB/s (368MB/s-368MB/s), io=30.9GiB (33.1GB), run=90001-90001msec

Run status group 1 (all jobs):
  WRITE: bw=1010MiB/s (1059MB/s), 1010MiB/s-1010MiB/s (1059MB/s-1059MB/s), io=48.0GiB (51.5GB), run=48661-48661msec

Disk stats (read/write):
  loop2: ios=0/27730749, merge=0/0, ticks=0/1935133, in_queue=1254597, util=99.26%

**Comment by sitsofe** [comment]
> While I am wandering that why they differ in the speed of write to ram only because of sync.

What filesystem is `/tmp` ? There's not really enough information here to know what's going to happen. If `/tmp` is on a disk backed filesystem I can well believe doing `O_SYNC` I/O is going to be much slower...

**Comment by CentUser** [comment]
> > While I am wandering that why they differ in the speed of write to ram only because of sync.
> 
> What filesystem is `/tmp` and what device is backing it? There's not really enough information here to know what's going to happen. If `/tmp` is on a disk backed filesystem I can well believe doing `O_SYNC` I/O is going to be much slower...

Yes, your question is to the point, I checked /tmp, and find that it is just an ordinary  dir under /. Which means /tmp is on an ext4 disk backed filesystem. Long time ago, I used linux, and was told that /tmp was always mounted as tmpfs, but now it seems like centos distribution have changed the convention. Sorry for the mistake.

Following the thought of testing a ram using fio, I moved the test file to /run, and checked that its filesystem is tmpfs which I take it is the ram filesystem. 

The same fio job configuration results as:

rr4k_ram_3g_sync: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
rr4k_ram_3g_nosync: (g=1): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
...
fio-3.1
Starting 48 processes
Jobs: 24 (f=24): [w(24),_(24)][26.6%][r=0KiB/s,w=422MiB/s][r=0,w=108k IOPS][eta 04m:08s]
rr4k_ram_3g_sync: (groupid=0, jobs=24): err= 0: pid=9449: Mon Sep 30 09:52:33 2019
  write: IOPS=37.4k, BW=146MiB/s (153MB/s)(12.8GiB/90002msec)
    slat (usec): min=3, max=3574, avg= 8.24, stdev=10.65
    clat (nsec): min=845, max=31188k, avg=632254.54, stdev=404436.64
     lat (usec): min=17, max=31198, avg=640.65, stdev=405.08
    clat percentiles (usec):
     |  1.00th=[  165],  5.00th=[  223], 10.00th=[  404], 20.00th=[  490],
     | 30.00th=[  523], 40.00th=[  562], 50.00th=[  627], 60.00th=[  676],
     | 70.00th=[  742], 80.00th=[  816], 90.00th=[  865], 95.00th=[  898],
     | 99.00th=[  971], 99.50th=[  996], 99.90th=[ 4948], 99.95th=[ 8094],
     | 99.99th=[16909]
   bw (  KiB/s): min=  472, max=15279, per=4.08%, avg=6100.51, stdev=1628.51, samples=4296
   iops        : min=  118, max= 3819, avg=1525.03, stdev=407.10, samples=4296
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 20=0.01%, 50=0.06%, 100=0.25%
  lat (usec)   : 250=7.59%, 500=15.43%, 750=47.43%, 1000=28.75%
  lat (msec)   : 2=0.35%, 4=0.02%, 10=0.08%, 20=0.03%, 50=0.01%
  cpu          : usr=0.43%, sys=1.73%, ctx=3369351, majf=0, minf=1272
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,3364097,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
rr4k_ram_3g_nosync: (groupid=1, jobs=24): err= 0: pid=9474: Mon Sep 30 09:52:33 2019
  write: IOPS=144k, BW=564MiB/s (592MB/s)(48.0GiB/87125msec)
    slat (usec): min=3, max=3472, avg= 5.82, stdev= 5.14
    clat (nsec): min=984, max=2126.2k, avg=158950.20, stdev=39652.09
     lat (usec): min=9, max=3591, avg=164.92, stdev=40.13
    clat percentiles (usec):
     |  1.00th=[   93],  5.00th=[   97], 10.00th=[  101], 20.00th=[  111],
     | 30.00th=[  130], 40.00th=[  159], 50.00th=[  172], 60.00th=[  180],
     | 70.00th=[  186], 80.00th=[  192], 90.00th=[  202], 95.00th=[  212],
     | 99.00th=[  239], 99.50th=[  243], 99.90th=[  251], 99.95th=[  253],
     | 99.99th=[  273]
   bw (  KiB/s): min=22536, max=36880, per=4.17%, avg=24100.54, stdev=1671.23, samples=4176
   iops        : min= 5634, max= 9220, avg=6024.89, stdev=417.81, samples=4176
  lat (nsec)   : 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 100=9.27%, 250=90.62%, 500=0.10%, 750=0.01%, 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=1.63%, sys=4.96%, ctx=12587570, majf=0, minf=2709
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,12582912,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=146MiB/s (153MB/s), 146MiB/s-146MiB/s (153MB/s-153MB/s), io=12.8GiB (13.8GB), run=90002-90002msec

Run status group 1 (all jobs):
  WRITE: bw=564MiB/s (592MB/s), 564MiB/s-564MiB/s (592MB/s-592MB/s), io=48.0GiB (51.5GB), run=87125-87125msec

Disk stats (read/write):
  loop1: ios=0/18375157, merge=0/0, ticks=0/3965563, in_queue=3979378, util=100.00%

Still nosync situation has approximately 3 times the bandwidth to sync version.
Compared to the former test on /tmp which is  backed on a ext4 formated disk, the difference reduce from about 11 times to 3 times.

Perhaps, this is really the difference between sync and nosync in ram access.

While my question is, whether I could test the speed of a ram using fio?

**Comment by sitsofe** [comment]
@CentUser What does "speed of RAM" mean though? You're going to be stuffing at least one (but maybe many more) abstraction over the top of your RAM to test it with `fio` and that's going to have a price.

For example doing I/O through that loopback device isn't going to be free - why wouldn't you just do I/O straight to a file in `tmpfs` folder? Are you were trying to workaround `direct=1` not working on `tmpfs` in which case you may need to ask yourself "how does `tmpfs` actually work behind the scenes?". If you think about it, something in RAM doesn't have traditional `O_SYNC` semantics because (traditionally) it's non-persistent. You would have to ask the kernel folks what `O_SYNC` on `tmpfs` means. Even though it turns into a no-op at the bottom perhaps there's still a cost to all the layers in-between? Why not use a purer RAM device via `brd` (e.g. `/dev/ram0`). Better yet, why not use a proper memory tester?

**Comment by CentUser** [comment]
@sitsofe Thank you for the advise, writing to a looped block device in ram and writing directly to tmpfs directory may be the same, perhaps just the dev element differs in memory. As I can see now, the fs layer may be the same, and what differs is the device driver. vfs layer -> ext4 device driver(for the loop device) -> tmpfs device driver -> ram.

As you suggested,  using tmpfs directly the data path should be vfs layer -> tmpfs device driver -> ram.  So the price paid  I think should be the ext4 device driver. 

Perhaps if I was to test the memory throughput, i should use tmpfs directory directly. I don't know the result, I'll try it.

In loop device case, tmpfs may really do not have an O_SYNC semantics, but ext4 device driver does. 

Now O_DIRECT,to me, means that we don't use buffer, but we could still specify an O_SYNC or not. with O_DIRECT | O_SYNC, we can be sure that the data is written from user space memory to disk which eventually is a loop device in memory, ie, from user space memory to another chunk of memory. 
Without O_SYNC, I read the kernel code, it uses completion which should add to some time delay.

In loop device case, maybe the bottle neck is the ext4 filesystem driver. 

I know I should find a proper memory tester, yet I think, using different methods, I could be happily  expecting some closer results.  Perhaps I'm wrong, actually testing ram throughput using fio is also just a wanton thoughts I'am diving in to the filesystem, and I read the codes for some time, I need to get my hand dirty. So I carried it out. 

I originally wanted to open a discussion, yet github does not provide such a place...

Sorry for the inconvenience  if there were, I am a beginner, and there might be faults, I am trying to get it.

**Comment by sitsofe** [comment]
> I originally wanted to open a discussion, yet github does not provide such a place...

No worries (and notice how you picked up that github wasn't the right place even though no one directly mentioned it - you're very astute!). You can always try the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails) but I can't guarantee an answer. If you're done for now could you close the issue - thanks!

FWIW `O_DIRECT` only guarantees that data has reached the disk but it DOESN'T guarantee it has reached non-volatile storage (and it says nothing about metadata). See https://lwn.net/Articles/457667/ for details!

**Comment by CentUser** [comment]
As you wish. @sitsofe
