### ISSUE TITLE
Can bw (MiB/s) max value be considered as the maximum bandwidth offered by the SSD

### ISSUE THREAD

**Issue by pankajd-57** [axboe/fio#829]
Hi,
I am trying to run FIO benchmark on the system with following flags. I wanted to bring Write bandwidth to 2900 MB/sec. However, after several tries , it is not coming to the expected number. between I got below result where the bw (MiB/s) max has gone up to 2754  MiB/s which comes to 2887 MB/s. This this result acceptable? If not, what changes should I make to get further performance?
I am using sequential write with 4k block size on ext4 filesystem with 16 threads. These parameters are fixed and should not be changed without buffered I/O. Please help me in this. 
```
_fio --name=seqwrite --rw=write --direct=1 --ioengine=libaio --bs=4k --numjobs=16 --size=4GB  --thread --iodepth=2 --group_reporting  --end_fsync=1_ 

seqwrite5: (groupid=0, jobs=16): err= 0: pid=52883: Sun Sep 29 16:37:59 2019
  write: IOPS=534k, BW=2085MiB/s (2186MB/s)(32.0GiB/15719msec)
    slat (usec): min=3, max=1245, avg=11.25, stdev= 8.19
    clat (nsec): min=340, max=2962.7k, avg=45250.20, stdev=19123.41
     lat (usec): min=18, max=2970, avg=56.56, stdev=20.29
    clat percentiles (usec):
     |  1.00th=[   21],  5.00th=[   26], 10.00th=[   30], 20.00th=[   34],
     | 30.00th=[   37], 40.00th=[   39], 50.00th=[   42], 60.00th=[   44],
     | 70.00th=[   48], 80.00th=[   53], 90.00th=[   65], 95.00th=[   81],
     | 99.00th=[  123], 99.50th=[  141], 99.90th=[  186], 99.95th=[  204],
     | 99.99th=[  251]
   **bw (  MiB/s): min= 1565, max= 2754, per=100.00%, avg=2205.29, stdev=17.67, samples=471**
   iops        : min=400767, max=705124, avg=564553.60, stdev=4523.83, samples=471
  lat (nsec)   : 500=0.01%, 750=0.01%, 1000=0.01%
  lat (usec)   : 2=0.01%, 4=0.01%, 10=0.07%, 20=0.91%, 50=74.95%
  lat (usec)   : 100=21.67%, 250=2.35%, 500=0.01%, 750=0.01%, 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%
  cpu          : usr=1.87%, sys=45.45%, ctx=7240391, majf=0, minf=820
  IO depths    : 1=0.1%, 2=100.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,8388608,0,16 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=2

Run status group 0 (all jobs):
  WRITE: bw=2085MiB/s (2186MB/s), 2085MiB/s-2085MiB/s (2186MB/s-2186MB/s), io=32.0GiB (34.4GB), run=15719-15719msec
```

**Comment by sitsofe** [comment]
@pankajd-57 

> I got below result where the bw (MiB/s) max has gone up to 2754 MiB/s which comes to 2887 MB/s

I'm afraid I don't understand this sentence even assuming you meant 2887 MiB/s (technically MB/s is a different unit to MiB).

> This this result acceptable?

There are too many possibilities to for me to say - I don't know your hardware, kernel configuration etc. What I do notice is a huge amount of time is used by the kernel (`sys=45.45%`) so you may want to focus on WHY that's so high (syscall overhead? Context switch overhead?). Also notice how you omitted your disk utilization stats from your output so there's even less to go on... I like to start by doing I/O to a block device (which obviously destroys the data on that device) so there's as little in the way as possible to get a maximum from that and only then add more layers such as a filesystem etc so I build up an idea of what each layer is adding...

> If not, what changes should I make to get further performance?

It sounds like you are trying to reach "hero numbers" (don't forget to read  https://github.com/axboe/fio/blob/master/MORAL-LICENSE if you're going to publish statistics using fio) and a bug report is not really the place for that discussion. Have you done a [google search for something like "fio go faster"](https://www.google.com/search?q=fio+go+faster)? That turns up things like the a [comment talking about people asking for "go faster options for fio"](https://github.com/axboe/fio/issues/579#issuecomment-382327888) and below that are more helpful suggestions in other comments.

As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.15/README#L58) (note that the list only accepts plain text emails).
