### ISSUE TITLE
FIO verify issue

### ISSUE THREAD

**Issue by viraj1899** [axboe/fio#830]
Can any one please explain my below FIO queries.As i am new to FIO command line tool. It will help me to understand the basic working

1> **Query1**: How **FIO wirte and check data integrity on file** using below script

write script :
fio --ioengine=libaio --bs=4K --direct=1 --verify=pattern --verify_pattern=0x0123456789abcdef --do_verify=0 --name=write --filename=/home/Home/writing --rw=write --size=1G --verify_interval=512

verify script:
fio --ioengine=libaio --bs=4K --direct=1 --verify=pattern --verify_pattern=0x0123456789abcdef --do_verify=1 --name=read --filename=/home/Home/writing --rw=read --size=1G --verify_interval=512

2> **Query 2:** Is the below script valid ? i need to writing data into file and read it back and Where can we get result of same ?
fio --ioengine=libaio --rw=randwrite  --bs=4k --direct=1 --size=1G --iodepth=16 --verify=crc32c --name=/home/Home/writeandverify

3> **Query 3:** What the role of generated **.state file** and how to access it ?
root@X:# ll
total 102412
drwxr-xr-x 2 root root      4096 Oct  1 20:22 ./
drwxr-xr-x 3 root root      4096 Oct  1 20:00 ../
-rw-r--r-- 1 root root       192 Oct  1 20:22 local-write-0-verify.state
-rw-r--r-- 1 root root 104857600 Oct  1 20:22 writing
root@X:# fio-verify-state local-write-0-verify.state
root@X:# fio-verify-state: command not found

Thanks In Advance

**Comment by sitsofe** [comment]
@viraj1899 As these aren't so much issues in fio and more of a "How do I/Why is?" questions they are better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.15/README#L58) (note that the list only accepts plain text emails). Could you post this to the list and close the issue here? Thanks!

**Comment by viraj1899** [comment]
@sitsofe Thanks for reply, but can you please tell me where can we see the results of data integrity ? weather it been passed or failed ?
thanks
