### ISSUE TITLE
How to tell 'iops' exponent from json output?

### ISSUE THREAD

**Issue by msmith491** [axboe/fio#84]
I'm currently running fio with the `--status-interval=x` and `--output-format=json` options.  I get a nice large json dump which is very easy to navigate, but I can't seem to find any indication of the current exponent of the 'iops' value returned.

Example:

json <-- one status interval json dump

    json['jobs'][0]['write']['iops'] == 28

Another is:

    json['jobs'][0]['read']['iops'] == 11.11

The second one seems like it's probably measured in `K` iops, but for the first one I have no real indication if it's actual iops or `K` iops.

Although I'm fairly new to fio (and the product I'm measuring) and I'm not 100% sure if either are reasonable units for this value, which is why having a sure-fire way of figuring out those units would be very useful :)

**Comment by axboe** [comment]
In the json output, there's no rounding of the IOPS. If it says 11.11, it's 11.11, not 11.11K or something like that.

**Comment by msmith491** [comment]
What about latency in the json output?  In the 'lat' category is it expressed in `us` by default?
