### ISSUE TITLE
Documentation for error codes

### ISSUE THREAD

**Issue by donny372** [axboe/fio#842]
When running FIO, we got different error codes, but there is no documentation about the error codes. Could you please add some explanation for them? Thanks a lot!

**Comment by sitsofe** [comment]
@donny372 Nearly all of those error codes actually bubble up from syscalls and the meaning can vary from OS to OS. errno can be used to decode the list on Linux - http://man7.org/linux/man-pages/man3/errno.3.html .

One that doesn't that springs to mind is verification mismatch (EILSEQ) but even that error code is mapped to syscall-like error number of you look at the pre-glibc meaning.

Which error codes were you thinking of in particular?

**Comment by donny372** [comment]
@sitsofe Thanks! Since the error codes are from syscalls, I think we can close this bug.
