### ISSUE TITLE
fio fails to verify hdr.rand_seed if iolog reordered io_u

### ISSUE THREAD

**Issue by mingnus** [axboe/fio#844]
This issue is similar to #746, but the root cause might be different.

fio follows iolog to verify `verify_header.rand_seed`. However, if the iolog reordered `io_u` (using RB tree), then `get_next_verify()` cannot produce the same random number sequence. Fio therefore failed to do verification.

iolog reorders `io_u` when there's no `randommap`, which happened under the following context. Details are list at the end.
* Single file with `--rw=randreadwrite`, and `--norandommap`
* Multiple files with `--rw=randreadwrite` and `--norandommap`
* Multiple files with `--rw=readwrite`

Here are my questions after looking into the code:

* Is it necessary to check `verify_header.rand_seed`?
  The header itself is checksum-protected, and the `verify_header.rand_seed` is not used for data verification, so I think there's no need to verify the `rand_seed`.

* If checking `verify_header.rand_seed` is required, why fio checks it only when the rw mode is not `readwrite`? In other words, fio wastes time in generating `rand_seed` under non-readwrite modes.
```
  // in verify_io_u()
  if (!td_rw(td) || (td->flags & TD_F_VER_BACKLOG))
      io_u->rand_seed = hdr->rand_seed;
```

---

**Test cases**

```
[global]
do_verify=1
verify=md5
direct=1
thread=1

[failure_case1]
rw=randrw
norandommap
filename=test.bin
size=1m

[failure_case2]
stonewall
rw=randrw
norandommap
directory=.
nrfiles=2
size=1m

[failure_case3]
stonewall
rw=readwrite
directory=.
nrfiles=2
size=1m
```

Result:
```
verify: bad header rand_seed 456666279995977728, wanted 46386204153304124 at file test.bin offset 4096, length 4096 (requested block: offset=4096, length=4096)
fio: pid=28893, err=84/file:io_u.c:2031, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character
```

**Comment by sitsofe** [comment]
@mingnus Hmm. Does this go away if you load a state file?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. @mingnus if you can supply the requested information could you reopen this issue. Thanks!
