### ISSUE TITLE
Unable to get verify_only option working.

### ISSUE THREAD

**Issue by sellerb5** [axboe/fio#85]
As per documentation, verify_only option is supposed to read back and verify the data. Expect to see only reads when this option is used. However, I do see that it is actually writing the data (as shown below).

verify_only Do not perform specified workload---only verify data still matches previous invocation of this workload. This option allows one to check data multiple times at a later date without overwriting it. This option makes sense only for workloads that write data, and does not support workloads with the time_based option set. 

`# fio --name=job1 --filename=/tmp/aa --size=1M --rw=write --ioengine=libaio --direct=1 --verify_dump=1 --verify_only `
job1: (g=0): rw=write, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio-2.2.8
Starting 1 process

job1: (groupid=0, jobs=1): err= 0: pid=4316: Mon Jun  8 15:38:40 2015
  write: io=1024.0KB, bw=1000.0MB/s, iops=256000, runt=     1msec
    clat (usec): min=133118, max=133189, avg=133156.36, stdev=19.06
     lat (usec): min=0, max=5, avg= 0.07, stdev= 0.38
    clat percentiles (msec):
     |  1.00th=[  135],  5.00th=[  135], 10.00th=[  135], 20.00th=[  135],
     | 30.00th=[  135], 40.00th=[  135], 50.00th=[  135], 60.00th=[  135],
     | 70.00th=[  135], 80.00th=[  135], 90.00th=[  135], 95.00th=[  135],
     | 99.00th=[  135], 99.50th=[  135], 99.90th=[  135], 99.95th=[  135],
     | 99.99th=[  135]
    lat (msec) : 250=100.00%
  cpu          : usr=0.00%, sys=0.00%, ctx=2, majf=0, minf=28
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=256/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0

Run status group 0 (all jobs):
**WRITE: io=1024KB, aggrb=1000.0MB/s, minb=1000.0MB/s, maxb=1000.0MB/s, mint=1msec, maxt=1msec**

Disk stats (read/write):
    dm-1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=0/0, aggrmerge=0/0, aggrticks=0/0, aggrin_queue=0, aggrutil=0.00%
  sda: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Comment by axboe** [comment]
You need to set a verify type as well, ala verify=crc32c - does it work if you do that?

**Comment by sellerb5** [comment]
With verify-crc32 it does try to read, but fails and continues with the write operation.

`fio --name=job1 --filename=/tmp/aa --size=1M --rw=write --ioengine=libaio --direct=1 --verify_dump=1 --verify_only  --verify=crc32`
job1: (g=0): rw=write, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio-2.2.8
Starting 1 process
**verify: bad magic header a090, wanted acca at file /tmp/aa offset 0, length 4096
fio: pid=5216, err=84/file:io_u.c:1875, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character**

job1: (groupid=0, jobs=1): err=84 (file:io_u.c:1875, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=5216: Mon Jun  8 15:55:24 2015
  read : io=4096B, bw=4000.0KB/s, iops=1000, runt=     1msec
    slat (usec): min=41, max=41, avg=41.00, stdev= 0.00
    clat (usec): min=67, max=67, avg=67.00, stdev= 0.00
     lat (usec): min=109, max=109, avg=109.00, stdev= 0.00
    clat percentiles (usec):
     |  1.00th=[   67],  5.00th=[   67], 10.00th=[   67], 20.00th=[   67],
     | 30.00th=[   67], 40.00th=[   67], 50.00th=[   67], 60.00th=[   67],
     | 70.00th=[   67], 80.00th=[   67], 90.00th=[   67], 95.00th=[   67],
     | 99.00th=[   67], 99.50th=[   67], 99.90th=[   67], 99.95th=[   67],
     | 99.99th=[   67]
  write: io=1024.0KB, bw=256000KB/s, iops=64000, runt=     4msec
    clat (usec): min=130752, max=134136, avg=132430.52, stdev=966.29
     lat (usec): min=0, max=6, avg= 0.17, stdev= 0.54
    clat percentiles (msec):
     |  1.00th=[  131],  5.00th=[  131], 10.00th=[  133], 20.00th=[  133],
     | 30.00th=[  133], 40.00th=[  133], 50.00th=[  133], 60.00th=[  133],
     | 70.00th=[  133], 80.00th=[  135], 90.00th=[  135], 95.00th=[  135],
     | 99.00th=[  135], 99.50th=[  135], 99.90th=[  135], 99.95th=[  135],
     | 99.99th=[  135]
    lat (usec) : 100=0.39%
    lat (msec) : 250=99.61%
  cpu          : usr=66.67%, sys=0.00%, ctx=9, majf=0, minf=76
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=1/w=256/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0

Run status group 0 (all jobs):
   **READ: io=4KB, aggrb=4000KB/s, minb=4000KB/s, maxb=4000KB/s, mint=1msec, maxt=1msec
  WRITE: io=1024KB, aggrb=256000KB/s, minb=256000KB/s, maxb=256000KB/s, mint=4msec, maxt=4msec**

Disk stats (read/write):
    dm-1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=1/6, aggrmerge=0/0, aggrticks=0/36, aggrin_queue=36, aggrutil=24.00%
  sda: ios=1/6, merge=0/0, ticks=0/36, in_queue=36, util=24.00%

**Comment by axboe** [comment]
Yes, and it should, because the data can't be verified without having been written first. The intent of verify_only is to add it to a job that has previously run, and then it will only verify the parts that were previously written. If you add --verify_only to a job that hasn't been allowed to write before, then you will fail verifying the contents because they are not valid.

Remove --verify_only, run the job. Then run it again, this time adding --verify_only. The latter invocation will read and verify the previously written parts, discarding any writes to the file (basically it turns those into reads).

**Comment by sellerb5** [comment]
Yes, the read works in that case. But still I see writes happening after reads with verify_only option. Is this expected? 

`# fio --filename=/tmp/aa --size=1M --rw=write --ioengine=libaio --direct=1 --verify=crc32 --verify_dump=1 --name=test --bs=4k --loops=1` 
....Output truncated ....
`# fio --filename=/tmp/aa --size=1M --rw=write --ioengine=libaio --direct=1 --verify=crc32 --verify_dump=1 --verify_only --name=test --bs=4k --loops=1`
test: (g=0): rw=write, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio-2.2.8
Starting 1 process

test: (groupid=0, jobs=1): err= 0: pid=6101: Mon Jun  8 16:05:07 2015
  read : io=1024.0KB, bw=42667KB/s, iops=10666, runt=    24msec
    slat (usec): min=7, max=48, avg= 8.35, stdev= 3.11
    clat (usec): min=60, max=105, avg=66.55, stdev= 4.48
     lat (usec): min=69, max=118, avg=75.15, stdev= 5.51
    clat percentiles (usec):
     |  1.00th=[   61],  5.00th=[   61], 10.00th=[   64], 20.00th=[   64],
     | 30.00th=[   64], 40.00th=[   65], 50.00th=[   66], 60.00th=[   68],
     | 70.00th=[   68], 80.00th=[   68], 90.00th=[   69], 95.00th=[   70],
     | 99.00th=[   88], 99.50th=[   92], 99.90th=[  105], 99.95th=[  105],
     | 99.99th=[  105]
  write: io=1024.0KB, bw=204800KB/s, iops=51200, runt=     5msec
    clat (msec): min=135, max=139, avg=137.63, stdev= 1.14
     lat (usec): min=0, max=6, avg= 0.22, stdev= 0.61
    clat percentiles (msec):
     |  1.00th=[  137],  5.00th=[  137], 10.00th=[  137], 20.00th=[  137],
     | 30.00th=[  137], 40.00th=[  139], 50.00th=[  139], 60.00th=[  139],
     | 70.00th=[  139], 80.00th=[  139], 90.00th=[  139], 95.00th=[  141],
     | 99.00th=[  141], 99.50th=[  141], 99.90th=[  141], 99.95th=[  141],
     | 99.99th=[  141]
    lat (usec) : 100=49.80%, 250=0.20%
    lat (msec) : 250=50.00%
  cpu          : usr=29.63%, sys=7.41%, ctx=263, majf=0, minf=44
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=256/w=256/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0

Run status group 0 (all jobs):
   **READ: io=1024KB, aggrb=42666KB/s, minb=42666KB/s, maxb=42666KB/s, mint=24msec, maxt=24msec
  WRITE: io=1024KB, aggrb=204800KB/s, minb=204800KB/s, maxb=204800KB/s, mint=5msec, maxt=5msec**

Disk stats (read/write):
    dm-1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%, aggrios=256/6, aggrmerge=0/0, aggrticks=14/36, aggrin_queue=50, aggrutil=27.78%
  sda: ios=256/6, merge=0/0, ticks=14/36, in_queue=50, util=27.78%

**Comment by axboe** [comment]
It should not actually be writing, but they are still accounted. I can double check that, but I believe it's just accounting. Try and do a larger size, then it should be more apparent.

**Comment by sellerb5** [comment]
That's correct, It seem to be the  accounting thing. Confirmed the same by running iostat parallely. Thanks a lot for your help.

Now using `verify=[option]` is a problem to my use case. My goal was to write all zeros and read them back. I am able to do all zero writes using `--zero_buffers` option. However if I use `verify=crc32|md5|meta` it doesn't generate zero buffers any more. Is there any work around it?

**Comment by sellerb5** [comment]
Closing this. Thanks for your help. 
Will open a seperate thread for issue seeing with simultaneous usage of  zero_buffers & verify options.

**Comment by axboe** [comment]
I fixed the accounting issue:

http://git.kernel.dk/?p=fio.git;a=commit;h=d5c8ea29023fccd33d577e3ca68f0254c1d87d6b
