### ISSUE TITLE
Error in `fio': free(): invalid pointer

### ISSUE THREAD

**Issue by jabingu** [axboe/fio#854]
I use this code:

> fio --direct=1 --thread=1 --ioengine=libaio --name=test --scramble_buffers=1 --userspace_reap --numjobs=4 --iodepth=256 --group_reporting --norandommap --random_distribution=zoned:90/5:5/20:3/35:2/40 --randrepeat=0 --filename=/dev/nvme0n1  --runtime=600 --time_based  --blocksize=4k --rw=randwrite   --write_iolog=iolog_distribution_zoned_600_2

get a error 

> fio-3.8
> Starting 4 threads
> *** Error in `fio': free(): invalid pointer: 0x0000000001e043a0 ***][eta 00m:00s]
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f712abe77e5]
> /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f712abf037a]
> /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f712abf453c]
> fio[0x46af23]
> /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f712b1456ba]
> /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f712ac7741d]
> ======= Memory map: ========
> 00400000-004af000 r-xp 00000000 08:01 4064097                            /usr/local/bin/fio
> 006af000-006b0000 r--p 000af000 08:01 4064097                            /usr/local/bin/fio
> 006b0000-00758000 rw-p 000b0000 08:01 4064097                            /usr/local/bin/fio
> 00758000-00790000 rw-p 00000000 00:00 0 
> 01e04000-01e39000 rw-p 00000000 00:00 0                                  [heap]
> 
> ...
> 
> 7ffd2dcee000-7ffd2dd0f000 rw-p 00000000 00:00 0                          [stack]
> 7ffd2dd7a000-7ffd2dd7c000 r--p 00000000 00:00 0                          [vvar]
> 7ffd2dd7c000-7ffd2dd7e000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
> Aborted (core dumped)

**Comment by sitsofe** [comment]
@jabingu Hi!

I ran the following with a recent fio for a few seconds and it was fine:

```
fio --direct=1 --thread=1 --ioengine=libaio --size=10M --name=test --scramble_buffers=1 --userspace_reap --numjobs=4 --iodepth=256 --group_reporting --norandommap --random_distribution=zoned:90/5:5/20:3/35:2/40 --randrepeat=0 --filename=fio.tmp --runtime=600 --time_based --blocksize=4k --rw=randwrite --write_iolog=iolog_distribution_zoned_600_2
```

Can you reproduce the issue with the newest fio (see https://github.com/axboe/fio/releases for which version we're up to)?

**Comment by jabingu** [comment]
> @jabingu Hi!
> 
> I ran the following with a recent fio for a few seconds and it was fine:
> 
> ```
> fio --direct=1 --thread=1 --ioengine=libaio --size=10M --name=test --scramble_buffers=1 --userspace_reap --numjobs=4 --iodepth=256 --group_reporting --norandommap --random_distribution=zoned:90/5:5/20:3/35:2/40 --randrepeat=0 --filename=fio.tmp --runtime=600 --time_based --blocksize=4k --rw=randwrite --write_iolog=iolog_distribution_zoned_600_2
> ```
> 
> Can you reproduce the issue with the newest fio (see https://github.com/axboe/fio/releases for which version we're up to)?

Thanks for your reply. i had upgrade fio to 3.16 and it worked successfully .
