### ISSUE TITLE
incorrect service time measurements for 'bursty' workloads 

### ISSUE THREAD

**Issue by kachini** [axboe/fio#855]
I'm running fio 'bursty' workload against cached disk array with 8 IOs batches like: 

[global]
ioengine=libaio
direct=1
size=100%
group_reporting=1
filename=${FILENAME}
runtime=1800
blocksize=8k
ramp_time=10

[ JOBNAME_5_RW8 ]
stonewall
numjobs=1
rw=randrw
rwmixread=80
iodepth = 8
iodepth_batch_submit = 0
iodepth_batch_complete_min = 8
iodepth_batch_complete_max = 8

fio reports service time for both reads and writes around 12 ms. This is not an expected behavior for cached disk array. I would expect to see writes much faster:

JOBNAME_5_RW8 : (groupid=0, jobs=1): err= 0: pid=158188: Thu Oct 31 15:59:11 2019
  read: IOPS=531, BW=4256KiB/s (4358kB/s)(848MiB/204124msec)
    slat (nsec): min=20957, max=57379, avg=32045.70, stdev=6398.38
    clat (usec): min=313, max=591339, **avg=12398.07,** stdev=20499.19
     lat (usec): min=337, max=591380, avg=12430.24, stdev=20499.17
  
   bw (  KiB/s): min=   64, max= 5712, per=99.96%, avg=4254.38, stdev=1305.84, samples=408
   iops        : min=    8, max=  714, avg=531.76, stdev=163.23, samples=408
  write: IOPS=132, BW=1060KiB/s (1085kB/s)(211MiB/204124msec)
    slat (nsec): min=21568, max=57506, avg=32445.00, stdev=6407.96
    clat (usec): min=314, max=591339, **avg=10372.41**, stdev=20247.17
     lat (usec): min=341, max=591372, avg=10404.98, stdev=20247.09

To trace individual IO requests I used 'block_rq_issue' and 'block_rq_complete' tracepoints. 
I clearly see that writes comes back shortly in less than 1 ms  (cache) and reads are returned from HDD in 5-12 ms.  There are no outlayers as well. 

So it seems that fio reports service times incorrectly as writes in fact completes in <1 ms, not in 12 ms. 

For example,  below is single 'batch' of IOs including 7 reads and 1 write. It can be seen that write IO completed in 0.3 ms i.e much faster than reads.  
......
0.339615 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x39990a40 len=8192 async=0 sync=0
0.339617 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0xc2980030 len=8192 async=0 sync=1
0.339617 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x1350b39c0 len=8192 async=0 sync=2
0.339618 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x20965c9a0 len=8192 async=0 sync=3
0.339619 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x245613e10 len=8192 async=0 sync=4
0.339619 cpu=206 **block_rq_issue** dev_t=0x0fd00000 **wr=write sector=0x36d8c4ff0 len=8192** async=0 sync=5
0.339620 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x39ccc2230 len=8192 async=0 sync=6
0.339621 cpu=206 block_rq_issue dev_t=0x0fd00000 wr=read sector=0x40ba3a4f0 len=8192 async=0 sync=7
0.339936 cpu=206 **block_rq_complete** dev_t=0x0fd00000 **wr=write** sector=0x36d8c4ff0 len=8192 len=8192 **svtm= 0.000317**    
0.343157 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0xc2980030 len=8192 len=8192 svtm= 0.003540
0.345123 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x40ba3a4f0 len=8192 len=8192 svtm= 0.005502
0.346807 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x20965c9a0 len=8192 len=8192 svtm= 0.007189
0.346837 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x1350b39c0 len=8192 len=8192 svtm= 0.007220
0.346841 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x39ccc2230 len=8192 len=8192 svtm= 0.007222
0.347926 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x39990a40 len=8192 len=8192 svtm= 0.008311
0.348201 cpu=206 block_rq_complete dev_t=0x0fd00000 wr=read sector=0x245613e10 len=8192 len=8192 svtm= 0.008582
............

So this looks like a fio issue with calculation of service time for 'bursty' workloads.  Is there any workaround? 

thanks, 

regards, 
Sergey

**Comment by sitsofe** [comment]
@kachini which version of fio? Can you make this happen at even lower queue depths? Can you make it happen on a read (or write) only workload? Are you running this with just a single job (if not how do you know the fio process that is seeing a longer time isn't being forced to wait to get on the CPU)?

**Comment by kachini** [comment]
> @kachini which version of fio? Can you make this happen at even lower queue depths? Can you make it happen on a read (or write) only workload? Are you running this with just a single job (if not how do you know the fio process that is seeing a longer time isn't being forced to wait to get on the CPU)?

1) fio-3.16 
2)yes,  i do see the same phenomena with queue = 4. 
3) "Can you make it happen on a read (or write) only workload? " sorry, but I didn't get the question. The nature of the problem is that it happens when a batch of IOs contains mix of reads and writes.  
3) just single job.  

I think the problem may happen because we are blocked in io_submit() until entire batch is written to disk.

**Comment by axboe** [comment]
This is a user problem, imho. You ask fio to batch completions, and that batch may have both reads and writes. If your reads are slower, then yes, fio won't know about the write completions before that batch has been retrieved from the kernel. That's where the timing is done, when fio sees the batch of completions you asked for. That will naturally skew the write completion times, if there's a disparity between the read and write completion latencies.

Fio can't track completions before it sees them, it doesn't have a crystal ball.

**Comment by kachini** [comment]
> 
> Fio can't track completions before it sees them, it doesn't have a crystal ball.
Ah, thanks. Will try to setup the workload in different way to organize batches differently.
