### ISSUE TITLE
HELP! It throw errors when run fio，it is what that cause these errors？

### ISSUE THREAD

**Issue by zb861359** [axboe/fio#861]
the errors is shown below：
![图片](https://user-images.githubusercontent.com/10735020/68556224-42af8680-046c-11ea-8167-504053d7c030.png)

**Comment by sitsofe** [comment]
@zb861359,

Um that might mean the kernel can't read from that disk (I'd check dmesg and see if there are errors being reported there). Unfortunately it's impossible to say more until you include at the least all the information in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ...

**Comment by zb861359** [comment]
@sitsofe ，
Thanks for your answer。
The environment has been destroyed，when it occurs next，I will collect dmesg。
What will cause“Input/output error”? （The second error “No data available” can be processed sometime in the further。）

**Comment by sitsofe** [comment]
(@zb861359 When you reply next don't forget to also include the information requested in REPORTING-BUGS - thanks!)

**Comment by sitsofe** [comment]
@zb861359:

> What will cause“Input/output error”? 

If the kernel is returning errors to fio (e.g. because it is having trouble communicating with the disk) then that can generate such a message.

**Comment by axboe** [comment]
Not a fio issue, closing.

**Comment by zb861359** [comment]
@axboe ,Hi!
we know the fio itsself has no problem, because we have many environments running fio test. there is only one environment come across this situation, and  the probability is very small. 
But what is the reason causing fio to throw out these errors?

**Comment by axboe** [comment]
Faulty hardware? You get an IO error, and then no data returned. That's all fio sees, and it reports it, there's not much else I can say.

**Comment by zb861359** [comment]
Thanks for your reply.
We discuss this only when it occurs next.
