### ISSUE TITLE
Observing I/O error while running nvme FIO test inside VM

### ISSUE THREAD

**Issue by Anilreddylinuxml** [axboe/fio#862]
Guest VM booted with vfio interface for NVME card and running fio test for nvme drive. observing below IO errors in guest dmesg. 
where as same fio command on host working fine for same nvme drive.

fio  --rw=rw --rwmixread=0 --bs=4k --ioengine=libaio --direct=0 --iodepth=8 --group_reporting  --name=Sequential-Write_4k  --numjobs=3 --runtime=60 --filename=/dev/nvme0n1

Sequential-Write_4k: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=8
...
fio-3.12
Starting 3 processes
[ 1993.291923] print_req_error: I/O error, dev nvme0n1, sector 12534528 flags 104001
[ 1993.293424] Buffer I/O error on dev nvme0n1, logical block 1566816, lost async page write
[ 1993.294988] Buffer I/O error on dev nvme0n1, logical block 1566817, lost async page write
[ 1993.296570] Buffer I/O error on dev nvme0n1, logical block 1566818, lost async page write
[ 1993.298146] Buffer I/O error on dev nvme0n1, logical block 1566819, lost async page write
[ 1993.299734] Buffer I/O error on dev nvme0n1, logical block 1566820, lost async page write
[ 1993.301282] Buffer I/O error on dev nvme0n1, logical block 1566821, lost async page write
[ 1993.302879] Buffer I/O error on dev nvme0n1, logical block 1566822, lost async page write
[ 1993.304471] Buffer I/O error on dev nvme0n1, logical block 1566823, lost async page write
[ 1993.306225] Buffer I/O error on dev nvme0n1, logical block 1566824, lost async page write
[ 1993.307960] Buffer I/O error on dev nvme0n1, logical block 1566825, lost async page write
[ 1993.310456] print_req_error: I/O error, dev nvme0n1, sector 12535040 flags 104001
[ 1993.313705] print_req_error: I/O error, dev nvme0n1, sector 12535552 flags 104001
[ 1993.315705] print_req_error: I/O error, dev nvme0n1, sector 12536064 flags 104001
[ 1993.386694] print_req_error: I/O error, dev nvme0n1, sector 12536320 flags 104001
[ 1993.388283] print_req_error: I/O error, dev nvme0n1, sector 12535808 flags 104001
[ 1993.389828] print_req_error: I/O error, dev nvme0n1, sector 12535296 flags 104001
[ 1993.391438] print_req_error: I/O error, dev nvme0n1, sector 12534784 flags 104001
[ 1993.393043] print_req_error: I/O error, dev nvme0n1, sector 12534272 flags 104001
[ 2028.861245] print_req_error: I/O error, dev nvme0n1, sector 30685440 flags 104001
[ 2028.862849] Buffer I/O error on dev nvme0n1, logical block 3835680, lost async page write
[ 2028.864316] Buffer I/O error on dev nvme0n1, logical block 3835681, lost async page write
[ 2028.865788] Buffer I/O error on dev nvme0n1, logical block 3835682, lost async page write
[ 2028.867255] Buffer I/O error on dev nvme0n1, logical block 3835683, lost async page write
[ 2028.868717] Buffer I/O error on dev nvme0n1, logical block 3835684, lost async page write
[ 2028.870183] Buffer I/O error on dev nvme0n1, logical block 3835685, lost async page write
[ 2028.871655] Buffer I/O error on dev nvme0n1, logical block 3835686, lost async page write
[ 2028.873125] Buffer I/O error on dev nvme0n1, logical block 3835687, lost async page write
[ 2028.874586] Buffer I/O error on dev nvme0n1, logical block 3835688, lost async page write
[ 2028.876046] Buffer I/O error on dev nvme0n1, logical block 3835689, lost async page write
[ 2028.877912] print_req_error: I/O error, dev nvme0n1, sector 30685952 flags 104001
[ 2028.879354] print_req_error: I/O error, dev nvme0n1, sector 30686464 flags 104001
[ 2028.880811] print_req_error: I/O error, dev nvme0n1, sector 30686976 flags 104001
[ 2028.882232] print_req_error: I/O error, dev nvme0n1, sector 30687488 flags 104001
[ 2028.892553] print_req_error: I/O error, dev nvme0n1, sector 30686720 flags 104001
[ 2028.893933] print_req_error: I/O error, dev nvme0n1, sector 30687232 flags 104001
[ 2028.895303] print_req_error: I/O error, dev nvme0n1, sector 30686208 flags 104001
[ 2028.896647] print_req_error: I/O error, dev nvme0n1, sector 30685696 flags 104001
Jobs: 1 (f=1): [f(1),_(2)][100.0%][eta 00m:00s]
Sequential-Write_4k: (groupid=0, jobs=3): err= 0: pid=1694: Sun Nov 10 22:53:33 2019
  write: IOPS=213k, BW=833MiB/s (873MB/s)(48.8GiB/60002msec); 0 zone resets
    slat (usec): min=2, max=228832, avg=11.63, stdev=281.22
    clat (usec): min=2, max=229108, avg=99.55, stdev=757.13
     lat (usec): min=7, max=229165, avg=111.48, stdev=808.27
    clat percentiles (usec):
     |  1.00th=[   48],  5.00th=[   53], 10.00th=[   57], 20.00th=[   61],
     | 30.00th=[   66], 40.00th=[   69], 50.00th=[   75], 60.00th=[   83],
     | 70.00th=[  108], 80.00th=[  147], 90.00th=[  165], 95.00th=[  176],
     | 99.00th=[  235], 99.50th=[  273], 99.90th=[  404], 99.95th=[  469],
     | 99.99th=[  644]
   bw (  KiB/s): min=117704, max=428992, per=33.29%, avg=283920.10, stdev=61927.27, samples=360
   iops        : min=29426, max=107248, avg=70980.00, stdev=15481.84, samples=360
  lat (usec)   : 4=0.01%, 10=0.01%, 20=0.01%, 50=2.40%, 100=65.59%
  lat (usec)   : 250=31.27%, 500=0.70%, 750=0.03%, 1000=0.01%
  lat (msec)   : 2=0.01%, 4=0.01%, 10=0.01%, 20=0.01%, 100=0.01%
  lat (msec)   : 250=0.01%
  cpu          : usr=19.08%, sys=61.77%, ctx=1643424, majf=0, minf=46
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=100.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.1%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,12794441,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=8

Run status group 0 (all jobs):
  WRITE: bw=833MiB/s (873MB/s), 833MiB/s-833MiB/s (873MB/s-873MB/s), io=48.8GiB (52.4GB), run=60002-60002msec

Disk stats (read/write):
  nvme0n1: ios=55/127584, merge=0/3955104, ticks=8/4184907, in_queue=3930212, util=41.25%

**Comment by sitsofe** [comment]
@Anilreddylinuxml I'm afraid issues like this that are reported by the kernel are outside the remit of the fio bug tracker - this can't possibly be due to a bug in fio and seems likely to be some issue in the guest kernel. I'd recommend contacting your distro's kernel people and seeing if they know why that's occurring...

**Comment by Anilreddylinuxml** [comment]
however --direct=1 works fine in guest VM without any I/O error, is it known issue ?

**Comment by sitsofe** [comment]
@Anilreddylinuxml That could be because going through the buffer cache is generating different looking I/O to the device compared when things happen O_DIRECTly (e.g. cached I/O might be bigger, chunkier and potentially more relentless once it get started I/O). I'm afraid you would likely have to ask someone who maintains those drivers if there's a known issue. A quick Google (https://www.google.com/search?q=Buffer+I%2FO+error+on+dev+nvme0n1 ) shows there was a fixed issue with Xen and ballooning in that area in 2017 (see https://bugzilla.redhat.com/show_bug.cgi?id=1463000#c4 ).
