### ISSUE TITLE
Add FIO worker Thread/Process ID as argument to exec_prerun/postrun command?

### ISSUE THREAD

**Issue by hannesweisbach** [axboe/fio#863]
Hi,

I have a bit of unconventional setup here, where I _think_ I need to pass the TID/PID of the invoking FIO worker thread/process to the exec_prerun/postrun command. This issue has a dual purpose:

1.  I may have missed something and there is a way to accomplish my goal without changing FIO. If so I would appreciate if you could hint at a potential solution.
2.  If I really need this change to get the behaviour I want, I might as well do it in a way so you could merge my change – if you think such a feature benefit the FIO codebase.

First let me explain my goal & setup. Basically I'm using FIO as a load generator and I use LTTng with in-kernel block layer & I/O-scheduler trace points to get more fine-grained latency data. Put simply, my goal is to break down total request latency into time spent in block layer, request merging, time in the I/O scheduler queue, and the time required by the device to actually serve the request.

I'm only interested in latency data of specific worker threads (i.e. specific workloads), not all worker threads at once. To limit the amount of data generated by LTTng I would like to filter trace events by PID. I thought, exec_prerun/postrun would be nice to start and stop tracing. My idea was to add a exec_prerun/postrun command to the FIO job of interest.

Unfortunately, I have no idea how to get the worker PID inside the prerun/postrun command. Since the prerun/postrun commands are started with system(), the parent PID is also not the PID of the FIO worker :(

Since the worker thread executes the prerun/postrun command, it could just pass its own PID to the command. I think it would be best to not do it by default, but only when enabled via a command line switch or job file option?

What are your thoughts on this?

**Comment by sitsofe** [comment]
@hannesweisbach Interesting! Couldn't you get the parent-parent pid?
```
#!/bin/sh

echo "Parent PID: ${PPID}"
PPPID=$(ps -o ppid= -p $PPID)
echo "Parent-Parent PID: ${PPPID}"
ps -p ${PPPID}
```

**Comment by hannesweisbach** [comment]
@sitsofe I tried that! I forgot to mention it. The reason this doesn't work is that system() calls /bin/sh to execute the command, which itself is a shell script, so I would need to get the parent-parent-parent PID. I verified that by looking at the process tree :)

The way I understand what is happening is as follows: system() invokes one instance of /bin/sh which calls the command with -c and in case the command is a script file, it launches a second /bin/sh (in case of your example, my scripts start with `#!/usr/bin/env bash`, which shouldn't make a difference here).

**Comment by sitsofe** [comment]
@hannesweisbach That's odd. I tried the above script and got back a an fio pid. Do you get something similar?

**Comment by hannesweisbach** [comment]
First of all, I have to apologize, I was confused. Of course your PPID-solution works (for processes). I believe I was remembering things incorrectly. I think my original issue was, that the non-bash-compatible redirection in exec_prerun/post_run caused the script to be run in the background (because of the ampersand), then the parent shell exited and the script was re-parented to init. At least I think that is what happened, I'm just remembering the script first being a child of fio and then of init. This no longer happens.

I tried your solution and it gets me the parent pid (realtime0 is the name of the job):
```
cat realtime0.prerun.txt
Parent-Parent PID:  5589
  PID TTY          TIME CMD
 5589 pts/5    00:00:00 fio
```
Now the FIO output:
```
realtime0: (groupid=0, jobs=1): err= 0: pid=5595: Tue Nov 12 09:15:54 2019
  read: IOPS=472, BW=1891KiB/s (1937kB/s)(18.5MiB/10001msec)
   bw (  KiB/s): min= 1864, max= 1896, per=100.00%, avg=1891.58, stdev= 8.10, samples=19
   iops        : min=  466, max=  474, avg=472.89, stdev= 2.02, samples=19
  cpu          : usr=0.12%, sys=0.95%, ctx=9465, majf=4, minf=4
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=4729,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1
```

Just for kicks and giggles, here's the process tree with threads as shown with top (I added a sleep to the prerun shell script to be able to capture it):

```
 5236 root      20   0  110080      0      0 S  0,0  0,0   0:00.01      `- sshd
 5300 rtss19-+  20   0  110080    516    468 S  0,0  0,0   0:00.18          `- sshd
 5301 rtss19-+  20   0   29900      4      4 S  0,0  0,0   0:00.04              `- bash
 5589 rtss19-+  20   0  730600  90788  89996 S  0,0  0,6   0:00.37                  `- fio
 5594 rtss19-+  20   0  730600  90788  89996 S  0,0  0,6   0:00.00                      `- fio
 5595 rtss19-+  20   0  730600  90788  89996 S  0,0  0,6   0:00.00                      `- fio
 5596 rtss19-+  20   0    4628    792    728 S  0,0  0,0   0:00.00                      `- sh
 5597 rtss19-+  20   0   19992   3308   3052 S  0,0  0,0   0:00.00                          `- bash
 5601 rtss19-+  20   0   14576    800    736 S  0,0  0,0   0:00.00                              `- sleep
```

So the worker thread **TID** is 5595, as reported by FIO and top, but the parent-parent **PID** (of the shell script) is 5589, the FIO main thread (I believe thread group leader, in Linux-speak?).

That is when I use threads, i.e. `thread=1` in the job file. If I use processes, i.e. `thread=0`, your solution works as desired. So I guess that was the difference :) I'll leave the explanation above as documentation, if someone happens to run into the same issue.

I think in light of that I'll switch to using processes as workers, instead of threads. I can't really remember why I used threads in the first place … ;)

Thanks for your help! 👍
