### ISSUE TITLE
fio doesn't create subdirectories as set at filename_format option 

### ISSUE THREAD

**Issue by StingerXIII** [axboe/fio#864]
I trying to launch a workload which writes files at the separate directories per each thread.
Here is my jobfile:

```
[global]
ioengine=psync
direct=1
rw=write
file_service_type=sequential:1
filename_format=$jobnum/$filenum
openfiles=1
create_on_open=1
end_fsync=1

[fstest]
numjobs=2
directory=/mnt/xfs/0
filesize=1M
nrfiles=10
```

The [manual](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-filename-format) says

> If you specify a path then the directories will be created up to the main directory for the file. So for example if you specify filename_format=a/b/c/$jobnum then the directories a/b/c will be created before the file setup part of the job. 

The error I get:
```
[root@hostname ~]# fio fio.ini 
fstest: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
...
fio-3.16
Starting 2 processes
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
disk util stat: No such file or directory
fio: pid=18011, err=2/file:filesetup.c:701, func=open(/mnt/xfs/0/0/0), error=No such file or directory
fio: pid=18012, err=2/file:filesetup.c:701, func=open(/mnt/xfs/0/1/0), error=No such file or directory


Run status group 0 (all jobs):
```

The directory /mnt/xfs/0 exists before I start a job.

**Comment by sitsofe** [comment]
Hi @StingerXIII,

If you cd to `/mnt/xfs/0` and then remove `directory=/mnt/xfs/0` does it still fail?

**Comment by sitsofe** [comment]
Hmm even
```
fio --filename_format=./1/1 --name=test --size=16k
```

seems to fail...

**Comment by StingerXIII** [comment]
@sitsofe it works when I remove `directory` option and start fio from `cd /mnt/xfs/0.`

Also I tried to remove `directory` option and provide absolute path - this fails.

manual says:
> If you specify directory then the path will be relative that directory, otherwise it is treated as the absolute path.

**Comment by sitsofe** [comment]
@StingerXIII can you see if the latest fio fixes your issue?

**Comment by StingerXIII** [comment]
@sitsofe yes, now my config works as expected.

**Comment by sitsofe** [comment]
@StingerXIII excellent! Thanks for following up - I'll close this issue.
