### ISSUE TITLE
fio get 'fio_file_lfsr(f)' failed Assertion with zoned random distribution and lfsr random generator

### ISSUE THREAD

**Issue by mangmang-zz** [axboe/fio#873]
Hello， axboe。
I got the error in the following picture with cmd parm "random_distribution=zoned:50/5:30/15:20/80" and "random_generator=lfsr". Is there any restriction between the two cmd options?
![image](https://user-images.githubusercontent.com/35731109/70305374-33d7ac00-183f-11ea-86e4-20b22ce06aae.png)

**Comment by axboe** [comment]
Please include the full job file, thanks.

**Comment by axboe** [comment]
Nevermind, I see what it is. Fixed pushed, thanks for reporting!
