### ISSUE TITLE
rbd engine "assert" within uncertain times.

### ISSUE THREAD

**Issue by shangdehao1** [axboe/fio#876]
hi, 
when i test my feature of RBD, i  faced one assert issue. 
when IOPS is very lower, it is very hard to recreate this bug, for example 10k below. When IOPS is about ~50k, i can reproduce this issue. Additional, it always occur within uncertain times. 

If i disable CONFIG_RBD_POLL, all things go well.

Currently, i don't make sure whether my feature introduce this issue. If convenient, could you please help me take a look. many thanks. 

- GDB log is as following : 
#0  0x00007ffff5120337 in raise () from /lib64/libc.so.6
#1  0x00007ffff5121a28 in abort () from /lib64/libc.so.6
#2  0x00007ffff5119156 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff5119202 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000047d8f5 in rbd_iter_events (wait=1, min_evts=1, events=<synthetic pointer>, td=0x7fffc5995000) at engines/rbd.c:390
#5  fio_rbd_getevents (td=0x7fffc5995000, min=1, max=<optimized out>, t=<optimized out>) at engines/rbd.c:451
#6  0x000000000041df85 in td_io_getevents (td=td@entry=0x7fffc5995000, min=<optimized out>, max=<optimized out>, t=<optimized out>) at ioengines.c:264
#7  0x0000000000447de1 in io_u_queued_complete (td=td@entry=0x7fffc5995000, min_evts=<optimized out>, min_evts@entry=1) at io_u.c:2058
#8  0x000000000040e3f0 in wait_for_completions (td=td@entry=0x7fffc5995000, time=time@entry=0x7fffbd980d60) at backend.c:445
#9  0x000000000046a729 in do_io (bytes_done=0x7fffbd980de0, td=0x7fffc5995000) at backend.c:1080
#10 thread_main (data=<optimized out>) at backend.c:1788
#11 0x00007ffff56c3e65 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff51e888d in clone () from /lib64/libc.so.6
 
- fio config file 
[global]
    direct=1
    time_based
    stonewall
[fiorbd-randwrite-64k-qd64-1g-200-3600-fiorbd]
    rw=randread
    bs=4k
    iodepth=256
    ramp_time=0
    runtime=600000
    ioengine=rbd
    clientname=admin
    pool=test_pool
    rbdname=test_rbd_child
    iodepth_batch_submit=1
    iodepth_batch_complete=1
    norandommap
    randrepeat=0
    #random_distribution=zipf:1.2

**Comment by sitsofe** [comment]
@shangdehao1 Hi

Can you include the details requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ?

**Comment by sitsofe** [comment]
Closing because we need more information from the reporter to take this further.

@shangdehao1  - please re-open this issue if you're able to supply the requested information. Thank you!
