### ISSUE TITLE
err=5/file:filesetup.c:239, func=fsync, error=Input/output error

### ISSUE THREAD

**Issue by zyuhu** [axboe/fio#877]
Hello, 
recently I'm using fio-2.99 to do a random read testing, it reported  "Input/output error" now and then during "fsync" the data to background disks. Any clue about this?
The below is error information:
########### Start of output
RandomReads-63488-4k-4: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=sync, iodepth=1
...
fio-2.99
Starting 4 threads
RandomReads-63488-4k-4: Laying out IO file (1 file / 15872MiB)
RandomReads-63488-4k-4: Laying out IO file (1 file / 15872MiB)
fio: pid=0, err=5/file:filesetup.c:239, func=fsync, error=Input/output error
RandomReads-63488-4k-4: Laying out IO file (1 file / 15872MiB)
RandomReads-63488-4k-4: Laying out IO file (1 file / 15872MiB)
fio: pid=0, err=5/file:filesetup.c:239, func=fsync, error=Input/output error

RandomReads-63488-4k-4: (groupid=0, jobs=4): err= 5 (file:filesetup.c:239, func=fsync, error=Input/output error): pid=4272: Sat Dec  7 10:28:32 2019

......
Sat Dec  7 10:28:32 CST 2019: io_block_generic_fio_random_fsync TEST INTERNAL ERROR (DEPRECATED RETURN VALUE - PLEASE REPORT): on 1/1 after 7m53s
########### Fio command line workloads
./fio --direct=0 --ioengine=sync --thread --directory=/abuild --invalidate=1 --group_reporting=1 --runtime=100 --fallocate=posix --ramp_time=10 --name=RandomReads-63488-4k-4 --new_group --rw=randread --size=15872m --numjobs=4 --bs=4k --filename_format=FioWorkloads.\$jobnum

This workloads is trying to test OS random read performance with IO size equal double memory 
########### End of Fio command line workloads

Any help is much appreciated.

**Comment by sitsofe** [comment]
@zyuhu Are there any errors reported in `dmesg`?

**Comment by zyuhu** [comment]
> @zyuhu Are there any errors reported in `dmesg`?
oops, found an call trace in the kernel 5.3 log:
Dec 07 12:14:02 localhost kernel: Call Trace:
Dec 07 12:14:02 localhost kernel:  sd_init_command+0x192/0xae0 [sd_mod]
Dec 07 12:14:02 localhost kernel:  scsi_queue_rq+0x512/0xa80 [scsi_mod]
Dec 07 12:14:02 localhost kernel:  blk_mq_dispatch_rq_list+0x90/0x540
Dec 07 12:14:02 localhost kernel:  ? elv_rb_del+0x1f/0x30
Dec 07 12:14:02 localhost kernel:  ? deadline_remove_request+0x49/0xb0
Dec 07 12:14:02 localhost kernel:  blk_mq_do_dispatch_sched+0x5f/0xf0
Dec 07 12:14:02 localhost kernel:  blk_mq_sched_dispatch_requests+0xf9/0x170
Dec 07 12:14:02 localhost kernel:  __blk_mq_run_hw_queue+0x51/0x100
Dec 07 12:14:02 localhost kernel:  __blk_mq_delay_run_hw_queue+0xfc/0x150
Dec 07 12:14:02 localhost kernel:  blk_mq_run_hw_queue+0x50/0x100
Dec 07 12:14:02 localhost kernel:  blk_mq_sched_insert_requests+0x71/0xf0
Dec 07 12:14:02 localhost kernel:  blk_mq_flush_plug_list+0x200/0x2b0
Dec 07 12:14:02 localhost kernel:  blk_flush_plug_list+0xc4/0xf0
Dec 07 12:14:02 localhost kernel:  blk_mq_make_request+0x317/0x5b0
Dec 07 12:14:02 localhost kernel:  generic_make_request+0x121/0x300
Dec 07 12:14:02 localhost kernel:  ? submit_bio+0x42/0x1c0
Dec 07 12:14:02 localhost kernel:  submit_bio+0x42/0x1c0
Dec 07 12:14:02 localhost kernel:  xfs_submit_ioend.isra.28+0x85/0x160 [xfs]
Dec 07 12:14:02 localhost kernel:  xfs_vm_writepages+0x75/0xa0 [xfs]
Dec 07 12:14:02 localhost kernel:  do_writepages+0x4b/0xe0
Dec 07 12:14:02 localhost kernel:  ? __writeback_single_inode+0x3d/0x330
Dec 07 12:14:02 localhost kernel:  __writeback_single_inode+0x3d/0x330
Dec 07 12:14:02 localhost kernel:  writeback_sb_inodes+0x1b5/0x490
Dec 07 12:14:02 localhost kernel:  __writeback_inodes_wb+0x5d/0xb0
Dec 07 12:14:02 localhost kernel:  wb_writeback+0x265/0x2f0
Dec 07 12:14:02 localhost kernel:  ? wb_workfn+0x1b5/0x400
Dec 07 12:14:02 localhost kernel:  wb_workfn+0x1b5/0x400
Dec 07 12:14:02 localhost kernel:  process_one_work+0x1f9/0x3f0
Dec 07 12:14:02 localhost kernel:  worker_thread+0x2d/0x3f0
Dec 07 12:14:02 localhost kernel:  ? process_one_work+0x3f0/0x3f0
Dec 07 12:14:02 localhost kernel:  kthread+0x10d/0x130
Dec 07 12:14:02 localhost kernel:  ? kthread_park+0xa0/0xa0
Dec 07 12:14:02 localhost kernel:  ret_from_fork+0x24/0x50
Dec 07 12:14:02 localhost kernel: ---[ end trace 2aff47c2a26de528 ]---
Dec 07 12:14:02 localhost kernel: blk_update_request: I/O error, dev sdb, sector 108264072 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
Dec 07 12:14:03 localhost kernel: XFS (sdb1): writeback error on sector 108264072
Dec 07 12:16:35 localhost kernel: blk_update_request: I/O error, dev sdb, sector 241782472 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
Dec 07 12:16:36 localhost kernel: XFS (sdb1): writeback error on sector 241782472
Dec 07 12:16:36 localhost kernel: blk_update_request: I/O error, dev sdb, sector 250171080 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
Dec 07 12:16:36 localhost kernel: XFS (sdb1): writeback error on sector 250171080

that call trace was followed in bugzilla, thanks.

**Comment by sitsofe** [comment]
@zyuhu Yeah, I thought that might have been the case :-) Given that the problem seems to be lower down in your stack I'll close this issue.

**Comment by zyuhu** [comment]
@sitsofe thanks.
