### ISSUE TITLE
fio state file not human readable？

### ISSUE THREAD

**Issue by axiqia** [axboe/fio#888]
Hi, 
I want to verify the write operation during my VM backend (eg. SPDK) restart.  so I reference fio doc for help but meet a  problem.

My job file is from [doc](https://fio.readthedocs.io/en/latest/fio_doc.html#basic-verification)：

```
# The most basic form of data verification. Write the device randomly
# in 4K chunks, then read it back and verify the contents.
[write-and-verify]
rw=randwrite
bs=4k
direct=1
ioengine=libaio
iodepth=16
verify=crc32c
runtime=30
# Use /dev/XXX. For running this on a file instead, remove the filename
# option and add a size=32G (or whatever file size you want) instead.
filename=/dev/vda
```

And the output is：
```
 ./fio-master/fio verify.fio
write-and-verify: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
fio-3.17
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=519MiB/s][w=133k IOPS][eta 00m:00s]
write-and-verify: (groupid=0, jobs=1): err= 0: pid=23335: Mon Dec 23 17:03:12 2019
  write: IOPS=132k, BW=514MiB/s (539MB/s)(15.1GiB/30001msec)
    slat (usec): min=3, max=174, avg= 5.09, stdev= 1.84
    clat (usec): min=16, max=734, avg=114.68, stdev= 6.56
     lat (usec): min=23, max=738, avg=120.12, stdev= 6.72
    clat percentiles (usec):
     |  1.00th=[  108],  5.00th=[  110], 10.00th=[  110], 20.00th=[  111],
     | 30.00th=[  112], 40.00th=[  113], 50.00th=[  114], 60.00th=[  115],
     | 70.00th=[  116], 80.00th=[  119], 90.00th=[  124], 95.00th=[  127],
     | 99.00th=[  135], 99.50th=[  139], 99.90th=[  153], 99.95th=[  194],
     | 99.99th=[  253]
   bw (  KiB/s): min=521952, max=533104, per=99.98%, avg=526674.47, stdev=3861.00, samples=59
   iops        : min=130488, max=133276, avg=131668.61, stdev=965.24, samples=59
  lat (usec)   : 20=0.01%, 50=0.01%, 100=0.01%, 250=99.99%, 500=0.01%
  lat (usec)   : 750=0.01%
  cpu          : usr=56.68%, sys=42.84%, ctx=18348, majf=0, minf=92633
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,3950822,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=514MiB/s (539MB/s), 514MiB/s-514MiB/s (539MB/s-539MB/s), io=15.1GiB (16.2GB), run=30001-30001msec

Disk stats (read/write):
  vda: ios=59/3937077, merge=0/0, ticks=3/62766, in_queue=62365, util=99.13%

```

and generated a state file：
![image](https://user-images.githubusercontent.com/22564578/71348158-dfeef600-25a6-11ea-9dc2-d2de41bd0b58.png)

Is it normal or not？

How can I see the verify's validation?

Thank you in advance.

**Comment by sitsofe** [comment]
@axiqia 

> Is it normal or not？

This is normal - it's a binary file.

> How can I see the verify's validation?

I don't understand the question I'm afraid. If validation failed `fio` would fail with an error code and exit. Are you asking something more?

**Comment by axiqia** [comment]
> @axiqia
> 
> > Is it normal or not？
> 
> This is normal - it's a binary file.
> 
> > How can I see the verify's validation?
> 


Thank you for your quick reply. 
I'm Sorry for not describing the problem clearly. Maybe I misunderstood the role of the state file.

I want to verify if there is any write operation lost or error with fio in a test job. ( I will restart SPDK several times during this job) .  

> I don't understand the question I'm afraid. If validation failed `fio` would fail with an error code and exit. Are you asking something more?

So I just need to check the whether fio exit with error code or not ?

**Comment by sitsofe** [comment]
@axiqia I don't normally reply this quickly :-)

> I'm Sorry for not describing the problem clearly. Maybe I misunderstood the role of the state file.

Not to worry! That's on me too to ask for clarification when I don't understand. The state file is more for recording where fio got to when you are doing things in two entirely separate fio invocations (e.g. you run one fio invocation to do writes, then you reboot the machine and want to know how far the original fio got when you try to do verifying reads). See https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-verify-state-save for more details.

> So I just need to check the whether fio exit with error code or not ?

Yes. Fio will print a message like:
```
fio: pid=16526, err=92/file:io_u.c:2031, func=io_u_sync_complete, error=Illegal byte sequence
```
along with the usual output and exit with a non-zero return code. See https://github.com/axboe/fio/issues/872#issuecomment-564262063 for an example (but maybe remove `--minimal`). You may also be interested in [`verify_fatal`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-fatal) and [`verify_dump`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-verify-dump).

If this answers your question could you close this issue? Thanks!

**Comment by axiqia** [comment]
@sitsofe Thank you for your kind and patient answers.
