### ISSUE TITLE
Is it possible to write to the second half of the device using --size flag? 

### ISSUE THREAD

**Issue by ghost** [axboe/fio#89]
I am trying to write one pattern to the half of the device and a different pattern to the other half. This is working fine with `--offset` option. However, I need to calculate the offset explicitly depending on my disk size.
To avoid this wondering if I can use `--size` flag on fio. 
I noticed that `--size=50%` is writing to the first 50% of the device. Since FIO already seem to be calculating the disk size and calculating 50% of it, Is it possible that we could tell the tool to write to the second half of the disk or start writing the size backwards ? Say something like `--size=-50%` or something?  
Please suggest.

**Comment by sitsofe** [comment]
Since fio-2.21 it should be possible to do this by using offset=50% size=50% . @sellerb5 can you confirm that this works for you and close this issue if so? Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
