### ISSUE TITLE
test failures with t0010-b7aae4ba.fio

### ISSUE THREAD

**Issue by vincentkfu** [axboe/fio#890]
Appveyor and Travis tests having been failing with t0010-b7aae4ba.fio:
```
# Expected result: fio runs and completes the job
# Buggy result: fio segfaults
#
[test]
ioengine=null
size=10g
io_submit_mode=offload
iodepth=16
```

Previously this only happened on Windows but there have been recent failures on other platforms. Failures occurring on multiple platforms suggests that there is a genuine problem.

- Windows failures (both x86 and x64)
  - https://ci.appveyor.com/project/axboe/fio/builds/29724441/job/5yc42vujc3y46r5b
  - https://ci.appveyor.com/project/axboe/fio/builds/29704848/job/4n6fq1rct22d70y3
  - https://ci.appveyor.com/project/axboe/fio/builds/29643383/job/lswsoca5laxj7vw6
  - https://ci.appveyor.com/project/vincentkfu/fio/builds/29688203/job/nc776ub9dt43w3qw
  - https://ci.appveyor.com/project/vincentkfu/fio/builds/29578210/job/vj083pvj5nma9q9k
  - https://ci.appveyor.com/project/vincentkfu/fio/builds/29342164/job/43q67r342g6wyd1f
- macOS failures
  -  https://travis-ci.org/axboe/fio/jobs/631746909
  - https://travis-ci.org/axboe/fio/jobs/635404562
- Linux failure
  - https://travis-ci.org/axboe/fio/jobs/633377483
  - https://travis-ci.org/axboe/fio/jobs/647005719

**Comment by vincentkfu** [comment]
The AppVeyor builds run configure with the --disable-native option, preventing the addition of march=native to CFLAGS. My own automated Windows builds typically do not run configure with --disable-native.

When I built fio *with* --disable-native, I saw one t0010 failure in 100 trials . Without --disable-native, I saw no failures in 100 trials.

disable-native  | march=native | Failures | Trials
---------------- | ------------ | -------- | ------
 yes | no | 1 | 100
 no | yes | 0 | 100

**Comment by bcran** [comment]
I'm running a set of tests now. So far 250 runs with no failures (built _with_ `--disable-native`).

**Comment by bcran** [comment]
I got a failure after a few hundred runs, which confirmed that I _can_ replicate the problem on my ThreadRipper system. I'll run a script overnight which runs fio via gdb.

**Comment by bcran** [comment]
It looks like it's getting to the end and hanging, waiting for threads to exit.

```
(gdb) info threads
  Id   Target Id           Frame
  1    Thread 21872.0x2bd8 0x00007ffa1d1dc744 in ntdll!ZwDelayExecution () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
* 2    Thread 21872.0xbdc  0x00007ffa1d1dc144 in ntdll!ZwWaitForSingleObject () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  3    Thread 21872.0x485c 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  4    Thread 21872.0x49bc 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  5    Thread 21872.0xa2c  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  6    Thread 21872.0x4db4 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  7    Thread 21872.0x5524 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  8    Thread 21872.0x48c8 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  9    Thread 21872.0x3cb8 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  10   Thread 21872.0x5554 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  11   Thread 21872.0x1d54 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  12   Thread 21872.0x52c8 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  13   Thread 21872.0x500c 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  14   Thread 21872.0x5f4  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  15   Thread 21872.0x59e0 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  16   Thread 21872.0x25a4 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  17   Thread 21872.0x4730 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  18   Thread 21872.0x14f0 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  19   Thread 21872.0x5190 0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
  20   Thread 21872.0x5030 0x00007ffa1d1dfad1 in ntdll!DbgBreakPoint () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
```
```
#0  0x00007ffa1d1dc744 in ntdll!ZwDelayExecution () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af56931 in SleepEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x0000000000492fb5 in usleep (useconds=10000) at os/windows/posix.c:632
#3  0x00000000004374fd in do_usleep (usecs=10000) at backend.c:2141
#4  0x000000000047492f in run_threads (sk_out=0x0) at backend.c:2460
#5  0x000000000043bf57 in fio_backend (sk_out=0x0) at backend.c:2513
#6  0x000000000046578b in main (argc=2, argv=0x213c0, envp=0x24340) at fio.c:60
```
``
#0  0x00007ffa1d1dc144 in ntdll!ZwWaitForSingleObject () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa198882ed in ?? () from /cygdrive/c/Windows/system32/mswsock.dll
#2  0x00007ffa1988f07a in Tcpip4_WSHGetWildcardSockaddr () from /cygdrive/c/Windows/system32/mswsock.dll
#3  0x00007ffa1c401f7c in select () from /cygdrive/c/Windows/System32/WS2_32.dll
#4  0x000000000045ab4d in helper_thread_main (data=0x1382290) at helper_thread.c:179
#5  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#6  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#7  0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#8  0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#9  0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#10 0x0000000000000000 in ?? ()

```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4e72fad0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x259c, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x259c, nointerrupt=0, timeout=4294967295, cs=0x94baf10, val=0x94baf38) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x9a04280) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x0000000000497904 in workqueue_init (td=0x99c0000, wq=0x9a04208, ops=0x5ae7e0 <rated_wq_ops>, max_workers=16, sk_out=0x0) at workqueue.c:359
#8  0x0000000000470f67 in rate_submit_init (td=0x99c0000, sk_out=0x0) at rate-submit.c:286
#9  0x0000000000491139 in thread_main (data=0x4e1fb720) at backend.c:1751
#10 0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#11 0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#12 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#13 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#14 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#15 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4e92fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2590, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2590, nointerrupt=0, timeout=4294967295, cs=0x94ba190, val=0x94ba1b8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x1382318) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x1382310) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4eb2fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x257c, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x257c, nointerrupt=0, timeout=4294967295, cs=0x94bb8d0, val=0x94bb8f8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x1382368) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x1382360) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4ed2fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2578, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2578, nointerrupt=0, timeout=4294967295, cs=0x94ba850, val=0x94ba878) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x13823b8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x13823b0) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4ef2fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2548, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2548, nointerrupt=0, timeout=4294967295, cs=0x94bbc90, val=0x94bbcb8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x1382408) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x1382400) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4f12fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2534, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2534, nointerrupt=0, timeout=4294967295, cs=0x94bafd0, val=0x94baff8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x1382458) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x1382450) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4f32fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2530, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2530, nointerrupt=0, timeout=4294967295, cs=0x94bbbd0, val=0x94bbbf8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x13824a8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x13824a0) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```

```
#0  0x00007ffa1d1dcc14 in ntdll!ZwWaitForMultipleObjects () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#1  0x00007ffa1af68027 in WaitForMultipleObjectsEx () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#2  0x00007ffa1af67f0e in WaitForMultipleObjects () from /cygdrive/c/Windows/System32/KERNELBASE.dll
#3  0x000000000040b946 in _pthread_wait_for_multiple_objects (count=count@entry=2, handles=handles@entry=0x4f52fca0, all=all@entry=0, timeout=timeout@entry=4294967295)
    at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/misc.c:136
#4  0x000000000040a9f9 in do_sema_b_wait_intern (sema=0x2504, nointerrupt=0, timeout=4294967295) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:647
#5  0x000000000040ad10 in do_sema_b_wait (sema=0x2504, nointerrupt=0, timeout=4294967295, cs=0x94bb5d0, val=0x94bb5f8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:606
#6  0x000000000040b2ca in pthread_cond_wait (c=<optimized out>, external_mutex=0x13824f8) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/cond.c:461
#7  0x00000000004972e6 in worker_thread (data=0x13824f0) at workqueue.c:194
#8  0x000000000040d8e4 in pthread_create_wrapper (args=0x0) at /usr/src/debug/mingw64-x86_64-winpthreads-7.0.0-1/src/thread.c:1499
#9  0x00007ffa1cf1b04a in msvcrt!_beginthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#10 0x00007ffa1cf1b11c in msvcrt!_endthreadex () from /cygdrive/c/Windows/System32/msvcrt.dll
#11 0x00007ffa1b207bd4 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x00007ffa1d1aced1 in ntdll!RtlUserThreadStart () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x0000000000000000 in ?? ()
```
...

**Comment by sitsofe** [comment]
@bcran is this one still here with the latest fio? I know @bvanassche fixed up one issue in https://github.com/axboe/fio/commit/3d86aaaa12eb95934a1f9e9303008ff958da66c5 ...

**Comment by vincentkfu** [comment]
Since this test only fails occasionally I have been waiting for more test passes before declaring victory, but things are looking good so far.

**Comment by bvanassche** [comment]
A candidate fix for the hang is available in https://github.com/axboe/fio/pull/1061.
