### ISSUE TITLE
Use correct github formats

### ISSUE THREAD

**Issue by Ornias1993** [axboe/fio#892]
It would be amazing if this repo would actually use the formatting for contribution guidelines, Issue templates (including requirements) and PR templates.

Instead of blaming people for not digging through the files in the repository to find out someone dropped all sorts of documentation there.

Creating a readme file that doesn't burn out eyes on github is also super awesome, btw.

**Comment by axboe** [comment]
I'll happily take pull requests for improvements, as I have done for decades.

> Instead of blaming people for not digging through the files in the repository to find out someone dropped all sorts of documentation there.

But what I will not tolerate is attitude on something that is provided 100% free of charge. There was no blame in my response to your request, I simply stated what should go into a good bug report. That is in no way specific to this project, ANY good bug report should include those things. If you want to get something fixed that you deem a bug, then the least you could do is provide all the necessary information, especially when kindly requested to do so.

**Comment by Ornias1993** [comment]
> But what I will not tolerate is attitude on something that is provided 100% free of charge

I think we agree there.
I didn't expect to be scoffed at after filling a bug that, in my opinion, was easy to repeat. Seems it wasnt that easy, sure. But people make mistakes.

> here was no blame in my response to your request

I think you might want a language coach or something, because you sounded pretty agressive to me... sorry for the misunderstanding!

> That is in no way specific to this project, ANY good bug report should include those things

Again the attitude, I FORGOT TO INCLUDE SOMETHING. DUDE. >.<

> then the least you could do is provide all the necessary information, especially when kindly requested to do so.

WHICH I DID, yes I ommitted some info and tryed to ammend as fast as possible. I'm not super human.

**Comment by axboe** [comment]
I need a language coach? I think you need some serious introspection and a thirty thousand feet view of the whole thing. You are the one looking for help and support. Can’t believe I have to say this. 

Don’t bother opening further issues, my life is too busy and too short to have to be subjected to this kind of behavior. I’ll repeat what I said before, in more than two decades of open source I’ve never had a worse case.

**Comment by Ornias1993** [comment]
I don't know if you noticed, but this was writhen before I suggested to burry the hatchet. 

Anyhow: I didn't actually expected you to fix it, I just wanted to report it in general and also don't expected nor requested help or support... 

If someone (it might be you, it might not be you, it might be me) wanted to fix the bug I report, I'm happy with it, if not... well, I cant force anyone to work for free nor can I expect it.

I think we both think the other is an asshole, which is fine.
What I do not find acceptable is closing issues because it contains attitude or arguments. A bug report or pull request is not more or less valid depending on the attitude of the one submitting the issue.

There are a lot of great and less-great people with hellish-shitty attitudes in OSS, who all contribute to the best of their ability. Hiding (possibly valid) issues/reports because you have a problem with someones attitude, is unacceptable.

For you, i'm just another rando who has an attitude and expects things
For me, you're just another kernel guy from linux with an attitude and issues with selfreflection.

We are never going to be friends, I get it. But you should be more focussed about what is said and less about how it's said... you know, there are assholes that have good contributions at times.
