### ISSUE TITLE
fio fails with "windows error 58 not handled" (io_u error)

### ISSUE THREAD

**Issue by vinitagnihotri** [axboe/fio#898]
Hi,
I am running a workload from windows client to linux based storage server over SMB.
Job consists of 29 files with size 64k and block size=4k, verify data=yes

Some times this fio fails with following error:

fio: windows error 58 not handled
fio: io_u error on file sequencial_write.14.0: Input/output error: write offset=4096, buflen=4096

What is meaning of this error? I checked all logs at linux server and I could not see any I/O error on system logs or SMB logs as well.

Can anyone please point out what issue is?

**Comment by sitsofe** [comment]
@vinitagnihotri 52 is `ERROR_BAD_NET_RESP` according to https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499- ...

**Comment by sitsofe** [comment]
Based on the above, it sounds like it is an error sent by the SMB server to the client. You would have to check there as to how it could occur (there seem to be various reasons if you search for ) but it's not an issue in fio. Given that could you close the issue here? Thanks!

**Comment by vinitagnihotri** [comment]
Thank you for the input, SMB side logs are showing said offset to be successful.
We also run small, large file IOs, random, sequential etc. Not sure why this happens.
Closing issue as windows:58 is now known.
