### ISSUE TITLE
POSIX_FADV_WILLNEED mode?

### ISSUE THREAD

**Issue by macdice** [axboe/fio#911]
Hi,

Do you think it would be useful to have a mode that would issue posix_fadvise(WILLNEED) n reads ahead, using a small queue, to test advise-based random I/O concurrency?  Here is a small rather hackish program that shows what I mean:

https://github.com/macdice/some-io-tests

This can be used to answer some of the sorts of questions you can see in the README there.  I could potentially try to write a patch, or maybe others have ideas about how best to do that.

Thanks!

**Comment by sitsofe** [comment]
@macdice I think this is essentially a different way to attempt what was described in the [readahead issue](https://github.com/axboe/fio/issues/780) and would have to overcome similar obstacles...

If someone submits an intelligent patch to fio that avoid the pitfalls mentioned in that issue we can always review it but I don't think it makes sense to keep this issue open until that point (of course Jens may disagree :-).

**Comment by axboe** [comment]
This does indeed run into the exact same things that I mentioned in the readahead issue. Your test program basically does:

for each n ios
    read_ahead

for each n ios
    read

and there's on easy way to do that in fio. Only idea I have there is similar to engines/sync.c for the vsync engine, where IO isn't really issued, only when ->commit() is called. The following logic might work:

- When ->queue() is invoked, call WILLNEED for that range
- When N IOs are already pending, or ->commit() is called, do the actual reads

That would essentially get you the behavior you are looking for. But not sure how much value there is in it, we have several async IO options that would be more appropriate.

**Comment by sitsofe** [comment]
Closing because no one is working on this one but if someone wants to please send a patch!
