### ISSUE TITLE
Windows physical drive regression

### ISSUE THREAD

**Issue by maciejsszmigiero** [axboe/fio#916]
Current master exits with the following error on Windows when run against a whole physical drive (that is, with something like `filename=\\.\PhysicalDrive1`):
```
fio-3.17
Starting 4 threads
CreateDirectoryA = 123
fio: failed to create dir (\\.): 2
CreateDirectoryA = 123
fio: failed to create dir (\\.): 2
CreateDirectoryA = 123
fio: failed to create dir (\\.): 2
CreateDirectoryA = 123
fio: failed to create dir (\\.): 2


Run status group 0 (all jobs):
```

It seems that this may be caused by commit df18600fd06258b96ae6f6b530ecdff541c2a82d ("filesetup: fix directory creation issues").
Before this commit fio would skip directory creation for absolute paths and also when I patch a fio binary to skip the whole create_work_dirs() function it actually runs fine.

**Comment by maciejsszmigiero** [comment]
Ping @Gt3pccb @sitsofe

**Comment by sitsofe** [comment]
According to https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499- error 123 is `ERROR_INVALID_NAME`. Sigh.

**Comment by maciejsszmigiero** [comment]
IMHO, we should just skip the whole directory creation thing for paths that begin with `\\.\` or `\\?\` on Windows.

**Comment by sitsofe** [comment]
> IMHO, we should just skip the whole directory creation thing for paths that begin with `\\.\` or `\\?\` on Windows.

Hmm that would be straightforward enough (but note it won't take care of double backslash collapsing). I was wondering if we could check the full path first but that won't be much better than what we have so likely a bunch of `strcmp`s (yuk) is as it good as it gets. I'd guess we'd need `\\.`, `\\.\`, `\\?` and `\\?\`...

**Comment by Prabhu088** [comment]
@maciejsszmigiero Please could you let me know what patch you used to fix the issue? Also, can you share the patch?

**Comment by sitsofe** [comment]
@Prabhu088 I've actually been working on this for the past few hours. The initial patch was easy:
```
diff --git a/os/os-windows.h b/os/os-windows.h
index 6d48ffe8..91447051 100644
--- a/os/os-windows.h
+++ b/os/os-windows.h
@@ -201,8 +201,14 @@ static inline int fio_mkdir(const char *path, mode_t mode) {
                errno = EEXIST;
                return -1;
        }
+       log_err("dwAttr = %d\n", dwAttr);

        if (CreateDirectoryA(path, NULL) == 0) {
+               /* Ignore errors if path is a namespace */
+               if (strcmp(path, "\\\\.") == 0 ) {
+                       errno = EEXIST;
+                       return -1;
+               }
                log_err("CreateDirectoryA = %d\n", GetLastError());
                errno = win_to_posix_error(GetLastError());
                return -1;
```
(but fix the broken tabs and you can throw away the debugging).

Unfortunately as I was debugging I found an extra complication because intermediate components of Windows UNC (`\\MSEDGEWIN10\Users\IEUser\Documents\Share`) and namespace (`\\?\C:\Windows\Temp\fio.tmp`) paths "don't exist" when you check them via `GetFileAttributesA()` (and of course `stat()` on Windows can't even cope with the full paths that `GetFileAttributesA()` can...). I think the only thing you can do is find the maximum existing path first and then make directories from there up...

**Comment by maciejsszmigiero** [comment]
> Please could you let me know what patch you used to fix the issue?

Didn't do any source patch, just patched a fio binary to skip the whole create_work_dirs() function.

**Comment by sitsofe** [comment]
OK https://github.com/sitsofe/fio/commit/f52b164322f92784898c946644789c754ff1ba4a tries to patch this and more. Any better?

**Comment by Prabhu088** [comment]
Thanks @sitsofe and @maciejsszmigiero. I will give a try with latest code.

**Comment by maciejsszmigiero** [comment]
I've checked the 7273058c66b82508c5935f8c59c382db225383ae AppVeyor build against a whole physical drive and can confirm that it now runs fine.

Thanks!
