### ISSUE TITLE
Windows package for fio 3.17

### ISSUE THREAD

**Issue by edwintorok** [axboe/fio#919]
fio-3.17 has an [important fix](https://github.com/axboe/fio/pull/859/commits/38ca5f03add887d9b7fa371fecd535c624a3031a) for Windows that is required to make queue-depth>1 work with newly created files. 
Previuosly newly created files would always be limited to queue-depth 1 on writes (see https://github.com/axboe/fio/issues/833), which caused fio to give different answers when using a new filename, and when reusing an existing filename, which causes quote a bit of confusion.

The latest release on https://bsdio.com/fio/ is still 3.16, please make a 3.17 release available for windows.

Apologies if this is the wrong place to request this, I couldn't find a contact e-mail address on bsdio.com

P.S. I know I can find the latest build from master here: https://ci.appveyor.com/project/axboe/fio/build/job/n7wwheatmju7loah/artifacts, but I'd prefer to use a released version for benchmarking.

**Comment by axboe** [comment]
Can't you just find the artifacts associated with the release tag? In any case, I'm going to release 3.18 today, so that's probably a better target.

**Comment by vincentkfu** [comment]
@bcran maintains bsdio.com

**Comment by bcran** [comment]
Unfortunately fio-3.17 doesn't build on Windows. I have installers ready to be uploaded to bsdio.com for code after 3.17, but at that point it's no better than the builds from appveyor.com

I'll build 3.18 installers when Jens tags it later today.

**Comment by bcran** [comment]
I've just uploaded Windows packages for fio 3.18 to https://bsdio.com/fio/

**Comment by edwintorok** [comment]
Thank you very much for the quick turnaround!
