### ISSUE TITLE
fio build issue

### ISSUE THREAD

**Issue by Octorocka** [axboe/fio#924]
I am running into build issues when trying to run fio on a baremetal server. This particular version is contained within perfkitbenchmarker, but it is following the build instructions as follows
git clone https://github.com/axboe/fio.git /opt/pkb/fio
cd /opt/pkb/fio && git checkout fio-2.17
./configure && make
STDOUT: Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no

Static build                  no
Wordsize                      64
zlib                          yes
Linux AIO support             yes
POSIX AIO support             yes
POSIX AIO support needs -lrt  yes
POSIX AIO fsync               yes
Solaris AIO support           no
__sync_fetch_and_add          yes
libverbs                      no
rdmacm                        no
Linux fallocate               yes
POSIX fadvise                 yes
POSIX fallocate               yes
sched_setaffinity(3 arg)      yes
sched_setaffinity(2 arg)      no
clock_gettime                 yes
CLOCK_MONOTONIC               yes
CLOCK_MONOTONIC_RAW           yes
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     yes
sync_file_range               yes
EXT4 move extent              yes
Linux splice(2)               yes
GUASI                         no
Fusion-io atomic engine       no
libnuma                       no
strsep                        yes
strcasestr                    yes
strlcat                       no
getopt_long_only()            yes
inet_aton                     yes
socklen_t                     yes
__thread                      yes
RUSAGE_THREAD                 yes
SCHED_IDLE                    yes
TCP_NODELAY                   yes
Net engine window_size        yes
TCP_MAXSEG                    yes
RLIMIT_MEMLOCK                yes
pwritev/preadv                yes
pwritev2/preadv2              yes
IPv6 helpers                  yes
Rados Block Device engine     no
rbd blkin tracing             no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           yes
libpmem                       no
libpmemblk                    no
NVML pmemblk engine           no
NVML dev-dax engine           no
lex/yacc for arithmetic       no
getmntent                     yes
getmntinfo                    no
Static Assert                 yes
bool                          yes
march_armv8_a_crc_crypto      no
    CC crc/crc16.o
    CC crc/sha512.o
    CC crc/crc7.o
    CC crc/sha1.o
    CC crc/crc32c.o
    CC crc/crc32c-arm64.o
    CC crc/crc32.o
    CC crc/murmur3.o
    CC crc/crc32c-intel.o
    CC crc/xxhash.o
    CC crc/test.o

STDERR: Warning: Permanently added '192.168.5.59' (ECDSA) to the list of known hosts.^M
FIO_VERSION = fio-2.17
In file included from crc/../os/os.h:33,
                 from crc/../thread_options.h:5,
                 from crc/../fio.h:18,
                 from crc/test.c:5:
crc/../os/os-linux.h:119:19: error: static declaration of gettid follows non-static declaration
  119 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from crc/../fio.h:12,
                 from crc/test.c:5:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of gettid was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make: *** [Makefile:318: crc/test.o] Error 1

The server is using Ubuntu 19.04 with a 5.3.0-29-generic kernel. gcc version is gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008.

**Comment by axboe** [comment]
2.17 is more than three years old. The backstory here is that libc finally included gettid(), for decades they did not. Hence you run into issues. Just upgrade to a recent version instead.
