### ISSUE TITLE
Feature request: Add eta & elapsed seconds to JSON output

### ISSUE THREAD

**Issue by apexearth** [axboe/fio#93]
Can we add the eta data to the JSON output?

Something like: 
https://github.com/apexearth/fio/commit/b01af66b13f0594617602b61d31b1495292e5fd2

**Comment by axboe** [comment]
Looks fine to me. Though it only makes sense to include ETA for rolling output instead of final output, I don't think it's a big enough deal to warrant any specific handling in that regard.
