### ISSUE TITLE
FIO verify fails on rand_seed during verification.

### ISSUE THREAD

**Issue by Seth5141** [axboe/fio#930]
Hi @sitsofe, I believe I have hit another instance of the verification issue from #740, #746 and #844.

My repro case is specifically using the fio plugin in SPDK, but a lot of the features are the same.

Here is my FIO configuration file: 

~~~
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
enable_sgl=1
time_based=1
ramp_time=0
runtime=2
iodepth=128
rw=randrw
bs=16k
verify=md5

[test]
numjobs=1
~~~

The key parts here are that it's a verify workload and I am doing randrw. I also tested with time_based=0 (and removed runtime) and got the same result.

I see an error log that looks similar to this:
~~~
verify: bad header rand_seed 861870971629624068, wanted 3851527457205462216 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 12566528, length 16384 (requested block: offset=12566528, length=16384)
...
verify: bad header rand_seed 1084641059188417035, wanted 9388557979107351970 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 37355520, length 16384 (requested block: offset=37355520, length=16384)
fio: pid=45142, err=84/file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character
~~~

I found that this error occurred on fio versions > 3.3 (specifically I tested 3.15, 3.18, and master). I did a little digging and found that verifysort wsa removed from the thread data object somewhere between 3.3 and 3.15. Previously verifysort was enabled by default so I believe it masked this issue.

I verified that when I add verify_backlog into my workload this issue disappears.
I also found something interesting. When the SPDK NVMe driver runs out of nvme request objects, it returns FIO_Q_BUSY from the ioengine_ops queue function. I noticed that when I increase the number of NVMe requests allocated in SPDK to the point where I never return FIO_Q_BUSY, the verification issues also disappear which is reminiscent of #844.

I am not familiar enough with the inner workings of the fio verify engine to make complete sense of this, but it seems that there is some sort of issue with replaying the verify_state variable when IO is  re-queued before being submitted.

Please let me know if you need any more details about my configuration.

Thanks!

**Comment by sitsofe** [comment]
Hi @Seth5141,

I'd really have to see a debug=io log to fully understand this one. Something that springs to mind is that if the the "file" is small you can end up issuing reads for regions that are being written which may fool fio into thinking that it is safe to verify that data when it really isn't (see https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-serialize-overlap ). How big was the file you were working with (I'm assuming it's dramatically bigger than 2 megabytes)?

Also I see you are using runtime= so are you talking about split verification (where you write the I/O with one distinct job and then try and verify it with another job)?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
