### ISSUE TITLE
riscv support

### ISSUE THREAD

**Issue by kirana1996** [axboe/fio#936]
hi,
i need this benchmark in riscv architecture,it is possible to port..

thanks,

**Comment by sitsofe** [comment]
@kirana1996 what doesn't work? The only parts that I could think of that might need some work (assuming Linux):
- `arch.h` (and by extension the creation of something like `arch-riscv.h` for a better barrier, nop and anything arch specific)
: https://github.com/axboe/fio/blob/bfed648c9dae6a2459cb43f55c14d8303dcec07b/arch/arch.h
- Syscalls: https://github.com/axboe/fio/blob/master/os/os-linux-syscall.h

As I don't have RISC-V machine to test on would you be able to try your hand at providing a tested patch?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
