### ISSUE TITLE
The different parameter order cause the different laying out IO files size

### ISSUE THREAD

**Issue by homerl** [axboe/fio#944]
Hi 
     The same values in fio1.cfg and fio2.cfg.   
     The parameter order cause laying out different sizes.   

CentOS 7   
Fio version 3.7   
      Does it bug ? thanks.

the same parameters values. 
```
fio1.cfg
size=1G
nrfiles=512
numjobs=64

fio2.cfg
filesize=1G
numjobs=64
nrfiles=512
```
`fio1 is fio1: Laying out IO files (512 files / total 1024MiB)`
`fio2 is fio2: Laying out IO files (512 files / total 524288MiB)`

```
$ cat fio1.cfg
[fio1]
rw=rw
ioengine=posixaio
size=1G
nrfiles=512
group_reporting
timeout=$timeout
bssplit=1M/100
directory=/mnt
numjobs=64

$  fio fio.cfg
fio1: (g=0): rw=rw, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=posixaio, iodepth=1
...
fio-3.7
Starting 64 processes
fio1: Laying out IO files (512 files / total 1024MiB)
```

The another config
```bash
$ cat fio2.cfg
[fio2]
rw=rw
bssplit=1M/100
directory=/mnt
ioengine=posixaio
filesize=1G
numjobs=64
nrfiles=512

$ fio fio2.cfg
fio2: (g=0): rw=rw, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=posixaio, iodepth=1
...
fio-3.7
Starting 64 processes
fio2: Laying out IO files (512 files / total 524288MiB)
```

**Comment by axboe** [comment]
size=X sets the total size to X, hence if you have Y files, each file will be X/Y in size, and the total size will still be X.

filesize=X sets each file to size X, hence when you then do nrfiles=Y, then the total size would be the same as if you had set size=X*Y.

Hope that explains it.

**Comment by homerl** [comment]
@axboe Thank you.  Got it.
