### ISSUE TITLE
Illegal instruction on an intel Denverton board

### ISSUE THREAD

**Issue by 2005songliwei** [axboe/fio#946]
$ fio --help
Illegal instruction

reproduce on an intel Denverton board, not all Intel board meet this issue
if compile with --disable-optimizations, the issue gone.

**Comment by sitsofe** [comment]
@2005songliwei are you using a pre-built fio? If so and it **wasn't** configured with `--disable-native` then it will be built using instructions optimal for the **build** machine. If you then try and run the binary on a older architecture than that of the build machine which doesn't support those instructions, then you will have illegal instruction errors (as the CPU doesn't know how to run that code).

Put another way: if you are distributing an fio binary and you don't know for sure that the target architecture where the binary will be run is equal or better than that of the build machine then make sure you are doing `./configure --disable-native` so the binary supports the minimal architecture for that platform. You can see Linux distros taking this approach (e.g. https://salsa.debian.org/debian/fio/-/commit/fabce846a3c843b20e9c2bcee3729c7ef645f12e )...

**Comment by 2005songliwei** [comment]
Thanks for your input, and yes, we are using a pre-built fio, it works with --disable-native option
but I'm a little confusing, if we config with --disable-native, what optimal instructions will be used?
just a minimal optimal instruction set will be used for one arch(eg. x86)?
take x86 for example, if I build fio with --disable-native, it can run on most of the CPU like skylake,
haswell, and it only contain the common optimal instruction can be used by both skylake and haswell, if I want it include haswell specific optimizations, then I need remove --disable-native and
build it on an haswell machine, right?
with --disable-native may have a low performance than without it on some specific CPU if the build machine and runing fio machine are same?
Anyway --disable-native already solve my issue. but look forward to your comment.
Thanks again.

**Comment by axboe** [comment]
Shouldn't be a huge impact with --disable-native, it'll still compile fio with -O3 and other optimizations, just not set the specific architecture type.

**Comment by 2005songliwei** [comment]
understand, thanks for your help.

**Comment by sitsofe** [comment]
@2005songliwei:

> if I want it include haswell specific optimizations, then I need remove --disable-native and
build it on an haswell machine, right?

That would be one way. The other way would be to use `--disable-native '--extra-cflags=-march=haswell'` on ANY (even older than haswell!) x86_64 build machine but as @axboe stated the impact won't be huge.
