### ISSUE TITLE
Minimum loops

### ISSUE THREAD

**Issue by aaronknister** [axboe/fio#949]
I'm curious if this is possible today with fio, or if such a feature would be accepted.

I'd like to be able to have fio run at least one iteration/loop of the workload but if additional runtime remains the execute additional loops.

I was thinking of an option named minimum_loops which when used with the time_based parameter will guarantee that at least one loop/iteration of the workload completes even if it exceeds runtime. If more than one workload completes then we keep looping until runtime is exhausted.

-Aaron

**Comment by sitsofe** [comment]
@aaronknister I'd imagine such a feature would be accepted via a patch.

My only suggestion is whether you want to introduce a different parameter (e.g. `looping_criteria`) which takes parameters like `min_loops,min_time` etc (maybe min_ios in the future). which changes how the traditional criteria are interpreted...

Thoughts?

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
