### ISSUE TITLE
ETA in shell does not show progress when outputformat Json or Json+

### ISSUE THREAD

**Issue by Gt3pccb** [axboe/fio#951]
Using 3.19 and using when outputformat Json or Json+ the shell shows no progress

 Jobs: 2 (f=0): [/(2)][-.-%][eta 02m:30s]

I tried 
" --eta=always --eta-interval=1 --status-interval=5"
" --eta=always --eta-interval=1"
" --eta=auto"
with similar results.
thanks

**Comment by sitsofe** [comment]
I think this is by design otherwise the eta output would interfere with the JSON output (see https://github.com/axboe/fio/blob/4ee9c375b64de236356cc97843d84978edeba491/eta.c#L396 )...

**Comment by Gt3pccb** [comment]
Thanks.
