### ISSUE TITLE
FIO support for Tape devices

### ISSUE THREAD

**Issue by saaraj** [axboe/fio#965]
I'm looking for FIO support with Tape devices . Is it possible to run FIO test on tape devices [where sequential load  of data along with file marker based metadata  needs to be managed].
Incase if the tape devices are not supported in FIO, looking for some help/documentation which help me  to tune FIO to support I/O on tape devices.

**Comment by sitsofe** [comment]
Hi @saaraj,

I don't think fio can support tape drives easily as it expects devices to be able to arbitrarily seek (which means regular ioengines only work with block devices). This suggests you would need unless you write your own ioengine (e.g. see https://github.com/axboe/fio/tree/master/engines ) at a minimum and try and map what fio wants to do to character device calls. If you still wanted to adapt `fio` you can take a look at the changes that were involved to do the zone block device work (see https://github.com/axboe/fio/search?p=1&q=zbd&type=Commits ).

You may find a different project like dt (https://github.com/RobinTMiller/dt ) is easier to adapt to your needs...

**Comment by sitsofe** [comment]
Closing this issue because we haven't heard back from @saaraj .
