### ISSUE TITLE
error: unknown field ‘XXX’ specified in initializer in json.h

### ISSUE THREAD

**Issue by changliwei** [axboe/fio#966]
when make gets some errors
make 
    CC crc/crc16.o
    CC crc/crc32.o
    CC crc/crc32c-arm64.o
    CC crc/crc32c-intel.o
    CC crc/crc32c.o
    CC crc/crc64.o
    CC crc/crc7.o
    CC crc/fnv.o
    CC crc/md5.o
    CC crc/murmur3.o
    CC crc/sha1.o
    CC crc/sha256.o
    CC crc/sha3.o
    CC crc/sha512.o
    CC crc/test.o
    CC crc/xxhash.o
    CC lib/axmap.o
    CC lib/bloom.o
    CC lib/flist_sort.o
    CC lib/gauss.o
    CC lib/getrusage.o
    CC lib/hweight.o
    CC lib/ieee754.o
    CC lib/lfsr.o
    CC lib/memalign.o
    CC lib/memcpy.o
    CC lib/mountcheck.o
    CC lib/num2str.o
    CC lib/output_buffer.o
    CC lib/pattern.o
    CC lib/prio_tree.o
    CC lib/rand.o
    CC lib/rbtree.o
    CC lib/strntol.o
    CC lib/zipf.o
    CC gettime.o
In file included from stat.h:7,
                 from thread_options.h:7,
                 from fio.h:18,
                 from gettime.c:7:
json.h: In function ‘json_object_add_value_int’:
json.h:60: error: unknown field ‘integer_number’ specified in initializer
json.h:60: warning: missing braces around initializer
json.h:60: warning: (near initialization for ‘arg.<anonymous>’)
json.h: In function ‘json_object_add_value_float’:
json.h:71: error: unknown field ‘float_number’ specified in initializer
json.h:71: warning: missing braces around initializer
json.h:71: warning: (near initialization for ‘arg.<anonymous>’)
json.h: In function ‘json_object_add_value_string’:
json.h:83: error: unknown field ‘string’ specified in initializer
json.h:83: warning: missing braces around initializer
json.h:83: warning: (near initialization for ‘arg.<anonymous>’)
json.h:83: warning: initialization makes integer from pointer without a cast
json.h: In function ‘json_object_add_value_object’:
json.h:95: error: unknown field ‘object’ specified in initializer
json.h:95: warning: missing braces around initializer
json.h:95: warning: (near initialization for ‘arg.<anonymous>’)
json.h:95: warning: initialization makes integer from pointer without a cast
json.h: In function ‘json_object_add_value_array’:
json.h:107: error: unknown field ‘array’ specified in initializer
json.h:107: warning: missing braces around initializer
json.h:107: warning: (near initialization for ‘arg.<anonymous>’)
json.h:107: warning: initialization makes integer from pointer without a cast
json.h: In function ‘json_array_add_value_int’:
json.h:121: error: unknown field ‘integer_number’ specified in initializer
json.h:121: warning: missing braces around initializer
json.h:121: warning: (near initialization for ‘arg.<anonymous>’)
json.h: In function ‘json_array_add_value_float’:
json.h:132: error: unknown field ‘float_number’ specified in initializer
json.h:132: warning: missing braces around initializer
json.h:132: warning: (near initialization for ‘arg.<anonymous>’)
json.h: In function ‘json_array_add_value_string’:
json.h:143: error: unknown field ‘string’ specified in initializer
json.h:143: warning: missing braces around initializer
json.h:143: warning: (near initialization for ‘arg.<anonymous>’)
json.h:143: warning: initialization makes integer from pointer without a cast
json.h: In function ‘json_array_add_value_object’:
json.h:154: error: unknown field ‘object’ specified in initializer
json.h:154: warning: missing braces around initializer
json.h:154: warning: (near initialization for ‘arg.<anonymous>’)
json.h:154: warning: initialization makes integer from pointer without a cast
json.h: In function ‘json_array_add_value_array’:
json.h:165: error: unknown field ‘array’ specified in initializer
json.h:165: warning: missing braces around initializer
json.h:165: warning: (near initialization for ‘arg.<anonymous>’)
json.h:165: warning: initialization makes integer from pointer without a cast
make: *** [gettime.o] Error 1

**Comment by changliwei** [comment]
version 3.19 witch configure
`Operating system              Linux
CPU                           x86_64
Big endian                    no
Compiler                      gcc
Cross compile                 no

Static build                  no
Wordsize                      64
zlib                          yes
Linux AIO support             yes
Linux AIO over io_uring       no
POSIX AIO support             yes
POSIX AIO support needs -lrt  yes
POSIX AIO fsync               yes
POSIX pshared support         yes
pthread_condattr_setclock()   yes
pthread_sigmask()             yes
Solaris AIO support           no
__sync_fetch_and_add          yes
__sync_synchronize            yes
__sync_val_compare_and_swap   yes
libverbs                      no
rdmacm                        no
asprintf()                    yes
vasprintf()                   yes
Linux fallocate               yes
POSIX fadvise                 yes
POSIX fallocate               yes
sched_setaffinity(3 arg)      yes
sched_setaffinity(2 arg)      no
clock_gettime                 yes
CLOCK_MONOTONIC               yes
CLOCK_MONOTONIC_RAW           yes
CLOCK_MONOTONIC_PRECISE       no
clockid_t                     yes
gettimeofday                  yes
fdatasync                     yes
pipe()                        yes
pipe2()                       yes
pread()                       yes
sync_file_range               yes
EXT4 move extent              yes
Linux splice(2)               yes
GUASI                         no
libnuma                       yes
libnuma v2                    yes
strsep                        yes
strcasestr                    yes
strlcat                       no
getopt_long_only()            yes
inet_aton                     yes
socklen_t                     yes
__thread                      yes
RUSAGE_THREAD                 yes
SCHED_IDLE                    yes
TCP_NODELAY                   yes
Net engine window_size        yes
TCP_MAXSEG                    yes
RLIMIT_MEMLOCK                yes
pwritev/preadv                yes
pwritev2/preadv2              no
IPv6 helpers                  yes
http engine                   no
Rados engine                  no
Rados Block Device engine     no
setvbuf                       yes
Gluster API engine            no
s390_z196_facilities          no
HDFS engine                   no
MTD                           yes
libpmem                       no
libpmemblk                    no
PMDK pmemblk engine           no
PMDK dev-dax engine           no
PMDK libpmem engine           no
DDN's Infinite Memory Engine  no
iscsi engine                  no
NBD engine                    no
lex/yacc for arithmetic       yes
getmntent                     yes
getmntinfo                    no
Static Assert                 no
bool                          yes
strndup                       yes
Valgrind headers              no
Zoned block device support    no
march_armv8_a_crc_crypto      no
cuda                          no
Build march=native            no
CUnit                         no
__kernel_rwf_t                no
-Wimplicit-fallthrough        no
MADV_HUGEPAGE                 no
gettid                        no
statx(2)/libc                 no
statx(2)/syscall              no
TCMalloc support              no`

**Comment by axboe** [comment]
What compiler are you using?

**Comment by axboe** [comment]
Pushed a fix for this.
