### ISSUE TITLE
The --rate option cannot support values above 4G

### ISSUE THREAD

**Issue by sbates130272** [axboe/fio#976]
While root-causing #975 we determined that the --rate option cannot handle values over 4G. In high performant systems (like those containing several NVMe SSDs) this is not that big of a value. Consider moving --rate to FIO_OPT_ULL to increase the values it can support.

**Comment by sitsofe** [comment]
Closing as a duplicate of #716 (I think all the rate options will suffer this flaw)...

(@sbates130272 any chance you could cook up a patch for this one?)

**Comment by sbates130272** [comment]
Thanks @sitsofe! I concur this is a duplicate of #716 and I will look at a patch for that.
