### ISSUE TITLE
fio-2.0.13 randread write_iops_log doesn't show the full detail information

### ISSUE THREAD

**Issue by cliicy** [axboe/fio#978]
os:
CentOS release 6.9 (Final)
2.6.32-696.el6.x86_64

command line:
fio --group_reporting --thread --time_based --name 1_64_128k_randread --ioengine=libaio --direct=1 --log_avg_msec=1000 --write_iops_log=randread.fio --size=100G --runtime=5m --filename=/dev/sfdv0n1 --numjobs=1 --iodepth=64 --bs=128k --rw=randread --output=randread.fio.report

result:
fio successfully finished after running 5 minutes but the iops_log file: randread.fio only shows 34 seconds details:
1000, 20169, 0, 0
2000, 23896, 0, 0
3000, 23631, 0, 0
4000, 23684, 0, 0
5000, 23703, 0, 0
6000, 23729, 0, 0
7001, 23757, 0, 0
8001, 23762, 0, 0
9001, 23768, 0, 0
10001, 23762, 0, 0
11001, 23769, 0, 0
12001, 23764, 0, 0
13001, 23771, 0, 0
14001, 23767, 0, 0
15001, 23770, 0, 0
16002, 23767, 0, 0
17002, 23771, 0, 0
18002, 23771, 0, 0
19002, 23766, 0, 0
20002, 23770, 0, 0
21002, 23773, 0, 0
22003, 23772, 0, 0
23003, 23775, 0, 0
24003, 23764, 0, 0
25003, 23771, 0, 0
26003, 23770, 0, 0
27003, 23767, 0, 0
28004, 23770, 0, 0
29004, 23773, 0, 0
30004, 23775, 0, 0
31004, 23763, 0, 0
32004, 23772, 0, 0
33004, 23769, 0, 0
34005, 23768, 0, 0

and 1_64_128k_randwrite also has the similar problem.

**Comment by sitsofe** [comment]
We (upstream) only support the latest fio. See https://github.com/axboe/fio/releases for which version we're up to. Can you retest and see if you can reproduce the issue with such a version? Thanks!

**Comment by cliicy** [comment]
ok, the problem couldn't be reproduced with the latest fio version. close it.
