### ISSUE TITLE
./configure output an error

### ISSUE THREAD

**Issue by xiejunshi** [axboe/fio#979]
# FIO configure log Sun May 10 06:28:32 CST 2020
# Configured with: './configure'
#
gcc -D_GNU_SOURCE -include config-host.h -Werror-implicit-function-declaration -c -o /tmp/fio-conf-23605-10842-21849.o /tmp/fio-conf-20692-10842-14919.c
/tmp/fio-conf-20692-10842-14919.c:2:2: error: #error __ANDROID__ not defined
 #error __ANDROID__ not defined
  ^
gcc -D_GNU_SOURCE -include config-host.h -Werror-implicit-function-declaration -c -o /tmp/fio-conf-23605-10842-21849.o /tmp/fio-conf-20692-10842-14919.c
gcc -D_GNU_SOURCE -include config-host.h -Werror-implicit-function-declaration -c -o /tmp/fio-conf-23605-10842-21849.o /tmp/fio-conf-20692-10842-14919.c
/tmp/fio-conf-20692-10842-14919.c:2:2: error: #error __i386__ not defined
 #error __i386__ not defined
  ^
gcc -D_GNU_SOURCE -include config-host.h -Werror-implicit-function-declaration -c -o /tmp/fio-conf-23605-10842-21849.o /tmp/fio-conf-20692-10842-14919.c
Compiling test case cross
gcc -D_GNU_SOURCE -include config-host.h -Werror-implicit-function-declaration -o /tmp/fio-conf-29418-10842-3556.exe /tmp/fio-conf-20692-10842-14919.c
collect2: fatal error: cannot find 'ld'
compilation terminated.
~

**Comment by sitsofe** [comment]
@xiejunshi,

Um, you're not giving the folks you've posted this to much to go on - you're not compiling with a regular Linux distro toolchain (or it's very broken) is mostly what I deduce. Not even having a linker suggests a rather major environment setup issue on your end. A wild guess is that you're trying to [cross compile fio for Android](https://www.google.com/search?q=cross+compile+fio+for+Android) (based on the few words you highlighted) but who knows without more information...

I'm afraid what you've posted is not enough for anyone to help further unless you post FAR more context about what you're compiling for and how you went about it (e.g. environment variables you set and what you passed to` configure`). Can you least add that and the information requested in https://github.com/axboe/fio/blob/master/REPORTING-BUGS ? Thanks!

**Comment by sitsofe** [comment]
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!
