### ISSUE TITLE
Linux AIO support is no when cross compiling

### ISSUE THREAD

**Issue by yu-zou** [axboe/fio#986]
Sorry, I'm totally a newbie. So basically, I want to cross-compile fio to use it on an embedded system.

When I run: 
make CROSS_COMPILE=aarch64-linux-gnu-

Makefile:19: config-host.mak: No such file or directory
FIO_VERSION = fio-3.19-56-g3ac77
Running configure ...
Operating system              Linux
CPU                           arm64
Big endian                    no
Compiler                      aarch64-linux-gnu-gcc
Cross compile                 yes

Static build                  no
Wordsize                      64
zlib                          no
Linux AIO support             no
Linux AIO over io_uring       no
POSIX AIO support             yes
POSIX AIO support needs -lrt  yes
POSIX AIO fsync               yes

I was wondering how to enable AIO support?

**Comment by sitsofe** [comment]
@yu-zou Hi,

It means that in your build target environment the compiler can't find the libaio library so configure disabled Linux AIO support. I'm afraid I'm not an embedded developer so it's impossible for me to guess how (or even if!) you can get it short of building the libaio library yourself (and if that was easy way to get it then you would have already done it :-).

In big distros you can see you get it by installing the right package (https://github.com/axboe/fio/blob/723f9bc5fe77ae8bedc08ed3ec3a25426b48c096/README#L146 )...

(If you can, you will find it MUCH easier to do the build on your target machine. 64 bit ARM machines have more than enough power to build fio on themselves assuming you're using some sort of standard distro).

**Comment by yu-zou** [comment]
@sitsofe God, your suggestion saved my life! I compiled it directly on PetaLinux, and it can be used now. Thank you.
