### ISSUE TITLE
Ver 3.18 can't work on windows with path like --filename=\\.\PhysicalDrive0

### ISSUE THREAD

**Issue by Ax2401** [axboe/fio#994]
if pass --filename=\\.\PhysicalDrive0 to fio 3.18 on windows, it will output :

Starting 1 thread
**CreateDirectoryA = 123
fio: failed to create dir (\\.): 2**

ver 3.16 and 3.17 can work properly, but 3.18 not.

**Comment by vincentkfu** [comment]
This should be fixed in 3.19 by https://github.com/axboe/fio/pull/937

**Comment by sitsofe** [comment]
@Ax2401 Does fio 3.19 work for you and if so can you close this issue? Thanks!

**Comment by Ax2401** [comment]
@sitsofe   3.19 and 3.20 are all ok.  issue closed.
