### ISSUE TITLE
Add support for reading iolog from stdin

### ISSUE THREAD

**Issue by donny372** [axboe/fio#997]
If we want run a disk test for weeks, the iolog file gets very big and often doesn't fit on the boot drive. The ability to generate the iolog file and pipe it directly to fio via stdin would be very useful.

Do you think if this is a reasonable feature request? Does anyone can help with this? If not, we can work on this and upload a patch.

**Comment by sitsofe** [comment]
@donny372 It does sound reasonable although some work will need to be done to flag an error if someone also requests the job file or the file to be worked on to be stdin (see https://fio.readthedocs.io/en/latest/fio_man.html#running-fio and https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-filename ).

I've no plans to work on it but you were to work on a patch I (or others) can try and review it (if you don't get a response to patches feel free to ask again after a suitable period of silence).

**Comment by donny372** [comment]
Hi, @sitsofe, could you please take a look? https://github.com/axboe/fio/pull/1018
